### ISSUE TITLE
spack: cmake pass variable to compiler

### ISSUE THREAD

**Issue by thenitinshukla** [LLNL/spack#35993] opened 2023-03-10 15:48 UTC
### Steps to reproduce

```
def cmake_args(self):
        args = []
        rpath = self.rpath
        rpath.append(os.path.join(self.prefix.lib, “ecsim”))
        args.append(“-DIPIC_H5HUT_OUTPUT=ON”)
        args.append(“-DH5HUT_HOME=/path....”)
        args.append(“-DPARALLEL_IO=1")
 return args (edited) 
```

### Information on your system

but it does not append  when compiling the code

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2023-04-05 12:56
@nzeal Not sure I understand what the issue is, since the steps to reproduce aren't really "steps to reproduce". Closing for now, but feel free to reopen with more details.

**Closed as not planned by alalazo** 2023-04-05 12:56 UTC
Labels: bug, unreproducible
