### ISSUE TITLE
py-pymol  Error  1. Cannot select a single "version" for package "py-pymol"

### ISSUE THREAD

**Issue by pab42** [LLNL/spack#42823] opened 2024-02-23 14:36 UTC
### Steps to reproduce

```console
$ git checkout c47b554fa1fbbd4f4272a0c197d3f68d32c079b9
$ spack spec py-pymol
$ git checkout HEAD~1 
$ spack spec py-pymol
```

### Error message

```console
$ spack --debug --stacktrace spec py-pymol
lib/spack/spack/cmd/__init__.py:123 ==> [2024-02-23-15:18:55.185125] Imported spec from built-in commands
lib/spack/spack/cmd/__init__.py:123 ==> [2024-02-23-15:18:55.185894] Imported spec from built-in commands
lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.188390] Reading config from file /scratch/spack/etc/spack/defaults/config.yaml
scratch/spack/lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.215692] Reading config from file /scratch/spack/etc/spack/defaults/bootstrap.yaml
scratch/spack/lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.226431] Reading config from file /scratch/spack/etc/spack/defaults/repos.yaml
scratch/spack/lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.230797] Reading config from file /scratch/spack/etc/spack/defaults/config.yaml
scratch/spack/lib/spack/spack/database.py:391 ==> [2024-02-23-15:18:55.252794] DATABASE LOCK TIMEOUT: 60s
scratch/spack/lib/spack/spack/database.py:397 ==> [2024-02-23-15:18:55.253000] PACKAGE LOCK TIMEOUT: No timeout
scratch/spack/lib/spack/spack/database.py:391 ==> [2024-02-23-15:18:55.253528] DATABASE LOCK TIMEOUT: 60s
scratch/spack/lib/spack/spack/database.py:397 ==> [2024-02-23-15:18:55.253743] PACKAGE LOCK TIMEOUT: No timeout
scratch/spack/lib/spack/spack/bootstrap/config.py:125 ==> [2024-02-23-15:18:55.253954] [BOOTSTRAP CONFIG SCOPE] name=_builtin
scratch/spack/lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.254453] Reading config from file /scratch/spack/etc/spack/defaults/bootstrap.yaml
scratch/spack/lib/spack/spack/bootstrap/config.py:138 ==> [2024-02-23-15:18:55.261801] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/scratch/spack/etc/spack/defaults
scratch/spack/lib/spack/spack/bootstrap/config.py:139 ==> [2024-02-23-15:18:55.261986] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/scratch/spack/etc/spack/defaults/linux
scratch/spack/lib/spack/spack/bootstrap/config.py:138 ==> [2024-02-23-15:18:55.262169] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/spack/.spack/bootstrap/config
scratch/spack/lib/spack/spack/bootstrap/config.py:139 ==> [2024-02-23-15:18:55.262342] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/spack/.spack/bootstrap/config/linux
scratch/spack/lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.262933] Reading config from file /home/spack/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap/_common.py:223 ==> [2024-02-23-15:18:55.301043] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.301743] Reading config from file /scratch/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/_common.py:185 ==> [2024-02-23-15:18:55.314432] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.404889] Reading config from file /scratch/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.519560] Reading config from file /scratch/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.621485] Reading config from file /scratch/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.634312] Reading config from file /scratch/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/bootstrap/_common.py:223 ==> [2024-02-23-15:18:55.676317] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
lib/spack/spack/bootstrap/_common.py:223 ==> [2024-02-23-15:18:55.678948] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap/core.py:376 ==> [2024-02-23-15:18:55.679123] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/bootstrap/_common.py:78 ==> [2024-02-23-15:18:55.704803] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.9/gqcctd2ejbgvyvyt4umqpetfoogfycwu" provides the "clingo" Python module
lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.705256] Reading config from file /scratch/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.711424] Reading config from file /scratch/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.780049] Reading config from file /scratch/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.813559] Reading config from file /scratch/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:55.835668] Reading config from file /scratch/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/util/web.py:345 ==> [2024-02-23-15:18:55.837533] Checking existence of https://mirror.spack.io/build_cache/index.json
lib/spack/spack/util/web.py:373 ==> [2024-02-23-15:18:56.488880] Failure reading URL: HTTP Error 404: Not Found
lib/spack/spack/config.py:996 ==> [2024-02-23-15:18:58.639131] Reading config from file /home/spack/.spack/linux/compilers.yaml
lib/spack/spack/main.py:1021 ==> [2024-02-23-15:19:13.216278] SpackError: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "py-pymol"
lib/spack/spack/error.py:54 ==> [2024-02-23-15:19:13.216773] Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "py-pymol"
Traceback (most recent call last):
  File "/scratch/spack/lib/spack/spack/cmd/__init__.py", line 220, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/scratch/spack/lib/spack/spack/spec.py", line 2905, in concretize
    self._new_concretize(tests)
  File "/scratch/spack/lib/spack/spack/spec.py", line 2880, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/scratch/spack/lib/spack/spack/solver/asp.py", line 2721, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/scratch/spack/lib/spack/spack/solver/asp.py", line 817, in solve
    error_handler.raise_if_errors()
  File "/scratch/spack/lib/spack/spack/solver/asp.py", line 651, in raise_if_errors
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "py-pymol"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/spack/lib/spack/spack/main.py", line 1018, in main
    return _main(argv)
  File "/scratch/spack/lib/spack/spack/main.py", line 973, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/scratch/spack/lib/spack/spack/main.py", line 1001, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/scratch/spack/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
  File "/scratch/spack/lib/spack/spack/cmd/spec.py", line 106, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/scratch/spack/lib/spack/spack/cmd/__init__.py", line 234, in parse_specs
    raise spack.error.SpackError(msg) from e
spack.error.SpackError: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "py-pymol"
 ```

The error message is related to #39530 and was apparently introduced by #37575 and is caused by the lines
```console
    depends_on("python+tkinter@2.7:", type=("build", "link", "run"), when="@2.3.0:2.4.0")
    depends_on("python+tkinter@3.6:", type=("build", "link", "run"), when="@2.5.0:")
```
I think it might be caused by `python+tkinter@2.7:` as it refers to python@2 which is no longer available. I am not sure if this should be fixed in the `py-pymol` package.py or somewhere else.

### Information on your system

```
* **Spack:** 0.20.0.dev0 (c47b554fa1fbbd4f4272a0c197d3f68d32c079b9)
* **Python:** 3.9.5
* **Platform:** linux-sles15-haswell
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by pab42** [comment] 2024-02-23 14:53
OK, it does not seem to be related to python2.

**Comment by cryingmyth** [comment] 2024-02-24 03:10
i encountered the same problem as u, but i was running  it on WSL2

**Comment by adamjstewart** [comment] 2024-02-25 13:37
Duplicate of #41146, I suggest we close this and discuss further there.

**Comment by alalazo** [comment] 2024-03-07 11:26
Duplicate of #41146

**Closed as not planned** 2024-03-07 11:27 UTC
Labels: bug, duplicate, triage
