### ISSUE TITLE
Installation issue: hdf5 failure with zlib - its looking for /usr/lib64/libz.a [and not the one installed by spack?]

### ISSUE THREAD

**Issue by balay** [LLNL/spack#46610] opened 2024-09-27 15:38 UTC
### Steps to reproduce the issue

```console
balay@al:~/spack$ ./bin/spack spec -I hdf5
Input spec
--------------------------------
 -   hdf5

Concretized
--------------------------------
 -   hdf5@1.14.3%gcc@14.2.1~cxx~fortran~hl~ipo~java~map+mpi+shared~subfiling~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make patches=82088c8 arch=linux-fedora40-aarch64
[+]      ^cmake@3.30.2%gcc@14.2.1~doc+ncurses+ownlibs build_system=generic build_type=Release patches=dbc3892 arch=linux-fedora40-aarch64
[+]          ^curl@8.8.0%gcc@14.2.1~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-fedora40-aarch64
[+]              ^nghttp2@1.63.0%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]                  ^diffutils@3.10%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]              ^openssl@3.3.1%gcc@14.2.1~docs+shared build_system=generic certs=mozilla arch=linux-fedora40-aarch64
[+]                  ^ca-certificates-mozilla@2023-05-30%gcc@14.2.1 build_system=generic arch=linux-fedora40-aarch64
[+]          ^ncurses@6.5%gcc@14.2.1~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-fedora40-aarch64
[+]      ^gcc-runtime@14.2.1%gcc@14.2.1 build_system=generic arch=linux-fedora40-aarch64
[e]      ^glibc@2.39%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]      ^gmake@4.4.1%gcc@14.2.1~guile build_system=generic arch=linux-fedora40-aarch64
[+]      ^openmpi@5.0.5%gcc@14.2.1+atomics~cuda~debug~gpfs~internal-hwloc~internal-libevent~internal-pmix~java~lustre~memchecker~openshmem~romio+rsh~static+vt+wrapper-rpath build_system=autotools fabrics=none romio-filesystem=none schedulers=none arch=linux-fedora40-aarch64
[+]          ^autoconf@2.72%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]              ^m4@1.4.19%gcc@14.2.1+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-fedora40-aarch64
[+]                  ^libsigsegv@2.14%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]          ^automake@1.16.5%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]          ^gnuconfig@2022-09-17%gcc@14.2.1 build_system=generic arch=linux-fedora40-aarch64
[+]          ^hwloc@2.11.1%gcc@14.2.1~cairo~cuda~gl~libudev+libxml2~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-fedora40-aarch64
[+]              ^libpciaccess@0.17%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]                  ^util-macros@1.20.1%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]              ^libxml2@2.10.3%gcc@14.2.1+pic~python+shared build_system=autotools arch=linux-fedora40-aarch64
[+]                  ^libiconv@1.17%gcc@14.2.1 build_system=autotools libs=shared,static arch=linux-fedora40-aarch64
[+]                  ^xz@5.4.6%gcc@14.2.1~pic build_system=autotools libs=shared,static arch=linux-fedora40-aarch64
[+]          ^libevent@2.1.12%gcc@14.2.1+openssl build_system=autotools arch=linux-fedora40-aarch64
[+]          ^libtool@2.4.7%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]              ^findutils@4.9.0%gcc@14.2.1 build_system=autotools patches=440b954 arch=linux-fedora40-aarch64
[+]          ^numactl@2.0.18%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]          ^openssh@9.8p1%gcc@14.2.1+gssapi build_system=autotools arch=linux-fedora40-aarch64
[+]              ^krb5@1.21.2%gcc@14.2.1+shared build_system=autotools arch=linux-fedora40-aarch64
[+]                  ^bison@3.8.2%gcc@14.2.1~color build_system=autotools arch=linux-fedora40-aarch64
[+]                  ^gettext@0.22.5%gcc@14.2.1+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-fedora40-aarch64
[+]                      ^tar@1.34%gcc@14.2.1 build_system=autotools zip=pigz arch=linux-fedora40-aarch64
[+]                          ^pigz@2.8%gcc@14.2.1 build_system=makefile arch=linux-fedora40-aarch64
[+]                          ^zstd@1.5.6%gcc@14.2.1+programs build_system=makefile compression=none libs=shared,static arch=linux-fedora40-aarch64
[+]              ^libedit@3.1-20240808%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]              ^libxcrypt@4.4.35%gcc@14.2.1~obsolete_api build_system=autotools patches=4885da3 arch=linux-fedora40-aarch64
[+]          ^perl@5.40.0%gcc@14.2.1+cpanm+opcode+open+shared+threads build_system=generic arch=linux-fedora40-aarch64
[+]              ^berkeley-db@18.1.40%gcc@14.2.1+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-fedora40-aarch64
[+]              ^bzip2@1.0.8%gcc@14.2.1~debug~pic+shared build_system=generic arch=linux-fedora40-aarch64
[+]              ^gdbm@1.23%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]                  ^readline@8.2%gcc@14.2.1 build_system=autotools patches=bbf97f1 arch=linux-fedora40-aarch64
[+]          ^pmix@5.0.3%gcc@14.2.1~munge~python~restful build_system=autotools arch=linux-fedora40-aarch64
[+]      ^pkgconf@2.2.0%gcc@14.2.1 build_system=autotools arch=linux-fedora40-aarch64
[+]      ^zlib-ng@2.2.1%gcc@14.2.1+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-fedora40-aarch64

```

### Error message

<details><summary>Error message</summary>

<pre>
-- Looking for MPI_Type_size_x - found
CMake Error at /usr/lib64/cmake/ZLIB/ZLIB.cmake:81 (message):
  The imported target "ZLIB::zlibstatic" references the file

     "/usr/lib64/libz.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib64/cmake/ZLIB/ZLIB.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib64/cmake/ZLIB/zlib-config.cmake:44 (include)
  CMakeFilters.cmake:77 (find_package)
  CMakeLists.txt:852 (include)

-- Configuring incomplete, errors occurred!

</pre></details>

### Information on your system

```console
balay@al:~/spack$ ./bin/spack debug report
* **Spack:** 0.23.0.dev0 (00fae6dd79f40dc322b3c1149f7460f527f83d44)
* **Python:** 3.12.6
* **Platform:** linux-fedora40-aarch64
```

### Additional information

[spack-build-env.txt](https://github.com/user-attachments/files/17166464/spack-build-env.txt)
[spack-build-out.txt](https://github.com/user-attachments/files/17166465/spack-build-out.txt)

cc: @brtnfld  @byrnHDF  @gheber @hyoklee  @lkurz  @lrknox

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by hyoklee** [comment] 2024-09-27 16:39
I think zlib-ng is the problem:

https://forum.hdfgroup.org/t/usage-of-non-system-zlib/12690

Can you try a few different variants of zlib-ng package? (e.g., ipo, new_strategies, opt, etc.)

**Comment by balay** [comment] 2024-09-27 19:27
Well the issue persists with `spack install hdf5 ^zlib`

And changing ` new_strategies, opt` with `zlib-ng` didn't make a difference.

**Comment by balay** [comment] 2024-09-27 19:28
I have a successful build with both `zlib` and `zlib-ng`  with https://github.com/spack/spack/pull/46612

**Comment by hyoklee** [comment] 2024-09-27 19:34
@balay , thanks for the patch! I approved it.

**Comment by BenWibking** [comment] 2024-09-28 01:16
This issue is a duplicate of https://github.com/spack/spack/issues/46035.

**Comment by hyoklee** [comment] 2024-09-28 01:28
I think it happens on aarch64 only. Am I observing the issue correctly?

**Comment by BenWibking** [comment] 2024-09-28 01:37
The Apple M1 is an aarch64 platform.

**Comment by hyoklee** [comment] 2024-09-28 01:54
I run spack CI testing on develop branch regularly on macos-latest, which is arm64 nowadays for GitHub:
 
https://github.com/hdfeos/hdf5/actions/runs/11036251085/job/30654240525

I guess the next release (1.14.5) will fix the problem.

You can also try develop branch yourself following

https://github.com/hdfeos/hdf5/actions/runs/11036251085/workflow

Please note that I'm using h5py to test hdf5 spack package.

**Comment by BenWibking** [comment] 2024-09-28 02:02
My issue has nothing to do with macOS. It is Linux on aarch64.

I just wanted to point out that this issue was a duplicate, since usually OSS projects use the first report of an issue to track further updates/fixes, although I'm not sure what Spack prefers to do in this case.

**Comment by balay** [comment] 2024-09-28 03:07
Ah - sorry I must have messed up my search for duplicate issues

This issue is not aarch64 specific. It also occurs on:
```
* **Platform:** linux-fedora40-skylake
```

[spack-build-out.txt](https://github.com/user-attachments/files/17172059/spack-build-out.txt)

My workaround was to just install  "/usr/lib64/libz.a" so that the spack install could succeeded..

**Comment by BenWibking** [comment] 2024-09-28 22:58
Thanks for the tip. Since Fedora provides that file via the `zlib-ng-compat-static` package, I installed it via dnf and it works now.

Seems like an HDF5 build/packaging issue to me.

**Comment by BenWibking** [comment] 2024-09-28 23:20
Actually, it might be a more generic CMake issue. I saw a similar problem when trying to build VTK on macOS awhile ago, which led (in part) to this PR (but it was never merged): https://github.com/spack/spack/pull/41661

Would be interesting to know if this fixed the issue here. I am not able to test it immediately.

**Comment by hyoklee** [comment] 2024-09-30 00:19
@BenWibking , I agree. It might be something else.

For example, I can't reproduce the error on [Aarch64 Ubuntu 24.04](https://github.com/hyoklee/actions/actions/runs/11094985973/workflow):

```
2024-09-29T20:26:50.8611870Z -- ... disable color and URL extended diagnostic messages
2024-09-29T20:26:51.1077985Z -- ....All Warnings are enabled
2024-09-29T20:26:51.3115123Z -- Could NOT find ZLIB (missing: ZLIB_DIR)
2024-09-29T20:26:51.4977589Z -- Found ZLIB: /home/runner/work/actions/actions/spack/opt/spack/linux-ubuntu24.04-aarch64/gcc-13.2.0/zlib-ng-2.2.1-e3mhknuzqwmjaxjack64hzukwfrn2eff/lib/libz.so (found version "1.3.1")  
2024-09-29T20:26:52.3231123Z -- Filter PLUGIN file is /
2024-09-29T20:26:53.7959347Z -- Configuring done (453.5s)
2024-09-29T20:27:00.0558577Z -- Generating done (5.1s)
2024-09-29T20:27:00.1531460Z CMake Warning:
2024-09-29T20:27:00.1617581Z   Manually-specified variables were not used by the project:
2024-09-29T20:27:00.1623102Z 
2024-09-29T20:27:00.1629948Z     ALLOW_UNSUPPORTED
2024-09-29T20:27:00.1637108Z     CMAKE_POLICY_DEFAULT_CMP0090
2024-09-29T20:27:00.1644608Z 
2024-09-29T20:27:00.1653119Z 
2024-09-29T20:27:00.1667336Z -- Build files have been written to: /tmp/root/spack-stage/spack-stage-hdf5-1.14.3-3yus7wbjlzzuth26dyk6245ienbqq3jy/spack-build-3yus7wb
2024-09-29T20:27:00.3156213Z [1;34m==>[0m hdf5: Executing phase: 'build'
2024-09-29T20:27:00.3308635Z [0;32m==>[0m [2024-09-29-20:27:00.328035] 'make' '-j4'
2024-09-29T20:27:00.4235048Z /usr/bin/cmake -S/tmp/root/spack-stage/spack-stage-hdf5-1.14.3-3yus7wbjlzzuth26dyk6245ienbqq3jy/spack-src -B/tmp/root/spack-stage/spack-stage-hdf5-1.14.3-3yus7wbjlzzuth26dyk6245ienbqq3jy/spack-build-3yus7wb --check-build-system CMakeFiles/Makefile.cmake 0
2024-09-29T20:27:00.6364210Z /usr/bin/cmake -E cmake_progress_start /tmp/root/spack-stage/spack-stage-hdf5-1.14.3-3yus7wbjlzzuth26dyk6245ienbqq3jy/spack-build-3yus7wb/CMakeFiles /tmp/root/spack-stage/spack-stage-hdf5-1.14.3-3yus7wbjlzzuth26dyk6245ienbqq3jy/spack-build-3yus7wb//CMakeFiles/progress.marks
2024-09-29T20:27:00.7611976Z /usr/bin/make  -f CMakeFiles/Makefile2 all
```

I tested `spack install hdf5~mpi`.

**Comment by BenWibking** [comment] 2024-09-30 01:46
Maybe it has to do with the system packages or paths in Fedora vs Ubuntu?

**Comment by balay** [comment] 2024-09-30 03:26
> CMake Error at /usr/lib64/cmake/ZLIB/ZLIB.cmake:81 (message):

My guess is - cmake defauts to preferring such cmake config files over actual check for the pkg in its search PATH.

Since spack does not install an equivalent `ZLIB.cmake` to over-ride it - cmake goes and picks and uses this system file.

```
balay@al:~$ ls -l /usr/lib64/cmake/
total 0
drwxr-xr-x. 2 root root 128 Sep 27 09:09 cblas-3.12.0
drwxr-xr-x. 2 root root 136 Sep 27 09:09 cblas64-3.12.0
drwxr-xr-x. 2 root root 140 Sep 27 09:09 cblas64_-3.12.0
drwxr-xr-x. 2 root root 132 Sep 27 09:09 lapack-3.12.0
drwxr-xr-x. 2 root root 140 Sep 27 09:09 lapack64-3.12.0
drwxr-xr-x. 2 root root 144 Sep 27 09:09 lapack64_-3.12.0
drwxr-xr-x. 2 root root 136 Sep 27 09:09 lapacke-3.12.0
drwxr-xr-x. 2 root root  36 Sep 27 09:08 openmp
drwxr-xr-x. 2 root root 108 Sep 27 23:42 ZLIB
```
I'm hoping there is a better way to tell hdf5 cmake the the correct ZLIB  to use - and not wander off checking the system installed one.

**Closed as completed** 2024-10-04 19:55 UTC
Labels: build-error, xSDK

**Comment by vkhodygo** [comment] 2026-05-21 16:36
I observe a similar issue while building `llvm`. Rocky10/OpenHPC

    spack install paraview@5.13.3 arch=linux-rocky10-haswell cppflags="-O2 -fPIC" %gcc@15
