### ISSUE TITLE
Installation issue: Stream (and other codes) with intel@19.1.1.217

### ISSUE THREAD

**Issue by ilbiondo** [LLNL/spack#17100] opened 2020-06-15 11:16 UTC
There appears to be a problem propagating the correct build environment to the compilers shipped with Intel Parallel Studio 2020 update 1

### Steps to reproduce the issue

The same problem occurs for a number of packages including netcdf-fortran and mumps. Stream is simply the fastest and simplest reproducer.

```console
$ spack install stream%intel@19.1.1.217
2 errors found in build log: 
     35    f77 -O2 -c stream.f
     36    f77 -O2 stream.o mysecond.o -o stream_f.exe
  >> 37    ld: /dcsrsoft/spack/external/intel/2020u1/compilers_and_libraries_2020.1.217/linux/bin/intel64/../../lib/LLVMgold.so: error loading plugin: libimf.so: cannot open shared object file: No such file or directory
  >> 38    make: *** [stream_f.exe] Error 1
```

The build works correctly with Intel@19.1.0.166 and also with a dirty build environment

```
$ spack install stream%intel@19.1.0.166
..
..
==> 172171: stream: Executing phase: 'edit'
==> 172171: stream: Executing phase: 'build'
==> 172171: stream: Executing phase: 'install'
==> 172171: stream: Successfully installed stre
```

```
$  spack load intel@19.1.1.217

$ spack install --dirty stream%intel@19.1.1.217
..
..
==> 172490: stream: Building stream [MakefilePackage]
==> 172490: stream: Executing phase: 'edit'
==> 172490: stream: Executing phase: 'build'
==> 172490: stream: Executing phase: 'install'
==> 172490: stream: Successfully installed stream
  Fetch: 0.03s.  Build: 1.02s.  Total: 1.06s.
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.13.3-2728-294ee67
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake_avx512
```

### Additional information

Adding the path to libimf in the icc.cfg doesn't help and it's not at all clear what has changed between the initial release of 2020 and update 1.

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by dev-zero** [comment] 2020-12-09 15:43
maybe a duplicate of #10308 ?
I had to specify a `modules` in my `compilers.yml` to get it to work, see https://github.com/spack/spack/issues/10308#issuecomment-716391950

**Closed as completed** 2021-09-03 06:07 UTC
Labels: build-error, intel
