### ISSUE TITLE
`spack install --test=root flux-sched` fails tests due to missing `py-cffi` but its dependency (flux-core) depends on py-cffi

### ISSUE THREAD

**Issue by grondo** [LLNL/spack#30167] opened 2022-04-19 16:36 UTC
### Steps to reproduce

I am trying to install and run tests on the flux-sched package, which depends on flux-core, but while the package can build fine without `--test=root` the `make check` fails, e.g.:

```console
$ spack install --test=root flux-sched
```

This command _should_ succeed (modulo real bugs or intermittent test failures), but instead fails when flux-core commands (e.g. `flux mini run`) are executed since they fail to find the Python cffi modules.

Another way to reproduce _might_ be to run

```console
$ spack  build-env flux-sched bash
$ flux mini run
```

Ostensibly, `flux mini run` should work (print a usage message anyway) in the build environment for flux-sched, since flux-sched `depends_on ("flux-core")` but here it fails:

```console
$ flux mini run
Traceback (most recent call last):
  File "/p/vast1/grondo/spack/opt/spack/linux-rhel7-broadwell/gcc-11.2.0/flux-core-0.37.0-2jiqtajoqsdzjlialanx7fxxvqvjkrfd/libexec/flux/cmd/flux-mini.py", line 27, in <module>
    import flux
  File "/p/vast1/grondo/spack/opt/spack/linux-rhel7-broadwell/gcc-11.2.0/flux-core-0.37.0-2jiqtajoqsdzjlialanx7fxxvqvjkrfd/lib/flux/python3.9/flux/__init__.py", line 14, in <module>
    import flux.core.handle
  File "/p/vast1/grondo/spack/opt/spack/linux-rhel7-broadwell/gcc-11.2.0/flux-core-0.37.0-2jiqtajoqsdzjlialanx7fxxvqvjkrfd/lib/flux/python3.9/flux/core/handle.py", line 16, in <module>
    from flux.future import Future
  File "/p/vast1/grondo/spack/opt/spack/linux-rhel7-broadwell/gcc-11.2.0/flux-core-0.37.0-2jiqtajoqsdzjlialanx7fxxvqvjkrfd/lib/flux/python3.9/flux/future.py", line 15, in <module>
    from flux.util import check_future_error, interruptible
  File "/p/vast1/grondo/spack/opt/spack/linux-rhel7-broadwell/gcc-11.2.0/flux-core-0.37.0-2jiqtajoqsdzjlialanx7fxxvqvjkrfd/lib/flux/python3.9/flux/util.py", line 27, in <module>
    from flux.core.inner import ffi, raw
  File "/p/vast1/grondo/spack/opt/spack/linux-rhel7-broadwell/gcc-11.2.0/flux-core-0.37.0-2jiqtajoqsdzjlialanx7fxxvqvjkrfd/lib/flux/python3.9/flux/core/inner.py", line 11, in <module>
    from _flux._core import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'
```

flux-core does properly depend on `py-cffi`:

```python
    depends_on("py-cffi@1.1:", type=('build', 'run'))
```

So I assume the above should work. 

### Error message

Hm, this is interesting and may be related, so I'll report it here:
```console
$ spack build-env flux-sched spack debug report
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002aaaaab16940 (most recent call first):
Aborted (core dumped)
```
:confused:

`spack debug report` works fine outside of `spack build-env flux-sched`, so I'm not sure how the package is confusing Python itself.

### Information on your system

* **Spack:** 0.18.0.dev0 (599f68d8fcf8880d65e93cc7eaf2d1607d807c4c)
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2024-05-21 16:14
Cannot reproduce anymore, closing:

![Screenshot from 2024-05-21 18-12-16](https://github.com/spack/spack/assets/4199709/7570a6f5-c657-4deb-a412-fc54bf06a984)

**Closed as not planned by alalazo** 2024-05-21 16:14 UTC
Labels: bug, tests, triage
