### ISSUE TITLE
'install_missing_compilers' Detected uninstalled dependency error

### ISSUE THREAD

**Issue by nicholas-sly** [LLNL/spack#16244] opened 2020-04-22 20:49 UTC
Spack errors on 'detected uninstalled dependency' error when trying to reinstall a stack where an external package was registered as having been built with a given compiler and the `package.py` file for that compiler changed since the previous build.

### Steps to reproduce the issue
1. Specify a dependency of a package to use an external package (e.g. Slurm or pkg-config%pgi).
2. Install a stack the installs the compiler as well as a dependency of the above external package.
3. Uninstall all packages from the stack
4. Modify the compiler's `package.py` file
5. Reinstall the stack

### Example Error Message
```
==> Error: Detected uninstalled dependencies for pkg-config: {'pgi'}
==> Error: Cannot proceed with pkg-config: 1 uninstalled dependency: pgi
```

### Information on your system

```
-bash-4.2$ spack debug report
* **Spack:** 0.14.2-700-395e91d
* **Python:** 3.6.8
* **Platform:** linux-rhel7-broadwell
```

Example external package specifications used.
```
    slurm:
      paths:
        slurm@19.05.5: /usr
      buildable: false
      version: []
      target: []
      compiler: []
      modules: {}
      providers: {}
    pkg-config:
      paths:
        pkg-config@0.27.1.system%pgi@19.10: /usr/bin
      buildable: true
      version: []
      target: []
      compiler: []
      modules: {}
      providers: {}
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by scheibelp** [comment] 2020-04-30 02:04
Can you add:

* The command you ran which produced the error message you got
* The output of that command when running with `-d` (`spack -d install...` or whichever command you were using)
* The modifications you made to any `package.py` files (you mentioned `pgi`, did you also modify `pkg-config`?)

Questions:

* Is step 4 required? Does everything proceed well up to that point?
* Is there a reason you set pkg-config as `buildable: True`? This means you want to allow Spack to build its own `pkg-config` if it desires to

Thanks!

**Comment by matthewcurry** [comment] 2020-05-05 03:39
Hi there,

I have hit this issue, as well, and it's pretty easy to reproduce. Here is my procedure:

1. Get a fresh checkout of Spack 0.14.2. Delete ~/.spack, get new shell for clean environment.
2. In spack tree, add the following as etc/spack/config.yaml:
```
config:
  install_missing_compilers: True
```
3. module purge
3. Load spack shell support (so I can get environments).
5. Create a spack.yaml with the following contents:
```
spack:
  specs:
    - openmpi@4.0.2%gcc@7.2.0
```
6. spack env create test spack.yaml
7. spack env activate test
8. spack concretize
```
==> Concretized openmpi@4.0.2%gcc@7.2.0
 -   ywtu2iw  openmpi@4.0.2%gcc@7.2.0~atomics~cuda~cxx~cxx_exceptions fabrics=none +gpfs~java~legacylaunchers~memchecker patches=073477a76bba780c67c36e959cd3ee6910743e2735c7e76850ffba6791d498e4 ~pmi+runpath schedulers=none ~sqlite3+static~thread_multiple+vt arch=linux-rhel7-thunderx2
 -   fo723o6      ^hwloc@1.11.11%gcc@7.2.0~cairo~cuda~gl+libxml2~netloc~nvml+pci+shared arch=linux-rhel7-thunderx2
 -   3rv633d          ^libpciaccess@0.13.5%gcc@7.2.0 arch=linux-rhel7-thunderx2
 -   55x7z6x              ^libtool@2.4.6%gcc@7.2.0 arch=linux-rhel7-thunderx2
 -   inyfuix                  ^m4@1.4.18%gcc@7.2.0 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-rhel7-thunderx2
 -   jd2yqae                      ^libsigsegv@2.12%gcc@7.2.0 arch=linux-rhel7-thunderx2
 -   zn67ndw              ^pkgconf@1.6.3%gcc@7.2.0 arch=linux-rhel7-thunderx2
 -   z3hvprx              ^util-macros@1.19.1%gcc@7.2.0 arch=linux-rhel7-thunderx2
 -   do7dlts          ^libxml2@2.9.10%gcc@7.2.0~python arch=linux-rhel7-thunderx2
 -   pqyofgx              ^libiconv@1.16%gcc@7.2.0 arch=linux-rhel7-thunderx2
 -   cqbbqaj              ^xz@5.2.5%gcc@7.2.0 arch=linux-rhel7-thunderx2
 -   ifes6d7              ^zlib@1.2.11%gcc@7.2.0+optimize+pic+shared arch=linux-rhel7-thunderx2
 -   s3eg6mv          ^numactl@2.0.12%gcc@7.2.0 arch=linux-rhel7-thunderx2
 -   bhiqo35              ^autoconf@2.69%gcc@7.2.0 arch=linux-rhel7-thunderx2
 -   xloe454                  ^perl@5.30.2%gcc@7.2.0+cpanm+shared+threads arch=linux-rhel7-thunderx2
 -   fjdwinj                      ^gdbm@1.18.1%gcc@7.2.0 arch=linux-rhel7-thunderx2
 -   krs5jkz                          ^readline@8.0%gcc@7.2.0 arch=linux-rhel7-thunderx2
 -   kv43kgk                              ^ncurses@6.2%gcc@7.2.0~symlinks+termlib arch=linux-rhel7-thunderx2
 -   idnnpx5              ^automake@1.16.2%gcc@7.2.0 arch=linux-rhel7-thunderx2
```
9. spack -d install, and wait for it to fail.
```
...
==> [2020-05-04-21:07:51.214663, 77282] 214272: gcc: Successfully installed gcc
  Fetch: 34.87s.  Build: 32m 32.43s.  Total: 33m 7.29s.
[+] /home/mlcurry/04-May-20/spack/opt/spack/linux-rhel7-thunderx2/gcc-4.8.5/gcc-7.2.0-uswg4thqokddr64eqai3h3l4kgvgcw5t
==> [2020-05-04-21:07:51.216813, 214272] WRITE LOCK (database): /home/mlcurry/04-May-20/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2020-05-04-21:07:51.218835, 214272] write locking [0:0]: timeout 3 sec
==> [2020-05-04-21:07:51.219801, 214272] WRITE LOCK (database): /home/mlcurry/04-May-20/spack/opt/spack/.spack-db/lock[0:0] [Acquired at 21:07:51.219733]
==> [2020-05-04-21:07:51.346116, 214272] WRITE LOCK (database): /home/mlcurry/04-May-20/spack/opt/spack/.spack-db/lock[0:0] [Releasing]
==> [2020-05-04-21:07:51.489769, 214272] WRITE LOCK (database): /home/mlcurry/04-May-20/spack/opt/spack/.spack-db/lock[0:0] [Released at 21:07:51.489694]
==> [2020-05-04-21:07:51.587433, 214272] '/home/mlcurry/04-May-20/spack/opt/spack/linux-rhel7-thunderx2/gcc-4.8.5/gcc-7.2.0-uswg4thqokddr64eqai3h3l4kgvgcw5t/bin/gfortran' '-dumpversion'
==> [2020-05-04-21:07:51.588892, 214272] '/home/mlcurry/04-May-20/spack/opt/spack/linux-rhel7-thunderx2/gcc-4.8.5/gcc-7.2.0-uswg4thqokddr64eqai3h3l4kgvgcw5t/bin/gfortran' '-dumpversion'
==> [2020-05-04-21:07:51.593108, 214272] '/home/mlcurry/04-May-20/spack/opt/spack/linux-rhel7-thunderx2/gcc-4.8.5/gcc-7.2.0-uswg4thqokddr64eqai3h3l4kgvgcw5t/bin/gfortran' '--version'
==> [2020-05-04-21:07:51.594633, 214272] '/home/mlcurry/04-May-20/spack/opt/spack/linux-rhel7-thunderx2/gcc-4.8.5/gcc-7.2.0-uswg4thqokddr64eqai3h3l4kgvgcw5t/bin/gfortran' '--version'
==> [2020-05-04-21:07:51.591639, 214272] '/home/mlcurry/04-May-20/spack/opt/spack/linux-rhel7-thunderx2/gcc-4.8.5/gcc-7.2.0-uswg4thqokddr64eqai3h3l4kgvgcw5t/bin/gcc' '--version'
==> [2020-05-04-21:07:51.590351, 214272] '/home/mlcurry/04-May-20/spack/opt/spack/linux-rhel7-thunderx2/gcc-4.8.5/gcc-7.2.0-uswg4thqokddr64eqai3h3l4kgvgcw5t/bin/g++' '--version'
==> [2020-05-04-21:07:51.638230, 214272] '/home/mlcurry/04-May-20/spack/opt/spack/linux-rhel7-thunderx2/gcc-4.8.5/gcc-7.2.0-uswg4thqokddr64eqai3h3l4kgvgcw5t/bin/gfortran' '-dumpfullversion'
==> [2020-05-04-21:07:51.628389, 214272] '/home/mlcurry/04-May-20/spack/opt/spack/linux-rhel7-thunderx2/gcc-4.8.5/gcc-7.2.0-uswg4thqokddr64eqai3h3l4kgvgcw5t/bin/gfortran' '-dumpfullversion'
==> [2020-05-04-21:07:51.664338, 214272] '/home/mlcurry/04-May-20/spack/opt/spack/linux-rhel7-thunderx2/gcc-4.8.5/gcc-7.2.0-uswg4thqokddr64eqai3h3l4kgvgcw5t/bin/gcc' '-dumpversion'
==> [2020-05-04-21:07:51.666093, 214272] '/home/mlcurry/04-May-20/spack/opt/spack/linux-rhel7-thunderx2/gcc-4.8.5/gcc-7.2.0-uswg4thqokddr64eqai3h3l4kgvgcw5t/bin/g++' '-dumpversion'
==> [2020-05-04-21:07:51.687433, 214272] '/home/mlcurry/04-May-20/spack/opt/spack/linux-rhel7-thunderx2/gcc-4.8.5/gcc-7.2.0-uswg4thqokddr64eqai3h3l4kgvgcw5t/bin/g++' '-dumpfullversion'
==> [2020-05-04-21:07:51.699082, 214272] '/home/mlcurry/04-May-20/spack/opt/spack/linux-rhel7-thunderx2/gcc-4.8.5/gcc-7.2.0-uswg4thqokddr64eqai3h3l4kgvgcw5t/bin/gcc' '-dumpfullversion'
==> [2020-05-04-21:07:51.712181, 214272] Couldn't get version for compiler /home/mlcurry/04-May-20/spack/opt/spack/linux-rhel7-thunderx2/gcc-4.8.5/gcc-7.2.0-uswg4thqokddr64eqai3h3l4kgvgcw5t/bin/gfortran
==> [2020-05-04-21:07:51.712459, 214272] Couldn't get version for compiler /home/mlcurry/04-May-20/spack/opt/spack/linux-rhel7-thunderx2/gcc-4.8.5/gcc-7.2.0-uswg4thqokddr64eqai3h3l4kgvgcw5t/bin/gfortran
==> [2020-05-04-21:07:51.732098, 214272] Flagging gcc as installed
==> [2020-05-04-21:07:51.732256, 214272] Removing gcc from libsigsegv's uninstalled dependencies.
==> [2020-05-04-21:07:51.732392, 214272] libsigsegv has no build task to update for gcc's success
==> [2020-05-04-21:07:51.732615, 214272] Downgrading to a read lock on gcc with timeout 1e-09
==> [2020-05-04-21:07:51.732768, 214272] WRITE LOCK (gcc): /home/mlcurry/04-May-20/spack/opt/spack/.spack-db/prefix_lock[5932990197472510748:1] [Downgrading]
==> [2020-05-04-21:07:51.732931, 214272] READ LOCK (gcc): /home/mlcurry/04-May-20/spack/opt/spack/.spack-db/prefix_lock[5932990197472510748:1] [Acquiring]
==> [2020-05-04-21:07:51.733070, 214272] read locking [5932990197472510748:1]: timeout 1e-09 sec
==> [2020-05-04-21:07:51.733775, 214272] READ LOCK (gcc): /home/mlcurry/04-May-20/spack/opt/spack/.spack-db/prefix_lock[5932990197472510748:1] [Downgraded at 21:07:51.733706]
==> [2020-05-04-21:07:51.734013, 214272] Error: Detected uninstalled dependencies for util-macros: {'gcc'}
==> [2020-05-04-21:07:51.734216, 214272] InstallError: Cannot proceed with util-macros: 1 uninstalled dependency: gcc
==> [2020-05-04-21:07:51.734344, 214272] Error: Cannot proceed with util-macros: 1 uninstalled dependency: gcc
Traceback (most recent call last):
  File "/home/mlcurry/04-May-20/spack/lib/spack/spack/main.py", line 760, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/mlcurry/04-May-20/spack/lib/spack/spack/main.py", line 488, in _invoke_command
    return_val = command(parser, args)
  File "/home/mlcurry/04-May-20/spack/lib/spack/spack/cmd/install.py", line 281, in install
    env.install_all(args)
  File "/home/mlcurry/04-May-20/spack/lib/spack/spack/environment.py", line 1211, in install_all
    self._install(spec, **kwargs)
  File "/home/mlcurry/04-May-20/spack/lib/spack/spack/environment.py", line 1169, in _install
    spec.package.do_install(**install_args)
  File "/home/mlcurry/04-May-20/spack/lib/spack/spack/package.py", line 1469, in do_install
    builder.install(**kwargs)
  File "/home/mlcurry/04-May-20/spack/lib/spack/spack/installer.py", line 1429, in install
    ','.join(task.uninstalled_deps)))
spack.installer.InstallError: Cannot proceed with util-macros: 1 uninstalled dependency: gcc
```

**Comment by scottwittenburg** [comment] 2020-05-13 05:01
I have also hit this error in the context of a compiler bootstrapping CI pipeline.  Some salient points:

- For the whole process, I'm in an environment defined by being in the directory containing the attached `spack.yaml` (renamed to `spack.yaml.txt` for github).
- I want to build a package using a compiler which is not already installed in my container
- So I configure a binary mirror where that compiler and all it's dependencies are already installed
- I use the `config` option 'install_missing_compilers` to tell spack to install the compiler I don't yet have
- I use a two-pass approach to install my package:
  1. `spack install --cache-only --only dependencies <path-to-my-concrete-spec.yaml>`
  2. `spack install --no-cache --only package <path-to-my-concrete-spec.yaml>`

After that first pass the compiler I want (and all it's deps) appear in the install tree.  But the result of the second pass is the same as the folks who reported above, e.g.:

```
Error: Cannot proceed with pkgconf: 1 uninstalled dependency: gcc
```

The compiler bootstrapping use-case is a little difficult to reproduce, not impossible to do outside of a gitlab runner, sort of painstaking and time-consuming.  I do have a bash script which can reproduce it in a locally running container, but it contains sensitive information that would normally be provided by gitlab via masked environment variables, so I don't want to paste that here necessarily.  If it seems really critical or useful to see that repro shell script, I can certainly remove the sensitive parts and paste it here.  I have attached a pipeline log showing the debug output in more detail, which corresponds to the summary I provided above.


[spack.yaml.txt](https://github.com/spack/spack/files/4622891/spack.yaml.txt)
[pipeline_log (82).txt](https://github.com/spack/spack/files/4619893/pipeline_log.82.txt)

**Comment by bdunlay** [comment] 2020-08-26 23:47
I am experiencing this issue on 0.15.4 when trying to build a dependent package that itself does not have a dependency on gcc: libbsd. Oddly enough, it fails saying it cannot proceed with libbsd because of an uninstalled dependency, gcc.

**Comment by cwsmith** [comment] 2021-02-19 12:33
I'm hitting the same problem in a spack 0.15.4 environment as described here: https://github.com/spack/spack/issues/16244#issuecomment-623820881

**Comment by alalazo** [comment] 2023-06-01 20:20
Duplicate of #15328

**Comment by haampie** [comment] 2024-11-01 09:40
The option was deprecated, closing this.

**Closed as completed by haampie** 2024-11-01 09:40 UTC
Labels: bug, triage
