### ISSUE TITLE
 Error: Bad characters in version string: 5.9.1-amdsos-build32-1+

### ISSUE THREAD

**Issue by vkallesh** [LLNL/spack#27552] opened 2021-11-19 15:20 UTC
### Steps to reproduce

I ran spack install gcc to install latest gcc and found instead of gcc installation, below message was observed:
Error: Bad characters in version string: 5.9.1-amdsos-build32-1+

### Error message

[spack_debug_stacktrace_output.txt](https://github.com/spack/spack/files/7571161/spack_debug_stacktrace_output.txt)

### Information on your system

* **Spack:** 0.17.0-216-c5aee4d9b4
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by vkallesh** [comment] 2021-12-01 06:08
This issue is not seen under 'develop' branch and not seen under 'releases/v0.17' branch

**Comment by alalazo** [comment] 2023-04-07 08:09
Closing, since v0.17 is not supported anymore and I can't reproduce anywhere else.

**Closed as not planned by alalazo** 2023-04-07 08:09 UTC
Labels: bug, triage
