### ISSUE TITLE
Installation issue: gcc

### ISSUE THREAD

**Issue by andymwood** [LLNL/spack#17556] opened 2020-07-16 12:56 UTC
Spack won't build gcc for me under OpenSUSE 15.1

### Steps to reproduce the issue

```console
$ spack install gcc
...
==> 5961: gcc: Building gcc [AutotoolsPackage]
==> 5961: gcc: Executing phase: 'autoreconf'
==> 5961: gcc: Executing phase: 'configure'
==> 5961: gcc: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j4'
...
              10.1.0-pidtewq6cymldvnvqgmdkwnv5zk6zrrm/spack-src/gcc/../libbacktrace -I/home/vagrant/spack/opt/spack/linux-opensuse_leap15-sandybridge/gcc-7.5.0/isl-0.21-s56ion4nr374zv2nlgn6lzxvbvn7sel5/include  -o cc1-checksum.o -MT cc1-
              checksum.o -MMD -MP -MF ./.deps/cc1-checksum.TPo cc1-checksum.c
  >> 12157    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lisl
  >> 12158    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lmpc
  >> 12159    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lmpfr
  >> 12160    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lisl
  >> 12161    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lmpc
  >> 12162    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lmpfr
  >> 12163    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lisl
  >> 12164    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lmpc
  >> 12165    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lmpfr
  >> 12166    collect2: error: ld returned 1 exit status
  >> 12167    make[3]: *** [/tmp/vagrant/spack-stage/spack-stage-gcc-10.1.0-pidtewq6cymldvnvqgmdkwnv5zk6zrrm/spack-src/gcc/lto/Make-lang.in:88: lto1] Error 1
...
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.15.1
* **Python:** 3.6.5
* **Platform:** linux-opensuse_leap15-sandybridge
```

compilers.yaml
```yaml
compilers:
- compiler:
    spec: gcc@7.5.0
    paths:
      cc: /usr/bin/gcc-7
      cxx: /usr/bin/g++-7
      f77:
      fc:
    flags: {}
    operating_system: opensuse_leap15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

### Additional information

* [spack-build-env.txt](https://github.com/spack/spack/files/4931545/spack-build-env.txt)
* [spack-build-out.txt](https://github.com/spack/spack/files/4931546/spack-build-out.txt)

@michaelkuhn

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by michaelkuhn** [comment] 2020-07-17 19:39
I noticed that GCC sometimes is using isl's `lib64` directory and (when it's failing) `lib`. Could you please check which of these actually exists within isl's directory (`spack location -i isl`)?

**Comment by michaelkuhn** [comment] 2020-07-17 19:41
Looks like this is a known problem: #10842, #2617

**Comment by andymwood** [comment] 2020-07-18 07:20
> I noticed that GCC sometimes is using isl's `lib64` directory and (when it's failing) `lib`. Could you please check which of these actually exists within isl's directory (`spack location -i isl`)?

```console
$ ls $(spack location -i isl)
include  lib64
```

I notice that the `-i` option for `spack location` is broken:
```console
$ spack location -h
  -i, --install-dir  install prefix for spec (spec need not be installed)
$ spack location -i gcc
==> Error: Spec 'gcc' matches no installed packages.
```

**Comment by andymwood** [comment] 2020-07-18 07:33
`SPACK_LINK_DIRS`, defined in `spack-build-env.txt` contains `/home/vagrant/spack/opt/spack/linux-opensuse_leap15-sandybridge/gcc-7.5.0/isl-0.21-s56ion4nr374zv2nlgn6lzxvbvn7sel5/lib64`.

But the failing command, in `spack-build-out.txt` contains `-L/home/vagrant/spack/opt/spack/linux-opensuse_leap15-sandybridge/gcc-7.5.0/isl-0.21-s56ion4nr374zv2nlgn6lzxvbvn7sel5/lib`.

Is there a simple work-around for this?

**Comment by andymwood** [comment] 2020-07-18 07:42
> Is there a simple work-around for this?

I'm trying this now. I'll report back when it finishes:
```console
spack install --only dependencies gcc
find spack -type d -name lib64 -execdir ln -s lib64 lib \;
spack install gcc
```

**Comment by andymwood** [comment] 2020-07-18 08:59
It worked.

**Comment by michaelkuhn** [comment] 2020-08-18 13:27
@andymwood Sorry for the delay. Could you give #18150 a try?

**Comment by alalazo** [comment] 2020-08-20 07:06
I can definitely reproduce this issue on the latest OpenSUSE. Given that [GCC docs](https://gcc.gnu.org/install/configure.html) say that:
```console
--with-isl=pathname
--with-isl-include=pathname
--with-isl-lib=pathname
If you do not have the isl library installed in a standard location and you want to build GCC, you can explicitly specify the directory where it is installed (‘--with-isl=islinstalldir’). The --with-isl=islinstalldir option is shorthand for --with-isl-lib=islinstalldir/lib and --with-isl-include=islinstalldir/include. If this shorthand assumption is not correct, you can use the explicit include and lib options directly.

These flags are applicable to the host platform only. When building a cross compiler, they will not be used to configure target libraries.
```
I would rather try to fix the recipe for `gcc` rather than symlinking every `lib64` directory we find :slightly_smiling_face:

**Comment by alalazo** [comment] 2020-08-20 07:22
Duplicate of #10842

**Comment by alalazo** [comment] 2020-08-20 07:26
Working on an alternative fix right now.

**Comment by michaelkuhn** [comment] 2020-08-20 08:06
> I would rather try to fix the recipe for `gcc` rather than symlinking every `lib64` directory we find

Agreed. I guess this also affects other packages (that use `prefix.lib`), though. We should probably make sure then that everything uses `libs.search_flags` or `libs.directories`.

**Closed as completed** 2020-08-20 15:42 UTC
Labels: build-error
