### ISSUE TITLE
Invalid version specifier message points to wrong `@`

### ISSUE THREAD

**Issue by cyrush** [LLNL/spack#29587] opened 2022-03-18 17:24 UTC
### Steps to reproduce

issue: with bad version in spec, carrot in error message doens't point to the issue.

```
 bin/spack install ascent@develop ^vtk-h@~blt_find_mpi 
```

### Error message

```
==> Error: Invalid version specifier
['ascent@develop', '^vtk-h@~blt_find_mpi']
         ^
```

The problem here, the carrot points at the first `@` - it should point to the second `@`.

(Easy to pick out in this example, but harder to track down in a more complex spec)

This is similar in nature to #8269, but I think it merits its own report.  

### Information on your system

* **Spack:** 0.17.1-1615-e0e3443f3a
* **Python:** 3.7.3
* **Platform:** darwin-catalina-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2023-04-07 09:26
Not a bug as of (possibly fixed with the reworking of the parser):

* **Spack:** 0.20.0.dev0 (4ace1e660a3ab60a2e510308d700e251126f8c0e)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

![Screenshot from 2023-04-07 11-25-21](https://user-images.githubusercontent.com/4199709/230583700-496ca385-0535-42f7-ba08-a5349603d487.png)

**Closed as not planned by alalazo** 2023-04-07 09:26 UTC
Labels: bug, not-a-bug
