### ISSUE TITLE
Installation issue: python + tkinter

### ISSUE THREAD

**Issue by d-beltran** [LLNL/spack#42497] opened 2024-02-05 16:49 UTC
### Steps to reproduce the issue

```console
spack install python@3.8: +tkinter
```

### Error message

==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    python@3.8:+tkinter is unsatisfiable, errors are:
    internal_error("imposed hash without imposing all variant values")

### Information on your system

* **Spack:** 0.22.0.dev0 (9c4e44a0ad2a65f12a8cc4ee88729208ab78844b)
* **Python:** 3.10.8
* **Platform:** linux-ubuntu18.04-skylake
* **Concretizer:** clingo

### Additional information

Hi @adamjstewart, @scheibelp and @skosukhin,

I am having problems with the tkinter variant specifically.
If I run for instance `spack install python@3.8: +uuid` the previous error is not thrown.

No build logs were produced

Best regards

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment] 2024-02-05 17:27
Duplicate of #41146, let's continue the discussion there.

**Closed as completed by adamjstewart** 2024-02-05 17:27 UTC
Labels: build-error

**Comment by d-beltran** [comment] 2024-02-06 10:25
Didn't see it. My bad :(

**Comment by adamjstewart** [comment] 2024-02-06 12:09
No worries, it happens all the time 😄
