### ISSUE TITLE
External packages && spack ci generate → KeyError

### ISSUE THREAD

**Issue by muffgaga** [LLNL/spack#24523] opened 2021-06-25 12:24 UTC
Hey *, (CC @scottwittenburg as you seem to be the gitlab ci contributor :); and @healther FYI)

I am currently trying to establish a gitlab-based build flow for a spack-managed software environment.
When testing packages with MPI dependencies I need to specify an package as an external package as the library will (later) be provided by the HPC environment on what we are actually running on.
For a simple test I just wanted to add the system's mpi library as an external package (mpich 3.0.4 from centos7).
⇒ The "generate" step in gitlab fails with the error below `KeyError: 'mpich/t2ghpmp'`.

I know this is a rather long error description and probably doesn't directly pinpoint the problem
→ I am be very happy to start a deeper investigation :).

General questions:
* Is there support for external packages in the `spack ci generate` gitlab flow?
* Does spack's gitlab-ci `bootstrap` support installing non-compiler packages at an early stage (e.g. external packages)?
  * This could be also interesting for the clingo concretizer because the centos7 compiler is too old for building it in the bootstrapping phase.

### Steps to reproduce the issue

Create a gitlab/CI repo, fill with the following contents:

`spack.yaml`
```yaml
spack:
  view: false
  concretization: separately

  definitions:
  - compiler-pkgs:
    - gcc@10.3.0 os=centos7
  - system-pkgs:
    - mpich %gcc@10.3.0
  - pkgs:
    # neuron depends on mpi by default
    - neuron
  - compilers:
    - '%gcc@10.3.0'
  - oses:
    - os=centos7

  specs:
  - matrix:
    - [$pkgs]
    - [$compilers]
    - [$oses]

  mirrors:
    # whatever

  gitlab-ci:
    bootstrap:
    - name: compiler-pkgs
      compiler-agnostic: true
    - name: system-pkgs
      compiler-agnostic: true

    mappings:
    - match:
      - os=centos7
      runner-attributes:
        tags:
        - docker-runner
        image: # whatever
    before_script:
    - git clone ${SPACK_REPO}
    - pushd spack && git checkout ${SPACK_CHECKOUT_VERSION} && git log -n 1 && popd
    - . "./spack/share/spack/setup-env.sh"
    script:
    - spack env activate --without-view .
    - spack -d ci rebuild
    enable-artifacts-buildcache: true
    rebuild-index: true
```

`external_mpich.yaml`:
```
```yaml
  mpi:
    buildable: false
  mpich:
    buildable: false
    externals:
    - spec: mpich@3.0.4
      prefix: /usr
```

`.gitlab-ci.yml`
```yaml
default:
  image:
    name: #whatever
    entrypoint: [""]
  tags:
    - docker-runner

stages:
  - generate
  - build

variables:
  SPACK_REPO: # whatever
  SPACK_REF: # whatever

generate-pipeline:
  stage: generate
  before_script:
    - git clone ${SPACK_REPO}
    - pushd spack && git checkout ${SPACK_REF} && git log -n 1 && popd
    - . "./spack/share/spack/setup-env.sh"
    # I also tried adding this in this file with the same results
    - cat external_mpich.yaml >> ./spack/etc/spack/packages.yaml
  script:
    - spack -d env activate --without-view .
    - spack -d ci generate --optimize
      --output-file "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"

build-jobs:
  stage: build
  trigger:
    include:
      - artifact: "jobs_scratch_dir/pipeline.yml"
        job: generate-pipeline
    strategy: depend
```

### Error Message

```
Traceback (most recent call last):
  File "/builds/emuller/brainscales-spack-test/spack/bin/spack", line 76, in <module>
    sys.exit(spack.main.main())
  File "/builds/emuller/brainscales-spack-test/spack/lib/spack/spack/main.py", line 773, in main
    return _invoke_command(command, parser, args, unknown)
  File "/builds/emuller/brainscales-spack-test/spack/lib/spack/spack/main.py", line 497, in _invoke_command
    return_val = command(parser, args)
  File "/builds/emuller/brainscales-spack-test/spack/lib/spack/spack/cmd/ci.py", line 454, in ci
    args.func(args)
  File "/builds/emuller/brainscales-spack-test/spack/lib/spack/spack/cmd/ci.py", line 119, in ci_generate
    use_dependencies=use_dependencies)
  File "/builds/emuller/brainscales-spack-test/spack/lib/spack/spack/ci.py", line 765, in generate_gitlab_ci_yaml
    enable_artifacts_buildcache))
  File "/whatever/spack/lib/spack/spack/ci.py", line 502, in format_job_needs
    dep_spec_info = stage_spec_dict[dep_spec_key]
KeyError: 'mpich/t2ghpmp'
```

### Information on your system

* The CI runners are based on Cent OS 7 docker containers.
* GitLab Community Edition 13.12.5

### Additional information

I tried the following things:

1. Adding the package (mpich from the underlying centos7 for testing purposes) to `spack/etc/spack/packages.yaml` → This yields the error mentioned at *Error Message*.

2. As I saw similar problems in the past when using environments locally, I tried to add an install step in between environment activation and `spack ci generate` call:
```
    - spack -d env activate --without-view .
    - spack install mpich
    - spack -d ci generate --optimize
      --output-file "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
```
It still fails, and the hashes don't match → system compiler != target compiler.

3. I tried to add a dummy compiler (matching the target compiler) before installing the packages:
```
- compiler:
    spec: gcc@10.3.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```
⇒ After `spack install` I now see:
```
$ spack install mpich
[+] /usr (external mpich-3.0.4-t2ghpmplyispumd26m5eggt7c7qlxlkh)
```
and later `spack ci generate` fails with (stacktrace as above):
```
KeyError: 'mpich/t2ghpmp'
```

The hashes seem to match, but I still get this error.

4. I now tried to add a second list of packages for spack's gitlab-ci bootstrap thingy:
```
  definitions:
  - compiler-pkgs:
    - gcc@10.3.0 os=centos7
  - system-pkgs:
    - mpich %gcc@10.3.0
…
  gitlab-ci:
    bootstrap:
    - name: compiler-pkgs
      compiler-agnostic: true
    - name: system-pkgs
      compiler-agnostic: true
```
but this still yields the same `KeyError` as above.

5. I also pulled in the latest changes touching `{,cmd/}ci.py` → No change; I rebased on current HEAD → no change.

6. I'm currently testing if commenting out `continue` in `ci.py` helps ;) → The line after "Will not stage external pkg:" (twice). ⇒ The ci generate step terminates correctly:
```
[…]
==> [2021-06-25-16:46:13.360644] Stages for phase "specs"
==> [2021-06-25-16:46:13.360682]   Staging summary:
==> [2021-06-25-16:46:13.360715]     stage 0 (10 jobs):
==> [2021-06-25-16:46:13.360937]       [x] berkeley-db/r3zalj3 -> berkeley-db@18.1.40%gcc@10.3.0  arch=linux-centos7-sandybridge
==> [2021-06-25-16:46:13.361182]       [x] findutils/ebv3de3 -> findutils@4.8.0%gcc@10.3.0  arch=linux-centos7-sandybridge
==> [2021-06-25-16:46:13.361492]       [x] libffi/stzzjh2 -> libffi@3.3%gcc@10.3.0  arch=linux-centos7-sandybridge
==> [2021-06-25-16:46:13.361740]       [x] libiconv/jgrcfwv -> libiconv@1.16%gcc@10.3.0  arch=linux-centos7-sandybridge
==> [2021-06-25-16:46:13.361970]       [x] libmd/5xcqoiw -> libmd@1.0.3%gcc@10.3.0  arch=linux-centos7-sandybridge
==> [2021-06-25-16:46:13.362213]       [x] libsigsegv/seobkx2 -> libsigsegv@2.13%gcc@10.3.0  arch=linux-centos7-sandybridge
==> [2021-06-25-16:46:13.362477]       [x] mpich/t2ghpmp -> mpich@3.0.4%gcc@10.3.0  arch=linux-centos7-sandybridge
[…]
==> [2021-06-25-16:46:13.371687]     stage 10 (1 jobs):
==> [2021-06-25-16:46:13.371914]       [x] neuron/qdlenj7 -> neuron@7.8.2%gcc@10.3.0  arch=linux-centos7-sandybridge
```

Thanks,
Eric

**Comment by scottwittenburg** [comment] 2021-06-25 16:15
Thanks for trying it out and reporting @muffgaga 👍 I haven't had a chance to try reproducing this yet, but I know I have run pipelines with external packages in the past.  However, recent changes to the ci modules may have broken things.  I wonder if @adrienbernede or @tldahlgren are still successfully running pipelines with external pkgs after the pipeline reproducibility PR (#22887) was merged, and what changes or workarounds may now be required?

As for using compiler bootstrapping in `gitlab-ci` to bootstrap clingo, I haven't tried that but suspect it won't work.  Fairly early on in the bootstrapping work, we decided to make it achievable in the time we had to support it for compilers only.  When compilers are modeled as dependencies, we may consider removing the bootstrapping support altogether anyway, to simplify the code.  I guess that wouldn't work for `clingo` though, since it's required in the generation phase.  I think @tdahlgren is using the new concretizer in her radiuss pipelines by using a docker image that has it already installed.

As for commenting out the `continue`, that doesn't sound right to me as even though the generate succeeded in your case when you did that, it appears to have staged a job for your external `mpich`, which should not happen for externals.

**Comment by adrienbernede** [comment] 2021-06-25 16:43
Hello @muffgaga,

### The bug:

It seems that you are running into the exact issue I had. I submitted a PR adding a note in the documentation about this in #24347. This is due to recent changes in `spack ci` feature.

In short, in the spack.yaml, the CI jobs should load the environment from the artifact received from the generation job, not the environment direrctly in your project. That can be a confusing change. Also, you will be missing the `--artifacts-root` at generation time.

I suggest you have a look to both [this section in the documentation](https://spack.readthedocs.io/en/latest/pipelines.html#functional-example) and the changes in #24347.

Feel free to ask for clarifications if needed. Again this is a fairly recent change. I am using external packages without problems in CI.

### Clingo:

What I do to run spack CI efficiently on a cluster is I use a single spack instance. I am NOT cloning spack for each job. This means I can also install clingo with Spack in a job proceeding the "generate", and in fact if I were building a compiler I could do that there too. I am only mentioning that for the performance aspect, and as a possible workaround your clingo issue.

**Comment by muffgaga** [comment] 2021-06-28 11:07
Hey @scottwittenburg and @adrienbernede,


thanks for your help and finding problems in my config files (I seem to have started reading a pre-#24347 documentation; sorry for that) :grimacing:.


## The bug

> As for commenting out the continue, that doesn't sound right to me as even though the generate succeeded in your case when you did that, it appears to have staged a job for your external mpich, which should not happen for externals.

I still get the `KeyError: 'mpich/t2ghpmp'` during generate when **not** commenting out 2x `continue` in `lib/spack/spack/ci.py` (the ones after the log msg "Will not stage external pkg"). Doesn't the stracktrace (`ci_generate` > `generate_gitlab_ci_yaml` > `format_job_needs`) indicate a problem when some package depend on mpich, but mpich can't be found in the data structure tracking all (currently) known staged specs (because it had been skipped?)? I'll try to find a more minimal example for this problem (I currently use `neuron+mpi`) which depends also on Python and other stuff…)


> It seems that you are running into the exact issue I had. I submitted a PR adding a note in the documentation about this in #24347. This is due to recent changes in spack ci feature.
> [...]

Thanks for this hint, before there was another concretization error
```
Traceback (most recent call last):
  File "/whatever/spack-test/spack/bin/spack", line 77, in <module>
    sys.exit(spack.main.main())
  File "/whatever/spack-test/spack/lib/spack/spack/main.py", line 771, in main
    return _invoke_command(command, parser, args, unknown)
  File "/whatever/spack-test/spack/lib/spack/spack/main.py", line 499, in _invoke_command
    return_val = command(parser, args)
  File "/whatever/spack-test/spack/lib/spack/spack/cmd/ci.py", line 600, in ci
    return args.func(args)
  File "/whatever/spack-test/spack/lib/spack/spack/cmd/ci.py", line 282, in ci_rebuild
    env, root_spec, job_spec_pkg_name, related_builds, compiler_action)
  File "/whatever/spack-test/spack/lib/spack/spack/ci.py", line 1221, in get_concrete_specs
    concrete_root = env.specs_by_hash[root_spec]
KeyError: '23wrsonsxywm2xymtcqa3ykkyvekq352'
```
in the build job which is solved by providing `--artifacts-root` and using `${SPACK_CONCRETE_ENV_DIR}` in the build jobs (+ the workaround above). Thanks!

⇒ I.e. I have a working build :tada: (with those `continue`s commented out → rebuilds spawn superfluous "build" jobs of the external `mpich` package.)


## Clingo

Thanks for your suggestion regarding a shared spack folder: that's actually what I also would like to see, but the infrastructure is just provided to me, so I can't easily modify it ;) — basically there's only a bunch of isolated containers in gitlab CI with Internet access → artifacts and (build)cache :).

I think as a next step I'll try to split my generate/build pipeline into two:
* generate/build for a clingo-build-compatible compiler (which could be also our target compiler)
* use clingo and generate/build for the rest of the software (with clingo enabled)
I guess this should be possible by moving the `spack.yaml`s into subfolders and having one more folder in the folder hierarchy for the artifacts.

**Comment by alalazo** [comment] 2023-07-10 20:21
Closing, since there has been no activity in a while. Feel free to reopen if you still have issues with anything mentioned above.

**Closed as not planned by alalazo** 2023-07-10 20:21 UTC
Labels: bug, external-packages, triage, pipelines
