### ISSUE TITLE
The concretizer seems to ignore explicit use of repo.package and always choses the first repo in ~/.spack/repos.yaml

### ISSUE THREAD

**Issue by hamchugh** [LLNL/spack#40719] opened 2023-10-26 15:27 UTC
### Steps to reproduce

Create and add a new repo
```
spack repo create /path/to/repos/mynewrepo
spack repo add /path/to/repos/mynewrepo
```
Create a toy package that exists in more than one repo to test with easily
```
spack create -r /path/to/repos/builtin mycoolpackage
spack create -r /path/to/repos/mynewrepo mycoolpackage
```
Confirm order of repos in ~/.spack/repos.yaml
```
cat ~/.spack/repos.yaml

repos:
- /path/to/repos/mynewrepo
- $spack/var/spack/repos/builtin
```
Test default concretization (this should concretize as the first repo in ~/.spack/repos.yaml which should be mynewrepo)
```
spack spec -N mycoolpackage

Input spec
--------------------------------
 -   .mycoolpackage

Concretized
--------------------------------
 -   mynewrepo.mycoolpackage@1.2.4%gcc@13.1.0 build_system=generic arch=linux-rhel8-zen2
```
Now test explicit use of repo.package_name using a repo that is not default choice (i.e not first in ~/.spack/repos.yaml)
```
spack spec -N builtin.mycoolpackage

Input spec
--------------------------------
 -   builtin.mycoolpackage

Concretized
--------------------------------
 -   mynewrepo.mycoolpackage@1.2.4%gcc@13.1.0 build_system=generic arch=linux-rhel8-zen2
```

Based on my understanding this spec should concretize the package builtin.mycoolpackage but I am seeing it is always seems to choose the default repo that is defined in ~/.spack/repos.yaml. Am I missing something or is this ac actual bug?

Cheers,
Harry

### Information on your system

* **Spack:** 0.21.0.dev0 (53d501119263cfb04f741106cadeb2507e431599)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2023-10-30 10:16
Duplicate of #35536

**Comment by alalazo** [comment] 2023-12-07 09:28
I'll be closing this as a duplicate, but I raised priority on #35536 and will start working on this bug there.

**Closed as not planned by alalazo** 2023-12-07 09:28 UTC
Labels: bug, duplicate
