### ISSUE TITLE
Installation issue: Dakota 6.12

### ISSUE THREAD

**Issue by troyrock** [LLNL/spack#29560] opened 2022-03-17 12:12 UTC
### Steps to reproduce the issue

```console
$ spack spec -l dakota
==> Bootstrapping clingo from pre-built binaries
==> Bootstrapping clingo from sources
==> Error: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %gcc target=x86_64" due to the following failures:
    'spack-install' raised ConflictsInSpecError: Conflicts in concretized spec "clingo-bootstrap@spack%gcc@4.8.5~docs~ipo+python~static_libstdcpp build_type=Release arch=linux-centos7-x86_64/ewz4dcn"

    List of matching conflicts for spec:

    clingo-bootstrap@spack%gcc@4.8.5~docs~ipo+python~static_libstdcpp build_type=Release arch=linux-centos7-x86_64
        ^bison@3.0.4%gcc@4.8.5 patches=b72914f arch=linux-centos7-x86_64
        ^cmake@3.22.2%gcc@4.8.5~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-centos7-x86_64
            ^ncurses@6.2%gcc@4.8.5~symlinks+termlib abi=none arch=linux-centos7-x86_64
                ^pkgconf@1.8.0%gcc@4.8.5 arch=linux-centos7-x86_64
            ^openssl@1.1.1m%gcc@4.8.5~docs certs=system arch=linux-centos7-x86_64
                ^perl@5.34.0%gcc@4.8.5+cpanm+shared+threads arch=linux-centos7-x86_64
                    ^berkeley-db@18.1.40%gcc@4.8.5+cxx~docs+stl patches=b231fcc arch=linux-centos7-x86_64
                    ^bzip2@1.0.8%gcc@4.8.5~debug~pic+shared arch=linux-centos7-x86_64
                        ^diffutils@3.8%gcc@4.8.5 arch=linux-centos7-x86_64
                            ^libiconv@1.16%gcc@4.8.5 libs=shared,static arch=linux-centos7-x86_64
                    ^gdbm@1.19%gcc@4.8.5 arch=linux-centos7-x86_64
                        ^readline@8.1%gcc@4.8.5 arch=linux-centos7-x86_64
                    ^zlib@1.2.11%gcc@4.8.5+optimize+pic+shared arch=linux-centos7-x86_64
        ^python@3.10%gcc@4.8.5+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,7d40923,f2fd060 arch=linux-centos7-x86_64
        ^re2c@2.2%gcc@4.8.5 arch=linux-centos7-x86_64

1. "%gcc@:5" conflicts with "clingo-bootstrap" [C++14 support is required to bootstrap clingo]

    Please run `spack -d spec zlib` for more verbose error messages

$ spack -d spec zlib
==> [2022-03-17-07:30:39.718274] Imported spec from built-in commands
==> [2022-03-17-07:30:39.719333] Imported spec from built-in commands
==> [2022-03-17-07:30:39.720833] Reading config file /net/fs01.cluster.com/home/ACROPOLIS/spack/etc/spack/defaults/config.yaml
==> [2022-03-17-07:30:39.739210] Reading config file /net/fs01.cluster.com/home/ACROPOLIS/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-03-17-07:30:39.751681] Reading config file /net/fs01.cluster.com/home/ACROPOLIS/spack/etc/spack/defaults/config.yaml
==> [2022-03-17-07:30:39.768199] DATABASE LOCK TIMEOUT: 3s
==> [2022-03-17-07:30:39.768259] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-03-17-07:30:39.768692] Reading config file /net/fs01.cluster.com/home/ACROPOLIS/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-03-17-07:30:39.775927] DATABASE LOCK TIMEOUT: 3s
==> [2022-03-17-07:30:39.775980] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-03-17-07:30:39.776042] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2022-03-17-07:30:39.776379] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/net/fs01.cluster.com/home/ACROPOLIS/spack/etc/spack/defaults
==> [2022-03-17-07:30:39.776428] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/net/fs01.cluster.com/home/ACROPOLIS/spack/etc/spack/defaults/linux
==> [2022-03-17-07:30:39.776496] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/trockwood/.spack/bootstrap/config
==> [2022-03-17-07:30:39.776543] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/trockwood/.spack/bootstrap/config/linux
==> [2022-03-17-07:30:39.777380] Reading config file /home/trockwood/.spack/bootstrap/config/linux/compilers.yaml
==> [2022-03-17-07:30:39.800295] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2022-03-17-07:30:39.800370] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2022-03-17-07:30:39.800659] Reading config file /net/fs01.cluster.com/home/ACROPOLIS/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-03-17-07:30:39.900005] Bootstrapping clingo from pre-built binaries
==> [2022-03-17-07:30:39.902028] Reading config file /net/fs01.cluster.com/home/ACROPOLIS/spack/etc/spack/defaults/config.yaml
==> [2022-03-17-07:30:39.920193] DATABASE LOCK TIMEOUT: 3s
==> [2022-03-17-07:30:39.920247] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-03-17-07:30:39.936842] Reading config file /net/fs01.cluster.com/home/ACROPOLIS/spack/etc/spack/defaults/mirrors.yaml
==> [2022-03-17-07:30:39.997781] Cached index for https://mirror.spack.io/bootstrap/github-actions/v0.1 already up to date
==> [2022-03-17-07:30:40.010802] Bootstrapping clingo from sources
==> [2022-03-17-07:30:40.165680] '/usr/bin/cmake' '--version'
==> [2022-03-17-07:30:40.175582] '/usr/bin/bison' '--version'
==> [2022-03-17-07:30:40.177581] '/usr/bin/gawk' '--version'
==> [2022-03-17-07:30:40.179863] Reading config file /net/fs01.cluster.com/home/ACROPOLIS/spack/etc/spack/defaults/packages.yaml
==> [2022-03-17-07:30:40.203894] Reading config file /home/trockwood/.spack/bootstrap/config/packages.yaml
==> [2022-03-17-07:30:40.215516] Reading config file /net/fs01.cluster.com/home/ACROPOLIS/spack/etc/spack/defaults/config.yaml
==> [2022-03-17-07:30:40.243570] diffutils applying constraint iconv
==> [2022-03-17-07:30:40.269845] ncurses applying constraint pkgconfig
==> [2022-03-17-07:30:40.271330] readline applying constraint ncurses
==> [2022-03-17-07:30:40.272871] gdbm applying constraint readline
==> [2022-03-17-07:30:40.281378] bzip2 applying constraint diffutils
==> [2022-03-17-07:30:40.286090] perl applying constraint gdbm@:1.19
==> [2022-03-17-07:30:40.287776] perl applying constraint berkeley-db
==> [2022-03-17-07:30:40.289314] perl applying constraint bzip2
==> [2022-03-17-07:30:40.291073] perl applying constraint zlib
==> [2022-03-17-07:30:40.292770] bison applying constraint diffutils
==> [2022-03-17-07:30:40.294423] bison applying constraint m4
==> [2022-03-17-07:30:40.296175] bison applying constraint perl
==> [2022-03-17-07:30:40.298349] clingo-bootstrap applying constraint python
==> [2022-03-17-07:30:40.299359] python applying constraint pkgconfig@0.9.0:
==> [2022-03-17-07:30:40.302809] python applying constraint pkgconfig@0.9.0:
==> [2022-03-17-07:30:40.308011] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2022-03-17-07:30:40.310314] clingo-bootstrap applying constraint re2c@0.13:
==> [2022-03-17-07:30:40.312743] clingo-bootstrap applying constraint bison@2.5:
==> [2022-03-17-07:30:40.314647] clingo-bootstrap applying constraint python
==> [2022-03-17-07:30:40.331236] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2022-03-17-07:30:40.334050] clingo-bootstrap applying constraint re2c@0.13:
==> [2022-03-17-07:30:40.335632] clingo-bootstrap applying constraint bison@2.5:
==> [2022-03-17-07:30:40.337081] clingo-bootstrap applying constraint python
==> [2022-03-17-07:30:40.338051] python applying constraint pkgconfig@0.9.0:
==> [2022-03-17-07:30:40.347245] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2022-03-17-07:30:40.349840] clingo-bootstrap applying constraint re2c@0.13:
==> [2022-03-17-07:30:40.351390] clingo-bootstrap applying constraint bison@2.5:
==> [2022-03-17-07:30:40.352884] clingo-bootstrap applying constraint python
==> [2022-03-17-07:30:40.391527] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2022-03-17-07:30:40.411461] ncurses applying constraint pkgconfig
==> [2022-03-17-07:30:40.413297] readline applying constraint ncurses
==> [2022-03-17-07:30:40.414937] gdbm applying constraint readline
==> [2022-03-17-07:30:40.420127] diffutils applying constraint iconv
==> [2022-03-17-07:30:40.421782] bzip2 applying constraint diffutils
==> [2022-03-17-07:30:40.423400] perl applying constraint zlib
==> [2022-03-17-07:30:40.425125] perl applying constraint gdbm@:1.19
==> [2022-03-17-07:30:40.426722] perl applying constraint berkeley-db
==> [2022-03-17-07:30:40.428331] perl applying constraint bzip2
==> [2022-03-17-07:30:40.429937] perl applying constraint zlib
==> [2022-03-17-07:30:40.431533] openssl applying constraint zlib
==> [2022-03-17-07:30:40.433200] openssl applying constraint perl@5.14.0:
==> [2022-03-17-07:30:40.435706] cmake applying constraint ncurses
==> [2022-03-17-07:30:40.448179] cmake applying constraint openssl
==> [2022-03-17-07:30:40.450442] cmake applying constraint ncurses
==> [2022-03-17-07:30:40.453766] clingo-bootstrap applying constraint re2c@0.13:
==> [2022-03-17-07:30:40.457472] clingo-bootstrap applying constraint bison@2.5:
==> [2022-03-17-07:30:40.459880] clingo-bootstrap applying constraint python
==> [2022-03-17-07:30:40.463089] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2022-03-17-07:30:40.466222] clingo-bootstrap applying constraint re2c@0.13:
==> [2022-03-17-07:30:40.468799] clingo-bootstrap applying constraint bison@2.5:
==> [2022-03-17-07:30:40.471360] clingo-bootstrap applying constraint python
==> [2022-03-17-07:30:41.221499] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2022-03-17-07:30:41.230603] cmake applying constraint openssl
==> [2022-03-17-07:30:41.231589] openssl applying constraint zlib
==> [2022-03-17-07:30:41.232609] openssl applying constraint perl@5.14.0:
==> [2022-03-17-07:30:41.233654] perl applying constraint gdbm@:1.19
==> [2022-03-17-07:30:41.234873] gdbm applying constraint readline
==> [2022-03-17-07:30:41.236061] readline applying constraint ncurses
==> [2022-03-17-07:30:41.236678] ncurses applying constraint pkgconf
==> [2022-03-17-07:30:41.237777] perl applying constraint berkeley-db
==> [2022-03-17-07:30:41.238981] perl applying constraint bzip2
==> [2022-03-17-07:30:41.240026] bzip2 applying constraint diffutils
==> [2022-03-17-07:30:41.240650] diffutils applying constraint iconv
==> [2022-03-17-07:30:41.241704] perl applying constraint zlib
==> [2022-03-17-07:30:41.243306] cmake applying constraint ncurses
==> [2022-03-17-07:30:41.245489] clingo-bootstrap applying constraint re2c@0.13:
==> [2022-03-17-07:30:41.247650] clingo-bootstrap applying constraint bison@2.5:
==> [2022-03-17-07:30:41.249427] clingo-bootstrap applying constraint python
==> [2022-03-17-07:30:41.267661] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2022-03-17-07:30:41.275823] cmake applying constraint openssl
==> [2022-03-17-07:30:41.276712] openssl applying constraint zlib
==> [2022-03-17-07:30:41.277620] openssl applying constraint perl@5.14.0:
==> [2022-03-17-07:30:41.278622] perl applying constraint gdbm@:1.19
==> [2022-03-17-07:30:41.279671] gdbm applying constraint readline
==> [2022-03-17-07:30:41.280861] readline applying constraint ncurses
==> [2022-03-17-07:30:41.281375] ncurses applying constraint pkgconf
==> [2022-03-17-07:30:41.282506] perl applying constraint berkeley-db
==> [2022-03-17-07:30:41.283470] perl applying constraint bzip2
==> [2022-03-17-07:30:41.284425] bzip2 applying constraint diffutils
==> [2022-03-17-07:30:41.284961] diffutils applying constraint libiconv
==> [2022-03-17-07:30:41.285995] perl applying constraint zlib
==> [2022-03-17-07:30:41.287605] cmake applying constraint ncurses
==> [2022-03-17-07:30:41.289425] clingo-bootstrap applying constraint re2c@0.13:
==> [2022-03-17-07:30:41.291493] clingo-bootstrap applying constraint bison@2.5:
==> [2022-03-17-07:30:41.293001] clingo-bootstrap applying constraint python
==> [2022-03-17-07:30:41.360151] clingo-bootstrap applying constraint cmake@3.16.0:
==> [2022-03-17-07:30:41.368397] cmake applying constraint openssl
==> [2022-03-17-07:30:41.369616] openssl applying constraint zlib
==> [2022-03-17-07:30:41.370939] openssl applying constraint perl@5.14.0:
==> [2022-03-17-07:30:41.372309] perl applying constraint gdbm@:1.19
==> [2022-03-17-07:30:41.373647] gdbm applying constraint readline
==> [2022-03-17-07:30:41.375077] readline applying constraint ncurses
==> [2022-03-17-07:30:41.376561] ncurses applying constraint pkgconf@1.8.0%gcc@4.8.5 arch=linux-centos7-x86_64
==> [2022-03-17-07:30:41.378108] perl applying constraint berkeley-db
==> [2022-03-17-07:30:41.380126] perl applying constraint bzip2
==> [2022-03-17-07:30:41.381375] bzip2 applying constraint diffutils
==> [2022-03-17-07:30:41.382790] diffutils applying constraint libiconv@1.16%gcc@4.8.5 libs=shared,static arch=linux-centos7-x86_64
==> [2022-03-17-07:30:41.384698] perl applying constraint zlib
==> [2022-03-17-07:30:41.386384] cmake applying constraint ncurses
==> [2022-03-17-07:30:41.388421] clingo-bootstrap applying constraint re2c@0.13:
==> [2022-03-17-07:30:41.390337] clingo-bootstrap applying constraint bison@2.5:
==> [2022-03-17-07:30:41.391965] clingo-bootstrap applying constraint python
==> [2022-03-17-07:30:41.414707] Ordered hashes [bison]: bison/30/b72914fe38e54a6fc25f29019e0a0786705c4f61ce20d414cc2010c8d62448c7
==> [2022-03-17-07:30:41.415184] Ordered hashes [berkeley-db]: berkeley-db/64/b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522
==> [2022-03-17-07:30:41.416126] Ordered hashes [python]: python/5/0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87, python/6/f2fd060afc4b4618fe8104c4c5d771f36dc55b1db5a4623785a4ea707ec72fb4, python/9/7d4092366f2e9c19ba85132402e70eb96cac94fdda6a33810c2a980a129c7a22
==> [2022-03-17-07:30:41.431912] [BOOTSTRAP MODULE clingo] Unexpected error "Conflicts in concretized spec "clingo-bootstrap@spack%gcc@4.8.5~docs~ipo+python~static_libstdcpp build_type=Release arch=linux-centos7-x86_64/ewz4dcn"

    List of matching conflicts for spec:

    clingo-bootstrap@spack%gcc@4.8.5~docs~ipo+python~static_libstdcpp build_type=Release arch=linux-centos7-x86_64
        ^bison@3.0.4%gcc@4.8.5 patches=b72914f arch=linux-centos7-x86_64
        ^cmake@3.22.2%gcc@4.8.5~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-centos7-x86_64
            ^ncurses@6.2%gcc@4.8.5~symlinks+termlib abi=none arch=linux-centos7-x86_64
                ^pkgconf@1.8.0%gcc@4.8.5 arch=linux-centos7-x86_64
            ^openssl@1.1.1m%gcc@4.8.5~docs certs=system arch=linux-centos7-x86_64
                ^perl@5.34.0%gcc@4.8.5+cpanm+shared+threads arch=linux-centos7-x86_64
                    ^berkeley-db@18.1.40%gcc@4.8.5+cxx~docs+stl patches=b231fcc arch=linux-centos7-x86_64
                    ^bzip2@1.0.8%gcc@4.8.5~debug~pic+shared arch=linux-centos7-x86_64
                        ^diffutils@3.8%gcc@4.8.5 arch=linux-centos7-x86_64
                            ^libiconv@1.16%gcc@4.8.5 libs=shared,static arch=linux-centos7-x86_64
                    ^gdbm@1.19%gcc@4.8.5 arch=linux-centos7-x86_64
                        ^readline@8.1%gcc@4.8.5 arch=linux-centos7-x86_64
                    ^zlib@1.2.11%gcc@4.8.5+optimize+pic+shared arch=linux-centos7-x86_64
        ^python@3.10%gcc@4.8.5+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,7d40923,f2fd060 arch=linux-centos7-x86_64
        ^re2c@2.2%gcc@4.8.5 arch=linux-centos7-x86_64

1. "%gcc@:5" conflicts with "clingo-bootstrap" [C++14 support is required to bootstrap clingo]
"

```

### Error message

When I originally tried to build I got a different error message than I am currently getting.  I saved part of the original error message but not all of it (sorry).
<details><summary>Error message</summary><pre>
     4460    cd /tmp/trockwood/spack-stage/spack-stage-dakota-6.12-6xlinzt67zzxar6fut3nmkw6l2tbs24t/spack-build-
             6xlinzt/packages/external/LHS && /net/fs01.cluster.com/home/ACROPOLIS/spack/lib/spack/env/gcc/gfort
             ran -DHAVE_CONFIG_H -DHAVE_DAKOTA_SURROGATES -Dlhs_EXPORTS -I/tmp/trockwood/spack-stage/spack-stage
             -dakota-6.12-6xlinzt67zzxar6fut3nmkw6l2tbs24t/spack-build-6xlinzt/packages/external/LHS/mods -I/tmp
             /trockwood/spack-stage/spack-stage-dakota-6.12-6xlinzt67zzxar6fut3nmkw6l2tbs24t/spack-build-6xlinzt
             /packages/external/LHS/mods/mod -O2 -g -DNDEBUG -fPIC -ffixed-form  -std=legacy -c /tmp/trockwood/s
             pack-stage/spack-stage-dakota-6.12-6xlinzt67zzxar6fut3nmkw6l2tbs24t/spack-src/packages/external/LHS
             /Betaic.f90 -o CMakeFiles/lhs.dir/Betaic.f90.o
     4461    /tmp/trockwood/spack-stage/spack-stage-dakota-6.12-6xlinzt67zzxar6fut3nmkw6l2tbs24t/spack-src/src/s
             urrogates/GaussianProcess.cpp: In member function 'virtual void dakota::surrogates::GaussianProcess
             ::build(const MatrixXd&, const MatrixXd&)':
  >> 4462    /tmp/trockwood/spack-stage/spack-stage-dakota-6.12-6xlinzt67zzxar6fut3nmkw6l2tbs24t/spack-src/src/s
             urrogates/GaussianProcess.cpp:131:63: error: no matching function for call to 'ROL::Algorithm<doubl
             e>::Algorithm(const char [12], Teuchos::ParameterList&)'
     4463       ROL::Algorithm<double> algo("Line Search",*gp_mle_rol_params);
     4464                                                                   ^
</pre></details>

Now when I try to run, I get the following error messages:
<details><summary> Error message</summary><pre>

==> Error: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %gcc target=x86_64" due to the following failures:
    'spack-install' raised ConflictsInSpecError: Conflicts in concretized spec "clingo-bootstrap@spack%gcc@4.8.5~docs~ipo+python~static_libstdcpp build_type=Release arch=linux-centos7-x86_64/ewz4dcn"

    List of matching conflicts for spec:

    clingo-bootstrap@spack%gcc@4.8.5~docs~ipo+python~static_libstdcpp build_type=Release arch=linux-centos7-x86_64
        ^bison@3.0.4%gcc@4.8.5 patches=b72914f arch=linux-centos7-x86_64
        ^cmake@3.22.2%gcc@4.8.5~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-centos7-x86_64
            ^ncurses@6.2%gcc@4.8.5~symlinks+termlib abi=none arch=linux-centos7-x86_64
                ^pkgconf@1.8.0%gcc@4.8.5 arch=linux-centos7-x86_64
            ^openssl@1.1.1m%gcc@4.8.5~docs certs=system arch=linux-centos7-x86_64
                ^perl@5.34.0%gcc@4.8.5+cpanm+shared+threads arch=linux-centos7-x86_64
                    ^berkeley-db@18.1.40%gcc@4.8.5+cxx~docs+stl patches=b231fcc arch=linux-centos7-x86_64
                    ^bzip2@1.0.8%gcc@4.8.5~debug~pic+shared arch=linux-centos7-x86_64
                        ^diffutils@3.8%gcc@4.8.5 arch=linux-centos7-x86_64
                            ^libiconv@1.16%gcc@4.8.5 libs=shared,static arch=linux-centos7-x86_64
                    ^gdbm@1.19%gcc@4.8.5 arch=linux-centos7-x86_64
                        ^readline@8.1%gcc@4.8.5 arch=linux-centos7-x86_64
                    ^zlib@1.2.11%gcc@4.8.5+optimize+pic+shared arch=linux-centos7-x86_64
        ^python@3.10%gcc@4.8.5+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,7d40923,f2fd060 arch=linux-centos7-x86_64
        ^re2c@2.2%gcc@4.8.5 arch=linux-centos7-x86_64

1. "%gcc@:5" conflicts with "clingo-bootstrap" [C++14 support is required to bootstrap clingo]

</pre></details>

### Information on your system

$ spack debug report
* **Spack:** 0.17.1-1521-428c630
* **Python:** 3.10.1
* **Platform:** linux-centos7-broadwell
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8284899/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8284901/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adityakavalur** [comment] 2022-05-11 00:30
@troyrock this isnt a dakota issue, its a bootstrapping issue. Is it possible to use a newer gcc version? or install clingo as a pip package?

**Comment by ltalirz** [comment] 2022-05-26 17:25
I also recently started running into this issue on CentOS 7, which still uses GCC 4.8.5 by default.
The issue appeared without me updating spack (which had been working fine), it just occurred with at some point with a `spack install` command.

`pip install clingo` fixed it for me, thanks @troyrock for the suggestion.

**Comment by alalazo** [comment] 2022-06-14 14:45
Couldn't reproduce the bootstrap failure in a Docker container. `clingo` should be able to bootstrap from binaries on CentOS 7. Closing since there are no further comments from @troyrock but let me know if I should reopen.

**Closed as completed by alalazo** 2022-06-14 14:45 UTC
Labels: build-error
