### ISSUE TITLE
Spack doesn't enforce package preferences

### ISSUE THREAD

**Issue by andymwood** [LLNL/spack#37630] opened 2023-05-12 10:21 UTC
### Steps to reproduce

When packages.yaml contains the following
```yaml
packages:
  openssl:
    version: [system]
    buildable: false
    externals:
    - spec: openssl@1.0.2k
      prefix: /usr
  mvapich2:
    version: [2.2]
    variants: process_managers=slurm fabrics=nemesis
```
I get the wrong spec for mvapich2:
```console
$ spack spec mvapich2
Input spec
--------------------------------
mvapich2

Concretized
--------------------------------
mvapich2@2.2%gcc@10.4.0~alloca~cuda~debug+regcache+wrapperrpath build_system=autotools ch3_rank_bits=32 fabrics=nemesis file_systems=auto process_managers=hydra threads=multiple arch=linux-opensuse_leap15-haswell
    ^bison@3.8.2%gcc@10.4.0 build_system=autotools arch=linux-opensuse_leap15-haswell
        ^diffutils@3.8%gcc@10.4.0 build_system=autotools arch=linux-opensuse_leap15-haswell
        ^m4@1.4.19%gcc@10.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-opensuse_leap15-haswell
            ^libsigsegv@2.13%gcc@10.4.0 build_system=autotools arch=linux-opensuse_leap15-haswell
        ^perl@5.36.0%gcc@10.4.0+cpanm+shared+threads build_system=generic arch=linux-opensuse_leap15-haswell
            ^berkeley-db@18.1.40%gcc@10.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-opensuse_leap15-haswell
            ^bzip2@1.0.8%gcc@10.4.0~debug~pic+shared build_system=generic arch=linux-opensuse_leap15-haswell
            ^gdbm@1.23%gcc@10.4.0 build_system=autotools arch=linux-opensuse_leap15-haswell
                ^readline@8.1.2%gcc@10.4.0 build_system=autotools arch=linux-opensuse_leap15-haswell
                    ^ncurses@6.3%gcc@10.4.0~symlinks+termlib abi=none build_system=autotools arch=linux-opensuse_leap15-haswell
    ^findutils@4.9.0%gcc@10.4.0 build_system=autotools patches=440b954 arch=linux-opensuse_leap15-haswell
    ^libpciaccess@0.16%gcc@10.4.0 build_system=autotools arch=linux-opensuse_leap15-haswell
        ^libtool@2.4.7%gcc@10.4.0 build_system=autotools arch=linux-opensuse_leap15-haswell
        ^util-macros@1.19.3%gcc@10.4.0 build_system=autotools arch=linux-opensuse_leap15-haswell
    ^libxml2@2.10.1%gcc@10.4.0~python build_system=autotools arch=linux-opensuse_leap15-haswell
        ^libiconv@1.16%gcc@10.4.0 build_system=autotools libs=shared,static arch=linux-opensuse_leap15-haswell
        ^xz@5.2.7%gcc@10.4.0~pic build_system=autotools libs=shared,static arch=linux-opensuse_leap15-haswell
    ^pkgconf@1.8.0%gcc@10.4.0 build_system=autotools arch=linux-opensuse_leap15-haswell
    ^zlib@1.2.13%gcc@10.4.0+optimize+pic+shared build_system=makefile arch=linux-opensuse_leap15-haswell
...
```
ie `process_managers=hydra` instead of `process_managers=slurm`, and the dependency on slurm is missing.

If I remove the section for openssl from packages.yaml, it returns the correct variant and the dependency on slurm, but then it doesn't use the system version of openssl.

Specifying the variant on the command line seems to work properly though.

### Information on your system

* **Spack:** 0.19.1 (8254ea0644f97275cfb3ec45539969199b067cdb)
* **Python:** 3.6.15
* **Platform:** linux-opensuse_leap15-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2023-06-06 08:30
@adammoody You can use requirements to have a stronger control of the variants:
```yaml
packages:
  mvapich2:
    require: "process_managers=slurm fabrics=nemesis"
```
Preferences have a weaker semantic, and clingo can work around them if that makes the objective function used in the optimization "better".

Docs about the two:
- https://spack.readthedocs.io/en/latest/build_settings.html#package-requirements
- https://spack.readthedocs.io/en/latest/build_settings.html#package-preferences

**Comment by alalazo** [comment] 2023-06-06 08:31
Let me know if there are other issues.

**Comment by alalazo** [comment] 2023-06-08 08:31
Duplicate of #36774

**Closed as completed** 2023-07-19 09:35 UTC
Labels: bug, not-a-bug
