### ISSUE TITLE
`spack spec` is very slow

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#3863] opened 2017-04-17 14:11 UTC
I find that `spack spec` is very slow for complex package dependencies.

To ensure that I get a self-consistent set of installed packages, I create an "umbrella package" that lists all my desired package as dependencies, and then install this package (see `https://github.com/eschnett/spack/tree/eschnett/cactusext`). This also helps a lot with installing packages on MacOS, where one semi-randomly has to choose either `gcc` or `clang` as compiler to make packages build, and I don't want to list these choices on every command line.

A simple `time spack spec cactusext` takes a long time:
```
real	1m45.546s
user	1m42.092s
sys	0m2.347s
```
This concretizes 127 packages; a lot of these are Python packages pulled in automatically as dependencies for the visualization package `py-yt`, as well as other low-level packages pulled in as dependencies of `lmod`.

This issue was raised earlier in #676, which is now closed.

I understand that it can be, in principle, a very difficult problem to find a matching set of versions and variants. However, I strongly suspect that this isn't the case here -- here, mostly dependency packages need to be added, and certain variants enabled. The only backtracking I see would come from `openssl` where the most recent version isn't allowed by certain other packages.

**Comment by adamjstewart** [comment] 2017-04-17 14:14
Duplicate of #3346.

**Comment by eschnett** [comment] 2017-04-17 15:43
Ah, I didn't find that one. Change its description to be more generic?

**Comment by adamjstewart** [comment] 2017-04-17 15:49
Done. Mind if I close this issue so the conversation doesn't get split across multiple issues?

**Closed** 2017-04-19 15:39 UTC
Labels: concretization, duplicate, speed
