### ISSUE TITLE
Installation issue: openssh

### ISSUE THREAD

**Issue by samcmill** [LLNL/spack#22872] opened 2021-04-08 16:54 UTC
#22115 added `openssh` as a dependency to the `openmpi` package.  `openssh` fails to build on my system, which breaks multiple upstream packages that depend on `openmpi`.  

The workaround is to use an external ssh.

### Steps to reproduce the issue

```console
$ spack install openssh
```

The issue likely only appears if the user database is managed by NIS.

### Additional information

OpenSSH builds successfully, but during install runs `ssh-keygen -A`.  That fails with:

```
No user exists for uid 1175
```

The offending code is:

```
     pw = getpwuid(getuid());
     if (!pw)
         fatal("No user exists for uid %lu", (u_long)getuid());
```

The reporter wrote:
> The root cause appears to be that `ssh-keygen` is using `libcrypto.so` from the `openssl` package via RPATH, but NIS wants the system `libcrypto.so`.  

**Remark by bernhardkaindl:**
* *NIS cannot "want" an openssl Library because NIS does not use any crypto, NIS is completely plain-text, it's very old.*

```
$ ldd ssh-keygen
...
	libcrypto.so.1.1 => /home/smcmillan/git/smcmillan/spack/opt/spack/linux-centos8-haswell/gcc-8.3.1/openssl-1.1.1k-5kyfnh3x5k6hxkttqgcsysaw5ayeykoh/lib/libcrypto.so.1.1 (0x00007f34b6371000)
...
```

If I modify the `ssh-keygen` binary with `chrpath` to remove that RPATH entry, then it uses the system `libcrypto.so` and  succeeds.  This looks identical to https://bugzilla.redhat.com/show_bug.cgi?id=1877730.  

**Remark by bernhardkaindl:**
* *That bugzilla is not caused by the openssl in the RPATH (see my strace analysis below). Might be triggered thru another lib in the RPATH tough like the libnss_systemd found in the strace of the non-working strace in the bugzilla.*

**Comment by haampie** [comment] 2021-04-08 18:35
Instead of doing chrpath tricks, can you run `spack external find --not-buildable openssh` so that spack never builds it?

Or maybe you should make openssl external?

In any case, I think openssh as part of openmpi is not necessarily a mistake, since ssh is not always installed and CI tests were reported to fail in github actions with openmpi.

**Comment by samcmill** [comment] 2021-04-08 19:16
Right, `spack external find openssh` is what I meant by "The workaround is to use an external ssh".

My concern is that many users will not know how to work around this, and I expect this will impact many people since many systems use NIS.  

My preference would be to make the `openssh` dependency an optional `openmpi` variant rather than have it enabled by default.

**Comment by bernhardkaindl** [comment] 2022-06-11 00:16
> This looks identical to https://bugzilla.redhat.com/show_bug.cgi?id=1877730.

While it does look identical from what is written there, the strace attachments have never been analyzed by Red Hat and the developer came to a wrong guess. Here is the proof that the assumption of the RedHat Developer is wrong:

The strace from the working and the non_working log show that the RPATH's libcrypto is used in both runs:
```py
$ curl -s https://bugzilla-attachments.redhat.com/attachment.cgi?id=1714404 |grep libcrypto
openat(AT_FDCWD, "/opt/uge/8.6.12/bin/lx-amd64/../../lib/lx-amd64/libcrypto.so.1.1", O_RDONLY|O_CLOEXEC) = 3
$ curl -s https://bugzilla-attachments.redhat.com/attachment.cgi?id=1714405 |grep libcrypto
openat(AT_FDCWD, "/opt/uge/8.6.12/bin/lx-amd64/../../lib/lx-amd64/libcrypto.so.1.1", O_RDONLY|O_CLOEXEC) = 3
```
The claim of the Red Hat Developer that the non-system libcrypto is the culprit is refuted right there.

Since that (likely correctly assumed, but not proven) `getpwuid(getuid());` is erroring out, and `getpwuid()` being a glibc function, it does by definition not depend on OpenSSL's libcrypto because glibc code can of course never depend on any other library.

Indirectly it thru glibc's name service switch code (controlled by `/etc/nsswitch.conf`), there could be a dependency, but since NIS is using unencrypted, plain-text transfers, it does not use any crypto and libnss_nis.so.2 being glibc as well also excludes openssl as the culprit for the uid lookup of `getpwuid()` failing:

```py
$ curl -s https://bugzilla-attachments.redhat.com/attachment.cgi?id=1714404 |grep _nis
openat(AT_FDCWD, "/opt/uge/8.6.12/bin/lx-amd64/../../lib/lx-amd64/libnss_nis.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib64/libnss_nis.so.2", O_RDONLY|O_CLOEXEC) = 3
$ curl -s https://bugzilla-attachments.redhat.com/attachment.cgi?id=1714405 |grep _nis
openat(AT_FDCWD, "/opt/uge/8.6.12/bin/lx-amd64/../../lib/lx-amd64/libnss_nis.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib64/libnss_nis.so.2", O_RDONLY|O_CLOEXEC) = 3
```

Where the non-working code trails off is this after this line:
```py
curl -s https://bugzilla-attachments.redhat.com/attachment.cgi?id=1714405 |grep 'systemd.*= [0-9]'
openat(AT_FDCWD, "/lib64/libnss_systemd.so.2", O_RDONLY|O_CLOEXEC) = 3
```

This shows that the nonworking case only unsuccessfully tries to connect to `nscd` (the glibc name service cache daemon), but never even opens a datagram socket to use NIS.
```py
curl -s https://bugzilla-attachments.redhat.com/attachment.cgi?id=1714405 |grep socket
``` 

This means that in the non-working strace, `/etc/nsswitch.conf` contained systemd to lookup uids, while in the working strace, it did not. One can only guess why the (loaded) libnss_nis.so.2 didn't run it's NIS lookup, but it might have had to do with the /lib64/libnss_systemd.so.2 behaving very strangely according to the strace with many repeated reads of /etc/passwd. Finally after  libnss_systemd.so.2 for some reason not falling back to libnss_nis.so.2 might have been the cause.

But all of that has nothing to do with the libcrypto.so.1.1 or the RPATH which was loaded from RPATH in both traces.

@samcmill After a failed `spack install openssh` run `strace -o strace.txt ...../ssh-keygen -A` to get a trace, otherwise we can only close this issue as not having enough information to solve it.

**Comment by samcmill** [comment] 2022-06-13 19:54
@bernhardkaindl strace output attached.

strace.out corresponds to `ssh-keygen -A`, which fails as above.
[strace.out.gz](https://github.com/spack/spack/files/8894015/strace.out.gz)

strace2.out corresponds to `LD_PRELOAD=/lib64/libcrypto.so.1.1 ssh-keygen -A`, which works.
[strace2.out.gz](https://github.com/spack/spack/files/8894019/strace2.out.gz)

```
$ grep libcrypto strace.out
openat(AT_FDCWD, "/home/smcmillan/git/smcmillan/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.5.0/openssl-1.1.1n-mwlzoxbr7skc62qeq4yof4p3teeglott/lib/libcrypto.so.1.1", O_RDONLY|O_CLOEXEC) = 3
$ grep libcrypto strace2.out
openat(AT_FDCWD, "/lib64/libcrypto.so.1.1", O_RDONLY|O_CLOEXEC) = 3
```

**Comment by bernhardkaindl** [comment] 2022-06-14 01:41
@samcmill you wrote:
> strace2.out corresponds to LD_PRELOAD=/lib64/libcrypto.so.1.1 ssh-keygen -A, which works.

No, this not true (at the very least, very misleading). See the first line of the two strace outputs:
```py
head -1 strace*
==> strace.out <==
execve("./ssh-keygen", ["./ssh-keygen", "-A"], 0x7fffe4d5f648 /* 109 vars */) = 0

==> strace2.out <==
execve("/usr/bin/ssh-keygen", ["ssh-keygen", "-A", "-f", "."], 0x7fff85eef728 /* 110 vars */) = 0
```
The strace recording shows that you executed an entirely different command (the real CentoOS exectuable), and with different args for `strace2.out`.

I assume, you ment to call `LD_PRELOAD=/lib64/libcrypto.so.1.1 ./ssh-keygen -A` instead.

I recommend strongly to trace the same executable (and on the same host, just in case), to aid in finding the issue.

Nonetheless, the strace from the normal system tool (the normal good case) is good to have.

A few things to try:

1) Just in case, from https://github.com/NixOS/nixpkgs/issues/64665 (but likely this does not apply here):
```py
export LD_PRELOAD=/lib/x86_64-linux-gnu/libnss_sss.so.2
```

2) If NIS uses Kerberos on your host, #31086 which enables Keberos in OpenSSH might(should) help.

3) Since the host libcrypto and the one from your logs both use `libcrypto.so.1.1`, move the one built by spack out of the way:
```py
mv /home/smcmillan/git/smcmillan/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.5.0/openssl-1.1.1n-mwlzoxbr7skc62qeq4yof4p3teeglott/lib/libcrypto.so.1.1 backup-dir/libcrypto.so.1.1-spack
```

4) If 1-3 does not help, this might be interesing (after moving libcrypto.so.1.1 back, or using the backup dir instead)
LD_LIBRARY_PATH=/home/smcmillan/git/smcmillan/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.5.0/openssl-1.1.1n-mwlzoxbr7skc62qeq4yof4p3teeglott/lib/

Also `ltrace -S -o strace.out ./ssh-keygen-A` might be interesting and in case `ltrace` is not available or fails to execute properly, then build `uftrace`, either using Linuxbrew or `spack install uftrace` and trace it with:
```py
uftrace -al -P main --srcline ./ssh-keygen -A 2>uftrace.out >&2
```

**Comment by samcmill** [comment] 2022-06-14 14:15
Sorry!  Correct strace log for `LD_PRELOAD=/lib64/libcrypto.so.1.1 ,/ssh-keygen -A` uploaded as
[strace3.out.gz](https://github.com/spack/spack/files/8900501/strace3.out.gz).

**Comment by bernhardkaindl** [comment] 2022-06-14 22:36
The strace logs show that for (some unknown reason), the despite `/lib64/libnss_nis.so.2` being loaded, it does not do a NIS lookup, it does not even call `uname()` to check for the NIS domain name.

Since `strace` only shows system calls, it does not give any clue why that could be.
The other checks in my github message could give some guidance, and `gdb ./ssh-keygen`  could be used ro run the ssh-keygen under GDB.

Two further checks:
* Could you send/show the content of `/etc/nsswitch.conf` on that system?
* Have you tried building and `openssh` using `spack install openssh ^openssl@3` for building with openssl-3.x?
* Ask Florian Weimer from https://bugzilla.redhat.com/show_bug.cgi?id=1877730 why
 *"It turns out a non-system OpenSSL version was loaded, as a result of an RPATH setting in the main executable."* is a problem.
 
Possible mitigations:
* Build `libnss_nis.so.2` as a dependency in spack as well.
* Wen NIS is enabled, refuse to build `openssh` with spack's `openssl`
* Trace or Debug the API between `glibc` and `libnss_nis.so.2` to see what is going on there.
  * The `ltrace` and `uftrace` calls in my previous comment would be helpful with that.

**Comment by bernhardkaindl** [comment] 2024-07-22 22:54
Closing as there was no further response after the posed analysis.

**Comment by bernhardkaindl** [comment] 2024-07-22 22:55
Closing as there was no further response after the posted analysis.

**Closed as not planned by bernhardkaindl** 2024-07-22 22:55 UTC
Labels: build-error
