### ISSUE TITLE
Dependence checking failing for hdf5 and mpi

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/spack#3004] opened 2017-02-02 17:31 UTC
The HDF5 package depends on mpi when the mpi variant is enabled (which is enabled by default). However, if one tries to specify a particular mpi implementation, spack errors with "Error: hdf5 does not depend on openmpi". This can be worked around by explicitly requesting hdf5+mpi. Below are a few `spack spec hdf5` commands and the results:

[lee218@opal186:spack]$ ./bin/spack spec hdf5                                   
Input spec                                                                      
--------------------------------                                                
hdf5                                                                            

Normalized
--------------------------------
hdf5                            
    ^zlib@1.1.2:

Concretized
--------------------------------
hdf5@1.10.0-patch1%gcc@4.9.3+cxx~debug+fortran+mpi+pic+shared~szip~threadsafe arch=linux-rhel7-x86_64
    ^openmpi@2.0.1%gcc@4.9.3~java~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm+verbs+vt arch=linux-rhel7-x86_64
        ^hwloc@1.11.5%gcc@4.9.3 arch=linux-rhel7-x86_64
            ^libpciaccess@0.13.4%gcc@4.9.3 arch=linux-rhel7-x86_64
                ^libtool@2.4.6%gcc@4.9.3 arch=linux-rhel7-x86_64
                    ^m4@1.4.18%gcc@4.9.3+sigsegv arch=linux-rhel7-x86_64
                        ^libsigsegv@2.10%gcc@4.9.3 arch=linux-rhel7-x86_64
                ^pkg-config@0.29.1%gcc@4.9.3+internal_glib arch=linux-rhel7-x86_64
                ^util-macros@1.19.1%gcc@4.9.3 arch=linux-rhel7-x86_64
    ^zlib@1.2.10%gcc@4.9.3+pic+shared arch=linux-rhel7-x86_64

[lee218@opal186:spack]$ ./bin/spack spec hdf5^openmpi
Input spec
--------------------------------
hdf5
    ^openmpi

Normalized
--------------------------------
==> Error: hdf5 does not depend on openmpi

[lee218@opal186:spack]$ ./bin/spack spec hdf5+mpi^openmpi
Input spec
--------------------------------
hdf5+mpi
    ^openmpi

Normalized
--------------------------------
hdf5+mpi
    ^openmpi
        ^hwloc
            ^libpciaccess
                ^libtool
                    ^m4@1.4.6:
                ^pkg-config@0.9.0:
                ^util-macros
    ^zlib@1.1.2:

Concretized
--------------------------------
hdf5@1.10.0-patch1%gcc@4.9.3+cxx~debug+fortran+mpi+pic+shared~szip~threadsafe arch=linux-rhel7-x86_64
    ^openmpi@2.0.1%gcc@4.9.3~java~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm+verbs+vt arch=linux-rhel7-x86_64
        ^hwloc@1.11.5%gcc@4.9.3 arch=linux-rhel7-x86_64
            ^libpciaccess@0.13.4%gcc@4.9.3 arch=linux-rhel7-x86_64
                ^libtool@2.4.6%gcc@4.9.3 arch=linux-rhel7-x86_64
                    ^m4@1.4.18%gcc@4.9.3+sigsegv arch=linux-rhel7-x86_64
                        ^libsigsegv@2.10%gcc@4.9.3 arch=linux-rhel7-x86_64
                ^pkg-config@0.29.1%gcc@4.9.3+internal_glib arch=linux-rhel7-x86_64
                ^util-macros@1.19.1%gcc@4.9.3 arch=linux-rhel7-x86_64
    ^zlib@1.2.10%gcc@4.9.3+pic+shared arch=linux-rhel7-x86_64

[lee218@opal186:spack]$

**Comment by adamjstewart** [comment] 2017-02-02 17:39
Duplicate of #397. @tgamblin is promising an overhaul of our concretization algorithm for the next release that will fix this and hundreds of other related issues.

**Comment by davydden** [comment] 2017-02-02 17:43
> This can be worked around by explicitly requesting hdf5+mpi

known issue indeed. Exactly what @futuretristan  experienced here https://github.com/LLNL/spack/issues/3001

@lee218llnl if you don't mind, I am closing this as a duplicate.


btw, the original issue is `397`, the current issue number is `3004`. This gives a perspective of how old the original issue is :smile:

**Closed by davydden** 2017-02-02 17:43 UTC
Labels: concretization, dependencies, duplicate
