### ISSUE TITLE
Test dependencies not available when executing `spack test run`

### ISSUE THREAD

**Issue by GianlucaFicarelli** [LLNL/spack#22014] opened 2021-03-01 13:45 UTC
Dependencies defined in a python package using `depends_on('<py-package>', type='test')` are not considered when running `spack test run`.
Instead, the same dependency is available when using `type='run'`.

According to the documentation [here](https://spack.readthedocs.io/en/latest/packaging_guide.html#adding-install-tests)
> These tests run in an environment that provides access to the package and all of its dependencies, including `test`-type dependencies.

Some additional context: I'm trying to execute `pip check` to verify that the dependencies defined in `setup.py` are satisfied in Spack as well.
This should be useful to identify some inconsistencies between the dependencies defined in `setup.py` and in `package.py`.
Please advice if thre is another way to do it, or if instead a check like this could be made part of the standard tests of python packages (together with the `import checking` recently added).

### Steps to reproduce the issue

- Add a test dependency and the `test` method to the python package using `spack edit py-jsmin` (`py-jsmin` is just used as an example because it doesn't have any complex dependency, but the same commands can be applied to any other python package):
  ```python
    depends_on('py-pip', type='test')

    def test(self):
        super().test()
        self.run_test(
            python.path, ['-mpip', 'check'], purpose='checking dependencies'
        )
   ```
- Install the package using `spack install py-jsmin`
- Run the tests using `spack test run py-jsmin`

### Error Message

The test fails with the message `No module named pip`:
```console
$ spack test run py-jsmin

==> Spack test u4ljxk3w6bigt55f6tqlbxhsugu3gvt3
==> Testing package py-jsmin-2.2.2-k4hhyqf
==> Error: TestFailure: 1 tests failed.


Command exited with status 1:
    '/path/to/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.8-2ksnrjibwvlao6hvsx6674u5usahu4ek/bin/python3.8' '-mpip' 'check'
/path/to/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.8-2ksnrjibwvlao6hvsx6674u5usahu4ek/bin/python3.8: No module named pip



1 error found in test log:
     3    ==> [2021-03-01-14:19:17.000394] checking import of jsmin
     4    ==> [2021-03-01-14:19:17.000591] '/path/to/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.8-2ksnrjibwvlao6hvsx6674u5usahu4ek/bin/python3
          .8' '-c' 'import jsmin'
     5    PASSED
     6    ==> [2021-03-01-14:19:17.024497] checking dependencies
     7    ==> [2021-03-01-14:19:17.024770] '/path/to/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.8-2ksnrjibwvlao6hvsx6674u5usahu4ek/bin/python3
          .8' '-mpip' 'check'
     8    /path/to/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.8-2ksnrjibwvlao6hvsx6674u5usahu4ek/bin/python3.8: No module named pip
  >> 9    FAILED: Command exited with status 1:
     10       '/path/to/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.8-2ksnrjibwvlao6hvsx6674u5usahu4ek/bin/python3.8' '-mpip' 'check'
     11   /path/to/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.8-2ksnrjibwvlao6hvsx6674u5usahu4ek/bin/python3.8: No module named pip
     12   
     13     File "/path/to/spack/bin/spack", line 71, in <module>
     14       sys.exit(spack.main.main())
     15     File "/path/to/spack/lib/spack/spack/main.py", line 762, in main



/path/to/spack/lib/spack/spack/build_environment.py:872, in _setup_pkg_and_run:
        869        tb_string = traceback.format_exc()
        870
        871        # build up some context from the offending package so we can
  >>    872        # show that, too.
        873        package_context = get_package_context(tb)
        874
        875        logfile = None

```

### Information on your system

* **Spack:** 0.16.1-1534-890a93bbcd
* **Python:** 3.8.3
* **Platform:** linux-rhel7-skylake_avx512
* **Concretizer:** original

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment] 2021-03-01 15:56
Duplicate of #20553

**Comment by alalazo** [comment] 2021-03-02 09:13
@GianlucaFicarelli Added #20553 to v0.16.2 and v0.17.0 dashboard to keep track of it. Closing this duplicate. Thanks for the report!

**Closed as completed by alalazo** 2021-03-02 09:13 UTC
Labels: bug, triage
