### ISSUE TITLE
New concretizer reusing packages too agressively?

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [LLNL/spack#31607] opened 2022-07-15 17:16 UTC
### Steps to reproduce

Hi,

I have seen pretty weird stuff with the new concretizer after upgrading from an older version Spack. I think it all comes down to the concretizer being too aggressive at reusing package.

For example in the following example, the concretizer chooses to use different versions of Python which leads to a completely broken environment:
```console
Input spec
--------------------------------
 -   [    ]  julia@1.7.2

Concretized
--------------------------------
 -   [    ]  julia@1.7.2%intel@19.1.3+openlibm+precompile patches=3a5243c,5ac4965,89a3101,8b993a2,ba7ab19 arch=linux-rhel8-skylake_avx512                                                                                                                     
 -   [bl  ]      ^curl@7.78.0%intel@19.1.3~gssapi~ldap~libidn2~librtmp~libssh+libssh2+nghttp2 libs=shared,static tls=mbedtls,openssl arch=linux-rhel8-skylake_avx512
 -   [bl  ]          ^libssh2@1.9.0%intel@19.1.3~ipo+shared build_type=RelWithDebInfo crypto=mbedtls arch=linux-rhel8-skylake_avx512                                                                                                                          
[+]  [b   ]              ^cmake@3.18.4%intel@19.1.3~doc+ncurses+openssl+ownlibs~qt patches=bf695e3 arch=linux-rhel8-skylake_avx512                                                                                                                            
[+]  [bl  ]                  ^ncurses@6.2%intel@19.1.3~symlinks+termlib arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^openssl@1.1.1g%intel@19.1.3+systemcerts arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                      ^zlib@1.2.11%intel@19.1.3+optimize+pic+shared arch=linux-rhel8-skylake_avx512
 -   [bl  ]              ^mbedtls@2.24.0%intel@19.1.3+pic build_type=Release libs=shared,static patches=ab3db2c arch=linux-rhel8-skylake_avx512                                                                                                               
[+]  [blr ]              ^xz@5.2.5%intel@19.1.3~pic arch=linux-rhel8-skylake_avx512
 -   [bl  ]          ^nghttp2@1.44.0%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [b   ]              ^pkgconf@1.8.0%intel@19.1.3 arch=linux-rhel8-skylake_avx512
 -   [bl  ]      ^dsfmt@2.2.5%intel@19.1.3 patches=b79624c arch=linux-rhel8-skylake_avx512
[+]  [bl  ]      ^gmp@6.2.1%intel@19.1.3 libs=shared,static arch=linux-rhel8-skylake_avx512
[+]  [b   ]          ^autoconf@2.69%intel@19.1.3 patches=35c4492,7793209,a49dd5b arch=linux-rhel8-skylake_avx512
[+]  [b r ]              ^m4@1.4.19%intel@19.1.3+sigsegv patches=9dc5fbd,bfdffa7 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^libsigsegv@2.13%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [b r ]              ^perl@5.34.1%gcc@8.4.1+cpanm+shared+threads arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^berkeley-db@18.1.40%gcc@8.4.1+cxx~docs+stl patches=b231fcc arch=linux-rhel8-skylake_avx512
[+]  [blr ]                  ^bzip2@1.0.8%intel@19.1.3~debug~pic+shared arch=linux-rhel8-skylake_avx512
[+]  [b   ]                      ^diffutils@3.8%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                          ^libiconv@1.16%intel@19.1.3 libs=shared,static arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^gdbm@1.19%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                      ^readline@8.1%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                          ^ncurses@6.2%intel@19.1.3~symlinks+termlib abi=none arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^zlib@1.2.12%intel@19.1.3+optimize+pic+shared patches=0d38234 arch=linux-rhel8-skylake_avx512
[+]  [b   ]          ^automake@1.16.5%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [b   ]          ^libtool@2.4.7%intel@19.1.3 arch=linux-rhel8-skylake_avx512
 -   [bl  ]      ^libblastrampoline@3.1.0%intel@19.1.3 arch=linux-rhel8-skylake_avx512
 -   [bl  ]      ^libgit2@1.1.1%intel@19.1.3~curl~ipo+mmap+ssh build_type=RelWithDebInfo https=system arch=linux-rhel8-skylake_avx512                                                                                                                         
 -   [bl  ]      ^libunwind@1.6.2%intel@19.1.3~block_signals~conservative_checks~cxx_exceptions~debug~debug_frame+docs~pic+tests+weak_backtrace~xz~zlib components=none libs=shared,static arch=linux-rhel8-skylake_avx512
 -   [bl  ]      ^libuv@1.42.0%intel@19.1.3 patches=d9252fb arch=linux-rhel8-skylake_avx512
[+]  [b   ]          ^autoconf@2.69%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [b r ]              ^m4@1.4.18%intel@19.1.3+sigsegv patches=3877ab5,fc9b616 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^libsigsegv@2.12%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [b r ]              ^perl@5.30.3%intel@19.1.3+cpanm+shared+threads arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^berkeley-db@18.1.40%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^gdbm@1.18.1%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                      ^readline@8.0%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [b   ]          ^automake@1.16.2%intel@19.1.3 arch=linux-rhel8-skylake_avx512
 -   [b   ]      ^libwhich@1.1.0%intel@19.1.3 arch=linux-rhel8-skylake_avx512
 -   [bl  ]      ^llvm@12.0.1%intel@19.1.3+clang~code_signing+compiler-rt~cuda~flang+gold~internal_unwind~ipo+libcxx+link_llvm_dylib+lld+lldb+llvm_dylib~mlir+omp_as_runtime~omp_debug~omp_tsan+polly~python~shared_libs~split_dwarf~z3 build_type=Release patches=10cb42f,88ae104,f920173 targets=amdgpu,bpf,nvptx,webassembly version_suffix=jl arch=linux-rhel8-skylake_avx512
 -   [bl  ]          ^binutils@2.38%intel@19.1.3~gas+gold~headers~interwork+ld~libiberty~lto+nls+plugins libs=shared,static arch=linux-rhel8-skylake_avx512                                                                                                   
[+]  [b   ]              ^diffutils@3.7%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^libiconv@1.16%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]              ^gettext@0.21%intel@19.1.3+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-rhel8-skylake_avx512                                                                                                                              
[+]  [bl  ]                  ^bzip2@1.0.8%intel@19.1.3+shared arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^libxml2@2.9.10%intel@19.1.3~python arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^tar@1.32%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]          ^hwloc@2.2.0%intel@19.1.3~cairo~cuda~gl~libudev+libxml2~netloc~nvml+pci+shared arch=linux-rhel8-skylake_avx512                                                                                                                           
[+]  [bl  ]              ^libpciaccess@0.16%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]          ^libedit@3.1-20191231%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [b   ]          ^ninja@1.10.2%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [b   ]              ^python@3.9.12%intel@19.1.3+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-rhel8-skylake_avx512                                                                                                                              
[+]  [bl  ]                  ^expat@2.4.8%intel@19.1.3+libbsd arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                      ^libbsd@0.11.5%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                          ^libmd@1.0.4%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^gettext@0.21%intel@19.1.3+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-rhel8-skylake_avx512                                                                                                                          
[+]  [bl  ]                      ^libxml2@2.9.13%intel@19.1.3~python arch=linux-rhel8-skylake_avx512
[+]  [blr ]                          ^xz@5.2.5%intel@19.1.3~pic libs=shared,static arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                      ^tar@1.34%intel@19.1.3 zip=pigz arch=linux-rhel8-skylake_avx512
[+]  [  r ]                          ^pigz@2.7%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [  r ]                          ^zstd@1.5.2%intel@19.1.3+programs compression=none libs=shared,static arch=linux-rhel8-skylake_avx512                                                                                                                    
[+]  [bl  ]                  ^libffi@3.4.2%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^openssl@1.1.1o%intel@19.1.3~docs~shared certs=system arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^sqlite@3.38.5%intel@19.1.3+column_metadata+dynamic_extensions+fts~functions+rtree arch=linux-rhel8-skylake_avx512                                                                                                               
[+]  [bl  ]                  ^util-linux-uuid@2.37.4%intel@19.1.3 arch=linux-rhel8-skylake_avx512
 -   [b   ]          ^perl-data-dumper@2.173%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [b   ]          ^python@3.6.12%intel@19.1.3+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-rhel8-skylake_avx512
[+]  [bl  ]              ^expat@2.2.9%intel@19.1.3+libbsd arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^libbsd@0.10.0%intel@19.1.3 patches=71b49f5 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]              ^libffi@3.3%intel@19.1.3 patches=26f26c6 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]              ^libuuid@1.0.3%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]              ^sqlite@3.33.0%intel@19.1.3+column_metadata+fts~functions~rtree arch=linux-rhel8-skylake_avx512
 -   [bl  ]          ^swig@4.0.2%intel@19.1.3 arch=linux-rhel8-skylake_avx512
 -   [bl  ]              ^pcre@8.45%intel@19.1.3~jit+multibyte+utf arch=linux-rhel8-skylake_avx512
[+]  [bl  ]      ^mpfr@4.0.2%intel@19.1.3 libs=shared,static patches=3f80b83 arch=linux-rhel8-skylake_avx512
[+]  [b   ]          ^autoconf-archive@2022.02.11%intel@19.1.3 patches=130cd48 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]      ^openblas@0.3.20%gcc@8.4.1~bignuma~consistent_fpcsr+ilp64+locking+pic+shared symbol_suffix=64_ threads=none arch=linux-rhel8-skylake_avx512
[+]  [b   ]          ^perl@5.34.1%gcc@8.4.1+cpanm+shared+threads arch=linux-rhel8-skylake_avx512
[+]  [bl  ]              ^bzip2@1.0.8%gcc@8.4.1~debug~pic+shared arch=linux-rhel8-skylake_avx512
[+]  [b   ]                  ^diffutils@3.8%gcc@8.4.1 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                      ^libiconv@1.16%gcc@8.4.1 libs=shared,static arch=linux-rhel8-skylake_avx512
[+]  [bl  ]              ^gdbm@1.19%gcc@8.4.1 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                  ^readline@8.1%gcc@8.4.1 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]                      ^ncurses@6.2%gcc@8.4.1~symlinks+termlib abi=none arch=linux-rhel8-skylake_avx512
[+]  [b   ]                          ^pkgconf@1.8.0%gcc@8.4.1 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]              ^zlib@1.2.12%gcc@8.4.1+optimize+pic+shared patches=0d38234 arch=linux-rhel8-skylake_avx512
 -   [bl  ]      ^openlibm@0.7.5%intel@19.1.3 arch=linux-rhel8-skylake_avx512
 -   [bl  ]      ^p7zip@16.02%intel@19.1.3 arch=linux-rhel8-skylake_avx512
 -   [b   ]      ^patchelf@0.14.5%intel@19.1.3 arch=linux-rhel8-skylake_avx512
[+]  [bl  ]      ^pcre2@10.39%intel@19.1.3~jit+multibyte arch=linux-rhel8-skylake_avx512
 -   [bl  ]      ^suite-sparse@5.10.1%intel@19.1.3~cuda~graphblas~openmp+pic~tbb arch=linux-rhel8-skylake_avx512
[+]  [bl  ]          ^metis@5.1.0%intel@19.1.3~gdb~int64~real64+shared build_type=Release patches=4991da9 arch=linux-rhel8-skylake_avx512
[+]  [b   ]              ^cmake@3.23.1%intel@19.1.3~doc+ncurses+ownlibs~qt build_type=Release arch=linux-rhel8-skylake_avx512
 -   [bl  ]      ^utf8proc@2.6.1%intel@19.1.3~ipo build_type=RelWithDebInfo arch=linux-rhel8-skylake_avx512
```

The concretizer also seems to ignore completely the priority order defined for the virtual dependency providers. I have "intel-mkl" set as the highest priority but I first installed a program that specifically required `openblas+ilp64`, the concretizer would then always try to reuse the installed Openblas package even though it was lowest priority and `+ilp64` would break the specific package I was trying to install (this might not have been properly specified in the package though).

I have also seen the concretizer mixing compilers.

Let me know if you want me to try providing real reproducers, it might not be easy though since this heavily depends on the already installed packages.

### Information on your system

* **Spack:** 0.18.0 (0e8fa3c3b109a00a9613d5cf048bade8eecd2d49)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by melven** [comment] 2022-07-21 08:34
I have a similar problem: the `reuse` has higher priority than the mpi-provider (e.g., `packages:all:providers:mpi: [mpich]`).

This results in an environment with `mpich` that reuses packages built with openmpi, e.g. (`hdf5^openmpi`, `petsc^openmpi`, ...) which is not what I intended...

Concerning mixing of python-versions in the example above: these are only build dependencies, so from my understanding, it should by fine, right?

But problems concerning the virtual dependency providers also occur in my spack workflow: if there is one package explicitly built with different dependencies, then this messes up later builds.

Perhaps a "reuse: when_possible" feature could be helpful that still prevents building 10 versions of ninja but respects the desired dependency provider and compiler, etc.

**Comment by RemiLacroix-IDRIS** [comment] 2022-07-21 08:53
> Concerning mixing of python-versions in the example above: these are only build dependencies, so from my understanding, it should by fine, right?

Unfortunately not, this leaded to the python executable not being able to run because of mixed up paths.

**Comment by melven** [comment] 2022-07-21 08:58
> > Concerning mixing of python-versions in the example above: these are only build dependencies, so from my understanding, it should by fine, right?
> 
> Unfortunately not, this leaded to the python executable not being able to run because of mixed up paths.

Ok thanks for the clarification. Then I'll need to avoid that case, too.
(So for environment with different python versions, I'll probably need to build some packages like ninja multiple times...)

**Comment by jgalarowicz** [comment] 2022-07-22 15:08
I am also seeing this issue with openspeedshop which requires python 2.7 but the new clingo concretizer is using the ninja python 3 while the original concretizer does the right thing pulling in python 2.7 for openspeedshop.   You mention building ninja multiple times.  I'm assuming you mean specifying different python versions for each of the multiple builds.   Will the new concretizer work correctly if it sees multiple choices for the ninja/python combinations?   I need a work around to get openspeedshop built for our customers.   Thanks for any insights!

**Comment by RemiLacroix-IDRIS** [comment] 2022-08-16 15:35
Any news about this? It's really driving me crazy... :(

**Comment by alalazo** [comment] 2022-08-23 10:59
@RemiLacroix-IDRIS I don't see it mentioned in the thread, but I assume you are aware that with:
```console
$ spack config add concretizer:reuse:false
```
you'll get back the old deterministic concretizer behavior.

**Comment by RemiLacroix-IDRIS** [comment] 2022-08-23 11:01
@alalazo : is it the same as `--fresh` on the command-line?

**Comment by alalazo** [comment] 2022-08-23 11:07
Yes, but from config file - so you don't have to specify `--fresh` every time.

**Comment by teachers-uk-net** [comment] 2023-01-04 17:22
Hi

Not sure if it is related although believe it is, however, only manifested since we added even more architectures and an additional compiler but seemed to confirm when tested with `spack spec -I kraken2` then `spack spec -I kraken2 target=cascadelake` and `spack spec -U -I kraken2 target=cascadelake` got some surprising results (in attached file [spack_spec.txt](https://github.com/spack/spack/files/10346118/spack_spec.txt)).

**Comment by alalazo** [comment] 2023-07-07 11:45
Reusing specs takes into account constraints. If an old, installed version of something is used and it breaks builds, there's likely missing information in some package recipe (missing conflicts, missing dependencies). 

> The concretizer also seems to ignore completely the priority order defined for the virtual dependency providers.

It doesn't ignore them, they're just lower priority than reuse. If you want to force a provider, you can try requirements.

Marking this as not-a-bug, but let me know if there are other behaviors that still need some investigation.

**Comment by alalazo** [comment] 2023-07-07 11:47
> Let me know if you want me to try providing real reproducers, it might not be easy though since this heavily depends on the already installed packages.

Real reproducers that can be <kbd>Ctrl+C</kbd> and <kbd>Ctrl+V</kbd> make triaging bugs so much easier, so if you have them they're more than welcome. Thanks!

**Comment by RemiLacroix-IDRIS** [comment] 2023-07-07 12:04
@alalazo : The main issue here was having two different versions of Python in the dependency tree. Is that even supposed to be possible?

**Comment by alalazo** [comment] 2023-07-07 13:24
> Is that even supposed to be possible?

Yes, in one specific case: you install a spec that has a `python` as a build dependency, and then reuse that spec later for a parent that needs a different version/configuration of `python`. The fact is: we don't use build dependency information when reusing an installed spec.

**Comment by alalazo** [comment] 2023-07-12 12:38
Looking above, both Pythons are pure build dependencies, so an admissible configuration if done in multiple steps.

**Closed as not planned by alalazo** 2023-07-12 12:38 UTC
Labels: bug, concretization, not-a-bug
