### ISSUE TITLE
Installation issue: meson broken on multilib systems with lib/lib64 split (like openSUSE)

### ISSUE THREAD

**Issue by dev-zero** [LLNL/spack#26546] opened 2021-10-06 07:07 UTC
### Steps to reproduce the issue

```console
$ spack install meson
$ spack load meson
$ meson --help
meson --help
Traceback (most recent call last):
  File "/sw-ng/spack/opt/spack/linux-opensuse_leap15-sandybridge/gcc-11.2.0/meson-0.59.2-w3xwpklyb6mnoosqb6oclexad6clr2on/bin/meson", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3123, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3107, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3136, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'meson==0.59.2' distribution was not found and is required by the application
$ echo $PYTHONPATH
/sw-ng/spack/opt/spack/linux-opensuse_leap15-sandybridge/gcc-11.2.0/py-setuptools-57.4.0-p7r4vvplum63eqqx6tf7qwfitk7ppalp/lib64/python3.6/site-packages:/sw-ng/spack/opt/spack/linux-opensuse_leap15-sandybridge/gcc-11.2.0/meson-0.59.2-w3xwpklyb6mnoosqb6oclexad6clr2on/lib64/python3.6/site-packages:/sw-ng/spack/opt/spack/linux-opensuse_leap15-sandybridge/gcc-11.2.0/py-setuptools-57.4.0-p7r4vvplum63eqqx6tf7qwfitk7ppalp/lib64/python3.6/site-packages:/sw-ng/spack/opt/spack/linux-opensuse_leap15-sandybridge/gcc-11.2.0/ninja-1.10.2-x4i5ucjcn43khkqqjam4ae3xqcn5ahtk/misc
$ ls /sw-ng/spack/opt/spack/linux-opensuse_leap15-sandybridge/gcc-11.2.0/meson-0.59.2-w3xwpklyb6mnoosqb6oclexad6clr2on/lib64/python3.6/site-packages
$ ls /sw-ng/spack/opt/spack/linux-opensuse_leap15-sandybridge/gcc-11.2.0/meson-0.59.2-w3xwpklyb6mnoosqb6oclexad6clr2on/lib/python3.6/site-packages
meson-0.59.2-py3.6.egg-info  mesonbuild
```

Meaning: the directory included in `$PYTHONPATH` does not contain the Meson distro while the `lib` dir would.

@michaelkuhn

### Information on your system

* **Spack:** 0.16.3-4672-572791006d
* **Python:** 3.6.13
* **Platform:** linux-opensuse_leap15-sandybridge
* **Concretizer:** clingo

### Additional information

Since this is not a build problem, but rather that the installed files are broken I don't have the spack-build* files.
I wonder whether this is a general problem with Python packages.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by dev-zero** [comment] 2021-10-06 07:10
Note, this issue is similar to #7353 but exactly the other way round: `lib64` gets added to `$PYTHONPATH` while the package was installed in `lib` (since it doesn't contain any compiled extensions).

**Comment by dev-zero** [comment] 2021-10-06 07:10
... and since `meson` is now a requirement of `mesa` this breaks the build tree for all UI-related packages.

**Comment by michaelkuhn** [comment] 2021-10-06 20:26
Looks like a general problem, your `PYTHONPATH` contains only `lib64` directories as far as I can see.

@adamjstewart probably knows best what's going on with Python packages.

**Comment by adamjstewart** [comment] 2021-10-06 20:35
Hey, I'll try to summarize the issue. The Python build system installs libraries to one of several locations:

* `lib/python-X.Y/site-packages`
* `lib64/python-X.Y/site-packages`
* `lib/python-X.Y.Z/dist-packages`
* etc.

We can query the Python `distutils` package (now deprecated) to determine where these packages will get installed. However, CMake packages that install Python libraries install them to wherever they feel like? There doesn't seem to be a good way to predict where these libraries will be. Or at least, I haven't figured one out yet.

In the past we've tried recursively searching for Python libraries, but this doesn't work before the package is built, so we wanted a more general solution.

Possible workarounds for now:
1. See if it's possible to control where the Python libraries get installed to via CMake
2. If not, set `PYTHONPATH` yourself since this package differs from 99% of Python packages

**Comment by michaelkuhn** [comment] 2021-10-06 20:44
Thanks! Meson is a regular setuptools package as far as I can tell, though. Shouldn't it end up in `lib` then?

**Comment by adamjstewart** [comment] 2021-10-07 00:18
Hmm, was this package installed before the PythonPackage refactor? I would try installing it again on develop and see if the issue is still present. We should now be adding the same directory as we force setuptools to install to.

**Comment by dev-zero** [comment] 2021-10-08 06:55
@adamjstewart the first thing I did was to update `develop` and install the latest version of meson. Or do I need to reinstall the whole dependency chain (e.g. path stored somewhere in `setuptools`)?

**Comment by dev-zero** [comment] 2021-10-08 06:57
@michaelkuhn the package correctly installs to`lib/`, but `lib/python3.6` does not get added to the `PYTHONPATH`, only `lib64/python3.6` does.

**Comment by michaelkuhn** [comment] 2021-10-08 12:14
Oh, sorry, I mixed that up. So the question is why Spack only adds `lib64` to `PYTHONPATH` then (and why it gets created, since it seems to be empty).

**Comment by adamjstewart** [comment] 2021-10-08 18:42
Can you uninstall and reinstall both meson and setuptools? If that doesn't work, can you share the `spack-build-out.txt` and `spack-build-env.txt` files for both meson and setuptools? They should be in the installation `<prefix>/.spack/` directory.

**Comment by dev-zero** [comment] 2021-10-12 07:37
Still no dice unfortunately, here come the spack-build-*.txt files:

[setuptools.spack-build-env.txt](https://github.com/spack/spack/files/7327869/setuptools.spack-build-env.txt)
[setuptools.spack-build-out.txt](https://github.com/spack/spack/files/7327870/setuptools.spack-build-out.txt)
[meson.spack-build-out.txt](https://github.com/spack/spack/files/7327871/meson.spack-build-out.txt)
[meson.spack-build-env.txt](https://github.com/spack/spack/files/7327873/meson.spack-build-env.txt)

**Comment by adamjstewart** [comment] 2021-10-12 16:43
Sigh, it looks like this was broken by #25998, which was designed to fix the exact opposite problem for the cython package. For now, you can undo that commit locally to fix your issue. In the long run, we need to figure out how setuptools/distutils decides where to install packages and use that consistently everywhere. We're currently using distutils to do this, but distutils is now deprecated in Python 3.10 and will be removed in Python 3.12, so we need to find an alternative anyway.

**Comment by dev-zero** [comment] 2021-10-17 20:49
@adamjstewart an alternative to figuring out what setuptools is doing is to tell setuptools what to do. This is what Gentoo (also a multilib-enabled distro) is doing, see here: https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/distutils-r1.eclass#n678

**Comment by adamjstewart** [comment] 2021-10-17 23:51
We do: https://github.com/spack/spack/blob/develop/lib/spack/spack/build_systems/python.py#L265,L266

The problem is that we also need to support external Python installations where we don't have control over this.

**Comment by adamjstewart** [comment] 2021-12-29 03:12
I believe this will be fixed by https://github.com/spack/spack/pull/27798/commits/98bffffe347fede2463192bbcef12780d6e2de7c

**Closed as completed** 2022-01-14 02:11 UTC
Labels: build-error
