### ISSUE TITLE
Default build_type method in CMakePackage

### ISSUE THREAD

**Issue by JavierCVilla** [LLNL/spack#3069] opened 2017-02-08 10:42 UTC
@adamjstewart 

As a proposal, I was wondering if `build_type` method in the CMakePackage could be set by default as:

```
def build_type(self):
        spec = self.spec
        if '+debug' in spec:
            return 'Debug'
        else:
            return 'Release'
```

I think that most of CMakePackage packages define the build type in that way, but I don't know if there is any other reason to leave it to the user.

**Comment by davydden** [comment] 2017-02-08 11:03
not all packages have `debug` variant, i guess that's the reasons why it's not set this way.

**Comment by alalazo** [comment] 2017-02-08 12:08
@JavierCVilla As soon as #2386 will be merged we can code what has been discussed in #2692 which should also go in the direction you are proposing.

**Comment by citibeth** [comment] 2017-02-08 16:45
At the point that #2692 is implemented, we will rip out individual-package efforts at providing similar functionality.  The job will be made easier if it's not added in the first place.

**Comment by citibeth** [comment] 2017-02-08 16:48
I'm closing this thread, since it is a duplicate of #2692.

**Closed by citibeth** 2017-02-08 16:48 UTC
