### ISSUE TITLE
Spack re-installing an already-installed dependency then complaining about same SHA-1

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#23168] opened 2021-04-21 13:47 UTC
Note: I'm filing this issue as a bug report rather than an installation issue of the argobots package because I do think the package is correct and Spack is actually faulty here.

Since the recent change to the Argobots package (https://github.com/spack/spack/pull/23133) which in particular added the `stackguard` variant, I see the following problem when installing any package that depends on argobots: the first package I install will build and install fine, building the following spec of argobots as a dependency:

```
argobots@1.1%gcc@8.2.1~affinity~debug+perf~stackunwind~tool~valgrind stackguard=no arch=linux-ubuntu16.04-skylake
```
Which ends up installed as `argobots-1.1-u2glvj7qojowtqmzi4j6us3gxikg72ke`.

Then I install a second package that depends on argobots. I see the exact same argobots dependency needed, yet spack is rebuilding it and reinstalling it, with the same hash. During this installation process, I get a warning:

```
==> Warning: Module file already exists : skipping creation
file : /nfs2/mdorier/spack/share/spack/modules/linux-ubuntu16.04-skylake/argobots-1.1-gcc-8.2.1-u2glvj7
spec : argobots@1.1%gcc@8.2.1~affinity~debug+perf~stackunwind~tool~valgrind stackguard=no arch=linux-ubuntu16.04-skylake
```

Then I install a third package that depends on argobots. This time it fails right away with this error:
```
==> Error: Specs argobots@1.1%gcc@8.2.1~affinity~debug+perf~stackunwind~tool~valgrind stackguard=no arch=linux-ubuntu16.04-skylake and argobots@1.1%gcc@8.2.1~affinity~debug+perf~stackguard~stackunwind~tool~valgrind arch=linux-ubuntu16.04-skylake have the same SHA-1 prefix!
```

This is a fresh installation of spack, and nothing in my packages.yaml or other configuration files to interfere. I have no idea why spack talks about a `~stackguard` variant in the last error message even though `stackguard` is a value-based variant, not a boolean one.

### Steps to reproduce the issue

You can easily reproduce this issue for instance by taking multiple versions of the mochi-margo package, which depends on argobots, as follows (though I have experienced this problem with pretty much any package that depends on argobots).

```console
$ spack install mochi-margo@0.9.4 ^mercury~boostsys
$ spack install mochi-margo@0.9.3 ^mercury~boostsys
$ spack install mochi-margo@0.9.2 ^mercury~boostsys
```

### Error Message

```console
$ spack --debug --stacktrace install mochi-margo@0.9.2 ^mercury~boostsys

nfs2/mdorier/spack/lib/spack/spack/installer.py:1872 ==> [2021-04-21-08:45:20.168908] - mercury-2.0.0-tpsjnnzzvnoa6fu7plgscmaggzizliy5
nfs2/mdorier/spack/lib/spack/spack/installer.py:1870 ==> [2021-04-21-08:45:20.182918] Pkg id mercury-2.0.0-tpsjnnzzvnoa6fu7plgscmaggzizliy5 has the following dependents:
nfs2/mdorier/spack/lib/spack/spack/installer.py:1872 ==> [2021-04-21-08:45:20.183178] - mochi-margo-0.9.2-xvj7oakacuvsigkxudndfdywp2ekggir
nfs2/mdorier/spack/lib/spack/spack/installer.py:1870 ==> [2021-04-21-08:45:20.229337] Pkg id mochi-margo-0.9.2-xvj7oakacuvsigkxudndfdywp2ekggir has the following dependents:
nfs2/mdorier/spack/lib/spack/spack/installer.py:1407 ==> [2021-04-21-08:45:20.230897] Ensure all dependencies know all dependents across specs
nfs2/mdorier/spack/lib/spack/spack/installer.py:961 ==> [2021-04-21-08:45:20.246422] Acquiring a write lock on argobots-1.1-u2glvj7qojowtqmzi4j6us3gxikg72ke with timeout 1e-09
nfs2/mdorier/spack/lib/spack/spack/stage.py:313 ==> [2021-04-21-08:45:20.266243] Creating stage lock spack-stage-argobots-1.1-u2glvj7qojowtqmzi4j6us3gxikg72ke
nfs2/mdorier/spack/lib/spack/spack/main.py:775 ==> [2021-04-21-08:45:20.285905] SpecHashCollisionError: Specs argobots@1.1%gcc@8.2.1~affinity~debug+perf~stackunwind~tool~valgrind stackguard=no arch=linux-ubuntu16.04-skylake and argobots@1.1%gcc@8.2.1~affinity~debug+perf~stackguard~stackunwind~tool~valgrind arch=linux-ubuntu16.04-skylake have the same SHA-1 prefix!
nfs2/mdorier/spack/lib/spack/spack/error.py:55 ==> [2021-04-21-08:45:20.300089] Error: Specs argobots@1.1%gcc@8.2.1~affinity~debug+perf~stackunwind~tool~valgrind stackguard=no arch=linux-ubuntu16.04-skylake and argobots@1.1%gcc@8.2.1~affinity~debug+perf~stackguard~stackunwind~tool~valgrind arch=linux-ubuntu16.04-skylake have the same SHA-1 prefix!
Traceback (most recent call last):
  File "/nfs2/mdorier/spack/lib/spack/spack/main.py", line 772, in main
    return _invoke_command(command, parser, args, unknown)
  File "/nfs2/mdorier/spack/lib/spack/spack/main.py", line 496, in _invoke_command
    return_val = command(parser, args)
  File "/nfs2/mdorier/spack/lib/spack/spack/cmd/install.py", line 406, in install
    install_specs(args, kwargs, zip(abstract_specs, specs))
  File "/nfs2/mdorier/spack/lib/spack/spack/cmd/install.py", line 216, in install_specs
    builder.install()
  File "/nfs2/mdorier/spack/lib/spack/spack/installer.py", line 1513, in install
    self._prepare_for_install(task)
  File "/nfs2/mdorier/spack/lib/spack/spack/installer.py", line 832, in _prepare_for_install
    if not partial and self.layout.check_installed(task.pkg.spec) and (
  File "/nfs2/mdorier/spack/lib/spack/spack/directory_layout.py", line 375, in check_installed
    raise SpecHashCollisionError(spec, installed_spec)
spack.directory_layout.SpecHashCollisionError: Specs argobots@1.1%gcc@8.2.1~affinity~debug+perf~stackunwind~tool~valgrind stackguard=no arch=linux-ubuntu16.04-skylake and argobots@1.1%gcc@8.2.1~affinity~debug+perf~stackguard~stackunwind~tool~valgrind arch=linux-ubuntu16.04-skylake have the same SHA-1 prefix!
```

### Information on your system

* **Spack:** 0.16.1-2330-8182994
* **Python:** 3.5.2
* **Platform:** linux-ubuntu16.04-skylake
* **Concretizer:** original

This problem was repeated on multiple other systems.

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by carns** [comment] 2021-04-21 13:54
Tagging @shintaro-iwasaki so he is aware also.

**Comment by mdorier** [comment] 2021-04-21 13:56
I can fix the problem by changing `no` to `none` in the argobots package, so I think somehow Spack considers`variant=no` as equivalent to `~variant`.

**Comment by shintaro-iwasaki** [comment] 2021-04-21 14:37
Thanks. @mdorier No matter whether this issue can/will be fixed in Spack or not, I should update the `argobots` package if changing `no` to `none` is the easiest fix so far.

I will submit a patch in a couple of days (as I would like to fix other things as well pointed out by @carns).

**Comment by scheibelp** [comment] 2021-04-21 17:46
> I should update the argobots package if changing no to none is the easiest fix so far.

@shintaro-iwasaki that would be an excellent short-term fix (and the Spack devs will need to update a longer-term fix)

In more detail:

I think this is occurring because of underlying YAML representations Spack uses to compute the hash. "no" can be represented as a boolean in YAML (https://yaml.org/type/bool.html). I think enclosing those strings in quotes would help (https://stackoverflow.com/questions/53648244/specifying-the-string-value-yes-in-a-yaml-property) although apparently YAML version 1.2 would generally resolve this (whether our vendored YAML library supports that or can be updated to follow that I'd have to check).

**Comment by scheibelp** [comment] 2021-04-23 21:49
This particular instance of the problem is fixed by https://github.com/spack/spack/pull/23171 (thanks @mdorier!)

In general in the future #23191 should allow packages to define variants with "no" as a possible value

**Closed as completed by scheibelp** 2021-04-23 21:49 UTC
Labels: bug, impact-medium
