### ISSUE TITLE
spack checksum now broken for lammps

### ISSUE THREAD

**Issue by rbberger** [LLNL/spack#40767] opened 2023-10-30 05:19 UTC
### Steps to reproduce

Previously, when I wanted to add a new version, I could provide a new version string which then got converted via `url_for_version` to the correct URL. E.g.
```console
spack checksum lammps@20230802
```
would produce the version line I would want to add to my package.

### Error message

However, what seems now to happen is that remote versions are fetched from GitHub (regardless of whether I just want a specific checksum) and somehow converted to what is believed to be the version based on the URL: (e.g. `15Jun2023`). When that version string is passed to the `url_for_version`, we obviously now get an error.
```console
 spack --debug --stacktrace checksum lammps@20230802
lib/spack/spack/config.py:988 ==> [2023-10-29-23:11:59.491964] Reading config from file /home/richard/GitHub/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:988 ==> [2023-10-29-23:11:59.511972] Reading config from file /home/richard/GitHub/spack/var/spack/environments/lammps_default/spack.yaml
lib/spack/spack/config.py:988 ==> [2023-10-29-23:11:59.515954] Reading config from file /home/richard/GitHub/spack/etc/spack/defaults/config.yaml
lib/spack/spack/environment/environment.py:211 ==> [2023-10-29-23:11:59.535199] Using environment 'lammps_default'
lib/spack/spack/cmd/__init__.py:121 ==> [2023-10-29-23:11:59.543910] Imported checksum from built-in commands
lib/spack/spack/cmd/__init__.py:121 ==> [2023-10-29-23:11:59.544730] Imported checksum from built-in commands
lib/spack/spack/config.py:988 ==> [2023-10-29-23:11:59.546421] Reading config from file /home/richard/GitHub/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:988 ==> [2023-10-29-23:11:59.682379] Reading config from file /home/richard/GitHub/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:988 ==> [2023-10-29-23:11:59.714274] Reading config from file /home/richard/GitHub/spack/etc/spack/packages.yaml
lib/spack/spack/util/web.py:585 ==> [2023-10-29-23:11:59.741996] SPIDER: [depth=0, max_depth=0, urls=4]
lib/spack/spack/util/web.py:706 ==> [2023-10-29-23:12:00.082553] Error in _spider: <class 'spack.util.web.SpackWebError'>:Download failed: GET https://github.com/lammps/lammps/archive/ returned 404: Not Found
  Traceback (most recent call last):
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 145, in read_from_url
    response = urlopen(request)
               ^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/llnl/util/lang.py", line 834, in __call__
    return self.instance(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 81, in dispatch_open
    return opener.open(fullurl, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 59, in http_error_default
    raise DetailedHTTPError(req, code, msg, hdrs, fp)
spack.util.web.DetailedHTTPError: GET https://github.com/lammps/lammps/archive/ returned 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 628, in _spider
    response_url, _, response = read_from_url(url, "text/html")
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 147, in read_from_url
    raise SpackWebError("Download failed: {}".format(str(err)))
spack.util.web.SpackWebError: Download failed: GET https://github.com/lammps/lammps/archive/ returned 404: Not Found

lib/spack/spack/util/web.py:709 ==> [2023-10-29-23:12:00.084926] SPIDER: [url=ParseResult(scheme='https', netloc='github.com', path='/lammps/lammps/archive/', params='', query='', fragment='')]
lib/spack/spack/util/web.py:706 ==> [2023-10-29-23:12:00.161862] Error in _spider: <class 'spack.util.web.SpackWebError'>:Download failed: GET https://github.com/lammps/lammps/archive returned 404: Not Found
  Traceback (most recent call last):
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 145, in read_from_url
    response = urlopen(request)
               ^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/llnl/util/lang.py", line 834, in __call__
    return self.instance(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 81, in dispatch_open
    return opener.open(fullurl, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 59, in http_error_default
    raise DetailedHTTPError(req, code, msg, hdrs, fp)
spack.util.web.DetailedHTTPError: GET https://github.com/lammps/lammps/archive returned 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 628, in _spider
    response_url, _, response = read_from_url(url, "text/html")
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 147, in read_from_url
    raise SpackWebError("Download failed: {}".format(str(err)))
spack.util.web.SpackWebError: Download failed: GET https://github.com/lammps/lammps/archive returned 404: Not Found

lib/spack/spack/util/web.py:709 ==> [2023-10-29-23:12:00.165378] SPIDER: [url=ParseResult(scheme='https', netloc='github.com', path='/lammps/lammps/archive', params='', query='', fragment='')]
lib/spack/spack/util/web.py:653 ==> [2023-10-29-23:12:05.204181] Error reading fragment: (<class 'spack.util.web.SpackWebError'>, 'Download failed: GET https://github.com/lammps/lammps/security/overall-count returned 404: Not Found'):Traceback (most recent call last):
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 145, in read_from_url
    response = urlopen(request)
               ^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/llnl/util/lang.py", line 834, in __call__
    return self.instance(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 81, in dispatch_open
    return opener.open(fullurl, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 59, in http_error_default
    raise DetailedHTTPError(req, code, msg, hdrs, fp)
spack.util.web.DetailedHTTPError: GET https://github.com/lammps/lammps/security/overall-count returned 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 650, in _spider
    fragment_response_url, _, fragment_response = read_from_url(abs_link, "text/html")
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 147, in read_from_url
    raise SpackWebError("Download failed: {}".format(str(err)))
spack.util.web.SpackWebError: Download failed: GET https://github.com/lammps/lammps/security/overall-count returned 404: Not Found

lib/spack/spack/util/web.py:709 ==> [2023-10-29-23:12:05.282100] SPIDER: [url=ParseResult(scheme='https', netloc='github.com', path='/lammps/lammps/releases', params='', query='', fragment='')]
lib/spack/spack/util/web.py:653 ==> [2023-10-29-23:12:05.476089] Error reading fragment: (<class 'spack.util.web.SpackWebError'>, 'Download failed: GET https://github.com/lammps/lammps/security/overall-count returned 404: Not Found'):Traceback (most recent call last):
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 145, in read_from_url
    response = urlopen(request)
               ^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/llnl/util/lang.py", line 834, in __call__
    return self.instance(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 81, in dispatch_open
    return opener.open(fullurl, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 59, in http_error_default
    raise DetailedHTTPError(req, code, msg, hdrs, fp)
spack.util.web.DetailedHTTPError: GET https://github.com/lammps/lammps/security/overall-count returned 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 650, in _spider
    fragment_response_url, _, fragment_response = read_from_url(abs_link, "text/html")
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/util/web.py", line 147, in read_from_url
    raise SpackWebError("Download failed: {}".format(str(err)))
spack.util.web.SpackWebError: Download failed: GET https://github.com/lammps/lammps/security/overall-count returned 404: Not Found

lib/spack/spack/util/web.py:709 ==> [2023-10-29-23:12:05.559520] SPIDER: [url=ParseResult(scheme='https', netloc='github.com', path='/lammps/lammps/releases/', params='', query='', fragment='')]
15Jun2023
Traceback (most recent call last):
  File "/home/richard/GitHub/spack/bin/spack", line 52, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/main.py", line 1022, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/main.py", line 977, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/main.py", line 1005, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/main.py", line 646, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/cmd/checksum.py", line 121, in checksum
    remote_versions = pkg.fetch_remote_versions(args.jobs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/package_base.py", line 2375, in fetch_remote_versions
    return spack.url.find_versions_of_archive(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/lib/spack/spack/url.py", line 704, in find_versions_of_archive
    if url == reference_package.url_for_version(ver):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/GitHub/spack/var/spack/repos/builtin/packages/lammps/package.py", line 370, in url_for_version
    if len(split_ver) < 2:
            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '15Jun2023' does not match format '%Y%m%d'

```

### Information on your system

* **Spack:** 0.21.0.dev0 (2a797f90b431d33f609dc1d92b2908f5734f4d50)
* **Python:** 3.11.5
* **Platform:** linux-arch-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by rbberger** [comment] 2023-10-30 05:48
Even if I make `url_from_version` more "robust" to handle both cases (`15Jun2023` and `20230802`), that has two more issues:
(1) The `spack checksum` output now shows the wrong version format. (2) There is still an error for the simple case of trying to verify the checksum of an existing version. This also happens with other packages, e.g.:
```console
$ spack checksum intel-oneapi-vpl@2023.1.0
==> Error: max() arg is an empty sequence
```

**Comment by alalazo** [comment] 2023-10-30 07:12
@haampie fyi

**Comment by haampie** [comment] 2023-10-31 12:11
@rbberger the change is that 

```
spack checksum pkg@x
```

uses the web crawler/spider to detect versions matching `x`. (For example `spack checksum cmake@3.12` gives you all detected `3.12.x` releases instead of the non-existing `3.12` version)

The error you see was already there in Spack 0.20:

```
$ spack checksum lammps
==> Error: time data '15Jun2023' does not match format '%Y%m%d'
```

If you wanna checksum a specific known version, without spidering the Github release page, use 

```
spack checksum lammps 20230802
```

I'll 

1. submit a small fix for the empty sequence error
2. improve the `spack checksum --help` signature

**Comment by haampie** [comment] 2023-10-31 12:47
See #40799 and #40800

**Comment by rbberger** [comment] 2023-10-31 15:51
@haampie Ok. While that fixes my use case, that still produces wrong versions for `spack checksum lammps` and other packages (e.g. some intel packages). Is there already a mechanism in place for a package to define a method to help decode a URL to a version string that I'm simply missing (the opposite of `url_for_version`)? For LAMMPS `spack checksum` finds things like `15Jun2023`, which should become `20230615` to be consistent.

**Comment by haampie** [comment] 2023-10-31 15:59
I think I'll close this specific issue since the regressions have been fixed, and the `lammps` / `intel` packages cases have never worked well with the crawler.

Feel free to create a separate issue for improving detection of oddly versioned packages ;p I'm not sure how much interest there is in fixing that though.

**Closed as completed by haampie** 2023-10-31 15:59 UTC
Labels: bug, triage
