### ISSUE TITLE
Uninstall that would require a true reinstall

### ISSUE THREAD

**Issue by BarrySmith** [LLNL/spack#2050] opened 2016-10-18 23:31 UTC
==> Do you want to proceed ? [y/n]
y
==> Successfully uninstalled xsdk@develop%gcc@4.9.0+trilinos arch=linux-Ubuntu12-x86_64-gm2glsk
==> Successfully uninstalled xsdk@master%gcc@4.9.0+trilinos arch=linux-Ubuntu12-x86_64-4fi65tq
==> Successfully uninstalled trilinos@12.6.2%gcc@4.9.0+boost~debug+hdf5+hypre+metis~mumps~python+shared~suite-sparse+superlu-dist arch=linux-Ubuntu12-x86_64-xqfuwzn
==> Successfully uninstalled trilinos@develop%gcc@4.9.0+boost~debug+hdf5+hypre+metis~mumps~python+shared~suite-sparse+superlu-dist arch=linux-Ubuntu12-x86_64-o4e4f4u
/sandbox/bsmith/spack/bin (develop *=) 
$ ./spack install xsdk
==> xsdk is already installed in /scratch/bsmith/spack/opt/spack/linux-Ubuntu12-x86_64/gcc-4.9.0/xsdk-0.2.0-gt56pofzvdpnen6u2ozludln2xtu53w6
/sandbox/bsmith/spack/bin (develop *=) 
$ ./spack purge
/sandbox/bsmith/spack/bin (develop *=) 
$ ./spack reindex
/sandbox/bsmith/spack/bin (develop *=) 
$ ./spack install xsdk
==> xsdk is already installed in /scratch/bsmith/spack/opt/spack/linux-Ubuntu12-x86_64/gcc-4.9.0/xsdk-0.2.0-gt56pofzvdpnen6u2ozludln2xtu53w6
/sandbox/bsmith/spack/bin (develop *=) 

Even though I uninstalled it it won't do a reinstall. 

I made some changes to the trilinos/package.py and so want to rebuild trilinos from scratch, how do I get that to happen?

**Comment by tgamblin** [comment] 2016-10-19 01:11
The one installed is /gt56 but you uninstalled /gm2g... either first uninstall all xsdk:

spack uninstall -a xsdk

Or be specific about the uninstall: 

spack uninstall /gt56
Or
spack uninstall xsdk@0.2.0

Or about the install:

spack install xsdk@develop

Not sure why the develop isn't being preferred on install.  Did you mark 0.1.0 as the preferred version?

**Comment by BarrySmith** [comment] 2016-10-19 02:11
I did 

./spack uninstall --dependents -a trilinos

which by my upderstanding should have uninstalled all the xsdk version and all the trilinos version.

Does the uninstall truly delete everything or does it just mark it as unstalled and perhaps spack does not properly check this mark at for example install?
_

**Comment by adamjstewart** [comment] 2017-04-13 18:04
@BarrySmith Have you seen this bug since October?

**Comment by BarrySmith** [comment] 2017-04-13 18:13
No

**Comment by adamjstewart** [comment] 2017-04-13 18:17
I've never seen this behavior before. This package isn't in Spack, so I assume it's still in development? I assume xsdk depends on trilinos? Perhaps you had an old xsdk package installed before the trilinos dependency was added. Do you mind if I close this issue since it can't be reproduced?

**Comment by BarrySmith** [comment] 2017-04-13 18:26
close it

**Closed** 2017-04-13 18:26 UTC
Labels: xSDK
