### ISSUE TITLE
Installation issue: py-scipy

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#28728] opened 2022-02-02 17:10 UTC
### Steps to reproduce the issue

The install works correctly but the package is broken afterwards. It appears to be an occurance of this issue: https://github.com/scipy/scipy/issues/15414

```
wspear@yu:~$ spack load py-scipy
wspear@yu:~$ python3 -c "import scipy.linalg._interpolative"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /home/wspear/bin/SPACK/spack/opt/spack/linux-ubuntu20.04-westmere/gcc-9.3.0/py-scipy-1.7.3-yjdwpwx74jbeo4mmh2igxeaupp465tnf/lib/python3.8/site-packages/scipy/linalg/_interpolative.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZGVbN2v_cos
wspear@yu:~$ spack find -dvl py-scipy
==> 1 installed package
-- linux-ubuntu20.04-westmere / gcc@9.3.0 -----------------------
yjdwpwx py-scipy@1.7.3
kyad4k4     openblas@0.3.19~bignuma~consistent_fpcsr~ilp64+locking+pic+shared symbol_suffix=none threads=none
ilqsgga     py-numpy@1.22.1+blas+lapack patches=873745d7b547857fcfec9cae90b09c133b42a4f0c23b6c2d84cf37e2dd816604
k7czfnf         py-setuptools@57.4.0
tpq4du5             python@3.8.12+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87,4c2457325f2b608b1b6a2c63087df8c26e07db3e3d493caf36a56f0ecf6fb768,f2fd060afc4b4618fe8104c4c5d771f36dc55b1db5a4623785a4ea707ec72fb4
4sqa6k7                 bzip2@1.0.8~debug~pic+shared
ebv4gza                 expat@2.4.4+libbsd
rlyv4lr                     libbsd@0.11.3
fdee4wa                         libmd@1.0.3
wjsgynz                 gdbm@1.22
u3x32au                     readline@8.1
nv2nzui                         ncurses@6.2~symlinks+termlib abi=none
5vb6tuq                 gettext@0.21+bzip2+curses+git~libunistring+libxml2+tar+xz
hr7nra6                     libiconv@1.16 libs=shared,static
d6gcgnl                     libxml2@2.9.12~python
2rm5ckj                         xz@5.2.4~pic libs=shared,static
2ee2xuq                         zlib@1.2.11+optimize+pic+shared
7pbwp76                     tar@1.34
zqovoh3                 libffi@3.3 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0
vb7wrtr                 openssl@1.1.1m~docs certs=system
g5xmxcq                 sqlite@3.31.1+column_metadata+dynamic_extensions+fts~functions+rtree
geqrhy2                 util-linux-uuid@2.36.2
u2thfr5     py-pybind11@2.7.1~ipo build_type=RelWithDebInfo
pqitzyp     py-pythran@0.9.12 patches=b427dcaaa74ed4dfa39c58819e446e86055b65648826a101c08634d3c0be1f95
h3jldge         py-beniget@0.4.1
noemlgr             py-gast@0.5.3
5efq7uo         py-ply@3.11
```

### Information on your system

* **Spack:** 0.17.1-1052-b9bb303063
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-westmere
* **Concretizer:** clingo

### Additional information

No applicable install logs.
@adamjstewart 
@yang

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment] 2022-02-02 17:12
Duplicate of #28642

**Closed as completed by adamjstewart** 2022-02-02 17:12 UTC
Labels: duplicate, build-error
