### ISSUE TITLE
cannot concretize when cflags is set as part of the compiler AND part of the spec

### ISSUE THREAD

**Issue by lukebroskop** [LLNL/spack#44662] opened 2024-06-10 21:50 UTC
### Steps to reproduce

# activate environment with the following spack.yaml

```
# This is a Spack Environment file.
#
spack:
  compilers:
  - compiler:
      spec: cce@17.0.1
      paths:
        cc: /opt/cray/pe/cce/17.0.1/bin/craycc
        cxx: /opt/cray/pe/cce/17.0.1/bin/crayCC
        f77: /opt/cray/pe/cce/17.0.1/bin/crayftn
        fc: /opt/cray/pe/cce/17.0.1/bin/crayftn
      flags:
        ldflags: "-Wl,--undefined-version -fPIC"
        cflags: "-Wno-implicit-function-declaration -fPIC"
        cxxflags: "-Wno-implicit-function-declaration -fPIC"
      operating_system: sles15
      target: any
      modules: []
      environment: {}
      extra_rpaths: []
  packages:
    all:
      compiler: [cce@17.0.1]
  specs:
  - mpip%cce cflags="-Wno-implicit-int"
 ```

# concretize
```
(1) lroskop@pinoak-login1:/cray/css/perfeng/lroskop/spack/test spack concretize -f
==> Error: {'-Wno-implicit-int'} does not equal {'-Wno-implicit-int', '-fPIC', '-Wno-implicit-function-declaration'}
```

### Error message

Error in Debug mode
```
(1) lroskop@pinoak-login1:/cray/css/perfeng/lroskop/spack/test spack  -d concretize -f
==> [2024-06-10-16:47:14.004812] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/config.yaml
==> [2024-06-10-16:47:14.124235] Reading config from file /cray/css/perfeng/lroskop/spack/test/spack.yaml
==> [2024-06-10-16:47:14.166132] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/config.yaml
==> [2024-06-10-16:47:14.249673] Reading config from file /cray/css/perfeng/lroskop/spack/test/spack.yaml
==> [2024-06-10-16:47:14.278849] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/config.yaml
==> [2024-06-10-16:47:14.362342] Reading config from file /cray/css/perfeng/lroskop/spack/test/spack.yaml
==> [2024-06-10-16:47:14.390492] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/config.yaml
==> [2024-06-10-16:47:14.475038] Using environment '/cray/css/perfeng/lroskop/spack/test'
==> [2024-06-10-16:47:14.493330] Imported concretize from built-in commands
==> [2024-06-10-16:47:14.494616] Imported concretize from built-in commands
==> [2024-06-10-16:47:14.524373] Reading config from file /cray/css/perfeng/lroskop/spack/test/spack.yaml
==> [2024-06-10-16:47:14.550683] Deactivated environment '/cray/css/perfeng/lroskop/spack/test'
==> [2024-06-10-16:47:14.552918] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/config.yaml
==> [2024-06-10-16:47:14.637766] Reading config from file /cray/css/perfeng/lroskop/spack/test/spack.yaml
==> [2024-06-10-16:47:14.680026] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/config.yaml
==> [2024-06-10-16:47:14.764518] Reading config from file /cray/css/perfeng/lroskop/spack/test/spack.yaml
==> [2024-06-10-16:47:14.792514] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/config.yaml
==> [2024-06-10-16:47:14.876826] Reading config from file /cray/css/perfeng/lroskop/spack/test/spack.yaml
==> [2024-06-10-16:47:14.904644] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/config.yaml
==> [2024-06-10-16:47:14.988814] Using environment '/cray/css/perfeng/lroskop/spack/test'
==> [2024-06-10-16:47:14.989907] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/concretizer.yaml
==> [2024-06-10-16:47:15.020383] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/repos.yaml
==> [2024-06-10-16:47:18.808069] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/packages.yaml
==> [2024-06-10-16:47:18.940387] DATABASE LOCK TIMEOUT: 60s
==> [2024-06-10-16:47:18.940506] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-06-10-16:47:20.213288] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/mirrors.yaml
==> [2024-06-10-16:47:20.447977] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-06-10-16:47:20.465600] Reading config from file /cray/css/perfeng/lroskop/spack/test/spack.yaml
==> [2024-06-10-16:47:20.482792] Deactivated environment '/cray/css/perfeng/lroskop/spack/test'
==> [2024-06-10-16:47:20.500482] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/repos.yaml
==> [2024-06-10-16:47:20.507458] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2024-06-10-16:47:20.508224] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-06-10-16:47:20.524716] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults
==> [2024-06-10-16:47:20.524774] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/linux
==> [2024-06-10-16:47:20.524823] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/users/lroskop/.spack/bootstrap/config
==> [2024-06-10-16:47:20.524863] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/users/lroskop/.spack/bootstrap/config/linux
==> [2024-06-10-16:47:20.526679] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/config.yaml
==> [2024-06-10-16:47:20.580598] Reading config from file /home/users/lroskop/.spack/bootstrap/config/linux/config.yaml
==> [2024-06-10-16:47:20.608319] DATABASE LOCK TIMEOUT: 60s
==> [2024-06-10-16:47:20.608389] PACKAGE LOCK TIMEOUT: No timeout
==> [2024-06-10-16:47:20.608894] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/packages.yaml
==> [2024-06-10-16:47:20.687100] Reading config from file /home/users/lroskop/.spack/bootstrap/config/packages.yaml
==> [2024-06-10-16:47:20.708403] Reading config from file /home/users/lroskop/.spack/bootstrap/config/linux/compilers.yaml
==> [2024-06-10-16:47:20.841055] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
==> [2024-06-10-16:47:20.841763] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/bootstrap.yaml
==> [2024-06-10-16:47:20.867177] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
==> [2024-06-10-16:47:20.877553] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/modules.yaml
==> [2024-06-10-16:47:20.901620] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/linux/modules.yaml
==> [2024-06-10-16:47:21.203215] Adding env modifications for patchelf
==> [2024-06-10-16:47:21.293808] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
==> [2024-06-10-16:47:21.295450] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2024-06-10-16:47:21.295517] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2024-06-10-16:47:21.511271] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.6/t4yf34cuvquqp5xd66zybmcfyhwbdlsf" provides the "clingo" Python module
==> [2024-06-10-16:47:21.513566] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/config.yaml
==> [2024-06-10-16:47:21.583259] Reading config from file /cray/css/perfeng/lroskop/spack/test/spack.yaml
==> [2024-06-10-16:47:21.606045] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/config.yaml
==> [2024-06-10-16:47:21.673740] Using environment '/cray/css/perfeng/lroskop/spack/test'
==> [2024-06-10-16:47:21.674265] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/concretizer.yaml
==> [2024-06-10-16:47:21.722123] Reading config from file /cray/css/perfeng/lroskop/spack/spack/etc/spack/defaults/packages.yaml
==> [2024-06-10-16:47:26.290522] Reading config from file /home/users/lroskop/.spack/linux/compilers.yaml
==> [2024-06-10-16:47:59.673414] UNKNOWN SYMBOL: attr("virtual_on_incoming_edges", NodeArgument(id='0', pkg='util-linux-uuid'), uuid)
==> [2024-06-10-16:47:59.675169] UNKNOWN SYMBOL: attr("virtual_on_incoming_edges", NodeArgument(id='0', pkg='libunwind'), unwind)
==> [2024-06-10-16:47:59.677300] UNKNOWN SYMBOL: attr("virtual_on_incoming_edges", NodeArgument(id='0', pkg='zlib'), zlib-api)
==> [2024-06-10-16:47:59.677691] UNKNOWN SYMBOL: attr("virtual_on_incoming_edges", NodeArgument(id='0', pkg='cray-mpich'), mpi)
==> [2024-06-10-16:47:59.677799] UNKNOWN SYMBOL: attr("virtual_on_incoming_edges", NodeArgument(id='0', pkg='libiconv'), iconv)
Traceback (most recent call last):
  File "/cray/css/perfeng/lroskop/spack/spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/cray/css/perfeng/lroskop/spack/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
  File "/cray/css/perfeng/lroskop/spack/spack/lib/spack/spack/main.py", line 1068, in main
    return _main(argv)
  File "/cray/css/perfeng/lroskop/spack/spack/lib/spack/spack/main.py", line 1021, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
  File "/cray/css/perfeng/lroskop/spack/spack/lib/spack/spack/main.py", line 1051, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/cray/css/perfeng/lroskop/spack/spack/lib/spack/spack/main.py", line 648, in _invoke_command
    return_val = command(parser, args)
  File "/cray/css/perfeng/lroskop/spack/spack/lib/spack/spack/cmd/concretize.py", line 44, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/cray/css/perfeng/lroskop/spack/spack/lib/spack/spack/environment/environment.py", line 1241, in concretize
    return self._concretize_together(tests=tests)
  File "/cray/css/perfeng/lroskop/spack/spack/lib/spack/spack/environment/environment.py", line 1361, in _concretize_together
    *specs_to_concretize, tests=tests
  File "/cray/css/perfeng/lroskop/spack/spack/lib/spack/spack/concretize.py", line 741, in concretize_specs_together
    return _concretize_specs_together_new(*abstract_specs, **kwargs)
  File "/cray/css/perfeng/lroskop/spack/spack/lib/spack/spack/concretize.py", line 750, in _concretize_specs_together_new
    abstract_specs, tests=kwargs.get("tests", False), allow_deprecated=allow_deprecated
  File "/cray/css/perfeng/lroskop/spack/spack/lib/spack/spack/solver/asp.py", line 3549, in solve
    setup, specs, reuse=reusable_specs, output=output, allow_deprecated=allow_deprecated
  File "/cray/css/perfeng/lroskop/spack/spack/lib/spack/spack/solver/asp.py", line 822, in solve
    answers = builder.build_specs(spec_attrs)
  File "/cray/css/perfeng/lroskop/spack/spack/lib/spack/spack/solver/asp.py", line 3342, in build_specs
    self.reorder_flags()
  File "/cray/css/perfeng/lroskop/spack/spack/lib/spack/spack/solver/asp.py", line 3266, in reorder_flags
    assert set(compiler_flags) == set(ordered_compiler_flags), msg
AssertionError: set() does not equal {'-fPIC', '-Wno-implicit-function-declaration'}
```

### Information on your system

(1) lroskop@pinoak-login1:/cray/css/perfeng/lroskop/spack/test spack debug report
* **Spack:** 0.22.0.dev0 (07fb83b493d522ef5369e4db565841674b4512c1)
* **Python:** 3.6.15
* **Platform:** linux-sles15sp5-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2024-06-20 12:04
Duplicate of #38664

**Comment by alalazo** [comment] 2024-06-20 12:05
I'll raise the other bug report in priority. @lukebroskop Feel free to comment there

**Closed as not planned** 2024-06-20 12:04 UTC
Labels: bug, duplicate, cray, e4s
