### ISSUE TITLE
making HIP and ROCM more robust

### ISSUE THREAD

**Issue by mwkrentel** [LLNL/spack#20132] opened 2020-11-27 02:45 UTC
The HIP and ROCM packages for AMD GPU's have a lot of dependencies and
often do not build cleanly.  I'd like to use this issue for a
discussion of problems and solutions for making `spack install hip`
work more robustly.

----------

(1) Here's where I'm currently stuck at `spack install comgr`.

This is on x86_64, RH 8.2, gcc 8.3.1, spack at commit 676d68a979 on
Nov 18, just after 0.16.0 and just before a couple of troublesome
commits for ROCM.  The RH HIP/ROCM packages for 3.8.0 are installed at
/opt/rocm.  But I'm also trying to build in spack from scratch.

```
% spack install -v comgr @3.8.0
...
Call Stack (most recent call first):
  /home/krentel/rocm/160/install/linux-rhel8-x86_64/gcc-8.3.1/cmake-3.15.7-papjvxann3gzrdnc75na4
  x7qk7gv3lq7/share/cmake-3.15/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /opt/rocm/hip/lib/cmake/hip/hip-config.cmake:112 (find_dependency)
  test/CMakeLists.txt:122 (find_package)
...
1 error found in build log:
  >> 27    CMake Error at /home/krentel/rocm/160/spack-repo/build-stage/spack-stage-comgr-3.8.0-2celuqx77r52he
           uhiub4awesu4iln567/spack-build-2celuqx/lib/cmake/amd_comgr/amd_comgr-config.cmake:3 (include):
     28      The file
     29    
     30        /home/krentel/rocm/160/spack-repo/build-stage/spack-stage-comgr-3.8.0-2celuqx77r52heuhiub4awesu
           4iln567/spack-build-2celuqx/lib/cmake/amd_comgr/amd_comgr-targets.cmake
     31    
     32      was generated by the export() command.  It may not be used as the argument
     33      to the include() command.  Use ALIAS targets instead to refer to targets by
```

The error is something in cmake about improperly using the output of
export() as the argument for include().  But note that the call stack
includes a cmake file from /opt/rocm/.  I have a full HIP install at
/opt/rocm, but nothing in spack ever refers to it, so this should not
happen.

And indeed, if I move /opt/rocm/ out of the way, then the build
succeeds.  So, the problem is that the ROCM cmake files are looking
into /opt/rocm/ when spack is trying to build everything from scratch.

This is probably something that needs to be fixed at the ROCM level,
outside of spack.  Theoretically, spack could add patches, but it
really needs to be fixed in ROCM/comgr.

I suspect there is a general problem that the ROCM cmake files are
looking into /opt/rocm/ and /usr when they shouldn't.  For example,
this is what the patches in llvm-amdgpu are doing for ncurses and
zlib, fixing cmake to prefer the spack builds over /usr.

Anyway, this is problem 1, where I'm stuck now.

@srekolam @haampie You want to add your war stories or solutions?

**Comment by haampie** [comment] 2020-11-27 08:58
I usually open a PR on the ROCm package, and then add a patch to spack. The problem is that upstream PRs remain open for a long time and sometimes do not get merged.

In this case, you want to make sure that comgr does not build the tests:

https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/blob/amd-stg-open/lib/comgr/test/CMakeLists.txt#L123

which apparently looks for an installation of hip although comgr is in our a case a dependency of hip itself :upside_down_face: 

The LLVM issues you're pointing out are really issues with LLVM itself. They should be fixed in LLVM 12 at least.

**Comment by mwkrentel** [comment] 2020-12-10 23:57
I took another look at this and decided that comgr was actually the
last build failure.  So, less of an issue than what I initially thought.

I used @haampie's suggestion and disabled the search for hip in
/opt/rocm.  Spack builds should not be looking in /opt/rocm.  That was
the smallest change to fix the build.  See PR #20330.

Btw, I know there are other places in the ROCM packages that use
find_package() for HIP/ROCM packages in /opt.  For example, in
comgr/CMakeLists.txt has:

```
find_package(ROCM PATHS "/opt/rocm")
if (ROCM_FOUND)
  include(ROCMSetupVersion)
  rocm_setup_version(VERSION "${amd_comgr_VERSION}")
endif()
```

Spack builds should not be using files in /opt/rocm.  For one thing,
you don't know that it's even the same version.  (And each new version
breaks the previous API.)  Spack wants to build all the pieces itself.

But so far, it doesn't break the build.  So, until I find an specific
example where this causes trouble, we'll leave it alone.

**Comment by haampie** [comment] 2020-12-11 07:57
I believe the search order for find_package(.. PATHS ...) is such that the literal path there are considered last. Spack provides general search paths as arguments when calling cmake. So it should work, but I agree the rocm assumptions about where things are installed are a pain.

**Closed as completed** 2020-12-15 12:55 UTC
Labels: AMD
