### ISSUE TITLE
Gitlab CI generator does not check included config files

### ISSUE THREAD

**Issue by qwofford** [LLNL/spack#24507] opened 2021-06-24 19:47 UTC
In order to generate a gitlab CI dynamic pipeline, you need to make sure "mirrors" keyword is defined in `spack.yaml` itself. If the mirror is in an external config file, I get an error message.

### Steps to reproduce the issue

```console
-bash-4.2$ spack ci generate
==> Warning: included configuration files should be updated manually [files=./, ../config.yaml, ../mirrors.yaml, ../modules.yaml, ../repos.yaml]
==> Error: spack ci generate requires an env containing a mirror
```

**Comment by alalazo** [comment] 2021-06-28 08:26
Duplicate of #24512

**Comment by alalazo** [comment] 2021-06-28 08:27
@qwofford I marked this issue as a duplicate, since it seems to me exactly the same as #24512. Let me know if I missed any detail and these are indeed two different issues.

**Comment by alalazo** [comment] 2023-04-06 09:31
Closing the duplicate

**Closed as not planned by alalazo** 2023-04-06 09:31 UTC
Labels: bug, triage
