### ISSUE TITLE
autoconf build partially non-functional when install_tree is padded (sbang ??)

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#19629] opened 2020-10-30 16:35 UTC
Using `spack@develop` checked out at:
* `52959528a2cb7e7e9b213efd1243a078502ac708`
* `Thu Oct 29 21:29:39 2020 +0100`

This checkout *includes* commit `sbang: vendor sbang`

`Automake` build fails due to non-functional `autoconf` when `install_tree: $padding:128`

```
$> spack install automake
....
==> Installing automake
==> Using cached archive: /opt/spack/var/spack/cache/_source-cache/archive/b2/b2f361094b410b4acbf4efba7337bdb786335ca09eb2518635a09fb7319ca5c1.tar.gz
==> automake: Executing phase: 'autoreconf'
==> automake: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/tmp/root/spack-stage/spack-stage-automake-1.16.2-lu2sautwpii24tkqbbo2at3gfju2zki7/spack-src/configure' '--prefix=/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_pl/linux-ubuntu18.04-ppc64le/gcc-7.5.0/automake-1.16.2-lu2sautwpii24tkqbbo2at3gfju2zki7'

1 error found in build log:
     17    checking for byacc... no
     18    checking for bison... no
     19    checking for lex... no
     20    checking for flex... no
     21    checking whether autoconf is installed... yes
     22    checking whether autoconf works... no
  >> 23    configure: error: The installed version of autoconf does not work.
     24        Please check config.log for error messages before this one.

See build log for details:
  /tmp/root/spack-stage/spack-stage-automake-1.16.2-lu2sautwpii24tkqbbo2at3gfju2zki7/spack-build-out.txt
```

From `config.log` (full log attached below): 

```
...
configure:3027: cd conftest && autoconf -o /dev/null conftest.ac
/bin/sh: 0: Can't open /spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/spack_path_placeholder/s
configure:3030: $? = 127
configure:3039: result: no
...
```

Looks like autoconf test line is being truncated due to padding?

Config log: [automake-config.log.txt](https://github.com/spack/spack/files/5466377/automake-config.log.txt)
Build log: [automake-build-out.txt](https://github.com/spack/spack/files/5466374/automake-build-out.txt)

@becker33 @tgamblin @scottwittenburg

**Comment by adamjstewart** [comment] 2020-10-30 16:47
Duplicate of #19580, fixed by #19582

**Comment by scottwittenburg** [comment] 2020-10-30 16:53
If this is a duplicate of #19580 (it's not clear to me that it is, but who knows), I'm still getting this error even with #19582, so that may not have resolved the issue completely.

**Comment by eugeneswalker** [comment] 2020-10-30 17:46
> ... I'm still getting this error even with #19582, so that may not have resolved the issue completely.

#19582 does not resolve this, yes.

**Comment by tgamblin** [comment] 2020-11-02 22:54
@becker33 is looking at this one.

**Closed as completed** 2020-11-13 00:08 UTC
Labels: bug, ecp, triage, e4s, sbang
