### ISSUE TITLE
Installation issue: py-h5py

### ISSUE THREAD

**Issue by codethief** [LLNL/spack#22671] opened 2021-03-31 10:29 UTC
### Steps to reproduce the issue

I'm trying to install `py-h5py@2.10.0` inside a Ubuntu 18.04 Docker container ([this one](https://hub.docker.com/r/balenalib/jetson-nano-ubuntu) to be precise) on my Jetson Nano. While 2.10.0 is not the most up-to-date version of h5py, newer versions don't work for my setup due to issues like [this one](https://github.com/tensorflow/tensorflow/issues/44467).

```console
$ cd ~
$ git clone https://github.com/spack/spack.git
$ . spack/share/spack/setup-env.sh
$ spack mirror add E4S https://cache.e4s.io
$ wget https://oaciss.uoregon.edu/e4s/e4s.pub
$ spack gpg trust e4s.pub
$ spack install -v py-h5py@2.10.0
```

Output, after hours of compiling dependencies:

```
==> Installing hdf5-1.10.7-q3i7i3hmdu4nzrezpkqjhv33vvwvjqpy
==> No binary for hdf5-1.10.7-q3i7i3hmdu4nzrezpkqjhv33vvwvjqpy found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/7a/7a1a0a54371275ce2dfc5cd093775bb025c365846512961e7e5ceaecb437ef15.tar.gz
#################################################################################################################################### 100.0%
==> Ran patch() for hdf5
==> hdf5: Executing phase: 'autoreconf'
==> hdf5: Executing phase: 'configure'
==> hdf5: Executing phase: 'build'
==> hdf5: Executing phase: 'install'
==> hdf5: Successfully installed hdf5-1.10.7-q3i7i3hmdu4nzrezpkqjhv33vvwvjqpy
  Fetch: 11.95s.  Build: 16m 20.73s.  Total: 16m 32.68s.
[+] /home/testuser/spack/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.5.0/hdf5-1.10.7-q3i7i3hmdu4nzrezpkqjhv33vvwvjqpy
==> Installing py-h5py-2.10.0-ou6evim6k7tid627q27lf3z6lxfeilsh
==> No binary for py-h5py-2.10.0-ou6evim6k7tid627q27lf3z6lxfeilsh found: installing from source
==> Warning: Suspicious requests to set or unset 'CC' found
==> Warning: 	    	env.set('CC', os.path.join(link_dir, compiler.link_paths['cc'])) at /home/testuser/spack/lib/spack/spack/build_environment.py:236
==> Warning: 	--->	env.set('HDF5_MPI', 'ON') at /home/testuser/spack/var/spack/repos/builtin/packages/py-h5py/package.py:78
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/84/84412798925dc870ffd7107f045d7659e60f5d46d1c70c700375248bf6bf512d.tar.gz
#################################################################################################################################### 100.0%
==> No patches needed for py-h5py
==> py-h5py: Executing phase: 'configure'
==> py-h5py: Executing phase: 'install'
==> Error: ProcessError: Command exited with status -4:
    '/home/testuser/spack/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.5.0/python-3.8.8-tpnwwr33yjoapraujuywrziolfckey5n/bin/python3.8' '-s' 'setup.py' '--no-user-cfg' 'install' '--prefix=/home/testuser/spack/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.5.0/py-h5py-2.10.0-ou6evim6k7tid627q27lf3z6lxfeilsh' '--single-version-externally-managed' '--root=/home/testuser/spack/opt/spack/linux-ubuntu18.04-aarch64/gcc-7.5.0/py-h5py-2.10.0-ou6evim6k7tid627q27lf3z6lxfeilsh' '--install-purelib=lib/python3.8/site-packages' '--install-platlib=lib/python3.8/site-packages' '--install-scripts=bin' '--install-data=' '--install-headers=include/python3.8'
See build log for details:
  /tmp/testuser/spack-stage/spack-stage-py-h5py-2.10.0-ou6evim6k7tid627q27lf3z6lxfeilsh/spack-build-out.txt
```

FWIW this issue look very similiar to https://github.com/h5py/h5py/issues/1837 which I encountered when trying to build h5py through pip.

### Information on your system

```console
$ spack debug report
* **Spack:** 0.16.1-1957-c3bab11ee1
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-aarch64
* **Concretizer:** original
```

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/6235748/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6235745/spack-build-env.txt)

```console
$ spack maintainers py-h5py
bryanherman
```
-> Could be https://github.com/bhermanmit but I'm not sure?

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate 

#### Epilogue

FWIW I've found [this very old issue](https://github.com/spack/spack/issues/2586) where it's being said that h5py is "so damn temperamental" when it comes to the precise dependencies and tools used to build it. At least I don't seem to be the only one struggling with h5py. :)

**Comment by adamjstewart** [comment] 2021-03-31 16:01
@bryanherman can you take a look at this?

**Comment by bryanherman** [comment] 2021-03-31 16:57
I will try and reproduce. @codethief - were there any other error messages when h5py started building extensions? I am not seeing anything in the output file, just a stoppage at build_ext.

**Comment by codethief** [comment] 2021-03-31 17:47
Thanks for responding so quickly!

@bryanherman Yeah, I was confused by that too. For some reason, the error message only showed up on the command line.

> were there any other error messages when h5py started building extensions?

Not that I know of, no.

**Comment by bryanherman** [comment] 2021-03-31 20:31
@codethief - I ran an install of py-h5py using the version and information you supplied above on an Ubuntu x86_64 system. It successfully installed. The only difference I see is that your system is a different architecture. I don't have any experience with aarch64. If I had this issue I would try to source the env file and try installing py-h5py by hand to see if there is more information.

**Comment by codethief** [comment] 2021-04-01 14:44
Yeah, I already suspected it must be architecture-related. I will follow your advice next time I'm attempting to build h5py! Unfortunately, yesterday I had to reset my Jetson Nano's SD card for $reasons, and I don't have the capacity right now to let my Nano run for another day to pull in and compile all the dependencies needed for building h5py.

For the time being, I discovered that https://github.com/tensorflow/tensorflow provides links to [archives](https://snapshots.linaro.org/ldcg/python/tensorflow/) that not only contain pre-built tensorflow wheels but also pre-built h5py wheels for aarch64. (Unfortunately, not of h5py v2.10 but, surprisingly, 3.1.0 actually seems to work fine for now, though I do need to do further testing.)

Thanks so much for your help!

**Comment by adamjstewart** [comment] 2022-01-07 21:27
Can you try #27798? We no longer run `build_ext` so hopefully the issue is no longer present.

**Comment by codethief** [comment] 2022-01-11 01:02
Hi @adamjstewart, I'm afraid I have moved on to a different project and won't have the time in the foreseeable future to give this a try. Sorry.

**Comment by adamjstewart** [comment] 2022-01-11 01:44
Thanks @codethief, in that case I'll close this issue. If anyone else runs into the same problem in the future they can open a new issue.

**Closed as completed by adamjstewart** 2022-01-11 01:44 UTC
Labels: build-error
