### ISSUE TITLE
install alsa-lib failed

### ISSUE THREAD

**Issue by sailer1205** [LLNL/spack#16794] opened 2020-05-25 03:35 UTC
Is anyone can access the ftp address below?

https://github.com/spack/spack/blob/bc145b2b3f87da8276e4c2e0665e9830de3d0322/var/spack/repos/builtin/packages/alsa-lib/package.py#L15

When I use spack to install alsa-lib, it failed, the reason is the ftp address is unavailable. Is this a bug or just for some network problems that only some area could not access the ftp?

**Comment by adamjstewart** [comment] 2020-05-26 00:22
`spack fetch alsa-lib` works fine for me, must be ftp issues. If you can find a http link you can submit a PR to switch it to that, or add multiple `urls = [...]`.

**Comment by sailer1205** [comment] 2020-05-26 01:16
@adamjstewart thanks for your reply!
The command "spack fetch alsa-lib" also works fine for me, and I  found that when I execute the command, the spack will fetch the alsa-lib archive from the url http://ftp.oregonstate.edu/.1/blfs/conglomeration/alsa-lib/alsa-lib-1.1.4.1.tar.bz2.
Shell we use the url instead?

**Comment by alalazo** [comment] 2020-05-26 07:35
I confirm that fetching `alsa-lib` seems fine. Also:
```console
$ spack fetch alsa-lib
[ ... ]
==> Fetching ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.4.1.tar.bz2
########################################################################################################################################### 100,0%
```
it uses the intended url for me.

**Comment by alalazo** [comment] 2020-05-26 07:40
@sailer1205 Closing as I was able to install and fetch without issues. Feel free to reopen if you think I missed something or you have a clear reproducer.

**Closed as completed by alalazo** 2020-05-26 07:40 UTC
Labels: unreproducible, fetching

**Comment by sailer1205** [comment] 2020-06-01 08:14
@alalazo It's the proxy problem. 
I only export the http_proxy and https_proxy environment variables, but forgot to export the ftp_proxy.
