### ISSUE TITLE
Installation issue: LAMMPS

### ISSUE THREAD

**Issue by yoonbo** [LLNL/spack#26857] opened 2021-10-20 19:09 UTC
### Steps to reproduce the issue

```
spack install lammps +cuda +kokkos +mpi cuda_arch=60 %gcc@9.4.0
```

Problem: When installing LAMMPS with CUDA and Kokkos, it does not turn on the CUDA support for Kokkos.

### Information on your system

* **Spack:** 0.16.3-4898-b2f059e
* **Python:** 3.7.4
* **Platform:** linux-centos7-haswell
* **Concretizer:** clingo

### Additional information

[spack-build-01-cmake-out.txt](https://github.com/spack/spack/files/7383665/spack-build-01-cmake-out.txt)

Attached is the cmake-out of Kokkos installed for LAMMPS. Although "+cuda" is used as the spack argument, CUDA is off for Kokkos:
```
-DKokkos_ENABLE_CUDA=OFF
```
As a result, the compiled LAMMPS cannot use Kokkos for GPUs.

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by junghans** [comment] 2021-10-21 01:50
I think the problem is that `lammps+cuda` enables the cuda support through the gpu package. To enable cuda through kokkos you might need to do something like `lammps+kokkos ^kokkos+cuda` as lammps is agnostic to the enabled kokkos backends.

**Comment by rbberger** [comment] 2023-03-15 05:37
@junghans answer is correct and explains the issue. Closing.

**Closed as completed by rbberger** 2023-03-15 05:37 UTC
Labels: build-error
