### ISSUE TITLE
luaposix fails to download

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2676] opened 2016-12-25 00:38 UTC
While installing lmod, `luaposix` fails to download.

```
curl: (22) The requested URL returned error: 404 Not Found
==> Fetching https://github.com/luaposix/luaposix/archive/33.4.0.tar.gz
==> Fetching from https://github.com/luaposix/luaposix/archive/33.4.0.tar.gz failed.
==> Error: FetchError: All fetchers failed for lua-luaposix-33.4.0-oiq5d2je66cshng6oiihy3cb3pvqausl
```

The tarball exists here:  https://github.com/luaposix/luaposix/archive/release-v33.4.0.tar.gz

and here's the relevant bit of the package.py

```
    homepage = "https://github.com/luaposix/luaposix/"
    url      = "https://github.com/luaposix/luaposix/archive/release-v33.4.0.tar.gz"

    version('33.4.0', 'b36ff049095f28752caeb0b46144516c')
```

The package itself hasn't changed.  I think I remember fetching code being reworked recently.  Does this ring any bells?

g.

**Comment by adamjstewart** [comment] 2016-12-25 01:07
@tgamblin

**Comment by adamjstewart** [comment] 2016-12-25 04:52
Duplicate of #2660.

**Closed by adamjstewart** 2016-12-25 04:52 UTC
Labels: bug
