### ISSUE TITLE
hip package fails due to system-installed rocm files

### ISSUE THREAD

**Issue by G-Ragghianti** [LLNL/spack#31065] opened 2022-06-09 00:36 UTC
### Steps to reproduce the issue

This propblem occurs because the hip package in spack tries to access system-installed rocm files during the cmake.  This causes cmake errors.  The Dockerfile will show that hip installs correctly when the rocm rpms are not installed but fails once rocm is installed on the system.  The (slightly ironic) result is that the hip spack package is unable to be built when rocm is also installed on the system under /opt/rocm/. 

Dockerfile:

```
FROM rockylinux 

RUN dnf clean all
RUN dnf -y update
RUN dnf -y groupinstall development
RUN dnf -y groupinstall --allowerasing "Minimal Install"
RUN dnf -y install gcc-gfortran python3 
RUN alternatives --set python /usr/bin/python3

RUN git clone https://github.com/spack/spack /opt/spack
RUN source /opt/spack/share/spack/setup-env.sh \
    && spack install --fail-fast hip ^mesa~llvm

RUN dnf -y install epel-release
RUN dnf -y --enablerepo=powertools install perl-File-BaseDir perl-URI-Encode
COPY extra.repo /etc/yum.repos.d/
RUN dnf -y --disablerepo=epel install rocm-hip-sdk rocprim rocm-ml-sdk rocm-openmp-sdk rocm-opencl-sdk rocm-developer-tools

RUN source /opt/spack/share/spack/setup-env.sh \
    && spack uninstall -y hip \
    && spack install --fail-fast hip ^mesa~llvm
```

Here is "extra.repo":

```
[amdgpu]
name=amdgpu
baseurl=https://repo.radeon.com/amdgpu/latest/rhel/8.5/main/x86_64
enabled=1
gpgcheck=0

[rocm]
name=rocm
baseurl=http://repo.radeon.com/rocm/yum/5.1.3/main
enabled=1
gpgcheck=0
```

### Error message

<details><summary>Error message</summary><pre>
3 errors found in build log:
     62      File "/opt/rocm/bin/rocm_agent_enumerator", line 241, in main
     63        target_list = readFromKFD()
     64      File "/opt/rocm/bin/rocm_agent_enumerator", line 200, in readFromK
           FD
     65        line = f.readline()
     66    PermissionError: [Errno 1] Operation not permitted
     67    -- ROCm Agent Enumurator Result: 1
  >> 68    CMake Error at /tmp/root/spack-stage/spack-stage-hip-5.1.3-bfajl27fz
           hqbtomxo5mglyeletz77cj6/spack-src/tests/hit/HIT.cmake:50 (string):
     69      string sub-command REPLACE requires at least four arguments.
     70    Call Stack (most recent call first):
     71      CMakeLists.txt:446 (include)
     72    
     73    
  >> 74    CMake Error at /tmp/root/spack-stage/spack-stage-hip-5.1.3-bfajl27fz
           hqbtomxo5mglyeletz77cj6/spack-src/tests/hit/HIT.cmake:51 (string):
     75      string sub-command LENGTH requires two arguments.
     76    Call Stack (most recent call first):
     77      CMakeLists.txt:446 (include)
     78    
     79    
  >> 80    CMake Error at /tmp/root/spack-stage/spack-stage-hip-5.1.3-bfajl27fz
           hqbtomxo5mglyeletz77cj6/spack-src/tests/hit/HIT.cmake:54 (if):
     81      if given arguments:
     82    
     83        "GREATER_EQUAL" "1"
     84    
     85      Unknown arguments specified
     86    Call Stack (most recent call first):

See build log for details:
  /tmp/root/spack-stage/spack-stage-hip-5.1.3-bfajl27fzhqbtomxo5mglyeletz77cj6/spack-build-out.txt

</pre></details>

### Information on your system

* **Spack:** 0.19.0.dev0 (3fdb3f832af56a4afc38da1691fff3ca6596bf20)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-zen3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by renjithravindrankannath** [comment] 2022-06-13 16:23
Hi @G-Ragghianti ,
I am able to build hip with the steps you have provided above on the environment with 8 gpu.
I am getting below result when I checked the gpu architecture upon running the rocm_agent_enumerator script/
```
[root@ixt-rack-104 spack-src]# python /opt/rocm/bin/rocm_agent_enumerator
gfx000
gfx906
gfx906
gfx906
gfx906
gfx906
gfx906
gfx906
gfx906
```
Could you please let us know what is the target gpu architecture of the your environment ?

**Comment by G-Ragghianti** [comment] 2022-06-13 16:27
```
 $ python /opt/rocm/bin/rocm_agent_enumerator
gfx000
gfx906
gfx906
gfx906
gfx906
```
Should the build process depend on what hardware is installed?

**Comment by renjithravindrankannath** [comment] 2022-06-13 19:40
rocm_agent_enumerator is executed to check the GPU architecture as part of test.
This test depends the availability of GPU.

**Comment by G-Ragghianti** [comment] 2022-06-14 13:30
- It seems like a "test" should only be executed when "spack install --test" is executed
- The test is trying to run a command under /opt/rocm directory which presumably should not be assumed to exist since when are doing the install.
- The spack install shouldn't depend on something that is outside of the spack install (by default)
- In all the cases that I've tested this on, the execution of rocm_agent_enumerator actually causes a cmake failure (and syntax error) only when /opt/rocm/* exists and the hardware is present.  This seems to be the opposite of what you want.
- We shouldn't require the hardware to be present on the compiling node

**Comment by G-Ragghianti** [comment] 2022-06-14 20:32
I've discovered that the problem causing rocm_agent_enumerator to fail is that it is trying to run "lsmod" but it is not in the $PATH.  This causes the enumerator to return only the CPU (in the case of AMD CPU), and then cmake has further problems due to this.

**Comment by luszczek** [comment] 2022-06-15 15:07
It would be useful to add `depends_on()` for this but I don't see a way of doing this even for other packages that deal with kernel interaction like `xpmem`.

**Comment by renjithravindrankannath** [comment] 2022-06-16 19:39
Hi @G-Ragghianti, Is the $PATH missing /usr/sbin/ or lsmod not present in the path?
With the rockylinux/rockylinux docker I could see lsmod is available under the path /usr/sbin/.
```
[root@ixt-rack-104 spack-src]# whereis  lsmod
lsmod: /usr/sbin/lsmod /usr/share/man/man8/lsmod.8.gz
```
And the path /usr/sbin/ was also in the $PATH.
```
[root@ixt-rack-104 spack-src]# echo $PATH
/opt/spack/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
This is in the below version of "Rocky Linux
```
[root@ixt-rack-104 spack-src]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
[root@ixt-rack-104 spack-src]#
```
Let us know if the issue is observed after adding the path to $PATH or by installing lsmod.

**Comment by renjithravindrankannath** [comment] 2022-07-26 16:30
Hi @G-Ragghianti ,
The issue wasn't reproduced on similar environment since lsmod was available in the same docker.
As you have already discovered the problem causing rocm_agent_enumerator to fail and found a solution 
please let us know if we can close this ticket.

**Comment by G-Ragghianti** [comment] 2022-08-01 12:14
Yes that does fix the problem, but the other reason that this is filed as an issue is that the install is dependent on something like rocm_agent_enumerator already being installed on the system.  Is there not a clear chicken-and-egg situation here?

**Closed as completed** 2022-08-15 20:51 UTC
Labels: build-error, ROCm/hip
