### ISSUE TITLE
Split spack and the default package collection into separate git repositories

### ISSUE THREAD

**Issue by ian-bertolacci** [LLNL/spack#17062] opened 2020-06-11 20:29 UTC
Spack, the package manager, and the collection of spack modules, which are managed using spack, should be developed in separate git repositories.

This repository is trying to version control 3 different processes:
1. The development of a sophisticated package manager
2. The curation of a default package collection
3. The maintenance of individual packages in the default collection

While these processes are intertwined in certain aspects, they have distinct development and release cycles.
The spack package manager has its development and release cycle, and the software inside a package its own individual development release cycle.
Having all of these processes in one version control system tangles these cycles together in a user-unfriendly way.

For example:
Yesterday, I wanted to install hpctoolkit.
I'm new to spack, so I download the latest release of spack (v.0.14.2 at the time), and went on installing hpctoolkit, only to run into this issue with intel-tbb not having the correct sha.
This issue is described in #16825 and resolved in 16f104aafe2bb780f2d03c04aae0ccff333aa821, but that commit isn't part of the v0.14.2 release.

Now what?

Do I just clone the head of the develop branch? (But what if spack is broken at develop->HEAD?)
Do I keep v0.14.2 and cherry-pick the fixing commit? (But what if that commit depends on other commits?)

Because the development of spack, the curated default package collection, and the maintenance of the package itself are all tied together in git, we've exchanged a package manager problem for a version control problem (a potentially tricky one as well).

This could be avoided (and probably eliminated) if the development of spack and the curation of the default package collection (and possibly the maintenance of each package) were each separate git repositories.

Now, when a user download the latest release version of spack, it would first clone the latest release version of the default package collection repository, which could be much newer than the software.
Because the two are separate, an update to, or addition of, a package do not require getting the latest commit of the spack software repository, eliminating any concerns I might have as a user regarding the safety and stability of the package management software
This could also make adoption on managed systems much more viable, as users no longer have to bug system admins to update spack (to a potentially unsafe version) in order to get the most recent package definitions.

For my example, this would never have been an issue, because there's no longer a way for a package definition to be "behind".
When spack checks for the package repo for package definitions, it would always have the most recent, most correct version of a package definition, without ever having to update or upgrade the actual spack software.

Additionally, from an organizational perspective, it seems like separated repositories would be better for you as project developers:

1. Issues and pull requests for packages and the software would be in totally separate locations, resulting in less "clutter" and more accurate search results (such as when looking for a previous solution to an issue or making sure I am not submitting a duplicate issue).
2. Maintainers of either repo only have to ensure that their stuff is in good state (except maybe when  spack has API breaking changes). 
3. Faster release cycles for both repositories, as a broken package would not impede the release of a new, stable version of spack, and vice-versa.

It *seems* like there is already a lot of infrastructure in place to enable this.
I can already [create and maintain my own personal local repositories](https://spack.readthedocs.io/en/latest/repositories.html), why not extend that to allow urls (specifically git-urls), and have the url to the separate default package collection repository be an entry in the default repos.yaml file?

Thoughts?

**Comment by mwkrentel** [comment] 2020-06-11 21:40
Separate from whether this is a good or bad idea, let me point out
that it would NOT solve the intel-tbb problem that you reported above.

Intel moved their repository in a way that both the URLs and the
sha256 sums changed.  So, even if you took a snapshot of spack that
used to work, it would no longer work after Intel's change because the
change was outside the spack repo.  No amount of splitting repos would
fix that.  (Take it up with Intel.)

The only way to fix that would be to make a giant repo with a copy of
every tar file, repo and patch that spack uses across every package.

The solution in this case is to update to a later version of spack
develop after it was fixed.

And it's not just Intel.  The libelf site went away and the latest
version was picked up on fossies.  Bzip2 resumed development and so
fossies dropped their copy, etc, etc.  So, unless you want to make a
snapshot of the entire internet ....

**Comment by ian-bertolacci** [comment] 2020-06-11 22:17
> it would NOT solve the intel-tbb problem

I know that it would not have solved the underlying problem with the checksums, but it would have prevented the issue I had, which was that the package definition was updated and corrected, but using that package definition required updating the entire spack repository, and the spack software itself.

And I think that what you've said is a good demonstration of why these should be separate repositories.
The maintenance of a package definition is its own separate software development process from the development and maintenance of the software that manages installations of those packages.

As software (and the way that software is 'presented', I gess, to the world) changes, so must the package definitions.
But that has no (or at most very occasional) impact on the development of the package manager.
The maintenance of a package definition is *more* tied to the maintenance of the software that package installs, than it is to the package management software.

Similarly, the package manager has no impact on the software, and hopefully no or only occasional impact on the package definitions.

The package definition and the package manager are weakly interacting, but by putting them into the same git repository we've strongly tied them together in version control history, which causes the problem I was describing.

**Comment by alalazo** [comment] 2020-06-12 08:55
Duplicate of #1773

**Comment by ian-bertolacci** [comment] 2020-06-12 15:15
Thanks, I'll move this over there.

**Comment by adamjstewart** [comment] 2021-01-10 23:05
Closing as a duplicate of #1773

**Closed as completed by adamjstewart** 2021-01-10 23:05 UTC
Labels: duplicate, feature, repos, git
