### ISSUE TITLE
Concretization Preferences for compilers do not work

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#1842] opened 2016-09-23 17:26 UTC
```
packages:
  all:
    compiler: [clang, gcc]
    providers:
      mpi: [openmpi]
      blas: [openblas]
      lapack: [openblas]
  libtool:
    compiler: [clang]
  python:
    compiler: [clang]
```
`libtool`/`python` are not used with `clang`:
```
$ spack spec petsc%gcc
Input spec
------------------------------
  petsc%gcc

Normalized
------------------------------
  petsc%gcc
      ^blas
      ^lapack
      ^python@2.6:2.7
          ^bzip2
          ^ncurses
          ^openssl
              ^zlib
          ^readline
          ^sqlite

Concretized
------------------------------
  petsc@3.7.2%gcc@6.2.0+boost~complex~debug+double+hdf5+hypre+metis+mpi+mumps+shared+superlu-dist arch=darwin-sierra-x86_64
      ^boost@1.61.0%gcc@6.2.0+atomic+chrono+date_time~debug+filesystem~graph~icu_support+iostreams+locale+log+math~mpi+multithreaded+program_options~python+random+regex+serialization+shared+signals+singlethreaded+system+test+thread+timer+wave arch=darwin-sierra-x86_64
          ^bzip2@1.0.6%gcc@6.2.0 arch=darwin-sierra-x86_64
          ^zlib@1.2.8%gcc@6.2.0 arch=darwin-sierra-x86_64
      ^hdf5@1.10.0-patch1%gcc@6.2.0+cxx~debug+fortran+mpi+shared~szip~threadsafe arch=darwin-sierra-x86_64
          ^openmpi@2.0.1%gcc@6.2.0~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=darwin-sierra-x86_64
              ^hwloc@1.11.4%gcc@6.2.0 arch=darwin-sierra-x86_64
                  ^libpciaccess@0.13.4%gcc@6.2.0 arch=darwin-sierra-x86_64
                      ^libtool@2.4.6%gcc@6.2.0 arch=darwin-sierra-x86_64
                          ^m4@1.4.17%gcc@6.2.0+sigsegv arch=darwin-sierra-x86_64
                              ^libsigsegv@2.10%gcc@6.2.0 arch=darwin-sierra-x86_64
      ^hypre@2.10.1%gcc@6.2.0~internal-superlu~shared arch=darwin-sierra-x86_64
          ^openblas@0.2.19%gcc@6.2.0+fpic~openmp+shared arch=darwin-sierra-x86_64
      ^metis@5.1.0%gcc@6.2.0~debug~gdb~idx64~real64+shared arch=darwin-sierra-x86_64
          ^cmake@3.6.1%gcc@6.2.0~doc+ncurses+openssl~ownlibs~qt arch=darwin-sierra-x86_64
              ^curl@7.50.3%gcc@6.2.0 arch=darwin-sierra-x86_64
                  ^openssl@1.0.2i%gcc@6.2.0 arch=darwin-sierra-x86_64
              ^expat@2.2.0%gcc@6.2.0 arch=darwin-sierra-x86_64
              ^libarchive@3.2.1%gcc@6.2.0 arch=darwin-sierra-x86_64
                  ^libxml2@2.9.4%gcc@6.2.0~python arch=darwin-sierra-x86_64
                      ^xz@5.2.2%gcc@6.2.0 arch=darwin-sierra-x86_64
                  ^lz4@131%gcc@6.2.0 arch=darwin-sierra-x86_64
                  ^lzma@4.32.7%gcc@6.2.0 arch=darwin-sierra-x86_64
                  ^lzo@2.09%gcc@6.2.0 arch=darwin-sierra-x86_64
                  ^nettle@3.2%gcc@6.2.0 arch=darwin-sierra-x86_64
                      ^gmp@6.1.1%gcc@6.2.0 arch=darwin-sierra-x86_64
              ^ncurses@6.0%gcc@6.2.0 arch=darwin-sierra-x86_64
      ^mumps@5.0.1%gcc@6.2.0+complex+double+float~idx64~metis+mpi~parmetis~ptscotch~scotch+shared arch=darwin-sierra-x86_64
          ^netlib-scalapack@2.0.2%gcc@6.2.0~fpic+shared arch=darwin-sierra-x86_64
      ^parmetis@4.0.3%gcc@6.2.0~debug~gdb+shared arch=darwin-sierra-x86_64
      ^python@2.7.12%gcc@6.2.0~tk~ucs4 arch=darwin-sierra-x86_64
          ^readline@6.3%gcc@6.2.0 arch=darwin-sierra-x86_64
          ^sqlite@3.8.5%gcc@6.2.0 arch=darwin-sierra-x86_64
      ^superlu-dist@5.0.0%gcc@6.2.0 arch=darwin-sierra-x86_64
```

**Comment by adamjstewart** [comment] 2016-09-23 17:39
Duplicate of #1371.

**Closed** 2016-09-23 17:40 UTC
Labels: bug, concretization, duplicate
