### ISSUE TITLE
spack env loads -r fails

### ISSUE THREAD

**Issue by skwde** [LLNL/spack#40210] opened 2023-09-26 12:41 UTC
### Steps to reproduce

I have an additional compiler installed via spack, I added this compiler to `compilers.yaml`

```sh
spack install gcc@13.1.0
spack load gcc@13.1.0
spack compiler find
```

I used this compiler to install an environment.

I tried both, a unmanaged environment

```sh
spack env create -d ~/test-envs/base
```

and then a managed environemnt

```sh
spack env create base
spacktivate -p base
spack config edit
```

In both I ensuree that the `spack.yaml` looks like

```yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs:
    - tmux
  view: true
  concretizer:
    unify: true
  packages:
    all:
      compiler:
        - gcc@13.1.0
      target:
        - x86_64_v3
```

After the install

```sh
spack install
```

when I then try to create the source script via

```sh
spack env loads -r
```

### Error message

```sh
$ spack --debug --stacktrace env loads -r
==> Error: The module for package tmux@3.3a/dj5uwwz should be at ~/opt/spack/share/spack/modules/linux-rocky9-x86_64_v3/tmux-3.3a-gcc-13.1.0-dj5uwwz, but it does not exist
```

### Information on your system

```sh
$ spack debug report
* **Spack:** 0.20.1 (e8658d6493887ef702dd38f0e9ee5870a1651c1e)
* **Python:** 3.9.16
* **Platform:** linux-rocky9-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by becker33** [comment] 2023-09-26 17:15
Is module generation enabled in your configuration? Try `spack config blame modules | grep -C3 enable`

**Comment by mwkrentel** [comment] 2023-09-26 18:16
Duplicate of #39682.
And yes, the real problem is that spack failed to create the modules
for non-root targets during `spack install`.

**Comment by skwde** [comment] 2023-09-27 05:38
@becker33, no, but to my understanding (<https://spack.readthedocs.io/en/latest/environments.html#loading>)

```sh
$ spack config blame modules | grep -C3 enable
~/opt/spack/etc/spack/defaults/modules.yaml:40      roots:
~/opt/spack/etc/spack/defaults/modules.yaml:41        tcl: $spack/share/spack/modules
~/opt/spack/etc/spack/defaults/modules.yaml:42        lmod: $spack/share/spack/lmod
~/opt/spack/etc/spack/defaults/modules.yaml:44      enable: []
~/opt/spack/etc/spack/defaults/modules.yaml:46      tcl:
~/opt/spack/etc/spack/defaults/modules.yaml:47        all:
~/opt/spack/etc/spack/defaults/modules.yaml:48          autoload: direct
```

this is also not required.

@mwkrentel thanks for pointing out the underlying issue. I guess we have to wait until the issue you mentioned is fixed.

**Comment by alalazo** [comment] 2023-10-12 16:40
Duplicate of #39682

**Comment by alalazo** [comment] 2023-10-12 16:41
Let's follow with the discussion in the other issue

**Closed as not planned** 2023-10-12 16:41 UTC
Labels: bug, triage
