### ISSUE TITLE
Installation issue: cp2k

### ISSUE THREAD

**Issue by yizeyi18** [LLNL/spack#40372] opened 2023-10-07 07:15 UTC
### Steps to reproduce the issue

```console
$ spack spec -l cp2k%gcc@13 +cosma+elpa+libint+libvori+libxc+pexsi+plumed+pytorch+quip+sirius+spglib+spla
Input spec
--------------------------------
 -   cp2k%gcc@13+cosma+elpa+libint+libvori+libxc+pexsi+plumed+pytorch+quip+sirius+spglib+spla

Concretized
--------------------------------
 -   bq4ygqp  cp2k@2023.2%gcc@13.1.0+cosma~cuda+elpa~enable_regtests+libint+libvori+libxc+mpi+openmp+pexsi+plumed+pytorch+quip~rocm+sirius+spglib+spla build_system=makefile lmax=5 smm=libxsmm arch=linux-ubuntu22.04-zen3
[+]  r7ou34d      ^cosma@2.6.6%gcc@13.1.0~apps~cuda~gpu_direct~ipo~profiling~rocm+scalapack~shared~tests build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-zen3
[e]  ifuqqrl          ^cmake@3.25.0%gcc@13.1.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-ubuntu22.04-zen3
[+]  y6flkrf          ^costa@2.2.2%gcc@13.1.0~apps~benchmarks~ipo~profiling+scalapack+shared~tests build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-zen3
[e]  4k6ngp6          ^gmake@4.3%gcc@13.1.0~guile build_system=autotools patches=599f134 arch=linux-ubuntu22.04-zen3
[+]  vhmgoza      ^elpa@2023.05.001%gcc@13.1.0~cuda+mpi+openmp~rocm build_system=autotools arch=linux-ubuntu22.04-zen3
[e]  zcn2q6s          ^libtool@2.4.6%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  6fs2j2y      ^fftw@3.3.10%gcc@13.1.0+mpi+openmp~pfft_patches build_system=autotools precision=double,float arch=linux-ubuntu22.04-zen3
[+]  y7rf2ca      ^libint@2.6.0%gcc@13.1.0~debug~fma+fortran build_system=autotools tune=cp2k-lmax-5 arch=linux-ubuntu22.04-zen3
[e]  bkou5hf          ^autoconf@2.71%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-zen3
[e]  szmalgl          ^automake@1.16.5%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  d5ul7yb          ^boost@1.82.0%gcc@13.1.0+atomic+chrono~clanglibcpp~container~context~contract~coroutine+date_time~debug+exception~fiber+filesystem+graph~graph_parallel~icu+iostreams~json+locale+log+math~mpi+multithreaded~nowide~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded~stacktrace+system~taggedlayout+test+thread+timer~type_erasure~versionedlayout+wave build_system=generic cxxstd=98 patches=a440f96,a7c807f visibility=hidden arch=linux-ubuntu22.04-zen3
[+]  y3b4mi5              ^zstd@1.5.5%gcc@13.1.0~programs build_system=makefile libs=shared,static arch=linux-ubuntu22.04-zen3
[+]  5jcadif          ^gmp@6.2.1%gcc@13.1.0+cxx build_system=autotools libs=shared,static patches=69ad2e2 arch=linux-ubuntu22.04-zen3
[+]  j7shlyf      ^libvori@220621%gcc@13.1.0~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-zen3
[+]  h3qnenu      ^libxc@6.2.2%gcc@13.1.0~cuda~kxc~lxc+shared build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  h75nxlh          ^perl@5.38.0%gcc@13.1.0+cpanm+opcode+open+shared+threads build_system=generic arch=linux-ubuntu22.04-zen3
[+]  3ejv4em              ^berkeley-db@18.1.40%gcc@13.1.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu22.04-zen3
[+]  v644nkh      ^libxsmm@1.17%gcc@13.1.0~debug~generator~header-only~large_jit_buffer~shared blas=default build_system=makefile arch=linux-ubuntu22.04-zen3
[e]  lagk3al          ^binutils@2.38%gcc@13.1.0+gas~gold~headers~interwork+ld~libiberty~lto~nls~pgo+plugins build_system=autotools compress_debug_sections=zlib libs=shared,static arch=linux-ubuntu22.04-zen3
[+]  k6lq5bq      ^netlib-scalapack@2.2.0%gcc@13.1.0~ipo~pic+shared build_system=cmake build_type=Release generator=make patches=072b006,1c9ce5f,244a9aa arch=linux-ubuntu22.04-zen3
[+]  2fnivlg      ^openblas@0.3.23%gcc@13.1.0~bignuma~consistent_fpcsr+fortran~ilp64+locking+pic+shared build_system=makefile symbol_suffix=none threads=openmp arch=linux-ubuntu22.04-zen3
[+]  wtajzbi      ^openmpi@4.1.5%gcc@13.1.0~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~internal-pmix~java~legacylaunchers~lustre~memchecker~openshmem~orterunprefix+romio+rsh~singularity+static+vt+wrapper-rpath build_system=autotools fabrics=none schedulers=none arch=linux-ubuntu22.04-zen3
[+]  mboh5p4          ^hwloc@2.9.1%gcc@13.1.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-ubuntu22.04-zen3
[+]  aovdawc              ^libpciaccess@0.17%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  zr7dxcj                  ^util-macros@1.19.3%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  x62zjud              ^libxml2@2.10.3%gcc@13.1.0~python build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  mkfs2bw          ^numactl@2.0.14%gcc@13.1.0 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-ubuntu22.04-zen3
[e]  qh7pxzx          ^openssh@8.9p1%gcc@13.1.0+gssapi build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  hxphdi7          ^pmix@4.2.4%gcc@13.1.0~docs+pmi_backwards_compatibility~python~restful build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  gpazfhh              ^libevent@2.1.12%gcc@13.1.0+openssl build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  vtmsxkg          ^zlib@1.2.13%gcc@13.1.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu22.04-zen3
[+]  kzxshhu      ^pexsi@2.0.0%gcc@13.1.0+fortran~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-zen3
[+]  45dxacb          ^parmetis@4.0.3%gcc@13.1.0~gdb~int64~ipo+shared build_system=cmake build_type=Release generator=make patches=4f89253,50ed208,704b84f arch=linux-ubuntu22.04-zen3
[+]  hpo75x2              ^metis@5.1.0%gcc@13.1.0~gdb~int64~ipo~real64+shared build_system=cmake build_type=Release generator=make patches=4991da9,93a7903,b1225da arch=linux-ubuntu22.04-zen3
[+]  oy3nnas          ^superlu-dist@7.2.0%gcc@13.1.0~cuda~int64~ipo~openmp~rocm+shared build_system=cmake build_type=Release generator=make patches=8da9e21 arch=linux-ubuntu22.04-zen3
[e]  hycwzo3      ^pkg-config@0.29.2%gcc@13.1.0+internal_glib build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  4q7jayw      ^plumed@2.8.2%gcc@13.1.0+gsl+mpi+shared arrayfire=none build_system=autotools optional_modules=all arch=linux-ubuntu22.04-zen3
[+]  264gmqi          ^gsl@2.7.1%gcc@13.1.0~external-cblas build_system=autotools arch=linux-ubuntu22.04-zen3
[e]  oeiup45          ^m4@1.4.18%gcc@13.1.0+sigsegv build_system=autotools patches=3877ab5,fc9b616 arch=linux-ubuntu22.04-zen3
[+]  uw4ishb          ^py-cython@3.0.0%gcc@13.1.0 build_system=python_pip arch=linux-ubuntu22.04-zen3
[+]  w27oud2      ^py-fypp@3.1%gcc@13.1.0 build_system=python_pip arch=linux-ubuntu22.04-zen3
[+]  emcr2jn          ^py-pip@23.1.2%gcc@13.1.0 build_system=generic arch=linux-ubuntu22.04-zen3
[+]  qqubkhn          ^py-setuptools@68.0.0%gcc@13.1.0 build_system=generic arch=linux-ubuntu22.04-zen3
[+]  ylqhqpw          ^py-wheel@0.37.1%gcc@13.1.0 build_system=generic arch=linux-ubuntu22.04-zen3
[+]  dz6f2fu      ^python@3.10.12%gcc@13.1.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=linux-ubuntu22.04-zen3
[+]  exxvkna          ^bzip2@1.0.8%gcc@13.1.0~debug~pic+shared build_system=generic arch=linux-ubuntu22.04-zen3
[e]  qoy5u3i              ^diffutils@3.8%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  mjzoqpk          ^expat@2.5.0%gcc@13.1.0+libbsd build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  5cus6qo              ^libbsd@0.11.7%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  6fz5v2f                  ^libmd@1.0.4%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  gzn6aai          ^gdbm@1.23%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  yxbg4m4          ^gettext@0.21.1%gcc@13.1.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  ked53pc              ^libiconv@1.17%gcc@13.1.0 build_system=autotools libs=shared,static arch=linux-ubuntu22.04-zen3
[e]  ipon2cg              ^tar@1.34%gcc@13.1.0 build_system=autotools zip=pigz arch=linux-ubuntu22.04-zen3
[+]  xfezfpt          ^libffi@3.4.4%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  ns5xr76          ^libxcrypt@4.4.35%gcc@13.1.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-ubuntu22.04-zen3
[+]  es2yxb4          ^ncurses@6.4%gcc@13.1.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  hc7n5fo          ^openssl@3.1.1%gcc@13.1.0~docs~shared build_system=generic certs=mozilla arch=linux-ubuntu22.04-zen3
[+]  62d6bky              ^ca-certificates-mozilla@2023-05-30%gcc@13.1.0 build_system=generic arch=linux-ubuntu22.04-zen3
[+]  7lgwtuy          ^readline@8.2%gcc@13.1.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu22.04-zen3
[+]  5gtzh6f          ^sqlite@3.42.0%gcc@13.1.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  rfhgv3u          ^util-linux-uuid@2.38.1%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-zen3
[+]  snzvo3y          ^xz@5.4.1%gcc@13.1.0~pic build_system=autotools libs=shared,static arch=linux-ubuntu22.04-zen3
[+]  q2sf7wi      ^sirius@7.4.3%gcc@13.1.0+apps~boost_filesystem~cuda~elpa+fortran~ipo~magma+memory_pool~nlcglib+openmp+profiler~python~rocm~scalapack+shared~single_precision~tests~vdwxc~wannier90 build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-zen3
[+]  azpqadz          ^hdf5@1.14.1-2%gcc@13.1.0~cxx~fortran+hl~ipo~java~map+mpi+shared~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-zen3
[+]  4usxxvr          ^spfft@1.0.6%gcc@13.1.0~cuda~fortran~gpu_direct~ipo+mpi+openmp~rocm~single_precision~static build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-zen3
[+]  wq7xyms          ^spla@1.5.5%gcc@13.1.0~cuda~fortran~ipo+openmp~rocm~static build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-zen3
[+]  4dpcw2t      ^spglib@2.0.2%gcc@13.1.0~ipo+openmp build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-zen3

```

### Error message

<details><summary>Error message</summary>
<pre>
==> Error: ProcessError: Command exited with status 2:
    'make' '-j12' 'ARCH=linux-ubuntu22.04-zen3-gcc' 'VERSION=psmp'

5 errors found in build log:
     407    /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-13.1.0/openmpi-4.1.5-wtajzbikckprkfytzm7eakiebknu6bkf/bin/mpicc -c -O2 -funroll-loops -ftree-vectorize -std=c99 -fopenmp -D__FFTW3 -I/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-13.1.0/fftw-3.3.10-6fs2j2y2ttnhd3p6yqzeyhsq3krbx75r/include -D__PLUMED2 -D__parallel -D__SCALAPACK -D__LIBINT -D__LIBXC -D__LIBPEXSI -D__ELPA=202305 -D__SIRIUS -D__LIBXSMM -D__LIBVORI -D__SPGLIB /tmp/yizeyi18/spack-stage/spack-stage-cp2k-2023.2-wnqmaktkmad2cy2fufrnio4lzq2qmtfa/spack-src/src/grid/ref/grid_ref_task_list.c
     408    /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-13.1.0/openmpi-4.1.5-wtajzbikckprkfytzm7eakiebknu6bkf/bin/mpicc -c -O2 -funroll-loops -ftree-vectorize -std=c99 -fopenmp -D__FFTW3 -I/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-13.1.0/fftw-3.3.10-6fs2j2y2ttnhd3p6yqzeyhsq3krbx75r/include -D__PLUMED2 -D__parallel -D__SCALAPACK -D__LIBINT -D__LIBXC -D__LIBPEXSI -D__ELPA=202305 -D__SIRIUS -D__LIBXSMM -D__LIBVORI -D__SPGLIB /tmp/yizeyi18/spack-stage/spack-stage-cp2k-2023.2-wnqmaktkmad2cy2fufrnio4lzq2qmtfa/spack-src/src/grid/ref/grid_ref_collocate.c
     409    /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-13.1.0/openmpi-4.1.5-wtajzbikckprkfytzm7eakiebknu6bkf/bin/mpicc -c -O2 -funroll-loops -ftree-vectorize -std=c99 -fopenmp -D__FFTW3 -I/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-13.1.0/fftw-3.3.10-6fs2j2y2ttnhd3p6yqzeyhsq3krbx75r/include -D__PLUMED2 -D__parallel -D__SCALAPACK -D__LIBINT -D__LIBXC -D__LIBPEXSI -D__ELPA=202305 -D__SIRIUS -D__LIBXSMM -D__LIBVORI -D__SPGLIB /tmp/yizeyi18/spack-stage/spack-stage-cp2k-2023.2-wnqmaktkmad2cy2fufrnio4lzq2qmtfa/spack-src/src/grid/common/grid_basis_set.c
     410    /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-13.1.0/openmpi-4.1.5-wtajzbikckprkfytzm7eakiebknu6bkf/bin/mpicc -c -O2 -funroll-loops -ftree-vectorize -std=c99 -fopenmp -D__FFTW3 -I/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-13.1.0/fftw-3.3.10-6fs2j2y2ttnhd3p6yqzeyhsq3krbx75r/include -D__PLUMED2 -D__parallel -D__SCALAPACK -D__LIBINT -D__LIBXC -D__LIBPEXSI -D__ELPA=202305 -D__SIRIUS -D__LIBXSMM -D__LIBVORI -D__SPGLIB /tmp/yizeyi18/spack-stage/spack-stage-cp2k-2023.2-wnqmaktkmad2cy2fufrnio4lzq2qmtfa/spack-src/src/grid/common/grid_sphere_cache.c
     411    /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-13.1.0/openmpi-4.1.5-wtajzbikckprkfytzm7eakiebknu6bkf/bin/mpicc -c -O2 -funroll-loops -ftree-vectorize -std=c99 -fopenmp -D__FFTW3 -I/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-13.1.0/fftw-3.3.10-6fs2j2y2ttnhd3p6yqzeyhsq3krbx75r/include -D__PLUMED2 -D__parallel -D__SCALAPACK -D__LIBINT -D__LIBXC -D__LIBPEXSI -D__ELPA=202305 -D__SIRIUS -D__LIBXSMM -D__LIBVORI -D__SPGLIB /tmp/yizeyi18/spack-stage/spack-stage-cp2k-2023.2-wnqmaktkmad2cy2fufrnio4lzq2qmtfa/spack-src/src/grid/common/grid_library.c
     412    /tmp/yizeyi18/spack-stage/spack-stage-cp2k-2023.2-wnqmaktkmad2cy2fufrnio4lzq2qmtfa/spack-src/src/grid/cpu/grid_cpu_collocate.c: In function 'write_task_file':
  >> 413    /tmp/yizeyi18/spack-stage/spack-stage-cp2k-2023.2-wnqmaktkmad2cy2fufrnio4lzq2qmtfa/spack-src/src/grid/cpu/grid_cpu_collocate.c:47:17: error: 'DBL_DECIMAL_DIG' undeclared (first use in this functio
            n); did you mean 'DECIMAL_DIG'?
     414       47 |   const int D = DBL_DECIMAL_DIG;
     415            |                 ^~~~~~~~~~~~~~~
     416            |                 DECIMAL_DIG
     417    /tmp/yizeyi18/spack-stage/spack-stage-cp2k-2023.2-wnqmaktkmad2cy2fufrnio4lzq2qmtfa/spack-src/src/grid/cpu/grid_cpu_collocate.c:47:17: note: each undeclared identifier is reported only once for eac
            h function it appears in
  >> 418    make[3]: *** [/tmp/yizeyi18/spack-stage/spack-stage-cp2k-2023.2-wnqmaktkmad2cy2fufrnio4lzq2qmtfa/spack-src/Makefile:518: grid_cpu_collocate.o] Error 1
     419    make[3]: *** Waiting for unfinished jobs....
  >> 420    make[2]: *** [/tmp/yizeyi18/spack-stage/spack-stage-cp2k-2023.2-wnqmaktkmad2cy2fufrnio4lzq2qmtfa/spack-src/Makefile:146: all] Error 2
  >> 421    make[1]: *** [/tmp/yizeyi18/spack-stage/spack-stage-cp2k-2023.2-wnqmaktkmad2cy2fufrnio4lzq2qmtfa/spack-src/Makefile:128: psmp] Error 2
  >> 422    make: *** [Makefile:123: all] Error 2
</pre></details>

### Information on your system

* **Spack:** 0.21.0.dev0 (6c1868f8ae48e9547cfc66cd902ee7bd32f29148)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-zen3
* **Concretizer:** clingo

### Additional information

@dev-zero @mtaillefumier
The problem seems caused by the "-std=c99" keyword or the line "cflags.append(self.compiler.c99_flag)" in packages.py, which lead to a float.h without DBL_DECIMAL_DIG through some mechanism I don't know.

After commenting the line in packages.py, the keyword disappears and it passes compiling.

The attaching spack-build-out.txt and spack-build-env.txt contains outputs from a failed build.
[spack-build-out.txt](https://github.com/spack/spack/files/12837059/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/12837060/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mtaillefumier** [comment] 2023-10-07 07:37
I am surprized this is failing because I continuously compile cp2k with gcc 13 and never encountered this issue. I need to investigate but there is nothing wrong with the recipe or the code. I suspect an issue with the compiler installation but even so this error should be present in others packages. 

DBL_DECIMAL_DIG is defined in the c99 standard as well. I need to investigate this. Would it be possible to test again with this additional flags to spack.  

build_system=cmake

**Comment by yizeyi18** [comment] 2023-10-07 09:33
> I am surprized this is failing because I continuously compile cp2k with gcc 13 and never encountered this issue. I need to investigate but there is nothing wrong with the recipe or the code. I suspect an issue with the compiler installation but even so this error should be present in others packages.
> 
> DBL_DECIMAL_DIG is defined in the c99 standard as well. I need to investigate this. Would it be possible to test again with this additional flags to spack.
> 
> build_system=cmake

Using cmake as build system, fails occured while detecting torch, quip and cosma. There may be some other problems yet.
Ignoring these fails (by cutting off their flags), cp2k succeeds to be compiled (and fails during linking against libvori), and the compile flags seems changed: "-std=c99" disappears in 
[spack-build-out.txt](https://github.com/spack/spack/files/12837337/spack-build-out.txt)
 (see attachment).
Also, in CMakeList.txt of cp2k-2023.2, "set(CMAKE_CXX_STANDARD 11)" at line 52 appears. May this change some of the status...?

**Comment by mtaillefumier** [comment] 2023-10-07 10:00
Hmm, -std=c99 is not present in the cmake build commands that's why I never seen this error before (I turn in on though). The undefined constant is defined in float.h which is a compiler header file. 
The C++ standard does not interfere with C so we can leave this alone. 
I need to test it this further, but the recipe is most likely correct and the problem lies elsewhere.

**Comment by haampie** [comment] 2023-10-13 08:06
> DBL_DECIMAL_DIG is defined in the c99 standard as well. I need to investigate this. Would it be possible to test again with this additional flags to spack.

It's not part of C99, it's C11, according to https://en.cppreference.com/w/c/types/limits#Limits_of_floating_point_types.

The issue is that CP2K bumped it's C standard requirement and the Spack package wasn't updated. Fixed in #40494.

**Comment by alalazo** [comment] 2023-10-30 12:53
Should we close this, now that #40494 has been merged?

**Comment by mtaillefumier** [comment] 2023-10-30 13:58
We can close this issue I think.

**Comment by yizeyi18** [comment] 2023-10-30 14:10
I think too.

**Closed as completed** 2023-10-30 14:25 UTC
Labels: build-error
