### ISSUE TITLE
Trouble with variants and hyphens?

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#4967] opened 2017-08-03 23:12 UTC
Previously, I was able to build *trilinos* against a specific version of *superlu-dist* like this:

```
spack install trilinos+superlu-dist ^superlu-dist@4.3 ^netlib-lapack
```

However, with the current _develop_ branch, I get this error:

```
==> Error: trilinos does not depend on superlu-dist
```

Using `spack info` and reviewing `trilinos/package.py` it is clear that the `+superlu-dist` variant should be available.  I'm wondering if this is broken due to the hyphen in the name.  (I should note that `spack install trilinos+boost ^boost@1.63.0` seems to work.)

Any ideas on why this doesn't work any longer?

**Comment by adamjstewart** [comment] 2017-08-03 23:48
Fixed by #4968. The problem is that the `superlu-dist` dependency was conditional on the version of `trilinos`. Since Spack doesn't concretize the `trilinos` version until after it reads your command-line spec, it didn't know that it depended on `superlu-dist`.

**Comment by adamjstewart** [comment] 2017-08-03 23:51
@davydden I believe this bug was introduced in #1053, specifically https://github.com/LLNL/spack/commit/0e04e65ae0108437e6bf5d3e2233cdbc775fd136. But it sounds like @KineticTheory just ran into this for the first time, so I'm confused.

**Comment by adamjstewart** [comment] 2017-08-03 23:55
Anyway, this is a fairly common concretization bug. As it was before, `trilinos+superlu-dist` didn't depend on `superlu-dist`, but `trilinos@version+superlu-dist` does depend on `superlu-dist`. You can confirm this by specifying any version:
```
$ spack spec trilinos+superlu-dist ^superlu-dist
Input spec
--------------------------------
trilinos+superlu-dist
    ^superlu-dist

Normalized
--------------------------------
==> Error: trilinos does not depend on superlu-dist
$ spack spec trilinos@12.10.1+superlu-dist ^superlu-dist
...
<doesn't crash>
```

**Closed** 2017-08-04 13:17 UTC
Labels: concretization
