### ISSUE TITLE
"spack config add" fails for config:concretizer due to enum requirement

### ISSUE THREAD

**Issue by joshessman-llnl** [LLNL/spack#23259] opened 2021-04-26 17:49 UTC
### Steps to reproduce the issue

```console
$ spack config --scope defaults add config:concretizer:clingo
```

This also requires that `concretizer: original` *not* be present in `etc/.../config.yaml` - this may be an unsupported configuration.

### Error Message

```console
$ spack config --scope defaults add config:concretizer:clingo
spack.config.ConfigError: Cannot determine valid type for path 'config:concretizer'.
```

### Information on your system

* **Spack:** 0.16.1
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** original

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

The issue appears to be the logic in [get_valid_type](https://github.com/spack/spack/blob/develop/lib/spack/spack/config.py#L1036) - because it uses the "default-constructed" instance of a type for schema checking, it only works with JSONSchema's `type` attribute - it does not appear to consider the case where the `enum` attribute is also used.

Fixing this may require traversing the schema, and either:
1. Using the enum values to determine the time (when `enum` is used)
2. Grabbing the required type information directly (from the `type` attr)

**Comment by joshessman-llnl** [comment] 2021-04-26 17:49
Tag: @becker33

**Comment by alalazo** [comment] 2021-04-28 13:02
Duplicate of #17543

**Closed as completed** 2021-10-29 16:44 UTC
Labels: bug, configuration, commands, triage
