### ISSUE TITLE
Installation issue: glib cannot find meson binary

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#39245] opened 2023-08-03 08:41 UTC
### Steps to reproduce the issue

```console
$ spack install glib
```

### Error message

<details><summary>Error message</summary>

<pre>
==> Installing glib-2.76.4-ztgdpl7nmv7cvhowj4mbhd7bcvwjdbdj [19/19]
==> No binary for glib-2.76.4-ztgdpl7nmv7cvhowj4mbhd7bcvwjdbdj found: installing from source
==> Using cached archive: /Users/mdorier/Code/spack/var/spack/cache/_source-cache/archive/5a/5a5a191c96836e166a7771f7ea6ca2b0069c603c7da3cba1cd38d1694a395dda.tar.xz
==> Ran patch() for glib
==> glib: Executing phase: 'meson'
==> Error: ProcessError: /home/mdorier.linux/.spack-sw/linux-ubuntu23.04-aarch64/gcc-12.2.0/meson-1.2.0-ys4frq4ozmzg3mu2re6zwqxgxgro7egt/bin/meson: No such file or directory
    Command: '/home/mdorier.linux/.spack-sw/linux-ubuntu23.04-aarch64/gcc-12.2.0/meson-1.2.0-ys4frq4ozmzg3mu2re6zwqxgxgro7egt/bin/meson' 'setup' '/tmp/mdorier/spack-stage/spack-stage-glib-2.76.4-ztgdpl7nmv7cvhowj4mbhd7bcvwjdbdj/spack-src' '-Dprefix=/home/mdorier.linux/.spack-sw/linux-ubuntu23.04-aarch64/gcc-12.2.0/glib-2.76.4-ztgdpl7nmv7cvhowj4mbhd7bcvwjdbdj' '-Dlibdir=/home/mdorier.linux/.spack-sw/linux-ubuntu23.04-aarch64/gcc-12.2.0/glib-2.76.4-ztgdpl7nmv7cvhowj4mbhd7bcvwjdbdj/lib' '-Dbuildtype=release' '-Dstrip=false' '-Ddefault_library=shared' '-Dwrap_mode=nodownload' '-Dlibmount=disabled' '-Ddtrace=false' '-Dsystemtap=false' '-Dselinux=disabled' '-Dgtk_doc=false' '-Dlibelf=enabled'
See build log for details:
  /tmp/mdorier/spack-stage/spack-stage-glib-2.76.4-ztgdpl7nmv7cvhowj4mbhd7bcvwjdbdj/spack-build-out.txt
</pre></details>

It looks like it cannot find `meson`. `meson@1.2.0` was installed by spack at the specified location, however everything is in a `local` subdirectory (e.g. the meson executable is in `<prefix>/local/bin` instead of `<prefix>/bin`).

Tagging the glib and meson maintainers: @eli-schwartz @michaelkuhn

### Information on your system

* **Spack:** 0.21.0.dev0 (d456f32685bcb4a018ac917c7673bff727791733)
* **Python:** 3.11.4
* **Platform:** linux-ubuntu23.04-aarch64
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by eli-schwartz** [comment] 2023-08-03 10:55
This looks to me like the kind of problem that likely has pip as the underlying cause, so pinging the generic PythonPackage experts...

@adamjstewart @pradyunsg

This looks like something to do with install scheme detection?

**Comment by adamjstewart** [comment] 2023-08-03 16:45
Duplicate of:

* https://github.com/spack/spack/issues/37632
* https://github.com/spack/spack/issues/33923
* https://github.com/spack/spack/issues/32769
* https://github.com/spack/spack/issues/32662
* https://github.com/spack/spack/pull/31939

See https://github.com/pypa/pip/issues/10978 for the upstream tracking issue.

The issue is that the system Python that comes with many popular Linux distros has been hacked to change the installation directory layout. Unfortunately, this also influences where pip will install packages.

The only current workaround is to let Spack install Python instead of using an externally-installed Python.

**Closed as completed by adamjstewart** 2023-08-03 16:45 UTC
Labels: build-error
