### ISSUE TITLE
Ipopt fails to build on OSX with clang

### ISSUE THREAD

**Issue by futuretristan** [LLNL/spack#3903] opened 2017-04-19 11:24 UTC
When I try and install Ipopt on OSX 10.11.6 with clang via `spack install ipopt`, then the build fails with the messages
`ld: -rpath can only be used when creating a dynamic final linked image`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

The corresponding section in my compilers.yaml looks like this
compilers:
```
\- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: elcapitan
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /opt/local/bin/gfortran-mp-5
      fc: /opt/local/bin/gfortran-mp-5
    spec: clang@8.0.0-apple
    target: x86_6
```

If I compile Ipopt manually and independent of spack, everything works fine with the following configure line `../configure F77=gfortran-mp-5 --prefix="/Users/StTrSchl/libs/ipopt/lib/Ipopt-3.12.5-clang"`. Hard to say what's different to the Spack approach, as I don't know anything about the environment variables Spack sets for the build.

**Comment by davydden** [comment] 2017-04-19 11:35
spack's package looks reasonable: https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/ipopt/package.py Try digging into configure logs.

>  I don't know anything about the environment variables Spack sets for the build.

check `build.env` in the stage folder.

**Comment by davydden** [comment] 2017-04-19 11:36
> ../configure F77=gfortran-mp-5 --prefix="/Users/StTrSchl/libs/ipopt/lib/Ipopt-3.12.5-clang"

if you really want to compare apples to apples, you need to use the same configure line as Spack does (provide mumps, blas/lapack, etc), see `build.out`.

**Comment by futuretristan** [comment] 2017-04-19 12:15
In `spack-build.out` I can see how Ipopt is configured by Spack:
```
==> './configure' '--prefix=/Users/StTrSchl/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/ipopt-3.12.4-kn52zlg6bn5vrljgl67tdjamvzs42335' '--with-mumps-incdir=/Users/StTrSchl/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/mumps-5.1.1-yrmirsoafjv34fjtzefuiqadvjseaosf/include' '--with-mumps-lib=-L/Users/StTrSchl/spack/opt/spack/darwin-elcapitan-x86_64/clang-8.0.0-apple/mumps-5.1.1-yrmirsoafjv34fjtzefuiqadvjseaosf/lib -ldmumps -lmumps_common -lpord -lmpiseq' '--enable-shared'
```

I can manually build and link against the Spack libraries with the same command by just adding `F77=gfortran-mp-5`.

There must be a problem with the Spack environment variables. in `spack-build.env` I can see 4 environment variables that contain `[...]=-Wl,-rpath,`. I loaded them via `export [...]=-Wl,-rpath,`, but still the manual build works well (as expected, because all these variables start with SPACK_ and will probably not be considered by Ipopt in a manual build). Is there a way to load alle the variables from the .env file with a single command (there are a lot)?

**Comment by davydden** [comment] 2017-04-19 12:17
> Is there a way to load alle the variables from the .env file with a single command

`spack env ipopt bash` will set up your environment exactly the same and ready to build from the command line.

**Comment by futuretristan** [comment] 2017-04-19 12:32
With the Spack environment I can reproduce the error. After the Spack "wrapper" for clang++ is called 
`/Users/StTrSchl/spack/lib/spack/env/clang/clang++ [...]`
, the error 
`ld: -rpath can only be used when creating a dynamic final linked image` 
appears. There is an environment variable `SPACK_CXX_RPATH_ARG=-Wl,-rpath,` which I suspect is causing this.

**Comment by davydden** [comment] 2017-04-19 12:33
@tgamblin @alalazo @adamjstewart any ideas?

**Comment by futuretristan** [comment] 2017-04-19 12:37
When I change the Spack environment variable
`CXX=/Users/StTrSchl/spack/lib/spack/env/clang/clang++`
to
`CXX=/usr/bin/clang++`
, avoiding the Spack wrapper, then the build works fine.

**Comment by futuretristan** [comment] 2017-04-21 07:16
Can anyone at least reproduce the problem?

**Comment by davydden** [comment] 2017-04-21 07:40
yes, i can:
```
(cd .libs/libipopt.lax/libtmatrices.a && ar x /Users/davydden/spack/var/spack/stage/ipopt-3.12.4-wccgpftvzsih7o6rerb6ghfvze5b24cn/Ipopt-3.12.4/Ipopt/src/Interfaces/../LinAlg/TMatrices/.libs/libtmatrices.a)
/Users/davydden/spack/lib/spack/env/clang/clang++ -r -keep_private_externs -nostdlib -o .libs/libipopt.1.10.4.dylib-master.o  .libs/IpInterfacesRegOp.o .libs/IpIpoptApplication.o .libs/IpSolveStatistics.o .libs/IpStdCInterface.o .libs/IpStdFInterface.o .libs/IpStdInterfaceTNLP.o .libs/IpTNLPAdapter.o .libs/IpTNLPReducer.o  .libs/libipopt.lax/libLinearSolverLoader.a/HSLLoader.o .libs/libipopt.lax/libLinearSolverLoader.a/LibraryHandler.o .libs/libipopt.lax/libLinearSolverLoader.a/PardisoLoader.o  .libs/libipopt.lax/libcgpenalty.a/IpCGPenaltyCq.o .libs/libipopt.lax/libcgpenalty.a/IpCGPenaltyData.o .libs/libipopt.lax/libcgpenalty.a/IpCGPenaltyLSAcceptor.o .libs/libipopt.lax/libcgpenalty.a/IpCGPenaltyRegOp.o .libs/libipopt.lax/libcgpenalty.a/IpCGPerturbationHandler.o .libs/libipopt.lax/libcgpenalty.a/IpCGSearchDirCalc.o .libs/libipopt.lax/libcgpenalty.a/IpPiecewisePenalty.o  .libs/libipopt.lax/libipoptalg.a/IpAdaptiveMuUpdate.o .libs/libipopt.lax/libipoptalg.a/IpAlgBuilder.o .libs/libipopt.lax/libipoptalg.a/IpAlgorithmRegOp.o .libs/libipopt.lax/libipoptalg.a/IpAugRestoSystemSolver.o .libs/libipopt.lax/libipoptalg.a/IpBacktrackingLineSearch.o .libs/libipopt.lax/libipoptalg.a/IpDefaultIterateInitializer.o .libs/libipopt.lax/libipoptalg.a/IpEquilibrationScaling.o .libs/libipopt.lax/libipoptalg.a/IpExactHessianUpdater.o .libs/libipopt.lax/libipoptalg.a/IpFilter.o .libs/libipopt.lax/libipoptalg.a/IpFilterLSAcceptor.o .libs/libipopt.lax/libipoptalg.a/IpGenAugSystemSolver.o .libs/libipopt.lax/libipoptalg.a/IpGradientScaling.o .libs/libipopt.lax/libipoptalg.a/IpIpoptAlg.o .libs/libipopt.lax/libipoptalg.a/IpIpoptCalculatedQuantities.o .libs/libipopt.lax/libipoptalg.a/IpIpoptData.o .libs/libipopt.lax/libipoptalg.a/IpIteratesVector.o .libs/libipopt.lax/libipoptalg.a/IpLeastSquareMults.o .libs/libipopt.lax/libipoptalg.a/IpLimMemQuasiNewtonUpdater.o .libs/libipopt.lax/libipoptalg.a/IpLoqoMuOracle.o .libs/libipopt.lax/libipoptalg.a/IpLowRankAugSystemSolver.o .libs/libipopt.lax/libipoptalg.a/IpLowRankSSAugSystemSolver.o .libs/libipopt.lax/libipoptalg.a/IpMonotoneMuUpdate.o .libs/libipopt.lax/libipoptalg.a/IpNLPBoundsRemover.o .libs/libipopt.lax/libipoptalg.a/IpNLPScaling.o .libs/libipopt.lax/libipoptalg.a/IpOptErrorConvCheck.o .libs/libipopt.lax/libipoptalg.a/IpOrigIpoptNLP.o .libs/libipopt.lax/libipoptalg.a/IpOrigIterationOutput.o .libs/libipopt.lax/libipoptalg.a/IpPDFullSpaceSolver.o .libs/libipopt.lax/libipoptalg.a/IpPDPerturbationHandler.o .libs/libipopt.lax/libipoptalg.a/IpPDSearchDirCalc.o .libs/libipopt.lax/libipoptalg.a/IpPenaltyLSAcceptor.o .libs/libipopt.lax/libipoptalg.a/IpProbingMuOracle.o .libs/libipopt.lax/libipoptalg.a/IpQualityFunctionMuOracle.o .libs/libipopt.lax/libipoptalg.a/IpRestoConvCheck.o .libs/libipopt.lax/libipoptalg.a/IpRestoFilterConvCheck.o .libs/libipopt.lax/libipoptalg.a/IpRestoIpoptNLP.o .libs/libipopt.lax/libipoptalg.a/IpRestoIterateInitializer.o .libs/libipopt.lax/libipoptalg.a/IpRestoIterationOutput.o .libs/libipopt.lax/libipoptalg.a/IpRestoMinC_1Nrm.o .libs/libipopt.lax/libipoptalg.a/IpRestoPenaltyConvCheck.o .libs/libipopt.lax/libipoptalg.a/IpRestoRestoPhase.o .libs/libipopt.lax/libipoptalg.a/IpStdAugSystemSolver.o .libs/libipopt.lax/libipoptalg.a/IpTimingStatistics.o .libs/libipopt.lax/libipoptalg.a/IpUserScaling.o .libs/libipopt.lax/libipoptalg.a/IpWarmStartIterateInitializer.o  .libs/libipopt.lax/liblinsolvers.a/IpLinearSolversRegOp.o .libs/libipopt.lax/liblinsolvers.a/IpMa27TSolverInterface.o .libs/libipopt.lax/liblinsolvers.a/IpMa28Partition.o .libs/libipopt.lax/liblinsolvers.a/IpMa28TDependencyDetector.o .libs/libipopt.lax/liblinsolvers.a/IpMa57TSolverInterface.o .libs/libipopt.lax/liblinsolvers.a/IpMa77SolverInterface.o .libs/libipopt.lax/liblinsolvers.a/IpMa86SolverInterface.o .libs/libipopt.lax/liblinsolvers.a/IpMa97SolverInterface.o .libs/libipopt.lax/liblinsolvers.a/IpMc19TSymScalingMethod.o .libs/libipopt.lax/liblinsolvers.a/IpMumpsSolverInterface.o .libs/libipopt.lax/liblinsolvers.a/IpPardisoSolverInterface.o .libs/libipopt.lax/liblinsolvers.a/IpSlackBasedTSymScalingMethod.o .libs/libipopt.lax/liblinsolvers.a/IpTripletToCSRConverter.o .libs/libipopt.lax/liblinsolvers.a/IpTSymDependencyDetector.o .libs/libipopt.lax/liblinsolvers.a/IpTSymLinearSolver.o  .libs/libipopt.lax/libcommon.a/IpDebug.o .libs/libipopt.lax/libcommon.a/IpJournalist.o .libs/libipopt.lax/libcommon.a/IpObserver.o .libs/libipopt.lax/libcommon.a/IpOptionsList.o .libs/libipopt.lax/libcommon.a/IpRegOptions.o .libs/libipopt.lax/libcommon.a/IpTaggedObject.o .libs/libipopt.lax/libcommon.a/IpUtils.o  .libs/libipopt.lax/liblinalg.a/IpBlas.o .libs/libipopt.lax/liblinalg.a/IpCompoundMatrix.o .libs/libipopt.lax/liblinalg.a/IpCompoundSymMatrix.o .libs/libipopt.lax/liblinalg.a/IpCompoundVector.o .libs/libipopt.lax/liblinalg.a/IpDenseGenMatrix.o .libs/libipopt.lax/liblinalg.a/IpDenseSymMatrix.o .libs/libipopt.lax/liblinalg.a/IpDenseVector.o .libs/libipopt.lax/liblinalg.a/IpDiagMatrix.o .libs/libipopt.lax/liblinalg.a/IpExpandedMultiVectorMatrix.o .libs/libipopt.lax/liblinalg.a/IpExpansionMatrix.o .libs/libipopt.lax/liblinalg.a/IpIdentityMatrix.o .libs/libipopt.lax/liblinalg.a/IpLapack.o .libs/libipopt.lax/liblinalg.a/IpLowRankUpdateSymMatrix.o .libs/libipopt.lax/liblinalg.a/IpMatrix.o .libs/libipopt.lax/liblinalg.a/IpMultiVectorMatrix.o .libs/libipopt.lax/liblinalg.a/IpScaledMatrix.o .libs/libipopt.lax/liblinalg.a/IpSumMatrix.o .libs/libipopt.lax/liblinalg.a/IpSumSymMatrix.o .libs/libipopt.lax/liblinalg.a/IpSymScaledMatrix.o .libs/libipopt.lax/liblinalg.a/IpTransposeMatrix.o .libs/libipopt.lax/liblinalg.a/IpVector.o .libs/libipopt.lax/liblinalg.a/IpZeroMatrix.o .libs/libipopt.lax/liblinalg.a/IpZeroSymMatrix.o  .libs/libipopt.lax/libtmatrices.a/IpGenTMatrix.o .libs/libipopt.lax/libtmatrices.a/IpSymTMatrix.o .libs/libipopt.lax/libtmatrices.a/IpTripletHelper.o 
ld: -rpath can only be used when creating a dynamic final linked image
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by davydden** [comment] 2017-04-21 12:08
@jppelteret had similar issues here https://groups.google.com/forum/#!topic/spack/SS8RnCnf_I4

**Comment by davydden** [comment] 2017-04-21 12:13
from that discussion, here's an explanation (for `flint`, but applies here as well):

> The problem is that we are linking an helper library with “-Wl,-r”. 
From the man page of ld on OS X: 
-r          Merges object files to produce another mach-o object file with file type MH_OBJECT. 

> For rpath to make sense you have to link a dynamical object, which is not 
what is done here. The logic of the spack wrapper may need to parse and recognise 
this particular option before adding rpath.

**Comment by davydden** [comment] 2017-04-21 12:31
the problem is that wrapper sees the line 

```
/Users/davydden/spack/lib/spack/env/clang/clang++ -r -keep_private_externs -nostdlib -o .libs/libipopt.1.10.4.dylib-master.o  .libs/IpInterfacesRegOp.o .libs/IpIpoptApplication.o .libs/IpSolveStatistics.o .libs/IpStdCInterface.o .libs/IpStdFInterface.o .libs/IpStdInterfaceTNLP.o .libs/IpTNLPAdapter.o .libs/IpTNLPReducer.o  .libs/libipopt.lax/libLinearSolverLoader.a/HSLLoader.o .libs/libipopt.lax/libLinearSolverLoader.a/LibraryHandler.o .libs/libipopt.lax/libLinearSolverLoader.a/PardisoLoader.o  .libs/libipopt.lax/libcgpenalty.a/IpCGPenaltyCq.o .libs/libipopt.lax/libcgpenalty.a/IpCGPenaltyData.o .libs/libipopt.lax/libcgpenalty.a/IpCGPenaltyLSAcceptor.o .libs/libipopt.lax/libcgpenalty.a/IpCGPenaltyRegOp.o .libs/libipopt.lax/libcgpenalty.a/IpCGPerturbationHandler.o .libs/libipopt.lax/libcgpenalty.a/IpCGSearchDirCalc.o .libs/libipopt.lax/libcgpenalty.a/IpPiecewisePenalty.o  .libs/libipopt.lax/libipoptalg.a/IpAdaptiveMuUpdate.o .libs/libipopt.lax/libipoptalg.a/IpAlgBuilder.o .libs/libipopt.lax/libipoptalg.a/IpAlgorithmRegOp.o .libs/libipopt.lax/libipoptalg.a/IpAugRestoSystemSolver.o .libs/libipopt.lax/libipoptalg.a/IpBacktrackingLineSearch.o .libs/libipopt.lax/libipoptalg.a/IpDefaultIterateInitializer.o .libs/libipopt.lax/libipoptalg.a/IpEquilibrationScaling.o .libs/libipopt.lax/libipoptalg.a/IpExactHessianUpdater.o .libs/libipopt.lax/libipoptalg.a/IpFilter.o .libs/libipopt.lax/libipoptalg.a/IpFilterLSAcceptor.o .libs/libipopt.lax/libipoptalg.a/IpGenAugSystemSolver.o .libs/libipopt.lax/libipoptalg.a/IpGradientScaling.o .libs/libipopt.lax/libipoptalg.a/IpIpoptAlg.o .libs/libipopt.lax/libipoptalg.a/IpIpoptCalculatedQuantities.o .libs/libipopt.lax/libipoptalg.a/IpIpoptData.o .libs/libipopt.lax/libipoptalg.a/IpIteratesVector.o .libs/libipopt.lax/libipoptalg.a/IpLeastSquareMults.o .libs/libipopt.lax/libipoptalg.a/IpLimMemQuasiNewtonUpdater.o .libs/libipopt.lax/libipoptalg.a/IpLoqoMuOracle.o .libs/libipopt.lax/libipoptalg.a/IpLowRankAugSystemSolver.o .libs/libipopt.lax/libipoptalg.a/IpLowRankSSAugSystemSolver.o .libs/libipopt.lax/libipoptalg.a/IpMonotoneMuUpdate.o .libs/libipopt.lax/libipoptalg.a/IpNLPBoundsRemover.o .libs/libipopt.lax/libipoptalg.a/IpNLPScaling.o .libs/libipopt.lax/libipoptalg.a/IpOptErrorConvCheck.o .libs/libipopt.lax/libipoptalg.a/IpOrigIpoptNLP.o .libs/libipopt.lax/libipoptalg.a/IpOrigIterationOutput.o .libs/libipopt.lax/libipoptalg.a/IpPDFullSpaceSolver.o .libs/libipopt.lax/libipoptalg.a/IpPDPerturbationHandler.o .libs/libipopt.lax/libipoptalg.a/IpPDSearchDirCalc.o .libs/libipopt.lax/libipoptalg.a/IpPenaltyLSAcceptor.o .libs/libipopt.lax/libipoptalg.a/IpProbingMuOracle.o .libs/libipopt.lax/libipoptalg.a/IpQualityFunctionMuOracle.o .libs/libipopt.lax/libipoptalg.a/IpRestoConvCheck.o .libs/libipopt.lax/libipoptalg.a/IpRestoFilterConvCheck.o .libs/libipopt.lax/libipoptalg.a/IpRestoIpoptNLP.o .libs/libipopt.lax/libipoptalg.a/IpRestoIterateInitializer.o .libs/libipopt.lax/libipoptalg.a/IpRestoIterationOutput.o .libs/libipopt.lax/libipoptalg.a/IpRestoMinC_1Nrm.o .libs/libipopt.lax/libipoptalg.a/IpRestoPenaltyConvCheck.o .libs/libipopt.lax/libipoptalg.a/IpRestoRestoPhase.o .libs/libipopt.lax/libipoptalg.a/IpStdAugSystemSolver.o .libs/libipopt.lax/libipoptalg.a/IpTimingStatistics.o .libs/libipopt.lax/libipoptalg.a/IpUserScaling.o .libs/libipopt.lax/libipoptalg.a/IpWarmStartIterateInitializer.o  .libs/libipopt.lax/liblinsolvers.a/IpLinearSolversRegOp.o .libs/libipopt.lax/liblinsolvers.a/IpMa27TSolverInterface.o .libs/libipopt.lax/liblinsolvers.a/IpMa28Partition.o .libs/libipopt.lax/liblinsolvers.a/IpMa28TDependencyDetector.o .libs/libipopt.lax/liblinsolvers.a/IpMa57TSolverInterface.o .libs/libipopt.lax/liblinsolvers.a/IpMa77SolverInterface.o .libs/libipopt.lax/liblinsolvers.a/IpMa86SolverInterface.o .libs/libipopt.lax/liblinsolvers.a/IpMa97SolverInterface.o .libs/libipopt.lax/liblinsolvers.a/IpMc19TSymScalingMethod.o .libs/libipopt.lax/liblinsolvers.a/IpMumpsSolverInterface.o .libs/libipopt.lax/liblinsolvers.a/IpPardisoSolverInterface.o .libs/libipopt.lax/liblinsolvers.a/IpSlackBasedTSymScalingMethod.o .libs/libipopt.lax/liblinsolvers.a/IpTripletToCSRConverter.o .libs/libipopt.lax/liblinsolvers.a/IpTSymDependencyDetector.o .libs/libipopt.lax/liblinsolvers.a/IpTSymLinearSolver.o  .libs/libipopt.lax/libcommon.a/IpDebug.o .libs/libipopt.lax/libcommon.a/IpJournalist.o .libs/libipopt.lax/libcommon.a/IpObserver.o .libs/libipopt.lax/libcommon.a/IpOptionsList.o .libs/libipopt.lax/libcommon.a/IpRegOptions.o .libs/libipopt.lax/libcommon.a/IpTaggedObject.o .libs/libipopt.lax/libcommon.a/IpUtils.o  .libs/libipopt.lax/liblinalg.a/IpBlas.o .libs/libipopt.lax/liblinalg.a/IpCompoundMatrix.o .libs/libipopt.lax/liblinalg.a/IpCompoundSymMatrix.o .libs/libipopt.lax/liblinalg.a/IpCompoundVector.o .libs/libipopt.lax/liblinalg.a/IpDenseGenMatrix.o .libs/libipopt.lax/liblinalg.a/IpDenseSymMatrix.o .libs/libipopt.lax/liblinalg.a/IpDenseVector.o .libs/libipopt.lax/liblinalg.a/IpDiagMatrix.o .libs/libipopt.lax/liblinalg.a/IpExpandedMultiVectorMatrix.o .libs/libipopt.lax/liblinalg.a/IpExpansionMatrix.o .libs/libipopt.lax/liblinalg.a/IpIdentityMatrix.o .libs/libipopt.lax/liblinalg.a/IpLapack.o .libs/libipopt.lax/liblinalg.a/IpLowRankUpdateSymMatrix.o .libs/libipopt.lax/liblinalg.a/IpMatrix.o .libs/libipopt.lax/liblinalg.a/IpMultiVectorMatrix.o .libs/libipopt.lax/liblinalg.a/IpScaledMatrix.o .libs/libipopt.lax/liblinalg.a/IpSumMatrix.o .libs/libipopt.lax/liblinalg.a/IpSumSymMatrix.o .libs/libipopt.lax/liblinalg.a/IpSymScaledMatrix.o .libs/libipopt.lax/liblinalg.a/IpTransposeMatrix.o .libs/libipopt.lax/liblinalg.a/IpVector.o .libs/libipopt.lax/liblinalg.a/IpZeroMatrix.o .libs/libipopt.lax/liblinalg.a/IpZeroSymMatrix.o  .libs/libipopt.lax/libtmatrices.a/IpGenTMatrix.o .libs/libipopt.lax/libtmatrices.a/IpSymTMatrix.o .libs/libipopt.lax/libtmatrices.a/IpTripletHelper.o 
ld: -rpath can only be used when creating a dynamic final linked image
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

as `ccld` mode (compile and link) instead of `ld` (link), and RPATH's are [turned off](https://github.com/LLNL/spack/blob/develop/lib/spack/env/cc#L215-L226) only when 
```
if [[ ($arg == -r && $mode == ld) || ($arg == -Wl,-r && $mode == ccld) ]]; then
```
whereas we have `-r` and `ccld`.

I am not sure if this is an error with mode identification or the `if` condition.

 @tgamblin @alalazo @adamjstewart  can you please comment on the compiler wrapper modes and this issue?

I can say that the issue can be trivially fixed by extending the `if`in wrappers to 
```
        if [[ ($arg == -r && $mode == ld) || ($arg == -r && $mode == ccld) || ($arg == -Wl,-r && $mode == ccld) ]]; then
```
but again, not sure if this is the proper solution.

@futuretristan for now, you can hack-in your own copy of Spack as I explained above to get things going...

**Closed** 2017-05-01 02:16 UTC
Labels: bug, compilers, macOS
