### ISSUE TITLE
`target` not honored in environment/`spack.yaml`

### ISSUE THREAD

**Issue by ChristianTackeGSI** [LLNL/spack#33889] opened 2022-11-14 13:46 UTC
### Steps to reproduce

```console
spack$ cat my-env/spack.yaml 
spack:
  packages:
    all:
      target: [zen]
  specs:
  - zlib
  # concretizer:
  #   unify: true
  view: false
spack$ spack env activate -d my-env
spack$ spack concretize -f
==> Concretized zlib
 -   yoaxqe6  zlib@1.2.13%gcc@10.2.1+optimize+pic+shared build_system=makefile arch=linux-debian11-skylake_avx512
```

Note the `skylake_avx512` and not `zen`.

This used to work in at least 0.16 (probably 0.17).

### Information on your system

* **Spack:** 0.19.0.dev0 (a4cec82841228266d10734ecae2056f2980bf482)
* **Python:** 3.9.2
* **Platform:** linux-debian11-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment] 2022-11-14 13:49
You will want to use package requirements now instead of package preferences: https://spack.readthedocs.io/en/latest/build_settings.html#package-requirements the docs have been updated to suggest requirements first. See the first paragraph of https://spack.readthedocs.io/en/latest/build_settings.html#package-preferences too

**Comment by ChristianTackeGSI** [comment] 2022-11-14 14:04
Hi @haampie, thanks for your very fast answer!

> You will want to use package requirements now instead of package preferences: https://spack.readthedocs.io/en/latest/build_settings.html#package-requirements the docs have been updated to suggest requirements first.

```console
spack$ head -4 my-env/spack.yaml 
spack:
  packages:
    all:
      require: target=zen
spack$ spack concretize -f
==> Error: Cannot satisfy requirement group for package 'zlib'
```

What am I missing? (`spack -d` just gives a big stack trace, but nothing more useful it seems to me.)

(#32528 should be fixed in my version, right?)

> See the first paragraph of https://spack.readthedocs.io/en/latest/build_settings.html#package-preferences too

Which exactly lists the `target`?

**Comment by haampie** [comment] 2022-11-14 14:35
Hm @alalazo can you have a look?

**Comment by alalazo** [comment] 2022-11-14 15:04
By default we only consider targets that are compatible with the current host, so you would need to:
```console
$ spack config add concretizer:targets:host_compatible:false
```
before trying to compile for `zen` on a `skylake`. ~That said it seems we have some regression with preferences and requirements, since adding the above I am able to force targets from cli, but not from `packages.yaml`. I'll check why's that and report any findings here.~ [^1]

[^1]: Apologies, I had a dirty ~/.spack from moving from another branch. It should work after you add the configuration above!

**Comment by ChristianTackeGSI** [comment] 2022-11-14 15:21
Okay, This seems to work better now:
```yaml
spack:
  packages:
    all:
      require: target=zen
  specs:
  - zlib
  concretizer:
    targets:
      host_compatible: false
  view: false
```

NOTE: If the old syntax is supposed to not work any longer, why is there no warning (with a suggestion to move to the `require:` syntax)?

Also from the docs it seems that the old and new syntax have different semantics? The old was a "preference" while the new one is a "requirement"?

**Comment by alalazo** [comment] 2022-11-14 15:23
They should both work. The old syntax is a preference, so Spack might do something different. The new syntax is a requirement, so Spack will either use that target or error.

**Comment by ChristianTackeGSI** [comment] 2022-11-14 15:29
Okay, it looks like the concretizer/targets/host_compatible=false setting also makes the old syntax work.

I'll leave it to you, whether or not it is feasible to note that setting in the concretization error?

Many thanks for the clarifications!

**Comment by alalazo** [comment] 2022-11-14 15:41
> I'll leave it to you, whether or not it is feasible to note that setting in the concretization error?

I'll close this issue for now. Pinging both @becker33 and @scheibelp since the conversation here might be useful for the discussions that are currently ongoing on better error messages from clingo.

**Closed as not planned by alalazo** 2022-11-14 15:41 UTC
Labels: bug, not-a-bug
