### ISSUE TITLE
boost+thread builds libboost_thread-mt.so instead of libboost_thread.so

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1820] opened 2016-09-21 21:39 UTC
Maybe someone more familiar with Boost than I am could take a look at this? I've ran into a couple packages now (currently working on OpenFOAM) that depend on `boost+thread`. But they can't find it because they're looking for `-lboost_thread` instead of `-lboost_thread-mt`. Any reason why Boost isn't building `libboost_thread.so`?

**Comment by davydden** [comment] 2016-09-22 05:39
see http://stackoverflow.com/questions/3031768/boost-thread-linking-boost-thread-vs-boost-thread-mt

on my macOS there is also only `boost_thread-mt`. It looks like those packages are broken. Maybe report upstream?

**Comment by tgamblin** [comment] 2016-09-22 08:29
I thought we resolved this a while ago, but apparently we did not.  Boost has some layout options to add a bunch of decorations to library names.  They're [described here](http://www.boost.org/doc/libs/1_61_0/more/getting_started/unix-variants.html#library-naming).  Basically if you add `--layout=tagged` to the `b2` call, it adds these.  Prior to boost 1.4.something they were the default; since then a default boost install uses `--layout=system`, which adds no decoration and libraries install with thread support by default.

This came up in the [March 31 telcon](https://github.com/LLNL/spack/wiki/Telcon:-2016-03-31) and we decided with no objection that boost should install _without_ `--layout=tagged` and would use `--layout=system`.  I think there are two good reasons to do this:

1. `--layout=system` mirrors a system package manager install, so packages that know how to find a system boost will also know how to find a Spack boost.
1. Spack installs things in their own prefix, and options like this should be handled at the variant level, not the library naming level.

Apparently we discussed this in #710, and @eschnett pointed out that if two variants of boost could potentially be used at the same time, it made sense to stick them in the same directory.  We mostly agreed that was the case here, and @eschnett was ok with moving to a system layout in #710, but apparently no one followed up and made the change, and the issue is actually still open.

I think we should make this change and install with the system layout by default for the reasons outlined above.

That *may* break existing packages (though I kind of doubt it will -- a system that knows to look for `-mt` probably also knows that some systems don't have it), in which case there are two things we could reasonably do:

1. Patch those packages to work with a system boost layout; or
2. Add a `tagged` variant to boost and make the special packages depend on `boost+tagged`.  It think this is reasonable to do b/c tagged library names are effectively an ABI change, or at the very least they're a build configuration change.

**Comment by adamjstewart** [comment] 2016-09-22 14:53
> That _may_ break existing packages (though I kind of doubt it will -- a system that knows to look for `-mt` probably also knows that some systems don't have it)

I knew I ran into this problem before! I actually had to patch Cantera to get it to work with this boost library naming scheme because it couldn't find `boost_thread` and `boost_system`:
```python
# Threadsafe build, requires Boost
if '+threadsafe' in spec:
    options.extend([
        'build_thread_safe=yes',
        'boost_inc_dir={0}'.format(spec['boost'].prefix.include),
        'boost_lib_dir={0}'.format(spec['boost'].prefix.lib),
        'boost_thread_lib=boost_thread-mt,boost_system-mt'
    ])
else:
    options.append('build_thread_safe=no')
```
So basically, I'm fine with whatever naming scheme we end up choosing. We just need to remember to update Cantera to work with this.

I'm fine with either not building the `boost_thread-mt` libraries or creating `boost_thread` symlinks to them.

**Comment by tgamblin** [comment] 2016-10-05 13:48
@scheibelp: if you have a chance in between custom view trees and modules, do you want to take a stab at this?

**Comment by scheibelp** [comment] 2016-10-05 17:46
Yes I'll do that

**Closed** 2016-10-11 13:46 UTC
Labels: package
