### ISSUE TITLE
Installation issue: fenics (mumps" and "scotch-6.1.1 are failed )

### ISSUE THREAD

**Issue by MostafaMollaali** [LLNL/spack#28775] opened 2022-02-04 09:26 UTC
### Steps to reproduce the issue

- spack add py-fenics-dolfinx ^petsc+mumps+hypre cflags="-O3" fflags="-O3"
- spack install

"mumps" and "scotch-6.1.1" are failed 

### Information on your system

spack debug report
* **Spack:** 0.17.1-1061-18b83c3833
* **Python:** 3.9.10
* **Platform:** darwin-bigsur-cannonlake
* **Concretizer:** clingo

### Mumps
[spack-build-01-install-out.txt](https://github.com/spack/spack/files/8001511/spack-build-01-install-out.txt)
[spack-build-env-mods.txt](https://github.com/spack/spack/files/8001512/spack-build-env-mods.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/8001513/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8001514/spack-build-out.txt)

### scotch
[scotch_6.1.1.tar.gz](https://github.com/spack/spack/files/8001550/scotch_6.1.1.tar.gz)
[spack-build-01-install-out.txt](https://github.com/spack/spack/files/8001552/spack-build-01-install-out.txt)
[spack-build-env-mods.txt](https://github.com/spack/spack/files/8001553/spack-build-env-mods.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/8001554/spack-build-env.txt)
[Uploading spack-build-out.txt…]()

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by garth-wells** [comment] 2022-06-23 09:08
Duplicate of #23812 (`scotch` build failure).

Note that the most recent release of `fenics-dolfinx` no longer requires `scotch`.

**Closed as completed by garth-wells** 2022-06-23 09:08 UTC
Labels: build-error
