### ISSUE TITLE
Spack CI does not copy included config files into job_scratch_dir

### ISSUE THREAD

**Issue by qwofford** [LLNL/spack#24512] opened 2021-06-24 22:36 UTC
If allspack configs are defined within `spack.yaml`, a dynamic pipeline executes correctly. However, when the `spack.yaml` includes include paths, the CI jobs which result do not copy the includes into the scratch dir before attempting to activate the environment, resulting in an error.

### Steps to reproduce the issue

1. Create a spack environment that has include files
2. Run `spack ci generate`
3. push to gitlab CI runner
4. Observe error message from child jobs.

### Error Message

```console
==> Error: Detected 4 missing include path(s):
<project home>/jobs_scratch_dir/common/repos.yaml
<project home>/jobs_scratch_dir/common/modules.yaml
<project home>/jobs_scratch_dir/common/mirrors.yaml
<project home>/jobs_scratch_dir/common/config.yaml
```

**Comment by alalazo** [comment] 2023-07-10 20:23
@scottwittenburg Is this one still a valid issue?

**Comment by alalazo** [comment] 2023-07-10 20:27
Duplicate of #24292

**Closed as not planned by alalazo** 2023-07-10 20:27 UTC
Labels: bug, triage, pipelines
