### ISSUE TITLE
Package conflict detected on the same package/Package merge blocked by file

### ISSUE THREAD

**Issue by asesidaa** [LLNL/spack#28793] opened 2022-02-05 09:06 UTC
### Steps to reproduce

When I am trying to install in an environment, the packages all build successfully, but when generating the view, I get ``Package conflict detected`` errors on the same package, I wonder whether this is a bug or something is wrong in my spec?

### Error message

```console
lib/spack/spack/filesystem_view.py:643 ==> [2022-02-05-17:03:01.659629] Error: [/mnt/nfs4/node2/home/jiych/env/.spack-env/._view/bv3kugkyftl6fvchzphtznr2yruyq52j] Package conflict detected:
   (Linked) numactl@2.0.14%gcc@10.3.0 patches=4e1d78cbbb85de625bad28705e748856033eaafab92a66dffd383a3d7e00cc94,62fc8a8bf7665a60e8f4c93ebbd535647cebf74198f7afafec4c085a8825c006,ff37630df599cfabf0740518b91ec8daaf18e8f288b19adaae5364dc1f6b2296 arch=linux-ubuntu20.04-zen2/v2t24i2
(Specified) numactl@2.0.14%gcc@10.3.0 patches=4e1d78cbbb85de625bad28705e748856033eaafab92a66dffd383a3d7e00cc94,62fc8a8bf7665a60e8f4c93ebbd535647cebf74198f7afafec4c085a8825c006,ff37630df599cfabf0740518b91ec8daaf18e8f288b19adaae5364dc1f6b2296 arch=linux-ubuntu20.04-zen2/v2t24i2
lib/spack/spack/filesystem_view.py:643 ==> [2022-02-05-17:03:01.660184] Error: [/mnt/nfs4/node2/home/jiych/env/.spack-env/._view/bv3kugkyftl6fvchzphtznr2yruyq52j] Package conflict detected:
   (Linked) hwloc@2.7.0%gcc@10.3.0~cairo+cuda~gl~libudev+libxml2~netloc~nvml~opencl+pci~rocm+shared arch=linux-ubuntu20.04-zen2/y7nme4r
(Specified) hwloc@2.7.0%gcc@10.3.0~cairo+cuda~gl~libudev+libxml2~netloc~nvml~opencl+pci~rocm+shared arch=linux-ubuntu20.04-zen2/y7nme4r
lib/spack/spack/filesystem_view.py:643 ==> [2022-02-05-17:03:01.660653] Error: [/mnt/nfs4/node2/home/jiych/env/.spack-env/._view/bv3kugkyftl6fvchzphtznr2yruyq52j] Package conflict detected:
   (Linked) hdf5@1.10.8%gcc@10.3.0~cxx~fortran+hl~ipo~java+mpi+shared~szip~threadsafe+tools api=default build_type=RelWithDebInfo arch=linux-ubuntu20.04-zen2/tncmghc
(Specified) hdf5@1.10.8%gcc@10.3.0~cxx~fortran+hl~ipo~java+mpi+shared~szip~threadsafe+tools api=default build_type=RelWithDebInfo arch=linux-ubuntu20.04-zen2/tncmghc
lib/spack/spack/filesystem_view.py:643 ==> [2022-02-05-17:03:01.661055] Error: [/mnt/nfs4/node2/home/jiych/env/.spack-env/._view/bv3kugkyftl6fvchzphtznr2yruyq52j] Package conflict detected:
   (Linked) libnl@3.3.0%gcc@10.3.0 arch=linux-ubuntu20.04-zen2/3ap2aad
(Specified) libnl@3.3.0%gcc@10.3.0 arch=linux-ubuntu20.04-zen2/3ap2aad
lib/spack/spack/filesystem_view.py:643 ==> [2022-02-05-17:03:01.661447] Error: [/mnt/nfs4/node2/home/jiych/env/.spack-env/._view/bv3kugkyftl6fvchzphtznr2yruyq52j] Package conflict detected:
   (Linked) libpciaccess@0.16%gcc@10.3.0 arch=linux-ubuntu20.04-zen2/pj3lkza
(Specified) libpciaccess@0.16%gcc@10.3.0 arch=linux-ubuntu20.04-zen2/pj3lkza
lib/spack/spack/filesystem_view.py:643 ==> [2022-02-05-17:03:01.661878] Error: [/mnt/nfs4/node2/home/jiych/env/.spack-env/._view/bv3kugkyftl6fvchzphtznr2yruyq52j] Package conflict detected:
   (Linked) protobuf@3.12.3%gcc@10.3.0+shared build_type=Release arch=linux-ubuntu20.04-zen2/6lemm5n
(Specified) protobuf@3.12.3%gcc@10.3.0+shared build_type=Release arch=linux-ubuntu20.04-zen2/6lemm5n
lib/spack/spack/filesystem_view.py:643 ==> [2022-02-05-17:03:01.662314] Error: [/mnt/nfs4/node2/home/jiych/env/.spack-env/._view/bv3kugkyftl6fvchzphtznr2yruyq52j] Package conflict detected:
   (Linked) re2@2021-06-01%gcc@10.3.0~ipo+pic+shared build_type=RelWithDebInfo arch=linux-ubuntu20.04-zen2/fytmuks
(Specified) re2@2021-06-01%gcc@10.3.0~ipo+pic+shared build_type=RelWithDebInfo arch=linux-ubuntu20.04-zen2/fytmuks
lib/spack/spack/filesystem_view.py:643 ==> [2022-02-05-17:03:01.662703] Error: [/mnt/nfs4/node2/home/jiych/env/.spack-env/._view/bv3kugkyftl6fvchzphtznr2yruyq52j] Package conflict detected:
   (Linked) util-linux-uuid@2.36.2%gcc@10.3.0 arch=linux-ubuntu20.04-zen2/grghggy
(Specified) util-linux-uuid@2.36.2%gcc@10.3.0 arch=linux-ubuntu20.04-zen2/grghggy
lib/spack/spack/filesystem_view.py:643 ==> [2022-02-05-17:03:01.663126] Error: [/mnt/nfs4/node2/home/jiych/env/.spack-env/._view/bv3kugkyftl6fvchzphtznr2yruyq52j] Package conflict detected:
   (Linked) libxml2@2.9.12%gcc@10.3.0~python arch=linux-ubuntu20.04-zen2/4hrlnlv
(Specified) libxml2@2.9.12%gcc@10.3.0~python arch=linux-ubuntu20.04-zen2/4hrlnlv
lib/spack/spack/filesystem_view.py:643 ==> [2022-02-05-17:03:01.663576] Error: [/mnt/nfs4/node2/home/jiych/env/.spack-env/._view/bv3kugkyftl6fvchzphtznr2yruyq52j] Package conflict detected:
   (Linked) openblas@0.3.19%gcc@10.3.0~bignuma~consistent_fpcsr~ilp64+locking+pic+shared symbol_suffix=none threads=none arch=linux-ubuntu20.04-zen2/ixyrqkw
(Specified) openblas@0.3.19%gcc@10.3.0~bignuma~consistent_fpcsr~ilp64+locking+pic+shared symbol_suffix=none threads=none arch=linux-ubuntu20.04-zen2/ixyrqkw
lib/spack/spack/filesystem_view.py:643 ==> [2022-02-05-17:03:01.664064] Error: [/mnt/nfs4/node2/home/jiych/env/.spack-env/._view/bv3kugkyftl6fvchzphtznr2yruyq52j] Package conflict detected:
   (Linked) openmpi@4.1.2%gcc@10.3.0~atomics+cuda+cxx~cxx_exceptions+gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker~pmi~pmix+romio~singularity~sqlite3+static+thread_multiple+vt+wrapper-rpath fabrics=hcoll,knem,ucx,xpmem schedulers=none arch=linux-ubuntu20.04-zen2/edxqazp
(Specified) openmpi@4.1.2%gcc@10.3.0~atomics+cuda+cxx~cxx_exceptions+gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker~pmi~pmix+romio~singularity~sqlite3+static+thread_multiple+vt+wrapper-rpath fabrics=hcoll,knem,ucx,xpmem schedulers=none arch=linux-ubuntu20.04-zen2/edxqazp
lib/spack/spack/filesystem_view.py:643 ==> [2022-02-05-17:03:01.664502] Error: [/mnt/nfs4/node2/home/jiych/env/.spack-env/._view/bv3kugkyftl6fvchzphtznr2yruyq52j] Package conflict detected:
   (Linked) openssl@1.1.1m%gcc@10.3.0~docs certs=system arch=linux-ubuntu20.04-zen2/bwsnth4
(Specified) openssl@1.1.1m%gcc@10.3.0~docs certs=system arch=linux-ubuntu20.04-zen2/bwsnth4
lib/spack/spack/filesystem_view.py:643 ==> [2022-02-05-17:03:01.664980] Error: [/mnt/nfs4/node2/home/jiych/env/.spack-env/._view/bv3kugkyftl6fvchzphtznr2yruyq52j] Package conflict detected:
   (Linked) python@3.9.9%gcc@10.3.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87,4c2457325f2b608b1b6a2c63087df8c26e07db3e3d493caf36a56f0ecf6fb768,f2fd060afc4b4618fe8104c4c5d771f36dc55b1db5a4623785a4ea707ec72fb4 arch=linux-ubuntu20.04-zen2/ffvrbtf
(Specified) python@3.9.9%gcc@10.3.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87,4c2457325f2b608b1b6a2c63087df8c26e07db3e3d493caf36a56f0ecf6fb768,f2fd060afc4b4618fe8104c4c5d771f36dc55b1db5a4623785a4ea707ec72fb4 arch=linux-ubuntu20.04-zen2/ffvrbtf
lib/spack/spack/filesystem_view.py:643 ==> [2022-02-05-17:03:01.665403] Error: [/mnt/nfs4/node2/home/jiych/env/.spack-env/._view/bv3kugkyftl6fvchzphtznr2yruyq52j] Package conflict detected:
   (Linked) rdma-core@34.0%gcc@10.3.0~ipo build_type=RelWithDebInfo arch=linux-ubuntu20.04-zen2/ladyvja
(Specified) rdma-core@34.0%gcc@10.3.0~ipo build_type=RelWithDebInfo arch=linux-ubuntu20.04-zen2/ladyvja
```

### Information on your system

* **Spack:** 0.17.1-1066-932408ac2b
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by asesidaa** [comment] 2022-02-06 15:45
I also got `==> Error: Package merge blocked by file: File blocks directory: /mnt/nfs4/node2/home/jiych/env/.spack-env/._view/r3n2sgjkf5377cy5egzgozyqjuloynhh/lib/modules` sometimes and this file belongs to openjdk, I can't figure out the root cause of the problem

**Comment by asesidaa** [comment] 2022-02-06 16:45
```console
Traceback (most recent call last):                                                                                                                                                  
  File "/mnt/nfs4/node2/home/jiych/spack/bin/spack", line 98, in <module>                                                                                                             
    sys.exit(spack.main.main())                                                                                                                                                     
  File "/mnt/nfs4/node2/home/jiych/spack/lib/spack/spack/main.py", line 900, in main                                                                                                  
    return _main(argv)                                                                                                                                                              
  File "/mnt/nfs4/node2/home/jiych/spack/lib/spack/spack/main.py", line 883, in _main                                                                                                 
    return _invoke_command(command, parser, args, unknown)                                                                                                                          
  File "/mnt/nfs4/node2/home/jiych/spack/lib/spack/spack/main.py", line 553, in _invoke_command                                                                                       
    return_val = command(parser, args)                                                                                                                                              
  File "/mnt/nfs4/node2/home/jiych/spack/lib/spack/spack/cmd/install.py", line 361, in install                                                                                          
    env.install_all(**kwargs)                                                                                                                                                       
  File "/mnt/nfs4/node2/home/jiych/spack/lib/spack/spack/environment/environment.py", line 1492, in install_all                                                                         
    self.install_specs(None, **install_args)                                                                                                                                        
  File "/mnt/nfs4/node2/home/jiych/spack/lib/spack/spack/environment/environment.py", line 1547, in install_specs                                                                     
    self.regenerate_views()                                                                                                                                                         
  File "/mnt/nfs4/node2/home/jiych/spack/lib/spack/spack/environment/environment.py", line 1310, in regenerate_views                                                                  
    view.regenerate(specs, self.roots())                                                                                                                                            
  File "/mnt/nfs4/node2/home/jiych/spack/lib/spack/spack/environment/environment.py", line 523, in regenerate                                                                         
    view.add_specs(*installed_specs_for_view,                                                                                                                                       
  File "/mnt/nfs4/node2/home/jiych/spack/lib/spack/spack/filesystem_view.py", line 334, in add_specs                                                                                  
    if all(map(self.add_standalone, standalones)):                                                                                                                                  
  File "/mnt/nfs4/node2/home/jiych/spack/lib/spack/spack/filesystem_view.py", line 388, in add_standalone                                                                             
    self.merge(spec)                                                                                                                                                                
  File "/mnt/nfs4/node2/home/jiych/spack/lib/spack/spack/filesystem_view.py", line 415, in merge                                                                                      
    raise MergeConflictError(conflicts[0])                                                                                                                                        
llnl.util.link_tree.MergeConflictError: Package merge blocked by file: File blocks directory: /mnt/nfs4/node2/home/jiych/env/.spack-env/._view/r3n2sgjkf5377cy5egzgozyqjuloynhh/lib/modules
```
Stacktrace for merge errors.

**Comment by asesidaa** [comment] 2022-02-07 09:54
```yaml
  # add package specs to the `specs` list
  specs: [cmake@3.22.1%gcc@10.3.0, python@3.9.9%gcc@10.3.0, nccl%gcc@10.3.0 cuda_arch=70,
    py-tensorflow%gcc@10.3.0+mpi cuda_arch=70, openjdk@11.0.12_7%gcc@10.3.0, protobuf@3.12.3%gcc@10.3.0,
    py-tensorboard%gcc@10.3.0, py-horovod@0.23.0%gcc@10.3.0 controllers=mpi cuda_arch=70
      frameworks=tensorflow tensor_ops=nccl, 'openmpi@4.1.2%gcc@10.3.0+cuda+cxx+thread_multiple
      fabrics=hcoll,knem,ucx,xpmem', ucx@1.11.2%gcc@10.3.0+cuda+knem+mlx5-dv+thread_multiple+xpmem
      cuda_arch=70, py-pip@21.3.1%gcc@10.3.0]
  view: true
  concretization: together
```
Packages in spack.yaml file. Does this error means conflict between packages?

**Comment by asesidaa** [comment] 2022-02-08 06:52
A minimal reproducible example:
```yaml
spack:
  # add package specs to the `specs` list
  specs: [ucx@1.11.2%gcc@10.3.0+cuda+knem+mlx5-dv+thread_multiple+xpmem, openjdk@11.0.12_7%gcc@10.3.0]
  view: true
  concretization: together
```
@adamjstewart Are there any conflict in this spec?

**Comment by flxmr** [comment] 2022-02-26 11:11
I encounter the thing when trying to fix this: https://github.com/spack/spack/issues/29237 using spack activate. There seems to be something seriously wrong with environments since last November, as this is not the only issue I have.

**Comment by alalazo** [comment] 2023-04-07 09:02
There's a typo in this reproducer:
```yaml
spack:
  # add package specs to the `specs` list
  specs: [ucx@1.11.2%gcc@10.3.0+cuda+knem+mlx5_dv+thread_multiple+xpmem, openjdk@11.0.12_7%gcc@10.3.0]
  view: true
  concretization: together
```
as the variant `mlx_dv` needs an underscore rather than a dash.

**Comment by alalazo** [comment] 2023-04-07 09:08
I could reproduce, but I think this is self-explanatory:
```console
[ ... ]
==> Updating view at /tmp/issues/.spack-env/view
==> Error: 1 fatal error(s) when merging prefixes:
    `/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.4.0/knem-1.1.4-ucuilv6usl77ebatzmrjog6lojlx4n7g/lib/modules` and `/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.4.0/openjdk-11.0.12_7-o5mr6jfpfhmyr4ox5ncmcnmlvtwgncdv/lib/modules` both project to `lib/modules`
```
both `knem` and `openjdk` want to take over `<view>/lib/modules`. I think you can add more boilerplate to configuration to avoid this clash. Closing, but  let me know if this is not the case and I'll reopen.

**Closed as not planned** 2023-04-07 09:09 UTC
Labels: bug, not-a-bug
