### ISSUE TITLE
Make Apple Clang a separate compiler from LLVM Clang

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#16967] opened 2020-06-05 13:44 UTC
As a user I want Apple Clang to be a separate compiler from LLVM Clang so that they are distinguished more clearly.

### Rationale

Despite the name of Apple's compiler is just `clang` the version numbers differ from vanilla LLVM and have to be distinguished by a `-apple` suffix. This is causing a complexity increase in e.g. the code that injects microarchitecture specific flags and is inconsistent with the treatment of other LLVM based compilers like `armclang`.

### Description

The proposed solution is to turn Apple Clang into a separate compiler named `appleclang` and reserve `clang` for vanilla LLVM.

### Additional information

Once implemented this modification will change the hashes of every spec built with Apple Clang. This likely means the modification should go into the next minor release after the merge, not the next patch release.

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment] 2020-06-05 13:44
@becker33 @adrienbernede

**Comment by adrienbernede** [comment] 2020-06-05 15:44
I would like to complete this with a related "bug" on MacOS (darwin-mojave-skylake), with Spack `0.14.2-1313-0086c4754`:

With `clang@10.0.0-apple` already configured (by autodetection), Spack won’t detect vanilla llvm 10.0.0 installed with Homebrew even when provided with the installation location.
Commenting Apple Clang config results in successful detection of LLVM Clang.

Although both are the same version I would expect Spack to make the difference. This issue would solve that.

**Comment by adamjstewart** [comment] 2020-06-06 20:58
Duplicate of #12011

**Closed as completed by adamjstewart** 2020-06-06 20:58 UTC
Labels: duplicate, feature
