### ISSUE TITLE
Installation issue: llvm +libcxx requires python distutils

### ISSUE THREAD

**Issue by luraess** [LLNL/spack#28619] opened 2022-01-26 22:49 UTC
### Steps to reproduce the issue

```
 spack install julia@1.7.1
 ```

### Information on your system

* **Spack:** 0.17.1-973-991438a242
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

### Additional information

@haampie  @vchuravy,  julia@1.7.0 builds fine, but since #27280 there is a build issue in llvm I guess
```
==> llvm: Executing phase: 'cmake'
==> llvm: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 1:
    'ninja' '-j16' '-v'
#[...]
```

See [spack-build-out.txt](https://github.com/spack/spack/files/7946130/spack-build-out.txt).

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by luraess** [comment] 2022-01-29 22:05
Resolved via
```
spack install julia ^llvm targets=amdgpu,nvptx ~clang ~compiler-rt ~libcxx ~lld ~lldb ~polly
```

**Comment by vchuravy** [comment] 2022-01-29 22:19
```
FAILED: lib/libc++.a 
: && /home/luraess/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/cmake-3.22.2-u5sgtfaigyawlf7lgwou7vsjxf7lbzpq/bin/cmake -E rm -f lib/libc++.a && /home/luraess/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/binutils-2.37-5pd5g3ih6tjrq24nenu6sswwdsfbiyta/bin/ar Dqc lib/libc++.a  projects/libcxx/src/CMakeFiles/cxx_static.dir/algorithm.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/any.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/atomic.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/barrier.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/bind.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/charconv.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/chrono.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/condition_variable.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/condition_variable_destructor.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/exception.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/functional.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/future.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/hash.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/memory.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/mutex.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/mutex_destructor.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/new.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/optional.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/random_shuffle.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/shared_mutex.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/stdexcept.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/string.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/system_error.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/thread.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/typeinfo.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/utility.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/valarray.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/variant.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/vector.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/debug.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/random.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/ios.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/ios.instantiations.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/iostream.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/locale.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/regex.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/strstream.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/filesystem/operations.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/filesystem/directory_iterator.cpp.o projects/libcxx/src/CMakeFiles/cxx_static.dir/filesystem/int128_builtins.cpp.o && /home/luraess/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/binutils-2.37-5pd5g3ih6tjrq24nenu6sswwdsfbiyta/bin/ranlib -D lib/libc++.a && cd /tmp/luraess/spack-stage/spack-stage-llvm-12.0.1-6t4zgebgmmt6gda4awpd4apyot2nkcec/spack-build-6t4zgeb/projects/libcxx/src && /usr/bin/python3.8 /tmp/luraess/spack-stage/spack-stage-llvm-12.0.1-6t4zgebgmmt6gda4awpd4apyot2nkcec/spack-src/libcxx/utils/merge_archives.py -o /tmp/luraess/spack-stage/spack-stage-llvm-12.0.1-6t4zgebgmmt6gda4awpd4apyot2nkcec/spack-build-6t4zgeb/lib/libc++.a --ar /home/luraess/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/binutils-2.37-5pd5g3ih6tjrq24nenu6sswwdsfbiyta/bin/ar /tmp/luraess/spack-stage/spack-stage-llvm-12.0.1-6t4zgebgmmt6gda4awpd4apyot2nkcec/spack-build-6t4zgeb/lib/libc++.a /tmp/luraess/spack-stage/spack-stage-llvm-12.0.1-6t4zgebgmmt6gda4awpd4apyot2nkcec/spack-build-6t4zgeb/lib/libc++abi.a
Traceback (most recent call last):
  File "/tmp/luraess/spack-stage/spack-stage-llvm-12.0.1-6t4zgebgmmt6gda4awpd4apyot2nkcec/spack-src/libcxx/utils/merge_archives.py", line 12, in <module>
    import distutils.spawn
ModuleNotFoundError: No module named 'distutils.spawn'
```

So the issue is in libcxx

**Comment by vchuravy** [comment] 2022-01-29 22:34
Probably due to #27256, it looks like on some platforms one has to install `python3-distutils`

**Comment by vchuravy** [comment] 2022-01-29 22:47
I should also note that this is irrespective of the Julia package and is an issue with the llvm spec

**Comment by adamjstewart** [comment] 2022-01-30 02:38
I'm not sure what the best way to handle this is. Many system package managers split distutils out into a separate package despite it being part of the standard library. I'm not sure exactly how we would make a Spack package for distutils, and I also don't think it would be a good idea.

For users who face this issue, the obvious solution is to use the system package manager to install distutils if they have admin privileges, or to let Spack install Python itself if they don't.

In the long run, Julia needs to stop using distutils. Distutils is deprecated in Python 3.10 and will be removed in 3.12. All functionality has been moved to either sysconfig or setuptools.

**Comment by vchuravy** [comment] 2022-01-30 02:45
> In the long run, Julia needs to stop using distutils. Distutils is deprecated in Python 3.10 and will be removed in 3.12. All functionality has been moved to either sysconfig or setuptools.

This is not a Julia issue. This is an issue with upstream LLVM.

**Comment by vchuravy** [comment] 2022-01-30 02:46
https://github.com/llvm/llvm-project/blob/815786eb67e89d1efe35b0ad6c143d5d7cc5577a/libcxx/utils/merge_archives.py#L11

**Comment by luraess** [comment] 2022-01-31 11:18
Hitting following error when using https://github.com/spack/spack/issues/28619#issuecomment-1024995426 install in combination with CUDA.jl
```
using CUDA
A = CUDA.ones(Float64, 3,1)
julia: symbol lookup error: /home/luraess/.julia/artifacts/f1d0060dd1a7698898f46626e143e03a442af46f/lib/libLLVMExtra-12.so: undefined symbol: LLVMInitializeWebAssemblyTargetInfo, version JL_LLVM_12.0
```
Upon brief discussion with main dev from CUDA.jl, seems reason for it is mismatching LLVM builds wrt to the one used for Julia (and CUDA.jl). Also, they commented:
> if one really wants to build own LLVM, one should take care it exactly matches "ours": same patches, same targets, same symbol versioning, etc. we might be able to relax some of those requirements, but no guarantees.

Don't know what's feasible there. Also, would it maybe be possible to still provide Julia 1.7.1 binaries using the previous recipe (as Julia 1.7.0) in the meanwhile?

**Comment by haampie** [comment] 2022-01-31 11:45
We have the same patches etc. The only difference is fewer targets. I did not expect them to be a hard requirement.

Should work with

```
llvm targets=amdgpu,bpf,nvptx,webassembly
```

I can turn it into a hard constraint in julia's package.py

**Comment by luraess** [comment] 2022-01-31 12:05
Thanks @haampie ! testing it right now.

**Comment by luraess** [comment] 2022-01-31 13:34
Did some tests, seems all good until now with refined targets. Thanks!

**Comment by haampie** [comment] 2022-01-31 13:35
Actually I think we can close this issue, given that @adamjstewart pointed out the LLVM problem is more of a missing system dependency because of the odd way debian packages Python.

**Closed as completed by haampie** 2022-01-31 13:35 UTC
Labels: build-error

**Comment by vchuravy** [comment] 2022-01-31 13:54
We ideally would be able to make express that build dependency... Since right now we just randomly fail.

Maybe we just need to bootstrap python first ;)

**Comment by haampie** [comment] 2022-01-31 14:05
If you do `spack install llvm +libcxx` it will build the latest compatible Python, so it should work by default. Only if Python is marked external, you would have to make sure the external Python is equivalent to a Spack-installed Python.

Maybe an easier way to solve this is to add a distutils variant to Python, make `llvm +libcxx` depend on `python +distutils` explicitly, and auto-detect the variant in `spack external find python` (@adamjstewart)
