### ISSUE TITLE
Packages pick up dependencies that are not controlled by Spack in user enviornment 

### ISSUE THREAD

**Issue by Char-Aznable** [LLNL/spack#18802] opened 2020-09-19 18:44 UTC
There are quite a few cases where I run into situation where a package picks up wrong version of dependencies in my environment. For example, `spack install font-util` runs a wrong version of `fc-cache` in `/usr/bin` to install the fonts but failed. Another example is, the configure phase of `spack install r` picks up a bunch of dependencies in my home directory that are not part of spack:
```
...
checking for a BSD-compatible install... /home/aznable/local/bin/ginstall -c
checking for sed... /home/aznable/local/bin/sed
checking for which... /bin/which
checking for less... /bin/less
checking for gtar... /bin/gtar
checking for tex... /home/aznable/local/bin/tex
checking for pdftex... /home/aznable/local/bin/pdftex
checking for pdflatex... /home/aznable/local/bin/pdflatex
checking for makeindex... /home/aznable/local/bin/makeindex
checking for texi2any... /home/aznable/local/bin/texi2any
checking whether texi2any version is at least 5.1... yes
checking for ginstall-info... no
checking for install-info... /home/aznable/local/bin/install-info
checking for texi2dvi... /home/aznable/local/bin/texi2dvi
checking for kpsewhich... /home/aznable/local/bin/kpsewhich
checking for latex inconsolata package... missing
configure: WARNING: neither inconsolata.sty nor zi4.sty found: PDF vignettes and package manuals will not be rendered optimally
checking for unzip... /home/aznable/local/bin/unzip
checking for zip... /home/aznable/local/bin/zip
checking for gzip... /bin/gzip
checking for bzip2... /home/aznable/spack/opt/spack/linux-centos7-haswell/gcc-9.3.0/bzip2-1.0.8-mlz6pdrikglamnlrn55am5uvxl4xu6lz/bin/bzip2
checking for firefox... no
checking for mozilla... no
checking for galeon... no
checking for opera... no
checking for xdg-open... /bin/xdg-open
using default browser ... /bin/xdg-open
checking for acroread... no
checking for acroread4... no
checking for xdg-open... /bin/xdg-open
checking for working aclocal... found
checking for working autoconf... found
checking for working autoheader... found
checking for bison... bison -y
checking for notangle... false
checking for realpath... /home/aznable/local/bin/realpath
checking for pkg-config... /home/aznable/local/bin/pkg-config
...
```

Yet another example is here https://github.com/spack/spack/issues/18749, which is relevant to a few other build issues I have seen when building python packages such as `py-scipy`.

Note that I have never specified those dependencies as external packages in the spack config file. 

### Steps to reproduce the issue

```console
$ spack install font-util
$ spack install r
$ spack install python@3.8.5
...
```

### Error Message

see my description above

### Information on your system

* **Spack:** 0.15.4-1022-80fe51046
* **Python:** 3.8.5
* **Platform:** linux-centos7-haswell

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by robertu94** [comment] 2020-12-23 02:11
I had this problem too with font-util as well.  For me, it was fixed by removing my external pkg-config  which had a fontconfig package entry provided by my OS.  I've also seen this problem with a collaborator who extensively modified his PATH and LD_LIBRARY_PATH variables.  The problem is that it is not trivial to decide when to strip entries not provided by spack out since you never know where a particular "base-system" package is installed.

**Comment by alalazo** [comment] 2023-04-06 07:32
Hmm, this either needs fixing in some recipes or needs a stricter isolation of the build environment. In any case it's a "known" behavior of current Spack. Closing, but feel free to reopen if you have something more actionable.

**Closed as not planned by alalazo** 2023-04-06 07:32 UTC
Labels: bug, triage
