### ISSUE TITLE
Installation issue: xz

### ISSUE THREAD

**Issue by hseara** [LLNL/spack#16887] opened 2020-06-01 07:13 UTC
xz package cannot be downloaded from sourceforge.net

I can download the files through the browser, despite the fact that it takes ages to start the download.

### Steps to reproduce the issue

```console
$ spack install xz
==> Fetching https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
################################################################################################# 100.0%################################################################################################# 100.0%curl: (28) Operation timed out after 10001 milliseconds with 0 out of 0 bytes received                 

==> Failed to fetch file from URL: https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
    Curl failed with error 28
==> Fetching https://freefr.dl.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
################################################################################################# 100.0%curl: (28) Failed to connect to iweb.dl.sourceforge.net port 443: Connection timed out                 

==> Failed to fetch file from URL: https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
    Curl failed with error 28
==> Fetching https://netcologne.dl.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
################################################################################################# 100.0%################################################################################################# 100.0%curl: (28) Operation timed out after 10001 milliseconds with 0 out of 0 bytes received                 

==> Failed to fetch file from URL: https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
    Curl failed with error 28
==> Fetching https://pilotfiber.dl.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
################################################################################################# 100.0%curl: (28) Operation timed out after 10000 milliseconds with 0 out of 0 bytes received                 

==> Failed to fetch file from URL: https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
    Curl failed with error 28
==> Fetching https://downloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
################################################################################################# 100.0%curl: (28) Operation timed out after 10001 milliseconds with 0 out of 0 bytes received                 

==> Failed to fetch file from URL: https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
    Curl failed with error 28
==> Fetching http://kent.dl.sourceforge.net/sourceforge/lzmautils/files/xz-5.2.5.tar.bz2
################################################################################################# 100.0%curl: (28) Failed to connect to iweb.dl.sourceforge.net port 443: Connection timed out                 

==> Failed to fetch file from URL: https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
    Curl failed with error 28
==> Fetching from https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2 failed.
==> Fetching https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
################################################################################################# 100.0%################################################################################################# 100.0%curl: (28) Operation timed out after 10001 milliseconds with 0 out of 0 bytes received                 

==> Failed to fetch file from URL: https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
    Curl failed with error 28
==> Fetching from https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2 failed.
==> Error: FetchError: All fetchers failed for spack-stage-xz-5.2.5-pixet4f7srjq65ejmwr7meuuluej3rhg

...
```

### Information on your system

* **Spack:** 0.14.2-1284-de63e1c2a
* **Python:** 3.8.3
* **Platform:** linux-archrolling-westmere

and the same in a server in different location: 

* **Spack:** 0.14.2-1284-de63e1c
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake_avx512

### Additional information

Not generated

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment] 2020-06-01 15:36
I was not able to reproduce  on:

* **Spack:** 0.14.2-1285-ca98f58fe
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-broadwell

This is what I get instead:
```console
$ spack fetch xz
[ ... ]
==> Fetching from file:///tmp/pytest-of-culpo/pytest-16/test_ci_rebuild_basic0/working_dir/local_mirror/_source-cache/archive/51/5117f930900b341493827d63aa910ff5e011e0b994197c3b71c08a20228a42df.tar.bz2 failed.
==> Fetching https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
########################################################################################################################################### 100,0%########################################################################################################################################### 100,0%########################################################################################################################################### 100,0%
```
Can you check if this was just an intermittent issue with `xz`?

**Comment by hseara** [comment] 2020-06-01 19:22
Interestingly, I continue without being able to download the package.

```console
$ spack fetch xz
==> Fetching https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
######################################################################## 100.0%
curl: (28) Connection timed out after 10377 milliseconds
==> Failed to fetch file from URL: https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
    Curl failed with error 28
==> Fetching https://freefr.dl.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
######################################################################## 100.0%
curl: (28) Connection timed out after 10793 milliseconds
==> Failed to fetch file from URL: https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
    Curl failed with error 28
==> Fetching https://netcologne.dl.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
######################################################################## 100.0%
curl: (28) Operation timed out after 10850 milliseconds with 0 out of 0 bytes received
==> Failed to fetch file from URL: https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
    Curl failed with error 28
==> Fetching https://pilotfiber.dl.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
######################################################################## 100.0%
curl: (28) Connection timed out after 10515 milliseconds
==> Failed to fetch file from URL: https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
    Curl failed with error 28
==> Fetching https://downloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
######################################################################## 100.0%
curl: (28) Connection timed out after 10920 milliseconds
==> Failed to fetch file from URL: https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
    Curl failed with error 28
==> Fetching http://kent.dl.sourceforge.net/sourceforge/lzmautils/files/xz-5.2.5.tar.bz2
######################################################################## 100.0%
curl: (28) Connection timed out after 10374 milliseconds
==> Failed to fetch file from URL: https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
    Curl failed with error 28
==> Fetching from https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2 failed.
==> Fetching https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
######################################################################## 100.0%
curl: (28) Connection timed out after 10344 milliseconds
==> Failed to fetch file from URL: https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
    Curl failed with error 28
==> Fetching from https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2 failed.
==> Error: All fetchers failed for spack-stage-xz-5.2.5-mfzs3dk7yazdhc25w6lmtjkqactogn6m
```

Please note that I am trying this from two entirely different sites within the Czech Republic and another in Finland. So unless something funny is happening within Europe's internet and `sourceforge.net`, I do not understand how all three sites may be without access since Saturday.  This is the day I tried the installation first. 

Do you have any clue what can I check that could be useful to debug the issue?

**Comment by mwkrentel** [comment] 2020-06-01 23:18
Sourceforge is known for being slow to connect.  And your connections
are timing out after the default of 10 seconds.

You can reset this in `config.yaml`.  Try increasing the timeout to
something like 60 seconds.

```
  # Timeout in seconds used for downloading sources etc. This only applies
  # to the connection phase and can be increased for slow connections or
  # servers. 0 means no timeout.
  connect_timeout: 10
```

Can you wget the file directly?  If all else fails, you could download
the file manually and put it in a spack mirror.

**Comment by hseara** [comment] 2020-06-02 06:25
Thanks for the replies and help. 

There is certainly an issue of timeouts due to the slowness of the redirections in sourforge.net. I finally managed to download it from one of the mirrors after trying several times  http://kent.dl.sourceforge.net/sourceforge/lzmautils/files/xz-5.2.5.tar.bz2. I will also increase my time out as suggested.

By the way, when I try to download directly with curl I get the following message:
```console
$ curl https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
<html>
 <head>
  <title>301 Moved Permanently</title>
 </head>
 <body>
  <h1>301 Moved Permanently</h1>
  The resource has been moved to <a href="https://downloads.sourceforge.net/project/lzmautils/xz-5.2.5.tar.bz2">https://downloads.sourceforge.net/project/lzmautils/xz-5.2.5.tar.bz2</a>;
you should be redirected automatically.


 </body>
</html>
```
Maybe we should change the links anyway because now it has to do 3 jumps:

1-  https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
```console
$ curl https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.5.tar.bz2
<html>
 <head>
  <title>301 Moved Permanently</title>
 </head>
 <body>
  <h1>301 Moved Permanently</h1>
  The resource has been moved to <a href="https://downloads.sourceforge.net/project/lzmautils/xz-5.2.5.tar.bz2">https://downloads.sourceforge.net/project/lzmautils/xz-5.2.5.tar.bz2</a>;
you should be redirected automatically.


 </body>
</html>
```

2-  https://downloads.sourceforge.net/project/lzmautils/xz-5.2.5.tar.bz2
```console
$ curl https://downloads.sourceforge.net/project/lzmautils/xz-5.2.5.tar.bz2
<html>
 <head>
  <title>302 Found</title>
 </head>
 <body>
  <h1>302 Found</h1>
  The resource was found at <a href="https://managedway.dl.sourceforge.net/project/lzmautils/xz-5.2.5.tar.bz2">https://managedway.dl.sourceforge.net/project/lzmautils/xz-5.2.5.tar.bz2</a>;
you should be redirected automatically.


 </body>
</html>
```
3-  https://managedway.dl.sourceforge.net/project/lzmautils/xz-5.2.5.tar.bz2

**Comment by adamjstewart** [comment] 2021-01-16 20:28
Spack now has an official downloads mirror that is used by default, so users rarely have to access sourceforge unless they are adding a new package/version. I think it's safe to close this issue, given that we have a mirror and the solution is to increase the downloads timeout.

**Closed as completed by adamjstewart** 2021-01-16 20:28 UTC
Labels: build-error, fetching
