### ISSUE TITLE
m4 does not build with clang

### ISSUE THREAD

**Issue by sknigh** [LLNL/spack#4883] opened 2017-07-24 18:36 UTC
``` bash
spack install m4%clang
```
produces a linker error
```
make[2]: Entering directory `/spack-stage/spack-stage-1tj6uI/m4-1.4.18/spack-build/src'
  CC       m4.o
  CC       builtin.o
  CC       debug.o
  CC       eval.o
  CC       format.o
  CC       freeze.o
  CC       macro.o
  CC       input.o
  CC       output.o
  CC       path.o
  CC       symtab.o
  CCLD     m4
../lib/libm4.a(xmalloc.o): In function `xnmalloc':
spack/var/spack/stage/m4-1.4.18-tdbq4h34ahmclwg3cyzlpg4rnzcefsoz/m4-1.4.18/lib/xmalloc.c:(.text+0x71): undefined reference to `__muloti4'
```

I suspect the build fails to find symbols that otherwise come from libgcc. I tried setting ```LIBS=-lcompiler-rt``` without success.

**Comment by KineticTheory** [comment] 2017-07-24 23:08
I've also run into this problem.  My work around is to use the system provided m4 via a `package.yaml` entry.

**Comment by adamjstewart** [comment] 2017-07-25 00:49
It would probably be best to contact the `m4` developers on this one, I don't think it's a Spack bug.

**Comment by sknigh** [comment] 2017-07-25 18:02
KineticTheory has a good workaround, however I try to avoid including external packages because it tends to leak other environment information into builds (Python will get confused IIRC)

I found two other workable solutions:
1. In packages, ```depends_on('m4%gcc', type='build')```
2. From CLI, ```spack install software%clang ^m4%gcc```

**Comment by adamjstewart** [comment] 2017-07-25 18:18
> 1. In packages, `depends_on('m4%gcc', type='build')`

We definitely don't want to do this. Just because one compiler doesn't work doesn't mean GCC is the only compiler that works.

> 2. From CLI, `spack install software%clang ^m4%gcc`

This is a perfectly fine workaround until someone reports the bug to the `m4` developers and we get it fixed with a patch or new release.

**Comment by KineticTheory** [comment] 2017-07-26 01:03
I [reported](https://lists.gnu.org/archive/html/bug-m4/2017-07/msg00003.html) this issue to the m4 development team.  Apparently, the issue is with gnulib (not m4) and the gnulib folks claim that this particular m4@clang compile failure can be resolved by proper installation and use of clang.  See this [LLVM bug report](https://bugs.llvm.org/show_bug.cgi?id=16404), particularly comment 12.

Does anyone want to give their solution a try?

**Comment by sknigh** [comment] 2017-07-26 22:27
I get a lot of this in the output, but it makes a working executable.
``` bash
clang-4.0: warning: argument unused during compilation: '-rtlib=compiler-rt' [-Wunused-command-line-argument]
```

**Closed** 2017-07-28 16:32 UTC
Labels: build-error, clang
