### ISSUE TITLE
configure: error: C++ compiler missing or inoperational

### ISSUE THREAD

**Issue by chvillanuevap** [LLNL/spack#37] opened 2015-04-27 21:13 UTC
I downloaded `spack` and immediately proceeded to install GCC version 4.8.4 with:

```
spack install gcc@4.8.4
```

Notice that I'm on Ubuntu, and I have GCC version 4.8.2 already installed.

When Spack runs, I get the following error: `configure: error: C++ compiler missing or inoperational`.

However, if I type `which g++` or `which c++` I do get the compilers. As I mentioned before, I have GCC version 4.8.2 installed. I'm trying to install version 4.8.4 using Spack.

Inspecting the directory `spack-master/lib/spack/env/case-insensitive/` I noticed that the environment variable `c++` points to `cc`, which I think is what causes the error. Furthermore, every single symbolic link in this directory points to `cc`. Is there a reason for this?

Once I corrected these symbolic links, my installation worked.

**Comment by tgamblin** [comment] 2015-04-27 21:19
The links point at cc because that's the compiler wrapper that inserts RPATHs:
    http://scalability-llnl.github.io/spack/packaging_guide.html#the-install-environment

lib/spack/env is put first in your path during a build to control the environment, but the error messages aren't that great, and I have not tested much on ubuntu (though apparently I should -- maybe travis is a good place to do this).

Have you looked at ~/.spackconfig to see whether your compilers are set up correctly?  By default Spack will use the latest gcc to build, so if that is not set properly (e.g. if it has "None" for cc or c++) things will break.

**Comment by chvillanuevap** [comment] 2015-04-27 21:31
I have the following in my .spackconfig file:
```
[compiler "gcc@4.8"]
    cc = /usr/bin/gcc
    cxx = None
    f77 = /usr/bin/gfortran
    fc = /usr/bin/gfortran
```
It seems Ubuntu sets the variables `g++`, `c++`, and `cpp`, but not `cxx`.

**Comment by tgamblin** [comment] 2015-04-27 21:36
Is there a /usr/bin/g++?  If so can you send the output of gcc -dumpversion AND g++ -dumpversion?

The autodetection in Spack is done via per-compiler classes.  Look at lib/spack/spack/compilers/*.py, each of which extends Compiler in lib/spack/spack/compiler.py.  Compiler detection is done by searching your PATH in parallel and locating all the executables with names like gcc*, g++*.  It then detects the version of each and groups them by version -- it looks like there was something wrong when it ran g++, OR it didn't match the others.

**Comment by chvillanuevap** [comment] 2015-04-27 21:39
Yes, there is:

```
ls /usr/bin/g++
lrwxrwxrwx 1 root root 7 Apr  7  2014 /usr/bin/g++ -> g++-4.8
```

Both gcc -dumpversion and g++ -dumpversion return 4.8. cc, gfortran, cpp, and c++ also return 4.8.

**Comment by tgamblin** [comment] 2015-04-27 21:45
I'll have to find an ubuntu machine to test on sometime soon.  In the meantime, if you add back /usr/bin/g++ for cxx, then things *should* work better for you.  Spack should really warn if it doesn't find some of the compilers.

**Comment by chvillanuevap** [comment] 2015-04-27 22:03
In `lib/spack/spack/compilers/__init__.py`, in line 181, there is a check:
```
        if not all(n in items for n in _required_instance_vars):
            raise InvalidCompilerConfigurationError(cspec)
```
Even though `cxx` is set to `None`, this check does not raise an exception because `items` does have `cxx` as a key. `_required_instance_vars` is a list with `['cc','cxx','f77','fc']`, while `items` is a dictionary.

**Comment by tgamblin** [comment] 2015-04-27 22:16
Does that fix it for you?  If so can you send a PR?  I can put the change in as well but I cannot verify it right now.

**Comment by chvillanuevap** [comment] 2015-04-28 01:09
My first fix was to create a symbolic link `/usr/bin/cxx` -> `/usr/bin/cpp` in the command line. It seems Ubuntu does not have a `cxx` symbolic link by default.

My second fix (and the more generic one) was to modify `_required_instance_vars` (in `lib/spack/spack/compilers/__init__.py`) to include `cpp` rather than `cxx`, and to change the Compiler attribute `self.cxx` to `self.cpp` to match the variable in `_required_instance_vars`.

I do not know if you wish to change the `cxx` variable to `cpp`, but if you do, I can send a PR.

**Comment by adamjstewart** [comment] 2016-03-11 17:27
Does this bug still occur? Specifically, the part about Spack not picking up `g++` on Ubuntu. It seems like all of the other bugs mentioned in this issue stem from that fact.

**Comment by tgamblin** [comment] 2016-03-11 21:35
I added some compiler checks to the Travis CI output, and indeed at least on the Travis Ubuntu distro, cxx is found properly.  Closing for now -- please reopen if this happens again.

**Comment by weijianwen** [comment] 2017-01-02 13:56
Hi. This happens agin on Cent OS 7. spack fails to identify `g++` shipped with the OS, which leads to configuration failure during gcc@4.9.4 installation.

```
bin/spack compiler info gcc@4.8.5
gcc@4.8.5:
        paths:
                cc = /usr/bin/gcc
                cxx = None
                f77 = /usr/bin/gfortran
                fc = /usr/bin/gfortran
        modules  = []
        operating system  = centos7

ls /usr/bin/g++
/usr/bin/g++
```

**Comment by adamjstewart** [comment] 2017-01-02 14:11
@weijianwen Do you have a `/usr/bin/g++`? If you delete `~/.spack/compilers.yaml` and/or `~/.spack/<OS>/compilers.yaml` and run `spack compiler find`, does it pick it up the second time?

**Comment by weijianwen** [comment] 2017-01-02 14:19
Thank you, @adamjstewart . Readding compiler via `spack compiler find` after removing `~/.spack/compilers.yaml` and `~/.spack/<OS>/compilers.yaml` works for me!

```
# rm -rf ~/.spack/compilers.yaml; rm -rf ~/.spack/linux/compilers.yaml; bin/spack compiler find
==> Added 1 new compiler to /root/.spack/linux/compilers.yaml
    gcc@4.8.5

# bin/spack compiler info gcc@4.8.5
gcc@4.8.5:
        paths:
                cc = /usr/bin/gcc
                cxx = /usr/bin/g++
                f77 = /usr/bin/gfortran
                fc = /usr/bin/gfortran
        modules  = []
        operating system  = centos7
```

**Comment by adamjstewart** [comment] 2017-01-02 14:52
I think the cause of the problem is that either Spack was broken when you first checked it out and it has been fixed since then, or you didn't have a C++ compiler when you first checked Spack out and have installed one since then. Spack isn't yet smart enough to look for missing compilers after the fact.

**Closed by adamjstewart** 2017-01-02 14:52 UTC
