### ISSUE TITLE
Unused dependencies in an explicit spec produces constraint(?) errors

### ISSUE THREAD

**Issue by mauneyc-LANL** [LLNL/spack#26271] opened 2021-09-27 16:41 UTC
### Steps to reproduce

This arises in some environment setups with a configuration like
```yaml
spack:
  definitions:
  - mpi : [openmpi]
  - packages: [gsl]
  specs:
  - matrix:
    - [$packages]
    - [$^mpi]
# ...
```

The problem is reproducible simply with:

```console
$> spack spec gsl ^ openmpi
# errors....
```

I've tried this on various package specs (e.g. `spack spec fmt ^ openblas`) with similar error outputs. 

That is (from what I can tell), if a package does not have an explicit dependency on a dependency listed in the spec, there is an error. It appears to be a constraint error, although the output is somewhat inscrutable (see below). **The expected result** here is for spack to ignore explicit dependencies in the spec that are not dependencies of the package when concertizing.

The question is, should spack be able to concertize a spec that contains unused dependencies (& if so why is this setup failing), or is giving unused dependencies not permitted? I would add that having spack ignore these explicit dependencies is very useful for writing clean environment configurations.

Also, the tutorials seem to imply that this is acceptable (e.g. https://spack-tutorial.readthedocs.io/en/latest/tutorial_stacks.html). 

### Error message

```console
$ spack -d spec gsl ^openmpi
==> [2021-09-27-10:25:10.967159] Imported spec from built-in commands
==> [2021-09-27-10:25:10.968902] Imported spec from built-in commands
Input spec
--------------------------------
gsl
    ^openmpi

Concretized
--------------------------------
==> [2021-09-27-10:25:10.973701] Reading config file /home/mauneyc/devel/flecsph_local/flecsph-env/spack.yaml
==> [2021-09-27-10:25:10.990103] Reading config file /home/mauneyc/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-09-27-10:25:11.000871] Reading config file /home/mauneyc/spack/etc/spack/defaults/config.yaml
==> [2021-09-27-10:25:11.021815] DATABASE LOCK TIMEOUT: 3s
==> [2021-09-27-10:25:11.021937] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-09-27-10:25:11.022536] Reading config file /home/mauneyc/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-09-27-10:25:11.032822] DATABASE LOCK TIMEOUT: 3s
==> [2021-09-27-10:25:11.033119] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-09-27-10:25:11.033439] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2021-09-27-10:25:11.034850] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/mauneyc/spack/etc/spack/defaults
==> [2021-09-27-10:25:11.035166] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/mauneyc/spack/etc/spack/defaults/linux
==> [2021-09-27-10:25:11.035417] [BOOTSTRAP CONFIG SCOPE] name=system, path=/etc/spack
==> [2021-09-27-10:25:11.035543] [BOOTSTRAP CONFIG SCOPE] name=system/linux, path=/etc/spack/linux
==> [2021-09-27-10:25:11.035681] [BOOTSTRAP CONFIG SCOPE] name=site, path=/home/mauneyc/spack/etc/spack
==> [2021-09-27-10:25:11.035825] [BOOTSTRAP CONFIG SCOPE] name=site/linux, path=/home/mauneyc/spack/etc/spack/linux
==> [2021-09-27-10:25:11.035962] [BOOTSTRAP CONFIG SCOPE] name=user, path=/home/mauneyc/.spack
==> [2021-09-27-10:25:11.036075] [BOOTSTRAP CONFIG SCOPE] name=user/linux, path=/home/mauneyc/.spack/linux
==> [2021-09-27-10:25:11.039017] Reading config file /home/mauneyc/.spack/linux/compilers.yaml
==> [2021-09-27-10:25:11.059686] [BOOTSTRAP ROOT SPEC] clingo: clingo-bootstrap@spack+python %gcc target=x86_64
==> [2021-09-27-10:25:11.059825] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2021-09-27-10:25:11.060131] Reading config file /home/mauneyc/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-09-27-10:25:11.229048] Reading config file /home/mauneyc/spack/etc/spack/defaults/config.yaml
==> [2021-09-27-10:25:11.337219] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.9 /hmnv6gk5wha64k6r3s7hid35mzvhkuot" provides the "clingo" Python module
==> [2021-09-27-10:25:11.337629] Reading config file /home/mauneyc/spack/etc/spack/defaults/repos.yaml
==> [2021-09-27-10:25:12.854896] Reading config file /home/mauneyc/.spack/linux/compilers.yaml
==> [2021-09-27-10:25:12.869235] Reading config file /home/mauneyc/spack/etc/spack/defaults/config.yaml
==> [2021-09-27-10:25:12.891244] Reading config file /home/mauneyc/spack/etc/spack/defaults/packages.yaml
==> [2021-09-27-10:25:22.089714] The following constraints are unsatisfiable:
  condition(1126)
  condition(1573)
  condition(2609)
  condition_requirement(1597,"node","llvm")
  condition_requirement(1612,"node","llvm")
  dependency_condition(1126,"libmng","cmake")
  dependency_condition(1573,"llvm","cmake")
  dependency_condition(2609,"qt","libmng")
  dependency_type(1126,"build")
  dependency_type(1573,"build")
  dependency_type(2609,"build")
  node("openmpi")
==> [2021-09-27-10:25:22.099826] UnsatisfiableSpecError: gsl ^openmpi does not satisfy unknown
==> [2021-09-27-10:25:22.103516] Error: gsl ^openmpi does not satisfy unknown
Traceback (most recent call last):
  File "/home/mauneyc/spack/lib/spack/spack/main.py", line 797, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/mauneyc/spack/lib/spack/spack/main.py", line 525, in _invoke_command
    return_val = command(parser, args)
  File "/home/mauneyc/spack/lib/spack/spack/cmd/spec.py", line 109, in spec
    spec.concretize()
  File "/home/mauneyc/spack/lib/spack/spack/spec.py", line 2624, in concretize
    self._new_concretize(tests)
  File "/home/mauneyc/spack/lib/spack/spack/spec.py", line 2597, in _new_concretize
    raise spack.error.UnsatisfiableSpecError(
spack.error.UnsatisfiableSpecError: gsl ^openmpi does not satisfy unknown
```

### Information on your system

```console
$> spack debug report
* **Spack:** 0.16.3-4463-4d3becdfd9
* **Python:** 3.9.6
* **Platform:** linux-manjaro21-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment] 2021-09-28 14:59
See #25695

**Comment by haampie** [comment] 2021-09-28 15:21
Duplicate of #20340

**Comment by alalazo** [comment] 2023-04-06 11:55
We deprecated the "best-effort" behavior on spec matrices, since it was not "well defined" and removed any mention of this behavior from the docs in v0.19. Right now here's what we suggest https://spack.readthedocs.io/en/latest/environments.html#speclists-as-constraints

**Closed as not planned by alalazo** 2023-04-06 11:55 UTC
Labels: bug, triage
