### ISSUE TITLE
`spack install --fake` does not fake the installation, package is installed

### ISSUE THREAD

**Issue by npf** [LLNL/spack#29297] opened 2022-03-02 17:38 UTC
### Steps to reproduce

```
spack (develop=)$ spack find
==> 0 installed packages
spack (develop=)$ spack install --fake xz
==> Installing xz-5.2.5-dsqz36wmpns2qctp7udbgg56sm2psmza
==> No binary for xz-5.2.5-dsqz36wmpns2qctp7udbgg56sm2psmza found: installing from source
==> xz: Successfully installed xz-5.2.5-dsqz36wmpns2qctp7udbgg56sm2psmza
  Fetch: .  Build: 0.01s.  Total: 0.01s.
[+] /spack/opt/spack/linux-debian10-skylake/gcc-8.3.0/xz-5.2.5-dsqz36wmpns2qctp7udbgg56sm2psmza
spack (develop=)$ spack find
==> 1 installed package
-- linux-debian10-skylake / gcc@8.3.0 ---------------------------
xz@5.2.5
```

### Error message

The package is installed.

### Information on your system

* **Spack:** 0.17.1-1394-e6dcd382ee
* **Python:** 3.7.3
* **Platform:** linux-debian10-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2022-03-03 12:53
Confirmed this bug:
```console
$ spack install --fake zlib
[+] /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.3.0/zlib-1.2.11-ech7q6sqptumrsjdsvureubhkov2dm23

$ tree /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.3.0/zlib-1.2.11-ech7q6sqptumrsjdsvureubhkov2dm23
/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.3.0/zlib-1.2.11-ech7q6sqptumrsjdsvureubhkov2dm23
├── bin
│   └── zlib
├── include
│   └── zlib.h
├── lib
│   ├── libzlib.a
│   └── libzlib.so
└── man
    └── man1

5 directories, 4 files
```
Looking at what is in the tree is what confirms the bug, since `--fake` used to touch fake files in the same prefix.

**Comment by alalazo** [comment] 2022-03-03 12:59
Apologies for changing labels a couple of times, but I had to refresh my knowledge of this part of the code. What gets installed when you pass `--fake` are empty fake files. You can check that by:
```console
$ spack -v install --fake xz
==> Installing xz-5.2.5-essg37llwgq3a7bh6vkss3h6xwdbh4dr
==> No binary for xz-5.2.5-essg37llwgq3a7bh6vkss3h6xwdbh4dr found: installing from source
==> xz: Successfully installed xz-5.2.5-essg37llwgq3a7bh6vkss3h6xwdbh4dr
  Fetch: .  Build: 0.01s.  Total: 0.01s.
[+] /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.3.0/xz-5.2.5-essg37llwgq3a7bh6vkss3h6xwdbh4dr

$ tree /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.3.0/xz-5.2.5-essg37llwgq3a7bh6vkss3h6xwdbh4dr
/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.3.0/xz-5.2.5-essg37llwgq3a7bh6vkss3h6xwdbh4dr
├── bin
│   └── xz
├── include
│   └── xz.h
├── lib
│   ├── libxz.a
│   └── libxz.so
└── man
    └── man1

5 directories, 4 files

$ file /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.3.0/xz-5.2.5-essg37llwgq3a7bh6vkss3h6xwdbh4dr/bin/xz 
/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.3.0/xz-5.2.5-essg37llwgq3a7bh6vkss3h6xwdbh4dr/bin/xz: empty
```
This argument is mainly for developer, to create synthetic databases for integration tests or similar purposes. Closing the issue, but let me know if you still have questions.

**Closed as completed by alalazo** 2022-03-03 12:59 UTC
Labels: bug, not-a-bug

**Comment by rhd** [comment] 2022-05-23 23:22
@alalazo is there an easy way to detect and uninstall packages that were installed with the `--fake` flag?

**Comment by evili** [comment] 2022-06-23 10:33
The `"--fake`" flag should have also a confirmation warning like
"`The --fake flag is for debug purposes and it could leave your environment unusable. Are you sure? (y/N)`"
 because it's often misused as "`--dry-run`" equivalent and it is not.
