### ISSUE TITLE
`spack style`: mypy checks files belonging to system python

### ISSUE THREAD

**Issue by iarspider** [LLNL/spack#33194] opened 2022-10-11 11:45 UTC
### Steps to reproduce

On a FC36 machine with mypy 0.982 installed under `/home/user/.local/bin`:
```
$ spack style
<...>
lib/spack/spack/cmd/style.py:247 ==> [2022-10-11-13:44:33.906931] Running mypy checks
lib/spack/spack/util/executable.py:197 ==> [2022-10-11-13:44:33.907313] '/home/razumov/.local/bin/mypy' '--config-file' '/home/razumov/my_spack/pyproject.toml' '--show-error-codes' '--package' 'spack' '--package' 'llnl'
../../../usr/lib64/python3.10/site-packages/numpy/__init__.pyi:642: error: Positional-only parameters are only supported in Python 3.8 and greater  [syntax]
Found 1 error in 1 file (errors prevented further checking)
  mypy found errors
```

### Error message

```console
$ spack -d --stacktrace style
lib/spack/spack/cmd/__init__.py:124 ==> [2022-10-11-13:44:33.430430] Imported style from built-in commands
lib/spack/spack/cmd/__init__.py:124 ==> [2022-10-11-13:44:33.431222] Imported style from built-in commands
lib/spack/spack/util/executable.py:197 ==> [2022-10-11-13:44:33.432170] '/usr/bin/git' 'rev-parse' '--quiet' '--verify' '--revs-only' 'develop'
lib/spack/spack/util/executable.py:197 ==> [2022-10-11-13:44:33.434302] '/usr/bin/git' 'diff' '--name-only' '--diff-filter=ACMR' '8e3c088a7ad587b2f028a1fabea67a331ef96847...'
lib/spack/spack/util/executable.py:197 ==> [2022-10-11-13:44:33.439366] '/usr/bin/git' 'diff' '--name-only' '--diff-filter=ACMR' '--cached'
lib/spack/spack/util/executable.py:197 ==> [2022-10-11-13:44:33.445087] '/usr/bin/git' 'diff' '--name-only' '--diff-filter=ACMR'
lib/spack/spack/util/executable.py:197 ==> [2022-10-11-13:44:33.460131] '/usr/bin/git' 'ls-files' '--exclude-standard' '--other'
lib/spack/spack/cmd/style.py:234 ==> [2022-10-11-13:44:33.624240] Running style checks on spack
  selected: isort, mypy, black, flake8
lib/spack/spack/cmd/style.py:241 ==> [2022-10-11-13:44:33.624456] Modified files
  var/spack/repos/builtin/packages/py-frozenlist/package.py
lib/spack/spack/config.py:1010 ==> [2022-10-11-13:44:33.627441] Reading config from file /home/razumov/my_spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.633020] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/defaults/linux/bootstrap.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.633276] Skipping nonexistent config path /etc/spack/bootstrap.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.633489] Skipping nonexistent config path /etc/spack/linux/bootstrap.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.633686] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/bootstrap.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.633892] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/linux/bootstrap.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.634109] Skipping nonexistent config path /home/razumov/.spack/bootstrap.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.634320] Skipping nonexistent config path /home/razumov/.spack/linux/bootstrap.yaml
lib/spack/spack/config.py:1010 ==> [2022-10-11-13:44:33.635184] Reading config from file /home/razumov/my_spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.648487] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/defaults/linux/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.648722] Skipping nonexistent config path /etc/spack/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.648922] Skipping nonexistent config path /etc/spack/linux/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.649142] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.649342] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/linux/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.649537] Skipping nonexistent config path /home/razumov/.spack/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.649722] Skipping nonexistent config path /home/razumov/.spack/linux/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.654563] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/defaults/upstreams.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.654922] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/defaults/linux/upstreams.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.655135] Skipping nonexistent config path /etc/spack/upstreams.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.655376] Skipping nonexistent config path /etc/spack/linux/upstreams.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.655586] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/upstreams.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.655786] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/linux/upstreams.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.655975] Skipping nonexistent config path /home/razumov/.spack/upstreams.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.656146] Skipping nonexistent config path /home/razumov/.spack/linux/upstreams.yaml
lib/spack/spack/config.py:1010 ==> [2022-10-11-13:44:33.657215] Reading config from file /home/razumov/my_spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.672109] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/defaults/linux/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.672441] Skipping nonexistent config path /etc/spack/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.672687] Skipping nonexistent config path /etc/spack/linux/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.672951] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.673203] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/linux/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.673483] Skipping nonexistent config path /home/razumov/.spack/config.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.673718] Skipping nonexistent config path /home/razumov/.spack/linux/config.yaml
lib/spack/spack/database.py:389 ==> [2022-10-11-13:44:33.673982] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:395 ==> [2022-10-11-13:44:33.674195] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1010 ==> [2022-10-11-13:44:33.674734] Reading config from file /home/razumov/my_spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.679915] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/defaults/linux/bootstrap.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.680146] Skipping nonexistent config path /etc/spack/bootstrap.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.680379] Skipping nonexistent config path /etc/spack/linux/bootstrap.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.680613] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/bootstrap.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.680828] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/linux/bootstrap.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.681031] Skipping nonexistent config path /home/razumov/.spack/bootstrap.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.681215] Skipping nonexistent config path /home/razumov/.spack/linux/bootstrap.yaml
lib/spack/spack/database.py:389 ==> [2022-10-11-13:44:33.681448] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:395 ==> [2022-10-11-13:44:33.681591] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap.py:628 ==> [2022-10-11-13:44:33.681746] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/bootstrap.py:639 ==> [2022-10-11-13:44:33.682273] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/razumov/my_spack/etc/spack/defaults
lib/spack/spack/bootstrap.py:640 ==> [2022-10-11-13:44:33.682484] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/razumov/my_spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap.py:639 ==> [2022-10-11-13:44:33.682662] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/razumov/.spack/bootstrap/config
lib/spack/spack/bootstrap.py:640 ==> [2022-10-11-13:44:33.682799] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/razumov/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.683364] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/defaults/compilers.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.683555] Skipping nonexistent config path /home/razumov/my_spack/etc/spack/defaults/linux/compilers.yaml
lib/spack/spack/config.py:1000 ==> [2022-10-11-13:44:33.683739] Skipping nonexistent config path /home/razumov/.spack/bootstrap/config/compilers.yaml
lib/spack/spack/config.py:1010 ==> [2022-10-11-13:44:33.683933] Reading config from file /home/razumov/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap.py:767 ==> [2022-10-11-13:44:33.703443] [BOOTSTRAP ROOT SPEC] py-isort@4.3.5: %gcc target=x86_64
lib/spack/spack/bootstrap.py:767 ==> [2022-10-11-13:44:33.706524] [BOOTSTRAP ROOT SPEC] py-mypy@0.900: %gcc target=x86_64
lib/spack/spack/bootstrap.py:767 ==> [2022-10-11-13:44:33.709389] [BOOTSTRAP ROOT SPEC] py-black@:21 %gcc target=x86_64
lib/spack/spack/util/executable.py:197 ==> [2022-10-11-13:44:33.709810] '/home/razumov/.local/bin/black' '--version'
lib/spack/spack/bootstrap.py:767 ==> [2022-10-11-13:44:33.825537] [BOOTSTRAP ROOT SPEC] py-flake8 %gcc target=x86_64
lib/spack/spack/cmd/style.py:247 ==> [2022-10-11-13:44:33.825847] Running isort checks
lib/spack/spack/util/executable.py:197 ==> [2022-10-11-13:44:33.826362] '/home/razumov/.local/bin/isort' '--rm' 'spack' '--rm' 'spack.pkgkit' '--rm' 'spack.package_defs' '-a' 'from spack.package import *' '--settings-path' '/home/razumov/my_spack/pyproject.toml' '--check' '--diff' 'var/spack/repos/builtin/packages/py-frozenlist/package.py'
  isort checks were clean
lib/spack/spack/cmd/style.py:247 ==> [2022-10-11-13:44:33.906931] Running mypy checks
lib/spack/spack/util/executable.py:197 ==> [2022-10-11-13:44:33.907313] '/home/razumov/.local/bin/mypy' '--config-file' '/home/razumov/my_spack/pyproject.toml' '--show-error-codes' '--package' 'spack' '--package' 'llnl'
../../../usr/lib64/python3.10/site-packages/numpy/__init__.pyi:642: error: Positional-only parameters are only supported in Python 3.8 and greater  [syntax]
Found 1 error in 1 file (errors prevented further checking)
  mypy found errors
lib/spack/spack/cmd/style.py:247 ==> [2022-10-11-13:44:36.359503] Running black checks
lib/spack/spack/util/executable.py:197 ==> [2022-10-11-13:44:36.359909] '/home/razumov/.local/bin/black' '--config' '/home/razumov/my_spack/pyproject.toml' '--check' '--diff' '--color' 'var/spack/repos/builtin/packages/py-frozenlist/package.py'
All done! ✨ 🍰 ✨
1 file would be left unchanged.
  black checks were clean
lib/spack/spack/cmd/style.py:247 ==> [2022-10-11-13:44:36.507444] Running flake8 checks
lib/spack/spack/util/executable.py:197 ==> [2022-10-11-13:44:36.507744] '/home/razumov/.local/bin/flake8' '--config=/home/razumov/my_spack/.flake8' 'var/spack/repos/builtin/packages/py-frozenlist/package.py'
  flake8 checks were clean
lib/spack/spack/cmd/style.py:463 ==> [2022-10-11-13:44:36.633625] Error: spack style found errors
```

### Information on your system

* **Spack:** 0.19.0.dev0 (73575eadde00573e6813633dd090041bee08c687)
* **Python:** 3.10.7
* **Platform:** linux-fedora36-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2023-07-07 10:34
Duplicate of #38704

**Closed as not planned** 2023-07-07 10:35 UTC
Labels: bug, triage
