### ISSUE TITLE
UnicodeDecodeError with MakefilePackage when using python 3.6.0

### ISSUE THREAD

**Issue by krafczyk** [LLNL/spack#3693] opened 2017-04-04 19:16 UTC
Checkout the current develop, and install astyle with python 3.6.0. I get the following:

```
python bin/spack install astyle
==> Installing astyle
==> Fetching http://downloads.sourceforge.net/project/astyle/astyle/astyle%202.05.1/astyle_2.05.1_linux.tar.gz
######################################################################## 100.0%
==> Error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
/home/matthew/Software/NCSA/Vertical/spack/spack-dev/lib/spack/spack/package.py:955, in do_fetch:
     923      def do_fetch(self, mirror_only=False):
     924          """
     925          Creates a stage directory and downloads the tarball for this package.
     926          Working directory will be set to the stage directory.
     927          """
     928          if not self.spec.concrete:
     929              raise ValueError("Can only fetch concrete packages.")
     930  
     931          start_time = time.time()
     932          if spack.do_checksum and self.version not in self.versions:
     933              tty.warn("There is no checksum on file to fetch %s safely." %
     934                       self.spec.format('$_$@'))
     935  
     936              # Ask the user whether to skip the checksum if we're
     937              # interactive, but just fail if non-interactive.
     938              ck_msg = "Add a checksum or use --no-checksum to skip this check."
     939              ignore_checksum = False
     940              if sys.stdout.isatty():
     941                  ignore_checksum = tty.get_yes_or_no("  Fetch anyway?",
     942                                                      default=False)
     943                  if ignore_checksum:
     944                      tty.msg("Fetching with no checksum.", ck_msg)
     945  
     946              if not ignore_checksum:
     947                  raise FetchError("Will not fetch %s" %
     948                                   self.spec.format('$_$@'), ck_msg)
     949  
     950          self.stage.fetch(mirror_only)
     951  
     952          self._fetch_time = time.time() - start_time
     953  
     954          if spack.do_checksum and self.version in self.versions:
  >> 955              self.stage.check()
     956  
     957          self.stage.cache_local()
```

**Comment by krafczyk** [comment] 2017-04-04 19:17
Python 2.7 works just fine.

**Comment by adamjstewart** [comment] 2017-04-04 19:18
Duplicate of #3655.

**Closed by adamjstewart** 2017-04-04 19:18 UTC
Labels: bug, python3
