### ISSUE TITLE
`concretizer:unify:when_possible` prefers locally concretized version a bit too much

### ISSUE THREAD

**Issue by Paul-Ferrell** [LLNL/spack#30961] opened 2022-06-02 12:34 UTC
### Steps to reproduce

An environment includes two packages, A and C. A depends on B which depends on C. When using `concretizer:unify:when_possible`, Spack will use the locally concretized spec for C even if a perfectly reasonable C exists upstream. Even worse, this will cause Spack to use a locally concretized B even if that exists upstream.

I'm not sure this is a bug or the expected behavior, but it's definitely not the behavior I would want.

## Reproducer
Clone two spack repos - spack_up and spack
In spack_up:

- `spack install libmd@1.0.2`

In spack:

- Set spack_up as an upstream
- Create and activate an environment
- `spack add expat`
- `spack add libmd@1.0.4`
- `spack concretize -f`
- `spack -c concretizer:unify:when_possible concretize -f`

### Error message

No error message.

### Information on your system

* **Spack:** 0.19.0.dev0 (dac5fec255f95b8b546899db707337ac2d907e1d)
* **Python:** 3.6.8
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by Paul-Ferrell** [comment] 2022-06-02 12:53
```
$ spack -c concretizer:unify:when_possible concretize -f
==> Concretized expat
 -   ow5r4q5  expat@2.4.8%gcc@4.8.5+libbsd arch=linux-rhel7-haswell
 -   asj54sh      ^libbsd@0.11.5%gcc@4.8.5 arch=linux-rhel7-haswell
[+]  7gftr2n          ^libmd@1.0.4%gcc@4.8.5 arch=linux-rhel7-haswell

==> Concretized libmd@1.0.4
[+]  7gftr2n  libmd@1.0.4%gcc@4.8.5 arch=linux-rhel7-haswell

==> Updating view at /tmp/pflarr/when_possible/spack/var/spack/environments/bar/.spack-env/view
fg-rfe1:spack $ spack concretize -f
==> Starting concretization pool with 2 processes
==> Environment concretized in 0.61 seconds.
==> Concretized expat
 -   4tc2q53  expat@2.4.8%gcc@4.8.5+libbsd arch=linux-rhel7-haswell
[^]  tn3kui4      ^libbsd@0.11.5%gcc@4.8.5 arch=linux-rhel7-haswell
[^]  3jzynwe          ^libmd@1.0.2%gcc@4.8.5 arch=linux-rhel7-haswell

==> Concretized libmd@1.0.4
[+]  7gftr2n  libmd@1.0.4%gcc@4.8.5 arch=linux-rhel7-haswell
```

**Comment by becker33** [comment] 2022-06-02 12:59
Closing this issue -- this is intended behavior.

**Closed as completed by becker33** 2022-06-02 12:59 UTC
Labels: bug, triage
