### ISSUE TITLE
spack style: mypy checks installed environment packages

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#38704] opened 2023-07-04 02:46 UTC
### Steps to reproduce

1. Create a managed environment with a view and some python sources, and install it
2. Run `spack style -t mypy`

### Error message

An example on my system:
```console
> spack style -t mypy                                                                                                                                                                                    17.5s
==> Running style checks on spack
  selected: mypy
==> Modified files
...
==> Running mypy checks
var/spack/environments/system/.spack-env/view/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2346: error: Positional-only parameters are only supported in Python 3.8 and greater  [syntax]
Found 1 error in 1 file (errors prevented further checking)
  mypy found errors
==> Error: spack style found errors
```

### Information on your system

* **Spack:** 0.21.0.dev0 (11bc27d984a1008f254abf6690c2d96c418b0c42)
* **Python:** 3.10.10
* **Platform:** darwin-ventura-m2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment] 2023-07-04 03:22
Unfortunately mypy fails on the first error it finds, so this prevents me from using `spack style -t mypy` at all.

**Comment by alalazo** [comment] 2023-07-05 12:50
Cannot reproduce on:

* **Spack:** 0.21.0.dev0 (12427c6974c644ca6c45ffd62207dbec32625e79)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

I created and environment, installed `py-ipython`, deactivate, re-activate and:
```console
$ which ipython
/tmp/spack-tvf58psy/.spack-env/view/bin/ipython
$ spack style -t mypy
==> Running style checks on spack
  selected: mypy
==> Modified files
==> Running mypy checks
Success: no issues found in 577 source files
```

**Comment by adamjstewart** [comment] 2023-07-06 01:31
Your environment isn't within Spack's source tree like mine is.

**Comment by alalazo** [comment] 2023-07-06 16:00
I can't reproduce even with a named environment. Did like before, just used:
```console
$ spack create test
```
to have a managed environment:

![Screenshot from 2023-07-06 18-00-13](https://github.com/spack/spack/assets/4199709/84370540-ae8b-4c78-aa90-8397eb0e43ef)

**Comment by adamjstewart** [comment] 2023-07-06 16:02
Not sure how to reproduce then. Any tips for debugging? I'm still able to reproduce the issue locally.

**Comment by alalazo** [comment] 2023-07-06 16:06
The difference is very likely in the computation of `changed_files` on our platforms:

https://github.com/spack/spack/blob/a13687f022dfc411cb1005c29de66980e25e8b7b/lib/spack/spack/cmd/style.py#L100-L118

I think environments managed by Spack should be excluded because of the `--exclude-standard` option and the:
```
/var/spack/environments
```
entry in `.gitignore`.

**Comment by alalazo** [comment] 2023-07-06 16:07
Did you stage or commit the files?

**Comment by adamjstewart** [comment] 2023-07-06 16:38
I don't think so.

**Comment by tgamblin** [comment] 2023-07-07 06:38
You're seeing this issue: https://github.com/python/mypy/issues/14373, which we first encountered with `numpy` in #38704.  It's not that we scan everything in the Spack tree (far from it).  It's that you have `IPython` installed and you're running Spack from its own python.  `mypy` will check *every* reachable import from your package.  `spack python` can optionally run `IPython`.

The only way to avoid this is to explicitly tell `mypy` what not to check, so I added `IPython` and a number of other of our external imports to the override list.  This also seems to knock 6 seconds or so off the `mypy` scan, so hopefully it decreases turnaround time for `spack style` too.

Should be fixed by https://github.com/spack/spack/pull/38769

**Closed as completed** 2023-07-11 11:30 UTC
Labels: bug, impact-low
