### ISSUE TITLE
Installation issue: failed to install zlib on centos 7.5

### ISSUE THREAD

**Issue by binbinao** [LLNL/spack#27818] opened 2021-12-06 06:42 UTC
### Steps to reproduce the issue

```consoles
pack install zlib
```

### Information on your system

==> Bootstrapping clingo from pre-built binaries
==> Bootstrapping clingo from sources
==> Error: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %gcc target=x86_64" due to the following failures:
    'spack-install' raised ConflictsInSpecError: Conflicts in concretized spec "clingo-bootstrap@spack%gcc@4.8.5~docs~ipo+python~static_libstdcpp build_type=Release arch=linux-centos7-x86_64/6hb2rkn"

    List of matching conflicts for spec:

    clingo-bootstrap@spack%gcc@4.8.5~docs~ipo+python~static_libstdcpp build_type=Release arch=linux-centos7-x86_64
        ^bison@3.0.4%gcc@4.8.5 patches=b72914fe38e54a6fc25f29019e0a0786705c4f61ce20d414cc2010c8d62448c7 arch=linux-centos7-x86_64
        ^cmake@3.21.4%gcc@4.8.5~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-centos7-x86_64
            ^ncurses@6.2%gcc@4.8.5~symlinks+termlib abi=none arch=linux-centos7-x86_64
                ^pkgconf@1.8.0%gcc@4.8.5 arch=linux-centos7-x86_64
            ^openssl@1.1.1l%gcc@4.8.5~docs certs=system arch=linux-centos7-x86_64
                ^perl@5.34.0%gcc@4.8.5+cpanm+shared+threads arch=linux-centos7-x86_64
                    ^berkeley-db@18.1.40%gcc@4.8.5+cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-centos7-x86_64
                    ^bzip2@1.0.8%gcc@4.8.5~debug~pic+shared arch=linux-centos7-x86_64
                        ^diffutils@3.8%gcc@4.8.5 arch=linux-centos7-x86_64
                            ^libiconv@1.16%gcc@4.8.5 libs=shared,static arch=linux-centos7-x86_64
                    ^gdbm@1.19%gcc@4.8.5 arch=linux-centos7-x86_64
                        ^readline@8.1%gcc@4.8.5 arch=linux-centos7-x86_64
                    ^zlib@1.2.11%gcc@4.8.5+optimize+pic+shared arch=linux-centos7-x86_64
        ^python@3.6%gcc@4.8.5+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-centos7-x86_64
        ^re2c@2.2%gcc@4.8.5 arch=linux-centos7-x86_64

1. "%gcc@:5" conflicts with "clingo-bootstrap" [C++14 support is required to bootstrap clingo]

    Please run `spack -d spec zlib` for more verbose error messages

### Additional information

Nothing

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment] 2021-12-06 17:03
Can you please report the information from `spack debug report` for the failing Spack instance?

**Comment by mwkrentel** [comment] 2021-12-06 17:19
I think the real issue is why did the binary bootstrap for clingo fail.
It seems to complain about the configuration/spec for patchelf but I don't know.
For me, this fails:

```
$ spack  solve  zlib
==> Bootstrapping clingo from pre-built binaries
==> buildcache spec(s) matching /vcipwnf57slgoo7busvvkzjkk7vydeb5 

==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.1/build_cache/linux-rhel5-x86_64/gcc-9.3.0/clingo-bootstrap-spack/linux-rhel5-x86_64-gcc-9.3.0-clingo-bootstrap-spack-vcipwnf57slgoo7busvvkzjkk7vydeb5.spack
==> Installing buildcache for spec clingo-bootstrap@spack%gcc@9.3.0~docs~ipo+python build_type=Release arch=linux-rhel5-x86_64
==> Bootstrapping patchelf from pre-built binaries
==> Error: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %gcc target=x86_64" due to the following failures:
    'github-actions' raised RuntimeError: cannot bootstrap any of the patchelf executables from spec "patchelf@0.13.1:0.13.99 %gcc target=x86_64"
    Please run `spack -d spec zlib` for more verbose error messages
```

$ spack debug report
* **Spack:** 0.17.0-413-235edd0
* **Python:** 3.6.8
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo

**Comment by mwkrentel** [comment] 2021-12-06 22:49
I discussed this with @alalazo on slack.  In my case, the problem was
that although clingo has a binary bootstrap, patchelf has no binary
and must be built with source (but it's small).  I had turned off
source bootstraps (spack-install) and I didn't realize that blocked
both clingo and patchelf source builds, so it failed.

@binbinao Check that your `bootstrap.yaml` file allows source and binary
installs.  You'll need both source (spack-install) for patchelf
because binary doesn't exist (not yet) and binary (github-actions) for
clingo to avoid C++14.

```
bootstrap:
  ...
  trusted:
    github-actions: true
    spack-install:  true
```

**Comment by haampie** [comment] 2021-12-14 14:37
@binbinao is this still an issue?

**Comment by alalazo** [comment] 2021-12-16 15:22
From what @binbinao reported it seems there are issues retrieving binaries from our public mirror, but I couldn't reproduce them anywhere. Having bootstrap from source failing instead is expected since `clingo` requires C++14. Closing for the time being, but feel free to reopen if you have a reproducer.

**Closed as completed by alalazo** 2021-12-16 15:22 UTC
Labels: bug, unreproducible, bootstrap
