### ISSUE TITLE
Checksum Error: libaio

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#4388] opened 2017-05-29 21:53 UTC
```bash
$ spack install libaio
==> Installing libaio
==> Already downloaded .../spack/var/spack/stage/libaio-0.3.110-1-x73kmwi7rzgszlgz2xngvtxlo3sa7swj/libaio-0.3.110-1.tar.gz
==> Error: ChecksumError: md5 checksum failed for .../spack/var/spack/stage/libaio-0.3.110-1-x73kmwi7rzgszlgz2xngvtxlo3sa7swj/libaio-0.3.110-1.tar.gz
    Expected eb6b1b435afadb5b80c5dd80984249f6 but got f7408735589b6365d089ee3cc69abd83
```

**Comment by adamjstewart** [comment] 2017-05-29 22:03
If you clear your repository and try fetching again, you'll get even more useful output:
```
$ spack fetch libaio
==> Fetching https://git.fedorahosted.org/cgit/libaio.git/snapshot/libaio-0.3.110-1.tar.gz
######################################################################## 100.0%
==> Warning: The contents of 
  the archive
   look like HTML.
  The checksum will likely be bad.  If it is, you can use
  'spack clean <package>' to remove the bad archive, then
  fix your internet gateway issue and install again.
==> Error: md5 checksum failed for /Users/Adam/spack/var/spack/stage/libaio-0.3.110-1-t7nbakuufbh5t7crtcr7dymp2z3u4bch/libaio-0.3.110-1.tar.gz
Expected eb6b1b435afadb5b80c5dd80984249f6 but got b20e0403f8054796a1c474e146b146c4
```
The checksum didn't change, the package is just no longer available for download. If you go to the project homepage: https://git.fedorahosted.org/cgit/libaio.git

> fedorahosted.org was retired on March 1st, 2017. If you are viewing this page, odds are it's after that date and you have been redirected here by attempting to go to some project on fedorahosted.org. If you are a user of a project formerly hosted at fedorahosted.org, please search for the new home the project you are interested in likely has. If you are a maintainer of a project formerly hosted at fedorahosted.org and need your data to migrate, see below.

Duplicate of #3851 which first reported this problem. If you can find a new download URL, feel free to fix this.

**Closed** 2017-05-30 11:56 UTC
Labels: duplicate, fetching
