### ISSUE TITLE
Problem with new concretizer and package version constraints

### ISSUE THREAD

**Issue by albestro** [LLNL/spack#24878] opened 2021-07-14 13:04 UTC
The new concretizer complains that a newer version of a package does not satisfy a right-open range constraint.

### Steps to reproduce the issue
In our (currently not release yet) spack package for `dla-future` we define a dependency with HPX 1.6.0 or earlier versions with the line

`depends_on("hpx@1.6.0:")`

HPX (at the moment of writing) is 1.6.0, but soon the 1.7.0 will be released. Here it is what the current package provides in terms of versions.

```yaml
    version('master', git='https://github.com/STEllAR-GROUP/hpx.git', branch='master')
    version('stable', git='https://github.com/STEllAR-GROUP/hpx.git', tag='stable')
    version('1.6.0', sha256='4ab715613c1e1808edc93451781cc9bc98feec4e422ccd4322858a680f6d9017')
    version('1.5.1', sha256='b2f9358ce2a9446b9d8fb1998c30913e7199b007aa82e46d0aa05c763331c635')
    version('1.5.0', sha256='de2901d8ae017592c513e0af9cf58de295abc9802e55ece00424cbd8a3801920')
    version('1.4.1', sha256='965dabe44d17480e326d92da4eec56722d98b33943c53d2b0f8f4655cb208023')
    version('1.4.0', sha256='241a1c47fafba751848fac12446e7bf4ad3d342d5eb2fa1ef94dd904acc329ed')
    version('1.3.0', sha256='cd34da674064c4cc4a331402edbd65c5a1f8058fb46003314ca18fa08423c5ad')
    version('1.2.1', sha256='8cba9b48e919035176d3b7bbfc2c110df6f07803256626f1dad8d9dde16ab77a')
    version('1.2.0', sha256='20942314bd90064d9775f63b0e58a8ea146af5260a4c84d0854f9f968077c170')
    version('1.1.0', sha256='1f28bbe58d8f0da600d60c3a74a644d75ac777b20a018a5c1c6030a470e8a1c9')
```

In order to be able to test and debug my packages with the next release, I cloned the HPX repository, checked out the tag `1.7.0-rc2` with the release candidate code, and then I configured a spack environment saying that hpx package is a develop package, for which I have the code locally in my repo, and for which the spec has the newer version (as it is for real).

```yaml
spack:
  specs: [dla-future build_type=Debug]
  concretization: together
  view: true
  repos:
  - ~/workspace/repos/dla-future/spack
  develop:
    hpx:
      path: /Users/ialberto/workspace/libraries/hpx-1.7.0-rc2
      spec: hpx@1.7.0
```

### Error Message
Unfortunately, when I try to concretize this environment, I get an error from the new concretizer

```console
spack -d -e prova concretize -f
...
==> [2021-07-14-14:50:19.708392, 28451] UnsatisfiableVersionSpecError: 1.6.0 does not satisfy 1.7.0
==> [2021-07-14-14:50:19.708428, 28451] Error: 1.6.0 does not satisfy 1.7.0
Traceback (most recent call last):
  File "/Users/ialberto/spack/lib/spack/spack/main.py", line 774, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/ialberto/spack/lib/spack/spack/main.py", line 502, in _invoke_command
    return_val = command(parser, args)
  File "/Users/ialberto/spack/lib/spack/spack/cmd/concretize.py", line 36, in concretize
    concretized_specs = env.concretize(force=args.force, tests=tests)
  File "/Users/ialberto/spack/lib/spack/spack/environment.py", line 1209, in concretize
    return self._concretize_together(tests=tests)
  File "/Users/ialberto/spack/lib/spack/spack/environment.py", line 1248, in _concretize_together
    concrete_specs = spack.concretize.concretize_specs_together(
  File "/Users/ialberto/spack/lib/spack/spack/concretize.py", line 727, in concretize_specs_together
    return _concretize_specs_together_new(*abstract_specs, **kwargs)
  File "/Users/ialberto/spack/lib/spack/spack/concretize.py", line 732, in _concretize_specs_together_new
    result = spack.solver.asp.solve(abstract_specs)
  File "/Users/ialberto/spack/lib/spack/spack/solver/asp.py", line 1686, in solve
    return driver.solve(setup, specs, dump, models, timers, stats, tests)
  File "/Users/ialberto/spack/lib/spack/spack/solver/asp.py", line 381, in solve
    answers = builder.build_specs(tuples)
  File "/Users/ialberto/spack/lib/spack/spack/solver/asp.py", line 1636, in build_specs
    _develop_specs_from_env(s, env)
  File "/Users/ialberto/spack/lib/spack/spack/solver/asp.py", line 1660, in _develop_specs_from_env
    spec.constrain(dev_info['spec'])
  File "/Users/ialberto/spack/lib/spack/spack/spec.py", line 3065, in constrain
    raise UnsatisfiableVersionSpecError(self.versions, other.versions)
spack.spec.UnsatisfiableVersionSpecError: 1.6.0 does not satisfy 1.7.0
```

### Information on your system

* **Spack:** 0.16.2-3524-b37bf93aa2
* **Python:** 3.8.5
* **Platform:** darwin-mojave-skylake
* **Concretizer:** clingo

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment] 2021-07-19 14:17
Things are a quite inconsistent here...

Given the existing versions 1.2.8 and 1.2.11 of zlib and the non-existing version 1.3.0, this is the behavior more or less:

---

```yaml
spack:
  specs: [zlib@1.2.11]
  develop:
    zlib:
      spec: zlib@1.2.8
```

**Clingo**: Errors when collecting facts before concretization
**Original**: Errors during concretization

(it tries to add the constraint `@1.2.8` on top of `zlib@1.2.11`, which fails)

---

```yaml
spack:
  specs: [zlib]
  develop:
    zlib:
      spec: zlib@1.3.0
```

**Clingo**: `UnsatisfiableSpecError: zlib@1.3.0 dev_path=/tmp/tmp.Ua8r8vqDUt/zlib does not satisfy unknown` during concretization
**Original**: Concretizes to `zlib@1.3.0 dev_path=/tmp/tmp.Ua8r8vqDUt/zlib`, but issues a warning for a missing source id, which doesn't make sense for develop'ed packages...

---

```yaml
spack:
  specs: [zlib@1.3.0]
  develop:
    zlib:
      spec: zlib@1.3.0
```

**Clingo**: Concretizes to `zlib@1.3.0 dev_path=/tmp/tmp.Ua8r8vqDUt/zlib`, but issues a warning for a missing source id, which doesn't make sense for develop'ed packages...
**Original**: Concretizes to `zlib@1.3.0 dev_path=/tmp/tmp.Ua8r8vqDUt/zlib`, but issues a warning for a missing source id, which doesn't make sense for develop'ed packages...

**Comment by alalazo** [comment] 2021-12-21 12:37
Behavior number 3 is fixed in both `develop` and v0.17.0 The other two inconsistent behaviors are still there.

**Comment by alalazo** [comment] 2023-07-10 20:03
Cannot reproduce the original issue on:

* **Spack:** 0.21.0.dev0 (64c6d63675f8e45e0be12a9c55acb4b7969e383a)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

with this diff:
```diff
diff --git a/var/spack/repos/builtin/packages/dla-future/package.py b/var/spack/repos/builtin/packages/dla-future/package.py
index c08736e85f..82e795a0c0 100644
--- a/var/spack/repos/builtin/packages/dla-future/package.py
+++ b/var/spack/repos/builtin/packages/dla-future/package.py
@@ -34,6 +34,7 @@ class DlaFuture(CMakePackage, CudaPackage, ROCmPackage):
     depends_on("umpire+rocm~shared", when="+rocm")
     depends_on("umpire@4.1.0:")
 
+    depends_on("hpx@1.9.0:")
     depends_on("pika@0.15.1:")
     depends_on("pika-algorithms@0.1:")
     depends_on("pika +mpi")
```
I get the following:

![Screenshot from 2023-07-10 22-02-05](https://github.com/spack/spack/assets/4199709/1d02a05d-b8d6-498c-a484-2ae86e2ea28f)

**Comment by alalazo** [comment] 2023-07-10 20:06
These cases seems to be consistent now https://github.com/spack/spack/issues/24878#issuecomment-882586358

This:
```yaml
spack:
  specs: [zlib@1.2.13]
  develop:
    zlib:
      spec: zlib@=1.3.0
```
errors out with:
```console
==> Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "zlib"
   2. Cannot satisfy 'zlib@=1.3.0'
   3. Cannot satisfy 'zlib@1.2.13'

```

This instead:
```yaml
spack:
  specs: [zlib]
  develop:
    zlib:
      spec: zlib@=1.3.0
```
concretizes correctly.

**Closed as completed** 2023-07-10 20:06 UTC
Labels: bug, concretization, concretizer-use-case
