### ISSUE TITLE
[bug] Editor invocation from spack broken

### ISSUE THREAD

**Issue by planetA** [LLNL/spack#371] opened 2016-01-18 10:14 UTC
When I execute any spack command, which starts an editor, I do not see the editor output. I still can type the commands, but it looks like nothing is happening, until I close the editor.

I did git bisect and found out that the bug was in this commit: 099fa1df34a157a323aa023b69c52399a441b81b

If revert the changes to the file executable.py, the bug goes away:

git checkout 099fa1df34a157a323aa023b69c52399a441b81b^ -- lib/spack/spack/util/executable.py

**Comment by adamjstewart** [comment] 2016-01-18 16:06
I am seeing this problem as well. Something as simple as `spack edit gcc` can be used to reproduce this issue.

**Comment by tgamblin** [comment] 2016-01-19 09:19
Should be fixed by cee7bfa -- reopen if not.  @scheibelp: It looks like the pipe redirection in 099fa1d isn't getting along with editors.  Will the change in cee7bfa work with xunit?

**Closed by tgamblin** 2016-01-19 09:19 UTC

**Comment by scheibelp** [comment] 2016-01-19 18:58
This runs fine (as in I can run the tests and open an editor) - thanks! 

Potential issue: as of now any unit test which uses Executable.__call__ without return_output=True will cause a failure in the test framework. As it happens every unit test does this but I can imagine someone writing one and not setting return_output (default is false).

It could be less fragile if I add a PR to detect whether stdout has a .fileno attribute. Does that sound worthwhile?

**Comment by tgamblin** [comment] 2016-01-21 10:19
@scheibelp: I think that sounds like a useful thing, but maybe not top priority right now -- can you make an issue for it so we don't forget?
