### ISSUE TITLE
Installation issue: py-docutils (symlink error)

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#32769] opened 2022-09-22 19:40 UTC
### Steps to reproduce the issue

```console
$ spack install py-docutils
```

### Error message

```
==> Error: FileNotFoundError: [Errno 2] No such file or directory: '/projects/spack/opt/spack/linux-ubuntu22.04-sandybridge/gcc-11.2.0/py-docutils-0.18.1-cwwxkd7vth6lvylkfm4hyow75rv7ib5i/bin'

/projects/spack/var/spack/repos/builtin/packages/py-docutils/package.py:42, in post_install:
         40    def post_install(self):
         41        bin_path = self.prefix.bin
  >>     42        for file in os.listdir(bin_path):
         43            if file.endswith(".py"):
         44                os.symlink(os.path.join(bin_path, file), os.path.join(bin_path, file[:-3]))
```

### Information on your system

* **Spack:** 0.19.0.dev0 (123354e920582607af689db83037c1055e4ff778)
* **Python:** 3.10.4
* **Platform:** linux-ubuntu22.04-sandybridge
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment] 2022-09-22 20:44
See #31939. Quickest fix is to just let Spack build Python. The system Python on most distros is broken.

**Comment by adamjstewart** [comment] 2023-05-12 15:22
Closing as a duplicate of #32662

**Closed as completed by adamjstewart** 2023-05-12 15:22 UTC
Labels: build-error
