### ISSUE TITLE
Random failures in Travis CI

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2353] opened 2016-11-16 17:38 UTC
I've been noticing a lot of seemingly random failures in Travis lately. This Issue is an attempt to gather them all in one place and see if there is a pattern.

PR | Travis Build | Problem
--- | --- | ---
#2201 | can't find? | timeout?
#2285 | can't find? | unknown
#2299 | https://travis-ci.org/LLNL/spack/builds/174884110 | test_svn_mirror, test_fetch_default, test_fetch_r1
#2312 | https://travis-ci.org/LLNL/spack/builds/175156530 | timeout
#2351 | https://travis-ci.org/LLNL/spack/jobs/176425363 | test_all_mirror, test_svn_mirror, test_fetch_default, test_fetch_r1
#2343 | https://travis-ci.org/LLNL/spack/builds/176773337 | timeout
#2426 | https://travis-ci.org/LLNL/spack/builds/179464372 | timeout
#2511 | https://travis-ci.org/LLNL/spack/jobs/182086916 | test_all_mirror, test_svn_mirror, test_fetch_default, test_fetch_r1
#2559 | https://travis-ci.org/LLNL/spack/jobs/183188968 | never ran?
#2564 | https://travis-ci.org/LLNL/spack/jobs/183246648 | timeout
#2823 | https://travis-ci.org/LLNL/spack/jobs/191670901 | failed to clone spack on macOS
#2831 | https://travis-ci.org/LLNL/spack/jobs/191807465 | failed to pip install coveralls
#2886 | https://travis-ci.org/LLNL/spack/jobs/193570385 | brew failed to fetch gcc
#2897 | https://travis-ci.org/LLNL/spack/jobs/193920459 | apt-get failed to connect to ubuntu repos
#2952 | https://travis-ci.org/LLNL/spack/jobs/196159879 | build_system_guess, python != generic
#4020 | https://travis-ci.org/LLNL/spack/jobs/226473984 | build_system_guess, python != generic
#4037 | https://travis-ci.org/LLNL/spack/jobs/226836329 | timeout
#4081 | https://travis-ci.org/LLNL/spack/jobs/227970329 | brew failed to fetch homebrew-cask
#4118 | already re-ran, python 2.7 unit tests | test_svn_mirror
#4165 | https://github.com/LLNL/spack/pull/4165#issuecomment-300121038 | build_system_guess, python != generic
#4169 | https://travis-ci.org/LLNL/spack/jobs/230391718 | pip crashed with internal error, seeing same problem in a dozen other PRs, fixed by #4180
#4234 | already re-ran, python 2.6 unit tests | BarrierTimeOut, some kind of lock waiting problem

@alalazo @tgamblin

**Comment by alalazo** [comment] 2016-11-16 17:48
Ok, they all seem to fail for `python@2.6` and `CYAML=false` on fetching apart from one that seems to be caused by a Travis timeout.

**Comment by adamjstewart** [comment] 2016-11-16 17:50
```
Error: Destination path '/home/travis/build/LLNL/spack/var/spack/stage/svn-test-svn-ulpoqqvv5odsylne5sqwf45a3etftxvr/spack-expanded-archive/spack-expanded-archive' already exists
```
is an interesting error message

**Comment by alalazo** [comment] 2016-11-16 18:02
#2201 seems just a flake8 issue, so that doesn't count here :smile: 

```console
var/spack/repos/builtin/packages/xsdktrilinos/package.py:48: [E501] line too long (88 > 79 characters)
```

**Comment by adamjstewart** [comment] 2016-11-16 18:03
@alalazo See https://github.com/LLNL/spack/pull/2201#issuecomment-257745780

**Comment by adamjstewart** [comment] 2016-11-16 18:04
I wish there was an easy way to search for PRs that have been closed and reopened...

**Comment by alalazo** [comment] 2016-11-28 16:38
It's really odd that every random failure we tracked appears on the row `python@2.6` and `CYAML=false`...

**Comment by becker33** [comment] 2017-08-07 23:23
Closing as outdated given the changes to the tests since then.

**Closed by becker33** 2017-08-07 23:23 UTC
Labels: tests

**Comment by adamjstewart** [comment] 2017-08-10 02:51
For the record, `build_system_guess, python != generic` still fails quite regularly (just failed today). But the biggest problem right now is our build tests keep hitting 50 minutes and timing out. Opened a new issue at #5049.

**Comment by alalazo** [comment] 2017-08-20 21:34
What are the most frequent fails? Spurious failures may happen when relying on the order of keys as we  iterate over a dictionary (see discussion in #5084 . It's worth to check-out if `python != generic` and other failures fall in this category.

**Comment by adamjstewart** [comment] 2017-08-20 22:26
Based on the table above, I would say `build_system_guess`, SVN tests, and "Homebrew/apt can't fetch/install dependencies" are the 3 most common failures. If it was something as simple as dictionary ordering, that would be great.
