### ISSUE TITLE
spack activate fails if dependencies are already activated

### ISSUE THREAD

**Issue by ilbiondo** [LLNL/spack#22932] opened 2021-04-12 14:17 UTC
When activating an extension (python or R) the activation fails if any of the dependencies are already activated. 

### Steps to reproduce the issue

```console
spack activate py-biopython
```

There's the same behaviour if one tries to activate an already activated package.

With an older Spack instance (0.13.3) this returns an informational message and the activation continues.

### Error Message

```console
$ spack find -dl py-biopython
==> 1 installed package
-- linux-rhel8-zen2 / gcc@9.3.0 ---------------------------------
sc7ad4r py-biopython@1.78
jfrf5qg     py-numpy@1.20.2
kuedzzc         openblas@0.3.14
5stjmys         py-setuptools@50.3.2
rqhqacx             python@3.8.8
tsmb67u                 bzip2@1.0.8
rjyzhae                 expat@2.2.10
bdtqx3b                     libbsd@0.10.0
6h6znzs                 gdbm@1.19
swnjpjl                     readline@8.0
o5uglmw                         ncurses@6.2
wgotc6p                 gettext@0.21
uc7nftf                     libiconv@1.16
kcss646                     libxml2@2.9.10
3zvzfm6                         xz@5.2.5
ejndmi5                         zlib@1.2.11
u5sz3r5                     tar@1.32
j2cbdcs                 libffi@3.3
2mbz6et                 openssl@1.1.1c
k27yovt                 sqlite@3.34.0
3yzxuey                 util-linux-uuid@2.36

$ spack -d activate py-biopython
==> [2021-04-12-16:10:28.338572] Imported activate from built-in commands
==> [2021-04-12-16:10:28.339290] Imported activate from built-in commands
==> [2021-04-12-16:10:28.341524] Reading config file /dcsrsoft/spack/hetre/v1.1/spack/etc/spack/defaults/config.yaml
==> [2021-04-12-16:10:28.364591] Reading config file /dcsrsoft/spack/hetre/v1.1/spack/etc/spack/config.yaml
==> [2021-04-12-16:10:28.368351] DATABASE LOCK TIMEOUT: 3s
==> [2021-04-12-16:10:28.368396] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-04-12-16:10:28.466561] Reading config file /dcsrsoft/spack/hetre/v1.1/spack/etc/spack/defaults/repos.yaml
==> [2021-04-12-16:10:28.469615] Reading config file /dcsrsoft/spack/hetre/v1.1/spack/etc/spack/repos.yaml
==> [2021-04-12-16:14:43.890409] Activating extension py-biopython@1.78%gcc@9.3.0 arch=linux-rhel8-zen2/sc7ad4r for python@3.8.8%gcc@9.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-rhel8-zen2/rqhqacx
==> [2021-04-12-16:14:43.895104] Activating extension py-numpy@1.20.2%gcc@9.3.0+blas+lapack patches=873745d7b547857fcfec9cae90b09c133b42a4f0c23b6c2d84cf37e2dd816604 arch=linux-rhel8-zen2/jfrf5qg for python@3.8.8%gcc@9.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-rhel8-zen2/rqhqacx
==> [2021-04-12-16:14:43.902956] ExtensionAlreadyInstalledError: py-numpy@1.20.2%gcc@9.3.0+blas+lapack patches=873745d7b547857fcfec9cae90b09c133b42a4f0c23b6c2d84cf37e2dd816604 arch=linux-rhel8-zen2/jfrf5qg is already installed in python@3.8.8%gcc@9.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-rhel8-zen2/rqhqacx
==> [2021-04-12-16:14:43.903007] Error: py-numpy@1.20.2%gcc@9.3.0+blas+lapack patches=873745d7b547857fcfec9cae90b09c133b42a4f0c23b6c2d84cf37e2dd816604 arch=linux-rhel8-zen2/jfrf5qg is already installed in python@3.8.8%gcc@9.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-rhel8-zen2/rqhqacx
Traceback (most recent call last):
  File "/dcsrsoft/spack/hetre/v1.1/spack/lib/spack/spack/main.py", line 768, in main
    return _invoke_command(command, parser, args, unknown)
  File "/dcsrsoft/spack/hetre/v1.1/spack/lib/spack/spack/main.py", line 496, in _invoke_command
    return_val = command(parser, args)
  File "/dcsrsoft/spack/hetre/v1.1/spack/lib/spack/spack/cmd/activate.py", line 51, in activate
    spec.package.do_activate(view, with_dependencies=not args.force)
  File "/dcsrsoft/spack/hetre/v1.1/spack/lib/spack/spack/package.py", line 2331, in do_activate
    verbose=verbose)
  File "/dcsrsoft/spack/hetre/v1.1/spack/lib/spack/spack/package.py", line 2323, in do_activate
    self.extendee_spec, self.spec)
  File "/dcsrsoft/spack/hetre/v1.1/spack/lib/spack/spack/directory_layout.py", line 434, in check_extension_conflict
    raise ExtensionAlreadyInstalledError(spec, ext_spec)
spack.directory_layout.ExtensionAlreadyInstalledError: py-numpy@1.20.2%gcc@9.3.0+blas+lapack patches=873745d7b547857fcfec9cae90b09c133b42a4f0c23b6c2d84cf37e2dd816604 arch=linux-rhel8-zen2/jfrf5qg is already installed in python@3.8.8%gcc@9.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-rhel8-zen2/rqhqacx

```

### Information on your system

$ spack debug report
* **Spack:** 0.16.1-1940-3d7069e039
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen2
* **Concretizer:** clingo

Maybe @alalazo would like to take a look?

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by cyrush** [comment] 2021-04-13 18:14
I hit this as well, i think it's fixed on develop but not sure how that feeds into 0.16.2:

https://github.com/spack/spack/issues/22530

**Comment by ilbiondo** [comment] 2021-04-26 16:00
The PR https://github.com/spack/spack/pull/22587 mentioned above fixes the issue - I have no idea why my search of open issues didn't find it...

**Comment by alalazo** [comment] 2021-04-28 13:20
Duplicate of #22530

**Comment by alalazo** [comment] 2021-04-28 13:21
I added both this issue and #22530 to the v0.16.2 project so that we'll backport the bugfix to the next minor release. Closing, but let me know if anything else needs to be done.

**Closed as completed by alalazo** 2021-04-28 13:21 UTC
Labels: bug, triage
