### ISSUE TITLE
hypre does not build on Darwin

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#521] opened 2016-03-09 20:10 UTC
hypre used to build fine on Darwin; it's now broken. There are many errors of the kind

```
ld: unknown option: -soname
collect2: error: ld returned 1 exit status
```

This looks as if hypre's support for shared libraries didn't work on Darwin.

We could make static libraries the default.

**Comment by alalazo** [comment] 2016-03-09 20:16
@eschnett I would say that until we have support for forwarding variants we should stick with the same defaults for all packages for `shared` (True), `debug` (False) and maybe `mpi` (True). This is just to avoid the inconvenience of remembering which is which when you install a package that has lots of dependencies.

**Comment by eschnett** [comment] 2016-03-09 20:16
Why is it a problem to build `hypre` with static libraries and `petsc` with shared libraries?

**Comment by tgamblin** [comment] 2016-03-09 20:21
Can the build be made to work?  Would the cmake build work properly on Darwin?  The package currently uses the autotools build.

**Comment by tgamblin** [comment] 2016-03-09 20:22
@rfalgout: do people here build Hypre on macs with shared libs?

**Comment by rfalgout** [comment] 2016-03-09 20:47
No clue.  We do some nightly regression testing on a Mac that @tzanio has, but it doesn’t look like it does a shared libs compile.  Which version of hypre has problems on Darwin and which one worked before?

**Comment by tzanio** [comment] 2016-03-09 21:05
I can confirm that the shared library build is broken on my Macs. We should probably replace `"-soname"` in `config/Makefile.config` with something like `"-dynamiclib -undefined dynamic_lookup -install_name "` in this case.

**Comment by eschnett** [comment] 2016-03-09 21:29
@rfalgout The hypre build fails, but Spack doesn't notice that it fails. You have to look at the error messages on the screen to notice the failure. See #505.

**Comment by citibeth** [comment] 2016-03-14 01:54
Without a solution to the problems of (a) building shared on Mac, or (b) getting Spack to recognize the build failure properly, I would suggest that hyper/package.py:
  1. Use ~shared by default, ONLY ON MAC.  This is temporary, until someone gets +shared working on Mac.
  2. Give an error if the user tries to set +shared on a Mac; since it doesn't know how to build that.

**Comment by tgamblin** [comment] 2016-03-15 18:32
I'm going to send the `hypre` guys a PR to get this working on mac.  I'll also add a patch to the `package.py` until they release a version with working mac shared libs.

**Comment by mathstuf** [comment] 2016-03-30 21:37
@tgamblin Any news on that hypre PR? Link?

**Comment by tgamblin** [comment] 2016-03-30 21:38
@mathstuf: Haven't had a chance to do it but am planning to do so -- feel free to take a stab if you want.

**Comment by mathstuf** [comment] 2016-03-31 17:51
Looking into it.

**Comment by eschnett** [comment] 2016-04-04 17:32
This is now working for me.

**Comment by tgamblin** [comment] 2016-04-04 17:51
@eschnett: it builds static by default now.  Do you want a dynamic build?

I was able to patch the build to use dynamic libs on OS X -- they use autotools w/o libtool so this is more complex than it probably needs to be, but [here is the WIP branch](https://github.com/LLNL/spack/tree/features/hypre-macosx-dylibs).  It builds dylibs but doesn't properly link example programs yet.

**Comment by citibeth** [comment] 2016-04-04 17:54
I haven't forgotten that I was tasked to come up with Spack style
guidelines.

I do believe that Spack packages should build shared by default.

**Comment by eschnett** [comment] 2016-04-04 19:47
I do not care about static vs. shared libraries.

I believe my Darwin changes included respective patches to make shared libraries work. They had a `.so` suffix, but since a suffix is only a convention that doesn't matter. I also have `install_name_tool` fixes for them.

**Comment by davydden** [comment] 2016-07-05 10:39
is this still an issue? Hypre builds fine for me on macOS.

**Comment by alalazo** [comment] 2017-01-10 13:11
@eschnett Closing this since there was no reply to @davydden since July, reopen if necessary.

**Closed by alalazo** 2017-01-10 13:11 UTC
Labels: build-error, macOS
