### ISSUE TITLE
`spack view` needs to merge `easy-install.pth` files

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#3245] opened 2017-02-27 04:42 UTC
Each Python package comes with its own `easy-install.pth` file. `spack view` links one (probably the first) into the destination directory, and ignores the others. Instead, it needs to merge (concatenate, and maybe then de-duplicate) these files.

**Comment by paulhopkins** [comment] 2017-02-27 13:48
I have some additions that does use the Python activate code to stitch the `easy-install.pth` file together correctly when creating views. I can work on creating a PR from it. However, since I wrote that I also had trouble with two Python packages that use a single namespace, and therefore must be installed as normal directories and not use the zip file + `easy-install.pth` approach. For these I modified the `python setup.py install` arguments to also include the `--single-version-externally-managed` argument (and also `--record=...`). This is how Python Pip works and I wonder whether Spack should be doing this by default as well. Does @tgamblin @adamjstewart or anybody else have any information on this?

**Comment by adamjstewart** [comment] 2017-02-27 13:53
> For these I modified the python setup.py install arguments to also include the `--single-version-externally-managed` argument... This is how Python Pip works and I wonder whether Spack should be doing this by default as well.

This may actually solve #1036. The problem we are seeing there is you can't use the same Python installation to run Spack that you are installing Python modules for. Whenever the Python dependency is the same as the Python running Spack, it crashes.

**Comment by citibeth** [comment] 2017-02-27 14:53
> However, since I wrote that I also had trouble with two Python packages that use a single namespace, and therefore must be installed as normal directories and not use the zip file + easy-install.pth approach.

Have you looked at the official Python guidelines on this issue?

**Comment by obreitwi** [comment] 2017-02-28 13:11
I submitted #3227 last week to solve this issue.

**Comment by muffgaga** [comment] 2017-02-28 13:47
This issue is a duplicate of my suggestion #1789

**Comment by paulhopkins** [comment] 2017-02-28 14:06
> Have you looked at the official Python guidelines on this issue?

I think the official guidance is to use Pip to install packages: https://packaging.python.org/installing/#installing-from-local-archives. To manage scientific software stacks use Spack, Hashdist, or conda: https://packaging.python.org/current/.

To be clear the reason I mention this now is that using the `--single-version-externally-managed` does not create multiple `easy-install.pth` files which have to be combined together.

**Comment by citibeth** [comment] 2017-02-28 14:17
@paulhopkins Sorry, I meant the issue of the same package being present on two or more installs, and how to merge those packages.  I believe there's a "hacky" way to do it from Python2, which was later revamped for Python3.  But not all software follows the standard, and that can cause problems; for example, `basemap` + `matplotlib`.  See #1964 for more details...

**Comment by muffgaga** [comment] 2017-02-28 15:08
What happens to old distutils-based `setup.py`s? AFAIK the distutils' install command does not support `--single-version-externally-managed`. (And what about wheels... does it solve this namespace problem?). @paulhopkins

@obreitwi In any case, your changeset should handle merging of already activated extensions (i.e. ignore activated extensions).

**Comment by alalazo** [comment] 2017-11-03 07:45
Is this solved by #5415?

**Comment by obreitwi** [comment] 2017-11-03 10:03
As far as I am concerned it is solved.

**Comment by alalazo** [comment] 2017-11-03 10:06
I am going to close this then, please reopen if there's need

**Closed by alalazo** 2017-11-03 10:06 UTC
Labels: python
