### ISSUE TITLE
Wrong dependencies for flang compiler

### ISSUE THREAD

**Issue by ChinouneMehdi** [LLNL/spack#5991] opened 2017-10-26 17:40 UTC
To build flang compiler one need to build : llvm, openmp-llvm clang-flang and flang
the flang compiler in spack depend only on llvm (which includes openmp) and con not be built without clang.

**Comment by junghans** [comment] 2017-10-26 17:55
`flang` depends on `llvm+clang` with a patch to build `clang-flang` as part of `llvm`. I haven't looked at the openmp dependency, but for `llvm+clang` openmp is build as part of `llvm`, too. So what dependency is missing?

Is this just a duplicate of the recently fixed #5941?

**Closed** 2017-10-26 18:01 UTC
