### ISSUE TITLE
Installation issue: flang

### ISSUE THREAD

**Issue by BenWibking** [LLNL/spack#18553] opened 2020-09-07 21:56 UTC
### Steps to reproduce the issue

```console
$ spack install flang
...
==> Installing flang
==> No binary for flang found: installing from source
==> Using cached archive: /home/benwibking/spack/var/spack/cache/_source-cache/archive/b8/b8c621da53829f8c53bad73125556fb1839c9056d713433b05741f7e445199f2.tar.gz
==> flang: Executing phase: 'cmake'
==> flang: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make'

3 errors found in build log:
     519    In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/ios_base.h
            :39:
     520    In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/atomicity.h
            :35:
     521    In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/x86_64-linux-gnu/c++/
            9/bits/gthr.h:148:
     522    In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/x86_64-linux-gnu/c++/
            9/bits/gthr-default.h:35:
     523    In file included from /usr/include/pthread.h:22:
     524    In file included from /usr/include/sched.h:43:
  >> 525    /usr/include/x86_64-linux-gnu/bits/sched.h:92:12: error: exception specification in declaration
             does not match previous declaration
     526    extern int getcpu (unsigned int *, unsigned int *) __THROW;
     527               ^
     528    /tmp/benwibking/spack-stage/spack-stage-flang-20190329-begpn7xyomjbpz64jolyivsvt5ruia2d/spack-s
            rc/include/legacy-util-api.h:91:15: note: previous declaration is here
     529    unsigned long getcpu(void);
     530                  ^
     531    1 error generated.
  >> 532    make[2]: *** [tools/flang2/utils/ilitp/CMakeFiles/ilitp.dir/build.make:85: tools/flang2/utils/i
            litp/CMakeFiles/ilitp.dir/ilitp.cpp.o] Error 1
     533    make[2]: Leaving directory '/tmp/benwibking/spack-stage/spack-stage-flang-20190329-begpn7xyomjb
            pz64jolyivsvt5ruia2d/spack-build'
  >> 534    make[1]: *** [CMakeFiles/Makefile2:1564: tools/flang2/utils/ilitp/CMakeFiles/ilitp.dir/all] Err
            or 2
     535    make[1]: Leaving directory '/tmp/benwibking/spack-stage/spack-stage-flang-20190329-begpn7xyomjb
            pz64jolyivsvt5ruia2d/spack-build'
     536    make: *** [Makefile:152: all] Error 2

See build log for details:
  /tmp/benwibking/spack-stage/spack-stage-flang-20190329-begpn7xyomjbpz64jolyivsvt5ruia2d/spack-build-out.txt
```

### Information on your system

* **Spack:** 0.15.4-879-28c6ce971
* **Python:** 3.8.2
* **Platform:** linux-ubuntu20.04-zen2

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/5185001/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/5185006/spack-build-env.txt)

@naromero77 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by BenWibking** [comment] 2020-09-07 22:29
It looks like this failure may be due to glibc 2.29+ including a wrapper around the `getcpu` system call: https://lwn.net/Articles/778286/

It looks like this version is not yet shipping in RHEL/CentOS, so this may have been missed in testing.  Hopefully a good argument to include the latest Ubuntu LTS release in build tests.

**Comment by naromero77** [comment] 2020-09-08 15:56
Looks like you are building with a really old version of clang, could you please try to build with a recent version of GCC (>7.5).

`spack install flang%gcc`

**Comment by BenWibking** [comment] 2020-09-09 01:08
I don't know why the build log reports Clang 7, which I don't even have installed. I'm actually building with gcc by default:

```
DESKTOP-AD96FNH% spack compilers
==> Available compilers
-- clang ubuntu20.04-x86_64 -------------------------------------
clang@10.0.0

-- gcc ubuntu20.04-x86_64 ---------------------------------------
gcc@9.3.0  gcc@8.4.0
DESKTOP-AD96FNH% spack spec flang
Input spec
--------------------------------
flang

Concretized
--------------------------------
flang@20190329%gcc@9.3.0~cuda build_type=RelWithDebInfo cuda_arch=none arch=linux-ubuntu20.04-zen2
    ^cmake@3.18.2%gcc@9.3.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu20.04-zen2
        ^ncurses@6.2%gcc@9.3.0~symlinks+termlib arch=linux-ubuntu20.04-zen2
            ^pkgconf@1.7.3%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
        ^openssl@1.1.1g%gcc@9.3.0+systemcerts arch=linux-ubuntu20.04-zen2
            ^perl@5.30.3%gcc@9.3.0+cpanm+shared+threads arch=linux-ubuntu20.04-zen2
                ^berkeley-db@18.1.40%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
                ^gdbm@1.18.1%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
                    ^readline@8.0%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
            ^zlib@1.2.11%gcc@9.3.0+optimize+pic+shared arch=linux-ubuntu20.04-zen2
    ^llvm-flang@20190329%gcc@9.3.0~all_targets~cuda build_type=Release cuda_arch=none arch=linux-ubuntu20.04-zen2
        ^hwloc@2.2.0%gcc@9.3.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml+pci+shared arch=linux-ubuntu20.04-zen2
            ^libpciaccess@0.16%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
                ^libtool@2.4.6%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
                    ^m4@1.4.18%gcc@9.3.0+sigsegv patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 arch=linux-ubuntu20.04-zen2
                        ^libsigsegv@2.12%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
                ^util-macros@1.19.1%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
            ^libxml2@2.9.10%gcc@9.3.0~python arch=linux-ubuntu20.04-zen2
                ^libiconv@1.16%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
                ^xz@5.2.5%gcc@9.3.0~pic arch=linux-ubuntu20.04-zen2
        ^perl-data-dumper@2.173%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
        ^python@3.8.5%gcc@9.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-ubuntu20.04-zen2
            ^bzip2@1.0.8%gcc@9.3.0+shared arch=linux-ubuntu20.04-zen2
                ^diffutils@3.7%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
            ^expat@2.2.9%gcc@9.3.0+libbsd arch=linux-ubuntu20.04-zen2
                ^libbsd@0.10.0%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
            ^gettext@0.21%gcc@9.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu20.04-zen2
                ^tar@1.32%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
            ^libffi@3.3%gcc@9.3.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=linux-ubuntu20.04-zen2
            ^libuuid@1.0.3%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
            ^sqlite@3.33.0%gcc@9.3.0+column_metadata+fts~functions~rtree arch=linux-ubuntu20.04-zen2
    ^pgmath@20190329%gcc@9.3.0 build_type=RelWithDebInfo patches=4014df1e5855dd21242b0fc938a4e7835941c20f9a89c3a7a5314e74b6232bcb,ef386e848c01cd115f4ba93a3d9292e4ed960332fcf71a15f6967bf8a0982c1e arch=linux-ubuntu20.04-zen2
        ^gawk@5.0.1%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
            ^gmp@6.1.2%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
                ^autoconf@2.69%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
                ^automake@1.16.2%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
            ^mpfr@4.0.2%gcc@9.3.0 patches=3f80b836948aa96f8d1cb9cc7f3f55973f19285482a96f9a4e1623d460bcccf0 arch=linux-ubuntu20.04-zen2
                ^autoconf-archive@2019.01.06%gcc@9.3.0 arch=linux-ubuntu20.04-zen2
```

**Comment by BenWibking** [comment] 2020-09-09 01:12
Explicitly adding %gcc to the spec gives the same error:

```
% spack install flang%gcc
[...]
==> Installing flang
==> No binary for flang found: installing from source
==> Using cached archive: /home/benwibking/spack/var/spack/cache/_source-cache/archive/b8/b8c621da53829f8c53bad73125556fb1839c9056d713433b05741f7e445199f2.tar.gz
==> flang: Executing phase: 'cmake'
==> flang: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make'

3 errors found in build log:
     519    In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/ios_base.h:39:
     520    In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/atomicity.h:35:
     521    In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/x86_64-linux-gnu/c++/9/bits/gthr.
            h:148:
     522    In file included from /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/x86_64-linux-gnu/c++/9/bits/gthr-
            default.h:35:
     523    In file included from /usr/include/pthread.h:22:
     524    In file included from /usr/include/sched.h:43:
  >> 525    /usr/include/x86_64-linux-gnu/bits/sched.h:92:12: error: exception specification in declaration does not ma
            tch previous declaration
     526    extern int getcpu (unsigned int *, unsigned int *) __THROW;
     527               ^
     528    /tmp/benwibking/spack-stage/spack-stage-flang-20190329-begpn7xyomjbpz64jolyivsvt5ruia2d/spack-src/include/l
            egacy-util-api.h:91:15: note: previous declaration is here
     529    unsigned long getcpu(void);
     530                  ^
     531    1 error generated.
  >> 532    make[2]: *** [tools/flang2/utils/ilitp/CMakeFiles/ilitp.dir/build.make:85: tools/flang2/utils/ilitp/CMakeFi
            les/ilitp.dir/ilitp.cpp.o] Error 1
     533    make[2]: Leaving directory '/tmp/benwibking/spack-stage/spack-stage-flang-20190329-begpn7xyomjbpz64jolyivsv
            t5ruia2d/spack-build'
  >> 534    make[1]: *** [CMakeFiles/Makefile2:1564: tools/flang2/utils/ilitp/CMakeFiles/ilitp.dir/all] Error 2
     535    make[1]: Leaving directory '/tmp/benwibking/spack-stage/spack-stage-flang-20190329-begpn7xyomjbpz64jolyivsv
            t5ruia2d/spack-build'
     536    make: *** [Makefile:152: all] Error 2
```

**Comment by naromero77** [comment] 2020-09-09 15:15
First, give the master branch a try:
spack install flang@master%gcc

Its common for these compilers to break with the newest releases on Linux. This is not a bug in Spack Flang package, but in Flang itself. If the master branch does not work, please file a github issue here:
https://github.com/flang-compiler/flang

Sorry that I can't be of more help.

**Comment by BenWibking** [comment] 2020-09-10 01:57
Ah, ok. Compiling with the master branch works! Thanks.

**Comment by naromero77** [comment] 2020-09-11 19:36
Your welcome. 

Since this is fixed in the master branch, I would consider this issue closed.

**Closed as completed** 2020-09-12 02:08 UTC
Labels: build-error
