### ISSUE TITLE
Undocumented install steps and dependencies.

### ISSUE THREAD

**Issue by gartung** [LLNL/spack#434] opened 2016-02-11 18:46 UTC
I have been trying out spack on Scientific Linux Fermi 6 and I ran into some stumbling blocks. First spack seems to be dependent on the python-backports library to function correctly. Second after cloning the repository I had to run 'spack compiler add' for the system compiler to be configured. The second step was also necessary on OSX10.10.

**Comment by adamjstewart** [comment] 2016-02-12 16:46
The second step you mentioned is actually well documented. If you take a look at:
http://software.llnl.gov/spack/basic_usage.html#compiler-configuration
you'll see what I mean. In many cases, Spack can auto-detect compilers that are present in your path when you install it. However, if you don't have all of your compilers in your path or they are installed in a non-standard location, then they will need to be manually added.

As to your first step, I'm not familiar with the python-backports library. Is that something that is used to backport features of Python 3 to Python 2? I believe Spack requires Python 2.6 or 2.7, although I'm not sure if/where that is documented. What version of Python are you running?

**Comment by gartung** [comment] 2016-02-12 16:58
I am just referring to README.md and the first package install example. I ran those command and got an error message about no compilers found. This was on SLF6.6 install ( A RedHat EL 6.6 recompile that Fermilab does). The system python version is 2.6.6. I got an error in spack when I tired to run it on SLF6.6 system. The error occurred in the nose package config call.  On a SLF6.7 and CentOS6.7 I did not get the same error but I got the missing compilers error. The only difference in the python configuration of these systems was that the python-backports package was not installed on the SLF6.6 system.

**Comment by adamjstewart** [comment] 2016-02-12 17:10
Ah, I see. Well, the README can't possibly discuss every problem that may occur and how to solve it. That's why it points to the [full documentation](http://llnl.github.io/spack) in many locations. For most system admin users, there should be at least one compiler in your PATH, so this situation shouldn't arise very frequently. Do you think we should add something to the README for this situation, or point to the full documentation sooner? It would be nice to keep the README simple, but we also don't want to scare away new users who think that Spack doesn't work.

I don't know much about nose, so I'll let someone else handle that part of the issue.

**Comment by gartung** [comment] 2016-02-12 17:22
The system compilers were installed in the usual location /usr/bin/gcc. I am only proposing that you add the line

spack compiler add 

to the current 3 line instructions in README.md.

**Comment by tgamblin** [comment] 2016-02-12 18:30
Hi @gartung: the compilers issue is a known bug -- I'm working on fixing it.  I think this crept into the develop branch recently.  `spack compilers` should auto detect and show something useful on a fresh clone, even if there are no compilers configured.

Also, the back ports issue sounds legitimate as well.  For nose, we tried to include the necessary 2.6 packages to remain compatible, but maybe we missed something.  Can you paste the error message you get *without* `python-backports`?  Spack should run on Python 2.6 without additional packages.

**Comment by gartung** [comment] 2016-02-12 19:38
It may or may not be related to python-backports being available. The error appeared even after the sysadmin install the rpm. When I ran python -m trace --trace `which spack` the error went away. That may have been because nose.py got recompiled with the backport package available. The original error is below.

[gartung@woof ~]$ export SPACK_ROOT=~/scratch/spack/
[gartung@woof ~]$ export PATH=$SPACK_ROOT/bin:$PATH
[gartung@woof ~]$ spack
Traceback (most recent call last):
  File "/home/gartung/scratch/spack//bin/spack", line 50, in <module>
    import nose
  File "/scratch/gartung/spack/lib/spack/external/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/scratch/gartung/spack/lib/spack/external/nose/core.py", line 11, in <module>
    from nose.config import Config, all_config_files
  File "/scratch/gartung/spack/lib/spack/external/nose/config.py", line 2, in <module>
    import optparse
  File "/usr/lib64/python2.6/optparse.py", line 90, in <module>
    from gettext import gettext
  File "/usr/lib64/python2.6/gettext.py", line 49, in <module>
    import locale, copy, os, re, struct, sys
  File "/usr/lib64/python2.6/locale.py", line 98, in <module>
    @functools.wraps(_localeconv)
AttributeError: 'module' object has no attribute 'wraps'

**Comment by gartung** [comment] 2016-02-12 20:02
I did trigger a rebuild on nose/config.py because I commented/uncommented this line

from optparse import OptionParser

which moved the error down to the first use of OptionParser

        self.parserClass = OptionParser



-rw-r--r--. 1 gartung g163   698 Feb 11 10:55 __init__.pyc
-rw-r--r--. 1 gartung g163 13389 Feb 11 10:55 core.pyc
-rw-r--r--. 1 gartung g163 25238 Feb 11 11:39 config.py
-rw-r--r--. 1 gartung g163 24099 Feb 11 11:39 config.pyc
-rw-r--r--. 1 gartung g163 21749 Feb 11 11:59 util.pyc

**Comment by gartung** [comment] 2016-02-12 20:16
I am not sure what was in my PYTHON_PATH variable at the time. I searched with google which suggested that something was shadowing @functools.wraps(_localeconv)

**Comment by tgamblin** [comment] 2016-02-18 08:58
@gartung: the latest commit should fix the issue with `spack compilers` not working right on a fresh clone.

I'm reopening this to look into the dependency issues.

**Comment by tgamblin** [comment] 2016-02-18 09:09
@gartung: I can't reproduce the import error locally.  The version of `nose` in Spack is compatible with Python 2.6, so that shouldn't be an issue.

The error you're getting would seem to imply that `functools.wraps` is not present, but that has been around since Python 2.5 and you're using 2.6.  Spack uses one backported function from 2.7 `functools` (`total_ordering`), but that is hidden in a `functools_backport` namespace, so it wouldn't interfere.

The only thing I can imagine is, as you suggest, that something in your `PYTHONPATH` shadowed `functools`.  

I'll close this for now, but feel free to reopen the issue if you're able to reproduce this problem again.

**Closed by tgamblin** 2016-02-18 09:09 UTC
