### ISSUE TITLE
"cuda" package runtime libs and headers not mapped in environment view

### ISSUE THREAD

**Issue by AndrewGaspar** [LLNL/spack#19531] opened 2020-10-26 21:26 UTC
The runtime libraries for cuda, located in "lib64" of the install prefix, and the header files, located in "include" of the install prefix, are not mapped into the target environment view.

If I had to hazard a guess, it's probably relevant that the "lib64" and "include" directories are symbolic links. Regardless, it's undesirable behavior.

### Steps to reproduce the issue

```console
$ spack env create cuda-test
$ spack env activate cuda-test
$ spack add cuda
$ spack install
$ ls $SPACK_ENV/.spack-env/view/lib64
# Observe that "libcudart" is not present
```

I disable and re-enabled the view with `-d`, and I didn't get any extra output. More "d"s didn't help.

```console
$ spack -d env view enable
==> Updating view at /home/agaspar/spack/var/spack/environments/cuda-test/.spack-env/view
```

### Error Message

```console
$ ls $(spack location -i cuda)/lib64
libaccinj64.so -> libaccinj64.so.11.1
libaccinj64.so.11.1 -> libaccinj64.so.11.1.69
libaccinj64.so.11.1.69
libcublas.so -> libcublas.so.11
libcublas.so.11 -> libcublas.so.11.2.1.74
libcublas.so.11.2.1.74
libcublas_static.a
libcublasLt.so -> libcublasLt.so.11
libcublasLt.so.11 -> libcublasLt.so.11.2.1.74
libcublasLt.so.11.2.1.74
libcublasLt_static.a
libcudadevrt.a
libcudart.so -> libcudart.so.11.0
libcudart.so.11.0 -> libcudart.so.11.1.74
libcudart.so.11.1.74
libcudart_static.a
libcufft.so -> libcufft.so.10
libcufft.so.10 -> libcufft.so.10.3.0.74
libcufft.so.10.3.0.74
libcufft_static.a
libcufft_static_nocallback.a
libcufftw.so -> libcufftw.so.10
libcufftw.so.10 -> libcufftw.so.10.3.0.74
libcufftw.so.10.3.0.74
libcufftw_static.a
libcuinj64.so -> libcuinj64.so.11.1
libcuinj64.so.11.1 -> libcuinj64.so.11.1.69
libcuinj64.so.11.1.69
libculibos.a
libcurand.so -> libcurand.so.10
libcurand.so.10 -> libcurand.so.10.2.2.74
libcurand.so.10.2.2.74
libcurand_static.a
libcusolver.so -> libcusolver.so.11
libcusolver.so.11 -> libcusolver.so.11.0.0.74
libcusolver.so.11.0.0.74
libcusolver_static.a
libcusolverMg.so -> libcusolverMg.so.11
libcusolverMg.so.11 -> libcusolverMg.so.11.0.0.74
libcusolverMg.so.11.0.0.74
libcusparse.so -> libcusparse.so.11
libcusparse.so.11 -> libcusparse.so.11.2.0.275
libcusparse.so.11.2.0.275
libcusparse_static.a
liblapack_static.a
libmetis_static.a
libnppc.so -> libnppc.so.11
libnppc.so.11 -> libnppc.so.11.1.1.269
libnppc.so.11.1.1.269
libnppc_static.a
libnppial.so -> libnppial.so.11
libnppial.so.11 -> libnppial.so.11.1.1.269
libnppial.so.11.1.1.269
libnppial_static.a
libnppicc.so -> libnppicc.so.11
libnppicc.so.11 -> libnppicc.so.11.1.1.269
libnppicc.so.11.1.1.269
libnppicc_static.a
libnppidei.so -> libnppidei.so.11
libnppidei.so.11 -> libnppidei.so.11.1.1.269
libnppidei.so.11.1.1.269
libnppidei_static.a
libnppif.so -> libnppif.so.11
libnppif.so.11 -> libnppif.so.11.1.1.269
libnppif.so.11.1.1.269
libnppif_static.a
libnppig.so -> libnppig.so.11
libnppig.so.11 -> libnppig.so.11.1.1.269
libnppig.so.11.1.1.269
libnppig_static.a
libnppim.so -> libnppim.so.11
libnppim.so.11 -> libnppim.so.11.1.1.269
libnppim.so.11.1.1.269
libnppim_static.a
libnppist.so -> libnppist.so.11
libnppist.so.11 -> libnppist.so.11.1.1.269
libnppist.so.11.1.1.269
libnppist_static.a
libnppisu.so -> libnppisu.so.11
libnppisu.so.11 -> libnppisu.so.11.1.1.269
libnppisu.so.11.1.1.269
libnppisu_static.a
libnppitc.so -> libnppitc.so.11
libnppitc.so.11 -> libnppitc.so.11.1.1.269
libnppitc.so.11.1.1.269
libnppitc_static.a
libnpps.so -> libnpps.so.11
libnpps.so.11 -> libnpps.so.11.1.1.269
libnpps.so.11.1.1.269
libnpps_static.a
libnvblas.so -> libnvblas.so.11
libnvblas.so.11 -> libnvblas.so.11.2.1.74
libnvblas.so.11.2.1.74
libnvjpeg.so -> libnvjpeg.so.11
libnvjpeg.so.11 -> libnvjpeg.so.11.2.0.74
libnvjpeg.so.11.2.0.74
libnvjpeg_static.a
libnvptxcompiler_static.a
libnvrtc-builtins.so -> libnvrtc-builtins.so.11.1
libnvrtc-builtins.so.11.1 -> libnvrtc-builtins.so.11.1.74
libnvrtc-builtins.so.11.1.74
libnvrtc.so -> libnvrtc.so.11.1
libnvrtc.so.11.1 -> libnvrtc.so.11.1.74
libnvrtc.so.11.1.74
libnvToolsExt.so -> libnvToolsExt.so.1
libnvToolsExt.so.1 -> libnvToolsExt.so.1.0.0
libnvToolsExt.so.1.0.0
libOpenCL.so -> libOpenCL.so.1
libOpenCL.so.1 -> libOpenCL.so.1.0
libOpenCL.so.1.0 -> libOpenCL.so.1.0.0
libOpenCL.so.1.0.0
stubs
```

```console
$ ls $SPACK_ENV/.spack-env/view/lib64
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.15.4-1499-e61330a50
* **Python:** 3.8.5
* **Platform:** linux-rhel7-power9le
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment] 2020-10-26 23:50
@ax3l @Rombur

**Comment by ax3l** [comment] 2020-11-30 22:59
Thank you for the report and reproducer!

Hm, I wonder where they should be showing up? In `$SPACK_ENV/.spack-env/view/lib64` or do we map those to `lib/`? The missing `include/` is definitely also an issue.

This looks like a general environment issue to me that manifests in this package.

**Comment by AndrewGaspar** [comment] 2020-11-30 23:02
Oh, probably lib64. I should correct the reproducer instructions. Don't know why lib was put in that first bit when lib64 is used everywhere else.

> This looks like a general environment issue to me that manifests in this package.

That would be my guess.

**Comment by lockshaw** [comment] 2021-03-07 06:57
I ran into this issue as well and it definitely seems to be caused by `include` and `lib64` being symlinks. I was able to fix it by modifying the `install` procedure in the CUDA package to replace the symlinks with a full copy of the directory. Is this a fix that should be applied to the package, or does a change need to be made to the underlying environment functionality? 

@ax3l recommended I mention @adamjstewart and @alalazo on this

**Comment by adamjstewart** [comment] 2021-03-07 14:45
There is a way to modify the environment functionality to handle this. We had to do something similar for Python. I'm not aware of the details, but @scheibelp or @becker33  would know.

**Comment by scheibelp** [comment] 2021-03-08 19:27
In short: https://github.com/spack/spack/issues/19531#issuecomment-792228997 I think is the best short-term fix for this

In more detail:

"copying" symlinks in general would require modifications to the core Spack code. I can't remember (or never had to understand in the first place) why we may want to avoid copying symlinks. Ultimately I think we'll either need to modify that to include all symlinks or provide some function that explicitly indicates some symlinks should be included.

Packages can define `add_files_to_view`, but at the point this function executes, the symlinks are excluded from consideration. Searching for them would be awkward given the exposed API. Manually redefining the symlinks could be possible but is also awkward and would require updating the corresponding `remove_files_from_view` function (which I think is more difficult):

```
# Manually redefine symlinks. Note this is not actually recommended, just an example
# of how it would be done with add_files_to_view
def add_files_to_view(self, view, merge_map):
    dst_root = os.path.abspath(
        view.get_projection_for_spec(self.spec))
    for src, dst in merge_map.items():
        fname = os.path.basename(src)
        if fname.endswith('.so'):
            view.link(src, os.path.join(dst_root, 'lib64', fname))
        if not os.path.exists(dst):
            view.link(src, dst, spec=self.spec)
```

**Comment by alalazo** [comment] 2023-07-11 08:06
Seem to be fixed as of:

* **Spack:** 0.21.0.dev0 (64c6d63675f8e45e0be12a9c55acb4b7969e383a)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

![Screenshot from 2023-07-11 10-06-26](https://github.com/spack/spack/assets/4199709/53a90231-c198-48f3-adff-481dc903d2dc)

**Closed as completed by alalazo** 2023-07-11 08:06 UTC
Labels: bug, environments, cuda, triage
