### ISSUE TITLE
Installing gcc@6.2: `configure: error: cannot compute sizeof (long long)`

### ISSUE THREAD

**Issue by willfurnass** [LLNL/spack#1866] opened 2016-09-27 19:45 UTC
Trying to build gcc@6.2.0 on Centos 7.2 x64 and get

```
configure: error: cannot compute sizeof (long long)
```

This error resulted from doing the following:

```
$ yum install gcc gcc-g++ autoconf autotools libtool bzip2 xz
...
$ spack compiler add
==> Added 1 new compiler to /home/will/.spack/compilers.yaml
    gcc@4.8.5
$ spack install gcc@6.2.0
```

**Comment by willfurnass** [comment] 2016-10-09 15:45
Same issue if try to `spack instal gcc@5.4.0`

**Comment by adamjstewart** [comment] 2016-10-09 17:24
Do you have a Fortran compiler? I wonder if installing gfortran and adding that to your `~/.spack/compilers.yaml` would help.

**Comment by willfurnass** [comment] 2016-10-11 14:50
Installed `gcc-gfortran` using `yum` but the problem persists.  From the `spack-build.out` log:

```
checking for ptrdiff_t... configure: error: in `/tmp/sa_cs1wf/spack-stage/spack-stage-OeXEui/spack-build/gcc':
configure: error: cannot compute sizeof (long long)
See `config.log' for more details.
make[2]: *** [configure-stage1-gcc] Error 77
```

**Comment by adamjstewart** [comment] 2016-10-11 14:52
Can you run `spack config get compilers` and show me the output?

**Comment by willfurnass** [comment] 2016-10-11 15:08
For some bizarre reason I had:
```
$ spack config get compilers
compilers:
- compiler:
    modules: []
    operating_system: redhat6
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: gcc@4.4.7
- compiler:
    modules: []
    operating_system: centos7
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.8.5
```
This may be due to me having a home dir shared between two clusters and having tried using spack on the older RHEL6 one previously.

I deleted `~/.spack`, ran `spack compiler rm gcc@4.4.7` to ditch the unwanted version of GCC then re-ran `spack install gcc@6.2.0` but the install failed in the same way as before.

**Comment by adamjstewart** [comment] 2016-10-11 15:16
Does a manual installation outside of Spack work? I can't imagine that your compilers depend on environment variables to run since they are yum installations.

@citibeth You run CentOS 7, right? Have you run into anything like this?

**Comment by willfurnass** [comment] 2016-10-11 16:07
Yes, I've already set up GCC 6.2 on the cluster using [this script](https://github.com/mikecroucher/HPC_Installers/blob/master/compilers/gcc/6.2/sheffield/sharc/install_gcc_6.2.sh) so it can be loaded using [this modulefile](https://github.com/mikecroucher/HPC_Installers/blob/master/compilers/gcc/6.2/sheffield/sharc/6.2).  However I'm keen to move away from writing manual install scripts if possible:)

**Comment by sknigh** [comment] 2016-10-11 23:19
@willfurnass Fortran compilers are not necessary to build GCC. GCC should be able to build with 4.4.7/4.8.5 which are available on Centos 6/7.

Recommend trying  ```spack install gcc@6.2.0~binutils``` on Centos 7

**Comment by willfurnass** [comment] 2016-10-12 10:52
@sknigh : `spack install gcc@6.2.0~binutils` worked!  Am I right in saying that this uses the system `ld`, `as` etc rather than the ones provided by the spack `binutils` package?

**Comment by sknigh** [comment] 2016-10-12 18:24
@willfurnass  It's a bad combination of binutil's ```ld``` and spack's tenancy to purge the environment variables that break the build system. You should see this in the configure script output (note: not the normal build output). 

I don't know why this isn't an issue on Centos 6.

**Comment by adamjstewart** [comment] 2017-04-13 17:41
I've never had `gcc+binutils` work. In my mind, the default should really be `gcc~binutils`. I've raised this issue elsewhere, but no one has agreed. Since @willfurnass was able to get GCC installed properly, I'll close this issue.

**Comment by jcftang** [comment] 2017-04-18 15:50
JTFR this behaviour can be seen in gcc 6.3.0 on centos7

**Comment by adamjstewart** [comment] 2017-04-18 15:55
> this behaviour can be seen in gcc 6.3.0 on centos7

Just to clarify, you mean `gcc+binutils` doesn't work but `gcc~binutils` does? I know I got `gcc@6.3.0~binutils` to install on CentOS 7.

**Comment by jcftang** [comment] 2017-04-18 15:57
> Just to clarify, you mean gcc+binutils doesn't work but gcc~binutils does? I know I got gcc@6.3.0~binutils to install on CentOS 7.

Yes @adamjstewart that is what I meant

**Comment by baberlevi** [comment] 2017-06-08 20:14
I am getting the same error installing gcc (I've tried 6.3 and 7.1) on RHEL7.  Ubuntu17.04 worked for me. Currently testing CentOS7 - will update this ticket with results.

Binutils builds successfully, but during the configure process of gcc, it fails with the 'long long' error. Installing gcc~binutils works (this doesn't seem like a solution to me, but a workaround).

I've also tried loading the binutils/2.28 module that spack built, and using the --dirty flag to install gcc+binutils, but that results in the same error.

**Comment by adamjstewart** [comment] 2017-06-08 20:23
@ssergien and I have seen this same problem as well. At ANL we've never been able to get `gcc+binutils` to build on CentOS 6 or 7. Once again, I vote to make the default `gcc~binutils` until someone fixes `gcc+binutils`.

**Comment by baberlevi** [comment] 2017-06-08 20:28
Confirmed, CentoOS7 has the same issue as RHEL7 (as expected).

I see in https://github.com/LLNL/spack/pull/2144 @citibeth says that CentOS7 install has been successful with gcc+binutils. Curious how that worked ?

**Comment by alalazo** [comment] 2017-06-09 05:59
@adamjstewart @baberlevi Now I am curious what could be the difference among our environments, because we built `gcc@5.4.0`, `gcc@6.3.0` and `gcc@7.1.0` without issues on RHEL6 and RHEL7 (all of them with the default `+binutils` variant).

**Closed** 2017-08-07 17:13 UTC
Labels: linux, new-package
