### ISSUE TITLE
spack fails to include default variants as dependencies

### ISSUE THREAD

**Issue by ashkan2200** [LLNL/spack#2503] opened 2016-12-07 15:03 UTC
Hi all,

There is an issue with spack where if I input the command `spack install dealii ^trilinos@12.8.1` the command fails by saying `Dealii does not depend on trilinos`. However, Deal.II is compiled with Trilinos as one of the dependencies which are turned on by default.

On the other hand, if I point explicitly that trilinos should be enabled `spack install dealii+mpi+trilinos ^trilinos@12.8.1`, I don't get the error anymore.

Is this a bug or a feature? :)

**Comment by citibeth** [comment] 2016-12-07 15:23
Yes, that's about how it works. I'll let others decide whether it's a bug or a feature.

You can also put a `trilinos` entry into your `packages.yaml` file, then you just have to write `spack install dealii`.

**Comment by davydden** [comment] 2016-12-07 15:25
yes, it's known inconvenient behaviour that defaults are not considered so you need to help spack with `spack install dealii+mpi+trilinos ^trilinos@12.8.1`.

I generally find it easier to work with `packages.yaml` and put all my preferred versions/variants there.

**Comment by citibeth** [comment] 2016-12-07 15:29
I think this has been answered adequately, closing for now.

**Comment by adamjstewart** [comment] 2016-12-07 15:29
Yes, this bug has been around since the early days of Spack. I believe #397 is the oldest known reference I've seen. @tgamblin has a lot of work planned for the concretizer, and I believe this is one of the issues we would all like addressed, just for the sake of avoiding confusion.

**Comment by citibeth** [comment] 2016-12-07 15:30
OK my mistake closing... I re-opened and added the "documentation" tag.  Unless/until we fix, we should talk about this "gotcha" in the docs.

**Comment by tgamblin** [comment] 2016-12-07 15:40
Can we add a "known issues" page to the docs to reduce the number of open issues?  We have some things like this in the getting started guide, but not in easily referenced form like I've seen other projects do.

It could even reference original issues on github, and then when we close duplicates, we can reference the original as @adamjstewart did so that there's a link to the new one.

**Comment by adamjstewart** [comment] 2016-12-07 15:43
I would definitely be in favor of linking to original issues and closing duplicates. I always cringe at spending time documenting bugs vs. just fixing them, but for complicated bugs like this that may take a while.

**Comment by citibeth** [comment] 2016-12-07 15:51
There are two problems here relating to too many open issues:

1. Open bugs
2. Open documentation requests.

Why don't we make a two single Issues called something like "Known Issues"
and "Documentation Issues".  When we decide to close discussion on an issue
but mark it as something we wish to fix or document later, we link it into
those two Issues.

OK, I'll demo this...

**Comment by adamjstewart** [comment] 2016-12-07 16:00
Instead of documenting things that are missing from the documentation, and creating elaborate posts containing the information that should be documented... why don't we just add it to the documentation and close the issue? Yes, some missing documentation is contributor-knowledge specific (I'm looking at you @alalazo 😉) but a lot of these are pretty simple...

**Comment by citibeth** [comment] 2016-12-07 16:02
Because oftentimes other people provide the information in the post, and
nobody at the time has the time or inclination to fix the docs.  In the
past, I was very productive by tackling 10 small doc problems at once.

**Comment by tgamblin** [comment] 2016-12-07 19:12
> nobody at the time has the time or inclination to fix the docs

The idea was to add a section called "Known Issues" in the docs and link to github issues for long-standing things... I don't see how the new issues help people a) find the information more easily or b) cut down on the number of open issues.

**Comment by citibeth** [comment] 2016-12-07 19:27
It looks like there are two slightly different proposals here:

1. Add a section called "Known Issues" in the docs and link to github issues for long-standing things...

2. Create an Issue thread called "Known Issues" and link to github issues for long-standing things.... (and also create a single link to this "Known Issues" thread from the docs).  [See #2505 for an example of how the "Known Issues" thread could work].

My concern with (1) is that in the past, getting things merged takes time and concerted effort.  The process is (legitimately) slowed down by discussions, peoples' time issues, etc.  Just look at #2478 to see what I mean... what was in theory a "quick and simple" checklist turned into a lot of discussions, resulting in (so far) nothing that is mergeable.  And that is AFTER significant time spent on it.

I think that forcing known issues through the merge process would be inappropriate.  Even if we decide to relax our standards here and NOT argue about what is / is not a known issue, someone will still have to commit to merging "Known Issue PRs" in a timely fashion.

The alternative in (2) offers similar functionality but less red tape.  We can quickly link new issue threads to the "Known Issues" thread, close the original thread, and then later have the debates on each issue individually to eventually get it in the docs, or fixed.

Alternative (2) does not prevent people from sifting through known issues from the "Known Issues" thread, writing them up a bit in RST format, and including them directly in the manual.  That should be encouraged, in fact.

As a separate but similar idea, I am also suggesting a "Documentation Requests" thread (#2505) that functions similarly; it holds references to first-draft documents that people have written, that have not yet been vetted through the merge process.  That will allow us to close all the outstanding Issues that have resulted in nothing more than a need to improve documentation.

**Comment by tgamblin** [comment] 2016-12-07 20:32
@citibeth: 

1. I suspect, though I could be wrong, that a known issues page would incite considerably less controversy than the contributor guide.  Does anyone disagree about which issues are known?  I think we're all pretty open about that.  It's much more clear cut than "what should every PR submitter have to do".

2. The timescale we're talking about here is long.  I am not so concerned about the merge time because this is specifically for things we may not fix for a while.  So the merge overhead seems small to me.  If it's something that's easier to just fix we should do that (per @adamjstewart)

3. I don't like the documentation requests issue, because we already have the `documentation` label.  You can just click on it to see all the open documentation requests.  I would rather have a distributed labeling system than a system where we have to remember to edit and append to #2405.

4. The idea was to get the known issues into the docs, so that new users can see them easily.  I think most people will not want to wade through github issues.

**Comment by citibeth** [comment] 2016-12-07 20:59
>
>    1.
>
>    The idea was to get the known issues into the docs, so that new users
>    can see them easily. I think most people will not want to wade through
>    github issues.
>
>
Does this mean writing them up for the docs in RST format?  Or does it mean
simply putting a GitHub link into the docs?

Still, submitting a PR for every known-issue would still be a pain. How
about this... when we see a known issue that needs to head to the docs, we
tag it with known-issue and documentation.  Someone else figures out what
to do later when collecting the documentation tags...

**Comment by jrood-nrel** [comment] 2016-12-12 18:41
Can I vote bug on this? I was just about to post this exact same thing as an issue.

**Comment by citibeth** [comment] 2016-12-13 05:37
Jon, what do you mean by "vote bug on this"?

**Comment by adamjstewart** [comment] 2016-12-13 14:00
@citibeth OP asked if this was a bug or a feature (maybe a rhetorical question). @jrood-nrel votes that's it's a bug.

**Comment by adamjstewart** [comment] 2017-05-22 16:06
Since this is a duplicate of #397 and is now documented as of #3722, I'm going to close this issue.

**Closed by adamjstewart** 2017-05-22 16:06 UTC
Labels: concretization, documentation, duplicate
