### ISSUE TITLE
Module Referesh makes different module from `spack install`

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#3074] opened 2017-02-08 16:43 UTC
@alalazo 

The problem: I did a `spack install` on a package, which created a module file.  I immediately did a `spack module refresh`, which re-generated the module file.  The two module files are different.  See transcript below.

I have not applied #3060, although I suspect this is a different bug.

```
$ dspack install modele --setup ibmisc --setup pism --setup icebin modele
...
==> Generating config file icebin-config.py [icebin@develop%gcc@4.9.3+coupler~doc+everytrace+gridgen+modele+pism+python arch=linux-centos7-x86_64-z7c3fls]
...
$ dspack find -l icebin
==> 1 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
z7c3fls icebin@develop
$ cp ~/spack5/share/spack/modules/linux-centos7-x86_64/icebin-develop-gcc-4.9.3-z7c3fls  ~/tmp/x.mod
$ dspack module refresh icebin
$ diff ~/tmp/x.mod ~/spack5/share/spack/modules/linux-centos7-x86_64/icebin-develop-gcc-4.9.3-z7c3fls
2c2
< ## Module file created by spack (https://github.com/LLNL/spack) on 2017-02-08 11:32:40.732375
---
> ## Module file created by spack (https://github.com/LLNL/spack) on 2017-02-08 11:34:52.926176
15d14
< prepend-path PYTHONPATH "/home2/rpfische/spack5/opt/spack/linux-centos7-x86_64/gcc-4.9.3/icebin-develop-z7c3flsksji423veihw5torvrchgdqoq/lib/python3.5/site-packages"
```

Here is `icebin/package.py`.  Note that it conditionally `extends(python)`.

```
class Icebin(CMakePackage):
    """Regridding/Coupling library for GCM + Ice Sheet Model"""

    homepage = "https://github.com/citibeth/icebin"
    url         = "https://github.com/citibeth/icebin/tarball/v0.1.0"

    version('0.1.5', 'a209c4cd4502b9ded7525ebaa7c6107f')
    ...

    variant('everytrace', default=False, description='Report errors through Everytrace (requires Everytrace)')
    variant('python', default=True, description='Build Python extension (requires Python, Numpy)')
    variant('gridgen', default=True, description='Build grid generators (requires CGAL, GMP, MPFR)')
    variant('coupler', default=False, description='Build the GCM couplers (requires MPI)')
    variant('pism', default=False, description='Build coupling link with PISM (requires PISM, PETSc)')
    variant('modele', default=False, description='Build coupling link with ModelE (no exta requirements')
    variant('doc', default=False, description='Build documentation')

    extends('python', when='+python')

    depends_on('everytrace', when='+everytrace')

    depends_on('python@3:', when='+python')
    depends_on('py-cython', when='+python')
    depends_on('py-numpy', when='+python')

    depends_on('cgal', when='+gridgen')
    depends_on('gmp', when='+gridgen')
    depends_on('mpfr', when='+gridgen')

    depends_on('mpi', when='+coupler')
    depends_on('pism~python', when='+coupler+pism')
    depends_on('petsc', when='+coupler+pism')

    depends_on('boost+filesystem+date_time+mpi')
    depends_on('blitz')
    depends_on('netcdf-cxx4')
    depends_on('ibmisc+proj+blitz+netcdf+boost+udunits2+python')
    depends_on('proj')
    depends_on('eigen')

    depends_on('cmake', type='build')
    depends_on('doxygen', type='build', when='+doc')

    def cmake_args(self):
        ...
    def setup_environment(self, spack_env, run_env):
        """Add <prefix>/bin to the module; this is not the default if we
        extend python."""
        run_env.prepend_path('PATH', join_path(self.prefix, 'bin'))
```

**Comment by alalazo** [comment] 2017-02-08 17:54
I'll try to have a look. Two questions: what is `dspack` ? Which version of spack are you using?

**Comment by citibeth** [comment] 2017-02-08 18:16
```
alias dspack='\spack -c ~/spscopes/centos7 -c ~/spscopes/gissversions -c
~/spscopes/twoway -c ~/spscopes/develop'
```
It's just a way of combining a bunch of configuration scopes beyond those
built into Spack.  I don't have any `modules.yaml` files in those scopes.

I'm using a version whose most recent shared ancestor with `develop` is:
```
commit b9ec69dce15c69ba11f6d637614399b3a3a470e5
Author: Todd Gamblin <tgamblin@llnl.gov>
Date:   Sat Dec 31 08:12:38 2016 -0800
    Disallow vdeps in `packages.yaml` (#2699)
    * Consolidate packages.yaml code to preferred_packages
    * Add validation check and a test for packages.py parsing.
    * flake8
```

I don't believe any of my innovations are affecting this problem.  A
summary of all changes can be found at:

https://github.com/LLNL/spack/pull/2490/files

**Comment by alalazo** [comment] 2017-02-08 19:23
I tried to reproduce modifying `szip` in `develop` to contain:
```python
variant('python', default=True, description='')
extends('python', when='+python')
```
but couldn't reproduce:
```console
$ spack install python # This needs to be installed for real
...
$ spack install --fake szip
==> Installing szip
==> python is already installed in /home/mculpo/PycharmProjects/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/python-2.7.13-yypjawdznorcqm34udm2vwb6apvvlsqa
==> Building szip [AutotoolsPackage]
==> Successfully installed szip
  Fetch: .  Build: 0.16s.  Total: 0.16s.
[+] /home/mculpo/PycharmProjects/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/szip-2.1-nx4mibwub3yabcseyksylzcal5kqobzi

$ cp share/spack/modules/linux-ubuntu14-x86_64/szip-2.1-gcc-4.8-nx4mibw orig.mod

$ spack module refresh szip
==> You are about to regenerate tcl module files for:

-- linux-ubuntu14-x86_64 / gcc@4.8 ------------------------------
nx4mibw szip@2.1

==> Do you want to proceed ? [y/n]
y
==> Regenerating tcl module files

$ diff share/spack/modules/linux-ubuntu14-x86_64/szip-2.1-gcc-4.8-nx4mibw orig.mod
2c2
< ## Module file created by spack (https://github.com/LLNL/spack) on 2017-02-08 20:18:39.996192
---
> ## Module file created by spack (https://github.com/LLNL/spack) on 2017-02-08 20:18:15.717894

```
By the way: do you see the query:
```console
==> Do you want to proceed ? [y/n]
```
when you try to refresh?

**Comment by citibeth** [comment] 2017-02-08 19:27
> By the way: do you see the query:

yes

On Wed, Feb 8, 2017 at 2:23 PM, Massimiliano Culpo <notifications@github.com

**Comment by citibeth** [comment] 2017-02-08 19:43
> I tried to reproduce modifying szip in develop to contain:

I'll bet you need a `setup_environment()` method.  My program is basically a CMake-based C++ library; along with a Python interface.  The Python interface is built/installed with CMake, not setuptools.

Apparently, once I write `extends('python')`, `$PATH` disappears from my module.  I added `setup_environment()` to add it back.  It feels hacky, and I'm not at all convinced it's the "right" solution.  However, it should also not be triggering this bug...

**Comment by alalazo** [comment] 2017-02-08 21:59
Tried to add:
```python
def setup_environment(self, senv, renv):
    renv.prepend_path('PATH', 'something')
```
still no luck in reproducing:
```console
$ cp share/spack/modules/linux-ubuntu14-x86_64/szip-2.1-gcc-4.8-nx4mibw orig.mod

$ spack module refresh szip
==> You are about to regenerate tcl module files for:

-- linux-ubuntu14-x86_64 / gcc@4.8 ------------------------------
nx4mibw szip@2.1

==> Do you want to proceed ? [y/n]
y
==> Regenerating tcl module files

$ diff share/spack/modules/linux-ubuntu14-x86_64/szip-2.1-gcc-4.8-nx4mibw orig.mod
2c2
< ## Module file created by spack (https://github.com/LLNL/spack) on 2017-02-08 22:56:55.249268
---
> ## Module file created by spack (https://github.com/LLNL/spack) on 2017-02-08 22:56:30.375786
```

**Comment by alalazo** [comment] 2017-07-15 12:19
I am closing this issue as I cannot reproduce the problem. If you can find a series of steps that systematically show the problem, feel free to post them and reopen.

**Closed by alalazo** 2017-07-15 12:19 UTC
Labels: bug, modules
