### ISSUE TITLE
new concretizer issue with paraview package

### ISSUE THREAD

**Issue by Nandinihpc** [LLNL/spack#23008] opened 2021-04-15 16:05 UTC
But using new concetizer this is the new error with paraview
spack concretize -f
==> Error: invalid values for variant "cuda_arch" in package "paraview": ['10']
Let me know the fix please. thanks

**Comment by adamjstewart** [comment] 2021-04-15 17:04
@chuckatkins @danlipsa @vicentebolea are our `paraview` package maintainers.

The issue is that the package inherits from the `CudaPackage` base class, which contains things like:
```python
    depends_on('cuda@:6.0',     when='cuda_arch=10')                                     
```
but overrides the `cuda_arch` variant like so:
```python
    variant('cuda_arch', default='native', multi=False,                                  
            values=('native', 'fermi', 'kepler', 'maxwell',                              
                    'pascal', 'volta', 'turing', 'ampere', 'all', 'none'),               
            description='CUDA architecture') 
```
The solution would be one of the following:

1. Don't inherit from `CudaPackage`, which requires a `+cuda` variant and dependencies/conflicts, or
2. Don't override the `cuda_arch` variant, which requires the default values to be mapped to what the package expects

Personally I recommend solution 2, but 1 is also acceptable. @chuckatkins @danlipsa @vicentebolea can one of you submit a PR to fix this issue discovered by the new concretizer?

**Comment by vicentebolea** [comment] 2021-04-15 17:09
This was also reported here https://github.com/spack/spack/issues/22970.

Fixes also being discussed there

**Comment by Nandinihpc** [comment] 2021-04-15 18:02
the problem is before installing new concretizer i have openfoam with paraview installed.  And the server that i have built openfoam doesnt have GPU so i have not added cuda variant at all to my built process. For non GPU server let me know the fix which doesnt need cuda packages at all.

**Comment by Nandinihpc** [comment] 2021-04-16 21:31
thanks that fixes the paraview issue.

**Comment by sethrj** [comment] 2021-08-11 19:11
See also https://github.com/spack/spack/pull/20623#issuecomment-879226388

**Comment by vicentebolea** [comment] 2021-08-18 00:04
The resolution was just merged at https://github.com/spack/spack/pull/23257. Closing this.

**Closed as completed by vicentebolea** 2021-08-18 00:04 UTC
Labels: bug, concretization
