### ISSUE TITLE
problem parsing url for hwloc

### ISSUE THREAD

**Issue by cyrush** [LLNL/spack#32503] opened 2022-09-02 23:30 UTC
### Steps to reproduce

Spack install of openmpi on macOS using -k.

OpenMPI is dependency of larger tree for me, but this should do the trick:

```
spack/bin/spack -k install openmpi
```

### Error message

During spack's fetch it tries to construct the proper version via a few failed attempts, including:

https://download.open-mpi.org/release/hwloc/v2.0/hwloc-2.8.0.tar.gz

Note: that `v2.0` should be `v2.8`,  but spack doesn't know that so it invokes spider mode:

```
==> [2022-09-01-12:44:42.102923] SPIDER: [depth=0, max_depth=2, urls=3]
==> [2022-09-01-12:44:42.181879] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)>
==> [2022-09-01-12:44:42.182812] Warning: Spack was unable to fetch url list due to a certificate verification problem. You can try running spack -k, which will not check SSL certificates. Use this at your own risk.
==> [2022-09-01-12:44:42.183845] SPIDER: [url=ParseResult(scheme='http', netloc='www.open-mpi.org', path='/software/hwloc/', params='', query='', fragment=None)]
==> [2022-09-01-12:44:42.296220] HTTP Error 403: Forbidden
==> [2022-09-01-12:44:42.297108] SPIDER: [url=ParseResult(scheme='https', netloc='download.open-mpi.org', path='/release/hwloc/v2.0', params='', query='', fragment=None)]
==> [2022-09-01-12:44:42.299018] HTTP Error 403: Forbidden
==> [2022-09-01-12:44:42.299866] SPIDER: [url=ParseResult(scheme='https', netloc='download.open-mpi.org', path='/release/hwloc/v2.0/', params='', query='', fragment=None)]
==> [2022-09-01-12:44:42.300701] SPIDER: [depth=1, max_depth=2, urls=0]
==> [2022-09-01-12:44:42.301512] SPIDER: [depth=2, max_depth=2, urls=0]
==> [2022-09-01-12:44:42.306127] KeyError: VersionBase('2.8.0')
==> [2022-09-01-12:44:42.306804] Cannot find version 2.8.0 in url_list
```
(Side note, I am using `-k` not sure if that is used by the spider command)

These all fail with forbidden, which dooms the download. 

For whatever reason -  fetching from the spack mirror fails as well (but I can download from there just fine)
```
==> [2022-09-01-12:44:42.307512] Fetching from https://mirror.spack.io/_source-cache/archive/20/20b2bd4df436827d8e50f7afeafb6f967259f2fb374ce7330244f8d0ed2dde6f.tar.gz failed.
==> [2022-09-01-12:44:42.308122] Fetching from https://mirror.spack.io/hwloc/hwloc-2.8.0.tar.gz failed.
==> [2022-09-01-12:44:42.308808] Fetching from http://www.open-mpi.org/software/hwloc/v2.8/downloads/hwloc-2.8.0.tar.gz failed.
==> [2022-09-01-12:44:42.326849] Error: FetchError: All fetchers failed for spack-stage-hwloc-2.8.0-qw5hsym4lfrplnk7iq4ltelrfdhz77vv
```
These fallback don't save me. 

If I change the direct url to the exact version -- spack fetch still does not work.

For whatever reason the openmpi website really doesn't like the spack fetch approach.
(every other tarball works fine with `-k`, and I can download the valid hwloc urls fine with my web browser)

Full install debug :

```
==> [2022-09-01-12:44:39.676210] Installing hwloc-2.8.0-qw5hsym4lfrplnk7iq4ltelrfdhz77vv
==> [2022-09-01-12:44:39.676292] Searching for binary cache of hwloc-2.8.0-qw5hsym4lfrplnk7iq4ltelrfdhz77vv
==> [2022-09-01-12:44:40.219023] No binary for hwloc-2.8.0-qw5hsym4lfrplnk7iq4ltelrfdhz77vv found: installing from source
==> [2022-09-01-12:44:40.219365] Creating the installation directory /Users/harrison37/Work/alpine/ascent/build/spack/opt/spack/darwin-catalina-skylake/apple-clang-11.0.1/hwloc-2.8.0-qw5hsym4lfrplnk7iq4ltelrfdhz77vv
==> [2022-09-01-12:44:40.223490] '/usr/local/bin/git' '-C' '/Users/harrison37/Work/alpine/ascent/build/spack' 'rev-parse' 'HEAD'
==> [2022-09-01-12:44:40.592113] [TOOLCHAIN] MATCH Aocc
==> [2022-09-01-12:44:40.592992] [TOOLCHAIN] MATCH AppleClang
==> [2022-09-01-12:44:40.593720] [TOOLCHAIN] MATCH Clang
==> [2022-09-01-12:44:40.594670] [TOOLCHAIN] MATCH Gcc
==> [2022-09-01-12:44:40.595708] [TOOLCHAINS] {'Clang', 'Aocc', 'AppleClang', 'Gcc'}
==> [2022-09-01-12:44:40.596629] microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check apple-clang@11.0.1 for further details]
==> [2022-09-01-12:44:40.602408] Adding compiler bin/ paths: /Users/harrison37/Work/alpine/ascent/build/spack/lib/spack/env /Users/harrison37/Work/alpine/ascent/build/spack/lib/spack/env/case-insensitive /Users/harrison37/Work/alpine/ascent/build/spack/lib/spack/env/clang
==> [2022-09-01-12:44:40.729253] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> [2022-09-01-12:44:40.732276] '/usr/bin/clang++' '-v' '/var/folders/wj/jjhjt_0d3kg1vmk56d5bq_38001kr8/T/spack-implicit-link-infoj43znfnd/main.c' '-o' '/var/folders/wj/jjhjt_0d3kg1vmk56d5bq_38001kr8/T/spack-implicit-link-infoj43znfnd/output'
==> [2022-09-01-12:44:41.140079] parsing implicit link info
==> [2022-09-01-12:44:41.141149] linker line:  "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -no_deduplicate -dynamic -arch x86_64 -macosx_version_min 10.15.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -o /var/folders/wj/jjhjt_0d3kg1vmk56d5bq_38001kr8/T/spack-implicit-link-infoj43znfnd/output /var/folders/wj/jjhjt_0d3kg1vmk56d5bq_38001kr8/T/main-0a2464.o -lc++ -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/lib/darwin/libclang_rt.osx.a
==> [2022-09-01-12:44:41.141925] found raw link dirs: 
==> [2022-09-01-12:44:41.142790] found link dirs: 
==> [2022-09-01-12:44:41.149399] Checking existence of https://mirror.spack.io/_source-cache/archive/20/20b2bd4df436827d8e50f7afeafb6f967259f2fb374ce7330244f8d0ed2dde6f.tar.gz
==> [2022-09-01-12:44:41.320248] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/_source-cache/archive/20/20b2bd4df436827d8e50f7afeafb6f967259f2fb374ce7330244f8d0ed2dde6f.tar.gz
==> [2022-09-01-12:44:41.321708] Checking existence of https://mirror.spack.io/hwloc/hwloc-2.8.0.tar.gz
==> [2022-09-01-12:44:41.489775] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/hwloc/hwloc-2.8.0.tar.gz
==> [2022-09-01-12:44:41.491613] Checking existence of http://www.open-mpi.org/software/hwloc/v2.8/downloads/hwloc-2.8.0.tar.gz
==> [2022-09-01-12:44:41.799166] Checking existence of https://download.open-mpi.org/release/hwloc/v2.0/hwloc-2.8.0.tar.gz
==> [2022-09-01-12:44:42.075608] FailedDownloadError: Failed to fetch file from URL: https://download.open-mpi.org/release/hwloc/v2.0/hwloc-2.8.0.tar.gz
==> [2022-09-01-12:44:42.102923] SPIDER: [depth=0, max_depth=2, urls=3]
==> [2022-09-01-12:44:42.181879] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)>
==> [2022-09-01-12:44:42.182812] Warning: Spack was unable to fetch url list due to a certificate verification problem. You can try running spack -k, which will not check SSL certificates. Use this at your own risk.
==> [2022-09-01-12:44:42.183845] SPIDER: [url=ParseResult(scheme='http', netloc='www.open-mpi.org', path='/software/hwloc/', params='', query='', fragment=None)]
==> [2022-09-01-12:44:42.296220] HTTP Error 403: Forbidden
==> [2022-09-01-12:44:42.297108] SPIDER: [url=ParseResult(scheme='https', netloc='download.open-mpi.org', path='/release/hwloc/v2.0', params='', query='', fragment=None)]
==> [2022-09-01-12:44:42.299018] HTTP Error 403: Forbidden
==> [2022-09-01-12:44:42.299866] SPIDER: [url=ParseResult(scheme='https', netloc='download.open-mpi.org', path='/release/hwloc/v2.0/', params='', query='', fragment=None)]
==> [2022-09-01-12:44:42.300701] SPIDER: [depth=1, max_depth=2, urls=0]
==> [2022-09-01-12:44:42.301512] SPIDER: [depth=2, max_depth=2, urls=0]
==> [2022-09-01-12:44:42.306127] KeyError: VersionBase('2.8.0')
==> [2022-09-01-12:44:42.306804] Cannot find version 2.8.0 in url_list
==> [2022-09-01-12:44:42.307512] Fetching from https://mirror.spack.io/_source-cache/archive/20/20b2bd4df436827d8e50f7afeafb6f967259f2fb374ce7330244f8d0ed2dde6f.tar.gz failed.
==> [2022-09-01-12:44:42.308122] Fetching from https://mirror.spack.io/hwloc/hwloc-2.8.0.tar.gz failed.
==> [2022-09-01-12:44:42.308808] Fetching from http://www.open-mpi.org/software/hwloc/v2.8/downloads/hwloc-2.8.0.tar.gz failed.
==> [2022-09-01-12:44:42.326849] Error: FetchError: All fetchers failed for spack-stage-hwloc-2.8.0-qw5hsym4lfrplnk7iq4ltelrfdhz77vv
```

### Information on your system

* **Spack:** 0.19.0.dev0 (62e4177e445719189ea9b90ac91e18eff157ddfa)
* **Python:** 3.7.3
* **Platform:** darwin-catalina-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by cyrush** [comment] 2022-09-07 20:25
More info:

It consistently fails with spack's `urllib` (default) fetch option, but using `curl` I was able to to download hwloc and build. 

If folks have advice on how to get to the bottom of the fetch issue, I am happy to experiment a bit more.

**Comment by kuberry** [comment] 2022-09-16 12:29
This really looks like an SSL issue from the warnings, but I don't believe it is. The direct link to the resource is at: `https://download.open-mpi.org/release/hwloc/v2.0/hwloc-2.8.0.tar.gz` which is giving `403 Forbidden` errors.

I had no success downloading version 2.8.0 of hwloc so I switched to requesting `^2.7.1` which can succeed because it is older and is cached (direct link for 2.7.1 also doesn't work).

This seems like an issue with `download.open-mpi.org`. 

Should a different server be considered for providing `hwloc` software (it seems pretty central to most builds)? @tgamblin

**Comment by cyrush** [comment] 2022-09-16 18:40
@kuberry 
I agree something is different related to `download.open-mpi.org.

The right url should be `https://download.open-mpi.org/release/hwloc/v2.8/hwloc-2.8.0.tar.gz`.

Based on the details in the package.py, Spack doens't know this info at first.

The issue is when spack's extra logic to search around (which is normally robust) hits some barriers talking to the server with `urllib` in an attempt to sort out the right url. 

Things worked OK for me when I switched to curl. -- so there is something with the urllib usage that `download.open-mpi.org` is unhappy with.

**Comment by kuberry** [comment] 2022-09-19 12:20
@cyrush I can confirm that `https://download.open-mpi.org/release/hwloc/v2.8/hwloc-2.8.0.tar.gz` works using wget/curl directly, but **not** `https://download.open-mpi.org/release/hwloc/v2.0/hwloc-2.8.0.tar.gz` (which is the address Spack has resolved).

**Comment by kuberry** [comment] 2022-09-20 20:53
in `lib//spack/spack/util/web.py`, in function `def read_from_url(url, accept_content_type=None):`,
there is a conditional:

```py
    # Don't even bother with a context unless the URL scheme is one that uses
    # SSL certs.
    if uses_ssl(url):
        if verify_ssl:
            if __UNABLE_TO_VERIFY_SSL:
                # User wants SSL verification, but it cannot be provided.
                warn_no_ssl_cert_checking()
            else:
                # User wants SSL verification, and it *can* be provided.
                context = ssl.create_default_context()  # novm
        else:
            # User has explicitly indicated that they do not want SSL
            # verification.
            if not __UNABLE_TO_VERIFY_SSL:
                context = ssl._create_unverified_context()
```

Because `hwloc` uses `list_url = "http://www.open-mpi.org/software/hwloc/"` with 
```py
    def url_for_version(self, version):
        return "http://www.open-mpi.org/software/hwloc/v%s/downloads/hwloc-%s.tar.gz" % (
            version.up_to(2),
            version,
        )
```
, both using `http protocol`, the url is treated as http and so ` if uses_ssl(url)` is False, no Context is created for an SSL connection, and an SSL error is produced.

This problem likely exists for all `http` addresses that are redirected to `https` for all packages.  
One solution is to patch `hwloc` to use `https` rather than `http` for `list_url` and `url_for_version`. I've tested this and it works fine. Another option is to fix web.py to handle `https` redirects from `http`.

**Comment by cyrush** [comment] 2022-09-20 20:58
Nice work diving deep on this!

**Comment by kuberry** [comment] 2022-09-29 12:28
Hello @cyrush. Now that the fix is in, would you mind checking if it solved your `hwloc` issue?

**Closed as completed** 2022-10-11 12:18 UTC
Labels: bug, triage
