### ISSUE TITLE
spack.yaml comment reformatting adds newlines

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#31091] opened 2022-06-10 20:35 UTC
### Steps to reproduce

1. Create a new environment
2. Add comments to the `spack.yaml` file
3. Any command like `spack install` or `spack add` will reformat this file and add extra newlines

There are two bugs here:

* `spack install` should never modify `spack.yaml` at all
* `spack add` should only add packages, it shouldn't add extra newline chars

It seems like `spack install` adds 2 newlines per comment, while `spack add` only adds 1 newline per comment. This bug is additive. If you run these commands multiple times, you'll end up with a file that is more newlines than actual lines.

I believe @scheibelp has helped me fix issues like this in the past and should know where to look.

### Error message

N/A

### Information on your system

* **Spack:** 0.19.0.dev0 (bedad508a92fbfacc09316839f5d47c7e339e237)
* **Python:** 3.9.12
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by iarspider** [comment] 2022-06-11 08:52
Not sure if it's related or not, but this I also observe inline comments to migrating around - i.e. moving to an unrelated line

**Comment by sethrj** [comment] 2022-06-11 11:13
Yep I've seen this forever. Every new environment concretization makes my YAML file longer 😂  I know @haampie has complained about this too ;)

**Comment by blue42u** [comment] 2022-06-12 16:12
Not sure if it's related, but I've also had my view path become absolute when the environment concertizes. (Makes it tricky to share some of my environments over Git.)

**Comment by adamjstewart** [comment] 2022-06-19 04:26
Related to #11602

**Comment by adamjstewart** [comment] 2023-03-20 00:01
Duplicate of #24885, but contains steps to reproduce so we should probably keep this one open instead.

Just wanted to say that this issue is still present in develop.

**Comment by alalazo** [comment] 2023-04-07 10:36
Can reproduce. Also, some comments disappear:
![Screenshot from 2023-04-07 12-36-12](https://user-images.githubusercontent.com/4199709/230594601-a41f969f-58e5-41d0-a410-c86e521a5638.png)

**Comment by alalazo** [comment] 2023-04-07 15:30
This is related https://stackoverflow.com/questions/42172399/modifying-yaml-using-ruamel-yaml-adds-extra-new-lines

**Comment by alalazo** [comment] 2023-04-07 16:08
Smaller reproducer so far. Using this YAML file:
```yaml
spack:
  specs:
  # baz
  - zlib

```
and:
```python
Spack version 0.20.0.dev0
Python 3.8.10, Linux x86_64
>>> import sys
>>> import ruamel.yaml
>>> with open("spack.yaml") as f:
...     data = ruamel.yaml.load(f, Loader=ruamel.yaml.RoundTripLoader)
... 
>>> data
CommentedMap([('spack', CommentedMap([('specs', ['zlib'])]))])
>>> ruamel.yaml.dump(data, sys.stdout, Dumper=ruamel.yaml.RoundTripDumper)
spack:
  specs:
  
  # baz
  - zlib


```
so it might be a known bug from our vendored `ruamel.yaml` v0.11.15 from 2016

**Comment by alalazo** [comment] 2023-04-07 16:10
Same experiment with the latest version of the library:
```python
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import ruamel.yaml
>>> with open("/tmp/issues/spack.yaml.orig.1") as f:
...     data = ruamel.yaml.load(f, Loader=ruamel.yaml.RoundTripLoader)
... 
>>> data
ordereddict([('spack', ordereddict([('specs', ['zlib'])]))])
>>> ruamel.yaml.dump(data, sys.stdout, Dumper=ruamel.yaml.RoundTripDumper)
spack:
  specs:
  # baz
  - zlib

>>> 
```

**Comment by alalazo** [comment] 2023-04-07 16:19
So to solve this issue we need to be able to update our vendored `ruamel.yaml` which might be difficult due to how tied we are on its internals. @tgamblin FYI

**Comment by alalazo** [comment] 2023-04-07 20:40
Also related to #8081

**Comment by tgamblin** [comment] 2023-04-07 23:35
@alalazo I don't think there's anything that ties us particularly strongly to the internals.  The only patches to the library are two for 2.6 support and pyqver that can just be ignored/overwritten, then there is yours for Python 3.10 support in 40a40e0265. I don't think any of those patches need to be carried over.  

`spack_yaml` relies on overriding a few standard methods (i.e. standard in the sense that they're loader methods, not ruamel-specific methods) form `RoundTripLoader`. Those methods just add our own line info on top of the (worse) line info that ruamel has.  We should keep the changes in `OrderedLineLoader` unless something major has changed in Ruamel's line tracking that we don't need our own anymore.  In particular, AFAIK Ruamel doesn't have the fine-grained attribution for dict keys that we need for `spack blame`.  This stuff is only like 25 lines of code -- I suspect it'll just keep working.

**Comment by alalazo** [comment] 2023-04-08 07:44
I wrote that comment after having a branch in which I tried to just update the library. 

The `ruamel.yaml` internal hierarchy changed, see [here](https://yaml.readthedocs.io/en/latest/api.html). I can't find clear documentation, apart from reading ruamel code (quite "complicated" tbh). Using the old API kind of works after a few tweaks but:
1. We need to silence warnings about using a deprecated interface
2. We actually delete comment when changing spack.yaml files (I still need to solve this)

The `Mark` class turned into multiple different classes, so maybe that's part of the issue I see. I'll check that. Also there are around 10 files in which we use `ruamel.yaml` directly, and I think those should route through our wrapper `spack_yaml` module, so that in the future we'll have a single place to change and look at when dealing with the YAML 3rd party library we use.

**Comment by alalazo** [comment] 2023-04-08 12:45
Leaving a reference that, while trying to get a sense of the latest [ruamel.yaml](https://sourceforge.net/projects/ruamel-yaml/), I am also trying to check if [strictyaml](https://hitchdev.com/strictyaml/) can be a possible substitute. From what I read it preserves comments too, and seems much more maintained.

EDIT: after a short read `strictyaml` should offer the functionality we need too. One part that would need consideration, in case, is YAML validation - since `strictyaml` has its own type of schema that need to be written in code (not an issue), is different from JSON schema (see [here](https://hitchdev.com/strictyaml/why-not/json-schema/)) and is used to determine the type of objects when reading a document (to avoid the Norway issue).

EDIT 2: `strictyaml` is literally based on `ruamel` see https://github.com/crdoconnor/strictyaml/tree/master/strictyaml - so it won't make the inner structure better.

**Comment by alalazo** [comment] 2023-04-08 13:47
So, matching name of the methods it seems that, at least for us:
- `Loader` -> `Constructor`
- `Dumper` -> `Representer`

Doing a first adjustment I get this:
```
Traceback (most recent call last):
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/config.py", line 706, in print_section
    syaml.dump_config(data, stream=sys.stdout, default_flow_style=False, blame=blame)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/util/spack_yaml.py", line 326, in dump_config
    return handler.dump(data, stream)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/util/spack_yaml.py", line 305, in dump
    return self.yaml.dump(data, stream=stream, transform=transform)
  File "/home/culpo/PycharmProjects/spack/lib/spack/external/_vendoring/ruamel/yaml/main.py", line 574, in dump
    return self.dump_all([data], stream, transform=transform)
  File "/home/culpo/PycharmProjects/spack/lib/spack/external/_vendoring/ruamel/yaml/main.py", line 583, in dump_all
    self._context_manager.dump(data)
  File "/home/culpo/PycharmProjects/spack/lib/spack/external/_vendoring/ruamel/yaml/main.py", line 915, in dump
    self._yaml.representer.represent(data)
  File "/home/culpo/PycharmProjects/spack/lib/spack/external/_vendoring/ruamel/yaml/representer.py", line 80, in represent
    node = self.represent_data(data)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/util/spack_yaml.py", line 179, in represent_data
    result = super().represent_data(data)
  File "/home/culpo/PycharmProjects/spack/lib/spack/external/_vendoring/ruamel/yaml/representer.py", line 113, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/home/culpo/PycharmProjects/spack/lib/spack/external/_vendoring/ruamel/yaml/representer.py", line 354, in represent_undefined
    raise RepresenterError(_F('cannot represent an object: {data!s}', data=data))
ruamel.yaml.representer.RepresenterError: cannot represent an object: {'config': {'debug': True, 'install_tree': ordereddict([('root', '$spack/opt/spack'), ('projections', ordereddict([('all', '{architecture}/{compiler.name}-{compiler.version}/{name}-{version}-{hash}')]))]), 'template_dirs': ['$spack/share/spack/templates'], 'license_dir': '$spack/etc/spack/licenses', 'build_stage': ['$tempdir/$user/spack-stage', '$user_cache_path/stage'], 'test_stage': '$user_cache_path/test', 'source_cache': '$spack/var/spack/cache', 'misc_cache': '$user_cache_path/cache', 'connect_timeout': 10, 'verify_ssl': True, 'suppress_gpg_warnings': False, 'install_missing_compilers': False, 'checksum': True, 'deprecated': False, 'dirty': False, 'build_language': 'C', 'locks': True, 'url_fetch_method': 'urllib', 'ccache': False, 'concretizer': 'clingo', 'db_lock_timeout': 60, 'package_lock_timeout': None, 'shared_linking': ordereddict([('type', 'rpath'), ('bind', False)]), 'allow_sgid': True, 'terminal_title': False, 'binary_index_ttl': 600, 'flags': ordereddict([('keep_werror', 'none')]), 'build_jobs': 8}}
```
Investigating further...

**Comment by tgamblin** [comment] 2023-04-10 20:47
IMO, strictyaml would be good. I thought I’d looked at it in the past and it required ruamel. I’m either thinking of another project or that’s changed — looks like it only requires date util?

**Comment by blue42u** [comment] 2023-04-10 21:12
I would have concerns if Spack switched to strictyaml, it implements a sub-dialect of YAML with a number of (they claim "bad") features removed. Personally, I'd like to continue using YAML anchors in my `ci.yaml` configuration.

**Comment by alalazo** [comment] 2023-04-11 13:31
Concerning the comments being stripped when I update the version of `ruamel.yaml`, here's the issue:

https://github.com/spack/spack/blob/1c3961bdd04bcaea533ce4d23e213b879a90fef4/lib/spack/spack/environment/environment.py#L2205

`ruamel.yaml` change where the `CommentToken` gets appended at some point, so copying a `speclist` make us lose all the comments associated with an item in the list.

> I thought I’d looked at it in the past and it required ruamel. I’m either thinking of another project or that’s changed — looks like it only requires date util?

It requires `ruamel`, but vendors it - see EDIT 2 in https://github.com/spack/spack/issues/31091#issuecomment-1500884733 I think there would be both pros and cons if we decide later to switch. Pros are that the project seems better maintained and validates the yaml files as it parses them (so we won't lose information on the place a schema validation fails), but on the other hand it makes some restrictive (and controversial?) assumptions on the YAML dialect and requires some change to schema code.

**Comment by alalazo** [comment] 2023-04-14 15:05
Another update that causes troubles, this time with Spack view:
```console
(tmp.Z45ZYD3oS0) culpo@nivola:~/github/spack$ cat /tmp/spack-ckejja8j/spack.yaml 
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs: []
  view:
    foo:
      # foo      
      root: /tmp/foo/view
      # bar
      link_type: symlink
      # baz
  concretizer:
    unify: true
(tmp.Z45ZYD3oS0) culpo@nivola:~/github/spack$ spack env view enable
(tmp.Z45ZYD3oS0) culpo@nivola:~/github/spack$ cat /tmp/spack-ckejja8j/spack.yaml 
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs: []
  view:
    foo:
      root: /tmp/foo/view
      link_type: symlink
    default:
      root: /tmp/spack-ckejja8j/.spack-env/view
      link_type: symlink
  concretizer:
    unify: true
```
For what is worth I'm trying to work on a fix by refactoring some code, but it's taking longer than I would have expected :sweat:

**Closed as completed** 2023-05-04 15:00 UTC
Labels: bug, user-experience, environments, triage
