### ISSUE TITLE
new concretizer issue with lammps adios dependency

### ISSUE THREAD

**Issue by Nandinihpc** [LLNL/spack#23052] opened 2021-04-16 21:34 UTC
The new concretizer is having issue with lammps dependency adios.

spack concretize -f
==> Error: variant "adios" not found in package "lammps"

Let me know the fix please.

**Comment by alalazo** [comment] 2021-04-20 13:44
Duplicate of #23126

**Closed as completed by alalazo** 2021-04-20 13:44 UTC
Labels: bug, triage
