### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-9: ordinal not in range(128)

### ISSUE THREAD

**Issue by pattakosn** [LLNL/spack#18536] opened 2020-09-07 10:37 UTC
### Steps to reproduce the issue
```console
spack install hdf5 %intel
[some@where ~]$ spack install hdf5 %intel
==> intel-mpi@2018.3.222 : externally installed in /opt/intel/impi/2018.3.222
[+] /opt/intel/impi/2018.3.222
==> Installing zlib
==> No binary for zlib found: installing from source
==> Error: UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-9: ordinal not in range(128)

/nfs-mnt/user-home/some/spack/lib/spack/spack/build_environment.py:863, in child_process:
860 tb_string = traceback.format_exc()
861
862 # build up some context from the offending package so we can
>> 863 # show that, too.
864 package_context = get_package_context(tb)
865
866 build_log = None


==> Warning: Skipping build of hdf5 since zlib failed
==> Error: Installation of hdf5 failed. Review log for details
```

### Information on your system

*Spack:** 0.15.4
*Python:** 2.7.5
*Platform:** linux-centos7-broadwell

```python
packages:
    intel-mpi:
        externals:
        - spec: intel-mpi@2018.3.222
        prefix: /opt/intel/impi/2018.3.222
    buildable: false
```
### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

@lrknox

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment] 2020-09-07 17:59
This looks like a Spack issue, not an hdf5 issue. Can you run `spack --debug install zlib` and post the output?

@scheibelp @tgamblin

**Comment by pattakosn** [comment] 2020-09-08 10:20
Hi, sure, here it is:
```terminal
[some@where ~]$ spack --debug install hdf5 %intel ^intel-mpi
==> [2020-09-08-16:53:39.569690] Imported install from built-in commands
==> [2020-09-08-16:53:39.573079] Reading config file /nfs-mnt/user-home/some/spack/etc/spack/defaults/config.yaml
==> [2020-09-08-16:53:39.619830] Imported install from built-in commands
==> [2020-09-08-16:53:39.625356] Reading config file /nfs-mnt/user-home/some/spack/etc/spack/defaults/repos.yaml
==> [2020-09-08-16:53:41.414175] Reading config file /nfs-mnt/user-home/some/spack/etc/spack/defaults/packages.yaml
==> [2020-09-08-16:53:41.472450] Reading config file /nfs-mnt/user-home/some/.spack/packages.yaml
==> [2020-09-08-16:53:41.477687] Reading config file /nfs-mnt/user-home/some/.spack/linux/compilers.yaml
==> [2020-09-08-16:53:41.602164] DATABASE LOCK TIMEOUT: 3s
==> [2020-09-08-16:53:41.602301] PACKAGE LOCK TIMEOUT: No timeout
==> [2020-09-08-16:53:41.654391] Initializing the build queue for hdf5
==> [2020-09-08-16:53:41.683260] Removing failure marking for intel-mpi
==> [2020-09-08-16:53:41.733160] Removing failure marking for zlib
==> [2020-09-08-16:53:41.780222] Removing failure marking for hdf5
==> [2020-09-08-16:53:41.789258] Acquiring a write lock on intel-mpi with timeout 1e-09
==> [2020-09-08-16:53:41.803139] Creating stage lock spack-stage-intel-mpi-2019.8.254-vhkiqmno5czsa2nc6s3vbougmpex4cds
==> [2020-09-08-16:53:41.807703] Installing intel-mpi
==> [2020-09-08-16:53:41.807882] Searching for binary cache of intel-mpi
==> [2020-09-08-16:53:41.808323] Reading config file /nfs-mnt/user-home/some/spack/etc/spack/defaults/mirrors.yaml
==> [2020-09-08-16:53:41.813815] Finding buildcaches at https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache
==> [2020-09-08-16:53:41.814299] Creating stage lock build_cache
==> [2020-09-08-16:53:41.815912] Checking existence of https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/linux-centos7-broadwell-intel-18.0.3-intel-mpi-2019.8.254-vhkiqmno5czsa2nc6s3vbougmpex4cds.spec.yaml
==> [2020-09-08-16:53:41.816878] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/linux-centos7-broadwell-intel-18.0.3-intel-mpi-2019.8.254-vhkiqmno5czsa2nc6s3vbougmpex4cds.spec.yaml'
==> [2020-09-08-16:53:42.434177] FailedDownloadError: Failed to fetch file from URL: https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/linux-centos7-broadwell-intel-18.0.3-intel-mpi-2019.8.254-vhkiqmno5czsa2nc6s3vbougmpex4cds.spec.yaml
==> [2020-09-08-16:53:42.434579] Fetching from https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/linux-centos7-broadwell-intel-18.0.3-intel-mpi-2019.8.254-vhkiqmno5czsa2nc6s3vbougmpex4cds.spec.yaml failed.
==> [2020-09-08-16:53:42.437249] No binary for intel-mpi found: installing from source
==> [2020-09-08-16:53:42.599560] [TOOLCHAIN] MATCH Intel
==> [2020-09-08-16:53:42.627790] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> [2020-09-08-16:53:42.692671] '/opt/intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/icpc' '-v' '/tmp/spack-implicit-link-infoo7OPLS/main.c' '-o' '/tmp/spack-implicit-link-infoo7OPLS/output'
==> [2020-09-08-16:53:43.275230] Error: UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-9: ordinal not in range(128)

/nfs-mnt/user-home/some/spack/lib/spack/spack/build_environment.py:863, in child_process:
860 tb_string = traceback.format_exc()
861
862 # build up some context from the offending package so we can
>> 863 # show that, too.
864 package_context = get_package_context(tb)
865
866 build_log = None


Traceback (most recent call last):
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/build_environment.py", line 846, in child_process
setup_package(pkg, dirty=dirty)
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/build_environment.py", line 765, in setup_package
implicit_rpaths = pkg.compiler.implicit_rpaths()
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/compiler.py", line 361, in implicit_rpaths
link_dirs = self._get_compiler_link_paths(exe_paths)
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/compiler.py", line 411, in _get_compiler_link_paths
output=str, error=str)) # str for py2
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-9: ordinal not in range(128)
==> [2020-09-08-16:53:43.276322] Flagging intel-mpi as failed: UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-9: ordinal not in range(128)
/nfs-mnt/user-home/some/spack/lib/spack/spack/build_environment.py:863, in child_process:
860 tb_string = traceback.format_exc()
861
862 # build up some context from the offending package so we can
>> 863 # show that, too.
864 package_context = get_package_context(tb)
865
866 build_log = None

Traceback (most recent call last):
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/build_environment.py", line 846, in child_process
setup_package(pkg, dirty=dirty)
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/build_environment.py", line 765, in setup_package
implicit_rpaths = pkg.compiler.implicit_rpaths()
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/compiler.py", line 361, in implicit_rpaths
link_dirs = self._get_compiler_link_paths(exe_paths)
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/compiler.py", line 411, in _get_compiler_link_paths
output=str, error=str)) # str for py2
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-9: ordinal not in range(128)

==> [2020-09-08-16:53:43.283302] Warning: Skipping build of hdf5 since intel-mpi failed
==> [2020-09-08-16:53:43.283475] Flagging hdf5 as failed
==> [2020-09-08-16:53:43.298160] Downgrading to a read lock on intel-mpi with timeout 1e-09
==> [2020-09-08-16:53:43.305347] Acquiring a write lock on zlib with timeout 1e-09
==> [2020-09-08-16:53:43.338361] Creating stage lock spack-stage-zlib-1.2.11-b73wckxh2rm37bf66efzzmtgx4ebstoe
==> [2020-09-08-16:53:43.343587] Installing zlib
==> [2020-09-08-16:53:43.343749] Searching for binary cache of zlib
==> [2020-09-08-16:53:43.344848] Finding buildcaches at https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache
==> [2020-09-08-16:53:43.345625] Checking existence of https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/linux-centos7-broadwell-intel-18.0.3-zlib-1.2.11-b73wckxh2rm37bf66efzzmtgx4ebstoe.spec.yaml
==> [2020-09-08-16:53:43.346544] '/usr/bin/curl' '--stderr' '-' '-s' '-f' '-r' '0-0' 'https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/linux-centos7-broadwell-intel-18.0.3-zlib-1.2.11-b73wckxh2rm37bf66efzzmtgx4ebstoe.spec.yaml'
==> [2020-09-08-16:53:43.995613] FailedDownloadError: Failed to fetch file from URL: https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/linux-centos7-broadwell-intel-18.0.3-zlib-1.2.11-b73wckxh2rm37bf66efzzmtgx4ebstoe.spec.yaml
==> [2020-09-08-16:53:43.995932] Fetching from https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/build_cache/linux-centos7-broadwell-intel-18.0.3-zlib-1.2.11-b73wckxh2rm37bf66efzzmtgx4ebstoe.spec.yaml failed.
==> [2020-09-08-16:53:44.000208] No binary for zlib found: installing from source
==> [2020-09-08-16:53:44.158901] [TOOLCHAIN] MATCH Intel
==> [2020-09-08-16:53:44.187501] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> [2020-09-08-16:53:44.258094] '/opt/intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/icpc' '-v' '/tmp/spack-implicit-link-infoR_Fc_u/main.c' '-o' '/tmp/spack-implicit-link-infoR_Fc_u/output'
==> [2020-09-08-16:53:44.466137] Error: UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-9: ordinal not in range(128)

/nfs-mnt/user-home/some/spack/lib/spack/spack/build_environment.py:863, in child_process:
860 tb_string = traceback.format_exc()
861
862 # build up some context from the offending package so we can
>> 863 # show that, too.
864 package_context = get_package_context(tb)
865
866 build_log = None


Traceback (most recent call last):
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/build_environment.py", line 846, in child_process
setup_package(pkg, dirty=dirty)
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/build_environment.py", line 765, in setup_package
implicit_rpaths = pkg.compiler.implicit_rpaths()
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/compiler.py", line 361, in implicit_rpaths
link_dirs = self._get_compiler_link_paths(exe_paths)
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/compiler.py", line 411, in _get_compiler_link_paths
output=str, error=str)) # str for py2
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-9: ordinal not in range(128)
==> [2020-09-08-16:53:44.466756] Flagging zlib as failed: UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-9: ordinal not in range(128)
/nfs-mnt/user-home/some/spack/lib/spack/spack/build_environment.py:863, in child_process:
860 tb_string = traceback.format_exc()
861
862 # build up some context from the offending package so we can
>> 863 # show that, too.
864 package_context = get_package_context(tb)
865
866 build_log = None

Traceback (most recent call last):
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/build_environment.py", line 846, in child_process
setup_package(pkg, dirty=dirty)
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/build_environment.py", line 765, in setup_package
implicit_rpaths = pkg.compiler.implicit_rpaths()
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/compiler.py", line 361, in implicit_rpaths
link_dirs = self._get_compiler_link_paths(exe_paths)
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/compiler.py", line 411, in _get_compiler_link_paths
output=str, error=str)) # str for py2
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-9: ordinal not in range(128)

==> [2020-09-08-16:53:44.480930] Downgrading to a read lock on zlib with timeout 1e-09
==> [2020-09-08-16:53:44.483429] InstallError: Installation of hdf5 failed. Review log for details
==> [2020-09-08-16:53:44.483608] Error: Installation of hdf5 failed. Review log for details
Traceback (most recent call last):
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/main.py", line 762, in main
return _invoke_command(command, parser, args, unknown)
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/main.py", line 490, in _invoke_command
return_val = command(parser, args)
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/cmd/install.py", line 397, in install
install_spec(args, kwargs, abstract, concrete)
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/cmd/install.py", line 243, in install_spec
spec.package.do_install(**kwargs)
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/package.py", line 1575, in do_install
builder.install(**kwargs)
File "/nfs-mnt/user-home/some/spack/lib/spack/spack/installer.py", line 1612, in install
raise InstallError(msg)
spack.installer.InstallError: Installation of hdf5 failed. Review log for detail
```

**Comment by adamjstewart** [comment] 2020-09-08 16:41
@mathstuf @becker33 This looks like a bug in our implicit RPATH detection for compilers. But that logic seems to use `Executable`, which was updated to prevent this bug in #5077 and #10186. I'm not sure what the issue is here.

**Comment by mathstuf** [comment] 2020-09-10 14:43
Looks like something in a path or the like has non-ascii characters? @pattakosn are any paths with non-ascii characters around your spack usage?

**Comment by pattakosn** [comment] 2020-09-16 13:11
I do not know which paths you would like me to check. Which paths are you refering to?

**Comment by tepperly** [comment] 2021-03-01 19:13
I was having this same problem. One of the variables in my environment (ie., printenv) had non-ASCII characters. unset'ing that variable caused a similar error message to go away.

**Comment by alalazo** [comment] 2023-04-05 21:24
Closing, since we don't support running with Python 2 anymore.

**Closed as not planned by alalazo** 2023-04-05 21:24 UTC
Labels: bug
