### ISSUE TITLE
`sysctl: unknown oid 'machdep.cpu.model'` on arm macOS (M1)

### ISSUE THREAD

**Issue by certik** [LLNL/spack#22273] opened 2021-03-13 05:16 UTC
With the new M1 arm based macOS, I am getting:
```console
% spack install -j8 binutils
sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'
sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'
```
I am using spack git version 839af2bd700211f4f38a99f98c099f8f8c4e5a09.

**Comment by alalazo** [comment] 2021-03-20 11:56
Duplicate of #22088

**Closed as completed by alalazo** 2021-03-20 11:56 UTC
Labels: bug, triage
