### ISSUE TITLE
spack code difficult to debug because of frequent use of fork

### ISSUE THREAD

**Issue by BarrySmith** [LLNL/spack#2182] opened 2016-10-30 23:44 UTC
Because of the use of 

```
   p.start()
    exc_type, exception, traceback = parent_connection.recv()
    p.join()
    if exception is not None:
        raise exception
```

It is difficult to debug crashes in the package's code. I tried 

`./spack --pdb install package`

and it still didn't allowing debugging the inner python code.  

I understand the rational for using subprocesses for packages but is there any way to use the debugger with them? Perhaps when ./spack is run with --pdb the subprocesses are not used?

**Comment by tgamblin** [comment] 2016-10-30 23:53
This is actually a recent regression -- let me fix that.

**Comment by tgamblin** [comment] 2016-10-30 23:53
@alalazo I think this regressed in #1186

**Comment by tgamblin** [comment] 2016-10-31 00:16
oh ok it's not losing the detailed context on command failure -- it's losing regular Python exception traces that make their way back to the parent... still working

**Comment by citibeth** [comment] 2016-10-31 02:40
Would it be possible to encapsulate the way `install()` is run so it can be run in-process for debugging?

**Comment by tgamblin** [comment] 2016-10-31 02:44
@citibeth: no.  that's more complicated than the actual solution.

**Comment by alalazo** [comment] 2016-10-31 07:25
@tgamblin Just read the thread. I can actually debug any package and can't reproduce the problem  above. Don't know if it matters, but I use `pycharm` to develop, not `pdb` directly from command line.

**Comment by tgamblin** [comment] 2016-10-31 07:28
@alalazo: I'm working on a fix -- this isn't for `ProcessErrors` when a command fails -- that still seems to work pretty well and it at least gives package context.  But if there's, say, a syntax error that raises something other than a `ProcessError`, you get a traceback from `build_environment` not from the child.  I'm working on generifying the code in `spack.util.executable.ProcessError` that gets package context and moving it to `build_environment`, since it really belongs there anyway.

**Comment by alalazo** [comment] 2016-10-31 07:31
@tgamblin Ok, thanks for the update.

**Closed** 2016-10-31 22:32 UTC
