### ISSUE TITLE
CI: Concretization step silently fails 

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/spack#27865] opened 2021-12-08 19:05 UTC
### Steps to reproduce

Using the following spack generate job, no child pipelines are actually generated. The gitlab job "passes" but no pipelines are uploaded as artifacts, and the child pipeline croaks. This occurs with commit `2d45a9d617` (and all commits since), which introduced the concretization pool. This does not occur with commit `64a323b`, which is the parent of `2d45a9d617`.

```yaml
spack-generate-job:
  <<: *spack-variables
  <<: *spack-rules
  stage: spack-generate
  image: spack/ubuntu-bionic
  tags: [k8s, ikp, exasgd, basic]
  before_script:
    - git clone ${SPACK_REPO}
    - pushd spack && git checkout ${SPACK_REF} && popd
    - . "./spack/share/spack/setup-env.sh"
  script:
    - cp buildsystem/container/spack.yaml . && spack env activate --without-view .
    - spack -d ci generate
      --artifacts-root "${CI_PROJECT_DIR}/jobs_scratch_dir"
      --output-file "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/jobs_scratch_dir"
```

#### Expected Output

I expect the usual concretization output, along with all jobs for specs that need to be rebuilt uploaded as artifacts:
```console
==> [2021-12-08-18:37:29.824885] Pruning spec that does not need to be rebuilt.
==> [2021-12-08-18:37:29.880549] 17 build jobs generated in 11 stages
==> [2021-12-08-18:37:29.880590] The max_needs_job is (specs) exago/v5c656i develop gcc@7.5.0 linux-ubuntu18.04-x86_64, with 5 needs
==> [2021-12-08-18:37:29.880630] Warning: Unable to populate buildgroup without CDash credentials
==> [2021-12-08-18:37:29.882520] '/usr/bin/git' 'describe' '--tags' '--match' 'v*'
Uploading artifacts...
00:01
/builds/exasgd/frameworks/exago/jobs_scratch_dir: found 5 matching files 
Uploading artifacts to coordinator... ok            id=86300 responseStatus=201 Created token=2G4bF89d
```

#### Actual Output

The concretization output seems to be omitted and the pipeline appears to pass even though the child pipelines are not uploaded. This takes a very long time to occur.
```console
$ spack -d ci generate --artifacts-root "${CI_PROJECT_DIR}/jobs_scratch_dir" --output-file "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
... (snipped output)
==> [2021-12-06-22:14:15.564685] Starting concretization pool with 8 processes
Uploading artifacts...
00:01
/builds/exasgd/frameworks/exago/jobs_scratch_dir: found 1 matching files 
Uploading artifacts to coordinator... ok            id=86080 responseStatus=201 Created token=pQsj7GWQ
```

### Error message

The child gitlab ci pipeline fails with:
```
Found errors in your .gitlab-ci.yml:
Path `jobs_scratch_dir/pipeline.yml` does not exist inside the `spack-generate-job` artifacts archive!
You can also test your .gitlab-ci.yml in CI Lint
```

### Information on your system

Relevant snippet of `.gitlab-ci.yml`:
```yaml
stages:
  - spack-generate
  - spack-build

.spack-variables: &spack-variables
  variables:
    # We usually use develop branch or tagged version here, but using commits to identify the issue
    # 64a323b, parent commit of commit that introduced concretization pools
    # 2d45a9d617, commit that introduced conc pools
    SPACK_REF: 2d45a9d617
    SPACK_REPO: https://github.com/LLNL/spack.git
    S3_ENDPOINT_URL: http://cache.exasgd.pnl.gov

.spack-rules: &spack-rules
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - if: '$CI_COMMIT_MESSAGE =~ /\[matrix\]/'
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - *pnnl-rule # specific to our site's gitlab
    - when: manual

spack-generate-job:
  <<: *spack-variables
  <<: *spack-rules
  stage: spack-generate
  image: spack/ubuntu-bionic
  tags: [k8s, ikp, exasgd, basic]
  before_script:
    - git clone ${SPACK_REPO}
    - pushd spack && git checkout ${SPACK_REF} && popd
    - . "./spack/share/spack/setup-env.sh"
  script:
    - cp buildsystem/container/spack.yaml . && spack env activate --without-view .
    - spack -d ci generate
      --artifacts-root "${CI_PROJECT_DIR}/jobs_scratch_dir"
      --output-file "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/jobs_scratch_dir"

spack-build-job:
  <<: *spack-rules
  <<: *spack-variables
  stage: spack-build
  trigger:
    include:
      - artifact: "jobs_scratch_dir/pipeline.yml"
        job: spack-generate-job
    strategy: depend
  needs:
    - artifacts: True
      job: spack-generate-job
```

Spack environment used for `spack ci`
```yaml
spack:
  definitions:
  - pkgs:
    - exago@develop+hiop
  - rajas: ['+raja', '~raja']
  - ipopts: ['+ipopt', '~ipopt']
  - mpis: ['+mpi', '~mpi']
  - arch:
    - '%gcc@7.5.0 arch=linux-ubuntu18.04-x86_64'
  specs:
  - matrix:
    - [$pkgs]
    - [$arch]
    - [$rajas]
    - [$ipopts]
    - [$mpis]

  mirrors:
    pnnl: s3://spack-ci

  config:
    install_tree:
      padded_length: 128

  packages:
    all:
      target: [x86_64]
      providers:
        mpi: [openmpi, mpich]
    petsc:
      version: [3.14.6]
      variants: ~hypre~hdf5~metis~superlu-dist
    ipopt:
      variants: +coinhsl~mumps
      version: [3.12.10]
    hiop:
      version: [0.5.1]
    coinhsl:
      variants: +blas

  gitlab-ci:

    # the mc business is to pull proprietary tarballs so spack can build coinhsl in CI without violating licenses
    before_script:
      - unset SPACK_SIGNING_KEY
      - curl -L -s -o mc 'https://dl.min.io/client/mc/release/linux-amd64/mc'
         && chmod +x ./mc
         && ./mc alias set minio $S3_ENDPOINT_URL $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
         && ./mc cp -r minio/private/ .
      - git clone ${SPACK_REPO}
      - pushd spack && git checkout ${SPACK_CHECKOUT_VERSION} && popd
      - . "./spack/share/spack/setup-env.sh"

    script:
      - unset SPACK_SIGNING_KEY
      - pushd ${SPACK_CONCRETE_ENV_DIR} && spack env activate --without-view . && popd
      - spack -d ci rebuild

    rebuild-index: true

    service-job-attributes:
      before_script:
        - git clone ${SPACK_REPO}
        - pushd spack && git checkout ${SPACK_CHECKOUT_VERSION} && popd
        - . "./spack/share/spack/setup-env.sh"
      tags:
      - k8s
      - ikp
      - exasgd
      - basic
      image:
        name: spack/ubuntu-bionic
        entrypoint: [""]

    mappings:
    - match:
      - arch=linux-ubuntu18.04-x86_64
      runner-attributes:
        tags:
        - k8s
        - ikp
        - exasgd
        - basic
        image:
          name: spack/ubuntu-bionic
          entrypoint: [""]
```

**Comment by ashermancinelli** [comment] 2021-12-08 19:08
CC @scottwittenburg @scheibelp @tldahlgren (please cc anyone I missed)

**Comment by scottwittenburg** [comment] 2021-12-08 19:14
@ashermancinelli Based on the commit you pointed to as the one that broke things, I would think this could be reproduced more simply, without any need for a gitlab instance.  You would need to use `docker run` to get into the container where your CI jobs run, and then just activate the environment and run `spack concretize`.  If that reproduces the problem, it will be easier to diagnose and fix.  If it doesn't, then we can look into what part of the CI workflow is causing problems.

**Comment by ashermancinelli** [comment] 2021-12-08 21:18
Generating CI in a local container does concretize but gives this error:
```console
$ docker pull spack/ubuntu-bionic
$ docker run -it spack/ubuntu-bionic
$ # clone spack and checkout commit 2d45a9d617
$ spack --version
0.16.3-4933-2d45a9d617
$ spacktivate . # spack.yaml already in cwd
$ CI_PROJECT_DIR=$PWD spack -d ci generate \
     --artifacts-root "${CI_PROJECT_DIR}/jobs_scratch_dir" \
     --output-file "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
... (snipped output)
Traceback (most recent call last):
  File "/root/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/root/spack/lib/spack/spack/main.py", line 816, in main
    return _invoke_command(command, parser, args, unknown)
  File "/root/spack/lib/spack/spack/main.py", line 529, in _invoke_command
    return_val = command(parser, args)
  File "/root/spack/lib/spack/spack/cmd/ci.py", line 639, in ci
    return args.func(args)
  File "/root/spack/lib/spack/spack/cmd/ci.py", line 143, in ci_generate
    use_dependencies=use_dependencies, artifacts_root=artifacts_root)
  File "/root/spack/lib/spack/spack/ci.py", line 963, in generate_gitlab_ci_yaml
    'needs': sorted(job_dependencies, key=lambda d: d['job']),
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```
[This is the full log.](https://github.com/spack/spack/files/7678975/log.txt)

I can't tell if this is a bug already fixed in develop or an issue with my config.

I tried again with develop, finding a different issue which seems related to S3, but connecting to S3 was not an issue in the above commit:
```console
root@392c744c435b:~# spack --version
0.17.0-459-79a04605d3
root@392c744c435b:~# CI_PROJECT_DIR=$PWD spack -d ci generate      --artifacts-root "${CI_PROJECT_DIR}/jobs_scratch_dir"      --output-file "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
==> [2021-12-08-21:16:43.952903] Reading config file /root/spack/etc/spack/defaults/config.yaml
==> [2021-12-08-21:16:44.018328] Reading config file /root/spack.yaml
==> [2021-12-08-21:16:44.056542] Using environment '/root'
==> [2021-12-08-21:16:44.061046] Imported gpg from built-in commands
==> [2021-12-08-21:16:44.065782] Imported gpg from built-in commands
==> [2021-12-08-21:16:44.068297] Imported compiler from built-in commands
==> [2021-12-08-21:16:44.071800] Imported compiler from built-in commands
==> [2021-12-08-21:16:44.073820] Imported ci from built-in commands
==> [2021-12-08-21:16:44.078121] Imported ci from built-in commands
==> [2021-12-08-21:16:44.175602] Reading config file /root/spack/etc/spack/defaults/repos.yaml
==> [2021-12-08-21:16:44.280374] Reading config file /root/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-12-08-21:16:44.300061] Reading config file /root/.spack/bootstrap.yaml
==> [2021-12-08-21:16:44.304014] Deactivated environment '/root'
==> [2021-12-08-21:16:44.308716] Reading config file /root/spack/etc/spack/defaults/config.yaml
==> [2021-12-08-21:16:44.339697] DATABASE LOCK TIMEOUT: 3s
==> [2021-12-08-21:16:44.339989] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-12-08-21:16:44.341068] Reading config file /root/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-12-08-21:16:44.364130] Reading config file /root/.spack/bootstrap.yaml
==> [2021-12-08-21:16:44.368007] DATABASE LOCK TIMEOUT: 3s
==> [2021-12-08-21:16:44.368459] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-12-08-21:16:44.368652] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2021-12-08-21:16:44.369757] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/root/spack/etc/spack/defaults
==> [2021-12-08-21:16:44.369940] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/root/spack/etc/spack/defaults/linux
==> [2021-12-08-21:16:44.370019] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/root/.spack/bootstrap/config
==> [2021-12-08-21:16:44.370119] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/root/.spack/bootstrap/config/linux
==> [2021-12-08-21:16:44.371319] Reading config file /root/.spack/bootstrap/config/linux/compilers.yaml
==> [2021-12-08-21:16:44.428817] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2021-12-08-21:16:44.429162] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2021-12-08-21:16:44.429910] Reading config file /root/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-12-08-21:16:44.607605] Reading config file /root/spack/etc/spack/defaults/config.yaml
==> [2021-12-08-21:16:44.698146] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.6 /vcipwnf57slgoo7busvvkzjkk7vydeb5" provides the "clingo" Python module
==> [2021-12-08-21:16:44.699381] Reading config file /root/spack/etc/spack/defaults/config.yaml
==> [2021-12-08-21:16:44.731165] Reading config file /root/spack.yaml
==> [2021-12-08-21:16:44.774679] Using environment '/root'
==> [2021-12-08-21:16:44.838481] Reading config file /root/.spack/linux/compilers.yaml
==> [2021-12-08-21:16:45.071009] Reading config file /root/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-12-08-21:16:45.080423] Reading config file /root/.spack/bootstrap.yaml
==> [2021-12-08-21:16:45.082015] DATABASE LOCK TIMEOUT: 3s
==> [2021-12-08-21:16:45.082090] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-12-08-21:16:45.535836] View at /root/.spack-env/view does not need regeneration.
==> [2021-12-08-21:16:45.538607] Reading config file /root/spack/etc/spack/defaults/mirrors.yaml
Traceback (most recent call last):
  File "/root/spack/lib/spack/spack/util/web.py", line 556, in _urlopen
    return opener(req, *args, **kwargs)
TypeError: open() got an unexpected keyword argument 'context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/spack/bin/spack", line 98, in <module>
    sys.exit(spack.main.main())
  File "/root/spack/lib/spack/spack/main.py", line 882, in main
    return _main(argv)
  File "/root/spack/lib/spack/spack/main.py", line 865, in _main
    return _invoke_command(command, parser, args, unknown)
  File "/root/spack/lib/spack/spack/main.py", line 535, in _invoke_command
    return_val = command(parser, args)
  File "/root/spack/lib/spack/spack/cmd/ci.py", line 639, in ci
    return args.func(args)
  File "/root/spack/lib/spack/spack/cmd/ci.py", line 143, in ci_generate
    use_dependencies=use_dependencies, artifacts_root=artifacts_root)
  File "/root/spack/lib/spack/spack/ci.py", line 669, in generate_gitlab_ci_yaml
    bindist.binary_index.update()
  File "/root/spack/lib/spack/spack/binary_distribution.py", line 329, in update
    cached_mirror_url, expect_hash=cached_index_hash)
  File "/root/spack/lib/spack/spack/binary_distribution.py", line 410, in _fetch_and_cache_index
    _, _, fs = web_util.read_from_url(hash_fetch_url)
  File "/root/spack/lib/spack/spack/util/web.py", line 132, in read_from_url
    response = _urlopen(req, timeout=_timeout, context=context)
  File "/root/spack/lib/spack/spack/util/web.py", line 561, in _urlopen
    return opener(req, *args, **kwargs)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/root/spack/lib/spack/spack/s3_handler.py", line 67, in s3_open
    url, headers, stream = _s3_open(orig_url)
  File "/root/spack/lib/spack/spack/s3_handler.py", line 45, in _s3_open
    connection=s3_util.get_mirror_connection(parsed))  # noqa: E501
  File "/root/spack/lib/spack/spack/util/s3.py", line 19, in get_mirror_connection
    connection = mirror.to_dict()[url_type]
TypeError: string indices must be integers
```

Again, none of this is logged in GitLab.

**Comment by ashermancinelli** [comment] 2021-12-08 21:24
(simply running `spack concretize -f` goes through just fine)

**Comment by scottwittenburg** [comment] 2021-12-08 22:12
> ```
> $ CI_PROJECT_DIR=$PWD spack -d ci generate \
> ```

The first error (before you tried with develop) was caused because `spack ci generate` depends on the presence of a couple other environment variables.  If you can run that again with these prepended before the spack command: `CI_JOB_NAME=blah CI_PIPELINE_ID=fake ...`, and let's see what the error is after that.  I don't know what the deal is with develop there in that second stack trace.  Some things related to S3 mirrors have changed recently which caused problems for others, but I'm not sure if that's affecting you or something else.  Does that second stack trace look familiar @josephsnyder?

@ashermancinelli Does that S3 bucket (`s3://spack-ci`) live in an instance you manage, or is it on AWS?

**Comment by ashermancinelli** [comment] 2021-12-08 22:38
I manage that instance in a private k8s. I'll run the older version with those extra environment variables and report back. Thanks!

**Comment by ashermancinelli** [comment] 2021-12-08 22:54
Running with those dummy environment variables seems to work, ending with this output:
```console
...
==> [2021-12-08-22:41:59.340925]     stage 11 (4 jobs):
==> [2021-12-08-22:41:59.341363]       [x] exago/34nuwzw -> exago@develop%gcc@7.5.0  arch=linux-ubuntu18.04-x86_64
==> [2021-12-08-22:41:59.341812]       [x] exago/mxwdqod -> exago@develop%gcc@7.5.0  arch=linux-ubuntu18.04-x86_64
==> [2021-12-08-22:41:59.342307]       [x] exago/wvexxx6 -> exago@develop%gcc@7.5.0  arch=linux-ubuntu18.04-x86_64
==> [2021-12-08-22:41:59.342685]       [x] exago/zk4h7eh -> exago@develop%gcc@7.5.0  arch=linux-ubuntu18.04-x86_64
==> [2021-12-08-22:41:59.342833] 25 build jobs generated in 12 stages
==> [2021-12-08-22:41:59.343058] The max_needs_job is (specs) exago/wvexxx6 develop gcc@7.5.0 linux-ubuntu18.04-x86_64, with 9 needs
==> [2021-12-08-22:41:59.343196] Warning: Unable to populate buildgroup without CDash credentials
==> [2021-12-08-22:41:59.345615] '/usr/bin/git' 'describe' '--tags' '--match' 'v*'
```
Must be specific to gitlab ci then?

**Comment by scottwittenburg** [comment] 2021-12-08 22:58
Did it generate a pipeline yaml file?  If so, can you take that and run it through the CI Lint tool on your gitlab instance to see if it's valid?

**Comment by ashermancinelli** [comment] 2021-12-08 23:15
Yes it did, and the CI Lint tool determined the syntax is correct. [Here's the generated pipeline if that's helpful.](https://github.com/spack/spack/files/7681036/t.txt)

**Comment by scottwittenburg** [comment] 2021-12-09 04:10
Can you get a shell into one of the machines that actually runs the pipeline generation jobs (is that an instance your k8s cluster or a physical machine?) and try the same thing?  Maybe again start by just running `spack concretize` with your environment activated to make there are no problems with that, and if that works, then try `spack ci generate`.  Just spitballing here.

**Comment by ashermancinelli** [comment] 2021-12-09 17:22
I can try that, however it is just a vm in a k8s cluster using `spack/ubuntu-bionic` docker image. I'll work with my k8s sysadmin to look for red flags from the k8s side.

**Comment by scottwittenburg** [comment] 2021-12-09 17:42
One option we could consider, maybe closer to a last resort: I could try to take your `.gitlab-ci.yml` and `spack.yaml` and run them in a project on `gitlab.spack.io` and see what happens there.  Obviously, that would involve removal of anything specific to your cluster, making it a less faithful reproducer.

The combination of which commit was the problematic one with the fact that you don't see any concretization output, just makes me think it could have something to do with the underlying hardware and how it handles threading.

**Comment by ashermancinelli** [comment] 2021-12-09 17:52
> Obviously, that would involve removal of anything specific to your cluster, making it a less faithful reproducer.

I think this is actually really valuable - if it only fails on our k8s cluster, it might indicate a problem on our end that we should get to the bottom of. If you're willing to spend the time to run our setup in gitlab.spack.io, I think that would be helpful. If it's not too hard to grant someone else access, I'd be happy to do this as well. 

Alternatively, is there a config option to limit the number of procs in the _generate_ step? Or perhaps an option to disable the concretization pool?

**Comment by scottwittenburg** [comment] 2021-12-09 17:53
> Alternatively, is there a config option to limit the number of procs in the _generate_ step? Or perhaps an option to disable the concretization pool?

I'm not sure, but likely @alalazo knows whether either of those are possible.

**Comment by ashermancinelli** [comment] 2021-12-09 17:56
Looking through the spack source, it doesn't seem that disabling the concretization pool is possible, but I wouldn't mind adding that functionality myself if it's deemed useful enough.

**Comment by ashermancinelli** [comment] 2021-12-09 18:01
Resource graph from k8s for the hanging job: ![Screenshot from 2021-12-09 09-57-17](https://user-images.githubusercontent.com/30530525/145450834-aee927dd-c48e-4614-b715-e4e2b24e1561.png)

**Comment by ashermancinelli** [comment] 2021-12-09 18:03
Might `spack (ci generate|concretize) --max-nprocs=N` be in order?

**Comment by alalazo** [comment] 2023-07-10 13:02
@ashermancinelli Is this still an issue for you? For what is worth we have `spack concretize -j` since a while on `develop`:
```console
$ spack concretize -h
usage: spack concretize [-hfqU] [--test {root,all}] [--reuse] [--reuse-deps] [-j JOBS]

concretize an environment and write a lockfile

optional arguments:
  --test {root,all}     Concretize with test dependencies. When 'root' is chosen, test
                        dependencies are only added for the environment's root specs. When 'all' is
                        chosen, test dependencies are enabled for all packages in the environment.
  -f, --force           Re-concretize even if already concretized.
  -h, --help            show this help message and exit
  -j JOBS, --jobs JOBS  explicitly set number of parallel jobs
  -q, --quiet           Don't print concretized specs

concretizer arguments:
  --reuse               reuse installed packages/buildcaches when possible
  --reuse-deps          reuse installed dependencies only
  -U, --fresh           do not reuse installed deps; build newest configuration
```

**Comment by alalazo** [comment] 2024-05-21 15:10
Closing, since there has been no reply since last July. Feel free to reopen if you want to continue work on this.

**Closed as not planned by alalazo** 2024-05-21 15:10 UTC
Labels: bug, triage
