### ISSUE TITLE
Inconsistent CLI scope options for compiler and config

### ISSUE THREAD

**Issue by mwilliammyers** [LLNL/spack#1127] opened 2016-06-27 21:44 UTC
Currently you can do: `spack config --site edit <foo>` and `spack compiler --scope=site find`. In terms of selecting a scope, I think they should probably be consistent? My vote would be for `--site` or `--user` over `--scope={site,user}`...

**Comment by alalazo** [comment] 2016-06-28 08:06
@mwilliammyers I agree that the various command in spack should be as consistent as possible in their options, so :+1: to this

Concerning which one to keep, I would vote for `--scope {site,user}` as it can be easily extended to deal with scopes other than  `site` and `user` (in case any will be added in the future) or with a logic for preferences :
```
--scope site # Use only site, fail if not possible
--scope site,user # Prefer site over user
```

**Comment by mwilliammyers** [comment] 2016-06-29 00:52
@alalazo Makes sense, that is way better. I had only picked `--site` because it seemed like more people were referencing that style on GitHub, in the docs etc. I can definetly fix this but should this be a breaking change or should we keep the old syntax for a while?

**Comment by tgamblin** [comment] 2016-06-29 06:14
You could leave `--site` in as a deprecated option for now, and maybe warn that it might go away.

I'm tempted to change `--site` to `--scope spack`, as it really isn't a "site" setting so much as a "this particular spack repo" setting.  Some teams use that as a "site" setting, others use it as a "project" setting.  It depends on your use case.  I don't think we need to change it just yet, but just FYI.

**Comment by alalazo** [comment] 2016-06-29 07:02
> I'm tempted to change --site to --scope spack, as it really isn't a "site" setting so much as a "this particular spack repo" setting. Some teams use that as a "site" setting, others use it as a "per-project" setting. I don't think we need to change it just yet, but just FYI.

:+1: In the long run it could be nice to have `--scope` supporting `site` (`/etc` or similar), `project` and `user` scope

**Comment by tgamblin** [comment] 2016-06-29 07:08
> 👍 In the long run it could be nice to have --scope supporting site (/etc or similar), project and user scope

We'd like to do this for OpenHPC.  Basically allow an `/etc/spack/packages` directory with `package.yaml` files per installed RPM (like multi-file `packages.yaml`).

The idea is to allow a more "homebrew-ish" experience even on HPC machines, so that sites can give you externals that are preferred to some extent in default concretization preferences.  Only issue is that  this would be an issue for reproducible builds if done poorly, so users should be able to either turn it off or build from a complete spec instead of an abstract one.

**Comment by alalazo** [comment] 2017-01-10 14:50
@mwilliammyers Closing this because it has been fixed in develop:
```console
$ spack config --help
usage: spack config [-h]
                    [--scope {defaults,defaults/linux,site,site/linux,user,user/linux}]
                    SUBCOMMAND ...

positional arguments:
  SUBCOMMAND
    get                 Print configuration values.
    edit                Edit configuration file.

optional arguments:
  -h, --help            show this help message and exit
  --scope {defaults,defaults/linux,site,site/linux,user,user/linux}
                        Configuration scope to read/modify.

$ spack compiler find --help 
usage: spack compiler find [-h]
                           [--scope {defaults,defaults/linux,site,site/linux,user,user/linux}]
                           ...

positional arguments:
  add_paths

optional arguments:
  -h, --help            show this help message and exit
  --scope {defaults,defaults/linux,site,site/linux,user,user/linux}
                        Configuration scope to modify.
```

**Closed by alalazo** 2017-01-10 14:50 UTC
Labels: configuration
