### ISSUE TITLE
Installation issue: cannot contretize all ROCm related packages in single environment

### ISSUE THREAD

**Issue by UweSauter** [LLNL/spack#24745] opened 2021-07-07 08:58 UTC
@arjun-raj-kuppala @srekolam

### Steps to reproduce the issue

I'm trying to include all ROCm related packages into one environment so that a user only needs to load one module instead of (currently) 43. Also I want to keep the necessary installed dependencies to a minimum.

This fails because of some packages require different flags of `llvm-amdgpu` than others. Question is if this could somehow be unified?

```console
$ cd /localscratch
$ spack env create -d 2021-07-07
$ spack env activate 2021-07-07
$ cd 2021-07-07
$ echo <<EOF >>spack.yaml
spack:
  concretization: together
  packages:
    all:
      compiler: [gcc@10.3.0]
  specs:
  - matrix:
    - ['%gcc@10.3.0^cmake@3.17.5']
    - [atmi, comgr, hip, hipblas, hipcub, hipfft, hipfort, hipify-clang, hip-rocclr,
      hipsparse, hsakmt-roct, hsa-rocr-dev, llvm-amdgpu, migraphx, miopengemm, miopen-hip,
      miopen-opencl, mivisionx, rccl, rdc, rocalution, rocblas, rocfft, rocm-bandwidth-test,
      rocm-clang-ocl, rocm-cmake, rocm-dbgapi, rocm-debug-agent, rocm-device-libs,
      rocm-gdb, rocminfo, rocm-opencl, rocm-openmp-extras, rocm-smi-lib, rocm-tensile,
      rocm-validation-suite, rocprim, rocprofiler-dev, rocrand, rocsolver, rocsparse,
      rocthrust, roctracer-dev]
  view: true
  EOF
$ spack concretize
==> Error: An unsatisfiable variant constraint has been detected for spec:

    llvm-amdgpu@4.2.0%gcc@10.3.0~ipo+openmp~rocm-device-libs build_type=Release arch=linux-centos7-zen2
        ^cmake@3.17.5%gcc@10.3.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-centos7-zen2
            ^ncurses@6.2%gcc@10.3.0~symlinks+termlib abi=none arch=linux-centos7-zen2
                ^pkgconf@1.7.4%gcc@10.3.0 arch=linux-centos7-zen2
            ^openssl@1.1.1k%gcc@10.3.0~docs+systemcerts arch=linux-centos7-zen2
                ^perl@5.34.0%gcc@10.3.0+cpanm+shared+threads arch=linux-centos7-zen2
                    ^berkeley-db@18.1.40%gcc@10.3.0+cxx~docs+stl arch=linux-centos7-zen2
                    ^gdbm@1.19%gcc@10.3.0 arch=linux-centos7-zen2
                        ^readline@8.1%gcc@10.3.0 arch=linux-centos7-zen2
                ^zlib@1.2.11%gcc@10.3.0+optimize+pic+shared arch=linux-centos7-zen2
        ^hwloc
        ^libelf@0.8.13%gcc@10.3.0 arch=linux-centos7-zen2
        ^perl-data-dumper@2.173%gcc@10.3.0 arch=linux-centos7-zen2
        ^python@3.8.11%gcc@10.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-centos7-zen2
            ^bzip2@1.0.8%gcc@10.3.0~debug~pic+shared arch=linux-centos7-zen2
                ^diffutils@3.7%gcc@10.3.0 arch=linux-centos7-zen2
                    ^libiconv@1.16%gcc@10.3.0 arch=linux-centos7-zen2
            ^expat@2.3.0%gcc@10.3.0+libbsd arch=linux-centos7-zen2
                ^libbsd
            ^gettext@0.21%gcc@10.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-zen2
                ^libxml2@2.9.10%gcc@10.3.0~python arch=linux-centos7-zen2
                    ^xz@5.2.5%gcc@10.3.0~pic libs=shared,static arch=linux-centos7-zen2
                ^tar
            ^libffi@3.3%gcc@10.3.0 arch=linux-centos7-zen2
            ^sqlite@3.35.5%gcc@10.3.0+column_metadata+fts~functions~rtree arch=linux-centos7-zen2
            ^util-linux-uuid@2.36.2%gcc@10.3.0 arch=linux-centos7-zen2
        ^z3@4.8.9%gcc@10.3.0~gmp~ipo+python build_type=RelWithDebInfo arch=linux-centos7-zen2
            ^py-setuptools@44.1.0%gcc@10.3.0 arch=linux-centos7-zen2


while trying to concretize the partial spec:

    hip@4.2.0%gcc@10.3.0~ipo build_type=RelWithDebInfo arch=linux-centos7-zen2
        ^cmake@3.17.5%gcc@10.3.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-centos7-zen2
            ^ncurses@6.2%gcc@10.3.0~symlinks+termlib abi=none arch=linux-centos7-zen2
                ^pkgconf@1.7.4%gcc@10.3.0 arch=linux-centos7-zen2
            ^openssl@1.1.1k%gcc@10.3.0~docs+systemcerts arch=linux-centos7-zen2
                ^perl@5.34.0%gcc@10.3.0+cpanm+shared+threads arch=linux-centos7-zen2
                    ^berkeley-db@18.1.40%gcc@10.3.0+cxx~docs+stl arch=linux-centos7-zen2
                    ^gdbm@1.19%gcc@10.3.0 arch=linux-centos7-zen2
                        ^readline@8.1%gcc@10.3.0 arch=linux-centos7-zen2
                ^zlib@1.2.11%gcc@10.3.0+optimize+pic+shared arch=linux-centos7-zen2
        ^comgr@4.2.0%gcc@10.3.0~ipo build_type=Release arch=linux-centos7-zen2
            ^llvm-amdgpu@4.2.0%gcc@10.3.0~ipo+openmp~rocm-device-libs build_type=Release arch=linux-centos7-zen2
                ^hwloc
                ^libelf@0.8.13%gcc@10.3.0 arch=linux-centos7-zen2
                ^perl-data-dumper@2.173%gcc@10.3.0 arch=linux-centos7-zen2
                ^python@3.8.11%gcc@10.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-centos7-zen2
                    ^bzip2@1.0.8%gcc@10.3.0~debug~pic+shared arch=linux-centos7-zen2
                        ^diffutils@3.7%gcc@10.3.0 arch=linux-centos7-zen2
                            ^libiconv@1.16%gcc@10.3.0 arch=linux-centos7-zen2
                    ^expat@2.3.0%gcc@10.3.0+libbsd arch=linux-centos7-zen2
                        ^libbsd
                    ^gettext@0.21%gcc@10.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-zen2
                        ^libxml2@2.9.10%gcc@10.3.0~python arch=linux-centos7-zen2
                            ^xz@5.2.5%gcc@10.3.0~pic libs=shared,static arch=linux-centos7-zen2
                        ^tar
                    ^libffi@3.3%gcc@10.3.0 arch=linux-centos7-zen2
                    ^sqlite@3.35.5%gcc@10.3.0+column_metadata+fts~functions~rtree arch=linux-centos7-zen2
                    ^util-linux-uuid@2.36.2%gcc@10.3.0 arch=linux-centos7-zen2
                ^z3@4.8.9%gcc@10.3.0~gmp~ipo+python build_type=RelWithDebInfo arch=linux-centos7-zen2
                    ^py-setuptools@44.1.0%gcc@10.3.0 arch=linux-centos7-zen2
            ^rocm-cmake@4.2.0%gcc@10.3.0~ipo+ldconfig build_type=Release arch=linux-centos7-zen2
            ^rocm-device-libs@4.2.0%gcc@10.3.0~ipo build_type=Release arch=linux-centos7-zen2
                ^texinfo@6.5%gcc@10.3.0 arch=linux-centos7-zen2
        ^hip-rocclr@4.2.0%gcc@10.3.0~ipo build_type=RelWithDebInfo arch=linux-centos7-zen2
            ^hsa-rocr-dev@4.2.0%gcc@10.3.0+image~ipo+shared build_type=Release arch=linux-centos7-zen2
                ^hsakmt-roct@4.2.0%gcc@10.3.0~ipo+shared build_type=Release arch=linux-centos7-zen2
                    ^numactl@2.0.14%gcc@10.3.0 arch=linux-centos7-zen2
                        ^autoconf@2.69%gcc@10.3.0 arch=linux-centos7-zen2
                            ^m4@1.4.19%gcc@10.3.0+sigsegv arch=linux-centos7-zen2
                                ^libsigsegv
                        ^automake@1.16.3%gcc@10.3.0 arch=linux-centos7-zen2
                        ^libtool@2.4.6%gcc@10.3.0 arch=linux-centos7-zen2
                ^xxd
            ^mesa18@18.3.6%gcc@10.3.0+glx~llvm~opengles+osmesa swr=none arch=linux-centos7-zen2
                ^binutils@2.36.1%gcc@10.3.0~gas~gold~headers~interwork~ld~libiberty~lto+nls+plugins libs=shared,static arch=linux-centos7-zen2
                ^bison@3.7.6%gcc@10.3.0 arch=linux-centos7-zen2
                ^flex@2.6.4%gcc@10.3.0+lex~nls arch=linux-centos7-zen2
                    ^findutils@4.8.0%gcc@10.3.0 arch=linux-centos7-zen2
                    ^help2man
                ^glproto@1.4.14:
                    ^util-macros
                ^libx11@1.6:
                    ^inputproto
                    ^kbproto
                    ^libxcb@1.1.92:
                        ^libpthread-stubs
                        ^libxau@0.99.2:
                            ^xproto@7.0.17:
                        ^libxdmcp
                        ^xcb-proto
                    ^xextproto@7.1.99:
                    ^xtrans
                ^libxext
                ^py-mako@1.1.4%gcc@10.3.0 arch=linux-centos7-zen2
                    ^py-markupsafe@1.1.1%gcc@10.3.0 arch=linux-centos7-zen2


hip requires llvm-amdgpu variant +rocm-device-libs, but spec asked for ~rocm-device-libs
```
When changing `concretization: together` to `concretization: separately` the concretization succeeds but wants to install muliple instances of `llvm-amdgpu` (and possible other packages, haven't checked).

### Information on your system
```
$ spack debug report
* **Spack:** 0.16.2-3395-59eea28
* **Python:** 3.6.8
* **Platform:** linux-centos7-zen2
* **Concretizer:** original
```
### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by srekolam** [comment] 2021-07-07 19:46
with the additions as part of #23859, rocm-device-libs is added as external project inside llvm-amdgpu package and most of the rocm packages are modified to include the llvm-amdgpu+ rocm-device-libs.  I am thinking the above error is due to addition of  the rocm-device-libs in yaml file .
@haampie  , any thoughts ?

**Comment by UweSauter** [comment] 2021-07-09 08:15
I removed `rocm-device-libs` from the list and then concretion is successful.

Thanks for the hint.

**Comment by srekolam** [comment] 2021-07-15 17:26
can we close this issue ?

**Comment by haampie** [comment] 2021-07-20 09:29
Yeah, you'd either have to use `concretization: separately` or remove the standalone rocm-device-libs

**Closed as completed** 2021-07-20 09:29 UTC
Labels: build-error

**Comment by UweSauter** [comment] 2021-07-25 12:04
Could we please reopen?

This happened again with the latest development version which includes #23853.

```
$ spack debug report
* **Spack:** 0.16.2-3655-4208cf6
* **Python:** 3.6.8
* **Platform:** linux-centos7-zen2
* **Concretizer:** original
```
`spack.yaml`
```
spack:
  concretization: together
  packages:
    all:
      compiler: [gcc@10.3.0]
  specs:
  - matrix:
    - ['%gcc@10.3.0^cmake@3.17.5']
    - [atmi, comgr, hip, hipblas, hipcub, hipfft, hipfort, hipify-clang, hip-rocclr,
      hipsparse, hsakmt-roct, hsa-rocr-dev, llvm-amdgpu, migraphx, miopengemm, miopen-hip,
      miopen-opencl, mivisionx, rccl, rdc, rocalution, rocblas, rocfft, rocm-bandwidth-test,
      rocm-clang-ocl, rocm-cmake, rocm-dbgapi, rocm-debug-agent, rocm-gdb, rocminfo,
      rocm-opencl, rocm-openmp-extras, rocm-smi-lib, rocm-tensile, rocm-validation-suite,
      rocprim, rocprofiler-dev, rocrand, rocsolver, rocsparse, rocthrust, roctracer-dev]
  view: true
```
Output:
```
$ spack concretize
==> Error: An unsatisfiable variant constraint has been detected for spec:
                                                                                                         
    llvm-amdgpu@4.2.0%gcc@10.3.0~ipo+openmp+rocm-device-libs build_type=Release arch=linux-centos7-zen2
        ^cmake@3.17.5%gcc@10.3.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-centos7-zen2
            ^ncurses@6.2%gcc@10.3.0~symlinks+termlib abi=none arch=linux-centos7-zen2
                ^pkgconf@1.7.4%gcc@10.3.0 arch=linux-centos7-zen2
            ^openssl@1.1.1k%gcc@10.3.0~docs+systemcerts arch=linux-centos7-zen2
                ^perl@5.34.0%gcc@10.3.0+cpanm+shared+threads arch=linux-centos7-zen2
                    ^berkeley-db@18.1.40%gcc@10.3.0+cxx~docs+stl arch=linux-centos7-zen2
                    ^bzip2@1.0.8%gcc@10.3.0~debug~pic+shared arch=linux-centos7-zen2
                        ^diffutils@3.7%gcc@10.3.0 arch=linux-centos7-zen2
                            ^libiconv@1.16%gcc@10.3.0 arch=linux-centos7-zen2
                    ^gdbm@1.19%gcc@10.3.0 arch=linux-centos7-zen2
                        ^readline@8.1%gcc@10.3.0 arch=linux-centos7-zen2
                    ^zlib@1.2.11%gcc@10.3.0+optimize+pic+shared arch=linux-centos7-zen2
        ^hwloc@2:         
        ^libelf@0.8.13%gcc@10.3.0 arch=linux-centos7-zen2
        ^perl-data-dumper@2.173%gcc@10.3.0 arch=linux-centos7-zen2
        ^python@3.8.11%gcc@10.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-centos7-zen2
            ^expat@2.4.1%gcc@10.3.0+libbsd arch=linux-centos7-zen2
                ^libbsd
            ^gettext@0.21%gcc@10.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-zen2
                ^libxml2@2.9.10%gcc@10.3.0~python arch=linux-centos7-zen2           
                    ^xz@5.2.5%gcc@10.3.0~pic libs=shared,static arch=linux-centos7-zen2   
                ^tar                                                                                     
            ^libffi@3.3%gcc@10.3.0 arch=linux-centos7-zen2                          
            ^sqlite@3.35.5%gcc@10.3.0+column_metadata+fts~functions~rtree arch=linux-centos7-zen2
            ^util-linux-uuid@2.36.2%gcc@10.3.0 arch=linux-centos7-zen2                                                                                                                                             
        ^z3@4.8.9%gcc@10.3.0~gmp~ipo~python build_type=RelWithDebInfo arch=linux-centos7-zen2

                                                                                                         
while trying to concretize the partial spec:

    rocm-device-libs@4.2.0
        ^cmake@3.17.5%gcc@10.3.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-centos7-zen2
            ^ncurses@6.2%gcc@10.3.0~symlinks+termlib abi=none arch=linux-centos7-zen2
                ^pkgconf@1.7.4%gcc@10.3.0 arch=linux-centos7-zen2
            ^openssl@1.1.1k%gcc@10.3.0~docs+systemcerts arch=linux-centos7-zen2
                ^perl@5.34.0%gcc@10.3.0+cpanm+shared+threads arch=linux-centos7-zen2
                    ^berkeley-db@18.1.40%gcc@10.3.0+cxx~docs+stl arch=linux-centos7-zen2
                    ^bzip2@1.0.8%gcc@10.3.0~debug~pic+shared arch=linux-centos7-zen2
                        ^diffutils@3.7%gcc@10.3.0 arch=linux-centos7-zen2
                            ^libiconv@1.16%gcc@10.3.0 arch=linux-centos7-zen2
                    ^gdbm@1.19%gcc@10.3.0 arch=linux-centos7-zen2
                        ^readline@8.1%gcc@10.3.0 arch=linux-centos7-zen2
                    ^zlib@1.2.11%gcc@10.3.0+optimize+pic+shared arch=linux-centos7-zen2
        ^texinfo@6.5%gcc@10.3.0 arch=linux-centos7-zen2


rocm-device-libs requires llvm-amdgpu variant ~rocm-device-libs, but spec asked for +rocm-device-libs
```

**Comment by sanjtrip** [comment] 2021-07-27 06:50
Hi @UweSauter, Can you please test with "concretization: separately" and update ?

**Comment by UweSauter** [comment] 2021-07-27 08:47
`concretization: separately` succeeds but again wants to install multiple versions of `llvm-amdgpu` (and possibly other packages, haven't checked).

[concretize.log](https://github.com/spack/spack/files/6884067/concretize.log)
[spack.lock](https://github.com/spack/spack/files/6884072/spack.lock.txt)

**Comment by haampie** [comment] 2021-07-27 09:25
The issue is rocm-openmp-extras, it depends on llvm-amdgpu ~rocm-device-libs, but I can't comment on whether this is necessary or not. See also https://github.com/ROCm-Developer-Tools/aomp/issues/217#issuecomment-848847695

**Comment by sanjtrip** [comment] 2021-07-27 16:02
@srekolam, can you update on rocm-openmp-extras dependencies and how can we remove the circular dependency ?

**Comment by srekolam** [comment] 2021-07-29 16:47
Hello Uwe,
Can you please help me with more information when you say ' but again wants to install multiple versions of llvm-amdgpu (and possibly other packages')
do you mean you wanted to use different rocm version of llvm-amdgpu like 4.2.0, 4.1.0 in same environment.

**Comment by UweSauter** [comment] 2021-07-30 06:34
@srekolam: What I mean is that I expect only one version per package inside that environment. Meaning all packages dependending on e.g. `llvm-amdgpu` should require the same configuration parameters for `llvm-amdgpu` so that only one `llvm-amdgpu` configuration needs to be built.

I don't want to mix release versions inside the environement; I want to have a ROCm 4.2 environment that does not include multiple installations of the same (release) version with different (build/dependency) configurations.

Can you follow this trail of thoughts?
