### ISSUE TITLE
Spack generated Dockerfile is not OCI compliant

### ISSUE THREAD

**Issue by goulf-3m** [LLNL/spack#39353] opened 2023-08-09 07:08 UTC
### Steps to reproduce

I followed the documentation.

1. write spack.yaml
2. `spack containerize > Dockerfile`
3. `docker build -t myimage .`

### Error message

[1/2] STEP 3/5: RUN cd /opt/spack-environment && spack env activate . && spack install --fail-fast && spack gc -y
/bin/sh: line 1: spack: command not found

### Information on your system

Fedora38, with podman (docker) and spack installed at `~/opt/spack`

spack debug report:
* **Spack:** 0.21.0.dev0 (2041b92d3ae49947d22ac746c461444f94aaef24)
* **Python:** 3.11.4
* **Platform:** linux-fedora38-zen3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by goulf-3m** [comment] 2023-08-09 07:14
If I insert `RUN declare`, I got the following. Nothing to help locate the spack command.

```
[1/2] STEP 4/7: RUN declare
BASH=/bin/sh
BASHOPTS=checkwinsize:cmdhist:complete_fullquote:extquote:force_fignore:globasciiranges:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_EXECUTION_STRING=declare
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="5" [1]="1" [2]="8" [3]="1" [4]="release" [5]="x86_64-redhat-linux-gnu")
BASH_VERSION='5.1.8(1)-release'
CURRENTLY_BUILDING_DOCKER_IMAGE=1
DIRSTACK=()
EUID=0
GROUPS=()
HOME=/root
HOSTNAME=7bcbc89c69c3
HOSTTYPE=x86_64
IFS=' 	
'
MACHTYPE=x86_64-redhat-linux-gnu
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
POSIXLY_CORRECT=y
PPID=0
PS4='+ '
PWD=/root
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments:posix
SHLVL=1
SPACK_ROOT=/opt/spack
TERM=xterm
UID=0
_=/bin/sh
container=docker
```

**Comment by alalazo** [comment] 2023-08-09 07:33
Can you post your `spack.yaml`?

**Comment by goulf-3m** [comment] 2023-08-11 09:45
A very simple one.
```
spack:
  specs:
    - julia
```

**Comment by alalazo** [comment] 2023-08-11 11:00
This works correctly with `docker`. I'll try to install `podman` and verify with that.

**Comment by alalazo** [comment] 2023-10-13 10:54
Turns out that our Dockerfile is not fully OCI compliant (to be fair, it never claimed to be! :sweat_smile: ) I think the issue is that Spack activation does not pass to the next command. You can though:
```
podman build --format docker .
```
and that should succeed.

**Comment by haampie** [comment] 2024-05-24 09:06
I think we can close this. There's a workaround as pointed out above.

Also there is a way to create OCI images without podman / buildah / docker: https://spack-tutorial.readthedocs.io/en/latest/tutorial_binary_cache.html

**Closed as completed by haampie** 2024-05-24 09:06 UTC
Labels: bug, impact-low, containers
