### ISSUE TITLE
Patches and Package Namespace

### ISSUE THREAD

**Issue by homerdin** [LLNL/spack#5002] opened 2017-08-07 17:12 UTC
I have another repo other than builtin.  There is a lulesh package in both my repo and the builtin repo.  The builtin spackage has a patch, the version in my repo does not.  Spack was looking for the patch in my repo and failing to find it.  My thought was that the way spack checks for patches ignores the namespace?  
However after installing the patch into my repo directory to work then removing it to recreate the error solved the issue.

**Comment by adamjstewart** [comment] 2017-08-07 17:14
This looks like a duplicate of the same bug first reported in #4236. @alalazo Did you ever track this one down?

**Comment by alalazo** [comment] 2017-08-07 17:18
It should be fixed by #4307. I even made the fix cherry-pickable in case people didn't agree with the refactoring there.

**Closed** 2017-08-12 02:18 UTC
Labels: duplicate, repos
