### ISSUE TITLE
py-numpy: build fails when using preinstalled python [also has cython installed]

### ISSUE THREAD

**Issue by balay** [LLNL/spack#18520] opened 2020-09-04 22:22 UTC
py-numpy build fails when using preinstalled python3. 

System Cython is also installed - however this build is using spack dependencies for cython.  Likely system cython is getting picked up instead of spack installed cython?

```console
[balay@pj01 .spack]$ cat ~/.spack/packages.yaml
packages:
  python:
    externals:
    - spec: "python@3.7.8%gcc@9.3.1"
      prefix: /usr
[balay@pj01 .spack]$ python3 -c "import cython;print(cython.__version__)"
0.29.13
[balay@pj01 .spack]$ spack spec py-numpy
Input spec
--------------------------------
py-numpy

Concretized
--------------------------------
py-numpy@1.19.1%gcc@9.3.1+blas+lapack arch=linux-fedora31-skylake
    ^openblas@0.3.10%gcc@9.3.1~consistent_fpcsr~ilp64+pic+shared threads=none arch=linux-fedora31-skylake
    ^py-cython@0.29.21%gcc@9.3.1 arch=linux-fedora31-skylake
        ^py-setuptools@49.2.0%gcc@9.3.1 arch=linux-fedora31-skylake
            ^python@3.7.8%gcc@9.3.1+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-fedora31-skylake

[balay@pj01 .spack]$ spack install py-numpy
==> Installing openblas
==> No binary for openblas found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/04/0484d275f87e9b8641ff2eecaa9df2830cbe276ac79ad80494822721de6e1693.tar.gz
############################################################################################################################################################################################################ 100.0%
==> openblas: Executing phase: 'edit'
==> openblas: Executing phase: 'build'
==> openblas: Executing phase: 'install'
[+] /home/balay/spack/opt/spack/linux-fedora31-skylake/gcc-9.3.1/openblas-0.3.10-rjaatbkpaiylnv7k7osx64n2ylyytvxu
==> python@3.7.8 : externally installed in /usr
[+] /usr
==> Installing py-setuptools
==> No binary for py-setuptools found: installing from source
==> Fetching https://pypi.io/packages/source/s/setuptools/setuptools-49.2.0.zip
############################################################################################################################################################################################################ 100.0%
==> py-setuptools: Executing phase: 'build'
==> py-setuptools: Executing phase: 'install'
[+] /home/balay/spack/opt/spack/linux-fedora31-skylake/gcc-9.3.1/py-setuptools-49.2.0-c6an5huaysuobc3k4ycsacw6edoxvjxh
==> Installing py-cython
==> No binary for py-cython found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/e5/e57acb89bd55943c8d8bf813763d20b9099cc7165c0f16b707631a7654be9cad.tar.gz
############################################################################################################################################################################################################ 100.0%
==> py-cython: Executing phase: 'build'
==> py-cython: Executing phase: 'install'
[+] /home/balay/spack/opt/spack/linux-fedora31-skylake/gcc-9.3.1/py-cython-0.29.21-sues7uro5rryb2b63s3esw3zihz2iuyu
==> Installing py-numpy
==> No binary for py-numpy found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/b8/b8456987b637232602ceb4d663cb34106f7eb780e247d51a260b84760fd8f491.zip
############################################################################################################################################################################################################ 100.0%
==> py-numpy: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/python3.7' '-s' 'setup.py' '--no-user-cfg' 'build'
See build log for details:
  /home/balay/spack-temp/stage/spack-stage-py-numpy-1.19.1-sknmujvto2tr3dqp5qbocpiwwb3k2qu4/spack-build-out.txt
```
```
[balay@pj01 .spack]$ spack debug report
* **Spack:** 0.15.4-853-f4d3a1a0c
* **Python:** 3.7.8
* **Platform:** linux-fedora31-skylake
```

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/5177157/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/5177158/spack-build-env.txt)

**Comment by adamjstewart** [comment] 2020-09-04 22:33
Hmm, I'm not sure how to prevent this. It looks like your system cython is too old to compile numpy. I'll have to see how cython is found and if there's a way to put Spack's cython first.

**Comment by adamjstewart** [comment] 2020-09-04 22:41
If you run `spack build-env` to step into the build, what happens when you run:
```console
$ python
>>> import Cython
>>> Cython.__file__
```
My guess is that it's pointing to your system Cython instead of the Spack-installed one.

**Comment by adamjstewart** [comment] 2020-09-04 22:42
According to https://docs.python.org/3/tutorial/modules.html#the-module-search-path, `PYTHONPATH` should be searched first.

**Comment by balay** [comment] 2020-09-05 06:18
```
[balay@pj01 spack]$ spack build-env py-numpy bash
[balay@pj01 spack]$ echo $PYTHONPATH
/home/balay/spack/opt/spack/linux-fedora31-skylake/gcc-9.3.1/py-numpy-1.19.1-sknmujvto2tr3dqp5qbocpiwwb3k2qu4/lib/python3.7/site-packages:/home/balay/spack/opt/spack/linux-fedora31-skylake/gcc-9.3.1/py-cython-0.29.21-sues7uro5rryb2b63s3esw3zihz2iuyu/lib/python3.7/site-packages:/home/balay/spack/opt/spack/linux-fedora31-skylake/gcc-9.3.1/py-setuptools-49.2.0-c6an5huaysuobc3k4ycsacw6edoxvjxh/lib/python3.7/site-packages
[balay@pj01 spack]$ ls /home/balay/spack/opt/spack/linux-fedora31-skylake/gcc-9.3.1/py-cython-0.29.21-sues7uro5rryb2b63s3esw3zihz2iuyu/lib/python3.7/site-packages
[balay@pj01 spack]$ ls /home/balay/spack/opt/spack/linux-fedora31-skylake/gcc-9.3.1/py-cython-0.29.21-sues7uro5rryb2b63s3esw3zihz2iuyu/lib64/python3.7/site-packages/
Cython  Cython-0.29.21-py3.7.egg-info  cython.py  __pycache__  pyximport
[balay@pj01 spack]$ 
```

Hm - so PYTHONPATH got set incorrectly for cython. [or perhaps it should be installed in lib  and not lib64?]

**Comment by balay** [comment] 2020-09-05 06:26
```
[balay@pj01 spack]$ python3 -c "import cython;print(cython.__file__)"
/usr/lib64/python3.7/site-packages/cython.py
```
So the system stuff is in lib64
However some python packages installed by spack use lib
```
[balay@pj01 spack]$ ls /home/balay/spack/opt/spack/linux-fedora31-skylake/gcc-9.3.1/py-setuptools-49.2.0-c6an5huaysuobc3k4ycsacw6edoxvjxh/lib/python3.7/site-packages/
easy_install.py  pkg_resources  __pycache__  setuptools  setuptools-49.2.0-py3.7.egg-info
[balay@pj01 spack]$ 
```

**Comment by adamjstewart** [comment] 2020-09-05 15:22
Thanks @balay, that explains it. I remember a similar issue where the `lib` vs `lib64` problem affected a user (#17126).

I think there are two possible solutions here:

1. Add both `lib` and `lib64` to the `PYTHONPATH`
2. Install to `lib`, not `lib64`

1 is more inline with how we treat non-Python libraries. I think 2 might be problematic for external Python installations like yours that we don't have control over. For example, I don't think `spack activate` would work. I'm probably going to go with solution 1.

**Comment by balay** [comment] 2020-09-05 15:33
```
[balay@pj01 Cython-0.29.21]$ python3 setup.py  install --help |grep lib
Unable to find pgen, not compiling formal grammar.
  --install-purelib                    installation directory for pure Python
  --install-platlib                    installation directory for non-pure
  --install-lib                        installation directory for all module
                                       purelib and --install-platlib)
                                       '/home/balay/.local/lib/python3.7/site-
```
Perhaps one of these options - say   --install-lib  can be used consistently with all python packages so that the path used here exactly matches the one used with PYTHONPATH?

And somehow `python3.7/site-packages` is obtained by spack  to set for PYTHONPATH  so 'lib' vs 'lib64' can be similarly obtained  from installed python - and used?

`python3 setup.py  install --prefix=$HOME/cython-0.29.21 --install-lib=$HOME/cython-0.29.21/lib64/python3.7/site-packages/`

So `PYTHONPATH=$HOME/cython-0.29.21/lib64/python3.7/site-packages/`

**Comment by adamjstewart** [comment] 2020-09-05 15:36
> Perhaps one of these options - say --install-lib can be used consistently with all python packages so that the path used here exactly matches the one used with PYTHONPATH?

The problem is that users may also add packages like `py-cython` as external packages. So we can't guarantee that they will be installed in `lib`.

> And somehow python3.7/site-packages is obtained by spack to set for PYTHONPATH so 'lib' vs 'lib64' can be similarly obtained from installed python - and used?

We just use `'python{0}/site-packages'.format(self.version.up_to(2))`, not much magic there. There might be a way to query the `python` executable to see what it will use, but it's difficult to find those options in a consistent way across all Python versions. Another option is to check both and only use directories that exist, but the problem there is that we also need to set `PYTHONPATH` for the installation directory before it exists.

**Comment by balay** [comment] 2020-09-05 15:36
BTW: `lib` vs `lib64` can be similarly controlled at install time for autoconf/cmake packages. [but yeah - for pre-installed/system packages - specified in ~/.spack/packages.yaml - spack would have to check both locations]

**Comment by balay** [comment] 2020-09-05 15:47
Always using `lib` should also be fine [as long as all spack packages are consistent]

**Closed as completed** 2020-10-13 00:59 UTC
Labels: build-error
