### ISSUE TITLE
`spack load intel` emits warnings

### ISSUE THREAD

**Issue by ikitayama** [LLNL/spack#22775] opened 2021-04-05 04:06 UTC
### Steps to reproduce the issue

```console
$ spack load intel

==> Warning: Quotes in command arguments can confuse scripts like configure.
  The following arguments may cause problems when executed:
      source /dev/null &> /dev/null && python3 -c "import os, json; print(json.dumps(dict(os.environ)))"
  Quotes aren't needed because spack doesn't use a shell.
  Consider removing them
==> Warning: Quotes in command arguments can confuse scripts like configure.
  The following arguments may cause problems when executed:
      source /p/project/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.2.0/intel-20.0.4-codjiizk7rkajeuwnuf7skdd6rg7ox3h/compilers_and_libraries_2020.4.304/linux/bin/compilervars.sh intel64 &> /dev/null && python3 -c "import os, json; print(json.dumps(dict(os.environ)))"
  Quotes aren't needed because spack doesn't use a shell.
  Consider removing them
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by ikitayama** [comment] 2021-04-05 04:07
```
$ spack debug report
* **Spack:** 0.16.1-2041-1908e6834d
* **Python:** 3.6.8
* **Platform:** linux-centos8-zen2
* **Concretizer:** original
```

**Comment by maxim-belkin** [comment] 2021-04-05 14:48
Duplicate of #22766

**Comment by alalazo** [comment] 2021-04-06 05:08
Closing as duplicate

**Closed as completed by alalazo** 2021-04-06 05:08 UTC
Labels: bug, duplicate, impact-low
