### ISSUE TITLE
Installation issue: clingo

### ISSUE THREAD

**Issue by rchoudhary** [LLNL/spack#28183] opened 2021-12-29 21:53 UTC
### Steps to reproduce the issue

```
% spack install py-matplotlib backend=qt5agg arch=m1 
...
==> Installing clingo-bootstrap-spack-gmmjcapqovtzrdbsqrcserdmlh334c5w
==> No binary for clingo-bootstrap-spack-gmmjcapqovtzrdbsqrcserdmlh334c5w found: installing from source
==> Error: RuntimeError: Unable to locate libpython3.9.a libraries in /opt/homebrew/Caskroom/miniforge/base/lib

/Users/rutvik/spack/var/spack/repos/builtin/packages/python/package.py:828, in libs:
        825                return LibraryList(os.path.join(macos_developerdir, ldlibrary))
        826            else:
        827                msg = 'Unable to locate {0} libraries in {1}'
  >>    828                raise RuntimeError(msg.format(ldlibrary, libdir))
        829        else:
        830            library = self.config_vars['LIBRARY']
        831


==> Error: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %apple-clang target=aarch64" due to the following failures:
    'spack-install' raised InstallError: Terminating after first install failure: RuntimeError: Unable to locate libpython3.9.a libraries in /opt/homebrew/Caskroom/miniforge/base/lib
    Please run `spack -d spec zlib` for more verbose error messages
```

### Information on your system

* **Spack:** 0.17.1-677-c2e1a12cdf
* **Python:** 3.9.7
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### Additional information

I have Python 3.9 through [Miniforge](https://github.com/conda-forge/miniforge). If I check `/opt/homebrew/Caskroom/miniforge/base/lib` I see that I have `libpython3.9.dylib` but not `libpython3.9.a`.

@alalazo @tgamb

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [ ] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by rchoudhary** [comment] 2021-12-29 22:26
I should add that installing [libpython-static](https://anaconda.org/conda-forge/libpython-static) from conda-forge fixed the issue. However someone had told me that spack should be handling this without manual intervention.

Please close the issue if this is an incorrect assumption.

**Comment by adamjstewart** [comment] 2021-12-29 22:31
@alalazo tried to convince a friend to switch from Conda to Spack and he immediately ran into this issue, not a great user experience. Luckily we found a workaround, but this is something we definitely want to handle better in the long run. If the Python libraries can't be found, can Spack automatically bootstrap Python as well?

**Comment by alalazo** [comment] 2021-12-30 07:51
@adamjstewart Part of the issue is also that we don't have binaries yet for `m1` and thus we fall back to bootstrapping from sources. 

> If the Python libraries can't be found, can Spack automatically bootstrap Python as well?

I need to think about it. Bootstrapping Python should be feasible, but not in the lazy way we bootstrap other dependencies. Maybe a command / subcommand to explicitly bootstrap Python with instructions on how to use it afterwards?

**Comment by alalazo** [comment] 2021-12-30 07:52
@tgamblin

**Comment by mathstuf** [comment] 2022-01-28 20:27
I'll note that macOS arm64 installation is still busted here. Right now, it is failing with Xcode 13.2:

```
==> Installing clingo-bootstrap-spack-2abcszpozj2aqevhf54dz43nosay2sk4
==> No binary for clingo-bootstrap-spack-2abcszpozj2aqevhf54dz43nosay2sk4 found: installing from source
==> looking in /Applications/Xcode-13.2.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include
==> looking for ['pyconfig.h', 'pyconfig.hpp', 'pyconfig.hxx', 'pyconfig.hh', 'pyconfig.H', 'pyconfig.txx', 'pyconfig.tcc', 'pyconfig.icc', 'pyconfig.mod', 'pyconfig.inc']
==> looking at /Applications/Xcode-13.2.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include
==> /Applications/Xcode-13.2.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include
==> []
==> Error: IndexError: list index out of range

/Users/benboeckel-admin/code/vtk/src-remoting/.gitlab/spack/src/var/spack/repos/builtin/packages/python/package.py:912, in headers:
        909                'pyconfig', self.prefix.include, recursive=True)
        910            tty.info(self.prefix.include)
        911            tty.info(list(headers))
  >>    912            config_h = headers[0]
        913
        914        headers.directories = [os.path.dirname(config_h)]
        915        return headers


==> Error: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %apple-clang target=aarch64" due to the following failures:
    'spack-install' raised InstallError: Terminating after first install failure: IndexError: list index out of range
    Please run `spack -d spec zlib` for more verbose error messages
```

I added some debugging here. The issue is that the searched-for directory contains a symlink (which is not followed in the `os.walk`):

```
% ls -l /Applications/Xcode-13.2.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include
total 0
lrwxr-xr-x  1 svc-dashboard  staff  10 Jan 25 19:27 python3.8 -> ../Headers
```

Adding `followlinks` ends up with Spack trying to make directories it does not have permission for (namely, `==> Error: PermissionError: [Errno 13] Permission denied: '/Library/Python/3.8'` ends up happening).

I don't know if this is a new error masking the one from this issue or if this issue is "resolved" and this is the "next error".

**Comment by mathstuf** [comment] 2022-01-28 20:35
Hmm, the initial issue here looks like #27017 which was supposed to be fixed by #27023 (and was at the time).

**Comment by kgerheiser** [comment] 2022-02-24 22:07
I'm hitting this too while bootstrapping Clingo. Does Clingo require a static libpython?

**Comment by kgerheiser** [comment] 2022-02-25 15:21
I found a solution to this. My Python install only has shared libraries, but did not have `+shared` in its spec. There's a check in Python's package.py that checks for shared vs. static with `if '+shared' in self.spec:`. Adding `+shared` to the external spec let Python find the correct libraries and boostrap Clingo.

**Comment by tmenari** [comment] 2022-03-15 16:48
I am also failing to bootstrap `develop` clingo on macOS 12.2.1 M1 with Xcode installed in the default location. It appears to be a regression from v0.17.1 introduced by commit e0f044561e9b3cb384bfb0f364555e5875b1a492.

**Comment by healther** [comment] 2022-04-06 11:05
Do we have a solution for this? I'm running into this with an anaconda provided python...

**Closed as completed** 2022-05-27 10:18 UTC
Labels: macOS, build-error, arm, bootstrap
