### ISSUE TITLE
Installation issue: hpl with intel-oneapi-mkl

### ISSUE THREAD

**Issue by yellowhat** [LLNL/spack#21724] opened 2021-02-17 10:55 UTC
### Steps to reproduce the issue
Modify the hpl `package.py` adding:
```
        if (self.spec.satisfies('^intel-mkl') or
+           self.spec.satisfies('^intel-oneapi-mkl') or
            self.spec.satisfies('^intel-parallel-studio+mkl')):
            config.append('LDFLAGS={0}'.format(
                self.spec['blas'].libs.ld_flags))
```

```console
$ spack install hpl +openmp arch=x86_64 ^intel-oneapi-mpi ^intel-oneapi-mkl
[+] /opt/intel/oneapi (external intel-oneapi-mkl-2021.1.1-qyjzf2zkff4rhbw64iduevpqpb35dkmg)
[+] /opt/intel/oneapi (external intel-oneapi-mpi-2021.1.1-um6h5no2hqudztstzosrnxz676vmoct2)
==> Installing hpl-2.3-4gwoqbhrvbhpjbu5wkgefawvadvxrhtq
==> No binary for hpl-2.3-4gwoqbhrvbhpjbu5wkgefawvadvxrhtq found: installing from source
==> Using cached archive: /home/vasco/spack/var/spack/cache/_source-cache/archive/32/32c5c17d22330e6f2337b681aded51637fb6008d3f0eb7c277b163fadd612830.tar.gz
==> No patches needed for hpl
==> hpl: Executing phase: 'autoreconf'
==> hpl: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 77:
    '/dev/shm/vasco/spack-stage/spack-stage-hpl-2.3-4gwoqbhrvbhpjbu5wkgefawvadvxrhtq/spack-src/configure' '--prefix=/home/vasco/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/hpl-2.3-4gwoqbhrvbhpjbu5wkgefawvadvxrhtq' 'CFLAGS=-O3 -fopenmp' 'LDFLAGS=-L/opt/intel/oneapi/mkl/latest/lib/intel64 -lmkl_blacs_sgimpt_lp64 -lmkl_cdft_core -lmkl_core -lmkl_gf_ilp64 -lmkl_gf_lp64 -lmkl_gnu_thread -lmkl_intel_ilp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_pgi_thread -lmkl_rt -lmkl_scalapack_ilp64 -lmkl_scalapack_lp64 -lmkl_sequential -lmkl_sycl -lmkl_tbb_thread -lmkl_blacs_intelmpi_ilp64 -lmkl_blacs_intelmpi_lp64 -lmkl_blacs_openmpi_ilp64 -lmkl_blacs_openmpi_lp64 -lmkl_blacs_sgimpt_ilp64'

2 errors found in build log:
     1    ==> hpl: Executing phase: 'autoreconf'
     2    ==> hpl: Executing phase: 'configure'
     3    ==> [2021-02-17-10:53:34.682876] FILTER FILE: configure [replacing "^libs10=.*"]
     4    ==> [2021-02-17-10:53:34.698402] '/dev/shm/vasco/spack-stage/spack-stage-hpl-2.3-4gwoqbhrvbhpjbu5wkgefawvadvxrhtq/spack-src/configure' '--prefix
          =/home/vasco/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/hpl-2.3-4gwoqbhrvbhpjbu5wkgefawvadvxrhtq' 'CFLAGS=-O3 -fopenmp' 'LDFLAGS=-L/opt/inte
          l/oneapi/mkl/latest/lib/intel64 -lmkl_blacs_sgimpt_lp64 -lmkl_cdft_core -lmkl_core -lmkl_gf_ilp64 -lmkl_gf_lp64 -lmkl_gnu_thread -lmkl_intel_ilp
          64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_pgi_thread -lmkl_rt -lmkl_scalapack_ilp64 -lmkl_scalapack_lp64 -lmkl_sequential -lmkl_sycl -lmkl_tb
          b_thread -lmkl_blacs_intelmpi_ilp64 -lmkl_blacs_intelmpi_lp64 -lmkl_blacs_openmpi_ilp64 -lmkl_blacs_openmpi_lp64 -lmkl_blacs_sgimpt_ilp64'
     5    checking for gcc... /home/vasco/spack/lib/spack/env/gcc/gcc
     6    checking whether the C compiler works... no
  >> 7    configure: error: in `/dev/shm/vasco/spack-stage/spack-stage-hpl-2.3-4gwoqbhrvbhpjbu5wkgefawvadvxrhtq/spack-src':
  >> 8    configure: error: C compiler cannot create executables
     9    See `config.log' for more details

See build log for details:
  /dev/shm/vasco/spack-stage/spack-stage-hpl-2.3-4gwoqbhrvbhpjbu5wkgefawvadvxrhtq/spack-build-out.txt
```

### Information on your system
```
$ spack debug report
* **Spack:** 0.16.0-1310-ee1b0b9
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake
* **Concretizer:** original
```

### Additional information
@rscohn2
[spack-cc-hpl-4gwoqbh.out.log](https://github.com/spack/spack/files/5995062/spack-cc-hpl-4gwoqbh.out.log)
[spack-cc-hpl-4gwoqbh.in.log](https://github.com/spack/spack/files/5995063/spack-cc-hpl-4gwoqbh.in.log)

### General information
- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by yellowhat** [comment] 2021-02-17 16:36
In the config.log file:
```
Using built-in specs.
COLLECT_GCC=/opt/gcc-9.2.0/bin/gcc
COLLECT_LTO_WRAPPER=/opt/gcc-9.2.0/libexec/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ./configure --disable-multilib --prefix=/opt/gcc-9.2.0
Thread model: posix
gcc version 9.2.0 (GCC)
configure:2617: $? = 0
configure:2606: /home/vasco/spack/lib/spack/env/gcc/gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:2617: $? = 1
configure:2606: /home/vasco/spack/lib/spack/env/gcc/gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
configure:2617: $? = 1
configure:2637: checking whether the C compiler works
configure:2659: /home/vasco/spack/lib/spack/env/gcc/gcc -O3 -fopenmp  -L/opt/intel/oneapi/mkl/latest/lib/intel64 -lmkl_blacs_sgimpt_lp64 -lmkl_cdft_core -lmkl_core -lmkl_gf_ilp64 -lmkl_gf_lp64 -lmkl_gnu_thread -lmkl_intel_ilp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_pgi_thread -lmkl_rt -lmkl_scalapack_ilp64 -lmkl_scalapack_lp64 -lmkl_sequential -lmkl_sycl -lmkl_tbb_thread -lmkl_blacs_intelmpi_ilp64 -lmkl_blacs_intelmpi_lp64 -lmkl_blacs_openmpi_ilp64 -lmkl_blacs_openmpi_lp64 -lmkl_blacs_sgimpt_ilp64 conftest.c  >&5
/usr/bin/ld: warning: libsycl.so.5, needed by /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libtbb.so.12, needed by /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_tbb_thread.so, not found (try using -rpath or -rpath-link)
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::device::is_gpu() const'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `vtable for cl::sycl::detail::buffer_impl'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_pgi_thread.so: undefined reference to `_mp_scheds_dyn_init8'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::detail::OSUtil::getOSModuleHandle(void const*)'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::malloc_shared(unsigned long, cl::sycl::queue const&)'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_pgi_thread.so: undefined reference to `__c_mcopy4_bwd'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::__host_std::fma(float, float, float)'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_pgi_thread.so: undefined reference to `pgf90_compiled'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `clReleaseKernel'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::queue::queue(_cl_command_queue*, cl::sycl::context const&, std::function<void (cl::sycl::exception_list)> const&)'
```

**Comment by rscohn2** [comment] 2021-02-17 19:39
Thanks for the report. I will investigate.

**Comment by yellowhat** [comment] 2021-03-23 10:57
With the merge of #22202 I have tried to build hpl:
```
# Add externally installed intel-oneapi-mpi and intel-oneapi-mkl
cat >>spack/etc/spack/defaults/packages.yaml <<EOF

  intel-oneapi-mpi:
    externals:
    - spec: intel-oneapi-mpi @2021.1.1
      prefix: /opt/intel/oneapi/

  intel-oneapi-mkl:
    externals:
    - spec: intel-oneapi-mkl @2021.11.
      prefix: /opt/intel/oneapi/
EOF

# Add the following to the hpl package:
    if (self.spec.satisfies('^intel-mkl') or
            self.spec.satisfies('^intel-oneapi-mkl') or
            self.spec.satisfies('^intel-parallel-studio+mkl')):
            config.append('LDFLAGS={0}'.format(
                self.spec['blas'].libs.ld_flags))

$ spack install hpl +openmp arch=x86_64 ^intel-oneapi-mpi ^intel-oneapi-mkl
```

The `config.log` contains:
```
configure:2659: /home/vasco/spack/lib/spack/env/gcc/gcc -O3 -fopenmp  -L/opt/intel/oneapi/mkl/latest/lib/intel64 -lmkl_blacs_sgimpt_lp64 -lmkl_cdft_core -lmkl_core -lmkl_gf_ilp64 -lmkl_gf_lp64 -lmkl_gnu_thread -lmkl_intel_ilp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_pgi_thread -lmkl_rt -lmkl_scalapack_ilp64 -lmkl_scalapack_lp64 -lmkl_sequential -lmkl_sycl -lmkl_tbb_thread -lmkl_blacs_intelmpi_ilp64 -lmkl_blacs_intelmpi_lp64 -lmkl_blacs_openmpi_ilp64 -lmkl_blacs_openmpi_lp64 -lmkl_blacs_sgimpt_ilp64 conftest.c  >&5
/usr/bin/ld: warning: libsycl.so.5, needed by /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libtbb.so.12, needed by /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_tbb_thread.so, not found (try using -rpath or -rpath-link)
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::device::is_gpu() const'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `vtable for cl::sycl::detail::buffer_impl'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_pgi_thread.so: undefined reference to `_mp_scheds_dyn_init8'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::detail::OSUtil::getOSModuleHandle(void const*)'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::malloc_shared(unsigned long, cl::sycl::queue const&)'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_pgi_thread.so: undefined reference to `__c_mcopy4_bwd'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::__host_std::fma(float, float, float)'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_pgi_thread.so: undefined reference to `pgf90_compiled'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `clReleaseKernel'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::queue::queue(_cl_command_queue*, cl::sycl::context const&, std::function<void (cl::sycl::exception_list)> const&)'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::__host_std::sin(double)'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::__host_std::sincos(float, float*)'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::detail::SYCLMemObjT::updateHostMemory()'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::__host_std::copysign(double, double)'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::detail::AccessorImplHost::~AccessorImplHost()'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::__host_std::fmin(double, double)'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::event::wait_and_throw()'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_blacs_openmpi_ilp64.so: undefined reference to `ompi_mpi_dblcplex'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::opencl::make_device(unsigned long)'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::__host_std::tan(double)'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::event::event()'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sycl.so: undefined reference to `cl::sycl::platform::platform()'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_blacs_sgimpt_lp64.so: undefined reference to `MPI_Alltoallv'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_tbb_thread.so: undefined reference to `tbb::detail::r1::wait_bounded_queue_monitor(tbb::detail::r1::concurrent_monitor*, unsigned long, long, tbb::detail::d1::delegate_base&)'
```

I am getting the same output by letting spack install `intel-oneapi-mpi` and `intel-oneapi-mkl`.

**Comment by rscohn2** [comment] 2021-03-23 13:35
MKL, DAL, etc all include optional libraries for SYCL. The SYCL library needs libsycl, which is part of the compiler runtime. I assumed package owners would only add the -lmkl_sycl when they wanted to use SYCL and would add a dependence on the compiler package.  It looks like this package is adding -l for every possible mkl library. 

I am not sure how this should be fixed. Ideally, there would be a separate SYCL runtime package and MKL would depend on it. Package owners like hpl would not have to understand the dependencies of mkl.

As a test, I tried adding a dependence on the compiler package, but that did not help. I need to check that.

@scheibelp @frankwillmore @glennpj @DanVev

**Comment by scheibelp** [comment] 2021-03-23 18:10
Note if all the `-l` flags are coming from `self.spec['blas'].libs.ld_flags`, then `intel-oneapi-mkl` can define a custom `libs` property which excludes the SYCL-based libraries.

> MKL, DAL, etc all include optional libraries for SYCL

Are these additional libraries needed for SYCL support? Or are they alternatives libraries built with SYCL support (in which case for example you wouldn't link `-lmkl_sequential` and `-lmkl_sycl`)?

**Comment by rscohn2** [comment] 2021-03-25 14:04
The pre-oneapi intel-mkl package and has a much smaller set of libraries in libs so I will try to reproduce that.

They are additional libraries. I will make a test for mkl sycl interfaces with/without icx and hande that separately.

**Closed as completed** 2021-03-26 21:16 UTC
Labels: build-error

**Comment by yellowhat** [comment] 2021-03-29 07:32
Hi,
just tried again:
```
# Add externally installed intel-oneapi-mpi and intel-oneapi-mkl
cat >>spack/etc/spack/defaults/packages.yaml <<EOF

  intel-oneapi-mpi:
    externals:
    - spec: intel-oneapi-mpi @2021.1.1
      prefix: /opt/intel/oneapi/

  intel-oneapi-mkl:
    externals:
    - spec: intel-oneapi-mkl @2021.1.1
      prefix: /opt/intel/oneapi/
EOF

# Add the following to the hpl package:
    if (self.spec.satisfies('^intel-mkl') or
            self.spec.satisfies('^intel-oneapi-mkl') or
            self.spec.satisfies('^intel-parallel-studio+mkl')):
            config.append('LDFLAGS={0}'.format(
                self.spec['blas'].libs.ld_flags))

$ spack install hpl +openmp arch=x86_64 ^intel-oneapi-mpi ^intel-oneapi-mkl`
```

But I am still getting errors:
```
configure:2659: /dev/shm/spack/lib/spack/env/gcc/gcc -O3 -fopenmp  -L/opt/intel/oneapi/mkl/latest/lib/intel64 -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core conftest.c  >&5
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sequential.so: undefined reference to `cos'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `ceilf'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sequential.so: undefined reference to `acos'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `ceil'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `atan2'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `sqrtf'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `fabs'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sequential.so: undefined reference to `sin'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `exp'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `sqrt'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sequential.so: undefined reference to `log'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sequential.so: undefined reference to `log10'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `pow'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `expf'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `logf'
collect2: error: ld returned 1 exit status
```

**Comment by rscohn2** [comment] 2021-03-29 13:56
I wasn't able to reproduce the problem because they gcc on ubuntu 20.04 always adds -lm. The intel-mkl package for parallel studio adds -lm -ldl -lpthread so I added them, too. Please let me know if #22607 fixes the problem.

**Comment by yellowhat** [comment] 2021-03-29 14:14
I have just tried to apply #22607 but still:
```
configure:2659: /home/vasco/spack/lib/spack/env/gcc/gcc -O3 -fopenmp  -L/opt/intel/oneapi/mkl/latest/lib/intel64 -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core conftest.c  >&5
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sequential.so: undefined reference to `cos'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `ceilf'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sequential.so: undefined reference to `acos'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `ceil'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `atan2'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `sqrtf'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `fabs'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sequential.so: undefined reference to `sin'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `exp'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `sqrt'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sequential.so: undefined reference to `log'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_sequential.so: undefined reference to `log10'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `pow'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `expf'
/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so: undefined reference to `logf'
collect2: error: ld returned 1 exit status
```

**Comment by rscohn2** [comment] 2021-03-29 16:22
I didn't add the libraries correctly, sorry for missing that.

I updated the PR. Can you try again? I manually verified that the link line is correct.

**Comment by yellowhat** [comment] 2021-03-29 17:04
Now I am able to compile HPL but on running:
```
$ mpirun -np 30 $(which xhpl)
WARNING: release_mt library was used but no multi-ep feature was enabled. Please use release library instead.
================================================================================
HPLinpack 2.3  --  High-Performance Linpack benchmark  --   December 2, 2018
Written by A. Petitet and R. Clint Whaley,  Innovative Computing Laboratory, UTK
Modified by Piotr Luszczek, Innovative Computing Laboratory, UTK
Modified by Julien Langou, University of Colorado Denver
================================================================================

An explanation of the input/output parameters follows:
T/V    : Wall time / encoded variant.
N      : The order of the coefficient matrix A.
NB     : The partitioning blocking factor.
P      : The number of process rows.
Q      : The number of process columns.
Time   : Time in seconds to solve the linear system.
Gflops : Rate of execution for solving the linear system.

The following parameter values will be used:

N      :   75000
NB     :     232
PMAP   : Row-major process mapping
P      :       5
Q      :       6
PFACT  :   Right
NBMIN  :       4
NDIV   :       2
RFACT  :   Crout
BCAST  :  1ringM
DEPTH  :       1
SWAP   : Mix (threshold = 64)
L1     : transposed form
U      : transposed form
EQUIL  : yes
ALIGN  : 8 double precision words

--------------------------------------------------------------------------------

- The matrix A is randomly generated for each test.
- The following scaled residual check will be computed:
      ||Ax-b||_oo / ( eps * ( || x ||_oo * || A ||_oo + || b ||_oo ) * N )
- The relative machine precision (eps) is taken to be               1.110223e-16
- Computational tests pass if scaled residuals are less than                16.0


Intel MKL ERROR: Parameter 8 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 8 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 8 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 10 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 10 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 8 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 8 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 8 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 8 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 10 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 10 was incorrect on entry to DGEMM .

Intel MKL ERROR: Parameter 8 was incorrect on entry to DGEMM .
```

I have tried to compile HPL manually against intel-oneapi-mpi and intel-oneapi-mkl and it worked.

**Comment by yellowhat** [comment] 2021-03-29 17:07
I am using the following LA flags:
```
# - Linear Algebra library (BLAS or VSIPL) -----------------------------
LAdir        = $MKLROOT
LAinc        = -I$(LAdir)/include -DMKL_ILP64 -m64
LAlib        = -L$(LAdir)/mkl/lib/intel64 \
               -Wl,--start-group \
               $(LAdir)/lib/intel64/libmkl_intel_ilp64.a \
               $(LAdir)/lib/intel64/libmkl_gnu_thread.a \
               $(LAdir)/lib/intel64/libmkl_core.a \
               -Wl,--end-group -lgomp -lpthread -lm -ldl
```

**Comment by rscohn2** [comment] 2021-03-30 15:41
I have not been able to reproduce the problem, but fixed an issue
where it was using the wrong library.
(https://github.com/spack/spack/pull/22607)

You are using ilp64 when you build manually and I am using lp64. I am
adding support for ilp64 but that doesn't seem like it could be the
issue.

**Comment by yellowhat** [comment] 2021-03-30 18:42
Just tried with this:
```
# - Linear Algebra library (BLAS or VSIPL) -----------------------------
LAdir        = /opt/intel/oneapi/mkl/latest/
LAinc        = -I$(LAdir)/include -DMKL_LP64 -m64
LAlib        = -L$(LAdir)/mkl/lib/intel64 \
               -Wl,--start-group \
               $(LAdir)/lib/intel64/libmkl_intel_lp64.a \
               $(LAdir)/lib/intel64/libmkl_gnu_thread.a \
               $(LAdir)/lib/intel64/libmkl_core.a \
               -Wl,--end-group -lgomp -lpthread -lm -ldl
```
and no errors while running

**Comment by rscohn2** [comment] 2021-03-31 11:51
The MKL package injects the proper ```-I<dir>``` but does not have a way to inject the ```-DMKL_LP64 -m64```. They are the default so it should not matter.
The MKL package injects: ```-lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl```. In another thread, I am working with spack developers on a way to have MKL inject the parallel libraries by controlling the spec (variant or some other mechanism), but for now I always provide mkl_sequential.

The last time you tested, I was incorrectly using libmkl_intel_ilp64 when HPL was not compiled with -DMKL_ILP64. This might have been the source of the problem. This is fixed by my last commit to #22607 so can you try again or wait until it is merged and try again?

**Comment by yellowhat** [comment] 2021-03-31 13:12
Thanks for the update. Just tried and it compiling and running.
The only thing is that it is working using MPI only, no OpenMP.
I can see that intel-oneapi-mkl does not expose the `threads=openmp` variant as `intel-mkl`.

**Comment by rscohn2** [comment] 2021-03-31 15:39
I am working on the variants like threads=openmp and it would be great if
you can test it after it is enabled.

**Comment by yellowhat** [comment] 2021-03-31 15:47
Absolutely, can you reference pull request that implements this?

Thanks

**Comment by rscohn2** [comment] 2021-03-31 15:50
We are discussing it here https://github.com/spack/spack/issues/22621 and I will notify you when there is a PR.

**Comment by yellowhat** [comment] 2021-03-31 15:51
Perfect. Thanks
