### ISSUE TITLE
Hashes in develop have changed

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#19147] opened 2020-10-04 21:00 UTC
I have some package installed before 075c3e0d9247e9c1716ac44e7052366ac59ff110. When I update Spack to a newer commit, all `spack install` commands try to reinstall all of my already installed packages. When I explicitly tell it to use a particular hash for the dependency, it is completely ignored and still rebuilds everything.

### Steps to reproduce the issue

```console
$ git clone https://github.com/spack/spack
$ git checkout 075c3e0d9247e9c1716ac44e7052366ac59ff110~1
$ spack install python
$ git checkout 075c3e0d9247e9c1716ac44e7052366ac59ff110
$ spack spec -I python
$ spack spec -I /hashofpython
```

### Information on your system

* **Spack:** 0.15.4-1279-eabfdba08f
* **Python:** 3.8.5
* **Platform:** darwin-catalina-ivybridge

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

@scottwittenburg I believe this bug was introduced in #18359, can you take a look?

**Comment by scottwittenburg** [comment] 2020-10-05 15:23
@adamjstewart Yes, I'll look into this.

**Comment by scottwittenburg** [comment] 2020-10-05 16:42
Maybe I'm doing it wrong, or maybe I'm not interpreting the results correctly.  This is what I get when I follow the steps to reproduce, outlined above.

```
Scotts-MacBook-Pro-2:spack scott$ git checkout 075c3e0d9247e9c1716ac44e7052366ac59ff110~1
Note: switching to '075c3e0d9247e9c1716ac44e7052366ac59ff110~1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 5558bc2b5 rocm-3.8.0 updates for hipblas, rocsolver, miopen-hip, rocalution, rocmvalidationsuite (#19031)
Scotts-MacBook-Pro-2:spack scott$ 
Scotts-MacBook-Pro-2:spack scott$  
Scotts-MacBook-Pro-2:spack scott$ spack install zlib
==> Warning: apple-clang@10.0.0 cannot build optimized binaries for "skylake". Using best target possible: "x86_64"
==> Installing zlib
==> No binary for zlib found: installing from source
==> Warning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check apple-clang@10.0.0 for further details]
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/c3/c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1.tar.gz
###################################################################################################################################################################################################################################### 100.0%
==> zlib: Executing phase: 'install'
[+] /Users/scott/Documents/spack/spack_installs/spack_path_placeholder/spack_path_placeholder/spac/darwin-catalina-x86_64/apple-clang-10.0.0/zlib-1.2.11-bceibuvwx5mlahykezmw22h6xadhdnop
Scotts-MacBook-Pro-2:spack scott$ 
Scotts-MacBook-Pro-2:spack scott$ 
Scotts-MacBook-Pro-2:spack scott$ spack spec -I zlib
Input spec
--------------------------------
 -   zlib

Concretized
--------------------------------
==> Warning: apple-clang@10.0.0 cannot build optimized binaries for "skylake". Using best target possible: "x86_64"
[+]  zlib@1.2.11%apple-clang@10.0.0+optimize+pic+shared arch=darwin-catalina-x86_64

Scotts-MacBook-Pro-2:spack scott$ 
Scotts-MacBook-Pro-2:spack scott$ 
Scotts-MacBook-Pro-2:spack scott$ git checkout 075c3e0d9247e9c1716ac44e7052366ac59ff110
Previous HEAD position was 5558bc2b5 rocm-3.8.0 updates for hipblas, rocsolver, miopen-hip, rocalution, rocmvalidationsuite (#19031)
HEAD is now at 075c3e0d9 Merge pull request #18359 from scottwittenburg/add-binary-distribution-cache-manager
Scotts-MacBook-Pro-2:spack scott$ 
Scotts-MacBook-Pro-2:spack scott$ 
Scotts-MacBook-Pro-2:spack scott$ spack find -l
==> 1 installed package
-- darwin-catalina-x86_64 / apple-clang@10.0.0 ------------------
bceibuv zlib@1.2.11
Scotts-MacBook-Pro-2:spack scott$ 
Scotts-MacBook-Pro-2:spack scott$ 
Scotts-MacBook-Pro-2:spack scott$ spack spec -I zlib
Input spec
--------------------------------
 -   zlib

Concretized
--------------------------------
==> Warning: apple-clang@10.0.0 cannot build optimized binaries for "skylake". Using best target possible: "x86_64"
 -   zlib@1.2.11%apple-clang@10.0.0+optimize+pic+shared arch=darwin-catalina-x86_64

Scotts-MacBook-Pro-2:spack scott$ spack spec -I /bceibuv
Input spec
--------------------------------
[+]  zlib@1.2.11%apple-clang@10.0.0+optimize+pic+shared arch=darwin-catalina-x86_64

Concretized
--------------------------------
[+]  zlib@1.2.11%apple-clang@10.0.0+optimize+pic+shared arch=darwin-catalina-x86_64

```

**Comment by scottwittenburg** [comment] 2020-10-05 16:47
I also tried in an ubuntu docker container, and in that case, taking that one step forward in spack commit history resulted in `zlib` concretizing to a new DAG hash.  Is that the problem you're talking about here?

**Comment by adamjstewart** [comment] 2020-10-05 19:31
Yes, it concretizes to a new DAG hash. At least on macOS with Python 3, it also prevents me from linking to a particular DAG hash.

**Comment by scheibelp** [comment] 2020-10-05 19:34
@tldahlgren who reviewed https://github.com/spack/spack/pull/18359: do you have a notion of why this would be happening?

**Comment by scottwittenburg** [comment] 2020-10-05 19:36
So it could be that adding the `full_hash` attribute in the database entry caused the DAG hash to change, I'm not sure.  But DAG hashes change from time to time, right?  So I assume this problem is bigger than just that.  Can you provide some more information to reproduce the failure to link to a particular DAG hash?  I'm not sure I understand that part of the problem.

**Comment by adamjstewart** [comment] 2020-10-05 19:44
Okay, I'm unable to reproduce the DAG hash linking problem with a single package, but it works with a package with multiple dependencies. For example, on develop:
```console
$ spack spec -Il py-setuptools
Input spec
--------------------------------
 -   py-setuptools

Concretized
--------------------------------
==> Warning: apple-clang@12.0.0 cannot build optimized binaries for "ivybridge". Using best target possible: "x86_64"
 -   uohctia  py-setuptools@50.1.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   by37rey      ^python@3.8.5%apple-clang@12.0.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=darwin-catalina-x86_64
 -   sbhwqzb          ^bzip2@1.0.8%apple-clang@12.0.0+shared arch=darwin-catalina-x86_64
 -   qa54myt              ^diffutils@3.7%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   rc75pzw                  ^libiconv@1.16%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   cktmwaj          ^expat@2.2.9%apple-clang@12.0.0~libbsd arch=darwin-catalina-x86_64
 -   5ejah5f          ^gdbm@1.18.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   e5442ry              ^readline@8.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   diqhryy                  ^ncurses@6.2%apple-clang@12.0.0~symlinks+termlib arch=darwin-catalina-x86_64
 -   7k6uoyl                      ^pkgconf@1.7.3%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   ih77fl3          ^gettext@0.21%apple-clang@12.0.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=darwin-catalina-x86_64
 -   6cvazfn              ^libxml2@2.9.10%apple-clang@12.0.0~python arch=darwin-catalina-x86_64
 -   dsc5ym7                  ^xz@5.2.5%apple-clang@12.0.0~pic arch=darwin-catalina-x86_64
 -   j5nn3tx                  ^zlib@1.2.11%apple-clang@12.0.0+optimize+pic+shared arch=darwin-catalina-x86_64
 -   u2makpc              ^tar@1.32%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   bziarwx          ^libffi@3.3%apple-clang@12.0.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=darwin-catalina-x86_64
 -   t5onyq6          ^openssl@1.1.1g%apple-clang@12.0.0+systemcerts arch=darwin-catalina-x86_64
 -   3tdrhoj              ^perl@5.30.3%apple-clang@12.0.0+cpanm+shared+threads arch=darwin-catalina-x86_64
 -   54oxvjs                  ^berkeley-db@18.1.40%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   i754rrc          ^sqlite@3.33.0%apple-clang@12.0.0+column_metadata+fts~functions~rtree arch=darwin-catalina-x86_64

$ spack find -l python
==> 1 installed package
-- darwin-catalina-x86_64 / apple-clang@12.0.0 ------------------
xaouivq python@3.8.5
$ spack spec -Il py-setuptools ^/xaouivq
Input spec
--------------------------------
 -   py-setuptools
 -       ^python@3.8.5%apple-clang@12.0.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=darwin-catalina-x86_64
 -           ^bzip2@1.0.8%apple-clang@12.0.0+shared arch=darwin-catalina-x86_64
 -           ^expat@2.2.9%apple-clang@12.0.0~libbsd arch=darwin-catalina-x86_64
 -           ^gdbm@1.18.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -               ^readline@8.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -                   ^ncurses@6.2%apple-clang@12.0.0~symlinks+termlib arch=darwin-catalina-x86_64
 -           ^gettext@0.21%apple-clang@12.0.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=darwin-catalina-x86_64
 -               ^libiconv@1.16%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -               ^libxml2@2.9.10%apple-clang@12.0.0~python arch=darwin-catalina-x86_64
 -                   ^xz@5.2.5%apple-clang@12.0.0~pic arch=darwin-catalina-x86_64
 -                   ^zlib@1.2.11%apple-clang@12.0.0+optimize+pic+shared arch=darwin-catalina-x86_64
 -               ^tar@1.32%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -           ^libffi@3.3%apple-clang@12.0.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=darwin-catalina-x86_64
 -           ^openssl@1.1.1g%apple-clang@12.0.0+systemcerts arch=darwin-catalina-x86_64
 -           ^sqlite@3.33.0%apple-clang@12.0.0+column_metadata+fts~functions~rtree arch=darwin-catalina-x86_64

Concretized
--------------------------------
 -   uohctia  py-setuptools@50.1.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   by37rey      ^python@3.8.5%apple-clang@12.0.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=darwin-catalina-x86_64
 -   sbhwqzb          ^bzip2@1.0.8%apple-clang@12.0.0+shared arch=darwin-catalina-x86_64
 -   qa54myt              ^diffutils@3.7%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   rc75pzw                  ^libiconv@1.16%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   cktmwaj          ^expat@2.2.9%apple-clang@12.0.0~libbsd arch=darwin-catalina-x86_64
 -   5ejah5f          ^gdbm@1.18.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   e5442ry              ^readline@8.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   diqhryy                  ^ncurses@6.2%apple-clang@12.0.0~symlinks+termlib arch=darwin-catalina-x86_64
 -   7k6uoyl                      ^pkgconf@1.7.3%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   ih77fl3          ^gettext@0.21%apple-clang@12.0.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=darwin-catalina-x86_64
 -   6cvazfn              ^libxml2@2.9.10%apple-clang@12.0.0~python arch=darwin-catalina-x86_64
 -   dsc5ym7                  ^xz@5.2.5%apple-clang@12.0.0~pic arch=darwin-catalina-x86_64
 -   j5nn3tx                  ^zlib@1.2.11%apple-clang@12.0.0+optimize+pic+shared arch=darwin-catalina-x86_64
 -   u2makpc              ^tar@1.32%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   bziarwx          ^libffi@3.3%apple-clang@12.0.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=darwin-catalina-x86_64
 -   t5onyq6          ^openssl@1.1.1g%apple-clang@12.0.0+systemcerts arch=darwin-catalina-x86_64
 -   3tdrhoj              ^perl@5.30.3%apple-clang@12.0.0+cpanm+shared+threads arch=darwin-catalina-x86_64
 -   54oxvjs                  ^berkeley-db@18.1.40%apple-clang@12.0.0 arch=darwin-catalina-x86_64
 -   i754rrc          ^sqlite@3.33.0%apple-clang@12.0.0+column_metadata+fts~functions~rtree arch=darwin-catalina-x86_64
```
Even though nothing about these package has changed, the python I installed before that commit can no longer be linked into an installation, and `spack install py-setuptools ^/hash` starts building every package from scratch.

**Comment by scottwittenburg** [comment] 2020-10-05 21:09
Thanks for the extra info.  Based on that, I installed `py-setuptools` to depend on `python@3.8.5` using the spack from the commit before #18359, and then I checked out my change, at which point I could see the result you pasted above.

If I remove only this `else` condition from my change ([here](https://github.com/spack/spack/pull/18359/files#diff-f8b3ba3a3e9600f6d136b31698f33be7R1556)), I see all those hashes as installed.  

One of the goals of my change was to support an option to `spack install` which would force spack to install from source if the `full_hash` computed locally on the concrete spec does not match the one stored remotely in the spec.yaml stored on the binary mirror.  The way I understood it, for this to work, I needed to update how specs were serialized/deserialized to/from node dictionaries, thus the specific part of my change above.  

So, where do we need to go from here?

**Comment by scheibelp** [comment] 2020-10-05 21:17
`to_node_dict` is used to compose the hash, so adding more fields will change all the hashes.

If that is necessary for you original PR (#18359) to work, I think we should revert it for now and discuss why (and we'll need to make it part of a major release). If it isn't, then you can revert just that change. I'm guessing it is important but don't currently have time to review the intent of the PR.

**Comment by scheibelp** [comment] 2020-10-05 21:17
@scottwittenburg would you be able to create a revert of that PR and reopen a copy of #18359 for more discussion?

**Comment by scottwittenburg** [comment] 2020-10-05 21:27
@scheibelp In that case do you know of a way to revert two PRs at once?  I merged #19132 to fix some other issue related to #18359 in the meantime.

**Comment by scheibelp** [comment] 2020-10-05 21:29
> In that case do you know of a way to revert two PRs at once? I merged #19132 to fix some other issue related to #18359 in the meantime.

If each PR was squashed into one commit, create a single new branch, and on that branch run two `git revert` commands. They should run in "reverse order" (i.e. revert #19132 first). Does that seem reasonable?

**Comment by scottwittenburg** [comment] 2020-10-05 21:41
Yes thanks, seems reasonable.  Except since #18359 was actually three logical commits, I assume I should revert them independently.

**Comment by scheibelp** [comment] 2020-10-05 21:45
> Yes thanks, seems reasonable. Except since #18359 was actually three logical commits, I assume I should revert them independently.

Yes that sounds like the best way to do it.

**Comment by scottwittenburg** [comment] 2020-10-05 21:45
Oh, but I did hit "squash and merge", so nevermind, I guess it's just two reverts.  

Ok, best to just get this over with.  Reverts on the way.

**Comment by scottwittenburg** [comment] 2020-10-05 22:02
Turns out it was three PRs to revert:

1. 7cfdf6197 Fix location in spec.yaml where we look for full_hash (#19132)
2. d3d98075c Fix fetch of spec.yaml files from buildcache (#19101)
3. 075c3e0d9 Merge pull request #18359 from scottwittenburg/add-binary-distribution-cache-manager

As for reopening a copy of #18359, should I just merge all those changes into a new branch and create a new PR for that?  Otherwise, what does it mean to open a copy of a closed PR?

**Comment by scheibelp** [comment] 2020-10-05 22:08
> As for reopening a copy of #18359, should I just merge all those changes into a new branch and create a new PR for that? Otherwise, what does it mean to open a copy of a closed PR?

I think the former makes the most sense

**Comment by haampie** [comment] 2020-10-06 07:25
Just a few questions about these PRs and how breaking changes are dealt with:

1. @scheibelp mentioned if this PR is breaking, it can only enter a major release:

   > and we'll need to make it part of a major release

   How would it be possible to land it in a major release without it residing in `develop` first? This PR was reverted from `develop` because it broke hashes, but isn't that part of living on the `develop` branch? Shouldn't `develop` receive all new contributions breaking or not, and only non-breaking patches are backported to older minor versions?

2. I'm kind of relying on this full hash / binary cache behavior already (or at least I was enthusiastically awaiting these PRs), and I'm inclined to say that the current behavior without these PRs is buggy, because you might end up with binaries that do not reflect package.py. I would rather see @scottwittenburg's PRs as bugfixes rather than new features.

3. Is there an obvious way to accomplish the same without breaking hashes?

Thanks!

**Comment by tgamblin** [comment] 2020-10-06 17:31
> Spack no longer recognizes previously installed packages

Spack doesn't forget packages.  They're all there, in `spack find`.  You *should* be able to refer to them by hash.  The part of this that is a bug is this:

> When I explicitly tell it to use a particular hash for the dependency, it is completely ignored and still rebuilds everything.

Do you have a reproducer for this?

**Comment by scheibelp** [comment] 2020-10-06 18:28
@haampie 

> scheibelp mentioned if this PR is breaking, it can only enter a major release:
> How would it be possible to land it in a major release without it residing in develop first?

Apologies - I think I gave the wrong impression: It can still be in develop (even if it changes the hashes). The problem in this case is that we didn't properly track that this was going to change the hashes. Usually we examine such PRs more closely.

The follow-up (https://github.com/spack/spack/pull/19209) can be merged pending some minor additional review to check into the hashing aspects.

**Comment by adamjstewart** [comment] 2020-10-06 18:40
> Do you have a reproducer for this?

Yes, I updated the initial comment (switched zlib with python). That should be enough to reproduce the issue. You'll see the same thing I saw in https://github.com/spack/spack/issues/19147#issuecomment-703848640

**Comment by adamjstewart** [comment] 2020-10-10 21:48
Now that #18359 has been reverted, should we close this issue, or leave it open for more discussion?

**Closed as completed** 2020-12-20 23:44 UTC
Labels: bug, impact-high, hash-change
