### ISSUE TITLE
Perform smoke tests in temporary directory

### ISSUE THREAD

**Issue by sethrj** [LLNL/spack#23673] opened 2021-05-17 10:59 UTC
Currently post-installation tests are usually run inside the install prefix and must be cleaned before reusing. I suggest a mechanism for running inside a temporary directory.

### Rationale

Installation tests, especially for libraries, can be messy (e.g. create a `build` dir with many files), and the result of one build might affect another build resulting in a false positive or negative.

Furthermore, it's possible that users of a shared spack installation other than the original installer would want to test, or spack is installed onto a read-only device. Currently the test system assumes the user testing has full write privileges on the installation prefix.

Finally, packages might `make clean` the test builds to avoid polluting the next run or leaving detritus in the installation directories, but that behavior interferes with the ability to debug a smoke test if it fails. The better solution is a temporary directory with a `--keep-stage` option.

### Description

I think a `self.test_build_dir` or something could easily replace the handrolled smoke test "build" dirs in place.

### General information

- [x] Spack version 0.16.1-2652-39a4f3ba88
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tldahlgren** [comment] 2021-05-17 23:08
Thank you for taking the time to create this issue.

> Currently post-installation tests are usually run inside the install prefix and must be cleaned before reusing. I suggest a mechanism for running inside a temporary directory.

Post-installation tests do not have to be run from inside the installation prefix. Early examples using files cached from the build did that for simplicity (and didn't typically clean up after themselves, which is something that needs to be addressed).

Spack *does* create a test suite stage directory *and*, for each spec, a test stage directory.  

Post-installation tests depending on custom files (https://spack.readthedocs.io/en/latest/packaging_guide.html#adding-custom-files) rely on those files being copied to the test stage directory and will build and run examples, when appropriate, in the spec-specific subdirectory.

> 
> ### Rationale
> Installation tests, especially for libraries, can be messy (e.g. create a `build` dir with many files), and the result of one build might affect another build resulting in a false positive or negative.
> 
> Furthermore, it's possible that users of a shared spack installation other than the original installer would want to test, or spack is installed onto a read-only device. Currently the test system assumes the user testing has full write privileges on the installation prefix.

This is an *excellent* reason for providing more infrastructure for (automatically) copying cached files to the stage directory IMO.

> 
> Finally, packages might `make clean` the test builds to avoid polluting the next run or leaving detritus in the installation directories, but that behavior interferes with the ability to debug a smoke test if it fails. The better solution is a temporary directory with a `--keep-stage` option.

The `--keep-stage` option exists for stand-alone tests and is (or still should be) enabled by default if tests fail just for that purpose.  The problem is it doesn't currently apply to files cached at build time.

**Comment by sethrj** [comment] 2021-05-18 01:05
Thanks for the response. I'm still a little confused about the test functionality, and this feature is new enough that it's easier for me to look through examples in other packages rather than try to understand based on the documentation alone 😬 so I do appreciate updates for both the explanations in the documentation and use cases in existing packages.

> Post-installation tests do not have to be run from inside the installation prefix. Early examples using files cached from the build did that for simplicity (and didn't typically clean up after themselves, which is something that needs to be addressed).

Gotcha, those are probably the ones I looked at.

> Spack _does_ create a test suite stage directory _and_, for each spec, a test stage directory.

Aha, that was not obvious to me 😄 good to know, so my feature request is already implemented! We can probably then close this issue and focus on updating the packages that build inside their install prefix.

> Post-installation tests depending on custom files (https://spack.readthedocs.io/en/latest/packaging_guide.html#adding-custom-files) rely on those files being copied to the test stage directory and will build and run examples, when appropriate, in the spec-specific subdirectory.

So it's the package's responsibility to copy the packages from `self.install_test_root` to `self.test_suite.current_test_data_dir`?

**Comment by tldahlgren** [comment] 2021-05-18 01:12
> Aha, that was not obvious to me 😄 good to know, so my feature request is already implemented! We can probably then close this issue and focus on updating the packages that build inside their install prefix.

Can we hold off on closing the issue?  I've automated the copy of cached test files to the test stage directory and am modifying several packages to build in the test stage directory.  Not quite ready for a PR but hopefully soon.

> 
> > Post-installation tests depending on custom files (https://spack.readthedocs.io/en/latest/packaging_guide.html#adding-custom-files) rely on those files being copied to the test stage directory and will build and run examples, when appropriate, in the spec-specific subdirectory.
> 
> So it's the package's responsibility to copy the packages from `self.install_test_root` to `self.test_suite.current_test_data_dir`?

It wouldn't be to `self.test_suite.current_test_data_dir`.  That's for custom files.

Depending on feedback -- once I make a PR -- I'm expecting that you'll be able to access copies of the cached test files in `self.test_suite.current_test_cache_dir`.

**Comment by tldahlgren** [comment] 2021-05-18 02:15
#23713 Should address the issue raised here

**Closed as completed** 2021-05-25 14:24 UTC
Labels: feature, stand-alone-tests
