### ISSUE TITLE
Installation issue: llvm

### ISSUE THREAD

**Issue by robertu94** [LLNL/spack#35813] opened 2023-03-03 15:27 UTC
### Steps to reproduce the issue

Installing LLVM on Fedora 37 using gcc12.2.1 seems to end an a failure regarding libunwind.

```console
$ spack spec -I 
Input spec
--------------------------------
 -   llvm+clang~compiler-rt~gold~libcxx~lld~lldb~omp_as_runtime~polly targets=x86

Concretized
--------------------------------
 -   llvm@15.0.7%gcc@12.2.1+clang~compiler-rt~cuda~flang~gold+internal_unwind~ipo~libcxx~link_llvm_dylib~lld~lldb+llvm_dylib~mlir~omp_as_runtime~omp_debug~omp_tsan~polly~python~split_dwarf~z3 build_system=cmake build_type=Release patches=3dc9bc1 shlib_symbol_version=none targets=x86 version_suffix=none arch=linux-fedora37-icelake
[+]      ^cmake@3.22.2%gcc@12.2.1~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-fedora37-icelake
[+]      ^hwloc@2.8.0%gcc@12.2.1~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-fedora37-icelake
[+]          ^libpciaccess@0.16%gcc@12.2.1 build_system=autotools arch=linux-fedora37-icelake
[+]              ^libtool@2.4.7%gcc@12.2.1 build_system=autotools arch=linux-fedora37-icelake
[+]              ^util-macros@1.19.3%gcc@12.2.1 build_system=autotools arch=linux-fedora37-icelake
[+]          ^libxml2@2.10.3%gcc@12.2.1~python build_system=autotools arch=linux-fedora37-icelake
[+]              ^libiconv@1.16%gcc@12.2.1 build_system=autotools libs=shared,static arch=linux-fedora37-icelake
[+]          ^ncurses@6.3%gcc@12.2.1~symlinks+termlib abi=none build_system=autotools arch=linux-fedora37-icelake
[+]      ^ninja@1.10.2%gcc@12.2.1 build_system=generic arch=linux-fedora37-icelake
[+]      ^perl-data-dumper@2.173%gcc@12.2.1 build_system=perl arch=linux-fedora37-icelake
[+]          ^perl@5.36.0%gcc@12.2.1+cpanm+shared+threads build_system=generic arch=linux-fedora37-icelake
[+]              ^berkeley-db@18.1.40%gcc@12.2.1+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-fedora37-icelake
[+]      ^pkgconf@1.8.0%gcc@12.2.1 build_system=autotools arch=linux-fedora37-icelake
[+]      ^python@3.8.15%gcc@12.2.1+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,4c24573,f2fd060 arch=linux-fedora37-icelake
[+]          ^bzip2@1.0.8%gcc@12.2.1~debug~pic+shared build_system=generic arch=linux-fedora37-icelake
[+]              ^diffutils@3.8%gcc@12.2.1 build_system=autotools arch=linux-fedora37-icelake
[+]          ^expat@2.4.8%gcc@12.2.1+libbsd build_system=autotools arch=linux-fedora37-icelake
[+]              ^libbsd@0.11.5%gcc@12.2.1 build_system=autotools arch=linux-fedora37-icelake
[+]                  ^libmd@1.0.4%gcc@12.2.1 build_system=autotools arch=linux-fedora37-icelake
[+]          ^gdbm@1.23%gcc@12.2.1 build_system=autotools arch=linux-fedora37-icelake
[+]          ^gettext@0.21.1%gcc@12.2.1+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-fedora37-icelake
[+]              ^tar@1.34%gcc@12.2.1 build_system=autotools zip=pigz arch=linux-fedora37-icelake
[+]          ^libffi@3.4.2%gcc@12.2.1 build_system=autotools arch=linux-fedora37-icelake
[+]          ^libxcrypt@4.4.33%gcc@12.2.1~obsolete_api build_system=autotools arch=linux-fedora37-icelake
[+]          ^openssl@1.1.1s%gcc@12.2.1~docs~shared build_system=generic certs=mozilla arch=linux-fedora37-icelake
[+]              ^ca-certificates-mozilla@2022-10-11%gcc@12.2.1 build_system=generic arch=linux-fedora37-icelake
[+]          ^readline@8.2%gcc@12.2.1 build_system=autotools patches=bbf97f1 arch=linux-fedora37-icelake
[+]          ^sqlite@3.40.0%gcc@12.2.1+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-fedora37-icelake
[+]          ^util-linux-uuid@2.38.1%gcc@12.2.1 build_system=autotools arch=linux-fedora37-icelake
[+]          ^xz@5.2.7%gcc@12.2.1~pic build_system=autotools libs=shared,static arch=linux-fedora37-icelake
[+]      ^zlib@1.2.13%gcc@12.2.1+optimize+pic+shared build_system=makefile arch=linux-fedora37-icelake

...
```

### Error message

<details><summary>Error message</summary><pre>
CMake Error at /home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-src/libunwind/src/CMakeLists.txt:109 (message):
  Compiler doesn't support generation of unwind tables if exception support
  is disabled.  Building libunwind DSO with runtime dependency on C++ ABI
  library is not supported.

-- Configuring incomplete, errors occurred!
FAILED: runtimes/runtimes-stamps/runtimes-configure /home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/runtimes/runtimes-stamps/runtimes-configure 
cd /home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/runtimes/runtimes-bins && /usr/bin/cmake -DCMAKE_C_COMPILER=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/clang -DCMAKE_CXX_COMPILER=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/clang++ -DCMAKE_ASM_COMPILER=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/clang -DCMAKE_AR=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/llvm-ar -DCMAKE_RANLIB=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/llvm-ranlib -DCMAKE_NM=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/llvm-nm -DCMAKE_OBJDUMP=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/llvm-objdump -DCMAKE_OBJCOPY=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/llvm-objcopy -DCMAKE_STRIP=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/llvm-strip -DCMAKE_READELF=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/llvm-readelf -DCMAKE_C_COMPILER_TARGET=x86_64-unknown-linux-gnu -DCMAKE_CXX_COMPILER_TARGET=x86_64-unknown-linux-gnu -DCMAKE_ASM_COMPILER_TARGET=x86_64-unknown-linux-gnu -DCMAKE_INSTALL_PREFIX=/home/runderwood/git/contrib/spack/opt/spack/linux-fedora37-icelake/gcc-12.2.1/llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv -DLLVM_BINARY_DIR=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4 -DLLVM_CONFIG_PATH=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/bin/llvm-config -DLLVM_ENABLE_WERROR=OFF -DLLVM_HOST_TRIPLE=x86_64-unknown-linux-gnu -DLLVM_HAVE_LINK_VERSION_SCRIPT=1 -DLLVM_USE_RELATIVE_PATHS_IN_DEBUG_INFO=OFF -DLLVM_USE_RELATIVE_PATHS_IN_FILES=OFF -DLLVM_LIT_ARGS=-sv -DLLVM_SOURCE_PREFIX= -DPACKAGE_VERSION=15.0.7 -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja-build -DCMAKE_C_COMPILER_LAUNCHER= -DCMAKE_CXX_COMPILER_LAUNCHER= -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCOMPILER_RT_BUILD_BUILTINS=Off -DLLVM_INCLUDE_TESTS=ON -DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-linux-gnu -DLLVM_ENABLE_PROJECTS_USED=ON -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=ON -DLLVM_BUILD_TOOLS=ON -DCMAKE_C_COMPILER_WORKS=ON -DCMAKE_CXX_COMPILER_WORKS=ON -DCMAKE_ASM_COMPILER_WORKS=ON -DHAVE_LLVM_LIT=ON -DLLVM_ENABLE_RUNTIMES=libunwind -GNinja -S /home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-src/llvm/runtimes/../../runtimes -B /home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/runtimes/runtimes-bins && /usr/bin/cmake -E touch /home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/runtimes/runtimes-stamps/runtimes-configure
ninja: build stopped: subcommand failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/ninja' '-j16' '-v'

2 errors found in build log:
     11439    -- Performing Test CXX_SUPPORTS_FUNWIND_TABLES_FLAG
     11440    -- Performing Test CXX_SUPPORTS_FUNWIND_TABLES_FLAG - Success
     11441    -- Performing Test CXX_SUPPORTS_FNO_EXCEPTIONS_FLAG
     11442    -- Performing Test CXX_SUPPORTS_FNO_EXCEPTIONS_FLAG - Failed
     11443    -- Performing Test CXX_SUPPORTS_FNO_RTTI_FLAG
     11444    -- Performing Test CXX_SUPPORTS_FNO_RTTI_FLAG - Failed
  >> 11445    CMake Error at /home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/
              spack-src/libunwind/src/CMakeLists.txt:109 (message):
     11446      Compiler doesn't support generation of unwind tables if exception support
     11447      is disabled.  Building libunwind DSO with runtime dependency on C++ ABI
     11448      library is not supported.
     11449    
     11450    
     11451    -- Configuring incomplete, errors occurred!
  >> 11452    FAILED: runtimes/runtimes-stamps/runtimes-configure /home/runderwood/scratch/spackstage/spack-stage-llvm-15.
              0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/runtimes/runtimes-stamps/runtimes-configure
     11453    cd /home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-
              nvlx7t4/runtimes/runtimes-bins && /usr/bin/cmake -DCMAKE_C_COMPILER=/home/runderwood/scratch/spackstage/spac
              k-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/clang -DCMAKE_CXX_COMPILER=/h
              ome/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7
              t4/./bin/clang++ -DCMAKE_ASM_COMPILER=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwi
              gkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/clang -DCMAKE_AR=/home/runderwood/scratch/spackstage/spack-
              stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/llvm-ar -DCMAKE_RANLIB=/home/ru
              nderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./b
              in/llvm-ranlib -DCMAKE_NM=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345
              k6j5ryqbnv/spack-build-nvlx7t4/./bin/llvm-nm -DCMAKE_OBJDUMP=/home/runderwood/scratch/spackstage/spack-stage
              -llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/llvm-objdump -DCMAKE_OBJCOPY=/home/r
              underwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./
              bin/llvm-objcopy -DCMAKE_STRIP=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46b
              vd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/llvm-strip -DCMAKE_READELF=/home/runderwood/scratch/spackstage/spa
              ck-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/./bin/llvm-readelf -DCMAKE_C_COMPI
              LER_TARGET=x86_64-unknown-linux-gnu -DCMAKE_CXX_COMPILER_TARGET=x86_64-unknown-linux-gnu -DCMAKE_ASM_COMPILE
              R_TARGET=x86_64-unknown-linux-gnu -DCMAKE_INSTALL_PREFIX=/home/runderwood/git/contrib/spack/opt/spack/linux-
              fedora37-icelake/gcc-12.2.1/llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv -DLLVM_BINARY_DIR=/home/runderwood/
              scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4 -DLLVM_CONFI
              G_PATH=/home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-bu
              ild-nvlx7t4/bin/llvm-config -DLLVM_ENABLE_WERROR=OFF -DLLVM_HOST_TRIPLE=x86_64-unknown-linux-gnu -DLLVM_HAVE
              _LINK_VERSION_SCRIPT=1 -DLLVM_USE_RELATIVE_PATHS_IN_DEBUG_INFO=OFF -DLLVM_USE_RELATIVE_PATHS_IN_FILES=OFF -D
              LLVM_LIT_ARGS=-sv -DLLVM_SOURCE_PREFIX= -DPACKAGE_VERSION=15.0.7 -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PRO
              GRAM=/usr/bin/ninja-build -DCMAKE_C_COMPILER_LAUNCHER= -DCMAKE_CXX_COMPILER_LAUNCHER= -DCMAKE_EXPORT_COMPILE
              _COMMANDS=1 -DCOMPILER_RT_BUILD_BUILTINS=Off -DLLVM_INCLUDE_TESTS=ON -DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-unk
              nown-linux-gnu -DLLVM_ENABLE_PROJECTS_USED=ON -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=ON -DLLVM_BUILD_TOOLS=ON 
              -DCMAKE_C_COMPILER_WORKS=ON -DCMAKE_CXX_COMPILER_WORKS=ON -DCMAKE_ASM_COMPILER_WORKS=ON -DHAVE_LLVM_LIT=ON -
              DLLVM_ENABLE_RUNTIMES=libunwind -GNinja -S /home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7
              t4xwigkmh46bvd345k6j5ryqbnv/spack-src/llvm/runtimes/../../runtimes -B /home/runderwood/scratch/spackstage/sp
              ack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-nvlx7t4/runtimes/runtimes-bins && /usr/bi
              n/cmake -E touch /home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbn
              v/spack-build-nvlx7t4/runtimes/runtimes-stamps/runtimes-configure
     11454    ninja: build stopped: subcommand failed.

See build log for details:
  /home/runderwood/scratch/spackstage/spack-stage-llvm-15.0.7-nvlx7t4xwigkmh46bvd345k6j5ryqbnv/spack-build-out.txt

</pre></details>

### Information on your system

* **Spack:** 0.20.0.dev0 (e5bd319c19d1c5bb2f41e708c77a477a3f6658b8)
* **Python:** 3.11.2
* **Platform:** linux-fedora37-icelake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/10883442/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/10883443/spack-build-out.txt)

@haampie @ trws

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alecbcs** [comment] 2023-05-06 06:00
Duplicate of #35819. 

(Technically @robertu94 reported the issue here first but there's a more active conversation on #35819.)

**Closed as completed by alecbcs** 2023-05-06 06:00 UTC
Labels: build-error
