### ISSUE TITLE
Environment `view:projections` doesn't apply to PythonPackage

### ISSUE THREAD

**Issue by blue42u** [LLNL/spack#32365] opened 2022-08-25 03:23 UTC
### Steps to reproduce

In an environment, specifying specific projections for some packages doesn't seem to work, only the catch-`all:` clause is used. So far I've only identified PythonPackages as affected:
```console
$ cat x/spack.yaml
spack:
  specs:
  - diffutils
  - meson
  - py-black

  view:
    default:
      root: view
      projections:
        py-black: py-black
        meson: meson
        all: other
$ spack -e x install
$ ls x/view
other
$ ls x/view/other/bin/{meson,black}
x/view/other/bin/black  x/view/other/bin/meson
```

### Error message

There should be 3 directories in `x/view/other`: `py-black`, `meson` and `other` containing Black, Meson and all other packages respectively.

### Information on your system

* **Spack:** 0.19.0.dev0 (c56abe424733105388f3635cf90d7fade88131c7)
* **Python:** 3.10.6
* **Platform:** linux-debianunstable-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2023-05-03 15:22
Confirmed in 

* **Spack:** 0.20.0.dev0 (11aa2d721e2a7cc0b1ead7687262545e95b17685)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

**Comment by haampie** [comment] 2024-02-15 11:26
This is by design: extensions always go into the dir of the package they extend.

I'll close this, but if you think the design is wrong, feel free to reopen.

**Closed as completed by haampie** 2024-02-15 11:26 UTC
Labels: bug, impact-low, environments
