### ISSUE TITLE
installed package jpeg not found

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [LLNL/spack#5293] opened 2017-09-06 16:55 UTC
Hi, I am not sure if this happens to be related to #5281 #5190 but R packages that require jpeg no longer work:

```
[root@node141 spack]# git log | head
commit feefdedadf224315d69ef2f6da1fafd6338bba5a
Author: Christoph Junghans <christoph.junghans@gmail.com>
Date:   Tue Sep 5 13:15:08 2017 -0600

    nauty: shared libraries (#5207)

commit 41d8981ab5b5e912d38e201b71b981ef0f17e20e
Author: Massimiliano Culpo <massimiliano.culpo@googlemail.com>
Date:   Tue Sep 5 17:15:25 2017 +0200
```

```
[root@node141 spack]# spack load -r r-zoo
==> Error: Package jpeg not found.
```

```
[root@node141 spack]# spack find | grep jpeg
libjpeg-turbo@1.5.0
jpeg@9b
libjpeg-turbo@1.5.0
r-jpeg@0.1-8
```
Concreteization works though I see:

```
[root@node141 spack]# spack -d load -r r-zoo                                                                                                                                                                                                  
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> Error: Package jpeg not found.
Traceback (most recent call last):
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/main.py", line 440, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/main.py", line 356, in _invoke_spack_command
    return_val = command(parser, args)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/cmd/module.py", line 267, in module
    callbacks[args.subparser_name](module_type, specs, args)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/cmd/module.py", line 134, in loads
    for spec in specs if os.path.exists(module_cls(spec).file_name)]
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/modules.py", line 265, in __init__
    self.pkg = spec.package  # Just stored for convenience
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/spec.py", line 1291, in package
    return spack.repo.get(self)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/repository.py", line 74, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/repository.py", line 317, in get
    return self.repo_for_pkg(spec).get(spec)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/repository.py", line 74, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/repository.py", line 567, in get
    raise UnknownPackageError(spec.name)
spack.repository.UnknownPackageError: Package jpeg not found.
```

This still works on my testing branch which is from way back in June.

```
[root@node141 spack]# git branch
  develop
  master
* testing
[root@node141 spack]# git log | head

commit 7d59197b7b056ce4525b3faccdcaa7f06519c886
Author: Douglas Duckworth <quackmaster@protonmail.com>
Date:   Thu Jun 29 14:42:56 2017 -0400

    added numpy 1.13 - modified albacore to use 1.13 (#4639)
    
    * albacore 1.24 requires numpy 1.13 - added numpy 1.13
    
    * added numpy 1.13
```

**Comment by JusticeForMikeBrown** [comment] 2017-09-06 17:09
```
[root@node141 spack]# spack find -p -l -v jpeg
==> 3 installed packages.
-- linux-rhel6-x86_64 / gcc@4.4.6 -------------------------------
rue73bc    libjpeg-turbo@1.5.0  /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.6/libjpeg-turbo-1.5.0-rue73bcgjpn4m4ctt4wicsqxc7tgm2zj

-- linux-rhel6-x86_64 / gcc@6.3.0 -------------------------------
xm3nnrp    jpeg@9b              /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-6.3.0/jpeg-9b-xm3nnrpn2eclrcfzsfhkacyt6etnzi4w
56ibsvd    libjpeg-turbo@1.5.0  /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-6.3.0/libjpeg-turbo-1.5.0-56ibsvdkdzl55qmgordmlvsgvjvlqwx7
```


```
[root@node141 spack]# ls -ltr /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-6.3.0/libjpeg-turbo-1.5.0-56ibsvdkdzl55qmgordmlvsgvjvlqwx7
total 16
drwxr-xr-x 4 root root 4096 Sep  5 12:34 share
drwxr-xr-x 2 root root 4096 Sep  5 12:34 include
drwxr-xr-x 3 root root 4096 Sep  5 12:34 lib
drwxr-xr-x 2 root root 4096 Sep  5 12:34 bin

[root@node141 spack]# ls -ltr /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-6.3.0/jpeg-9b-xm3nnrpn2eclrcfzsfhkacyt6etnzi4w
total 16
drwxr-xr-x 3 root root 4096 Apr 21 15:35 share
drwxr-xr-x 2 root root 4096 Apr 21 15:35 include
drwxr-xr-x 2 root root 4096 Apr 21 15:35 lib
drwxr-xr-x 2 root root 4096 Apr 21 15:35 bin

```

**Comment by JusticeForMikeBrown** [comment] 2017-09-06 17:29
On the testing branch:

[root@node141 spack]# spack find jpeg                                                                                                                                                                                                  
==> 1 installed packages.
-- linux-rhel6-x86_64 / gcc@6.3.0 -------------------------------
jpeg@9b

So it seems when I installed a few things like `libjpeg-turbo` on the develop branch that caused problems?  I don't understand why though since R depends upon 'jpeg` and not `libjpeg-turbo?`

**Comment by JusticeForMikeBrown** [comment] 2017-09-06 17:40
OK

I switched to the develop branch and removed all of the programs which were installed within that branch including `libjpeg-turbo` however

```
[root@node141 spack]# spack find -l -v jpeg
==> 2 installed packages.
-- linux-rhel6-x86_64 / gcc@4.4.6 -------------------------------
rue73bc libjpeg-turbo@1.5.0

-- linux-rhel6-x86_64 / gcc@6.3.0 -------------------------------
xm3nnrp jpeg@9b
[root@node141 spack]# spack load -r r-zoo r-yaml
==> Error: Package jpeg not found.
```
So `jpeg` seems to be present but not found?  Do I need to `reindex?`

**Comment by JusticeForMikeBrown** [comment] 2017-09-06 17:43
`reindex` did not work.

**Comment by scheibelp** [comment] 2017-09-06 18:04
#5281 points to https://github.com/LLNL/spack/pull/5190 which made jpeg a virtual dependency, so that could have affected packages built with jpeg. Deleting everything and doing a reindex ought to have worked at least (to be sure - you deleted everything under `spack/opt`?). Also I'm not sure why 

```
spack load -r r-zoo
```

would have worked since it isn't present in `spack find`. Are those packages installed in `spack/opt`?

**Comment by JusticeForMikeBrown** [comment] 2017-09-06 18:30
Hi @scheibelp 

So I need to reinstall everything that depends upon 'jpeg'?  That's **many** R packages as well as a few Python ones.  

There must be a better way to address this issue.

**Comment by scheibelp** [comment] 2017-09-07 02:54
@JusticeForMikeBrown FYI I think #5281 is a different issue than this (although both stem from #5190) - `spack spec r-zoo` runs fine.

I think the issue in this case is that Spack tries to find jpeg in the package repository but only searches the central repository. #5297 updates this to also check the repositories associated with the installation prefix. I'm curious if that helps you. I'd like to get it in working condition by the end of 9/8.

**Comment by JusticeForMikeBrown** [comment] 2017-09-07 14:02
Hi @scheibelp 

Yes, 'spec' works fine for any packages that depend upon 'jpeg' though 'load' fails entirely.  If #5297 fixes the issue then I'll try it once approved.  What do you think @tgamblin?

**Comment by healther** [comment] 2017-09-07 15:32
As a note: I ran into a similar issue (besides others in #5228). At some point spack tried to find a package ```jpeg``` even though it was a virtual dependency. Cleaning out all caches helped for me.
@JusticeForMikeBrown did you try ```spack clean --all```?

**Comment by JusticeForMikeBrown** [comment] 2017-09-07 15:37
hi @healther 

Sadly that does not work:
```

[root@node141 spack]# git checkout develop
Checking out files: 100% (748/748), done.
Switched to branch 'develop'
                                                                                                                                              
[root@node141 spack]# spack clean --all
==> Removing all temporary build stages
==> Removing cached downloads
==> Removing cached information on repositories
[root@node141 spack]# spack load -r r-zoo r-yaml py-matplotlib py-pillow
==> Error: Package jpeg not found.

[root@node141 spack]# spack -d load -r r-zoo r-yaml py-matplotlib py-pillow                                                                                                                                                                   
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> Error: Package jpeg not found.
Traceback (most recent call last):
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/main.py", line 440, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/main.py", line 356, in _invoke_spack_command
    return_val = command(parser, args)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/cmd/module.py", line 267, in module
    callbacks[args.subparser_name](module_type, specs, args)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/cmd/module.py", line 134, in loads
    for spec in specs if os.path.exists(module_cls(spec).file_name)]
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/modules.py", line 265, in __init__
    self.pkg = spec.package  # Just stored for convenience
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/spec.py", line 1291, in package
    return spack.repo.get(self)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/repository.py", line 74, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/repository.py", line 317, in get
    return self.repo_for_pkg(spec).get(spec)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/repository.py", line 74, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/repository.py", line 567, in get
    raise UnknownPackageError(spec.name)
spack.repository.UnknownPackageError: Package jpeg not found.
```

**Comment by XL64** [comment] 2017-09-15 12:07
Hello,

I have a similar error when I try to regenerate my tcl modules :
`
spack module refresh --module-type tcl --delete-tree -y

==> Regenerating tcl module files

==> Error: Package jpeg not found.
`

Seems to be linked with that commit : 
"
commit a48b5a627cb4fd18f7bd145e6bb944d5a315cfdb
Author: Sergey Kosukhin <skosukhin@gmail.com>
Date:   Thu Aug 24 10:30:35 2017 +0200

    Make jpeg a virtual dependency. (#5190)

    * Make jpeg a virtual dependency.

    * Make 'libjpeg-turbo' the default implementation of 'jpeg'.
"
Regards,

XL

**Comment by JusticeForMikeBrown** [comment] 2017-09-29 18:49
Now fixed!  Closing.

**Comment by JusticeForMikeBrown** [comment] 2017-10-02 16:55
Some `r-package` still has this issue with `jpeg`

I am loading each one to find out the cuprit.

**Comment by jcftang** [comment] 2017-10-06 12:23
I am also running into problems with this for the jupyter packages

**Comment by jcftang** [comment] 2017-10-06 12:42
Going back to 49a9d63 which reverts making jpeg a virtual package seems to work for me

**Comment by JusticeForMikeBrown** [comment] 2017-10-06 12:50
OK so I am a bit upset. 

I pulled the latest today from develop to address #5565 apparently fixed by #5580.

I now cannot even run "spack find."  

It seems this jpeg issue was never actually resolved.  So now I am on an older branch.  

I do not want to reinstall jpeg which will also mean I need to reinstall `R` as well as many `r-packages.`

Spack has greatly improved the lives of users as well as staff.  We like it a lot.  Can anything be done to improve the quality of code accepted into `develop?`  I don't like sending users emails saying there's another bug in Spack.  


```
[root@node117 spack]# git checkout develop
Switched to branch 'develop'
[root@node117 spack]# git log | head
commit b9d7903cdb1a18b095c0f3e329407640d19908a2
Author: George Hartzell <hartzell@alerce.com>
Date:   Thu Oct 5 15:53:12 2017 -0700

    Add link dependency on xproto to xau (recent dependency mechanics changes?) (#5624)
    
    * Add link dependency on xproto to xau
    
    The libxcb build was failing like so:
    
[root@node117 spack]# spack find
==> Error: Package jpeg not found.

[root@node117 spack]# spack -d find
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> Error: Package jpeg not found.
Traceback (most recent call last):
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/main.py", line 440, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/main.py", line 356, in _invoke_spack_command
    return_val = command(parser, args)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/cmd/find.py", line 122, in find
    query_specs = args.specs(**q_args)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/cmd/common/arguments.py", line 75, in _specs
    return spack.store.db.query(**kwargs)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/database.py", line 792, in query
    with self.read_transaction():
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/llnl/util/lock.py", line 307, in __enter__
    self._as = self._acquire_fn()
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/database.py", line 563, in _read
    self._read_from_file(self._index_path, format='json')
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/database.py", line 391, in _read_from_file
    rec.spec._mark_concrete()
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/spec.py", line 1891, in _mark_concrete
    if s.concrete and s.package.installed:
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/spec.py", line 1198, in package
    return spack.repo.get(self)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/repository.py", line 82, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/repository.py", line 567, in get
    return self.repo_for_pkg(spec).get(spec)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/repository.py", line 82, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/repository.py", line 814, in get
    raise UnknownPackageError(spec.name)
spack.repository.UnknownPackageError: Package jpeg not found.
```

**Comment by jcftang** [comment] 2017-10-06 12:57
I too see this same behaviour, I just pulled the latest develop branch.

**Comment by JusticeForMikeBrown** [comment] 2017-10-06 13:00
@jcftang https://www.youtube.com/watch?v=_O1hM-k3aUY

**Comment by scheibelp** [comment] 2017-10-06 17:19
@JusticeForMikeBrown from examining your stack trace at https://github.com/LLNL/spack/issues/5293#issuecomment-334745489 it looks like #5580 caused that issue and https://github.com/LLNL/spack/pull/5634 would fix it (although I'll aim to reproduce it to make sure).

@jcftang is your problem the same (e.g. you have an old `jpeg` and this same error is coming up)?

**Comment by scheibelp** [comment] 2017-10-06 18:04
I have added a unit test to #5634 which reproduces the error at https://github.com/LLNL/spack/issues/5293#issuecomment-334745489 on develop and confirmed that it is fixed in #5634.

**Comment by jcftang** [comment] 2017-10-06 18:41
@scheibelp yes I have the same problem, I have an existing jpeg install and I see the same behaviour as @JusticeForMikeBrown

**Comment by jcftang** [comment] 2017-10-06 18:48
FYI https://github.com/LLNL/spack/pull/5634 appears to fix the problem for me

**Comment by JusticeForMikeBrown** [comment] 2017-10-06 19:38
Excited for #5634 to be merged!

**Closed** 2017-10-06 21:23 UTC
