### ISSUE TITLE
Recursive Uninstall

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#457] opened 2016-02-29 04:16 UTC
A recursive uninstall (spack uninstall -r) would seem to be in order.  This might uninstall a lot of stuff, of course.  Dangerous but useful.  Especially when you've installed package A and it caused package C to be installed, and you realized C was installed with the wrong parameters.

Maybe have it ask for confirmation by default, unless you add another magic flag (-q? -f?) to tell it to not ask for confirmation.

**Comment by eschnett** [comment] 2016-02-29 17:47
Yes, something like this is definitively needed. Spack likes to go onto crazy excursions with its automatic dependency resolution mechanisms. Combined with the bug where it thinks a package is installed when the package actually failed to build, this often forces me to delete my `opt` tree and start from scratch.

**Comment by tgamblin** [comment] 2016-03-02 09:30
We do need this.  There is recursive deactivate, but not uninstall (yet).

We actually do something like this for `uninstall` without -f already -- if you try to uninstall a dep that's needed by something it'll warn you, unless you supply `-f`. 

@eschnett: Does removing the offending directory + `spack reindex` allow you to avoid removing `opt`?

**Comment by eschnett** [comment] 2016-03-02 15:17
@tgamblin It's difficult to find out which directory is the offending one. `spack find` outputs package specifications that look identical, and the directory names contain only hashes. It requires quite a bit of digging into the yaml files to find out which is which.

What might be helpful would be an `-n` option to `spack install` where it tells me exactly how it's resolving dependencies and what packages will be built.

I think the root of the problem is if Spack's hashes change. Then new packages get installed with the same specifications, and existing packages won't be used. Either hashes should be printed all the time in specs, or having identical specs with different hashes should be an error.

Or maybe a text file with the human-readable spec in Spack's install directories might help.

Of course, having Spack refuse to install a package because part of it thinks the package is already installed, while `spack find` doesn't list it because the install failed, is only adding to the confusion.

Having said all this -- a complete reinstall from time to time is only healthy; it ensures that everything continues to build without surprises. Once the new OpenSSL version is wrapped I'll probably have to do this.

**Comment by trws** [comment] 2016-03-02 19:45
For at least some of these cases I would think an "uninstall unneeded" command combined with a "rebuild reverse dependencies" command might be more useful.  The first of these uninstalling all packages that are not depended on, and are not listed as installed explicitly by the user, the latter rebuilding everything that depends on a given package.  This way, one could (in principle at least) build a new version of something like openssl, rebuild all of the things that depend on openssl using the new version, then clean out the trash with the uninstall unneeded.  This is actually what "revdep-rebuild" and friends are for in gentoo for example.

**Comment by tgamblin** [comment] 2016-03-02 19:51
@eschnett: The hashes are needed so that we can maintain provenance even for things that are too detailed to express on the command line.  The hashes may also get finer grained in future versions, as I would like them to include a hash of the actual `package.py` file.  The idea is to get closer to reproducible builds.  I don't want to add that stuff right now because it's going to make understanding what's installed more complicated.  I will start addressing some of this when the issues discussed in #157 are fixed.  That should alleviate quite a bit of the unnecessary package proliferation -- it will make Spack reuse more things and there should generally be less confusion.

@trws: See my most recent PR; it stores additional provenance so that we can start to do rebuilds.  The other thing we should start doing, to allow "uninstall unneeded" is to track what is actually requested.  Currently we track requested packages and their deps; we should also track what is explicitly requested via `spack install` to use for garbage collection roots in the scenario you describe.

**Comment by trws** [comment] 2016-03-02 19:55
@tgamblin exactly so.  Gentoo does this with `world`, where the contents are the specs of the explicitly requested leaf packages only.  It may also be useful to have more than one such list, especially if we want environments later though.  In a single-root system, the only really necessary ones are `world` and `system`, where system is a proper subset of world.  In a spack universe with multiple roots, it may be worthwhile to let users tag other sets of packages such that they can be acted on in a group.

**Comment by citibeth** [comment] 2016-03-02 23:25
Can you please provide a URL to #157?  All I see is "Python Twister," and
no discussion.

**Comment by citibeth** [comment] 2016-03-02 23:31
The Spack hashing system seems similar to a hashing system I use
elsewhere.  Some questions:

> I think the root of the problem is if Spack's hashes change.

Why do Spack's hashes change?

@eschnett: The hashes are needed so that we can maintain provenance even
for things that are too detailed to express on the command line. The hashes
may also get finer grained in future versions, as I would like them to
include a hash of the actual package.py file.

We need to be careful with hashing package.py.  Probably better to hash
together the name of the package (i.e. package.py/..) with a version number
supplied in the package.py file.  Otherwise, hash codes will change all the
time for no apparent reason, causing lots of rebuilding and upset.

For example, suppose all of package.py is hashed, and I add an new
version+hash code to package.py.  Now the hash for YOUR installed version
changes, and you get upset.

**Comment by tgamblin** [comment] 2016-03-02 23:39
> Can you please provide a URL to #157?  All I see is "Python Twister," and
> no discussion.

 I think github does not do a very good job of translating URLs into email.  The URL shows up on github and a lot of people refer to issues by number because it creates a link automatically.  I think you should view the discussion on the site. URL: github.com/LLNL/spack/pull/157

**Comment by adamjstewart** [comment] 2016-04-01 14:19
#670

**Comment by adamjstewart** [comment] 2016-07-21 21:19
I believe this issue is resolved by #670 and can be closed.

**Closed** 2016-07-22 04:55 UTC
