### ISSUE TITLE
Installation issue:  Casacore

### ISSUE THREAD

**Issue by cnwangfeng** [LLNL/spack#21399] opened 2021-01-30 01:40 UTC
Dear @mpokorny, 

May you please update the casacore?

I think it has two minor bugs that should be updated. 

1.    depends_on('cfitsio@3.181:')  : Actually, 3.181 is an old version. The newest one is 3.49.  The error solved when I set 3.181 to 3.40

2.   depends_on('hdf5', when='+hdf5') should be replaced with "depends_on('hdf5+hl', when='+hdf5')"

Otherwise, the cmake should report the error listed as follows. 

```
1 error found in build log:
     122    -- PYTHON3_EXECUTABLE ......... = /mnt/storage-ssd/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/python-3.8.7-awhlsatyaqicmjmu6ldgqsvq
            rbhgkylu/bin/python3.8
     123    -- PYTHON3_LIBRARIES .......... = /mnt/storage-ssd/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/python-3.8.7-awhlsatyaqicmjmu6ldgqsvq
            rbhgkylu/lib/libpython3.8.so
     124    -- PYTHON3_NUMPY_INCLUDE_DIRS . = /mnt/storage-ssd/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/py-numpy-1.19.5-hkt7m4dpowmk7g3yjm73y
            oqbqvitwpmy/lib/python3.8/site-packages/numpy/core/include
     125    -- PYTHON3_Boost_LIBRARIES .... = Boost::python
     126    -- PYTHON3_Boost_INCLUDE_DIRS . = /mnt/storage-ssd/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/boost-1.75.0-2pt2zb4qrm6fy2gprsu32j3o
            523gjxnl/include
     127    -- Configuring done
  >> 128    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
     129    Please set them or make sure they are set and tested correctly in the CMake files:
     130    HDF5_hdf5_hl_LIBRARY_DEBUG (ADVANCED)
     131        linked by target "casa_casa" in directory /tmp/spack/spack-stage/spack-stage-casacore-3.3.0-ybi2lobague5v2bpwdoouptfbnktrmhl/spack-
            src/casa
     132    HDF5_hdf5_hl_LIBRARY_RELEASE (ADVANCED)
     133        linked by target "casa_casa" in directory /tmp/spack/spack-stage/spack-stage-casacore-3.3.0-ybi2lobague5v2bpwdoouptfbnktrmhl/spack-
            src/casa

```
### Steps to reproduce the issue

```console
$ spack install casacore@3.3.0%gcc@9.3.0 fftw=True hdf5=True openmp=True python=True target=x86_64
...
```

### Information on your system

* **Spack:** 0.16.0-1029-0d521d5
* **Python:** 3.6.8
* **Platform:** linux-centos7-cascadelake
* **Concretizer:** original

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [ ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mpokorny** [comment] 2021-02-02 17:20
I'm able to reproduce the cfitsio issue. Newer cfitsio versions ought to be selected by the package recipe, but cfitsio uses some unusual version numbering scheme, which apparently doesn't fit well with Spack's notions of version numbers. No matter, though, since cfitsio v3.181 is very old, and no longer downloadable using ftp only, I will update the dependency to the earliest of those versions that are still directly downloadable. I have verified that this will fix your problem with cfitsio.

Regarding the HDF5 issue, I'm unable to reproduce it, and I suspect that it might be something other than casacore that's causing your issue. I was able to build the casacore variant you indicated in a fresh Spack install without a problem. I have also verified with a casacore developer that the HDF5 high-level interface is not used by casacore.

**Comment by mpokorny** [comment] 2021-02-02 17:26
I just found a problem with my build using HDF5: it seems to have picked up libhdf5_hl from outside of my Spack installation. Please disregard my previous comment on the HDF5 issue, and I will investigate further.

**Comment by mpokorny** [comment] 2021-02-02 20:34
I now think that the cause of the HDF5 problem is the cmake file in the casacore source used to find the HDF5 library. It seems to be an old version, which unfortunately allows no control over whether to link to the high-level library. Just removing that file from the casacore source, and building with a modern Cmake allowed me to build casacore successfully as you specified. I will consider how best to fix this problem for the Spack package.

**Comment by mpokorny** [comment] 2021-02-11 18:24
The cfitsio issue has been addressed by PR #21630

**Comment by mpokorny** [comment] 2021-02-11 22:50
I have a request for you @cnwangfeng . It turns out that casacore ships with a version of `FindHDF5.cmake` which is rather old, and does not support linking to HDF5 without the high-level library. Newer versions of CMake include their own `FindHDF5.cmake` that do support linking without the high-level HDF5 library. One solution for the Spack casacore package, which I have already tested, is to include a build dependency on a recent enough CMake version, and also implement a patch function in the package definition that deletes casacore's `FindHDF5.cmake` before CMake runs. I am ready to create a PR with this solution, but before I do that, I wanted to get any comments from you about this approach.

**Comment by mpokorny** [comment] 2021-02-23 16:19
The PR #21882 fixes the HDF5 high-level library issue as described by the previous comment.

**Comment by mpokorny** [comment] 2021-03-07 16:35
Both PRs that address these issues have been merged into develop. This issue should be closed.

**Closed as completed** 2021-03-09 08:33 UTC
Labels: build-error
