### ISSUE TITLE
Permissions error copying XCode on OSX when trying to install a package

### ISSUE THREAD

**Issue by jrood-nrel** [LLNL/spack#2496] opened 2016-12-06 17:54 UTC
@mathstuf When using Spack on my OSX (10.11.6) laptop with XCode (8.1), and trying to install a package using Spack, it appears to copy the entire XCode directory into Spack and by default it appears I do not have the correct permissions for some folders:

==> Warning: Copying Xcode from /Library to /Users/jrood/spack/var/spack/stage/xcode-select/clang/8.0.0-apple in order to add spack wrappers to it. Please do not interrupt.
==> Error: Error: [('/Library/Application Support/Apple/ParentalControls/Users', '/Users/jrood/spack/var/spack/stage/xcode-select/clang/8.0.0-apple/Application Support/Apple/ParentalControls/Users', "[Errno 13] Permission denied:...............................
.............................
.............................

Is this just a configuration issue on my own laptop? I could probably change the permissions, but is it just possible to copy over just the XCode command line utils to accomplish the compiler wrapping?

jrood-laptop:ParentalControls jrood$ pwd
/Library/Application Support/Apple/ParentalControls
jrood-laptop:ParentalControls jrood$ ls -alh
total 0
drwxr-xr-x   4 root  wheel   136B Aug 27  2015 .
drwxr-xr-x  12 root  wheel   408B Dec  2  2015 ..
drwxr-xr-x   2 root  wheel    68B Aug 27  2015 ALRHelperJobs
drwx------   2 root  wheel    68B Aug 27  2015 Users

**Comment by adamjstewart** [comment] 2016-12-06 17:57
Duplicate of #2363. You're not the only one with this problem. @davydden?

**Comment by davydden** [comment] 2016-12-06 17:58
I don't have that problem, no idea why

**Comment by cyrush** [comment] 2016-12-08 21:16
I was surprised to find that spack now makes a copy of xcode on OSX. 

Is this absolutely necessary?

Since I have several spack instances this wastes quite a bit of space.

**Comment by mathstuf** [comment] 2016-12-08 21:34
On Thu, Dec 08, 2016 at 13:16:59 -0800, Cyrus Harrison wrote:
> I was surprised to find that spack now makes a copy of xcode on OSX. 
> 
> Is this absolutely necessary?

Yes, some projects only look at Xcode for the compiler (e.g., Qt5), so a
hacked up Xcode is made which replaces the compilers with spack's
wrappers (which are needed to get dependent linker paths and such)..

> Since I have several spack instances this wastes quite a bit of space. 

Work was done to try and minimize what is copied, but there is likely
more to trim if you're interested (it was 12G or so; got it down to
1-2G; at least with the version I had handy).

--Ben

**Comment by tgamblin** [comment] 2016-12-08 21:39
@cyrush: it's really for Qt5 -- this was the only way @mathstuf was able to get it to build.

@mathstuf: it looks like currently makes the copy in the `stage` directory.  Could that be moved to [`misc_cache`](http://spack.readthedocs.io/en/latest/config_yaml.html) so that things can share the same mock XCode and so that it doesn't get purged by the system? (The stage directory can be in a volatile temp dir).

Also, would it be possible to mark packages (e.g., Qt5) as needing this and not do it for others?

**Comment by cyrush** [comment] 2016-12-08 21:39
would it be possible to only do this for qt5?

**Comment by cyrush** [comment] 2016-12-08 21:53
I understand the importance of qt5, but my gut tells me trying to mock something as complex as xcode is going to be a long term maintenance nightmare. 

It seems like there should be a way to create qt spec that would point to spack's compiler wrappers.  Obviously I don't know the full details, was there a discussion about what cropped up before the mocked xcode?

**Comment by tgamblin** [comment] 2016-12-08 21:58
@cyrush: So Ben actually tried mocking a Qt spec up first, and ran this up to Qt support.  They basically said that XCode was the only way to build Qt on a mac.  The layer we have to mock up is relatively small -- this basically just gets XCode to point at the OS X compilers. If we could get a thinner mock layer (maybe using more symlinks?) that would be nice but I was relatively convinced when we talked about this that this was the most compatible thing to do.  If you know how to avoid it that would be awesome though.

**Comment by cyrush** [comment] 2016-12-08 23:05
@tgamblin thanks, from that report trying something else could be an endeavor and maybe futile.

I think only doing this mocking when building packages that need it is a good thing to strive for.  It limits the fallout when things go wrong.

**Comment by mathstuf** [comment] 2016-12-09 13:59
> would it be possible to only do this for qt5?

IIRC, the compiler object is shared for the entire tree, no? So how do we have a package signal that it needs help (which may be on a per-compiler basis) and of what kind? IMO, it's easier just to have the compiler act the same for all packages rather than trying to figure out why you need to do some extra work for package A versus package B, but that's me.

>  If you know how to avoid it that would be awesome though.

Upstream for Qt5 basically said "good luck", so anything we do will need forward ported for Qt5 "forever".

> If we could get a thinner mock layer (maybe using more symlinks?) that would be nice

Possibly. Xcode is really finicky though…it likes piercing your symlinks a lot and then doing relative paths on the resolved paths which get you the naked compilers more often than not (hence the paths which are real in the current setup).

**Comment by adamjstewart** [comment] 2017-08-02 21:33
@jrood-nrel Are you still having this problem? If so, see the discussion in #2363 and #4958. It looks like the full Xcode suite is required to install `qt`. The command-line tools are not sufficient. If you have the full suite installed, copying works without any permissions errors. But you'll first need to delete any partial copies of Xcode by running:
```
$ sudo rm -rf var/spack/stage/xcode-select/
```

**Comment by jrood-nrel** [comment] 2017-08-16 16:11
Ok, thanks for the update. I haven't tried this in a long time as I have been using GCC from homebrew. We can close this if it is contained in other issues.

**Comment by adamjstewart** [comment] 2017-08-16 16:30
Will close when #4958 has been merged.

**Closed** 2017-10-21 00:31 UTC
Labels: duplicate
