### ISSUE TITLE
binary packages: symbolic links not rewritten to account for new locations

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#31401] opened 2022-06-30 23:54 UTC
### Steps to reproduce

Symbolic links are not being re-written to account for new locations when installing packages from build cache.

This is shown below when w/ `openssl` installed from build cache into a path that differs from the path where `openssl` was originally built.

Reproduced using:
* Docker container image `ecpe4s/ubuntu20.04-runner-x86_64:2022-05-01`
* `spack/develop` (861edcf996a1ce001aa20426d290ef950fd79870 from `Thu Jun 30 16:38:58 2022 -0600`)

```
# 1. Clone spack
$> git clone https://github.com/spack/spack /spack
$> (cd /spack && git checkout 861edcf996a1ce001aa20426d290ef950fd79870)
$> . /spack/share/spack/setup-env.sh

# 2. Build openssl in one path, push to cache
$> spack config add "config:install_tree:padded_length:256"
$> spack install --fresh openssl
$> spack buildcache create -af --unsigned -d / openssl

# 3. Uninstall openssl
$> spack uninstall --all

# 4. Install openssl from the cache, to a path that differs from the first path
$> spack config rm "config:install_tree:padded_length:256"
$> spack mirror add local /
$> spack install --fresh --cache-only --no-check-signature openssl
...
==> Installing openssl-1.1.1p-6i5af6cusk73iywespdfifrbqdbzq4br
==> Fetching file:///build_cache/linux-ubuntu20.04-cascadelake-gcc-11.1.0-openssl-1.1.1p-6i5af6cusk73iywespdfifrbqdbzq4br.spec.json
==> Fetching file:///build_cache/linux-ubuntu20.04-cascadelake/gcc-11.1.0/openssl-1.1.1p/linux-ubuntu20.04-cascadelake-gcc-11.1.0-openssl-1.1.1p-6i5af6cusk73iywespdfifrbqdbzq4br.spack
==> Extracting openssl-1.1.1p-6i5af6cusk73iywespdfifrbqdbzq4br from binary cache
==> Warning: Link target "/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-ubuntu20.04-cascadelake/gcc-11.1.0/ca-certificates-mozilla-2022-03-29-md3fhqpo3l3hpjm73bivi6rkujxmjsiy/share/cacert.pem" for symbolic link "/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-11.1.0/openssl-1.1.1p-6i5af6cusk73iywespdfifrbqdbzq4br/etc/openssl/cert.pem" is outside of the new install prefix /spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-11.1.0/openssl-1.1.1p-6i5af6cusk73iywespdfifrbqdbzq4br
...

# 5. Check link, verifying that it is now broken
$> file /spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-11.1.0/openssl-1.1.1p-6i5af6cusk73iywespdfifrbqdbzq4br/etc/openssl/cert.pem
/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-11.1.0/openssl-1.1.1p-6i5af6cusk73iywespdfifrbqdbzq4br/etc/openssl/cert.pem: broken symbolic link to /spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-ubuntu20.04-cascadelake/gcc-11.1.0/ca-certificates-mozilla-2022-03-29-md3fhqpo3l3hpjm73bivi6rkujxmjsiy/share/cacert.pem
```

As a result of this defect, `openssl` installed from build cache is not able to validate certificates.

FYI @scottwittenburg @gartung 

### Information on your system

* **Spack:** 0.19.0.dev0 (861edcf996a1ce001aa20426d290ef950fd79870)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by gartung** [comment] 2022-07-01 19:37
Something is going wrong in the path substitution for the absolute path the link point to
https://github.com/spack/spack/blob/87b8321fa948b906a285406c5ea79e33258386d1/lib/spack/spack/relocate.py#L741
You would need to  look at the listing from the buildache tarball to see what the original link is pointing to and see if the substitution of @'s worked correctly.

**Comment by gartung** [comment] 2022-07-01 19:43
Although this seems to indicate that this is the new way links are rewritten
https://github.com/spack/spack/blob/bb43308c444651f560c920c248257fa9e8dc4b18/lib/spack/spack/rewiring.py#L24
Ask @nhanford

**Comment by eugeneswalker** [comment] 2022-07-05 14:03
The problem is, the symlink which requires relinking resides beneath the openssl install prefix but it points to the install prefix of another package `ca-certificates-mozilla`. The existing relink logic only handles the case of re-linking those links which point to the install prefix of the package where the link resides, and so doesn't even attempt to handle the case identified in this issue:

https://github.com/spack/spack/blob/develop/lib/spack/spack/relocate.py#L764-L769

**Comment by eugeneswalker** [comment] 2022-07-05 15:18
I'm not sure we can fix this without changing what information is stored in the binary distribution metadata. We can't simply substitute the old layout root for the new layout root.

If there is a link in the openssl install prefix and that link targets a path outside the openssl install prefix, say it targets a subpath of the `ca-certificates-mozilla` install prefix, as is the case here, then to relocate this link we need to know what dependency the link is targeting so that we can properly construct the new install prefix for that package.

@scheibelp Thoughts?

**Comment by haampie** [comment] 2022-08-01 16:31
how is this different from changing rpaths...

**Comment by eugeneswalker** [comment] 2022-08-01 17:10
Who said it would be different? The rpath is relocatable because the original install prefix is recorded in the binary distribution metadata file. In order to relocate links that point to install prefixes of dependencies, would we not need to add to the metadata file the original install prefixes of the dependencies, so that we could use that during eventual relocation. Do you see another way?

**Comment by gartung** [comment] 2022-11-22 18:52
@tgamblin This symbolic link relocation bug is now impacting Fermilab's use of buildcaches. In particular the relocation of binutils is broken because ld relies on a symbolic link to find libctf.so.0. @chissg is epsilon-delta away from have an automated CI build of our software with spack.

**Comment by gartung** [comment] 2022-11-22 18:58
This link is listed in the install manifest
```
  "/scratch/workspace/build-spack-env-17/label1/swarm/label2/SLF7/spack_env/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_pa/linux-scientific7-x86_64/gcc-4.8.5/binutils-2.39-yi4yscl2bq6vo54llh6umem6u7szvjdl/lib/libctf.so.0": {
    "mode": 33261,
    "owner": 500,
    "group": 500,
    "type": "link",
    "dest": "libctf.so.0.0.0"
  },
```
but the link is not being made.

**Comment by gartung** [comment] 2022-11-22 19:01
I see part of the problem is that `lib/libctf.so.0.0.0` is listed in `relocate_binaries` but the link `libctf.so.0` is not listed in `relocate_links`

**Comment by haampie** [comment] 2022-11-22 19:26
What spack version are you at? Multiple bugs (#33636, #33608) related to it have been fixed recently.

**Comment by gartung** [comment] 2022-11-22 19:35
Latest commit merged into the Fermilab fork is 4bf964e6b36e8756b014c2e30343507c1cb71b03

**Comment by gartung** [comment] 2022-11-22 19:45
Ah the buildcaches were made before those fixes went in.

**Comment by gartung** [comment] 2022-11-22 19:54
@eugeneswalker Is this still an issue?

**Comment by eugeneswalker** [comment] 2022-11-22 21:32
> @eugeneswalker Is this still an issue
i don’t think so

**Comment by haampie** [comment] 2022-11-22 22:12
Feel free to reopen if still an issue, but I think it should be solved

**Closed as completed** 2022-11-22 22:12 UTC
Labels: bug, buildcache, binary-packages, triage, e4s
