### ISSUE TITLE
Failure to install dealii@develop

### ISSUE THREAD

**Issue by cpraveen** [LLNL/spack#2615] opened 2016-12-17 02:59 UTC
@davydden I am unable to install dealii@develop as it fails at cmake. I have attached log files.

[CMakeError.log.txt](https://github.com/LLNL/spack/files/658616/CMakeError.log.txt)
[CMakeOutput.log.txt](https://github.com/LLNL/spack/files/658617/CMakeOutput.log.txt)
[spack-build.out.txt](https://github.com/LLNL/spack/files/658618/spack-build.out.txt)

**Comment by cpraveen** [comment] 2016-12-17 03:12
I could install

spack install dealii@8.4.2 -netcdf

I had to disable netcdf though 

```
[ 90%] Built target obj_lac.release
make -f source/CMakeFiles/deal_II.dir/build.make source/CMakeFiles/deal_II.dir/depend
make[2]: Entering directory '/tmp/praveen/spack-stage/spack-stage-eYkWUP/dealii-8.4.2/spack-build'
cd /tmp/praveen/spack-stage/spack-stage-eYkWUP/dealii-8.4.2/spack-build && /home/spack/opt/spack/linux-opensuse20161212-x86_64/gcc-6/cmake-3.6.1-fazqngq3jmtpiaae5d4z7uxxvq4xwzmw/bin/cmake -E cmake_depends "Unix Makefiles" /home/spack/var/spack/stage/dealii-8.4.2-4mtq3y52op2fmbbc7234pqlhfas765eb/dealii-8.4.2 /home/spack/var/spack/stage/dealii-8.4.2-4mtq3y52op2fmbbc7234pqlhfas765eb/dealii-8.4.2/source /tmp/praveen/spack-stage/spack-stage-eYkWUP/dealii-8.4.2/spack-build /tmp/praveen/spack-stage/spack-stage-eYkWUP/dealii-8.4.2/spack-build/source /tmp/praveen/spack-stage/spack-stage-eYkWUP/dealii-8.4.2/spack-build/source/CMakeFiles/deal_II.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/tmp/praveen/spack-stage/spack-stage-eYkWUP/dealii-8.4.2/spack-build'
make -f source/CMakeFiles/deal_II.dir/build.make source/CMakeFiles/deal_II.dir/build
make[2]: Entering directory '/tmp/praveen/spack-stage/spack-stage-eYkWUP/dealii-8.4.2/spack-build'
make[2]: *** No rule to make target '/home/spack/opt/spack/linux-opensuse20161212-x86_64/gcc-6/netcdf-cxx-4.2-znea2p6zwurco5taepeha6nqfoqcxkxk/lib/libnetcdf_c++.so', needed by 'lib/libdeal_II.so.8.4.2'.  Stop.
make[2]: Leaving directory '/tmp/praveen/spack-stage/spack-stage-eYkWUP/dealii-8.4.2/spack-build'
make[1]: *** [CMakeFiles/Makefile2:564: source/CMakeFiles/deal_II.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Entering directory '/tmp/praveen/spack-stage/spack-stage-eYkWUP/dealii-8.4.2/spack-build'
make[2]: Nothing to be done for 'source/lac/CMakeFiles/obj_lac.debug.dir/build'.
make[2]: Leaving directory '/tmp/praveen/spack-stage/spack-stage-eYkWUP/dealii-8.4.2/spack-build'
[100%] Built target obj_lac.debug
make[1]: Leaving directory '/tmp/praveen/spack-stage/spack-stage-eYkWUP/dealii-8.4.2/spack-build'
make: *** [Makefile:131: all] Error 2
```

I have

```
/home/spack/opt/spack/linux-opensuse20161212-x86_64/gcc-6/netcdf-cxx-4.2-znea2p6zwurco5taepeha6nqfoqcxkxk/lib64
```

but it is looking for "lib" directory which is not present.

**Comment by davydden** [comment] 2016-12-17 09:04
@cpraveen i know where the problem is, will create a PR soon.

p.s. this is yet another reasons to have https://github.com/LLNL/spack/pull/1875 of @alalazo merged in some shape/form.

**Closed** 2016-12-17 16:57 UTC
