### ISSUE TITLE
mpich picks up system libfabric

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#22982] opened 2021-04-14 11:27 UTC
### Steps to reproduce the issue

On ubuntu 20.04

```console
$ apt-get install libfabric-dev
$ spack install spfft +mpi ^mpich
```

When installing spfft, cmake complains:

```
The MPI test test_mpi for CXX in mode normal failed to compile with the following output:
Change Dir: /tmp/harmen/spack-stage/spack-stage-spfft-1.0.1-5w6kgf3aietp7tg6dskjj5e5mcio3mca/spack-build-5w6kgf3/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_4de26/fast && /usr/bin/make  -f CMakeFiles/cmTC_4de26.dir/build.make CMakeFiles/cmTC_4de26.dir/build
make[1]: Entering directory '/tmp/harmen/spack-stage/spack-stage-spfft-1.0.1-5w6kgf3aietp7tg6dskjj5e5mcio3mca/spack-build-5w6kgf3/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_4de26.dir/test_mpi.cpp.o
/home/harmen/spack/lib/spack/env/gcc/g++  -isystem /home/harmen/spack/opt/spack/linux-ubuntu20.04-zen/gcc-8.4.0/mpich-3.4.1-dqwl5sfgnq2raufpppvmvvc72rwqmxgw/include -std=gnu++11 -o CMakeFiles/cmTC_4de26.dir/test_mpi.cpp.o -c /tmp/harmen/spack-stage/spack-stage-spfft-1.0.1-5w6kgf3aietp7tg6dskjj5e5mcio3mca/spack-build-5w6kgf3/CMakeFiles/FindMPI/test_mpi.cpp
Linking CXX executable cmTC_4de26
/home/harmen/spack/opt/spack/linux-ubuntu20.04-zen/gcc-8.4.0/cmake-3.20.0-4qidoyltbu3rmob2qg4zqipjiuepmrpo/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4de26.dir/link.txt --verbose=1
/home/harmen/spack/lib/spack/env/gcc/g++ -Wl,-rpath -Wl,/home/harmen/spack/opt/spack/linux-ubuntu20.04-zen/gcc-8.4.0/mpich-3.4.1-dqwl5sfgnq2raufpppvmvvc72rwqmxgw/lib -L/home/harmen/spack/opt/spack/linux-ubuntu20.04-zen/gcc-8.4.0/hwloc-2.4.1-h55onjtrja246c2dccbqcgwn7mionf2r/lib CMakeFiles/cmTC_4de26.dir/test_mpi.cpp.o -o cmTC_4de26  -Wl,-rpath,/home/harmen/spack/opt/spack/linux-ubuntu20.04-zen/gcc-8.4.0/mpich-3.4.1-dqwl5sfgnq2raufpppvmvvc72rwqmxgw/lib /home/harmen/spack/opt/spack/linux-ubuntu20.04-zen/gcc-8.4.0/mpich-3.4.1-dqwl5sfgnq2raufpppvmvvc72rwqmxgw/lib/libmpicxx.so /home/harmen/spack/opt/spack/linux-ubuntu20.04-zen/gcc-8.4.0/mpich-3.4.1-dqwl5sfgnq2raufpppvmvvc72rwqmxgw/lib/libmpi.so 
/usr/bin/ld: /home/harmen/spack/opt/spack/linux-ubuntu20.04-zen/gcc-8.4.0/mpich-3.4.1-dqwl5sfgnq2raufpppvmvvc72rwqmxgw/lib/libmpi.so: undefined reference to `fi_dupinfo@FABRIC_1.3'
/usr/bin/ld: /home/harmen/spack/opt/spack/linux-ubuntu20.04-zen/gcc-8.4.0/mpich-3.4.1-dqwl5sfgnq2raufpppvmvvc72rwqmxgw/lib/libmpi.so: undefined reference to `fi_getinfo@FABRIC_1.3'
/usr/bin/ld: /home/harmen/spack/opt/spack/linux-ubuntu20.04-zen/gcc-8.4.0/mpich-3.4.1-dqwl5sfgnq2raufpppvmvvc72rwqmxgw/lib/libmpi.so: undefined reference to `fi_freeinfo@FABRIC_1.3'
```

After running `spack uninstall mpich` and `apt-get remove libfabric-dev` it does not complain.

**Comment by naromero77** [comment] 2021-04-16 20:23
I am running into this issues as well.

Most of DOE is at the ECP Annual Meeting, but hopefully someone from the MPICH team can take a look.
@raffenet

**Comment by raffenet** [comment] 2021-04-16 20:31
Is the issue that it should be picking up a spack installed libfabric instead?

**Comment by haampie** [comment] 2021-04-16 20:37
Yeah, I didn't really look into this further, but superficially it looks like it links against a different version of mpich than it uses as runtime

Mpich builds fine, only when you use it you get errors

**Comment by naromero77** [comment] 2021-04-16 20:43
Hmmm... I am able to build `spfft` with your command, but I get the same identical linking issue in another package, `quantum-espresso`, but only in conjunction with `^mpich ^intel-mkl`, if I only do `^mpich` I don't see it. I wonder if there is some implicit assumption in the `quantum-espresso` that all MPIs packages behave like `openmpi`.

**Comment by naromero77** [comment] 2021-04-19 04:36
In the case, of `quantum espresso`, here is what I see:
`spack install quantum-espresso~scalapack@6.7%gcc@9.3.0 hdf5=parallel 
^intel-mkl@2020.4.304 ^mpich@3.3.2 netmod=tcp device=ch3` works

but, this generates a linking error:
`spack install quantum-espresso~scalapack@6.7%gcc@9.3.0 hdf5=parallel ^intel-mkl@2020.4.304 ^mpich@3.3.2 netmod=ofi device=ch4`


```
==> Installing quantum-espresso-6.7-ubtaw4vwqq4fvz6ui5lscljnts2il4qc
==> No binary for quantum-espresso-6.7-ubtaw4vwqq4fvz6ui5lscljnts2il4qc found: installing from source
==> Using cached archive: /nfs/gce/projects/naromero-workspace/spack/var/spack/cache/_source-cache/archive/fe/fe0ce74ff736b10d2a20c9d59025c01f88f86b00d229c123b1791f1edd7b4315.tar.gz
==> No patches needed for quantum-espresso
==> quantum-espresso: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j12' 'all'

6 errors found in build log:
     1021    a - DENSE/rotate_HSpsi_gamma.o
     1022    a - DENSE/rotate_HSpsi_k.o
     1023    a - DENSE/rotate_wfc_gamma.o
     1024    a - DENSE/rotate_wfc_k.o
     1025    ranlib libks_solvers.a
     1026    make[1]: Leaving directory '/scratch/naromero/tmp/spack-stage/spack-stage-quantum-espresso-6.7-ubtaw4vwqq4fvz6ui5lscljnts2il4qc/spack-src/KS_Solvers'
  >> 1027    /scratch/naromero/opt/spack/linux-ubuntu18.04-westmere/gcc-9.3.0/mpich-3.3.2-pii7btfu6cf7akxaqlkctrnxisioxnyx/lib/libmpi.so: undefined reference to `fi_getinfo@@FABRIC_1.3'
  >> 1028    /scratch/naromero/opt/spack/linux-ubuntu18.04-westmere/gcc-9.3.0/mpich-3.3.2-pii7btfu6cf7akxaqlkctrnxisioxnyx/lib/libmpi.so: undefined reference to `fi_dupinfo@@FABRIC_1.3'
  >> 1029    /scratch/naromero/opt/spack/linux-ubuntu18.04-westmere/gcc-9.3.0/mpich-3.3.2-pii7btfu6cf7akxaqlkctrnxisioxnyx/lib/libmpi.so: undefined reference to `fi_freeinfo@@FABRIC_1.3'
  >> 1030    collect2: error: ld returned 1 exit status
     1031    Makefile:63: recipe for target 'upfconv.x' failed
  >> 1032    make[1]: *** [upfconv.x] Error 1
     1033    make[1]: *** Waiting for unfinished jobs....
     1034    make[1]: Leaving directory '/scratch/naromero/tmp/spack-stage/spack-stage-quantum-espresso-6.7-ubtaw4vwqq4fvz6ui5lscljnts2il4qc/spack-src/upflib'
     1035    Makefile:194: recipe for target 'libupf' failed
  >> 1036    make: *** [libupf] Error 1

See build log for details:
  /scratch/naromero/tmp/spack-stage/spack-stage-quantum-espresso-6.7-ubtaw4vwqq4fvz6ui5lscljnts2il4qc/spack-build-out.txt

```

**Comment by raffenet** [comment] 2022-09-08 21:01
@haampie I believe this is fixed with the latest MPICH release. At least, I cannot reproduce it in my local setup. Can you confirm?

**Comment by alalazo** [comment] 2023-07-11 07:26
Cannot reproduce on:

* **Spack:** 0.21.0.dev0 (64c6d63675f8e45e0be12a9c55acb4b7969e383a)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

**Closed as completed by alalazo** 2023-07-11 07:26 UTC
Labels: bug, triage
