### ISSUE TITLE
`module` command not available after `spack install environment-modules`

### ISSUE THREAD

**Issue by yhgu2000** [LLNL/spack#43650] opened 2024-04-13 07:37 UTC
### Steps to reproduce

```console
$ spack install environment-modules
$ spack load environment-modules
$ module
zsh: command not found: module
```

I also tried `setup-env.sh`. It didn't work either.

### Error message

I dig into `setup-env.sh`. It seems `spack --print-shell-vars sh,modules` didn't set the variable `_sp_module_prefix` properly:

```console
$ spack --print-shell-vars sh,modules
_sp_sys_type='linux-ubuntu22.04-skylake'
_sp_compatible_sys_types='linux-ubuntu22.04-skylake:linux-ubuntu22.04-broadwell:linux-ubuntu22.04-haswell:linux-ubuntu22.04-ivybridge:linux-ubuntu22.04-x86_64_v3:linux-ubuntu22.04-sandybridge:linux-ubuntu22.04-westmere:linux-ubuntu22.04-nehalem:linux-ubuntu22.04-core2:linux-ubuntu22.04-x86_64_v2:linux-ubuntu22.04-nocona:linux-ubuntu22.04-x86_64'
_sp_tcl_roots='/data/@/spack/0.21.2/share/spack/modules'
_sp_lmod_roots='/data/@/spack/0.21.2/share/spack/lmod'
_sp_module_prefix='not_installed'
```

I don't know where `spack --print-shell-vars sh,modules` gets those variable values. There is not a single word about how to use spack with environment-modules itself installs in [the documentation](https://spack.readthedocs.io/en/latest/module_file_support.html). I believe it will be better if we add this part into the documentation.

### Information on your system

* **Spack:** 0.21.2
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment] 2024-04-15 07:50
`spack load` cannot define shell functions, you gotta source the setup script from the module package yourself.

**Comment by yhgu2000** [comment] 2024-04-17 05:33
> `spack load` cannot define shell functions, you gotta source the setup script from the module package yourself.

I wonder what's the purpose of `_sp_module_prefix`, and how to set it properly. It seems spack can source the module env automatically.

**Comment by haampie** [comment] 2024-04-17 06:28
Spack just populates MODULEPATH when you source Spack's `setup-env.sh`

**Comment by alalazo** [comment] 2024-04-20 12:53
@yhgu2000 It sounds like this is not a bug, so closing the issue.

**Closed as completed by alalazo** 2024-04-20 12:53 UTC
Labels: bug, not-a-bug
