### ISSUE TITLE
Clingo concretizer + compiler spec for a package

### ISSUE THREAD

**Issue by maxim-belkin** [LLNL/spack#21660] opened 2021-02-13 12:22 UTC
What I was trying to do: set preferred compiler for a specific package only (not for all packages).

1. Install and load Clingo:
    ```
    spack install clingo@master
    spack load clingo
    ````
1. Instruct Spack to use `clingo` as its concretizer:
    ```
    spack config --scope user add "config:concretizer:clingo"
    ```
1. Check that it can resolve package dependencies correctly:
    ```
    spack solve kokkos
    ```
    <details>
    <summary>Output of <code>spack solve kokkos</code> I see</summary>
    
    ```
    $ spack solve kokkos
    ==> Warning: Intel's compilers may or may not optimize to the same degree for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors
    ==> Best of 0 answers.
    ==> Optimization: [0, 1, -34, 0, 0, 2, -5, 1, 0, -1, 0]
    kokkos@3.2.00%gcc@8.2.0~aggressive_vectorization~compiler_warnings~cuda~cuda_lambda~cuda_ldg_intrinsic~cuda_relocatable_device_code~cuda_uvm~debug~debug_bounds_check~debug_dualview_modify_check~deprecated_code~examples~explicit_instantiation~hip~hpx~hpx_async_dispatch~hwloc~ipo~memkind~numactl~openmp~pic+profiling~profiling_load_print~pthread~qthread+serial+shared~tests~wrapper amd_gpu_arch=vega900 build_type=RelWithDebInfo cuda_arch=none std=11 arch=cray-cnl5-bulldozer
        ^cmake@3.18.4%gcc@8.2.0~doc~ncurses~openssl+ownlibs~qt patches=bf695e3febb222da2ed94b3beea600650e4318975da90e4a71d6f31a6d5d8c3d arch=cray-cnl5-bulldozer
    ```
    </details>
1. Set the preferred compiler for the above package:
    ```
    spack config --scope user add 'packages:kokkos:compiler:[gcc@6.3.0]'
    ```
1. Try to resolve dependencies again (and fail because the step hangs indefinitely).
    ```
    spack solve kokkos
    ```

### Error Message

```console
$ spack --debug --stacktrace solve kokkos
```
<details><summary>Output</summary>

```
timeout 5m spack --debug --stacktrace solve kokkos
mnt/a/sw/spack/spack/0.16/lib/spack/spack/util/executable.py:162 ==> [2021-02-13-06:15:04.425849] '/bin/bash' '--norc' '--noprofile' '-lc' 'echo $CRAY_CPU_TARGET'
mnt/a/sw/spack/spack/0.16/lib/spack/spack/platforms/cray.py:154 ==> [2021-02-13-06:15:04.479301] default to front-end architecture
mnt/a/sw/spack/spack/0.16/lib/spack/spack/cmd/__init__.py:122 ==> [2021-02-13-06:15:05.043010] Imported solve from built-in commands
mnt/a/sw/spack/spack/0.16/lib/spack/spack/cmd/__init__.py:122 ==> [2021-02-13-06:15:05.045342] Imported solve from built-in commands
mnt/a/sw/spack/spack/0.16/lib/spack/spack/config.py:907 ==> [2021-02-13-06:15:05.110223] Reading config file /mnt/a/sw/spack/spack/0.16/etc/spack/defaults/repos.yaml
mnt/a/sw/spack/spack/0.16/lib/spack/spack/config.py:907 ==> [2021-02-13-06:15:05.143329] Reading config file /mnt/a/sw/spack/spack/0.16/etc/spack/repos.yaml
mnt/a/sw/spack/spack/0.16/lib/spack/spack/config.py:907 ==> [2021-02-13-06:15:08.645034] Reading config file /mnt/a/sw/spack/spack/0.16/etc/spack/defaults/config.yaml
mnt/a/sw/spack/spack/0.16/lib/spack/spack/config.py:907 ==> [2021-02-13-06:15:08.711356] Reading config file /mnt/a/sw/spack/spack/0.16/etc/spack/config.yaml
mnt/a/sw/spack/spack/0.16/lib/spack/spack/config.py:907 ==> [2021-02-13-06:15:08.723837] Reading config file /u/staff/mbelkin/.spack/config.yaml
mnt/a/sw/spack/spack/0.16/lib/spack/spack/config.py:907 ==> [2021-02-13-06:15:14.365475] Reading config file /mnt/a/sw/spack/spack/0.16/etc/spack/compilers.yaml
mnt/a/sw/spack/spack/0.16/lib/spack/spack/config.py:907 ==> [2021-02-13-06:15:16.239300] Reading config file /mnt/a/sw/spack/spack/0.16/etc/spack/defaults/packages.yaml
mnt/a/sw/spack/spack/0.16/lib/spack/spack/config.py:907 ==> [2021-02-13-06:15:16.329732] Reading config file /mnt/a/sw/spack/spack/0.16/etc/spack/packages.yaml
mnt/a/sw/spack/spack/0.16/lib/spack/spack/config.py:907 ==> [2021-02-13-06:15:16.392936] Reading config file /u/staff/mbelkin/.spack/packages.yaml
mnt/a/sw/spack/spack/0.16/lib/spack/spack/main.py:429 ==> [2021-02-13-06:15:16.493629] Warning: Intel's compilers may or may not optimize to the same degree for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors
```
</details>

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

```
$ spack debug report
* **Spack:** 0.16.0
* **Python:** 3.8.6
* **Platform:** cray-suse_linux11-bulldozer
```

**Comment by maxim-belkin** [comment] 2021-02-13 12:24
CC @alalazo

**Comment by adamjstewart** [comment] 2021-02-13 20:04
This is also related to #1371

**Comment by alalazo** [comment] 2022-01-06 13:39
I cannot reproduce this behavior as of:

* **Spack:** 0.17.1-735-f8d4b4746c
* **Python:** 3.9.7
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

This is what I get with `clingo`:

![Screenshot from 2022-01-06 14-38-38](https://user-images.githubusercontent.com/4199709/148391432-4cb65ee8-4ff7-4c84-9a8b-3a5646355536.png)

**Comment by alalazo** [comment] 2022-01-06 13:40
Let me know if there is some detail missing to reproduce the issue or if we can close this one.

**Comment by alalazo** [comment] 2022-04-25 15:26
Closing on the assumption that the lack of answer means that the issue is solved

**Closed as completed by alalazo** 2022-04-25 15:26 UTC
Labels: bug, unreproducible
