### ISSUE TITLE
Error: Detected uninstalled dependencies

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#31309] opened 2022-06-26 17:05 UTC
### Steps to reproduce

I am installing an environment on the Theta supercomputer using this [spack.yaml](https://github.com/mochi-hpc-experiments/colza-experiments/blob/9093b3741ad75111692168fe26bfc49f9cc20ba6/theta/amr-wind/spack.yaml) file.
In this environment, `cmake` is an external, non-buildable package. If the `cmake` spec is put at the end of the list of specs, `spack install` installs a bunch of packages, but eventually fails with the following error:

```
==> Error: Detected uninstalled dependencies for metis-5.1.0-7shu46okiixzrxbueyqhsk5td24kq225: {'cmake-3.20.4-abpj56bmmx2efehl5cdivxyoiid7dqe5'}
==> Warning: metis-5.1.0-7shu46okiixzrxbueyqhsk5td24kq225 does NOT actually have any uninstalled deps left
==> Updating view at /gpfs/mira-home/mdorier/colza-experiments/theta/amr-wind/sw/spack/var/spack/environments/colza-amr-wind-env/.spack-env/view
==> Warning: Skipping external package: cray-mpich@7.7.14%gcc@9.3.0 arch=cray-cnl7-haswell/heuguyc
==> Warning: Skipping external package: cmake@3.20.4%gcc@9.3.0~doc+ncurses+ownlibs~qt build_type=Release arch=cray-cnl7-haswell/abpj56b
==> Error: Cannot proceed with metis-5.1.0-7shu46okiixzrxbueyqhsk5td24kq225: 1 uninstalled dependency: cmake-3.20.4-abpj56bmmx2efehl5cdivxyoiid7dqe5
```

It works fine when cmake is at the beginning.

I also had the problem when `cray-mpich` was listed as a spec, but with `vtk-m` failing to install with a similar error about `cray-mpich` being uninstalled. I didn't try every possible ordering of specs and I eventually just removed cray-mpich, just crossing fingers hopping that clingo would follow the `provider` section to pick `cray-mpich` as implementation of MPI by itself.

Note that I don't have anything in `~/.spack`, and I'm also using `export SPACK_DISABLE_LOCAL_CONFIG=true`.

### Error message

See above.

### Information on your system

* **Spack:** 0.18.0 (4c6564f10aa516bc00c1d7dbfdeafe35128985fe)
* **Python:** 3.6.12
* **Platform:** cray-sles15-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2024-05-21 16:29
Can't reproduce on another environment, and Theta has been decommissioned. Closing.
![Screenshot from 2024-05-21 18-28-43](https://github.com/spack/spack/assets/4199709/ffcefa6a-4e6f-416a-b3c0-84607fe792ca)

**Closed as not planned by alalazo** 2024-05-21 16:29 UTC
Labels: bug, cray, triage
