### ISSUE TITLE
Weird misbehaviors arround namespaced packages

### ISSUE THREAD

**Issue by robertu94** [LLNL/spack#30871] opened 2022-05-26 13:09 UTC
### Steps to reproduce

Two different issues, but I think they are related.

Spack@develop seems to have difficulties installing the package from the builtin repo if another repo that defines the package exists.

```console
git clone https://github.com/robertu94/spack_packages
spack repo add ./spack_packages
spack install builtin.sz
spack find -N sz
==> 5 installed packages
-- linux-fedora35-icelake / gcc@11.2.1 --------------------------
robertu94.sz@2.1.12.2  robertu94.sz@2.1.12.2  robertu94.sz@2.1.12.2  robertu94.sz@2.1.12.2  robertu94.sz@2.1.12.2
```

This may be a separate bug, but `spack edit builtin.sz` also cannot edit the builtin sz package.

### Error message

no crash for the first, but the second command yeilds

```console
spack --debug --stacktrace edit builtin.sz
lib/spack/spack/cmd/__init__.py:123 ==> [2022-05-26-09:07:06.952442] Imported edit from built-in commands
lib/spack/spack/cmd/__init__.py:123 ==> [2022-05-26-09:07:06.952876] Imported edit from built-in commands
lib/spack/spack/config.py:1020 ==> [2022-05-26-09:07:06.953493] Reading config file /home/runderwood/git/contrib/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1020 ==> [2022-05-26-09:07:06.954521] Reading config file /home/runderwood/.spack/repos.yaml
lib/spack/spack/cmd/edit.py:46 ==> [2022-05-26-09:07:06.956189] Error: No package for 'sz' was found.
    Use `spack create` to create a new package
lib/spack/spack/config.py:1020 ==> [2022-05-26-09:07:06.956597] Reading config file /home/runderwood/git/contrib/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/home/runderwood/git/contrib/spack/lib/spack/spack/main.py", line 893, in main
    return _main(argv)
  File "/home/runderwood/git/contrib/spack/lib/spack/spack/main.py", line 848, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/runderwood/git/contrib/spack/lib/spack/spack/main.py", line 876, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/runderwood/git/contrib/spack/lib/spack/spack/main.py", line 533, in _invoke_command
    return_val = command(parser, args)
  File "/home/runderwood/git/contrib/spack/lib/spack/spack/cmd/edit.py", line 123, in edit
    edit_package(name, args.repo, args.namespace)
  File "/home/runderwood/git/contrib/spack/lib/spack/spack/cmd/edit.py", line 46, in edit_package
    tty.die("No package for '{0}' was found.".format(spec.name),
  File "/home/runderwood/git/contrib/spack/lib/spack/llnl/util/tty/__init__.py", line 278, in die
    sys.exit(1)
SystemExit: 1

```

### Information on your system

spack debug report
* **Spack:** 0.18.0.dev0 (b5a519fa51cbdb38f5609c0c66ba7283d1888540)
* **Python:** 3.10.4
* **Platform:** linux-fedora35-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2023-07-07 12:01
Duplicate of #35536

**Comment by alalazo** [comment] 2023-07-07 12:02
@robertu94 Moving the discussion to a unique place. Raising the bug in impact due to the number of duplicates.

**Closed as not planned** 2023-07-07 12:01 UTC
Labels: bug, repos, triage
