### ISSUE TITLE
Installation issue: med: cmake: could not find target hdf5

### ISSUE THREAD

**Issue by superNick459** [LLNL/spack#25369] opened 2021-08-11 21:04 UTC
### Steps to reproduce the issue

`med` fails at CMake stage using:

- spack@develop [229bcd9](https://github.com/spack/spack/commit/229bcd9f036ffca43aae53af998f4f3ffe70fec8)
- Ubuntu 20.04, GCC 9.3.0

Spec: [med_spack.yaml.txt](https://github.com/spack/spack/files/6971256/med_spack.yaml.txt)

Docker container: `ecpe4s/ubuntu20.04-runner-x86_64:2021-07-01`
How to reproduce:
```
$ git clone https://github.com/spack/spack
$ cd spack
$ git checkout 229bcd9
$ . share/spack/setup-env.sh
$ spack env create test ~/med_spack.yaml
$ spack env activate test
$ spack buildcache keys -it
$ spack concretize -f
$ spack install
==> Installing med-4.0.0-newufxblwro3hhf3ez3lpicyh6ndcjo4
==> No binary for med-4.0.0-newufxblwro3hhf3ez3lpicyh6ndcjo4 found: installing from source
==> Using cached archive: /root/spack/var/spack/cache/_source-cache/archive/a4/a474e90b5882ce69c5e9f66f6359c53b8b73eb448c5f631fa96e8cd2c14df004.tar.gz
==> No patches needed for med
==> med: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
    'cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/med-4.0.0-newufxblwro3hhf3ez3lpicyh6ndcjo4' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=OFF' '-DCMAKE_INSTALL_RPATH:STRING=/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/med-4.0.0-newufxblwro3hhf3ez3lpicyh6ndcjo4/lib;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/med-4.0.0-newufxblwro3hhf3ez3lpicyh6ndcjo4/lib64;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hdf5-1.10.7-enbo4ptyoocchyzf5leqmafywi7axbnk/lib;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.2-z3qvcplqpvri2tliohtqp7ei2lnvqsf3/lib;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hwloc-2.4.1-eeigvjc57oehl37canx4h5lfganpvdq2/lib;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/libpciaccess-0.16-ux5xkhgfhhmitpkxfuf5h6ooudsiwhd4/lib;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/libxml2-2.9.10-qlt5ajqqmtin3atqcycnv67oex63cvny/lib;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/libiconv-1.16-w6zptbclncs3jsnl3i4qtg72fgheiwdf/lib;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/xz-5.2.5-ynkyqliadxgrqpk4mavevv3onehjrdco/lib;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/zlib-1.2.11-p7dmb5pqi6svirhovljrkp3uyfiytz3m/lib;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/ncurses-6.2-n5vhymfigwg6e45k7thdfyeswuhxojtx/lib;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/libfabric-1.12.1-lgug4cxazbl24jdtmttovd5qpnr6os7z/lib;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/numactl-2.0.14-vw2cdve2xpvtcq2r32ogoptxd4cyjfre/lib' '-DCMAKE_PREFIX_PATH:STRING=/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hdf5-1.10.7-enbo4ptyoocchyzf5leqmafywi7axbnk;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/numactl-2.0.14-vw2cdve2xpvtcq2r32ogoptxd4cyjfre;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.2-z3qvcplqpvri2tliohtqp7ei2lnvqsf3;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/libfabric-1.12.1-lgug4cxazbl24jdtmttovd5qpnr6os7z;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hwloc-2.4.1-eeigvjc57oehl37canx4h5lfganpvdq2;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/libxml2-2.9.10-qlt5ajqqmtin3atqcycnv67oex63cvny;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/xz-5.2.5-ynkyqliadxgrqpk4mavevv3onehjrdco;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/libpciaccess-0.16-ux5xkhgfhhmitpkxfuf5h6ooudsiwhd4;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/cmake-3.20.5-zyz2eldbrcih3f6l37dyvdxmyoiyvhv5;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/zlib-1.2.11-p7dmb5pqi6svirhovljrkp3uyfiytz3m;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/libiconv-1.16-w6zptbclncs3jsnl3i4qtg72fgheiwdf;/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/ncurses-6.2-n5vhymfigwg6e45k7thdfyeswuhxojtx' '-DHDF5_ROOT_DIR:STRING=/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hdf5-1.10.7-enbo4ptyoocchyzf5leqmafywi7axbnk' '-DMEDFILE_BUILD_TESTS:BOOL=OFF' '-DMEDFILE_BUILD_PYTHON:BOOL=OFF' '-DMEDFILE_INSTALL_DOC:BOOL=OFF' '-DCMAKE_Fortran_COMPILER=' '-DCMAKE_CXX_FLAGS:STRING=-DMED_API_23=1' '-DCMAKE_C_FLAGS:STRING=-DMED_API_23=1' '-DMED_API_23=1' '-DMEDFILE_BUILD_SHARED_LIBS=OFF' '-DMEDFILE_BUILD_STATIC_LIBS=ON' '-DMEDFILE_USE_MPI=YES' '-DMPI_ROOT_DIR=/root/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.2-z3qvcplqpvri2tliohtqp7ei2lnvqsf3' '/tmp/root/spack-stage/spack-stage-med-4.0.0-newufxblwro3hhf3ez3lpicyh6ndcjo4/spack-src'

1 error found in build log:
     21    -- Detecting CXX compile features
     22    -- Detecting CXX compile features - done
     23    -- No Fortran support
     24    -- Check for HDF5 ...
     25    -- Found HDF5 in CONFIG mode!
     26    -- Found HDF5 version 1.10.7 -- parallel flag is set to ON
  >> 27    CMake Error at config/cmake_files/FindMedfileHDF5.cmake:118 (GET_PROPERTY):
     28      GET_PROPERTY could not find TARGET hdf5.  Perhaps it has not yet been
     29      created.
     30    Call Stack (most recent call first):
     31      config/cmake_files/medMacros.cmake:396 (FIND_PACKAGE)
     32      CMakeLists.txt:101 (MED_FIND_HDF5)
     33    

See build log for details:
  /tmp/root/spack-stage/spack-stage-med-4.0.0-newufxblwro3hhf3ez3lpicyh6ndcjo4/spack-build-out.txt
```

### Information on your system

- Spack: 0.16.2-3894-229bcd9f03
- Python: 3.8.5
- Platform: linux-ubuntu20.04-zen3
- Concretizer: original

### Additional information

Build log: [med-build-out.txt](https://github.com/spack/spack/files/6971258/med-build-out.txt)
CMake log: [spack-build-01-cmake-out.txt](https://github.com/spack/spack/files/6971263/spack-build-01-cmake-out.txt)

@likask @cessenat

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by christoph-conrads** [comment] 2021-08-12 12:15
duplicate of #24671

**Comment by eugeneswalker** [comment] 2021-08-12 18:51
closing as duplicate

**Closed as completed by eugeneswalker** 2021-08-12 18:51 UTC
Labels: build-error, e4s
