### ISSUE TITLE
swig 3.0.11 failed to build while taking 40Gb of space

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#3000] opened 2017-02-02 06:50 UTC
subj. 

```
==> Installing swig
==> pcre is already installed in /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/pcre-8.39-nhyefptcom4ey5zjjnyot7no7f6gx67z
==> Fetching http://prdownloads.sourceforge.net/swig/swig-3.0.11.tar.gz
######################################################################## 100.0%
==> Staging archive: /Users/davydden/spack/var/spack/stage/swig-3.0.11-iynexulzro2dthcxcsuum3fscpjucvi5/swig-3.0.11.tar.gz
==> Created stage in /Users/davydden/spack/var/spack/stage/swig-3.0.11-iynexulzro2dthcxcsuum3fscpjucvi5
==> Ran patch() for swig
==> Building swig [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
Process logger_daemon:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/davydden/spack/lib/spack/llnl/util/tty/log.py", line 199, in _spawn_writing_daemon
    log_file.flush()
IOError: [Errno 28] No space left on device
```

**Comment by davydden** [comment] 2017-02-02 06:55
switching back to `Package` solved the issue, must be related to `autoreconf` phase, as I don't see what else is different. @alalazo ping.

**Comment by alalazo** [comment] 2017-02-02 07:46
@davydden I am not able to reproduce the issue on Ubuntu 14.04.

I don't think it's related to `autoreconf`, as:
  1. it is  a no-op for swig
  2. if `configure` was not there it would trigger an exception as swig does not depend on `autoconf`, `automake`, etc.

I assume the behavior is deterministic on MacOS. Can you check what happens during configure and the size of `build.out` (just a wild guess)?

**Comment by davydden** [comment] 2017-02-02 07:49
> I assume the behavior is deterministic on MacOS. Can you check what happens during configure and the size of build.out (just a wild guess)?

unfortunately i have only one mac around that I use for work on daily basis, thereby I can't do it immediately. I probably should have saved the `build.out` before wiping 40Gb stage folder which ate all free space. Maybe i leave it to hang overnight and try to get `build.out`.

**Comment by alalazo** [comment] 2017-02-02 07:50
> Maybe i leave it to hang overnight and try to get build.out.

I don't think it's necessary. I was just randomly guessing what could go wrong, because at the moment it doesn't seem anything obvious.

**Comment by adamjstewart** [comment] 2017-02-02 13:45
I've definitely seen a build.out eat up the filesystem before. I was installing something and the configuration wasn't right so it ended up indefinitely printing a warning message until I ran out of space.

**Comment by davydden** [comment] 2017-02-12 06:46
just tried to reproduce it and i cant:
```
$ spack install swig@3.0.10
==> Installing swig
==> pcre is already installed in /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/pcre-8.39-nhyefptcom4ey5zjjnyot7no7f6gx67z
==> Using cached archive: /Users/davydden/spack/var/spack/cache/swig/swig-3.0.10.tar.gz
==> Staging archive: /Users/davydden/spack/var/spack/stage/swig-3.0.10-7jnb2aaxy44jiizfd3hx2t3fbr4oywzl/swig-3.0.10.tar.gz
==> Created stage in /Users/davydden/spack/var/spack/stage/swig-3.0.10-7jnb2aaxy44jiizfd3hx2t3fbr4oywzl
==> Ran patch() for swig
==> Building swig [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Executing phase : 'build'
==> Executing phase : 'install'
==> Warning: Module file already exists : skipping creation
file : /Users/davydden/spack/share/spack/modules/darwin-sierra-x86_64/swig-3.0.10-clang-8.0.0-apple-7jnb2aa
spec : swig@3.0.10%clang@8.0.0-apple arch=darwin-sierra-x86_64 ^pcre@8.39%clang@8.0.0-apple+utf arch=darwin-sierra-x86_64
==> Warning: Module file already exists : skipping creation
file : /Users/davydden/spack/share/spack/dotkit/darwin-sierra-x86_64/swig-3.0.10-clang-8.0.0-apple-7jnb2aa.dk
spec : swig@3.0.10%clang@8.0.0-apple arch=darwin-sierra-x86_64 ^pcre@8.39%clang@8.0.0-apple+utf arch=darwin-sierra-x86_64
==> Successfully installed swig
```
Now idea what was going on but I close this with the hope that I won't see the issue again

**Comment by jppelteret** [comment] 2017-02-22 11:07
I can confirm that I had the same issue on MacOS - it chewed up all of my disc space. It seems like it tried to configure the examples and generated an enormous makefile for one example in the `android` directory.
```
<path>/spack-stage/spack-stage-kQqtoQ/swig-3.0.10/Examples/android/class$ ls -l
total 6503432
-rw-r--r--  1 <user>  staff         611 Jun 12  2016 AndroidManifest.xml
-rw-r--r--  1 <user>  staff  3329729255 Feb 22 12:01 Makefile
-rw-r--r--  1<user>  staff         696 Jun 12  2016 ant.properties
...
```
Its contents are basically a repetition of
```
spack-stage/spack-stage-kQqtoQ/swig-3.0.10/Examples/android/class$ cat Makefile
...
# DO NOT EDIT: instead edit ../../..//Users/<local_path>/spack/var/spack/stage/swig-3.0.^Cjp/Programs/GitHub/Spack/spack/var/spack/stage/swig-3.0.10-66gmnzsnvkqikyk7xecaeuklcm7t6pu7/swig-3.0.10/Examples//android/class/Makefile
# and run (cd ../../../ && ./config.status) to regenerate
TOP_BUILDDIR_TO_TOP_SRCDIR = /Users/<local_path>/spack/var/spack/stage/swig-3.0.10-66gmnzsnvkqikyk7xecaeuklcm7t6pu7/swig-3.0.10/
SRCDIR = ../../..//Users/<local_path>/spack/var/spack/stage/swig-3.0.10-66gmnzsnvkqikyk7xecaeuklcm7t6pu7/swig-3.0.10/Examples//android/class/
```
(Note: In case its important, I've been careful to preserve the path names exactly)
[Log file attached](https://github.com/LLNL/spack/files/793123/spack-build.out.txt)


The problem was fixed by temporarily reverting to the old package.

**Comment by eschnett** [comment] 2017-02-27 15:09
I now see this problem with `swig@3.0.12` that I tried to add. I have `swig@3.0.11` installed and saw no problems there.

**Comment by davydden** [comment] 2017-02-27 15:11
@eschnett does reverting to `Package` helps?

**Comment by eschnett** [comment] 2017-02-27 15:27
I confirm things are working when I switch to `Package`, and with a trivial `install` method:
```
    def install(self, spec, prefix):
        configure("--prefix=%s" % prefix)
        make()
        make("install")
```

The issue seems to be that the directory mentioned above (`Examples/android/class`) already contains a `Makefile` that is then overwritten by Spack. There is, however, no `Makefile.in` -- this is clearly a hand-written `Makefile`. Other `Makefile`s in the `Examples` subtree look similar.

I assume this is a case where a blanket `autoreconf` simply does the wrong thing.

**Closed** 2017-02-28 18:58 UTC
Labels: autotools, macOS
