### ISSUE TITLE
Namespaces for packages duplicated between repos not respected in spack install/add

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [LLNL/spack#34708] opened 2022-12-28 06:41 UTC
### Steps to reproduce

1. Clone spack repo and cd to root dir
2. `mkdir -p myrepo/packages`
3. `cp -r var/spack/repos/builtin/packages/hdf5 myrepo/packages/.`
4.
```
cat > etc/spack/defaults/repos.yaml << EOF
repos:
  - \$spack/myrepo
  - \$spack/var/spack/repos/builtin
EOF
```
5. `echo -ne "repo:\n  namespace: myrepo" > myrepo/repo.yaml`
6. `. share/spack/setup-env.sh`
7. `spack install builtin.hdf5`
8. `spack find -N`

### Error message

```
$ spack find -N
-- linux-centos8-x86_64 / gcc@8.5.0 -----------------------------
builtin.cmake@3.20.2  myrepo.hdf5@1.12.2  builtin.openmpi@4.1.1  builtin.pkgconf@1.4.2  builtin.zlib@1.2.13
==> 5 installed packages
```
The namespace of the installed package should be **builtin**, as specified, not **myrepo**. I have run this same test but with a modified hdf5/package.py to confirm that the incorrect package.py gets used. Same problem occurs when using an environment.

### Information on your system

* **Spack:** 0.20.0.dev0 (558695793fcde4f1ef9f75f6c0ca9e41e5420cf6)
* **Python:** 3.6.8
* **Platform:** linux-centos8-x86_64
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by qgp** [comment] 2023-07-01 15:43
Hi, I ran into a similar issue, the problem shows already with `spack spec` which does not respect the namespace of the input spec. Unless I am missing something, I think that namespaces are actually not carried along in `lib/spack/spack/solver/asp.py` and also not foreseen in `lib/spack/spack/solver/concretize.lp`. In fact, there's even a comment in `asp.py` saying:
> namespace assignment is done after the fact, as it is not currently part of the solve

If this is a correct, the claim in the documentation that you can force a package from a given repository by specifying the namespace is currently not fulfilled (at least with clingo).

Am I missing something? Are there plans to extend the solver to handle namespaces? In the meantime, shouldn't the documentation warn about this not being the case?

**Comment by alalazo** [comment] 2023-07-07 09:07
Duplicate of #35536

**Comment by alalazo** [comment] 2023-07-07 09:08
Closing this one, let's continue the discussion on the other issue. Thanks for reporting though!

**Closed as not planned** 2023-07-07 09:08 UTC
Labels: bug, duplicate, repos
