### ISSUE TITLE
Cannot bootstrap clingo from pre-built binaries within UBI-8

### ISSUE THREAD

**Issue by amagela** [LLNL/spack#29461] opened 2022-03-11 16:43 UTC
### Steps to reproduce

First, create Dockerfile.

```
FROM registry.access.redhat.com/ubi8:latest
LABEL version="2.7"

ENV DOCKERFILE_BASE=rhel              \
    DOCKERFILE_DISTRO=rhel            \
    DOCKERFILE_DISTRO_VERSION=8       \
    DEBIAN_FRONTEND=noninteractive    \
    CURRENTLY_BUILDING_DOCKER_IMAGE=1 \
    SPACK_ROOT=/opt/spack             \
    container=docker

# Prepare typical development environment
RUN dnf update -y \
 && dnf install -y \
        automake \
        cmake \
        curl \
        findutils \
        gcc-c++ \
        gcc \
        gcc-gfortran \
        git \
        gnupg2 \
        hostname \
        iproute \
        #Lmod \
        make \
        patch \
        python36 \
        python36-devel \
        python39 \
        python39-pip \
        python39-setuptools \
        python39-devel \
        tcl \
        unzip \
        which \
        ca-certificates \
        tar \
        gzip \
        unzip \
        bzip2 \
        xz \
        zstd \
        zlib \
        gpg \
        libX11-devel \
        m4 \
 && pip-3.9 install --trusted-host pypi.org --trusted-host files.pythonhosted.org --proxy foo:80 boto3 \
 && rm -rf /var/cache/dnf /var/cache/yum \
 && dnf clean all

# Prepare tools for proxy use and certificate trust 
RUN update-ca-trust extract
# RUN printf "insecure\nproxy = foo:80\nnoproxy = bar" > ~/.curlrc

# Clone Spack
RUN mkdir -p $SPACK_ROOT
RUN git clone https://github.com/spack/spack.git --single-branch --branch v0.17 $SPACK_ROOT

# Symbolically link Spack within the container
RUN ln -s $SPACK_ROOT/share/spack/docker/entrypoint.bash \
          /usr/local/bin/docker-shell \
 && ln -s $SPACK_ROOT/share/spack/docker/entrypoint.bash \
          /usr/local/bin/interactive-shell \
 && ln -s $SPACK_ROOT/share/spack/docker/entrypoint.bash \
          /usr/local/bin/spack-env

# Spack cleaning
RUN mkdir -p /root/.spack \
 && cp $SPACK_ROOT/share/spack/docker/modules.yaml \
        /root/.spack/modules.yaml \
 && rm -rf /root/*.* /run/nologin $SPACK_ROOT/.git

# Workaround issue
# https://superuser.com/questions/1241548/
#     xubuntu-16-04-ttyname-failed-inappropriate-ioctl-for-device#1253889
RUN [ -f ~/.profile ]                                               \
 && sed -i 's/mesg n/( tty -s \\&\\& mesg n || true )/g' ~/.profile \
 || true

# Prepare entry environment 
WORKDIR /root
SHELL ["docker-shell"]
ENTRYPOINT ["/bin/bash", "/opt/spack/share/spack/docker/entrypoint.bash"]
CMD ["interactive-shell"]
```

Then, go into the container and get it to bootstrap the concretizer.

```console
# time spack -d spec zlib
```

I would like for it to use the pre-built Clingo binaries but it, instead, will bootstrap it from source. I verified that I can `curl` on the URL given in the output (see below).

```console
# curl -O https://mirror.spack.io/bootstrap/github-actions/v0.1/build_cache/index.json
```

I am not sure what to check next.

### Error message

```console
[root@749ee77d34a4 ~]# time spack -d spec zlib
==> [2022-03-11-15:08:36.047624] Imported spec from built-in commands
==> [2022-03-11-15:08:36.048598] Imported spec from built-in commands
Input spec
--------------------------------
zlib

Concretized
--------------------------------
==> [2022-03-11-15:08:36.050371] Reading config file /opt/spack/etc/spack/defaults/config.yaml
==> [2022-03-11-15:08:36.076159] Reading config file /opt/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-03-11-15:08:36.088481] Reading config file /opt/spack/etc/spack/defaults/config.yaml
==> [2022-03-11-15:08:36.111342] DATABASE LOCK TIMEOUT: 3s
==> [2022-03-11-15:08:36.111438] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-03-11-15:08:36.111876] Reading config file /opt/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-03-11-15:08:36.121550] DATABASE LOCK TIMEOUT: 3s
==> [2022-03-11-15:08:36.121638] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-03-11-15:08:36.121730] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2022-03-11-15:08:36.122149] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/opt/spack/etc/spack/defaults
==> [2022-03-11-15:08:36.122187] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/opt/spack/etc/spack/defaults/linux
==> [2022-03-11-15:08:36.122220] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/root/.spack/bootstrap/config
==> [2022-03-11-15:08:36.122245] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/root/.spack/bootstrap/config/linux
==> [2022-03-11-15:08:36.211959] '/usr/bin/gfortran' '--version'
==> [2022-03-11-15:08:36.212317] '/usr/bin/gfortran' '--version'
==> [2022-03-11-15:08:36.213451] '/usr/bin/gfortran' '--version'
==> [2022-03-11-15:08:36.213091] '/usr/bin/gfortran' '--version'
==> [2022-03-11-15:08:36.223385] '/bin/gfortran' '--version'
==> [2022-03-11-15:08:36.224020] '/bin/gfortran' '--version'
==> [2022-03-11-15:08:36.227796] '/bin/gfortran' '--version'
==> [2022-03-11-15:08:36.228574] '/bin/gfortran' '--version'
==> [2022-03-11-15:08:36.233372] '/usr/bin/gcc' '--version'
==> [2022-03-11-15:08:36.236916] '/usr/bin/g++' '--version'
==> [2022-03-11-15:08:36.238407] '/usr/bin/gfortran' '-dumpversion'                                                                    [240/429]
==> [2022-03-11-15:08:36.238692] '/usr/bin/gfortran' '-dumpversion'
==> [2022-03-11-15:08:36.247768] '/usr/bin/gcc' '-dumpversion'
==> [2022-03-11-15:08:36.248953] '/usr/bin/gfortran' '-dumpfullversion'
==> [2022-03-11-15:08:36.254286] '/usr/bin/gcc' '-dumpfullversion'
==> [2022-03-11-15:08:36.257069] '/usr/bin/gfortran' '-dumpfullversion'
==> [2022-03-11-15:08:36.263145] '/bin/gfortran' '-dumpversion'
==> [2022-03-11-15:08:36.266171] '/bin/gfortran' '-dumpversion'
==> [2022-03-11-15:08:36.267630] '/bin/gfortran' '-dumpfullversion'
==> [2022-03-11-15:08:36.268398] '/bin/gcc' '--version'
==> [2022-03-11-15:08:36.278656] '/bin/gfortran' '-dumpfullversion'
==> [2022-03-11-15:08:36.282507] '/bin/gcc' '-dumpversion'
==> [2022-03-11-15:08:36.285364] '/usr/bin/g++' '-dumpversion'
==> [2022-03-11-15:08:36.287114] '/bin/gcc' '-dumpfullversion'
==> [2022-03-11-15:08:36.293967] '/usr/bin/g++' '-dumpfullversion'
==> [2022-03-11-15:08:36.298842] '/bin/g++' '--version'
==> [2022-03-11-15:08:36.302904] '/bin/g++' '-dumpversion'
==> [2022-03-11-15:08:36.307230] '/bin/g++' '-dumpfullversion'
==> [2022-03-11-15:08:36.310628] Couldn't get version for compiler /usr/bin/gfortran
==> [2022-03-11-15:08:36.310797] Couldn't get version for compiler /bin/gfortran
==> [2022-03-11-15:08:36.311047] Couldn't get version for compiler /usr/bin/gfortran
==> [2022-03-11-15:08:36.311095] Couldn't get version for compiler /bin/gfortran
==> [2022-03-11-15:08:36.311916] Error while executing candidate compiler /usr/bin/cc
TypeError: expected string or bytes-like object
==> [2022-03-11-15:08:36.312650] Error while executing candidate compiler /bin/cc
TypeError: expected string or bytes-like object
==> [2022-03-11-15:08:36.312924] Couldn't get version for compiler /usr/bin/gfortran
==> [2022-03-11-15:08:36.314017] Couldn't get version for compiler /bin/gfortran
==> [2022-03-11-15:08:36.314253] Couldn't get version for compiler /usr/bin/gfortran
==> [2022-03-11-15:08:36.314440] Couldn't get version for compiler /bin/gfortran
==> [2022-03-11-15:08:36.344380] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2022-03-11-15:08:36.344549] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2022-03-11-15:08:36.345232] Reading config file /opt/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-03-11-15:08:36.356481] Bootstrapping clingo from pre-built binaries
==> [2022-03-11-15:08:36.358846] Reading config file /opt/spack/etc/spack/defaults/config.yaml
==> [2022-03-11-15:08:36.385430] Reading config file /opt/spack/etc/spack/defaults/mirrors.yaml
==> [2022-03-11-15:08:36.787761] Fetching index from https://mirror.spack.io/bootstrap/github-actions/v0.1/build_cache/index.json
==> [2022-03-11-15:08:37.280058] DATABASE LOCK TIMEOUT: 3s
==> [2022-03-11-15:08:37.280196] PACKAGE LOCK TIMEOUT: No timeout
==> [2022-03-11-15:08:37.309394] Imported buildcache from built-in commands
==> [2022-03-11-15:08:37.313504] Imported buildcache from built-in commands
==> [2022-03-11-15:08:52.763543] AttributeError: 'NoneType' object has no attribute 'add_default_arg'
==> [2022-03-11-15:08:52.768052] Reading config file /opt/spack/etc/spack/defaults/bootstrap.yaml
==> [2022-03-11-15:08:52.781193] Reading config file /root/.spack/bootstrap/config/linux/bootstrap.yaml
==> [2022-03-11-15:08:52.789451] Bootstrapping clingo from sources
==> [2022-03-11-15:08:52.821702] '/bin/cmake' '--version'

```

### Information on your system

```console
# spack debug report
* **Spack:** 0.17.0
* **Python:** 3.6.8
* **Platform:** linux-rhel8-haswell
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2022-06-28 15:04
Hi, I tried your reproducer using `develop` instead of v0.17 (thanks for the Docker image, it was super useful!). I think this is not a bug, since:
```console
[root@de7cffddb056 ~]# spack bootstrap status
Spack v0.19.0.dev0 - python@3.6 

[FAIL] Core Functionalities
  [B] MISSING "clingo": required to concretize specs

[FAIL] Binary packages
  [-] MISSING "file": required to analyze files for buildcaches
  [B] MISSING "patchelf": required to relocate binaries


Spack will take care of bootstrapping any missing dependency marked as [B]. Dependencies marked as [-] are instead required to be found on the system.
```
If I install `file` bootstrapping from binaries seem to work correctly. Let me know if there are other issues I overlooked, otherwise I'd close this one.

**Comment by alalazo** [comment] 2023-04-07 09:17
Having a better error message for missing system requirements is tracked elsewhere, so closing this one.

**Closed as not planned by alalazo** 2023-04-07 09:17 UTC
Labels: bug, bootstrap, not-a-bug
