### ISSUE TITLE
Package issue: Can't load `petsc` after `spack gc`

### ISSUE THREAD

**Issue by pauleonix** [LLNL/spack#34977] opened 2023-01-17 12:19 UTC
### Steps to reproduce the issue

@balay @BarrySmith @jedbrown 
This is not directly an installation issue, but rather a configuration issue, I guess.

```console
$ spack install petsc
$ spack gc
$ spack load petsc
```
The `petsc` package marks `python` as a build dependency, so it is removed via `spack gc`. When trying to load `petsc`, the following errors appear.

### Error message

<details><summary>Error message</summary><pre>
==> Error: Unable to locate python headers in any of these locations:
/home/pauleonix/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/python-3.9.13-a55et2ot3xamuge2ufmljqojhf5ckndn/include/python3.9
/home/pauleonix/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/python-3.9.13-a55et2ot3xamuge2ufmljqojhf5ckndn/include/3.9
/home/pauleonix/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/python-3.9.13-a55et2ot3xamuge2ufmljqojhf5ckndn/Headers
</pre></details>

### Information on your system

* **Spack:** 0.19.0 (a86911246a8c5571ca210ff25fc990b8eb297a5c)
* **Python:** 3.10.6
* **Platform:** linux-ubuntu22.04-zen2
* **Concretizer:** clingo

### Additional information

As this is not directly an installation issue, I do not have any additional files. I don't think they will be useful here, but if I am wrong about that I can try to reinstall `petsc` and provide these.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by balay** [comment] 2023-01-17 17:07
Hm - python is indeed a build dependency for petsc library.

This error might be an issue related to 'spack load' cc: @adamjstewart @alalazo

**Comment by adamjstewart** [comment] 2023-01-17 17:21
Is there more to the stack trace? I'm confused why it's trying to find the Python headers. Try `spack -d load` if you can't see the full stack trace.

**Comment by balay** [comment] 2023-01-17 17:32
> Try spack -d load

I'm able to reproduce - this is what I get:

[spack-load-petsc.log.txt](https://github.com/spack/spack/files/10437860/spack-load-petsc.log.txt)

**Comment by adamjstewart** [comment] 2023-01-17 17:54
I believe @alalazo reported a similar issue. The fix is to remove:
```python
    def setup_run_environment(self, env):                                                           
        env.prepend_path("CPATH", os.pathsep.join(self.spec["python"].headers.directories))         
```
from the `python` package. @alalazo did you open a PR for this yet?

EDIT: It was @tgamblin, not @alalazo. This issue should be fixed by #34727.

**Comment by balay** [comment] 2023-01-17 18:48
Thanks! The fix works for me!

```console
[balay@pj01 spack]$ spack gc
==> There are no unused specs. Spack's store is clean.
[balay@pj01 spack]$ spack load petsc
[balay@pj01 spack]$ env |grep PETSC
PETSC_DIR=/home/balay/spack/opt/spack/linux-fedora37-skylake/gcc-12.2.1/petsc-3.18.3-fgncnmyeqnlflvebadt2dg4ltgrrygxl
```

**Closed as completed** 2023-01-19 15:08 UTC
Labels: build-error
