### ISSUE TITLE
Installation issue: py-pkgconfig

### ISSUE THREAD

**Issue by toxa81** [LLNL/spack#40601] opened 2023-10-18 20:56 UTC
### Steps to reproduce the issue

```console
$ spack spec -I py-pkgconfig
Input spec
--------------------------------
 -   py-pkgconfig

Concretized
--------------------------------
 -   py-pkgconfig@1.5.5%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64
[+]      ^pkgconf@1.9.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64
[e]          ^gmake@4.3%gcc@11.4.0~guile build_system=generic patches=599f134 arch=linux-ubuntu22.04-x86_64
[+]      ^py-pip@23.1.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64
[+]      ^py-poetry-core@1.6.1%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64
[+]      ^py-wheel@0.41.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64
[e]      ^python@3.10.12%gcc@11.4.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma+nis~optimizations+pic+pyexpat~pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,7d40923,ebdca64,f2fd060 arch=linux-ubuntu22.04-x86_64
```

### Error message

<details><summary>Error message</summary>

<pre>
==> Error: ProcessError: Command exited with status 2:
    '/tmp/root/spack-stage/spack-stage-py-pkgconfig-1.5.5-tofzwb4fsu5zhkoo7f4mvityznbsqsn5/build_env/bin/python' '-m' 'pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pkgconfig-1.5.5-tofzwb4fsu5zhkoo7f4mvityznbsqsn5' '.'
See build log for details:
  /tmp/root/spack-stage/spack-stage-py-pkgconfig-1.5.5-tofzwb4fsu5zhkoo7f4mvityznbsqsn5/spack-build-out.txt
</pre></details>

Error file contains the following
```
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'poetry'

```

### Information on your system

root@726fcd10ae0f:/# spack debug report
* **Spack:** 0.21.0.dev0 (294e659ae895c45a8ada51ea5cc0db2e5a004e1d)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-broadwell
* **Concretizer:** clingo

### Additional information

***spack-build-out.txt***
```
==> py-pkgconfig: Executing phase: 'install'
==> [2023-10-18-20:53:32.328917] '/usr/bin/python3.10' '-m' 'venv' '--without-pip' '/tmp/root/spack-stage/spack-stage-py-pkgconfig-1.5.5-tofzwb4fsu5zhkoo7f4mvityznbsqsn5/build_env'
==> [2023-10-18-20:53:32.445737] '/tmp/root/spack-stage/spack-stage-py-pkgconfig-1.5.5-tofzwb4fsu5zhkoo7f4mvityznbsqsn5/build_env/bin/python' '-m' 'pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pkgconfig-1.5.5-tofzwb4fsu5zhkoo7f4mvityznbsqsn5' '.'
Using pip 23.1.2 from /opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip (python 3.10)
Non-user install due to --prefix or --target option
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-build-tracker-rlpon7rz
Initialized build tracking at /tmp/pip-build-tracker-rlpon7rz
Created build tracker: /tmp/pip-build-tracker-rlpon7rz
Entered build tracker: /tmp/pip-build-tracker-rlpon7rz
Created temporary directory: /tmp/pip-install-6yg4l2wz
Created temporary directory: /tmp/pip-ephem-wheel-cache-qnz9qcd5
Processing /tmp/root/spack-stage/spack-stage-py-pkgconfig-1.5.5-tofzwb4fsu5zhkoo7f4mvityznbsqsn5/spack-src
  Added file:///tmp/root/spack-stage/spack-stage-py-pkgconfig-1.5.5-tofzwb4fsu5zhkoo7f4mvityznbsqsn5/spack-src to build tracker '/tmp/pip-build-tracker-rlpon7rz'
  Created temporary directory: /tmp/pip-modern-metadata-y0x6kmjm
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  Preparing metadata (pyproject.toml): finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/operations/prepare.py", line 631, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = generate_metadata(
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_internal/utils/misc.py", line 713, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'poetry'

Removed file:///tmp/root/spack-stage/spack-stage-py-pkgconfig-1.5.5-tofzwb4fsu5zhkoo7f4mvityznbsqsn5/spack-src from build tracker '/tmp/pip-build-tracker-rlpon7rz'
Removed build tracker: '/tmp/pip-build-tracker-rlpon7rz'
```

***spack-build-env.txt***
```
ACLOCAL_PATH=/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/pkgconf-1.9.5-2u3b7tq4rdetedhgmk4gg3grqhjhwwrp/share/aclocal; export ACLOCAL_PATH
CC=/spack/lib/spack/env/gcc/gcc; export CC
CMAKE_PREFIX_PATH=/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-poetry-core-1.6.1-6hfvfhwldwe6fcb7zwc6nv7blgubcmx7:/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-wheel-0.41.2-vmmhw2stkk3tndvweenc5u4ugc5f5xqw:/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb:/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/pkgconf-1.9.5-2u3b7tq4rdetedhgmk4gg3grqhjhwwrp; export CMAKE_PREFIX_PATH
CXX=/spack/lib/spack/env/gcc/g++; export CXX
DEBIAN_FRONTEND=noninteractive; export DEBIAN_FRONTEND
F77=/spack/lib/spack/env/gcc/gfortran; export F77
FC=/spack/lib/spack/env/gcc/gfortran; export FC
GIT_DIR=/tmp/root/spack-stage/spack-stage-py-pkgconfig-1.5.5-tofzwb4fsu5zhkoo7f4mvityznbsqsn5/spack-src/.git; export GIT_DIR
HOME=/root; export HOME
HOSTNAME=726fcd10ae0f; export HOSTNAME
LC_ALL=C; export LC_ALL
LC_CTYPE=C.UTF-8; export LC_CTYPE
LDCXXSHARED="/spack/lib/spack/env/gcc/g++ -shared -Wl,-O1 -Wl,-Bsymbolic-functions"; export LDCXXSHARED
LDSHARED="/spack/lib/spack/env/gcc/gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions      -g -fwrapv -O2   "; export LDSHARED
LESSCLOSE="/usr/bin/lesspipe %s %s"; export LESSCLOSE
LESSOPEN="| /usr/bin/lesspipe %s"; export LESSOPEN
LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"; export LS_COLORS
PATH=/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/pkgconf-1.9.5-2u3b7tq4rdetedhgmk4gg3grqhjhwwrp/bin:/spack/lib/spack/env/gcc:/spack/lib/spack/env/case-insensitive:/spack/lib/spack/env:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/spack/bin; export PATH
PKG_CONFIG_PATH=/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/pkgconf-1.9.5-2u3b7tq4rdetedhgmk4gg3grqhjhwwrp/lib/pkgconfig; export PKG_CONFIG_PATH
#PWD=/; export PWD
PYTHONPATH=/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pip-23.1.2-5wwi5ckvb6y7sacxifexcrqaf4yk4dqb/local/lib/python3.10/dist-packages:/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-poetry-core-1.6.1-6hfvfhwldwe6fcb7zwc6nv7blgubcmx7/local/lib/python3.10/dist-packages:/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-wheel-0.41.2-vmmhw2stkk3tndvweenc5u4ugc5f5xqw/local/lib/python3.10/dist-packages:/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pkgconfig-1.5.5-tofzwb4fsu5zhkoo7f4mvityznbsqsn5/local/lib/python3.10/dist-packages; export PYTHONPATH
SHLVL=1; export SHLVL
SPACK_CC=/usr/bin/gcc; export SPACK_CC
SPACK_CC_RPATH_ARG=-Wl,-rpath,; export SPACK_CC_RPATH_ARG
SPACK_COMPILER_FLAGS_KEEP=""; export SPACK_COMPILER_FLAGS_KEEP
SPACK_COMPILER_FLAGS_REPLACE="-Werror-|-Wno-error= -Werror|-Wno-error"; export SPACK_COMPILER_FLAGS_REPLACE
SPACK_COMPILER_SPEC=gcc@=11.4.0; export SPACK_COMPILER_SPEC
SPACK_CXX=/usr/bin/g++; export SPACK_CXX
SPACK_CXX_RPATH_ARG=-Wl,-rpath,; export SPACK_CXX_RPATH_ARG
SPACK_DEBUG_LOG_DIR=/; export SPACK_DEBUG_LOG_DIR
SPACK_DEBUG_LOG_ID=py-pkgconfig-tofzwb4; export SPACK_DEBUG_LOG_ID
SPACK_DTAGS_TO_ADD=--disable-new-dtags; export SPACK_DTAGS_TO_ADD
SPACK_DTAGS_TO_STRIP=--enable-new-dtags; export SPACK_DTAGS_TO_STRIP
SPACK_ENV_PATH=/spack/lib/spack/env:/spack/lib/spack/env/case-insensitive:/spack/lib/spack/env/gcc; export SPACK_ENV_PATH
SPACK_F77=/usr/bin/gfortran; export SPACK_F77
SPACK_F77_RPATH_ARG=-Wl,-rpath,; export SPACK_F77_RPATH_ARG
SPACK_FC=/usr/bin/gfortran; export SPACK_FC
SPACK_FC_RPATH_ARG=-Wl,-rpath,; export SPACK_FC_RPATH_ARG
SPACK_INCLUDE_DIRS=""; export SPACK_INCLUDE_DIRS
SPACK_LINKER_ARG=-Wl,; export SPACK_LINKER_ARG
SPACK_LINK_DIRS=""; export SPACK_LINK_DIRS
SPACK_PYTHON=/usr/bin/python3; export SPACK_PYTHON
SPACK_RPATH_DIRS=/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pkgconfig-1.5.5-tofzwb4fsu5zhkoo7f4mvityznbsqsn5/lib:/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-pkgconfig-1.5.5-tofzwb4fsu5zhkoo7f4mvityznbsqsn5/lib64; export SPACK_RPATH_DIRS
SPACK_SHORT_SPEC="py-pkgconfig@1.5.5%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64/tofzwb4"; export SPACK_SHORT_SPEC
SPACK_SYSTEM_DIRS=/bin:/usr/bin:/usr/local/bin:/bin64:/usr/bin64:/usr/local/bin64:/include:/usr/include:/usr/local/include:/lib:/usr/lib:/usr/local/lib:/lib64:/usr/lib64:/usr/local/lib64:/:/usr:/usr/local; export SPACK_SYSTEM_DIRS
SPACK_TARGET_ARGS="-march=x86-64 -mtune=generic"; export SPACK_TARGET_ARGS
TERM=xterm; export TERM
_=/spack/bin/spack; export _
root@726fcd10ae0f:/tmp/root/spack-stage/spack-stage-py-pkgconfig-1.5.5-tofzwb4fsu5zhkoo7f4mvityznbsqsn5#
```

***Dockerfile*** reproducer
```
FROM ubuntu:22.04 as builder

ENV DEBIAN_FRONTEND=noninteractive \
    PATH="$PATH:/spack/bin"

RUN apt-get -y update && apt-get install -y apt-utils

RUN apt-get install -y gcc g++ gfortran clang libomp-dev libomp-14-dev git make unzip \
   vim wget pkg-config curl tcl m4 cpio automake autoconf apt-transport-https \
   ca-certificates gnupg software-properties-common patchelf meson

# get latest version of spack
RUN git clone https://github.com/spack/spack.git
RUN spack config --scope system add config:install_tree:root:/opt/local
RUN spack config --scope system add packages:all:target:[x86_64]
RUN spack compiler find --scope system
RUN spack external find --all --scope system --not-buildable

RUN spack install py-pkgconfig
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment] 2023-10-18 21:23
Looks like the same issue as:

* #29308 
* #32375 
* https://github.com/spack/spack/pull/32936#discussion_r985116969

and several others. This should have been fixed by #33181. Does the same issue happen when using Spack-installed Python? Could also try different versions of poetry-core.

**Comment by toxa81** [comment] 2023-10-19 09:03
Hello @adamjstewart 
It works with spack's Python 3.11. With Ubuntu's system Python 3.10 it doesn't.

**Comment by adamjstewart** [comment] 2023-10-19 09:13
Good, so we at least have a workaround. When did you install poetry-core? Is it possible it's an old installation before #33181?

**Comment by toxa81** [comment] 2023-10-19 11:40
I didn't install poetry-core intentionally.  Maybe it leaked as a dependency of some other Ubuntu packages.

**Comment by haampie** [comment] 2023-10-19 12:58
@adamjstewart your workaround applies always? The venv (top lines in the build log) should prevent system / user packages from being visible. So, might be some debian specific thing that breaks it. I might have a look later.

**Comment by haampie** [comment] 2023-10-20 08:32
Thanks @toxa81 for the excellent reproducer :) 

@adamjstewart the issue is `PYTHONPATH` entries are:

```
/opt/local/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-poetry-core-1.6.1-n4sfigisjc3xsbwi5spn76lxkpyj5od4/local/lib/python3.10/dist-packages
```

```
<prefix>/local/...
         ^^^^^
```

is incorrect, probably only on Debian. Any clue?

**Comment by adamjstewart** [comment] 2023-10-20 08:53
Ah, so the fact that it's pkgconfig is a coincidence, and all Python packages fail to install. In that case, this is a duplicate of https://github.com/spack/spack/issues/32662#issuecomment-1545922922 and the other half dozen issues linked to it. Only known workaround is to not use external Python. You can also encourage Debian not to patch their build system and break prefix installations.

**Closed as completed** 2024-05-06 14:17 UTC
Labels: build-error
