### ISSUE TITLE
Repository namespace not respected during spack spec

### ISSUE THREAD

**Issue by knoepfel** [LLNL/spack#41464] opened 2023-12-06 17:11 UTC
### Steps to reproduce

```console
$ git clone https://github.com/spack/spack.git 
$ source spack/share/spack/setup-env.sh 
$ git clone https://github.com/FNALssi/fnal_art
$ spack repo add fnal_art
```

### Error message

```console
$ spack spec -I -N builtin.jsonnet@0.18.0
Input spec
--------------------------------
 -   builtin.jsonnet@0.18.0

Concretized
--------------------------------
 -   fnal_art.jsonnet@0.18.0%gcc@11.3.1 build_system=generic cxxstd=17 arch=linux-almalinux9-cascadelake
 ```

The `fnal_art.jsonnet` package is concretized instead of the requested one in the `builtin` repository.

### Information on your system

```console
$ spack debug report
* **Spack:** 0.22.0.dev0 (31645e11fa522bf1c85c8e47d585fccb5a3df956)
* **Python:** 3.9.14
* **Platform:** linux-almalinux9-cascadelake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2023-12-07 09:11
Duplicate of #35536

**Comment by alalazo** [comment] 2023-12-07 09:16
I'll close this as a duplicate, but I just raised priority of #35536. I'll start looking into it, since it seems to be a pain point for many people. Let me know if there is anything here that I missed, and if you think this should be an issue on its own.

**Closed as not planned by alalazo** 2023-12-07 09:16 UTC
Labels: bug, duplicate
