### ISSUE TITLE
Installation issue: gdb

### ISSUE THREAD

**Issue by tmadlener** [LLNL/spack#30836] opened 2022-05-25 08:48 UTC
### Steps to reproduce the issue

Trying to install `gdb` currently fails for me on Ubuntu 20.04 with a system provided `gcc@10.3.0` where the error message seems to indicate that `gcc` is invoked with a warning flag that is not present. The same thing happens if I use the "standard" `gcc@9.4.0` that comes with Ubuntu 20.04

```console
$ spack spec -Il gdb
Input spec
--------------------------------
 -   gdb

Concretized
--------------------------------
 -   4vwbyhq  gdb@11.2%gcc@10.3.0~gold~ld~lto+python~quad~source-highlight~tui+xz patches=7590c95 arch=linux-ubuntu20.04-skylake
[+]  adpd4is      ^gmp@6.2.1%gcc@10.3.0 libs=shared,static arch=linux-ubuntu20.04-skylake
[+]  vhjsw7p          ^autoconf@2.69%gcc@10.3.0 patches=35c4492,7793209,a49dd5b arch=linux-ubuntu20.04-skylake
[+]  5qzwuip              ^m4@1.4.19%gcc@10.3.0+sigsegv patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-skylake
[+]  wnv6k3k                  ^libsigsegv@2.13%gcc@10.3.0 arch=linux-ubuntu20.04-skylake
[+]  t5t3jq2              ^perl@5.34.1%gcc@10.3.0+cpanm+shared+threads arch=linux-ubuntu20.04-skylake
[+]  2cvmawe                  ^berkeley-db@18.1.40%gcc@10.3.0+cxx~docs+stl patches=b231fcc arch=linux-ubuntu20.04-skylake
[+]  f2tkjr2                  ^bzip2@1.0.8%gcc@10.3.0~debug~pic+shared arch=linux-ubuntu20.04-skylake
[+]  fqt552b                      ^diffutils@3.8%gcc@10.3.0 arch=linux-ubuntu20.04-skylake
[+]  uton2w5                          ^libiconv@1.16%gcc@10.3.0 libs=shared,static arch=linux-ubuntu20.04-skylake
[+]  zhrdgqf                  ^gdbm@1.19%gcc@10.3.0 arch=linux-ubuntu20.04-skylake
[+]  thvknky                      ^readline@8.1%gcc@10.3.0 arch=linux-ubuntu20.04-skylake
[+]  lroa5zp                          ^ncurses@6.2%gcc@10.3.0~symlinks+termlib abi=none arch=linux-ubuntu20.04-skylake
[+]  6yza7mk                              ^pkgconf@1.8.0%gcc@10.3.0 arch=linux-ubuntu20.04-skylake
[+]  xo7adq6                  ^zlib@1.2.12%gcc@10.3.0+optimize+pic+shared patches=0d38234 arch=linux-ubuntu20.04-skylake
[+]  fmzkwhe          ^automake@1.16.5%gcc@10.3.0 arch=linux-ubuntu20.04-skylake
[+]  2tbbxy4          ^libtool@2.4.7%gcc@10.3.0 arch=linux-ubuntu20.04-skylake
 -   bwysnnk      ^python@3.8.10%gcc@10.3.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma+nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl+tix+tkinter~ucs4+uuid+zlib patches=0d98e93,f2fd060 arch=linux-ubuntu20.04-skylake
[+]  74owlpr      ^texinfo@6.5%gcc@10.3.0 patches=12f6edb,1732115 arch=linux-ubuntu20.04-skylake
[+]  4yipomi      ^xz@5.2.5%gcc@10.3.0~pic libs=shared,static arch=linux-ubuntu20.04-skylake

$ spack install gdb
```

### Error message

<details><summary>Error message</summary><pre>
==> Error: ProcessError: Command exited with status 2:
    'make' '-j12' 'V=1'

23 errors found in build log:
     4962    /home/tmadlener/work/spack/lib/spack/env/gcc/g++  -DHAVE_CONFIG_H -I. -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport  -I/tmp/tmadlener/spack
             -stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../include -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/
             ../gdb -I../gnulib/import -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../gnulib/import -I.. -I/tmp/tmadlener/spack-stage/spack-stage-gdb-
             11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/..  -I../bfd -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../bfd   -Wall -Wpoin
             ter-arith -Wno-unused -Wunused-value -Wunused-variable -Wunused-function -Wno-switch -Wno-char-subscripts -Wempty-body -Wunused-but-set-parameter -Wunused-but-set-variable -Wno-sign-compare -Wno-er
             ror=maybe-uninitialized -Wno-mismatched-tags -Wno-error=deprecated-register -Wsuggest-override -Wimplicit-fallthrough=3 -Wduplicated-cond -Wshadow=local -Wdeprecated-copy -Wdeprecated-copy-dtor -Wr
             edundant-move -Wmissing-declarations -Wmissing-prototypes -Wstrict-null-sentinel -Wformat -Wformat-nonliteral  -g -O2     -MT common-debug.o -MD -MP -MF .deps/common-debug.Tpo -c -o common-debug.o 
             /tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/common-debug.cc
     4963    /home/tmadlener/work/spack/lib/spack/env/gcc/g++  -DHAVE_CONFIG_H -I. -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport  -I/tmp/tmadlener/spack
             -stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../include -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/
             ../gdb -I../gnulib/import -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../gnulib/import -I.. -I/tmp/tmadlener/spack-stage/spack-stage-gdb-
             11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/..  -I../bfd -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../bfd   -Wall -Wpoin
             ter-arith -Wno-unused -Wunused-value -Wunused-variable -Wunused-function -Wno-switch -Wno-char-subscripts -Wempty-body -Wunused-but-set-parameter -Wunused-but-set-variable -Wno-sign-compare -Wno-er
             ror=maybe-uninitialized -Wno-mismatched-tags -Wno-error=deprecated-register -Wsuggest-override -Wimplicit-fallthrough=3 -Wduplicated-cond -Wshadow=local -Wdeprecated-copy -Wdeprecated-copy-dtor -Wr
             edundant-move -Wmissing-declarations -Wmissing-prototypes -Wstrict-null-sentinel -Wformat -Wformat-nonliteral  -g -O2     -MT common-exceptions.o -MD -MP -MF .deps/common-exceptions.Tpo -c -o commo
             n-exceptions.o /tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/common-exceptions.cc
     4964    /home/tmadlener/work/spack/lib/spack/env/gcc/g++  -DHAVE_CONFIG_H -I. -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport  -I/tmp/tmadlener/spack
             -stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../include -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/
             ../gdb -I../gnulib/import -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../gnulib/import -I.. -I/tmp/tmadlener/spack-stage/spack-stage-gdb-
             11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/..  -I../bfd -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../bfd   -Wall -Wpoin
             ter-arith -Wno-unused -Wunused-value -Wunused-variable -Wunused-function -Wno-switch -Wno-char-subscripts -Wempty-body -Wunused-but-set-parameter -Wunused-but-set-variable -Wno-sign-compare -Wno-er
             ror=maybe-uninitialized -Wno-mismatched-tags -Wno-error=deprecated-register -Wsuggest-override -Wimplicit-fallthrough=3 -Wduplicated-cond -Wshadow=local -Wdeprecated-copy -Wdeprecated-copy-dtor -Wr
             edundant-move -Wmissing-declarations -Wmissing-prototypes -Wstrict-null-sentinel -Wformat -Wformat-nonliteral  -g -O2     -MT common-inferior.o -MD -MP -MF .deps/common-inferior.Tpo -c -o common-in
             ferior.o /tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/common-inferior.cc
     4965    /home/tmadlener/work/spack/lib/spack/env/gcc/g++  -DHAVE_CONFIG_H -I. -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport  -I/tmp/tmadlener/spack
             -stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../include -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/
             ../gdb -I../gnulib/import -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../gnulib/import -I.. -I/tmp/tmadlener/spack-stage/spack-stage-gdb-
             11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/..  -I../bfd -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../bfd   -Wall -Wpoin
             ter-arith -Wno-unused -Wunused-value -Wunused-variable -Wunused-function -Wno-switch -Wno-char-subscripts -Wempty-body -Wunused-but-set-parameter -Wunused-but-set-variable -Wno-sign-compare -Wno-er
             ror=maybe-uninitialized -Wno-mismatched-tags -Wno-error=deprecated-register -Wsuggest-override -Wimplicit-fallthrough=3 -Wduplicated-cond -Wshadow=local -Wdeprecated-copy -Wdeprecated-copy-dtor -Wr
             edundant-move -Wmissing-declarations -Wmissing-prototypes -Wstrict-null-sentinel -Wformat -Wformat-nonliteral  -g -O2     -MT common-regcache.o -MD -MP -MF .deps/common-regcache.Tpo -c -o common-re
             gcache.o /tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/common-regcache.cc
     4966    /home/tmadlener/work/spack/lib/spack/env/gcc/g++  -DHAVE_CONFIG_H -I. -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport  -I/tmp/tmadlener/spack
             -stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../include -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/
             ../gdb -I../gnulib/import -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../gnulib/import -I.. -I/tmp/tmadlener/spack-stage/spack-stage-gdb-
             11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/..  -I../bfd -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../bfd   -Wall -Wpoin
             ter-arith -Wno-unused -Wunused-value -Wunused-variable -Wunused-function -Wno-switch -Wno-char-subscripts -Wempty-body -Wunused-but-set-parameter -Wunused-but-set-variable -Wno-sign-compare -Wno-er
             ror=maybe-uninitialized -Wno-mismatched-tags -Wno-error=deprecated-register -Wsuggest-override -Wimplicit-fallthrough=3 -Wduplicated-cond -Wshadow=local -Wdeprecated-copy -Wdeprecated-copy-dtor -Wr
             edundant-move -Wmissing-declarations -Wmissing-prototypes -Wstrict-null-sentinel -Wformat -Wformat-nonliteral  -g -O2     -MT common-utils.o -MD -MP -MF .deps/common-utils.Tpo -c -o common-utils.o 
             /tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/common-utils.cc
     4967    /home/tmadlener/work/spack/lib/spack/env/gcc/g++  -DHAVE_CONFIG_H -I. -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport  -I/tmp/tmadlener/spack
             -stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../include -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/
             ../gdb -I../gnulib/import -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../gnulib/import -I.. -I/tmp/tmadlener/spack-stage/spack-stage-gdb-
             11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/..  -I../bfd -I/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/../bfd   -Wall -Wpoin
             ter-arith -Wno-unused -Wunused-value -Wunused-variable -Wunused-function -Wno-switch -Wno-char-subscripts -Wempty-body -Wunused-but-set-parameter -Wunused-but-set-variable -Wno-sign-compare -Wno-er
             ror=maybe-uninitialized -Wno-mismatched-tags -Wno-error=deprecated-register -Wsuggest-override -Wimplicit-fallthrough=3 -Wduplicated-cond -Wshadow=local -Wdeprecated-copy -Wdeprecated-copy-dtor -Wr
             edundant-move -Wmissing-declarations -Wmissing-prototypes -Wstrict-null-sentinel -Wformat -Wformat-nonliteral  -g -O2     -MT environ.o -MD -MP -MF .deps/environ.Tpo -c -o environ.o /tmp/tmadlener/
             spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/gdbsupport/environ.cc
  >> 4968    checking if /home/tmadlener/work/spack/lib/spack/env/gcc/gcc supports -fno-rtti -fno-exceptions... cc1plus: error: '-Wno-error=deprecated-register': no option '-Wdeprecated-register'; did you mean 
             '-Wdeprecated-copy-dtor'?
  >> 4969    cc1plus: error: '-Wno-error=deprecated-register': no option '-Wdeprecated-register'; did you mean '-Wdeprecated-copy-dtor'?
     4970    cc1plus: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
     4971    cc1plus: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
  >> 4972    cc1plus: error: '-Wno-error=deprecated-register': no option '-Wdeprecated-register'; did you mean '-Wdeprecated-copy-dtor'?
  >> 4973    cc1plus: error: '-Wno-error=deprecated-register': no option '-Wdeprecated-register'; did you mean '-Wdeprecated-copy-dtor'?
     4974    cc1plus: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
     4975    cc1plus: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
  >> 4976    make[3]: *** [Makefile:505: agent.o] Error 1
     4977    make[3]: *** Waiting for unfinished jobs....
  >> 4978    make[3]: *** [Makefile:505: btrace-common.o] Error 1
  >> 4979    cc1plus: error: '-Wno-error=deprecated-register': no option '-Wdeprecated-register'; did you mean '-Wdeprecated-copy-dtor'?
  >> 4980    make[3]: *** [Makefile:505: cleanups.o] Error 1
  >> 4981    make[3]: *** [Makefile:505: buffer.o] Error 1
     4982    cc1plus: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
  >> 4983    cc1plus: error: '-Wno-error=deprecated-register': no option '-Wdeprecated-register'; did you mean '-Wdeprecated-copy-dtor'?
  >> 4984    cc1plus: error: '-Wno-error=deprecated-register': no option '-Wdeprecated-register'; did you mean '-Wdeprecated-copy-dtor'?
     4985    cc1plus: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
  >> 4986    cc1plus: error: '-Wno-error=deprecated-register': no option '-Wdeprecated-register'; did you mean '-Wdeprecated-copy-dtor'?
     4987    cc1plus: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
     4988    cc1plus: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
  >> 4989    make[3]: *** [Makefile:505: common-inferior.o] Error 1
  >> 4990    cc1plus: error: '-Wno-error=deprecated-register': no option '-Wdeprecated-register'; did you mean '-Wdeprecated-copy-dtor'?
  >> 4991    make[3]: *** [Makefile:505: common-utils.o] Error 1
     4992    cc1plus: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
  >> 4993    make[3]: *** [Makefile:505: common-debug.o] Error 1
  >> 4994    make[3]: *** [Makefile:505: environ.o] Error 1
  >> 4995    make[3]: *** [Makefile:505: common-exceptions.o] Error 1
  >> 4996    cc1plus: error: '-Wno-error=deprecated-register': no option '-Wdeprecated-register'; did you mean '-Wdeprecated-copy-dtor'?
     4997    cc1plus: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
  >> 4998    make[3]: *** [Makefile:505: common-regcache.o] Error 1
     4999    make[3]: Leaving directory '/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/spack-build/gdbsupport'
  >> 5000    make[2]: *** [Makefile:400: all] Error 2
     5001    make[2]: Leaving directory '/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/spack-build/gdbsupport'
     5002    no
  >> 5003    checking for /home/tmadlener/work/spack/lib/spack/env/gcc/gcc option to produce PIC... make[1]: *** [Makefile:9652: all-gdbsupport] Error 2
     5004    -fPIC -DPIC
     5005    yes
     5006    make[1]: *** Waiting for unfinished jobs....
     5007    checking if /home/tmadlener/work/spack/lib/spack/env/gcc/gcc PIC flag -fPIC -DPIC works... checking size of long long... yes
     5008    checking if /home/tmadlener/work/spack/lib/spack/env/gcc/gcc static flag -static works... 8
     5009    checking whether basename is declared... yes

     ...

     5094    config.status: creating arch-subdir.mk
     5095    config.status: creating Makefile
     5096    config.status: creating config.h
     5097    config.status: executing libtool commands
     5098    config.status: executing depfiles commands
     5099    make[1]: Leaving directory '/tmp/tmadlener/spack-stage/spack-stage-gdb-11.2-4vwbyhqdsllmhqn3puzujqv37sgz5bp6/spack-src/spack-build'
  >> 5100    make: *** [Makefile:903: all] Error 2

</pre></details>

### Information on your system

```console
$ spack debug report
* **Spack:** 0.18.0.dev0 (6e7eb49888e37da3b63c8eaba1040ea91aec5fde)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** clingo
```

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8769428/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8769429/spack-build-out.txt)

@robertu94

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tmadlener** [comment] 2022-05-25 12:50
It seems that this is indeed a spack related issue as I can build gdb outside of spack (even if I use the same arguments to `configure`). I am not entirely sure which part of the spack build environment is responsible for the `Wdeprecated-register` flag.

**Comment by tmadlener** [comment] 2022-05-25 13:52
To add further to this: The problem also seems to be present on CentOS7. Digging a bit through other issues, I found #30799 and this build issue here seems to be caused by the same PR: #30284. Reverting those changes lets me build `gdb` successfully (on Ubuntu and CentOS7)

**Comment by robertu94** [comment] 2022-05-26 13:49
@trws This user seems to have a problem with a patch you merged recently.

**Comment by trws** [comment] 2022-05-26 16:25
It looks like this is a related problem, caused by this little chunk of shell in gdbsupport/warning.m4 in the autoconf setup for gdb:

```sh
# GCC does not complain about -Wno-unknown-warning.  Invert
# and test -Wunknown-warning instead.
case $w in
-Wno-*)
  wtest=`echo $w | sed 's/-Wno-/-W/g'` ;;
      -Wformat-nonliteral)
  # gcc requires -Wformat before -Wformat-nonliteral
  # will work, so stick them together.
  w="-Wformat $w"
  wtest="$w"
  ;;
*)
  wtest=$w ;;
esac
```

This translates `-Wno-err*` to `-Werr*` basically, on the theory that the
compiler will only fail when passed the `-Werror` version.  Because the patch is
stripping the `-Werror*` flags, it doesn't fail *but it does fail when the
`-Wno-error` ones are passed later*.  Ironically their attempt to prevent
spurious failures is causing a spurious failure.

I think I can make up a workaround for this where we test whether the compiler
will execute correctly with those flags and no file passed, but have to test the
idea.  May have to come up with a way to prevent that causing a slowdown, but
for now it's the best idea I have to solve this generically for all packages
        rather than having to fix any and all broken config checks like this.

**Comment by trws** [comment] 2022-05-27 00:15
The commit that caused this issue has been reverted for 0.18, for develop either #30882 or #30881 should fix this issue depending on how we decide to work around the problem long-term.

**Closed as completed** 2022-11-23 18:51 UTC
Labels: build-error
