### ISSUE TITLE
font-bh-type1 fails because mkfontscale is not found by configure

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2134] opened 2016-10-25 22:38 UTC
[edit, working with the current tip of develop: 7a575d2, though the X bits have been installed in dribs and drabs over the past couple of days]

I did this:

```
spack install font-bh-type1
```

which built and installed a number of things, including

```
==> Successfully installed mkfontscale
```

but then failed.  `spack-build.out` ended like so:

```
checking for fc-cache... /rss/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/fontconfig-2.11.1-ti2zz3wpp4yflrik6p7pt5nih7ngdhip/bin/fc-cache
checking for mkfontdir... /rss/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/mkfontdir-1.0.7-zcq774jm3vq4ockjac5ewmzksh2kt7mm/bin/mkfontdir
checking for mkfontscale... no
configure: error: mkfontscale is required to build font-bh-type1.
```

When I explicitly added mkfontscale in my environment, it completed successfully:

```
[hartzelg@spack-0 ~]$ module load mkfontscale
[hartzelg@spack-0 ~]$ spack install font-bh-type1
==> Installing font-bh-type1
==> mkfontdir is already installed in /rss/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/mkfontdir-1.0.7-zcq774jm3vq4ockjac5ewmzksh2kt7mm
==> mkfontscale is already installed in /rss/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/mkfontscale-1.1.2-5byj3bgdrrd6l3ibvj244vaodjx6nhwo
==> font-util is already installed in /rss/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/font-util-1.3.1-6rs7qlybxshfpui546rmxoeuxkahypbv
==> fontconfig is already installed in /rss/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/fontconfig-2.11.1-ti2zz3wpp4yflrik6p7pt5nih7ngdhip
==> util-macros is already installed in /rss/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/util-macros-1.19.0-l6pdwkbgbll2sq67oz45dvzvcvuvdays
==> pkg-config is already installed in /rss/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/pkg-config-0.29.1-jvt6jdizvngzjy6kdf2kswpf7riei7d6
==> Already downloaded /rss/spack/var/spack/stage/font-bh-type1-1.0.3-3w7y2sgnqnuphhcbrbqdxct3iy5kbag2/font-bh-type1-1.0.3.tar.gz
==> Already staged font-bh-type1-1.0.3-3w7y2sgnqnuphhcbrbqdxct3iy5kbag2 in /rss/spack/var/spack/stage/font-bh-type1-1.0.3-3w7y2sgnqnuphhcbrbqdxct3iy5kbag2
==> No patches needed for font-bh-type1
==> Building font-bh-type1 [Package]
==> Executing phase : 'install'
==> Successfully installed font-bh-type1
  Fetch: 0.01s.  Build: 5.43s.  Total: 5.44s.
[+] /rss/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/font-bh-type1-1.0.3-3w7y2sgnqnuphhcbrbqdxct3iy5kbag2
```

**Comment by citibeth** [comment] 2016-10-26 13:05
I think this is the same bug as #2086

**Comment by hartzell** [comment] 2016-10-26 19:28
@citibeth -- #2086 seems like it's coming at the same problem.

With the caveat that I'm not sure how the internals actually work....

Spack seems to arrange for all of a package's build dependencies to be inserted into the build environment as part of the environment setup.

It seems as if a package *P0* has a `build` dependency on *P1* that in turn has a `run` dependency on *P2*, then the build environment for *P0* needs to include *P2* so that *P1* can run.

More concretely, the build environment for *font-bh-type1* needs to include `mkfontscale` so that `mkfontdir` can run.

I haven't thought through whether all of the run dependencies in the graph need to be set up, but I feel like they do.

I'm unclear how spack adds the `build` dependencies, but it seems like it could use the same mechanism for the `run` dependencies in the subtree.

**Comment by tgamblin** [comment] 2016-10-26 22:24
@hartzell: I believe you are correct.  If that is not happening (as it seems not to be) then that is probably what we need to do to solve this.  I put this as a required thing for `0.10`.

If you want to take a stab at this you could look at `traverse()` in `spec.py` and `set_build_environment_variables` in `build_environment.py`.  I think the interface to `Spec.traverse()` has gotten kind of kludgy and probably needs a way to express the relationship you mentioned.

**Comment by tgamblin** [comment] 2016-10-26 22:24
Also, if you _don't_ want to take a look at this, I'll get to it.

**Comment by hartzell** [comment] 2016-10-27 14:39
I'll take a swing at it.

**Comment by hartzell** [comment] 2016-11-01 23:59
@tgamblin -- I think that I know what needs to be done here, but before I start cutting, is adding the dependencies' `bin` directory sufficient or *should* we be doing something fancier, using the dependencies' `setup_dependent_environment` or ....  Perhaps do something simple first, although I don't want to leave a mess for the next person to pick it up.

**Comment by becker33** [comment] 2017-01-11 16:57
@hartzell I just checked out the current tip of develop and tried to reproduce this, and my installation went smoothly. I was also unable to reproduce the error on the commit you listed (7a575d2). Can you provide more context on what you were doing? Were there other packages installed when you tried this? etc.

**Comment by becker33** [comment] 2017-01-14 00:28
Closing this as unreproducible. Please reopen if the issue persists on current develop.

**Closed by becker33** 2017-01-14 00:28 UTC
Labels: bug, build-environment, X11
