### ISSUE TITLE
Relocation: false BinaryTextReplaceError

### ISSUE THREAD

**Issue by vvolkl** [LLNL/spack#16564] opened 2020-05-11 08:56 UTC
I was  relocating packages to an install path longer than the one used to create the buildcache, and saw the Error below. But I remembered that `patchelf` should actually be capable of growing the rpath in binaries, so I tried commenting out the exception, and installed and used a few packages, all without any issues.

This raises the question, is this error really justified? If not, removing this constraint would really improve  the usefulness of buildcaches.

### Steps to reproduce the issue

```console
# use spack installation in /short/path on machine a 
$ spack install gcc
$ spack buildcache create -u -a gcc
# use spack installation in /looooooong/path on machine b
$ spack buildcache install -u gcc

...
```

### Error Message

```console
==> Installing buildcache for spec gcc@8.3.0%gcc@4.8.5~binutils languages=c,c++,fortran ~nvptx patches=49341f7807b12a89750c010a20707598f83121da9829150d4049ed3a1a140564,dc1ca240b7fb70112ae6cc47cd86925adf78d29ed9d0c26b0c51d52e40ceca0e ~piclibs~strip arch=linux-centos7-haswell
==> Error: New path longer than old path: binary text replacement not possible.
The new path /home/gitlab-runner/paaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaading/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-8.3.0-zvioj2ws7j3tm4k2ns72menfduhukqty is longer than the old path /home/vavolkl/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-8.3.0-zvioj2ws7j3tm4k2ns72menfduhukqty.
Text replacement in binaries will not work.
Create buildcache from an install path longer than new path.

```

### Information on your system

* **Spack:** 0.14.2-1039-f32d561
* **Python:** 3.7.7
* **Platform:** linux-centos7-haswell

**Comment by gartung** [comment] 2020-05-11 18:41
Can you try updating to the head of develop as a test.

**Comment by gartung** [comment] 2020-05-11 18:43
/home/gitlab-runner/paaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaading/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-8.3.0-zvioj2ws7j3tm4k2ns72menfduhukqty
 is longer than the old path 
/home/vavolkl/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/gcc-8.3.0-zvioj2ws7j3tm4k2ns72menfduhukqty

This is functioning as expected.

**Comment by gartung** [comment] 2020-05-11 18:46
Yes patchelf can grow the rpath entries, but the error is from trying to replace strings compiled into the binaries. I don't recall if I added a switch to bypass that check.

**Comment by gartung** [comment] 2020-05-11 18:56
As initially implemented  this was just a warning message. My colleague argued that this should be an error because the complete relocation was not done. 

You always have the option of connecting out the line that raises the error. Relocating compilers is tricky at best. The compilation rules file is text, so it will get rewritten. Running the compiler to get flags will result in incorrect paths unless the text in the binaries is rewritten. This can only happen if the new path is shorter than the old path.

**Comment by becker33** [comment] 2020-05-11 21:43
As @gartung said, this is not a false Error, it correctly identifies that the package will not work as intended in the new location because it has strings hard-coded into the package.

I'm closing this as correct behavior. @vvolkl feel free to ping me here (or on slack) if you want more information on how to work around this error or why this error is occurring despite the rpaths being correctly expanded.

**Closed as completed by becker33** 2020-05-11 21:43 UTC
Labels: buildcache

**Comment by vvolkl** [comment] 2020-05-12 11:28
@gartung @becker33 Many thanks for your explanations. I'd be interested to understand in more details the limitations of relocations, so l'll come back to that and write you on slack.
