### ISSUE TITLE
Unable to build ghostscript 9.21

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#4057] opened 2017-04-30 23:12 UTC
I'm seeing this error:

```
./obj/aux/echogs -a ./obj/ldt.tr -s -  -lm -ldl  -L/scratch/vendors/spack.20170428/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/libtiff-4.0.6-ymvv4frmgmpru6ewdkalbvibmuvoj3ur/lib -ltiff   -rdynamic -lfontconfig -lfreetype      -lpthread -lm
if [ x != x ]; then LD_RUN_PATH=; export LD_RUN_PATH; fi; \
XCFLAGS= XINCLUDE= XLDFLAGS= XLIBDIRS= XLIBS= \
PSI_FEATURE_DEVS= FEATURE_DEVS= DEVICE_DEVS= DEVICE_DEVS1= DEVICE_DEVS2= DEVICE_DEVS3= \
DEVICE_DEVS4= DEVICE_DEVS5= DEVICE_DEVS6= DEVICE_DEVS7= DEVICE_DEVS8= \
DEVICE_DEVS9= DEVICE_DEVS10= DEVICE_DEVS11= DEVICE_DEVS12= \
DEVICE_DEVS13= DEVICE_DEVS14= DEVICE_DEVS15= DEVICE_DEVS16= \
DEVICE_DEVS17= DEVICE_DEVS18= DEVICE_DEVS19= DEVICE_DEVS20= \
DEVICE_DEVS_EXTRA= \
/bin/sh <./obj/ldt.tr
/bin/ld: ./obj/pngrutil.o: undefined reference to symbol 'inflateValidate@@ZLIB_1.2.9'
/scratch/vendors/spack.20170428/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/zlib-1.2.11-hpdicdxfq5jn2ycttiuiu42hemg444nf/lib/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [bin/gs] Error 1
```

I'm not familiar with building this package manually, so I 'm looking for help from the community.  Does this error look familiar to anyone?  Ghostscript appears to have its own copy of zlib so this may be an issue with their build system and not with spack.  Comments?

[spack-build.out.txt](https://github.com/LLNL/spack/files/967077/spack-build.out.txt)
[spack-build.env.txt](https://github.com/LLNL/spack/files/967078/spack-build.env.txt)

**Comment by tgamblin** [comment] 2017-05-01 00:23
@KineticTheory: it looks like you're getting a versioned symbol for the `inflateValidate` call in `zlib` that does not match the `zlib` that `ghostscript` wants to link with.  If you look at the compile line for `pngrutil.o`, it looks like this:

```
/scratch/vendors/spack.20170428/lib/spack/env/gcc/gcc -O2 -Wall -Wstrict-prototypes -Wundef -Wmissing-declarations -Wmissing-prototypes -Wwrite-strings -Wno-strict-aliasing -Werror=declaration-after-statement -fno-builtin -fno-common -Werror=return-type -DHAVE_STDINT_H=1 -DHAVE_DIRENT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_SYS_TIMES_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_LIBDL=1 -DGX_COLOR_INDEX_TYPE="unsigned long long" -D__USE_UNIX98=1   -I/scratch/vendors/spack.20170428/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/libtiff-4.0.6-ymvv4frmgmpru6ewdkalbvibmuvoj3ur/include      -I./libpng -I./zlib -I./obj  -DPNG_NO_ASSEMBLER_CODE -o ./obj/pngrutil.o -c ./libpng/pngrutil.c
```

It looks like ghostscript includes vendored versions of a number of dependencies, like `libpng`, `zlib`, etc.  We force an external `libtiff` in the `ghostscript` package using `--with-system-libtiff`, which pulls in transitive link dependencies to Spack's `zlib`.  I think the issue is that we're sticking the includes for the Spack `zlib` on the compile line before the `-I./zlib` there, and they're not compatible with the vendored `zlib`.  Normally we'd try to force ghostscript to use Spack's `zlib`, but it doesn't look like it has options for that.

What happens if you get rid of the `libtiff` dependency and remove `--with-system-libtiff` from the config line? 

I'm not sure what the right thing to do here is.  The Spack compilers *used* to put their `-I` flags after any package-specific includes, but we got rid of that a while ago, and if we do that, then packages can potentially put a `-I/usr/include` on the compile line and override Spack dependency headers with system ones.  We could filter system paths out of the compile arguments, but allow includes within the package prefix or those of dependencies.  In this case I'm not sure there is a workable solution other than using *all* the vendored libraries for `ghostscript`, since `libtiff` depends on `zlib` anyway.

**Comment by adamjstewart** [comment] 2017-05-01 16:38
I'm able to reproduce this bug on Fedora 25 as well. The previous version of Ghostscript in Spack builds fine. I'll try taking a look.

**Comment by adamjstewart** [comment] 2017-05-01 17:19
Hahahaha

> **Note**: The Ghostscript build system is not user-friendly. In order to use system copies of various graphics libraries, you must do it using unconventional methods. 

http://www.linuxfromscratch.org/blfs/view/svn/pst/gs.html

**Comment by adamjstewart** [comment] 2017-05-01 18:34
I have a fix for this. PR incoming soon. Just want to run a couple more tests.

**Closed** 2017-05-02 14:45 UTC
Labels: build-error
