### ISSUE TITLE
Installation issue: intel-oneapi-compilers

### ISSUE THREAD

**Issue by hvds** [LLNL/spack#22813] opened 2021-04-06 17:52 UTC
This is essentially my first use of spack, I've only installed patchelf before this.

```console
% ./spack install intel-oneapi-compilers %gcc@7.5.0
[+] /src/util/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/patchelf-0.10-4vf542wykmvpfolrytplar3gbytbwzo7
==> Installing intel-oneapi-compilers-2021.1.2-37thdsexf7e5iy7sgwkmmwl6nf7sokwn
==> No binary for intel-oneapi-compilers-2021.1.2-37thdsexf7e5iy7sgwkmmwl6nf7sokwn found: installing from source
==> Fetching https://registrationcenter-download.intel.com/akdlm/irc_nas/17513/l_dpcpp-cpp-compiler_p_2021.1.2.63_offline.sh
######################################################################### 100.0%
==> Fetching https://registrationcenter-download.intel.com/akdlm/irc_nas/17508/l_fortran-compiler_p_2021.1.2.62_offline.sh
######################################################################### 100.0%
==> Moving resource stage
        source : /tmp/hv/spack-stage/resource-fortran-installer-37thdsexf7e5iy7sgwkmmwl6nf7sokwn/spack-src/
        destination : /tmp/hv/spack-stage/spack-stage-intel-oneapi-compilers-2021.1.2-37thdsexf7e5iy7sgwkmmwl6nf7sokwn/spack-src/fortran-installer
==> No patches needed for intel-oneapi-compilers
==> intel-oneapi-compilers: Executing phase: 'install'
==> Error: Exception occurred in writer daemon!
Traceback (most recent call last):
  File "/src/util/spack/lib/spack/llnl/util/tty/log.py", line 768, in _writer_daemon
    line = _retry(in_pipe.readline)()
  File "/src/util/spack/lib/spack/llnl/util/tty/log.py", line 830, in wrapped
    return function(*args, **kwargs)
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 5: ordinal not in range(128)
==> Error: BrokenPipeError: [Errno 32] Broken pipe

/src/util/spack/lib/spack/spack/build_environment.py:902, in _setup_pkg_and_run:
        899        tb_string = traceback.format_exc()
        900
        901        # build up some context from the offending package so we can
  >>    902        # show that, too.
        903        package_context = get_package_context(tb)
        904
        905        logfile = None

See build log for details:
  /tmp/hv/spack-stage/spack-stage-intel-oneapi-compilers-2021.1.2-37thdsexf7e5iy7sgwkmmwl6nf7sokwn/spack-build-out.txt
% 
```
(.. but the build log appears to be truncated,  see below.)

```
% ./spack debug report
* **Spack:** 0.16.1-2078-a4c3bc9893
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-skylake
* **Concretizer:** original
% 
```

```
% cat spack-build-out.txt
==> intel-oneapi-compilers: Executing phase: 'install'
==> [2021-04-06-17:23:11.008612] 'bash' 'l_dpcpp-cpp-compiler_p_2021.1.2.63_offline.sh' '-s' '-a' '-s' '--action' 'install' '--eula' 'accept' '--install-dir' '/src/util/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/intel-oneapi-compilers-2021.1.2-37thdsexf7e5iy7sgwkmmwl6nf7sokwn'
Checking system requirements...
Done.
Wait while the installer is preparing...
Done.
Launching the installer...
% 
```

```
% cat spack-build-env.txt
BASH_ENV=/home/hv/.bashrc; export BASH_ENV
CC=/src/util/spack/lib/spack/env/gcc/gcc; export CC
CMAKE_PREFIX_PATH=/src/util/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/patchelf-0.10-4vf542wykmvpfolrytplar3gbytbwzo7; export CMAKE_PREFIX_PATH
CVS_RSH=ssh; export CVS_RSH
CXX=/src/util/spack/lib/spack/env/gcc/g++; export CXX
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus; export DBUS_SESSION_BUS_ADDRESS
DEFAULTS_PATH=/usr/share/gconf/fvwm.default.path; export DEFAULTS_PATH
DESKTOP_SESSION=fvwm; export DESKTOP_SESSION
DISPLAY=:1; export DISPLAY
EDITOR=vi; export EDITOR
FVWM_DATADIR=/usr/share/fvwm; export FVWM_DATADIR
FVWM_MODULEDIR=/usr/lib/fvwm/2.6.7; export FVWM_MODULEDIR
FVWM_USERDIR=/home/hv/.fvwm; export FVWM_USERDIR
GDMSESSION=fvwm; export GDMSESSION
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1; export GPG_AGENT_INFO
GTK_MODULES=gail:atk-bridge; export GTK_MODULES
HOME=/home/hv; export HOME
HOSTDISPLAY=zen2:1; export HOSTDISPLAY
LANG=C; export LANG
LANGUAGE=en_GB:en; export LANGUAGE
LC_ALL=C; export LC_ALL
LESSCLOSE='/usr/bin/lesspipe %s %s'; export LESSCLOSE
LESSOPEN='| /usr/bin/lesspipe %s'; export LESSOPEN
LOGNAME=hv; export LOGNAME
MANDATORY_PATH=/usr/share/gconf/fvwm.mandatory.path; export MANDATORY_PATH
#OLDPWD=/src/util/spack; export OLDPWD
PATH=/src/util/spack/lib/spack/env/gcc:/src/util/spack/lib/spack/env/case-insensitive:/src/util/spack/lib/spack/env:/src/util/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/patchelf-0.10-4vf542wykmvpfolrytplar3gbytbwzo7/bin:/src/util/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/patchelf-0.10-4vf542wykmvpfolrytplar3gbytbwzo7/bin:/home/hv/bin:/home/hv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin; export PATH
#PWD=/src/util/spack/bin; export PWD
QT_ACCESSIBILITY=1; export QT_ACCESSIBILITY
RSYNC_RSH=ssh; export RSYNC_RSH
SHELL=/bin/bash; export SHELL
SHLVL=2; export SHLVL
SPACK_CC=/usr/bin/gcc; export SPACK_CC
SPACK_CC_RPATH_ARG=-Wl,-rpath,; export SPACK_CC_RPATH_ARG
SPACK_COMPILER_SPEC=gcc@7.5.0; export SPACK_COMPILER_SPEC
SPACK_CXX=/usr/bin/g++; export SPACK_CXX
SPACK_CXX_RPATH_ARG=-Wl,-rpath,; export SPACK_CXX_RPATH_ARG
SPACK_DEBUG_LOG_DIR=/src/util/spack/bin; export SPACK_DEBUG_LOG_DIR
SPACK_DEBUG_LOG_ID=intel-oneapi-compilers-37thdse; export SPACK_DEBUG_LOG_ID
SPACK_DTAGS_TO_ADD=--disable-new-dtags; export SPACK_DTAGS_TO_ADD
SPACK_DTAGS_TO_STRIP=--enable-new-dtags; export SPACK_DTAGS_TO_STRIP
SPACK_ENV_PATH=/src/util/spack/lib/spack/env:/src/util/spack/lib/spack/env/case-insensitive:/src/util/spack/lib/spack/env/gcc; export SPACK_ENV_PATH
SPACK_F77_RPATH_ARG=-Wl,-rpath,; export SPACK_F77_RPATH_ARG
SPACK_FC_RPATH_ARG=-Wl,-rpath,; export SPACK_FC_RPATH_ARG
SPACK_INCLUDE_DIRS=''; export SPACK_INCLUDE_DIRS
SPACK_LD_LIBRARY_PATH=''; export SPACK_LD_LIBRARY_PATH
SPACK_LINKER_ARG=-Wl,; export SPACK_LINKER_ARG
SPACK_LINK_DIRS=''; export SPACK_LINK_DIRS
SPACK_NEW_LD_LIBRARY_PATH=''; export SPACK_NEW_LD_LIBRARY_PATH
SPACK_PYTHON=/usr/bin/python3; export SPACK_PYTHON
SPACK_RPATH_DIRS=/src/util/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/intel-oneapi-compilers-2021.1.2-37thdsexf7e5iy7sgwkmmwl6nf7sokwn/lib:/src/util/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/intel-oneapi-compilers-2021.1.2-37thdsexf7e5iy7sgwkmmwl6nf7sokwn/lib64; export SPACK_RPATH_DIRS
SPACK_SHORT_SPEC='intel-oneapi-compilers@2021.1.2%gcc@7.5.0 arch=linux-ubuntu18.04-skylake/37thdse'; export SPACK_SHORT_SPEC
SPACK_SYSTEM_DIRS=/bin:/usr/bin:/usr/local/bin:/bin64:/usr/bin64:/usr/local/bin64:/include:/usr/include:/usr/local/include:/lib:/usr/lib:/usr/local/lib:/lib64:/usr/lib64:/usr/local/lib64:/:/usr:/usr/local; export SPACK_SYSTEM_DIRS
SPACK_TARGET_ARGS='-march=skylake -mtune=skylake'; export SPACK_TARGET_ARGS
SSH_AGENT_PID=2200; export SSH_AGENT_PID
SSH_AUTH_SOCK=/tmp/ssh-SGEV1R3oUMTR/agent.2133; export SSH_AUTH_SOCK
TERM=xterm; export TERM
USER=hv; export USER
WINDOWID=31457295; export WINDOWID
WINDOWPATH=2; export WINDOWPATH
XAUTHORITY=/run/user/1000/gdm/Xauthority; export XAUTHORITY
XDG_CONFIG_DIRS=/etc/xdg/xdg-fvwm:/etc/xdg; export XDG_CONFIG_DIRS
XDG_DATA_DIRS=/usr/share/fvwm:/home/hv/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop; export XDG_DATA_DIRS
XDG_RUNTIME_DIR=/run/user/1000; export XDG_RUNTIME_DIR
XDG_SEAT=seat0; export XDG_SEAT
XDG_SESSION_DESKTOP=fvwm; export XDG_SESSION_DESKTOP
XDG_SESSION_ID=2; export XDG_SESSION_ID
XDG_SESSION_TYPE=x11; export XDG_SESSION_TYPE
XDG_VTNR=2; export XDG_VTNR
XTERM_LOCALE=en_GB.UTF-8; export XTERM_LOCALE
XTERM_SHELL=/bin/bash; export XTERM_SHELL
XTERM_VERSION='XTerm(330)'; export XTERM_VERSION
_=/usr/bin/python3; export _
% 
```

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ikitayama** [comment] 2021-04-06 21:31
Could you try with the latest `gcc@10.2.0` ?

**Comment by ikitayama** [comment] 2021-04-06 21:32
@hvds ?

**Comment by ikitayama** [comment] 2021-04-06 21:45
```

$ spack install intel-oneapi-compilers
[+] /p/project/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.2.0/patchelf-0.10-3h5fydwf2zlhdvzl2wdshljjl6564psm
==> Installing intel-oneapi-compilers-2021.1.2-sxlvko36uf2pldarrp746td3s32tcrzb
==> No binary for intel-oneapi-compilers-2021.1.2-sxlvko36uf2pldarrp746td3s32tcrzb found: installing from source
==> Fetching https://registrationcenter-download.intel.com/akdlm/irc_nas/17513/l_dpcpp-cpp-compiler_p_2021.1.2.63_offline.sh
######################################################################### 100.0%
==> Fetching https://registrationcenter-download.intel.com/akdlm/irc_nas/17508/l_fortran-compiler_p_2021.1.2.62_offline.sh
######################################################################### 100.0%
==> Moving resource stage
	source : /p/scratch/cjzam11/kitayama1/spack-stage/resource-fortran-installer-sxlvko36uf2pldarrp746td3s32tcrzb/spack-src/
	destination : /p/scratch/cjzam11/kitayama1/spack-stage/spack-stage-intel-oneapi-compilers-2021.1.2-sxlvko36uf2pldarrp746td3s32tcrzb/spack-src/fortran-installer
==> No patches needed for intel-oneapi-compilers
==> intel-oneapi-compilers: Executing phase: 'install'
==> intel-oneapi-compilers: Successfully installed intel-oneapi-compilers-2021.1.2-sxlvko36uf2pldarrp746td3s32tcrzb
  Fetch: 1m 8.90s.  Build: 4m 7.93s.  Total: 5m 16.83s.
[+] /p/project/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.2.0/intel-oneapi-compilers-2021.1.2-sxlvko36uf2pldarrp746td3s32tcrzb
```

**Comment by ikitayama** [comment] 2021-04-06 21:46
> Could you try with the latest `gcc@10.2.0` ?

`$ spack install gcc@10.2.0`

**Comment by hvds** [comment] 2021-04-06 22:03
> Could you try with the latest `gcc@10.2.0` ?

In principle I could (or more likely 9.2.1, for which I already have the C compiler installed); however the opaque error doesn't _look_ likely to be a direct cause of the compiler - I'd rather understand what command it is trying to execute, and dig into why that is failing. I'm confused that the log file doesn't show this sort of useful information, and that makes me less inclined to trust spack at all.

**Comment by ikitayama** [comment] 2021-04-06 22:03
With `clang@13.0.0` (from `main`) I was able to build it too.

**Comment by ikitayama** [comment] 2021-04-06 22:04
@adamjstewart , @haampie  would you please assist @hvds please?

**Comment by ikitayama** [comment] 2021-04-06 22:53
For the record, 
```
[+] /p/project/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen/gcc-7.5.0/intel-oneapi-compilers-2021.1.2-ieod4nh36qhfmqdp7ykkmfdvmrkzcb23
```

**Comment by adamjstewart** [comment] 2021-04-07 00:58
The reason that the error appears on the command-line but not in the log is that this is a Spack bug, not a build error. Seems like some kind of unicode decoder error. @scheibelp has solved a few of these in the past, so he may be able to help with this one.

**Comment by ikitayama** [comment] 2021-04-07 01:55
Thanks @adamjstewart seems to me it's best to use the `develop` branch for further testing.

**Comment by scheibelp** [comment] 2021-04-07 19:46
I can reproduce this on an Ubuntu 18.04 docker image with the latest Spack:

```
spack debug report
* **Spack:** 0.16.1-2115-f365cb4535
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-haswell
* **Concretizer:** original
```

I'll be looking at suggestions from #20837 and #15285 over the next couple days to look for a fix (folks in those threads have dealt with similar issues with workarounds).

**Comment by scheibelp** [comment] 2021-04-08 22:56
(EDIT 5 minutes after posting this: this patch is insufficient)

(fixed now) ~Unfortunately I am being held up by a secondary issue here (I think related to the docker image where I reproduced this error) where I cannot reinstall `intel-oneapi-compilers`. I'm trying to sort that out (which I think will take a day or two) and then get back to this issue.~

In the meantime, if you are able, can you retry with the following diff:

```
diff --git a/lib/spack/llnl/util/tty/log.py b/lib/spack/llnl/util/tty/log.py
index ef14baeacf..6adf8ac95e 100644
--- a/lib/spack/llnl/util/tty/log.py
+++ b/lib/spack/llnl/util/tty/log.py
@@ -722,7 +722,7 @@ def _writer_daemon(stdin_multiprocess_fd, read_multiprocess_fd, write_fd, echo,
 
     # Use line buffering (3rd param = 1) since Python 3 has a bug
     # that prevents unbuffered text I/O.
-    in_pipe = os.fdopen(read_multiprocess_fd.fd, 'r', 1)
+    in_pipe = os.fdopen(read_multiprocess_fd.fd, 'r', 1, encoding='utf-8')
 
     if stdin_multiprocess_fd:
         stdin = os.fdopen(stdin_multiprocess_fd.fd)
```

(this wouldn't work in all cases, e.g. if the build process was generating `utf-16`-encoded output, but may be useful for the time being)

**Comment by scheibelp** [comment] 2021-04-08 23:03
> In the meantime, if you are able, can you retry with the following diff:

I was able to resolve my problem and try that diff: it was not sufficient. I'll keep at it.

**Comment by scheibelp** [comment] 2021-04-09 00:54
#22888 fixes the issue for me. Could you try it out?

**Comment by ikitayama** [comment] 2021-04-09 03:52
Thanks @scheibelp ! @hvds , would you mind checking the latest `develop` branch to see if it fixes?

**Comment by hvds** [comment] 2021-04-09 11:40
Thanks, using spack@1b8d975a94 it worked for me.

**Closed as completed** 2021-04-10 01:10 UTC
Labels: build-error
