### ISSUE TITLE
Dependency detection through virtual dependencies is currently broken

### ISSUE THREAD

**Issue by krafczyk** [LLNL/spack#2185] opened 2016-10-31 03:19 UTC
When attempting to install hdf5, I get the following error message:

```
spack install hdf5@1.8.16+szip ^openmpi
==> Error: hdf5 does not depend on openmpi
```

**Comment by tgamblin** [comment] 2016-10-31 03:22
duplicate of #397

**Comment by tgamblin** [comment] 2016-10-31 03:22
You have to help the concretizer a little bit at the moment with optional dependencies -- the defaults are not applied until after all the other stuff is worked out, so they won't trigger an optional dep.  so this would work:

`spack install hdf5@1.8.16+szip +mpi ^openmpi`

**Closed by tgamblin** 2016-10-31 03:22 UTC
Labels: Astronomy, duplicate

**Comment by krafczyk** [comment] 2016-10-31 16:53
Oh yes, that worked. I thought that +mpi was enabled by default. My mistake.

**Comment by adamjstewart** [comment] 2016-10-31 17:03
@krafczyk It is enabled by default. But there's a bug in the concretizer which requires you to explicitly enable it in your spec if you want to specify which MPI implementation you want to use. This will hopefully be fixed in future updates.
