### ISSUE TITLE
Installation issue: py-pyqt5

### ISSUE THREAD

**Issue by gustavoberman** [LLNL/spack#33866] opened 2022-11-12 19:59 UTC
### Steps to reproduce the issue

```console
$ spack spec -I py-pyqt5@5.13.1
Input spec
--------------------------------
 -   py-pyqt5@5.13.1

Concretized
--------------------------------
 -   py-pyqt5@5.13.1%gcc@11.1.0~qsci_api build_system=sip arch=linux-centos7-x86_64
[+]      ^py-sip@4.19.21%gcc@11.1.0 build_system=python_pip module=PyQt5.sip arch=linux-centos7-x86_64
[+]          ^bison@3.8.2%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^diffutils@3.8%gcc@11.1.0 arch=linux-centos7-x86_64
[+]                  ^libiconv@1.16%gcc@11.1.0 libs=shared,static arch=linux-centos7-x86_64
[+]              ^m4@1.4.19%gcc@11.1.0+sigsegv arch=linux-centos7-x86_64
[+]                  ^libsigsegv@2.13%gcc@11.1.0 arch=linux-centos7-x86_64
[+]              ^perl@5.34.0%gcc@11.1.0+cpanm+shared+threads arch=linux-centos7-x86_64
[+]                  ^berkeley-db@18.1.40%gcc@11.1.0+cxx~docs+stl patches=b231fcc arch=linux-centos7-x86_64
[+]          ^flex@2.6.3%gcc@11.1.0+lex~nls build_system=autotools arch=linux-centos7-x86_64
[+]              ^findutils@4.9.0%gcc@11.1.0 build_system=autotools patches=440b954 arch=linux-centos7-x86_64
[+]          ^py-pip@22.2.2%gcc@11.1.0 build_system=generic arch=linux-centos7-x86_64
[+]          ^py-wheel@0.37.1%gcc@11.1.0 build_system=generic arch=linux-centos7-x86_64
[+]      ^python@3.10.8%gcc@11.1.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=linux-centos7-x86_64
[+]          ^bzip2@1.0.8%gcc@11.1.0~debug~pic+shared build_system=generic arch=linux-centos7-x86_64
[+]          ^expat@2.4.8%gcc@11.1.0+libbsd build_system=autotools arch=linux-centos7-x86_64
[+]              ^libbsd@0.11.5%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]                  ^libmd@1.0.4%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^gdbm@1.19%gcc@11.1.0 arch=linux-centos7-x86_64
[+]          ^gettext@0.21.1%gcc@11.1.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-centos7-x86_64
[+]              ^libiconv@1.16%gcc@11.1.0 arch=linux-centos7-x86_64
[+]              ^tar@1.34%gcc@11.1.0 build_system=autotools zip=pigz arch=linux-centos7-x86_64
[+]                  ^pigz@2.7%gcc@11.1.0 build_system=makefile arch=linux-centos7-x86_64
[+]          ^libffi@3.4.2%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^ncurses@6.2%gcc@11.1.0~symlinks+termlib abi=none arch=linux-centos7-x86_64
[+]          ^openssl@1.1.1k%gcc@11.1.0~docs+systemcerts arch=linux-centos7-x86_64
[+]          ^pkgconf@1.8.0%gcc@11.1.0 arch=linux-centos7-x86_64
[+]          ^readline@8.1%gcc@11.1.0 arch=linux-centos7-x86_64
[+]          ^sqlite@3.39.4%gcc@11.1.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-centos7-x86_64
[+]          ^util-linux-uuid@2.38.1%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^xz@5.2.5%gcc@11.1.0~pic libs=shared,static arch=linux-centos7-x86_64
[+]          ^zlib@1.2.11%gcc@11.1.0+optimize+pic+shared arch=linux-centos7-x86_64
[+]      ^qt@5.15.5%gcc@11.1.0~dbus~debug~doc~examples~framework~gtk+gui+opengl~phonon+shared+sql+ssl+tools~webkit build_system=generic patches=2081e9c,51aeba5,75bcb42,7f34d48,84b0991,8cd4be9,9378afd arch=linux-centos7-x86_64
[+]          ^assimp@5.2.4%gcc@11.1.0~ipo+shared build_system=cmake build_type=RelWithDebInfo arch=linux-centos7-x86_64
[+]              ^cmake@3.20.3%gcc@11.1.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-centos7-x86_64
[+]          ^double-conversion@3.1.5%gcc@11.1.0~ipo build_system=cmake build_type=RelWithDebInfo arch=linux-centos7-x86_64
[+]          ^fontconfig@2.13.94%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^font-util@1.3.2%gcc@11.1.0 build_system=autotools fonts=encodings,font-adobe-100dpi,font-adobe-75dpi,font-adobe-utopia-100dpi,font-adobe-utopia-75dpi,font-adobe-utopia-type1,font-alias,font-arabic-misc,font-bh-100dpi,font-bh-75dpi,font-bh-lucidatypewriter-100dpi,font-bh-lucidatypewriter-75dpi,font-bh-type1,font-bitstream-100dpi,font-bitstream-75dpi,font-bitstream-speedo,font-bitstream-type1,font-cronyx-cyrillic,font-cursor-misc,font-daewoo-misc,font-dec-misc,font-ibm-type1,font-isas-misc,font-jis-misc,font-micro-misc,font-misc-cyrillic,font-misc-ethiopic,font-misc-meltho,font-misc-misc,font-mutt-misc,font-schumacher-misc,font-screen-cyrillic,font-sun-misc,font-winitzki-cyrillic,font-xfree86-type1 arch=linux-centos7-x86_64
[+]                  ^autoconf@2.69%gcc@11.1.0 arch=linux-centos7-x86_64
[+]                  ^automake@1.16.3%gcc@11.1.0 arch=linux-centos7-x86_64
[+]                  ^bdftopcf@1.0.5%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]                      ^fontsproto@2.1.3%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]                      ^libxfont@1.5.2%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]                  ^mkfontdir@1.0.7%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]                  ^mkfontscale@1.1.2%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]                      ^libfontenc@1.1.3%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^gperf@3.1%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^freetype@2.11.1%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^glib@2.74.1%gcc@11.1.0~libmount build_system=generic tracing=none arch=linux-centos7-x86_64
[+]              ^meson@0.63.3%gcc@11.1.0 build_system=python_pip patches=aa6c50d arch=linux-centos7-x86_64
[+]                  ^py-setuptools@65.5.0%gcc@11.1.0 build_system=generic arch=linux-centos7-x86_64
[+]              ^ninja@1.11.1%gcc@11.1.0 build_system=generic arch=linux-centos7-x86_64
[+]          ^glx@1.4%gcc@11.1.0 build_system=bundle arch=linux-centos7-x86_64
[+]              ^mesa@22.1.2%gcc@11.1.0+glx+llvm+opengl~opengles+osmesa~strip build_system=meson buildtype=release default_library=shared patches=ee737d1 arch=linux-centos7-x86_64
[+]                  ^glproto@1.4.17%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]                  ^libunwind@1.6.2%gcc@11.1.0~block_signals~conservative_checks~cxx_exceptions~debug~debug_frame+docs~pic+tests+weak_backtrace~xz~zlib build_system=autotools components=none libs=shared,static arch=linux-centos7-x86_64
[+]                  ^libxt@1.1.5%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]                  ^llvm@14.0.6%gcc@11.1.0+clang+compiler-rt~cuda~flang+gold+internal_unwind~ipo+libcxx~link_llvm_dylib+lld+lldb+llvm_dylib~mlir+omp_as_runtime~omp_debug~omp_tsan+polly~python~split_dwarf~z3 build_system=cmake build_type=Release patches=6379168,d85ef51,f920173 shlib_symbol_version=none targets=none version_suffix=none arch=linux-centos7-x86_64
[+]                      ^binutils@2.38%gcc@11.1.0~gas+gold~headers~interwork+ld~libiberty~lto+nls+plugins build_system=autotools libs=shared,static arch=linux-centos7-x86_64
[+]                          ^diffutils@3.8%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]                      ^hwloc@2.5.0%gcc@11.1.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml+pci+shared arch=linux-centos7-x86_64
[+]                          ^libpciaccess@0.16%gcc@11.1.0 arch=linux-centos7-x86_64
[+]                      ^libedit@3.1-20210216%gcc@11.1.0 arch=linux-centos7-x86_64
[+]                      ^perl-data-dumper@2.173%gcc@11.1.0 build_system=perl arch=linux-centos7-x86_64
[+]                  ^py-mako@1.2.2%gcc@11.1.0 build_system=python_pip arch=linux-centos7-x86_64
[+]                      ^py-markupsafe@2.1.1%gcc@11.1.0 build_system=python_pip arch=linux-centos7-x86_64
[+]                  ^xrandr@1.5.0%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]                      ^libxrandr@1.5.0%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]                      ^randrproto@1.5.0%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^harfbuzz@5.1.0%gcc@11.1.0~graphite2~strip build_system=meson buildtype=debugoptimized default_library=shared arch=linux-centos7-x86_64
[+]              ^cairo@1.16.0%gcc@11.1.0~X~fc+ft+gobject+pdf~png~svg build_system=autotools patches=7c4da77 arch=linux-centos7-x86_64
[+]                  ^libtool@2.4.6%gcc@11.1.0 arch=linux-centos7-x86_64
[+]                  ^pixman@0.40.0%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^gobject-introspection@1.72.0%gcc@11.1.0~strip build_system=meson buildtype=debugoptimized default_library=shared arch=linux-centos7-x86_64
[+]          ^icu4c@67.1%gcc@11.1.0 build_system=autotools cxxstd=11 arch=linux-centos7-x86_64
[+]              ^python@3.10.8%gcc@11.1.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=linux-centos7-x86_64
[+]                  ^gettext@0.21.1%gcc@11.1.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-centos7-x86_64
[+]                      ^libxml2@2.10.1%gcc@11.1.0~python build_system=autotools arch=linux-centos7-x86_64
[+]                      ^tar@1.34%gcc@11.1.0 build_system=autotools zip=pigz arch=linux-centos7-x86_64
[+]                  ^xz@5.2.5%gcc@11.1.0~pic libs=shared,static arch=linux-centos7-x86_64
[+]          ^libjpeg-turbo@2.1.3%gcc@11.1.0 build_system=generic arch=linux-centos7-x86_64
[+]              ^nasm@2.15.05%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^libmng@2.0.3%gcc@11.1.0~ipo build_system=cmake build_type=RelWithDebInfo arch=linux-centos7-x86_64
[+]              ^lcms@2.13.1%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^libpng@1.6.37%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^libsm@1.2.3%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^libice@1.0.9%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^util-macros@1.19.1%gcc@11.1.0 arch=linux-centos7-x86_64
[+]              ^xproto@7.0.31%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^xtrans@1.3.5%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^libtiff@4.4.0%gcc@11.1.0+ccitt~ipo~jbig+jpeg~jpeg12~lerc~libdeflate+logluv~lzma+lzw+next~old-jpeg+packbits~pixarlog+thunder~webp+zlib~zstd build_system=cmake build_type=RelWithDebInfo arch=linux-centos7-x86_64
[+]          ^libx11@1.7.0%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^inputproto@2.3.2%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^kbproto@1.0.7%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^xextproto@7.3.0%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^libxcb@1.14%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^libpthread-stubs@0.4%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^libxau@1.0.8%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^libxdmcp@1.1.2%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^xcb-proto@1.14.1%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^libxext@1.3.3%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^libxkbcommon@1.4.0%gcc@11.1.0~strip~wayland build_system=meson buildtype=debugoptimized default_library=shared arch=linux-centos7-x86_64
[+]              ^xkbdata@1.0.1%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]                  ^xkbcomp@1.4.4%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]                      ^libxkbfile@1.0.9%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^libxml2@2.9.10%gcc@11.1.0~python arch=linux-centos7-x86_64
[+]          ^libxrender@0.9.10%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^renderproto@0.11.1%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^pcre2@10.39%gcc@11.1.0~jit+multibyte build_system=autotools arch=linux-centos7-x86_64
[+]          ^xcb-util-image@0.4.0%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]              ^xcb-util@0.4.0%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^xcb-util-keysyms@0.4.0%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^xcb-util-renderutil@0.3.9%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^xcb-util-wm@0.4.1%gcc@11.1.0 build_system=autotools arch=linux-centos7-x86_64
[+]          ^zstd@1.5.2%gcc@11.1.0+programs build_system=makefile compression=none libs=shared,static arch=linux-centos7-x86_64

...
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing py-pyqt5-5.13.1-c7ok2d3elnimd24lvim6py4wdxfea6f2
==> No binary for py-pyqt5-5.13.1-c7ok2d3elnimd24lvim6py4wdxfea6f2 found: installing from source
==> Using cached archive: /share/apps/spack/var/spack/cache/_source-cache/archive/54/54b7f456341b89eeb3930e786837762ea67f235e886512496c4152ebe106d4af.tar.gz
==> No patches needed for py-pyqt5
==> py-pyqt5: Executing phase: 'configure'
==> Error: AttributeError: 'Adapter' object has no attribute 'python'

The 'py-pyqt5' package cannot find an attribute while trying to build from sources. This might be due to a change in Spack's package format to support multiple build-systems for a single package. You can fix this by updating the build recipe, and you can also report the issue as a bug. More information at https://spack.readthedocs.io/en/latest/packaging_guide.html#installation-procedure

/share/apps/spack/lib/spack/spack/builder.py:142, in __forward:
  >>    142        def __forward(self, *args, **kwargs):
        143            return self.__getattr__(fn_name)(*args, **kwargs)

See build log for details:
  /tmp/root/spack-stage/spack-stage-py-pyqt5-5.13.1-c7ok2d3elnimd24lvim6py4wdxfea6f2/spack-build-out.txt

...
</pre></details>

### Information on your system

spack debug report
* **Spack:** 0.19.0.dev0
* **Python:** 3.10.8
* **Platform:** linux-centos7-x86_64
* **Concretizer:** clingo

### Additional information

cat spack-build-out.txt 
==> py-pyqt5: Executing phase: 'configure'

------------------------------
[spack-build-env.txt](https://github.com/spack/spack/files/9995801/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by gustavoberman** [comment] 2022-11-13 00:15
Looks like same problem that [https://github.com/spack/spack/issues/33806](url)
#33806

**Comment by adamjstewart** [comment] 2022-11-13 21:30
Yep, closing as duplicate of #33806

**Closed as completed by adamjstewart** 2022-11-13 21:30 UTC
Labels: build-error
