### ISSUE TITLE
spack uninstall: inconsistent state in DB

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#32715] opened 2022-09-19 18:27 UTC
### Steps to reproduce

```console
$ spack install gcc
$ spack uninstall -ay
```

### Error message

```console
$ spack uninstall -ay
...
==> Successfully uninstalled autoconf-archive@2022.02.11%apple-clang@14.0.0 patches=139214f arch=darwin-monterey-m1/pgksyme
==> Successfully uninstalled zstd@1.5.2%apple-clang@14.0.0~programs libs=shared,static arch=darwin-monterey-m1/2l3wtxf
==> Successfully uninstalled autoconf@2.69%apple-clang@14.0.0 patches=35c4492,7793209,a49dd5b arch=darwin-monterey-m1/3ocdsdv
==> Successfully uninstalled diffutils@3.8%apple-clang@14.0.0 arch=darwin-monterey-m1/cykevnq
==> Successfully uninstalled libtool@2.4.7%apple-clang@14.0.0 arch=darwin-monterey-m1/ov3azl4
==> Successfully uninstalled pkgconf@1.8.0%apple-clang@14.0.0 arch=darwin-monterey-m1/wrbynmy
==> Successfully uninstalled automake@1.16.5%apple-clang@14.0.0 arch=darwin-monterey-m1/ppvglkw
==> Successfully uninstalled gnuconfig@2021-08-14%apple-clang@14.0.0 arch=darwin-monterey-m1/waq44kg
==> Successfully uninstalled gawk@5.1.1%apple-clang@14.0.0~nls arch=darwin-monterey-m1/tzmwt47
==> Successfully uninstalled texinfo@6.5%apple-clang@14.0.0 patches=12f6edb,1732115 arch=darwin-monterey-m1/wwiezo5
==> Successfully uninstalled mpc@1.2.1%apple-clang@14.0.0 libs=shared,static arch=darwin-monterey-m1/bx4pxnu
==> Successfully uninstalled libiconv@1.16%apple-clang@14.0.0 libs=shared,static arch=darwin-monterey-m1/jsxdcns
==> Successfully uninstalled perl@5.34.1%apple-clang@14.0.0+cpanm+shared+threads arch=darwin-monterey-m1/q3asorm
==> Successfully uninstalled m4@1.4.19%apple-clang@14.0.0+sigsegv patches=9dc5fbd,bfdffa7 arch=darwin-monterey-m1/jufcxnn
==> Successfully uninstalled mpfr@4.1.0%apple-clang@14.0.0 libs=shared,static arch=darwin-monterey-m1/2yfkhwh
==> Warning: Inconsistent state! Dependent wwiezo5roe6l7bhcskftqm7wkf3asblo of 24geus7kk6earlnxuzy73cn27wwcxfxd not in DB
==> Successfully uninstalled berkeley-db@18.1.40%apple-clang@14.0.0+cxx~docs+stl patches=26090f4,b231fcc arch=darwin-monterey-m1/24geus7
==> Warning: Inconsistent state! Dependent wwiezo5roe6l7bhcskftqm7wkf3asblo of lgdwy3d3n76355blegep7x4vwrlzlvpn not in DB
==> Successfully uninstalled gdbm@1.19%apple-clang@14.0.0 arch=darwin-monterey-m1/lgdwy3d
==> Successfully uninstalled libsigsegv@2.13%apple-clang@14.0.0 arch=darwin-monterey-m1/tbnsbgv
==> Warning: Inconsistent state! Dependent wwiezo5roe6l7bhcskftqm7wkf3asblo of ay6ey4schmydozukowbddpoekdvgvlaq not in DB
==> Successfully uninstalled zlib@1.2.12%apple-clang@14.0.0+optimize+pic+shared patches=0d38234 arch=darwin-monterey-m1/ay6ey4s
==> Successfully uninstalled gmp@6.2.1%apple-clang@14.0.0 libs=shared,static arch=darwin-monterey-m1/zor44kd
==> Warning: Inconsistent state! Dependent q3asormd2bxlzo3kel2dqwld3e3cpevi of b2pyoazvk5xzs3gzh624ow5bsep25b6b not in DB
==> Warning: Inconsistent state! Dependent 3ocdsdv7qpbqsfflnmmktje6puvp6rmq of b2pyoazvk5xzs3gzh624ow5bsep25b6b not in DB
==> Warning: Inconsistent state! Dependent ppvglkwzlvfklgybqdnzcgo2y5aqwiay of b2pyoazvk5xzs3gzh624ow5bsep25b6b not in DB
==> Warning: Inconsistent state! Dependent wwiezo5roe6l7bhcskftqm7wkf3asblo of b2pyoazvk5xzs3gzh624ow5bsep25b6b not in DB
==> Successfully uninstalled bzip2@1.0.8%apple-clang@14.0.0~debug~pic+shared arch=darwin-monterey-m1/b2pyoaz
==> Warning: Inconsistent state! Dependent lgdwy3d3n76355blegep7x4vwrlzlvpn of lck4i33bkkxfqtojmfwvmtfwquprf7gk not in DB
==> Warning: Inconsistent state! Dependent q3asormd2bxlzo3kel2dqwld3e3cpevi of lck4i33bkkxfqtojmfwvmtfwquprf7gk not in DB
==> Warning: Inconsistent state! Dependent 3ocdsdv7qpbqsfflnmmktje6puvp6rmq of lck4i33bkkxfqtojmfwvmtfwquprf7gk not in DB
==> Warning: Inconsistent state! Dependent ppvglkwzlvfklgybqdnzcgo2y5aqwiay of lck4i33bkkxfqtojmfwvmtfwquprf7gk not in DB
==> Warning: Inconsistent state! Dependent wwiezo5roe6l7bhcskftqm7wkf3asblo of lck4i33bkkxfqtojmfwvmtfwquprf7gk not in DB
==> Successfully uninstalled readline@8.1.2%apple-clang@14.0.0 arch=darwin-monterey-m1/lck4i33
==> Successfully uninstalled ncurses@6.3%apple-clang@14.0.0~symlinks+termlib abi=none arch=darwin-monterey-m1/duhzt5q
```
Spack should not be creating inconsistent DB states, especially with such a simple set of packages.

### Information on your system

* **Spack:** 0.19.0.dev0 (2f19826470b4009fa82b181b673b0520c8fa993a)
* **Python:** 3.8.9
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2022-09-20 06:47
Duplicate of #31366

**Closed as completed** 2022-09-20 13:23 UTC
Labels: bug, duplicate, impact-low
