### ISSUE TITLE
Environment concretization doesn't respect compiler

### ISSUE THREAD

**Issue by sethrj** [LLNL/spack#32170] opened 2022-08-16 11:07 UTC
### Steps to reproduce

I have a simple one-package environment asking for the NVHPC compiler. Manually concretizing the sole package on the command line works.
```console
$ spack spec -I geant4@11 cxxstd=17 %nvhpc
Input spec
--------------------------------
 -   geant4@11%nvhpc cxxstd=17

Concretized
--------------------------------
 -   geant4@11.0.2%nvhpc@22.5~ipo~motif~opengl~python~qt~tbb+threads~vecgeom~vtk~x11 build_type=RelWithDebInfo cxxstd=17 arch=linux-ubuntu20.04-cascadelake
 -       ^clhep@2.4.5.1%nvhpc@22.5~ipo build_type=RelWithDebInfo cxxstd=17 arch=linux-ubuntu20.04-cascadelake
 -           ^cmake@3.22.1%nvhpc@22.5~doc+ncurses+ownlibs~qt build_type=Release arch=linux-ubuntu20.04-cascadelake
 -       ^expat@2.4.8%nvhpc@22.5+libbsd arch=linux-ubuntu20.04-cascadelake
 -           ^libbsd@0.11.3%nvhpc@22.5 arch=linux-ubuntu20.04-cascadelake
 -               ^libmd@1.0.4%nvhpc@22.5 patches=991953c arch=linux-ubuntu20.04-cascadelake
 -       ^geant4-data@11.0.0%nvhpc@22.5 arch=linux-ubuntu20.04-cascadelake
 -           ^g4abla@3.1%nvhpc@22.5 arch=linux-ubuntu20.04-cascadelake
 -           ^g4emlow@8.0%nvhpc@22.5 arch=linux-ubuntu20.04-cascadelake
 -           ^g4ensdfstate@2.3%nvhpc@22.5 arch=linux-ubuntu20.04-cascadelake
 -           ^g4incl@1.0%nvhpc@22.5 arch=linux-ubuntu20.04-cascadelake
 -           ^g4ndl@4.6%nvhpc@22.5 arch=linux-ubuntu20.04-cascadelake
 -           ^g4particlexs@4.0%nvhpc@22.5 arch=linux-ubuntu20.04-cascadelake
 -           ^g4photonevaporation@5.7%nvhpc@22.5 arch=linux-ubuntu20.04-cascadelake
 -           ^g4pii@1.3%nvhpc@22.5 arch=linux-ubuntu20.04-cascadelake
 -           ^g4radioactivedecay@5.6%nvhpc@22.5 arch=linux-ubuntu20.04-cascadelake
 -           ^g4realsurface@2.2%nvhpc@22.5 arch=linux-ubuntu20.04-cascadelake
 -           ^g4saiddata@2.0%nvhpc@22.5 arch=linux-ubuntu20.04-cascadelake
 -       ^xerces-c@3.2.3%nvhpc@22.5 cxxstd=17 netaccessor=curl transcoder=gnuiconv arch=linux-ubuntu20.04-cascadelake
 -           ^curl@7.68.0%nvhpc@22.5+gssapi+ldap~libidn2~librtmp~libssh~libssh2+nghttp2 libs=shared,static tls=openssl arch=linux-ubuntu20.04-cascadelake
 -           ^libiconv@1.16%nvhpc@22.5 libs=shared,static arch=linux-ubuntu20.04-cascadelake
 -       ^zlib@1.2.12%nvhpc@22.5+optimize+pic+shared patches=0d38234 arch=linux-ubuntu20.04-cascadelake
```

### Error message

Actual concretization of the environment:
```console
$ cat spack.yaml
spack:
  specs:
  - geant4@11 cxxstd=17
  view: true
  concretizer:
    unify: true
  packages:
    all:
      compiler: [nvhpc]
$ spack -e . concretize --fresh -f
==> Concretized geant4@11 cxxstd=17
 -   tlct553  geant4@11.0.2%gcc@11.1.0~ipo~motif~opengl~python~qt~tbb+threads~vecgeom~vtk~x11 build_type=RelWithDebInfo cxxstd=17 arch=linux-ubuntu20.04-cascadelake
 -   ogkfuq4      ^clhep@2.4.5.1%gcc@11.1.0~ipo build_type=RelWithDebInfo cxxstd=17 arch=linux-ubuntu20.04-cascadelake
[+]  56ms6r3          ^cmake@3.22.1%gcc@11.1.0~doc+ncurses+ownlibs~qt build_type=Release arch=linux-ubuntu20.04-cascadelake
[+]  itevo6w      ^expat@2.4.8%gcc@11.1.0+libbsd arch=linux-ubuntu20.04-cascadelake
[+]  kf4p7p5          ^libbsd@0.11.5%gcc@11.1.0 arch=linux-ubuntu20.04-cascadelake
[+]  obe6ay6              ^libmd@1.0.4%gcc@11.1.0 arch=linux-ubuntu20.04-cascadelake
 -   t3hm3rk      ^geant4-data@11.0.0%gcc@11.1.0 arch=linux-ubuntu20.04-cascadelake
 -   opddw7a          ^g4abla@3.1%gcc@11.1.0 arch=linux-ubuntu20.04-cascadelake
 -   bjegzqz          ^g4emlow@8.0%gcc@11.1.0 arch=linux-ubuntu20.04-cascadelake
 -   hwmfczb          ^g4ensdfstate@2.3%gcc@11.1.0 arch=linux-ubuntu20.04-cascadelake
 -   b7lbatt          ^g4incl@1.0%gcc@11.1.0 arch=linux-ubuntu20.04-cascadelake
 -   2awzuld          ^g4ndl@4.6%gcc@11.1.0 arch=linux-ubuntu20.04-cascadelake
 -   6lodmnm          ^g4particlexs@4.0%gcc@11.1.0 arch=linux-ubuntu20.04-cascadelake
 -   h54ybro          ^g4photonevaporation@5.7%gcc@11.1.0 arch=linux-ubuntu20.04-cascadelake
 -   q2r6nvx          ^g4pii@1.3%gcc@11.1.0 arch=linux-ubuntu20.04-cascadelake
 -   kgljnqw          ^g4radioactivedecay@5.6%gcc@11.1.0 arch=linux-ubuntu20.04-cascadelake
 -   dh3rkan          ^g4realsurface@2.2%gcc@11.1.0 arch=linux-ubuntu20.04-cascadelake
 -   fxveowb          ^g4saiddata@2.0%gcc@11.1.0 arch=linux-ubuntu20.04-cascadelake
 -   vouzvme      ^xerces-c@3.2.3%gcc@11.1.0 cxxstd=17 netaccessor=curl transcoder=gnuiconv arch=linux-ubuntu20.04-cascadelake
 -   ie7ewbm          ^curl@7.68.0%gcc@11.1.0+gssapi+ldap~libidn2~librtmp~libssh~libssh2+nghttp2 libs=shared,static tls=openssl arch=linux-ubuntu20.04-cascadelake
[+]  bmbhjzc          ^libiconv@1.16%gcc@11.1.0 libs=shared,static arch=linux-ubuntu20.04-cascadelake
[+]  r2pqna7      ^zlib@1.2.12%gcc@11.1.0+optimize+pic+shared patches=0d38234 arch=linux-ubuntu20.04-cascadelake
```

### Information on your system

* **Spack:** 0.19.0.dev0 (89d55149c311aae2ca85d6fb032dcdb9b3ec4bf3)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

Possibly related: https://github.com/spack/spack/issues/28889

[packages.yaml.txt](https://github.com/spack/spack/files/9350215/packages.yaml.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2022-08-19 09:22
Reproduced the bug. You can workaround it with:
```yaml
spack:
  specs:
  - geant4@11 cxxstd=17
  view: true
  concretizer:
    unify: true
  packages:
    geant4:
      require: '%nvhpc'
```
in which case I get the following spec:

<details>

<summary>geant4@11 cxxstd=17</summary>

```
==> Concretized geant4@11 cxxstd=17
 -   4owwk6w  geant4@11.0.2%nvhpc@22.7~ipo~motif~opengl~python~qt~tbb+threads~vecgeom~vtk~x11 build_type=RelWithDebInfo cxxstd=17 arch=linux-ubuntu20.04-icelake
 -   i7gb3hi      ^clhep@2.4.5.1%gcc@12.1.0~ipo build_type=RelWithDebInfo cxxstd=17 arch=linux-ubuntu20.04-icelake
 -   bnjkjyx          ^cmake@3.23.3%gcc@12.1.0~doc+ncurses+ownlibs~qt build_type=Release arch=linux-ubuntu20.04-icelake
 -   caxzf26              ^ncurses@6.3%gcc@12.1.0~symlinks+termlib abi=none arch=linux-ubuntu20.04-icelake
 -   n42tagm                  ^pkgconf@1.8.0%gcc@12.1.0 arch=linux-ubuntu20.04-icelake
 -   euzuaun              ^openssl@1.1.1q%gcc@12.1.0~docs~shared certs=mozilla patches=3fdcf2d arch=linux-ubuntu20.04-icelake
 -   r5jowac                  ^ca-certificates-mozilla@2022-07-19%gcc@12.1.0 arch=linux-ubuntu20.04-icelake
 -   2d62hyr                  ^perl@5.34.1%gcc@12.1.0+cpanm+shared+threads arch=linux-ubuntu20.04-icelake
 -   uz3f5do                      ^berkeley-db@18.1.40%gcc@12.1.0+cxx~docs+stl patches=b231fcc arch=linux-ubuntu20.04-icelake
 -   n2dyye3                      ^bzip2@1.0.8%gcc@12.1.0~debug~pic+shared arch=linux-ubuntu20.04-icelake
 -   n5enre3                          ^diffutils@3.8%gcc@12.1.0 arch=linux-ubuntu20.04-icelake
 -   ximovra                              ^libiconv@1.16%gcc@12.1.0 libs=shared,static arch=linux-ubuntu20.04-icelake
 -   xz2pkvk                      ^gdbm@1.19%gcc@12.1.0 arch=linux-ubuntu20.04-icelake
 -   qfa44fh                          ^readline@8.1.2%gcc@12.1.0 arch=linux-ubuntu20.04-icelake
 -   hshnexs                      ^zlib@1.2.12%gcc@12.1.0+optimize+pic+shared patches=0d38234 arch=linux-ubuntu20.04-icelake
 -   evafzdm      ^expat@2.4.8%nvhpc@22.7+libbsd arch=linux-ubuntu20.04-icelake
 -   2jrwzd3          ^libbsd@0.11.3%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   x2sjqtb              ^libmd@1.0.4%nvhpc@22.7 patches=991953c arch=linux-ubuntu20.04-icelake
 -   rk62ync      ^geant4-data@11.0.0%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   k6e2cve          ^g4abla@3.1%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   ghw4zgv          ^g4emlow@8.0%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   2mzps2n          ^g4ensdfstate@2.3%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   onrthas          ^g4incl@1.0%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   2ggy5vl          ^g4ndl@4.6%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   3rkf55c          ^g4particlexs@4.0%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   2gh5krv          ^g4photonevaporation@5.7%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   kf6bjiu          ^g4pii@1.3%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   gwdkj3n          ^g4radioactivedecay@5.6%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   qxt6gji          ^g4realsurface@2.2%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   zimnhdf          ^g4saiddata@2.0%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   apri3nc      ^xerces-c@3.2.3%gcc@12.1.0 cxxstd=17 netaccessor=curl transcoder=gnuiconv arch=linux-ubuntu20.04-icelake
 -   6y7gmd5          ^curl@7.84.0%gcc@12.1.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2~nghttp2 libs=shared,static patches=9b011c9 tls=openssl arch=linux-ubuntu20.04-icelake
```

</details>

**Comment by alalazo** [comment] 2022-08-19 09:35
@sethrj This is one conflict that messes with your configuration (there might be more):

https://github.com/spack/spack/blob/be62635154758ace2337d8828f9eac5743115122/var/spack/repos/builtin/packages/cmake/package.py#L192-L194

Spack prefers to keep the default variant and use other compilers if you use preferences only. When you force the compiler on `geant4` like above it prefers to take a penalty on `cmake%gcc` rather than using `cmake%nvhpc~owlibs`. I tried to hack package requirements to allow for using `all` as a default and if we require `%nvhpc` everywhere this is the result:

```console
==> Concretized geant4@11 cxxstd=17
 -   gqlw436  geant4@11.0.2%nvhpc@22.7~ipo~motif~opengl~python~qt~tbb+threads~vecgeom~vtk~x11 build_type=RelWithDebInfo cxxstd=17 arch=linux-ubuntu20.04-icelake
 -   kyuvqgx      ^clhep@2.4.5.1%nvhpc@22.7~ipo build_type=RelWithDebInfo cxxstd=17 arch=linux-ubuntu20.04-icelake
 -   7cfogdv          ^cmake@3.23.3%nvhpc@22.7~doc+ncurses~ownlibs~qt build_type=Release arch=linux-ubuntu20.04-icelake
 -   hyu57tz              ^curl@7.84.0%nvhpc@22.7~gssapi~ldap~libidn2~librtmp~libssh~libssh2~nghttp2 libs=shared,static patches=9b011c9 tls=openssl arch=linux-ubuntu20.04-icelake
 -   36dbaua                  ^openssl@1.1.1q%nvhpc@22.7~docs~shared certs=mozilla patches=3fdcf2d arch=linux-ubuntu20.04-icelake
 -   cdhvzys                      ^ca-certificates-mozilla@2022-07-19%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   bjdzgre                      ^perl@5.34.1%nvhpc@22.7+cpanm+shared+threads patches=75c90f1 arch=linux-ubuntu20.04-icelake
 -   g3vqqfd                          ^berkeley-db@18.1.40%nvhpc@22.7+cxx~docs+stl patches=b231fcc arch=linux-ubuntu20.04-icelake
 -   qbmq5uc                          ^bzip2@1.0.8%nvhpc@22.7~debug~pic+shared arch=linux-ubuntu20.04-icelake
 -   u5vgvyg                              ^diffutils@3.7%nvhpc@22.7 patches=6e42dc2 arch=linux-ubuntu20.04-icelake
 -   wncsqpa                                  ^libiconv@1.16%nvhpc@22.7 libs=shared,static arch=linux-ubuntu20.04-icelake
 -   a4oe32h                          ^gdbm@1.19%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   xdv3bzv                              ^readline@8.1.2%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   2r2rp7j                                  ^ncurses@6.3%nvhpc@22.7~symlinks+termlib abi=none patches=933af9e arch=linux-ubuntu20.04-icelake
 -   mpjpsq7                                      ^pkgconf@1.8.0%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   33d3fvw                          ^zlib@1.2.12%nvhpc@22.7+optimize+pic+shared patches=0d38234 arch=linux-ubuntu20.04-icelake
 -   evafzdm              ^expat@2.4.8%nvhpc@22.7+libbsd arch=linux-ubuntu20.04-icelake
 -   2jrwzd3                  ^libbsd@0.11.3%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   x2sjqtb                      ^libmd@1.0.4%nvhpc@22.7 patches=991953c arch=linux-ubuntu20.04-icelake
 -   daqjmzp              ^libarchive@3.5.2%nvhpc@22.7+iconv compression=bz2lib,lz4,lzma,lzo2,zlib crypto=mbedtls libs=shared,static programs=none xar=expat arch=linux-ubuntu20.04-icelake
 -   5onzjfk                  ^lz4@1.9.3%nvhpc@22.7 libs=shared,static arch=linux-ubuntu20.04-icelake
 -   ul34bzz                  ^lzo@2.10%nvhpc@22.7 libs=shared,static arch=linux-ubuntu20.04-icelake
 -   rfehylw                  ^mbedtls@2.28.0%nvhpc@22.7+pic build_type=Release libs=static arch=linux-ubuntu20.04-icelake
 -   6tvcsyr                  ^xz@5.2.5%nvhpc@22.7~pic libs=shared,static arch=linux-ubuntu20.04-icelake
 -   o4xyu7k              ^libuv@1.44.1%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   f7hq2n5              ^rhash@1.4.2%nvhpc@22.7 patches=093518c,3fbfe46 arch=linux-ubuntu20.04-icelake
 -   rk62ync      ^geant4-data@11.0.0%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   k6e2cve          ^g4abla@3.1%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   ghw4zgv          ^g4emlow@8.0%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   2mzps2n          ^g4ensdfstate@2.3%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   onrthas          ^g4incl@1.0%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   2ggy5vl          ^g4ndl@4.6%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   3rkf55c          ^g4particlexs@4.0%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   2gh5krv          ^g4photonevaporation@5.7%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   kf6bjiu          ^g4pii@1.3%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   gwdkj3n          ^g4radioactivedecay@5.6%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   qxt6gji          ^g4realsurface@2.2%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   zimnhdf          ^g4saiddata@2.0%nvhpc@22.7 arch=linux-ubuntu20.04-icelake
 -   6hvkah3      ^xerces-c@3.2.3%nvhpc@22.7 cxxstd=17 netaccessor=curl transcoder=gnuiconv arch=linux-ubuntu20.04-icelake
```

**Comment by sethrj** [comment] 2022-08-19 11:00
Aha, I see. Curiously, though, I was using an external cmake, which concretized as:
```console
$ spack find -lvd cmake%nvhpc
==> 1 installed package
-- linux-ubuntu20.04-cascadelake / nvhpc@22.5 -------------------
yb4cuu6 cmake@3.22.1~doc+ncurses+ownlibs~qt build_type=Release
```
Perhaps also, conflicts shouldn't apply to externals since they've already been built?

**Comment by alalazo** [comment] 2022-08-19 11:11
Ugh, I didn't look at your `packages.yaml` - but I think the issue is of the same kind. Conflicts with `externals` are already not taken into account (for the good and bad, since sometimes that approach causes troubles too). 

Also, with https://github.com/spack/spack/pull/32260 you can generally ask for:
```yaml
packages:
  all:
    require: '%nvhpc'
```
which might be a more general solution if merged.

**Comment by sethrj** [comment] 2022-08-19 11:48
Yep, the `requires` option sounds like the right approach to take for environments going forward. Diffing the two concretized `specs` for nvhpc vs gcc, I get:
```
     ^clhep@2.4.5.1~ipo build_type=RelWithDebInfo cxxstd=17
         ^cmake@3.22.1~doc+ncurses+ownlibs~qt build_type=Release
     ^expat@2.4.8+libbsd
-        ^libbsd@0.11.5
-            ^libmd@1.0.4
+        ^libbsd@0.11.3
+            ^libmd@1.0.4 patches=991953c
     ^geant4-data@11.0.0
         ^g4abla@3.1
         ^g4emlow@8.0
```

The nvhpc patches/restrictions are due to @haampie in #29848 ... maybe there's an easy patch? It looks like the only problem is the hard-coded `-nostdlib -nostartfiles` options to `$(CC) -shared`...

**Comment by sethrj** [comment] 2022-09-15 15:17
@alalazo should I close this since the workaround in https://github.com/spack/spack/pull/32260 is merged, or is it possible to bump up the weight of the requested compiler in the concretizer?

**Comment by alalazo** [comment] 2022-09-20 07:29
@sethrj Let's close this for the time being. Sorry for the late answer.

**Closed as completed** 2022-09-20 09:59 UTC
Labels: bug, impact-low
