### ISSUE TITLE
Compiler flag combinations lead to silent concretization failure

### ISSUE THREAD

**Issue by psakievich** [LLNL/spack#42826] opened 2024-02-23 16:04 UTC
### Steps to reproduce

Spack has trouble combining multiple conditions on a spec's compiler flags.  In this case having a `require` direction on the package and a flag in the `spec` leads to a silent failure to concretize. The machinery is there to combine these into a single set of flags using the `FlagMap`, however the implementation is breaking down.

``` console
$ spack env activate --temp
$ spack add zlib cxxflags="-fPIC"
==> Adding zlib cxxflags="-fPIC" to environment /var/folders/ln/1_3kxbwd35s_ylsjlm3zmqmc00307v/T/spack-lh8x39li
$ spack config add packages:zlib:require:"cxxflags=-Werror"
$ spack concretize
[nothing ]
```
[Output of `spack solve`](https://github.com/spack/spack/files/14387308/solver_facts.txt)

### Information on your system

* **Spack:** 0.20.0 (62f58cb44299004e2876f6fc128ca11bae51f55c)
* **Python:** 3.10.12
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2024-02-23 16:16
Duplicate of #38664

**Comment by scheibelp** [comment] 2024-02-26 08:04
The "silent" part of this is addressed by https://github.com/spack/spack/pull/42655 so I'll close this. Feel free to reopen if you think https://github.com/spack/spack/issues/38664 does not capture the rest of this.

**Closed as completed by scheibelp** 2024-02-26 08:04 UTC
Labels: bug, triage
