### ISSUE TITLE
RISC-V Bootstrap of Clingo Fails

### ISSUE THREAD

**Issue by ktpedre** [LLNL/spack#42723] opened 2024-02-16 15:51 UTC
### Steps to reproduce

Trying to bootstrap Spack on a RISC-V Ubuntu 22.04 image, the build of clingo succeeds however bootstrap fails because the python3 import clingo check fails.

```console $ spack bootstrap now ``` 

Manually finding where clingo got installed and manually setting PYTHONPATH works around the issue. For example, if this is set before running spack bootstrap, it succeeds:

```
export PYTHONPATH=/root/.spack/bootstrap/store/linux-ubuntu22.04-riscv64/gcc-13.2.0/clingo-bootstrap-spack-z34hp2grqfz2qnvymtbnyqpo5tk5ofat/lib/python3.10/site-packages
```

### Error message

```
[+] /opt/riscv (external cmake-3.27.7-7ilybtzt43eys3wucq55soukiwcn4lud)
[+] /root/.spack/bootstrap/store/linux-ubuntu22.04-riscv64/gcc-13.2.0/gmake-4.4.1-jojivk6r7nv6hcngiwemkogudi5d3mfi
[+] /root/.spack/bootstrap/store/linux-ubuntu22.04-riscv64/gcc-13.2.0/re2c-2.2-che4uprddgtea5to3qhwzzdojoasiwny
[+] /usr (external bison-3.8.2-ad2lprmjsce65ltanbyx3j4cevvatjl6)
[+] /usr (external python-3.10.13-cbvimovp7b2bhiromakj3vz44osv3nz4)
==> Installing clingo-bootstrap-spack-z34hp2grqfz2qnvymtbnyqpo5tk5ofat [6/6]
==> No binary for clingo-bootstrap-spack-z34hp2grqfz2qnvymtbnyqpo5tk5ofat found: installing from source
==> Using cached archive: /root/spack/spack/var/spack/cache/_source-cache/git//potassco/clingo.git/2a025667090d71b2c9dce60fe924feb6bde8f667.tar.gz
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
==> Already patched clingo-bootstrap
==> clingo-bootstrap: Executing phase: 'cmake'
==> clingo-bootstrap: Executing phase: 'build'
==> clingo-bootstrap: Executing phase: 'install'
==> clingo-bootstrap: Successfully installed clingo-bootstrap-spack-z34hp2grqfz2qnvymtbnyqpo5tk5ofat
  Stage: 0.07s.  Cmake: 24.96s.  Build: 24m 31.37s.  Install: 4.63s.  Post-install: 0.97s.  Total: 25m 3.21s
[+] /root/.spack/bootstrap/store/linux-ubuntu22.04-riscv64/gcc-13.2.0/clingo-bootstrap-spack-z34hp2grqfz2qnvymtbnyqpo5tk5ofat
==> Warning: Spec clingo-bootstrap@=spack%gcc@=13.2.0~docs~force_setuptools~ipo~optimized+python~static_libstdcpp build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-riscv64 ^[deptypes=build] bison@=3.8.2%gcc@=13.2.0 build_system=autotools arch=linux-ubuntu22.04-riscv64 ^[deptypes=build] cmake@=3.27.7%gcc@=13.2.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-ubuntu22.04-riscv64 ^[deptypes=build] gmake@=4.4.1%gcc@=13.2.0~guile build_system=generic arch=linux-ubuntu22.04-riscv64 ^[deptypes=build,link,run] python@=3.10.13%gcc@=13.2.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,7d40923,ebdca64,f2fd060 arch=linux-ubuntu22.04-riscv64 ^[deptypes=build] re2c@=2.2%gcc@=13.2.0 build_system=generic arch=linux-ubuntu22.04-riscv64 did not provide module clingo
==> Error: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %gcc target=riscv64" due to the following failures:
github-actions-v0.5 raised RuntimeError: The binary index is empty
github-actions-v0.4 raised RuntimeError: The binary index is empty
Run `spack --debug ...` for more detailed errors
```

### Information on your system

```
* **Spack:** 0.21.1 (e30fedab102f9281a220fb4fae82e3f8c43a82ac)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-riscv64
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by keixthb** [comment] 2024-02-16 17:41
@ktpedre Can you run ```lscpu``` and post the results?

**Comment by ktpedre** [comment] 2024-02-17 14:56
root@ubuntu:~# lscpu
Architecture:          riscv64
  Byte Order:          Little Endian
CPU(s):                4
  On-line CPU(s) list: 0-3

**Comment by alalazo** [comment] 2024-02-19 10:11
Duplicate of #38622

**Closed as completed by alalazo** 2024-02-19 10:11 UTC
Labels: bug, triage

**Comment by alalazo** [comment] 2024-02-19 10:13
See in particular https://github.com/spack/spack/issues/38622#issuecomment-1673609001 Feel free to reopen if you think there's more than what already reported.
