### ISSUE TITLE
Installation issue: mpich

### ISSUE THREAD

**Issue by LDAmorim** [LLNL/spack#17934] opened 2020-08-07 17:51 UTC
This issue is related to https://github.com/spack/spack/issues/16913, but for macOS (clang).
And can be fixed by extending/duplicating the fix for compiler `gcc@10:` to `apple-clang@11:`.

### Steps to reproduce the issue

```console
$ spack install mpich
==> Warning: apple-clang@11.0.3 cannot build optimized binaries for "skylake". Using best target possible: "x86_64"
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/libsigsegv-2.12-cd2u6jt6oagbnhsgqal54myovfkwpri6
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/berkeley-db-18.1.40-3f4556kvgg2ihsahtuy4ta27i65hnikf
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/pkgconf-1.7.3-52kfpvjixcntquvt67sltjuajdhq73od
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/libiconv-1.16-2owd6xnxysuqdfuuu4mgemxmdhgto4px
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/xz-5.2.5-nfsvq5xchnmyvqc333p644ouuwnk7awe
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/zlib-1.2.11-7erteezzqncanvj4cr4lesgcawuztojo
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/m4-1.4.18-anoponiwofd7dqkxmcqy6iq6ildhe5s2
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/ncurses-6.2-wr2lahob7rnaawch75w2p5rce4qk3qul
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/libxml2-2.9.10-cvsddxrqg4jwdgk2xopykzztgwwypl3f
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/libtool-2.4.6-yrvttuduwubr6aebtif4ezrllojrfi7i
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/readline-8.0-mtiikfoyt34p7bvxqz3talk7xv5azul4
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/hwloc-2.2.0-ox7oz3tzcswqhmvo2urhb76oeum7ntpo
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/gdbm-1.18.1-aaqin73b6t3wbxht7pdtw3ozteqmecd2
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/perl-5.30.3-7aafes7kqahuojjmxcqtwdezuqh74ya4
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/texinfo-6.5-bpmdlwfjdbg3dynlm5hjtnhtohpcaqyy
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/autoconf-2.69-caqezswjz5nwgqaxltqjnk25qjsuszfo
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/automake-1.16.2-2ug6frtywzpnmtbh2uji4pllbcgbbeoy
[+] /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/findutils-4.6.0-2swrp2onomc2norjkbmshw5xajlxrerw
==> Installing mpich
==> No binary for mpich found: installing from source
==> Warning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check apple-clang@11.0.3 for further details]
==> mpich: Executing phase: 'autoreconf'
==> mpich: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/LDianaAmorim/spack-stage/spack-stage-mpich-3.3.2-fntycc6dcg327z5dy3sboxudvldscpxe/spack-src/configure' '--prefix=/Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/mpich-3.3.2-fntycc6dcg327z5dy3sboxudvldscpxe' '--disable-silent-rules' '--enable-shared' '--with-hwloc-prefix=/Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/hwloc-2.2.0-ox7oz3tzcswqhmvo2urhb76oeum7ntpo' '--with-pm=hydra' '--enable-romio' '--without-ibverbs' '--enable-wrapper-rpath=yes' '--with-slurm=no' '--with-pmi=simple' '--with-device=ch3:nemesis:tcp' '--enable-libxml2'

1 error found in build log:
     963    checking for shared library (esp. rpath) characteristics of F77... done (results in src/env/f77_shlib.conf)
     964    checking whether Fortran 77 accepts ! for comments... yes
     965    checking for include directory flag for Fortran... -I
     966    checking for Fortran 77 flag for library directories... -L
     967    checking whether Fortran 77 compiler processes .F files with C preprocessor... yes
     968    checking whether /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/gfortran allows mismatched arguments... no
  >> 969    configure: error: The Fortran compiler /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/gfortran will not compile files that call
     970    the same routine with arguments of different types.

See build log for details:
  /var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/LDianaAmorim/spack-stage/spack-stage-mpich-3.3.2-fntycc6dcg327z5dy3sboxudvldscpxe/spack-build-out.txt
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.15.3-421-c83236d3a
* **Python:** 3.7.3
* **Platform:** darwin-catalina-skylake
```

* clang version: 11.0.3
* gcc (gfortran) version: 10.2.0
* cmake version: 3.18.1

```console
$ cat ~/.spack/darwin/packages.yaml
packages:
  cmake:
    buildable: False
    paths:
      cmake@3.18.1: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/cmake-3.18.1-u4guucbahyuq5pswf55b2ebqslsjub7m
```

```console
$ % cat ~/.spack/darwin/compilers.yaml 
compilers:
- compiler:
    spec: apple-clang@11.0.3
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/gcc-10.2.0-phyqkhktab6nxd2noi3kklzjxsnku5le/bin/gfortran
      fc: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/gcc-10.2.0-phyqkhktab6nxd2noi3kklzjxsnku5le/bin/gfortran
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@10.2.0
    paths:
      cc: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/gcc-10.2.0-phyqkhktab6nxd2noi3kklzjxsnku5le/bin/gcc
      cxx: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/gcc-10.2.0-phyqkhktab6nxd2noi3kklzjxsnku5le/bin/g++
      f77: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/gcc-10.2.0-phyqkhktab6nxd2noi3kklzjxsnku5le/bin/gfortran
      fc: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/gcc-10.2.0-phyqkhktab6nxd2noi3kklzjxsnku5le/bin/gfortran
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

### Additional information

* [spack-build-env.txt](https://github.com/spack/spack/files/5042787/spack-build-env.txt)
* [spack-build-out.txt](https://github.com/spack/spack/files/5042788/spack-build-out.txt)
* [spack-configure-args.txt](https://github.com/spack/spack/files/5042789/spack-configure-args.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment] 2020-08-10 08:08
With https://github.com/spack/spack/pull/17964 you can avoid using Fortran compilers altogether, which can be useful if your package just uses the C or C++ interface.

**Comment by LDAmorim** [comment] 2020-08-10 15:57
Hi, Thank you for the reply!
I will try again without the fortran compilers (I actually think I did that first and got a missing `gfortran` error message, but I will double check it!).

**Comment by LDAmorim** [comment] 2020-09-03 18:52
Hi, sorry for my super late reply.
Indeed removing the fortran compilers from the clang description, allows to compile mpich (using the current *spack* repo) successfully.
So this issue can be closed, sorry for the trouble.
And thank you again for the suggestion @haampie !
Cheers,
Diana

**Comment by LDAmorim** [comment] 2020-09-08 23:56
Hi,
Sorry I ended up reopening this issue.
But I think I might need to use the fortran compilers after all, when I try to install `adios2`.
The issue I get, using the workaround of `spack install mpich~fortran` is:
```
>> 36    CMake Error at /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/cmake-3.18.
           2-hkd23wphpsyo3wminmu62gvusohcoh5n/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
     37      Could NOT find MPI (missing: MPI_Fortran_FOUND Fortran) (found version
     38      "3.1")
```
Is there any alternative or way to fix this `mpich` issue?

I attach here the files of the spack build error in case they help.

[spack-build-env.txt](https://github.com/spack/spack/files/5191796/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/5191797/spack-build-out.txt)
[spack-configure-args.txt](https://github.com/spack/spack/files/5191798/spack-configure-args.txt)

Thanks,
Diana

**Comment by scheibelp** [comment] 2020-09-09 01:11
I'm not sure how to quickly modify Spack to add `-fallow-argument-mismatch` to `FFLAGS` for a hybrid compiler identifying as Clang other than the method mentioned in the PR description. I don't think this would be good long-term though, since the need is based on the Fortran compiler vs. what the compiler identifies as. 

We plan to add compilers as dependencies, which will include finer-grained language support and I think that would support this naturally.

Perhaps an interim fix that would be more robust is to duplicate the logic used to detect compiler versions in the MPICH package, so that we can run the provided Fortran compiler, get the version/type, and then set `-fallow-argument-mismatch` accordingly.

**Comment by LDAmorim** [comment] 2020-09-09 02:52
Hi @scheibelp ! Thank you for your reply.
I think your last suggestion makes a lot of sense to me.
I will try to use the changes you might make (sorry, I am probably not gonna be able to implement anything on my own quickly) and test it and let you know how it goes.

**Comment by haampie** [comment] 2020-09-15 07:18
@scheibelp I'm not sure how your comment is related to the above issue, but I might be missing something.

@LDAmorim: If your package is using `find_package(MPI REQUIRED)`, it should just work as long as Fortran is not enabled as a language, and it does not explicitly list Fortran in the components. See https://github.com/Kitware/CMake/blob/master/Modules/FindMPI.cmake#L1400-L1414. Otherwise something odd is going on, in which case it should be fixable in the cmake scripts of adios2

**Comment by scheibelp** [comment] 2020-09-15 07:24
> @scheibelp I'm not sure how your comment is related to the above issue, but I might be missing something.

The issue description (https://github.com/spack/spack/issues/17934#issue-675174917) refers to https://github.com/spack/spack/issues/16913 which is fixed by adding `-fallow-argument-mismatch` and mentions that the same solution works here.

The problem is deciding when to add `-fallow-argument-mismatch`: we know it works here but Spack doesn't provide a good mechanism for deciding when to do this with hybrid compilers. So I suggested copying some of the version detection logic to get the version from the fortran compiler executable.

Does that provide better context or does my suggestion still seem out-of-place?

**Comment by haampie** [comment] 2020-09-15 08:08
Ah ok, but @LDAmorim is using clang for everything, not GCC 10 (from the logs).

In that case it should be fine if you just don't use Fortran compilers, and glancing over the cmakelists.txt of adios2, they only enable Fortran as a language when you request that explicitly. So `spack install adios2 %clang ~fortran ^mpich ~fortran` should be OK I guess.

**Comment by LDAmorim** [comment] 2020-09-15 15:06
Thanks @scheibelp and @haampie !
It does work when I remove `fortran`.
Sorry for the confusion.

**Closed as completed** 2020-10-21 17:34 UTC
Labels: build-error
