### ISSUE TITLE
n v0.23 "github-actions-v0.4" is not used by default but why do I have this error while creating a bootstrap mirror

### ISSUE THREAD

**Issue by BolarinwaSaheed** [LLNL/spack#48234] opened 2024-12-20 10:59 UTC
### Steps to reproduce

```console
$> spack bootstrap mirror --binary-packages /dev_sw/sys/spack/bootstrap

```

### Error message

```==> Adding "clingo-bootstrap@spack+python %gcc platform=linux target=x86_64" and dependencies to the mirror at /dev_sw/sys/spack/bootstrap/bootstrap_cache
==> Warning: duplicate found for gcc@=7.5.0 on sles15/x86_64. Edit your compilers.yaml configuration to remove it.
==> Warning: Using download cache instead of version control
  The required sources are normally checked out from a version control system, but have been archived in download cache: file:///dev_sw/sys/spack/cache/_source-cache/git//potassco/clingo.git/2a025667090d71b2c9dce60fe924feb6bde8f667.tar.gz. Spack lacks a tree hash to verify the integrity of this archive. Make sure your download cache is in a secure location.
==> Adding "gnupg@2.3: %gcc platform=linux target=x86_64" and dependencies to the mirror at /dev_sw/sys/spack/bootstrap/bootstrap_cache
==> Warning: duplicate found for gcc@=7.5.0 on sles15/x86_64. Edit your compilers.yaml configuration to remove it.
==> Adding "patchelf@0.13.1: %gcc platform=linux target=x86_64" and dependencies to the mirror at /dev_sw/sys/spack/bootstrap/bootstrap_cache
==> Warning: duplicate found for gcc@=7.5.0 on sles15/x86_64. Edit your compilers.yaml configuration to remove it.
==> Adding "file %gcc platform=linux target=x86_64" and dependencies to the mirror at /dev_sw/sys/spack/bootstrap/bootstrap_cache
==> Warning: duplicate found for gcc@=7.5.0 on sles15/x86_64. Edit your compilers.yaml configuration to remove it.
==> Adding "gnuconfig" and dependencies to the mirror at /dev_sw/sys/spack/bootstrap/bootstrap_cache
==> Warning: duplicate found for gcc@=7.5.0 on sles15/x86_64. Edit your compilers.yaml configuration to remove it.
==> Adding binary packages from "https://github.com/spack/spack-bootstrap-mirrors/releases/download/v0.4/bootstrap-buildcache.tar.gz" to the mirror at /dev_sw/sys/spack/bootstrap/bootstrap_cache
==> Error: [Errno 2] No such file or directory: '/dev_sw/spack/share/spack/bootstrap/github-actions-v0.4/clingo.json'
```

### Information on your system

> spack debug report 
* **Spack:** 0.23.0 (c6d4037758140fe15913c29e80cd1547f388ae51)
* **Python:** 3.6.15
* **Platform:** linux-sles15-icelake

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2024-12-24 10:21
Duplicate of #47827

**Closed as completed** 2024-12-27 00:41 UTC
Labels: bug, duplicate
