### ISSUE TITLE
Installation issue: intel-oneapi-compilers

### ISSUE THREAD

**Issue by ciaron** [LLNL/spack#23394] opened 2021-05-03 11:41 UTC
### Steps to reproduce the issue

```console
$ spack install intel-oneapi-compilers
[+] /p/system/packages/spack/opt/spack/linux-sles12-haswell/gcc-10.2.0/patchelf-0.10-uvuvmm3bmhijhrohulbi4v2ekhsadmab
==> Installing intel-oneapi-compilers-2021.1-3mm776c7ro425u262sbxpaykibawcmjg
==> No binary for intel-oneapi-compilers-2021.1-3mm776c7ro425u262sbxpaykibawcmjg found: installing from source
==> Fetching https://registrationcenter-download.intel.com/akdlm/irc_nas/17427/l_HPCKit_p_2021.1.2684_offline.sh
######################################################################## 100.0%
==> Warning: The contents of the archive look like HTML.  Either the URL you are trying to use does not exist or you have an internet gateway issue.  You can remove the bad archive using 'spack clean <package>', then try again using the correct URL.
==> Error: ChecksumError: sha256 checksum failed for /tmp/linstead/spack-stage/spack-stage-intel-oneapi-compilers-2021.1-3mm776c7ro425u262sbxpaykibawcmjg/l_HPCKit_p_2021.1.2684_offline.sh
    Expected 666b1002de3eab4b6f3770c42bcf708743ac74efeba4c05b0834095ef27a11b9 but got 114cf566ea583b8a5e9367b180e969bfd1e0194f772d3f373c597d082b4f8388

/p/system/packages/spack/lib/spack/spack/package.py:1335, in do_fetch:
       1332        self.stage.fetch(mirror_only, err_msg=err_msg)
       1333        self._fetch_time = time.time() - start_time
       1334
  >>   1335        if checksum and self.version in self.versions:
       1336            self.stage.check()
       1337
       1338        self.stage.cache_local()
```

Download URL is indeed a 404, also when logged in to my Intel account. The correct URL seems to be very slightly different:

https://registrationcenter-download.intel.com/akdlm/irc_nas/17427/l_HPCKit_p_2021.1.0.2684_offline.sh

(note extra "0." in the URL)

### Information on your system

```console
$ spack debug report
* **Spack:** 0.16.1-2-393a105c06
* **Python:** 3.6.2
* **Platform:** linux-sles12-haswell
```

### Additional information

* [spack-build-out.txt]() - not generated
* [spack-build-env.txt]() - not generated

 @rscohn2 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files (not generated in my case)
- [x] I have searched the issues of this repo and believe this is not a duplicate

Thanks!

**Comment by rscohn2** [comment] 2021-05-03 12:21
It looks like they renamed a file on the server. They don't usually do that and I will ask them to make both old and new URL's work.

I see that you are using the latest release, which is from February. Would it be possible to switch to the develop branch, as I believe it is working there.

**Comment by ciaron** [comment] 2021-05-03 13:15
Thanks Robert! 

I tried `develop`, but I get a different error:
```console
==> Error: There are no valid versions for intel-oneapi-compilers that match ':'
```

(I just did `git checkout develop` on my Spack installation - is this the right way to switch?)

**Comment by rscohn2** [comment] 2021-05-03 13:45
After the checkout, it would be better to do a:
```
git pull
```
To update the develop to the latest.

I am not sure if it is ok to switch branches when you have installed packages. Can you try a new clone and install?

**Comment by ciaron** [comment] 2021-05-03 16:00
Can confirm it works from a clean `develop` branch.

**Comment by rscohn2** [comment] 2021-05-03 18:56
@ciaron: Thanks for checking.

It turns out that the URL never worked. We were still getting everything working at the time they did the Feb release. This means 0.16 is unusable for people who want to install oneapi.

@scheibelp : FYI

**Comment by ciaron** [comment] 2021-05-04 08:59
@rscohn2 thanks for the update. It looks like the URL for `intel-parallel-studio@cluster.2020.4` is also broken in releases/v0.16. We're just trying out Spack for now, so none of this is urgent (for us at least).

**Comment by rscohn2** [comment] 2021-05-04 12:57
It doesn't look like 0.16 had support for 2020.4:
https://github.com/spack/spack/blob/8dd2d740b1fbd4335209240fcc42826d0a143f57/var/spack/repos/builtin/packages/intel-parallel-studio/package.py#L23
Was it a different PSXE update that had a bad URL?

**Comment by ciaron** [comment] 2021-05-04 14:46
You're right - my apologies. I was seeing the version numbers in `develop` and trying to install with `release`.

**Comment by rscohn2** [comment] 2021-05-28 03:17
@tldahlgren : I suggest this issue be closed. The intel-oneapi-compilers package in the 0.16 release of Spack is broken. Develop is working so there is not much we can do about it.

**Comment by kma** [comment] 2021-06-03 17:01
Hi,
I had the same problem. I just edited the package with the right version.
`spack edit intel-oneapi-compilers`

Modify version from 2021.1 to 2021.1.0  in release and version line.

Don't forget to modify sha too.

**EDIT**
Spack install exit without errors, but the installed folder is empty.

Checking logs:
`ERROR : Cannot change installation directory to 'intel-oneapi-compilers-2021.1.0-wqztavrstatoakd3ej2ly7ag636gwyku', because it is locked to 'intel-oneapi-mpi-2021.1.1-x5z72j52tf5k247luvsd2tlnrvxey3dn'`

best

**Comment by rscohn2** [comment] 2021-06-04 18:27
@kma Are you trying to install as root?
If so, you need to do this after every package is installed:
sudo rm -r /var/intel/installercache
There is some more background here: https://github.com/spack/spack/issues/23388#issuecomment-831285732

The locked installation directory and the bad URL are both fixed in the develop branch. If you are unable to use the workarounds, I could provide a patched 0.16 release under my personal account.

**Comment by samcom12** [comment] 2021-06-14 11:32
I'm getting same error with the `develop `branch

`==> Error: There are no valid versions for intel-oneapi-compilers that match ':'`

Following for resolution.

**Comment by rscohn2** [comment] 2021-06-14 11:35
Please show full command line and output.

**Comment by kma** [comment] 2021-06-14 11:55
@samcom12 which version of python are you using? use `spack debug report `command
I get the same error when using 2.6 version. Try upgrade to 3.x version.
Best.

**Comment by samcom12** [comment] 2021-06-14 12:02
After mentioning version number from `package.py`, getting below error-

`==> Error: Can't extrapolate a URL for version 2021.2.0 because package intel-oneapi-compilers defines no URLs`

spack --version
`0.16.2-3116-0d73fd2`

**Comment by samcom12** [comment] 2021-06-14 12:21
> @samcom12 which version of python are you using? use `spack debug report `command
> I get the same error when using 2.6 version. Try upgrade to 3.x version.
> Best.


Command-

**spack install intel-oneapi-compilers@2021.2.0**
```
==> Warning: Missing a source id for intel-oneapi-compilers@2021.2.0
==> Installing patchelf-0.12-c62fg6eh6o6wuva54cenrxk26zpdypfz
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for patchelf-0.12-c62fg6eh6o6wuva54cenrxk26zpdypfz found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/69/699a31cf52211cf5ad6e35a8801eb637bc7f3c43117140426400d67b7babd792.tar.bz2
######################################################################## 100.0%
==> Fetching https://mirror.spack.io/_source-cache/archive/a1/a155f233b228f02d7886e304cb13898d93801b52f351e098c2cc0719697ec9d0
######################################################################## 100.0%
==> Applied patch https://github.com/NixOS/patchelf/pull/230.patch
==> patchelf: Executing phase: 'autoreconf'
==> patchelf: Executing phase: 'configure'
==> patchelf: Executing phase: 'build'
==> patchelf: Executing phase: 'install'
==> patchelf: Successfully installed patchelf-0.12-c62fg6eh6o6wuva54cenrxk26zpdypfz
  Fetch: 4.09s.  Build: 1m 24.12s.  Total: 1m 28.21s.
[+] /home/apps/spack/opt/spack/linux-centos7-skylake_avx512/gcc-11.1.0/patchelf-0.12-c62fg6eh6o6wuva54cenrxk26zpdypfz
==> Error: Can't extrapolate a URL for version 2021.2.0 because package intel-oneapi-compilers defines no URLs

```

`spack debug report
`
![image](https://user-images.githubusercontent.com/13285627/121891368-fa87d280-cd38-11eb-86d9-b1ece388c237.png)


Not sure why spack is taking python-2.7.5 even Python 3.9.5 is there in env.

**Comment by rscohn2** [comment] 2021-06-14 12:32
Try setting:
```
export SPACK_PYTHON=python3
```

I have reproduced the problem with python2 and will fix it. Thanks @kma for pointing that out.

**Comment by samcom12** [comment] 2021-06-14 14:37
That worked for me. Thanks @rscohn2 and @kma

**Closed as completed** 2021-06-14 17:47 UTC
Labels: build-error
