### ISSUE TITLE
Spack ignores compiler concretization preference

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#4201] opened 2017-05-10 19:28 UTC
I am using this `packages.yaml` file in `~/.spack/packages.yaml`:

```
packages:
  all:
    providers:
      blas: [openblas]
      lapack: [openblas]
      mpi: [openmpi]
  bison:
    compiler: [clang@8.1.0-apple]
  cmake:
    compiler: [clang@8.1.0-apple]
  gettext:
    compiler: [clang@8.1.0-apple]
  py_matplotlib:
    compiler: [clang@8.1.0-apple]
  pkg_config:
    compiler: [clang@8.1.0-apple]
  python:
    compiler: [clang@8.1.0-apple]
```

Yet when I install a package that depends on Python, and when this package is built with `gcc`, Spack wants to build Python with `gcc` as well. This is contrary to the documentation at `http://spack.readthedocs.io/en/latest/build_settings.html#concretization-preferences`.

**Comment by adamjstewart** [comment] 2017-05-10 19:30
Duplicate of #1371. I feel like we keep discovering the same bugs 😆

**Closed by adamjstewart** 2017-05-10 19:30 UTC

**Comment by alalazo** [comment] 2017-05-10 20:54
Do we have a know issue on this? #1371 seems from a while ago.
