### ISSUE TITLE
Installation issue: meson 1.1.0 binary goes into local/bin/ instead of bin/ and dependent builds fail

### ISSUE THREAD

**Issue by tkoskela** [LLNL/spack#37632] opened 2023-05-12 10:41 UTC
### Steps to reproduce the issue

```console
$ spack spec -l meson@1.1.0%gcc@11.3.0
Input spec
--------------------------------
meson@1.1.0%gcc@11.3.0

Concretized
--------------------------------
e4wcp5f  meson@=1.1.0%gcc@=11.3.0 build_system=python_pip patches=0f0b1bd arch=linux-ubuntu22.04-icelake
ns3le63      ^ninja@=1.11.1%gcc@=11.3.0+re2c build_system=generic arch=linux-ubuntu22.04-icelake
enxpqa5          ^re2c@=2.2%gcc@=11.3.0 build_system=generic arch=linux-ubuntu22.04-icelake
jpvgnx6      ^py-pip@=23.0%gcc@=11.3.0 build_system=generic arch=linux-ubuntu22.04-icelake
3khwqua      ^py-setuptools@=67.6.0%gcc@=11.3.0 build_system=generic arch=linux-ubuntu22.04-icelake
cemqzwn      ^py-wheel@=0.37.1%gcc@=11.3.0 build_system=generic arch=linux-ubuntu22.04-icelake
qy37l67      ^python@=3.10.6%gcc@=11.3.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma+nis~optimizations+pic+pyexpat~pythoncmd+readline+shared+sqlite3+ssl+tix+tkinter+uuid+zlib build_system=generic patches=0d98e93,f2fd060 arch=linux-ubuntu22.04-icelake

```

### Error message

<details><summary>Error message</summary>

<pre>
==> Installing glib-2.76.1-ymrolapjhbf5mqwo3bwhsuy4n7nfhjt3
==> No binary for glib-2.76.1-ymrolapjhbf5mqwo3bwhsuy4n7nfhjt3 found: installing from source
==> Using cached archive: /home/tkoskela/git_repos/spack/var/spack/cache/_source-cache/archive/43/43dc0f6a126958f5b454136c4398eab420249c16171a769784486e25f2fda19f.tar.xz
==> Using cached archive: /home/tkoskela/git_repos/spack/var/spack/cache/_source-cache/archive/fa/fa31180b55a832cbb75cc640bb115b7b092a26d7bcf0f48768de55576f0a38d3
==> Applied patch https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3368.diff
==> Ran patch() for glib
==> glib: Executing phase: 'install'
==> Error: ProcessError: /home/tkoskela/git_repos/spack/opt/spack/linux-ubuntu22.04-icelake/gcc-11.3.0/meson-1.1.0-e4wcp5ftc2czlsqyt4urzgq62uac6i4j/bin/meson: No such file or directory
</pre></details>

*Here's the outcome of `spack install meson@1.1.0%gcc@11.3.0`
```
spack install meson@1.1.0%gcc@11.3.0
[+] /home/tkoskela/git_repos/spack/opt/spack/linux-ubuntu22.04-icelake/gcc-11.3.0/ninja-1.11.1-ns3le63pyfm25lszoawoqpva7kbm6c27
[+] /usr (external python-3.10.6-qy37l67wses7cwy4owuka3bsw2q6x4rf)
[+] /home/tkoskela/git_repos/spack/opt/spack/linux-ubuntu22.04-icelake/gcc-11.3.0/py-wheel-0.37.1-cemqzwniwrpmkpq67nulscmgbh5ztrq2
[+] /home/tkoskela/git_repos/spack/opt/spack/linux-ubuntu22.04-icelake/gcc-11.3.0/py-pip-23.0-jpvgnx6dt2lfywrrnepdxmnysf34y7ad
[+] /home/tkoskela/git_repos/spack/opt/spack/linux-ubuntu22.04-icelake/gcc-11.3.0/py-setuptools-67.6.0-3khwquabnxhqjdf6ndqttqlovgcdvkuj
==> Installing meson-1.1.0-e4wcp5ftc2czlsqyt4urzgq62uac6i4j
==> No binary for meson-1.1.0-e4wcp5ftc2czlsqyt4urzgq62uac6i4j found: installing from source
==> Using cached archive: /home/tkoskela/git_repos/spack/var/spack/cache/_source-cache/archive/f2/f29a3e14062043d75e82d16f1e41856e6b1ed7a7c016e10c7b13afa7ee6364cc.tar.gz
==> Applied patch /home/tkoskela/git_repos/spack/var/spack/repos/builtin/packages/meson/rpath-0.64.patch
==> meson: Executing phase: 'install'
==> meson: Successfully installed meson-1.1.0-e4wcp5ftc2czlsqyt4urzgq62uac6i4j
  Stage: 0.13s.  Install: 1.35s.  Post-install: 0.04s.  Total: 1.53s
[+] /home/tkoskela/git_repos/spack/opt/spack/linux-ubuntu22.04-icelake/gcc-11.3.0/meson-1.1.0-e4wcp5ftc2czlsqyt4urzgq62uac6i4j

$ ls /home/tkoskela/git_repos/spack/opt/spack/linux-ubuntu22.04-icelake/gcc-11.3.0/meson-1.1.0-e4wcp5ftc2czlsqyt4urzgq62uac6i4j
local

$ ls /home/tkoskela/git_repos/spack/opt/spack/linux-ubuntu22.04-icelake/gcc-11.3.0/meson-1.1.0-e4wcp5ftc2czlsqyt4urzgq62uac6i4j/local/
bin  lib  share

$ ls /home/tkoskela/git_repos/spack/opt/spack/linux-ubuntu22.04-icelake/gcc-11.3.0/meson-1.1.0-e4wcp5ftc2czlsqyt4urzgq62uac6i4j/local/bin/
meson
```

### Information on your system

* **Spack:** 0.20.0.dev0 (ebfc706c8c6e16455a9e6f476a48d0f0489a8aec)
* **Python:** 3.10.6
* **Platform:** linux-ubuntu22.04-icelake
* **Concretizer:** clingo

### Additional information

Mentioning the maintainers @adamjstewart @eli-schwartz @michaelkuhn @pradyunsg

[spack-build-env.txt](https://github.com/spack/spack/files/11462839/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/11462840/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by eli-schwartz** [comment] 2023-05-12 12:57
This sounds like some aspect of Ubuntu's patched python / setuptools is leaking its effects into spack. IIRC there's a Ubuntu-python patch (really a debian one) that adds a special config file to setuptools -- that config file causes setuptools to prefer /usr/local, and hopefully should not affect alternative --prefix etc. but may be doing so anyway?

**Comment by adamjstewart** [comment] 2023-05-12 15:18
Duplicate of:

* https://github.com/pypa/pip/issues/10978
* https://github.com/spack/spack/pull/31939
* https://github.com/spack/spack/issues/32662
* https://github.com/spack/spack/issues/32769

Let's close this issue on discuss further on one of those issues. I don't envision a great solution on Spack's side, I'm hoping we can convince Debian/RHEL to fix this themselves.

**Closed as completed by adamjstewart** 2023-05-12 15:18 UTC
Labels: build-error
