### ISSUE TITLE
Amrex fails to build with Intel

### ISSUE THREAD

**Issue by certik** [LLNL/spack#5791] opened 2017-10-17 17:56 UTC
```
$ cat ~/.spack/packages.yaml 
packages:
  openmpi:
    version: [2.1.1]
```
and
```
$ spack spec amrex%intel@17.0.1
Input spec
--------------------------------
amrex%intel@17.0.1

Normalized
--------------------------------
amrex%intel@17.0.1
    ^cmake

Concretized
--------------------------------
amrex@17.06%intel@17.0.1 build_type=RelWithDebInfo ~debug dims=3 +fortran+mpi~openmp~particles prec=DOUBLE arch=linux-fedora25-x86_64 
    ^cmake@3.9.4%intel@17.0.1~doc+ncurses+openssl+ownlibs~qt arch=linux-fedora25-x86_64 
        ^ncurses@6.0%intel@17.0.1 patches=f84b2708a42777aadcc7f502a261afe10ca5646a51c1ef8b5e60d2070d926b57 ~symlinks arch=linux-fedora25-x86_64 
            ^pkg-config@0.29.2%intel@17.0.1+internal_glib arch=linux-fedora25-x86_64 
        ^openssl@1.0.2k%intel@17.0.1 arch=linux-fedora25-x86_64 
            ^zlib@1.2.11%intel@17.0.1+pic+shared arch=linux-fedora25-x86_64 
    ^openmpi@2.1.1%intel@17.0.1~cuda fabrics= ~java schedulers= ~sqlite3~thread_multiple+vt arch=linux-fedora25-x86_64 
        ^hwloc@1.11.7%intel@17.0.1~cuda+libxml2+pci arch=linux-fedora25-x86_64 
            ^libpciaccess@0.13.5%intel@17.0.1 arch=linux-fedora25-x86_64 
                ^libtool@2.4.6%intel@17.0.1 arch=linux-fedora25-x86_64 
                    ^m4@1.4.18%intel@17.0.1 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00 +sigsegv arch=linux-fedora25-x86_64 
                        ^libsigsegv@2.11%intel@17.0.1 arch=linux-fedora25-x86_64 
                ^util-macros@1.19.1%intel@17.0.1 arch=linux-fedora25-x86_64 
            ^libxml2@2.9.4%intel@17.0.1~python arch=linux-fedora25-x86_64 
                ^xz@5.2.3%intel@17.0.1 arch=linux-fedora25-x86_64 
```
and
```
$ spack install amrex%intel@17.0.1
...
     258   [ 27%] Building CXX object Src/Base/CMakeFiles/box_c.dir/AMReX_BaseFab.cpp.o
     259   cd /tmp/certik/spack-stage/spack-stage-Psow07/amrex/spack-build/Src/Base && /home/certik/repos/spack/opt/spack/linux-fedora25-x86_64/intel-17.0.1/openmpi-2.1.1-u2jgcqpr5pyxnqnotrpjyrg53ypfzvki/bin/mpic++  -DBL_FORT_USE_UNDERSCORE -DBL_Linux -DBL_NOLINEVALUES -DBL_PARALLEL_IO -DBL_SPACEDIM=3 -DBL_USE_DOUBLE -DBL_USE_MPI -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Base -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Boundary -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Particle -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Amr -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/AmrCore -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/LinearSolvers/C_CellMG -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/LinearSolvers/C_TensorMG -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/LinearSolvers/C_to_F_MG -I/home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Extern/amrdata -I/home/certik/repos/spack/opt/spack/linux-fedora25-x86_64/intel-17.0.1/openmpi-2.1.1-u2jgcqpr5pyxnqnotrpjyrg53ypfzvki/include  -DBL_USE_FORTRAN_MPI=1 -DBL_USE_F_BASELIB=1 -std=c++11 -O2 -g -DNDEBUG -fPIC   -o CMakeFiles/box_c.dir/AMReX_BaseFab.cpp.o -c /home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Base/AMReX_BaseFab.cpp
  >> 260   /home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Base/AMReX_parmparse_mod.F90(240): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: , :: : )
     261          call amrex_abort("amrex_parmparse: get_intarr failed to get "
     262   --------------------------------------------------------------------^
  >> 263   /home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Base/AMReX_parmparse_mod.F90(255): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: , :: : )
     264          call amrex_abort("amrex_parmparse: get_realarr failed to get "
     265   ---------------------------------------------------------------------^
  >> 266   /home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/Src/Base/AMReX_parmparse_mod.F90(275): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: , :: : )
     267          call amrex_abort("amrex_parmparse: get_stringarr failed to get "
     268   -----------------------------------------------------------------------^
     269   compilation aborted for /tmp/certik/spack-stage/spack-stage-Psow07/amrex/spack-build/Src/Base/AMReX_parmparse_mod.F90.f90 (code 1)
  >> 270   Src/Base/CMakeFiles/box_c.dir/build.make:1297: recipe for target 'Src/Base/CMakeFiles/box_c.dir/AMReX_parmparse_mod.F90.f90.o' failed
  >> 271   make[2]: *** [Src/Base/CMakeFiles/box_c.dir/AMReX_parmparse_mod.F90.f90.o] Error 1
     272   make[2]: *** Waiting for unfinished jobs....
     273   make[2]: Leaving directory '/tmp/certik/spack-stage/spack-stage-Psow07/amrex/spack-build'
  >> 274   CMakeFiles/Makefile2:262: recipe for target 'Src/Base/CMakeFiles/box_c.dir/all' failed
  >> 275   make[1]: *** [Src/Base/CMakeFiles/box_c.dir/all] Error 2
     276   make[1]: *** Waiting for unfinished jobs....
     277   make[2]: Leaving directory '/tmp/certik/spack-stage/spack-stage-Psow07/amrex/spack-build'
     278   [ 27%] Built target box_cmg
     279   make[2]: Leaving directory '/tmp/certik/spack-stage/spack-stage-Psow07/amrex/spack-build'
     280   [ 27%] Built target box_camrcore
     281   make[2]: Leaving directory '/tmp/certik/spack-stage/spack-stage-Psow07/amrex/spack-build'
     282   [ 27%] Built target box_ctmg
     283   make[1]: Leaving directory '/tmp/certik/spack-stage/spack-stage-Psow07/amrex/spack-build'
     284   Makefile:143: recipe for target 'all' failed
  >> 285   make: *** [all] Error 2

See build log for details:
  /home/certik/repos/spack/var/spack/stage/amrex-17.06-rdlvzfchr65ypvfj2k3lbghbpuy3x7uu/amrex/spack-build.out
```

**Comment by scheibelp** [comment] 2017-11-01 00:58
This appears to be a duplicate of https://github.com/LLNL/spack/issues/5812. Feel free to reopen if I missed something here.

**Closed by scheibelp** 2017-11-01 00:58 UTC
