### ISSUE TITLE
Spack complains "matches multiple specs in the environment"

### ISSUE THREAD

**Issue by jrobcary** [LLNL/spack#28168] opened 2021-12-28 19:17 UTC
### Steps to reproduce

```
export SPACK_SKIP_MODULES=1
# Don't use system or user configurations
export SPACK_DISABLE_LOCAL_CONFIG=true
export SPACK_USER_CACHE_PATH=/tmp/spack
source ./spack/share/spack/setup-env.sh
spack env activate -d vsimall
spack --debug install trilinos@develop+cuda+hdf5~mpi+openmp cuda_arch=72 ^python~pyexpat ^kokkos-nvcc-wrapper~mpi 2>&1 | tee spackdebug.txt
```
env file:
[spackyaml.txt](https://github.com/spack/spack/files/7786080/spackyaml.txt)
[spackdebug.txt](https://github.com/spack/spack/files/7786086/spackdebug.txt)

### Information on your system

```
$ spack debug report
* **Spack:** 0.17.1-661-e028ee0d59
* **Python:** 3.6.8
* **Platform:** linux-rocky8-zen2
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by jrobcary** [comment] 2021-12-29 02:29
I blew everything away, started over, and trilinos configures now.  Still does not build.

**Comment by adamjstewart** [comment] 2021-12-29 03:58
Can you upload the `spack-build-out.txt` and `spack-build-env.txt` from the failed build? @keitat @kuberry @sethrj help maintain our trilinos package so they may be able to help with any build issues.

**Comment by sethrj** [comment] 2021-12-29 11:44
@jrobcary It sounds like you're describing two separate issues. The first error in the outputs you posted are:
```
SpackEnvironmentError: trilinos@develop+cuda+hdf5~mpi+openmp cuda_arch=72 ^kokkos-nvcc-wrapper~mpi ^python~pyexpat matches multiple specs in the environment /home/research/cary/projects/txcspack/vsimall: 
Root spec trilinos@develop+cuda+hdf5~mpi+openmp cuda_arch=72 ^kokkos-nvcc-wrapper~mpi ^python~pyexpat
  swgidvl  trilinos@develop%gcc@9.4.0~adios2+amesos+amesos2+anasazi+aztec~basker+belos~boost~chaco~complex+cuda~cuda_rdc~debug~dtk+epetra+epetraext~epetraextbtf~epetraextexperimental~epetraextgraphreorderings~exodus+explicit_template_instantiation~float+fortran~gtest+hdf5~hypre+ifpack+ifpack2~intrepid~intrepid2~ipo~isorropia+kokkos~mesquite~minitensor+ml~mpi+muelu~mumps~nox+openmp~phalanx~piro~python~rol~rythmos+sacado~scorec~shards+shared~shylu~stk~stokhos~stratimikos~strumpack~suite-sparse~superlu~superlu-dist~teko~tempus+tpetra~trilinoscouplings+wrapper~x11~zoltan~zoltan2 build_type=RelWithDebInfo cuda_arch=72 cxxstd=14 gotype=long_long arch=linux-rocky8-zen2
Root spec trilinos@develop+cuda+hdf5~mpi+openmp cuda_arch=72,80 ^kokkos-nvcc-wrapper~mpi ^python~pyexpat
  lumiaqz  trilinos@develop%gcc@9.4.0~adios2+amesos+amesos2+anasazi+aztec~basker+belos~boost~chaco~complex+cuda~cuda_rdc~debug~dtk+epetra+epetraext~epetraextbtf~epetraextexperimental~epetraextgraphreorderings~exodus+explicit_template_instantiation~float+fortran~gtest+hdf5~hypre+ifpack+ifpack2~intrepid~intrepid2~ipo~isorropia+kokkos~mesquite~minitensor+ml~mpi+muelu~mumps~nox+openmp~phalanx~piro~python~rol~rythmos+sacado~scorec~shards+shared~shylu~stk~stokhos~stratimikos~strumpack~suite-sparse~superlu~superlu-dist~teko~tempus+tpetra~trilinoscouplings+wrapper~x11~zoltan~zoltan2 build_type=RelWithDebInfo cuda_arch=72,80 cxxstd=14 gotype=long_long arch=linux-rocky8-zen2
```
which look like you've created an environment with different version of trilinos: you'd need to post that file for us to debug. One thing that stands out are it reports two different values of `cuda_arch` for the two different concretizations.

The build error is a separate issue (because it means you were able to successfully concretize) and you will need to post the out/error for trilinos. If you can't reproduce the environment failure issue, please close this issue as resolved and make a new issue for the trilinos build failures with all the required context, or update the description in this issue.

**Comment by jrobcary** [comment] 2021-12-29 13:05
I found that the nuclear fix worked.  Blow away the spack clone and start over.  
I'll post something on the trilinos build.

**Closed as completed** 2021-12-29 13:06 UTC
Labels: bug, triage

**Comment by jrobcary** [comment] 2021-12-29 13:36
I have a nice repeatable approach to this and can post if you like along with any desired files.  All saved.  Or I can start a new report.  LMK what you would like.

**Comment by sethrj** [comment] 2021-12-29 13:41
@jrobcary By "this" do you mean the "matches multiple specs" error or the trilinos failure? If the latter, please open a new report and tag me. Thanks!

**Comment by jrobcary** [comment] 2021-12-29 13:45
I have a repeatable approach to both.  I can avoid the "matches multiple specs" error by invoking the nuclear option and starting over with only one cuda arch.
When I do that, it fails to build.  I will write up what I know about the latter in an bug report and tag you.  Thx.

**Comment by jrobcary** [comment] 2021-12-29 14:04
I opened #28175.  I do not see how to tag you.
