### ISSUE TITLE
spack spec fails due to unsatisfiable dependency

### ISSUE THREAD

**Issue by healther** [LLNL/spack#5748] opened 2017-10-13 07:29 UTC
Trying to use #5716 I ran into the problem of getting a concretisation error of one of our internal packages. I also tried it with ```db149876a42ec4cc8db9e488d90d71c7d811a7a6``` where it also fails. So the reason isn't in #5716, although I know that it worked at some point in August.

This is the error message:
```
Concretized
--------------------------------
==> Error: An unsatisfiable variant constraint has been detected for spec:

    pcre@8.40%gcc@4.9.2~jit+utf arch=linux-debian8-x86_64 


while trying to concretize the partial spec:

    git@2.14.1%gcc@4.9.2 arch=linux-debian8-x86_64 


git requires pcre variant +jit, but spec asked for ~jit
```

It fails with current ```develop``` (Time to fail: ~1:30), but doesn't fail when setting the defaults of ```pcre``` to ```+jit```. (Time to complete: ~2:40)
Checking out ```db149876a42ec4cc8db9e488d90d71c7d811a7a6``` (the last commit before the merge) also fails (Time to complete: ~4:50)

will add some strange example code in a couple of minutes

**Comment by davydden** [comment] 2017-10-13 07:31
>  I know that it worked at some point in August.

`git bisect`

is your friend to find out which commit broke it.

**Comment by alalazo** [comment] 2017-10-13 07:32
Does Spack feel already full or is there a typo in the title?

**Comment by healther** [comment] 2017-10-13 07:40
Adding an example package:
```
from spack import *


class Example(Package):
    """FIXME: Put a proper description of your package here."""

    # FIXME: Add a proper url for your package's homepage here.
    homepage = "http://www.example.com"
    url      = "http://www.example.com/example-1.2.3.tar.gz"

    # FIXME: Add proper versions and checksums here.
    version('1.2.3', '0123456789abcdef0123456789abcdef')

    # FIXME: Add dependencies if required.
    depends_on('gettext')
    depends_on('git')
    depends_on('swig')

    def install(self, spec, prefix):
        # FIXME: Unknown build system
        make()
        make('install')
```

and doing ```spack spec example``` results in:
```
Concretized
--------------------------------
==> Error: An unsatisfiable variant constraint has been detected for spec:

    pcre@8.40%clang@9.0.0-apple~jit+utf arch=darwin-highsierra-x86_64 


while trying to concretize the partial spec:

    git@2.14.1%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
        ^autoconf@2.69%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
            ^m4@1.4.18%clang@9.0.0-apple+sigsegv arch=darwin-highsierra-x86_64 
                ^libsigsegv
            ^perl@5.24.1%clang@9.0.0-apple+cpanm+shared arch=darwin-highsierra-x86_64 
                ^gdbm@1.13%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
                    ^readline@7.0%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
                        ^ncurses@6.0%clang@9.0.0-apple~symlinks arch=darwin-highsierra-x86_64 
                            ^pkg-config@0.29.2%clang@9.0.0-apple+internal_glib arch=darwin-highsierra-x86_64 
        ^automake@1.15.1%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
        ^curl@7.56.0%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
            ^nghttp2@1.26.0%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
            ^openssl@1.0.2k%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
                ^zlib@1.2.11%clang@9.0.0-apple+pic+shared arch=darwin-highsierra-x86_64 
        ^gettext@0.19.8.1%clang@9.0.0-apple+bzip2+curses+git~libunistring+libxml2+tar+xz arch=darwin-highsierra-x86_64 
            ^bzip2
            ^libxml2
                ^xz
            ^tar
        ^libiconv@1.15%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
        ^libtool@2.4.6%clang@9.0.0-apple arch=darwin-highsierra-x86_64 
```

**Comment by healther** [comment] 2017-10-13 07:44
```315d844ab7e0036d11c5d9344d4999c16f8894cb``` is the first commit where it fails. #5430 introduced the ```+jit``` flag to ```pcre``` and a new version to git. So not really a new issue in the concretiser, but rather a new trigger by adding the second flag to ```pcre```

**Comment by healther** [comment] 2017-10-13 07:46
@tgamblin @scheibelp

**Comment by alalazo** [comment] 2017-10-13 10:17
@healther The problem is by default `git` wants `pcre+jit`, while `swig` wants `pcre~jit`. Pulling both into the same DAG cause the error,

**Comment by alalazo** [comment] 2017-10-13 10:25
Can we close this as duplicate of #5465 ?

**Comment by healther** [comment] 2017-10-13 11:40
The swig package only has 
```
    depends_on('pcre')
```
in it. It's only that ```pcre``` defaults to False. We can close this and move the discussion to #5465, but I really want to stress, that it is not an impossible spec that is wanted, but rather that the default is fixated too early.

**Comment by alalazo** [comment] 2017-10-13 11:45
@healther Sure. It's a known problem with the concretization heuristics. It just seemed to me exactly the same case. Even there `pcre` gets its default fixed early, and couldn't satisfy later `+jit`.

**Closed** 2017-10-13 11:49 UTC
Labels: concretization
