### ISSUE TITLE
Failing install return no error code without --fail-fast

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#21319] opened 2021-01-27 10:55 UTC
### Steps to reproduce the issue

```
$ git clone https://github.com/haampie-throwaway/spack-status-code.git
$ cd spack-status-code
$ spack -e . install &> /dev/null && echo "This should not be printed if the error code is correct"
This should not be printed if the error code is correct
$ spack -e . install --fail-fast &> /dev/null && echo "This should not be printed if the error code is correct"
$
```

* **Spack:** 0.16.0-997-aa8e026242
* **Python:** 3.8.7
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

ping @alalazo

**Comment by alalazo** [comment] 2021-01-27 12:38
Duplicate of #20510

**Comment by alalazo** [comment] 2021-01-27 12:39
@haampie Let's keep this open nonetheless, just added the comment above to be sure to close both issues.

**Comment by vvolkl** [comment] 2021-02-20 07:49
I hit this as well, is definitely an issue when using spack in CI builds  / scripts.

**Comment by tldahlgren** [comment] 2021-02-25 23:20
FYI.  Haven't tried to reproduce with your steps but I suspect, from the duplicate issue thread, that I know what the issue is here and am looking into it.

**Closed as completed** 2021-02-27 08:21 UTC
Labels: bug, impact-medium
