### ISSUE TITLE
I CANT INSTALL CMAKE

### ISSUE THREAD

**Issue by Bitllion** [LLNL/spack#22859] opened 2021-04-08 07:04 UTC
```
➜  ~ spack install cmake
[+] /home/bit/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/pkgconf-1.7.3-iv4r27lutf34ryajxgcf3sx3ves7w5uy
[+] /home/bit/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/berkeley-db-18.1.40-sd7qj37z5a7tq5eboycjwntctur4ygnp
[+] /home/bit/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/zlib-1.2.11-2pwsgfxppopolmjj6tf34k5jsaqzpodo
[+] /home/bit/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/ncurses-6.2-l4seuemvhefwetlot2dbcnlaxtncqzqd
[+] /home/bit/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/readline-8.0-r4c2fzm4n4clqhgcgxyky5dqebi6q5sc
[+] /home/bit/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/gdbm-1.18.1-5brqa4fwun6ku5eclsuorw3drx362cyo
[+] /home/bit/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/perl-5.32.1-w7ddqng3ea5eggp5r2c5xgnokrjvgcop
[+] /home/bit/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/openssl-1.1.1i-qq3co5z6gr5wf6g4xij3m3utlgktojxq
==> Installing cmake-3.19.2-yd5pspkxptim2xuzisherb653h5szshn
==> No binary for cmake-3.19.2-yd5pspkxptim2xuzisherb653h5szshn found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/e3/e3e0fd3b23b7fb13e1a856581078e0776ffa2df4e9d3164039c36d3315e0c7f0.tar.gz
############################################################################################################################################ 100.0%
==> cmake: Executing phase: 'bootstrap'
==> cmake: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j12'

2 errors found in build log:
     1950    /tmp/bit/spack-stage/spack-stage-cmake-3.19.2-yd5pspkxptim2xuzisherb653h5szshn/spack-src/Source/cmAddCustomCommandCommand.cxx:20:6: i
             nternal compiler error: Segmentation fault
     1951       20 | bool cmAddCustomCommandCommand(std::vector<std::string> const& args,
     1952          |      ^~~~~~~~~~~~~~~~~~~~~~~~~
     1953    Please submit a full bug report,
     1954    with preprocessed source if appropriate.
     1955    See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
  >> 1956    make[2]: *** [Source/CMakeFiles/CMakeLib.dir/build.make:2357: Source/CMakeFiles/CMakeLib.dir/cmAddCustomCommandCommand.cxx.o] Error 1
     1957    make[2]: *** Waiting for unfinished jobs....
  >> 1958    make[1]: *** [CMakeFiles/Makefile2:2327: Source/CMakeFiles/CMakeLib.dir/all] Error 2
     1959    make: *** [Makefile:182: all] Error 2

See build log for details:
  /tmp/bit/spack-stage/spack-stage-cmake-3.19.2-yd5pspkxptim2xuzisherb653h5szshn/spack-build-out.txt

```
OTHER
```
➜  ~ spack debug report
* **Spack:** 0.16.0
* **Python:** 3.7.9
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** original
```

**Comment by alalazo** [comment] 2021-04-08 08:40
The log points to an internal compiler error

**Comment by romintomasetti** [comment] 2021-04-12 19:30
I could not reproduce the bug. CMake was successfully installed (`cmake-3.20.0-jkqw2o56adzygbkk5wbxrskcecm66cxq`).

```text
spack debug report
* **Spack:** 0.16.1-2148-e21e26094e
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** original
```

I also tried `cmake-3.19.2` (`cmake-3.19.2-fkjdzsucqyyqrdwtyszryli4qegp7lwz`), no issue.

**Comment by alalazo** [comment] 2021-04-15 12:02
Closing, but feel free to reopen if you have more pointers.

**Closed as completed by alalazo** 2021-04-15 12:02 UTC
Labels: build-error, unreproducible
