### ISSUE TITLE
Split Builtin Spack repo and Spack itself

### ISSUE THREAD

**Issue by DiegoMagdaleno** [LLNL/spack#20769] opened 2021-01-10 00:37 UTC
As of right now Spack has their built in repository in the same Git repo where its source code is located.

This creates some problems, like packages not being able to be updated without updating spack itself, or doing git pull on the location Spack is installed on.

This proposal would make Spack do, what Homebrew does to a certain extent, have Spack and Spack-core (Repository).

Issues this would fix:

- Having a better issue tracking of what issues are package related and what issues are core related.
- Making it easier for developers to add a future Spack update command, where it is able to update the repository independently from Spack core.
- Reduce the clutter in the Spack root folder

I would be open to help with this transition in the same way Homebrew did it, in my opinion this has many benefits and allows for a more professional package manager experience, because right now there is a big issue with Spack and it is that, if I want to stay on Spack 0.16.0, and there is a bug with a package, since Spack doesn't follow a LTS release model (where most packages are supposed to be stable), I have to git clone the Spack repository, which makes it a little confusing if I only want to install Spack 0.16.0 and don't update in case something goes wrong with the `develop` branch.

**Comment by adamjstewart** [comment] 2021-01-10 23:05
Duplicate of #1773 and #17062

**Closed as completed by adamjstewart** 2021-01-10 23:05 UTC
Labels: duplicate, feature, repos, git
