### ISSUE TITLE
Installation issue: bison missing texinfo dependency 

### ISSUE THREAD

**Issue by thomas-robinson** [LLNL/spack#44438] opened 2024-05-29 17:48 UTC
### Steps to reproduce the issue

```console
$ cat Dockerfile 
FROM spack/rockylinux8:latest as builder
RUN . /opt/spack/share/spack/setup-env.sh && spack install bison

$ podman build -t test:test -f Dockerfile
...
```

### Error message

<details><summary>Error message</summary>

<pre>
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'V=1'

4 errors found in build log:
     2444      rc=$?; \
     2445      CDPATH="${ZSH_VERSION+.}:" && cd /tmp/root/spack-stage/spack-sta
             ge-bison-3.8.2-ycol4tvgrm6elwszgokozcnwcz6hfyaa/spack-src && \
     2446      $restore $backupdir/* `echo ".//tmp/root/spack-stage/spack-stage
             -bison-3.8.2-ycol4tvgrm6elwszgokozcnwcz6hfyaa/spack-src/doc/bison.
             info" | sed 's|[^/]*$||'`; \
     2447    fi; \
     2448    rm -rf $backupdir; exit $rc
     2449    /tmp/root/spack-stage/spack-stage-bison-3.8.2-ycol4tvgrm6elwszgoko
             zcnwcz6hfyaa/spack-src/build-aux/missing: line 81: makeinfo: comma
             nd not found
  >> 2450    WARNING: 'makeinfo' is missing on your system.
     2451             You should only need it if you modified a '.texi' file, o
             r
     2452             any other file indirectly affecting the aspect of the man
             ual.
     2453             You might want to install the Texinfo package:
     2454             <https://www.gnu.org/software/texinfo/>
     2455             The spurious makeinfo call might also be the consequence 
             of
     2456             using a buggy 'make' (AIX, DU, IRIX), in which case you m
             ight
     2457             want to install GNU make:
     2458             <https://www.gnu.org/software/make/>
  >> 2459    make[2]: *** [Makefile:9582: /tmp/root/spack-stage/spack-stage-bis
             on-3.8.2-ycol4tvgrm6elwszgokozcnwcz6hfyaa/spack-src/doc/bison.info
             ] Error 127
     2460    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-biso
             n-3.8.2-ycol4tvgrm6elwszgokozcnwcz6hfyaa/spack-src/spack-build'
  >> 2461    make[1]: *** [Makefile:10377: all-recursive] Error 1
     2462    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-biso
             n-3.8.2-ycol4tvgrm6elwszgokozcnwcz6hfyaa/spack-src/spack-build'
  >> 2463    make: *** [Makefile:3866: all] Error 2

See build log for details:
  /tmp/root/spack-stage/spack-stage-bison-3.8.2-ycol4tvgrm6elwszgokozcnwcz6hfyaa/spack-build-out.txt

Error: building at STEP "RUN . /opt/spack/share/spack/setup-env.sh && spack install bison": while running runtime: exit status 1

</pre></details>

### Information on your system

* **Spack:** 0.22.0 (5fe93fee1eec46a0750bd340198bffcb92ff9eec)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-zen2
* **Concretizer:** clingo

### Additional information

This issue was found while building a container using the spack/rockylinux8 container.  Adding the `texinfo` package as a dependency for bison , and that resolved the issue.  This is how I handled it in my Dockerfile:
```dockerfile
RUN sed -i '60i \    depends_on("texinfo")' /opt/spack/var/spack/repos/builtin/packages/bison/package.py && cat /opt/spack/var/spack/repos/builtin/packages/bison/package.py
```
I `cat`ed it to make sure the spacing was right.  It looks like the bison package.py file just needs to be updated to include the dependency.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment] 2024-05-29 19:22
Thanks for the detailed issue. The real issue is missing `diffutils` not `texinfo`.

**Comment by haampie** [comment] 2024-05-29 20:29
Duplicate of #44207

**Closed as completed by haampie** 2024-05-29 20:29 UTC
Labels: build-error
