### ISSUE TITLE
Installation issue:  akantu

### ISSUE THREAD

**Issue by darmac** [LLNL/spack#17946] opened 2020-08-08 02:24 UTC
`akantu` build fail in spack:
```
[root@Estuary-CentOS8 ~]# spack install -v akantu
==> Error: An unsatisfiable version constraint has been detected for spec:

    boost@1.73.0%gcc@8.2.1+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=98 visibility=hidden arch=linux-centos8-aarch64


while trying to concretize the partial spec:

    akantu@3.0.0%gcc@8.2.1+mpi~python build_type=RelWithDebInfo external_solvers=none arch=linux-centos8-aarch64
        ^cmake@3.18.1%gcc@8.2.1~doc+ncurses+openssl+ownlibs~qt arch=linux-centos8-aarch64
            ^ncurses
                ^pkgconfig
            ^openssl
                ^perl@5.14.0:
                    ^berkeley-db
                    ^gdbm
                        ^readline
                ^zlib


akantu requires boost version :1.66, but spec asked for 1.73.0
```

**Comment by adamjstewart** [comment] 2020-08-23 16:54
This is a known issue in the concretizer that should be fixed by @tgamblin's new concretizer (coming soon).

Current workarounds:
```console
$ spack install akantu@3.0.0
$ spack install akantu ^boost@:1.66
```
We could also modify the `package.py` to prevent this by making the following change:
```diff
diff --git a/var/spack/repos/builtin/packages/akantu/package.py b/var/spack/repos/builtin/packages/akantu/package.py
index c58225261f..965b261f40 100644
--- a/var/spack/repos/builtin/packages/akantu/package.py
+++ b/var/spack/repos/builtin/packages/akantu/package.py
@@ -30,7 +30,7 @@ class Akantu(CMakePackage):
             description="Activates python bindings")
 
     depends_on('boost@:1.66', when='@:3.0.99')
-    depends_on('boost')
+    depends_on('boost', when='@master')
     depends_on('lapack')
     depends_on('cmake@3.5.1:', type='build')
     depends_on('python', when='+python', type=('build', 'run'))
```
Feel free to submit a PR for this if you want.

**Comment by darmac** [comment] 2020-08-24 01:05
got it, thanks

**Comment by alalazo** [comment] 2020-11-02 22:55
Duplicate of #1781

**Closed as completed** 2020-11-02 22:55 UTC
Labels: build-error, concretization
