### ISSUE TITLE
Split packages directory into multiple directories

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#4185] opened 2017-05-09 20:28 UTC
Github refuses to display directories with more than 1000 entries. We should split the package directory into multiple directories. Splitting off e.g. the `py-` and `r-` files might be a beginning.

**Comment by adamjstewart** [comment] 2017-05-09 20:29
Duplicate of #2094.

**Comment by davydden** [comment] 2017-05-09 20:29
> We should

we could, but for now just press `t` while on https://github.com/LLNL/spack

**Closed by adamjstewart** 2017-05-09 20:29 UTC
