### ISSUE TITLE
Add better reporting for the use of old formatting style

### ISSUE THREAD

**Issue by kc9qey** [LLNL/spack#39294] opened 2023-08-07 14:11 UTC
### Steps to reproduce

```
svcdeltaswmgt@dt-login03 0.17.1]$ spack spec xerces-c
==> Warning: config:terminal_title has been replaced by install_status and is ignored
Input spec
--------------------------------
 -   xerces-c

Concretized
--------------------------------
 -   xerces-c@3.2.4%gcc@11.2.0 build_system=autotools cxxstd=default netaccessor=curl transcoder=gnuiconv arch=linux-rhel8-zen3
[e]      ^curl@7.61.1%gcc@11.2.0~gssapi~ldap~libidn2~librtmp~libssh+libssh2+nghttp2 build_system=autotools libs=shared,static tls=mbedtls,openssl arch=linux-rhel8-zen3
[+]      ^libiconv@1.16%gcc@11.2.0 libs=shared,static arch=linux-rhel8-zen3

[svcdeltaswmgt@dt-login03 0.17.1]$ spack install xerces-c%gcc@11.2.0
==> Warning: config:terminal_title has been replaced by install_status and is ignored
[+] /usr (external curl-7.61.1-ljruki2ikiqsewcogfj7o5hh6kqxuyix)
[+] /sw/spack/deltacpu-2022-03/apps/libiconv/1.16-gcc-11.2.0-va3oiyg
==> Error: Attempted to format attribute compilername.Spec  has no attribute compilername
[svcdeltaswmgt@dt-login03 0.17.1]$ 
[svcdeltaswmgt@dt-login03 0.17.1]$ spack --version
0.21.0.dev0 (ea9c488897a8729e31461731e9df934db8c27205)
[svcdeltaswmgt@dt-login03 0.17.1]$ 
```

### Error message

==> Error: Attempted to format attribute compilername.Spec  has no attribute compilername``

### Information on your system

[svcdeltaswmgt@dt-login03 0.17.1]$ spack debug report
* **Spack:** 0.21.0.dev0 (ea9c488897a8729e31461731e9df934db8c27205)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen3
==> Warning: config:terminal_title has been replaced by install_status and is ignored
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by kc9qey** [comment] 2023-08-07 14:39
```
# fyi, i'm on the latest version
[svcdeltaswmgt@dt-login03 0.17.1]$ cd $SPACK_ROOT
[svcdeltaswmgt@dt-login03 0.17.1]$ pwd
/sw/spack/spackcpu/0.17.1
[svcdeltaswmgt@dt-login03 0.17.1]$ git pull origin develop
From https://github.com/spack/spack
 * branch                  develop    -> FETCH_HEAD
Already up to date.
[svcdeltaswmgt@dt-login03 0.17.1]$ 
[svcdeltaswmgt@dt-login03 0.17.1]$ spack audit packages xerces-c
==> Warning: config:terminal_title has been replaced by install_status and is ignored
PKG-DIRECTIVES: 0 issues found.
PKG-ATTRIBUTES: 0 issues found.
PKG-PROPERTIES: 0 issues found.
[svcdeltaswmgt@dt-login03 0.17.1]$ spack audit configs
CFG-COMPILER: 0 issues found.
CFG-PACKAGES: 0 issues found.
[svcdeltaswmgt@dt-login03 0.17.1]$

**Comment by kc9qey** [comment] 2023-08-07 15:27
ok, i updated config.yaml ( even though audit configs shows no issues ) to look like:

    # all: "${PACKAGE}/${VERSION}-${COMPILERNAME}-${COMPILERVER}-${HASH:7}"
      all: "${PACKAGE}/${VERSION}-${compiler.name}-${compiler.version}-${HASH:7}"

as per a response in https://github.com/spack/spack/issues/37774 .  I'm not getting the "Spec  has no attribute  <foo> " now.  

However, attempts to install packages i've been able to build in the past now fail with (something with my ${HASH:7} , how to fix ??? ):

```
>> 879    /bin/sh: /.2.3-cc-1.2.0-mwk5yx/lib: No such file or directory

**Comment by kc9qey** [comment] 2023-08-07 15:51
ok, i *think* i'm back to operational after using this line in config.yaml:

      all: "{architecture}/{compiler.name}-{compiler.version}/{name}-{version}-{hash:7}"

following the new example i find in: https://spack.readthedocs.io/en/latest/config_yaml.html#config-yaml

...it would be nice to get more info from the error messages or better yet, for "spack audit configs" to spot this.  Are there other gotchas that are looming for me with leveling up to the latest spack devel version ??

**Comment by alalazo** [comment] 2023-08-08 08:21
Duplicate of #37774

**Comment by alalazo** [comment] 2023-08-08 08:23
> ...it would be nice to get more info from the error messages or better yet, for "spack audit configs" to spot this. Are there other gotchas that are looming for me with leveling up to the latest spack devel version ??

I'll implement an audit for this, and close the two issues when that is ready.

**Closed as completed** 2024-01-04 07:44 UTC
Labels: bug, impact-low
