### ISSUE TITLE
Spack-built Python: ImportError: No module named _io

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#3478] opened 2017-03-17 17:41 UTC
Has anyone seen this error message before?
```
$ /Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/python-2.7.13-tjqn5npfo573q2jw3dumzhzctfd2vvdv/bin/python
Python 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import io
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/python-2.7.13-tjqn5npfo573q2jw3dumzhzctfd2vvdv/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: No module named _io
```
It occurs for me on develop, but only on macOS. It's definitely new, as I've never seen it before. @davydden?

**Comment by davydden** [comment] 2017-03-17 17:53
i think i saw those when there was a misunderstanding between system provided python and the one build by spack, see https://github.com/LLNL/spack/issues/2534

**Comment by adamjstewart** [comment] 2017-03-17 17:54
Yep, seems like the same problem. I guess this was never resolved.

**Comment by davydden** [comment] 2017-03-17 17:55
current python works for me on Sierra:
```
$ spack load python
$ which python
/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/python-2.7.13-hcpozzgaht7gddrvyrn2fprcm5tmqqii/bin/python
$ python
Python 2.7.13 (default, Mar  3 2017, 22:36:11)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import io
>>>
```

**Comment by davydden** [comment] 2017-03-17 17:56
> I guess this was never resolved.

that one was resolved by https://github.com/LLNL/spack/pull/2560 which makes sure the same python is used to configure slepc as that which was used to build petsc.

**Comment by adamjstewart** [comment] 2017-03-17 18:06
Ah, so it's a different problem then. Your problem was that you were using the wrong Python. My problem is that `io` can't be imported at all with Spack-installed Python.

**Comment by davydden** [comment] 2017-03-17 18:18
> Your problem was that you were using the wrong Python. 

Correct

**Comment by xjrc** [comment] 2017-03-17 18:44
@adamjstewart: For what it's worth, this was the error I was getting before #1435 was merged.  The problem was that user configuration was getting in the way and causing shared libraries (e.g. `_io.so`) from being installed in the Python Spack directory.  It may be worthwhile to check and see if `_io.so` is located in `/path/to/spack/python/lib/python2.7/lib-dynload` and to figure out what could be redirecting it if it isn't present.

**Comment by adamjstewart** [comment] 2017-03-17 19:45
Thanks @xjrc. `_io.so` is indeed not installed anywhere in the Python installation directory. This also causes `make test` to fail. Any idea where these user configuration files would be hiding? I'll start poking around.

**Comment by xjrc** [comment] 2017-03-17 20:05
@adamjstewart: You can find information on the configuration files that can be used to change install paths [here](https://docs.python.org/2/install/index.html#distutils-configuration-files).  These files shouldn't be causing any problems after #1435, but I may have missed something in my fix related to a non-user configuration level.

To debug this, I'd recommend saving the install stage for `python@2.7.13` and looking around in the `/path/to/stage/Makefile.pre.in` file to see if `setup.py build/install` is ever invoked without `--no-user-cfg`.  If you find any such invocations, you'll have to modify the Spack build script for Python to catch these calls.  If you don't find anything suspicious in `Makefile.pre.in`, my only guess is that the problem is related to how `python@2.7.13` performs installation, which would require scouring the Python build source files.

**Comment by adamjstewart** [comment] 2017-03-17 20:20
@xjrc You didn't miss anything in `Makefile.pre.in`:
```
$ grep setup.py Makefile.pre.in
# Both CPPFLAGS and LDFLAGS need to contain the shell's value for setup.py to
		$(PYTHON_FOR_BUILD) $(srcdir)/setup.py $$quiet  --no-user-cfg build
	$(RUNSHARED) $(PYTHON_FOR_BUILD) $(srcdir)/setup.py  --no-user-cfg install \
	$(PYTHON_FOR_BUILD) $(srcdir)/Tools/scripts/setup.py  --no-user-cfg install \
```
I'll keep looking.

**Comment by adamjstewart** [comment] 2017-03-17 20:38
No suspicious environment variables like `DYLD_LIBRARY_PATH` that could be causing this problem.

**Comment by adamjstewart** [comment] 2017-03-17 21:28
Also tried upgrading the Anaconda installation that I run Spack with so that it would be the same version as the Python I am trying to install, but that didn't work. Nor did running Spack with the system Python.

**Comment by adamjstewart** [comment] 2017-03-18 14:05
Found the error message that explains why `_io.so` was never installed:
```
building '_io' extension
creating build/temp.macosx-10.6-x86_64-2.7/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io
/Users/Adam/spack/lib/spack/env/clang/clang -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -IModules/_io -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Mac/Include -I. -IInclude -I./Include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/bzip2-1.0.6-v2mr5fian2hsq2fucberwsqp4isjgx57/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/ncurses-6.0-yz5pwlpnmngucsbfj2aswcowcf2gnav6/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/zlib-1.2.11-ahv5tlvsgqpenkehyj7s6oagr5hbksnv/include -I/usr/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/sqlite-3.8.5-qhml3gk5d6cg2ljox7xeftlo2li2zvnq/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/readline-7.0-fuphoesrzfpywojpreftevqszupck3io/include -I/usr/local/include -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Include -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13 -c /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/bufferedio.c -o build/temp.macosx-10.6-x86_64-2.7/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/bufferedio.o
/Users/Adam/spack/lib/spack/env/clang/clang -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -IModules/_io -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Mac/Include -I. -IInclude -I./Include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/bzip2-1.0.6-v2mr5fian2hsq2fucberwsqp4isjgx57/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/ncurses-6.0-yz5pwlpnmngucsbfj2aswcowcf2gnav6/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/zlib-1.2.11-ahv5tlvsgqpenkehyj7s6oagr5hbksnv/include -I/usr/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/sqlite-3.8.5-qhml3gk5d6cg2ljox7xeftlo2li2zvnq/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/readline-7.0-fuphoesrzfpywojpreftevqszupck3io/include -I/usr/local/include -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Include -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13 -c /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/bytesio.c -o build/temp.macosx-10.6-x86_64-2.7/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/bytesio.o
/Users/Adam/spack/lib/spack/env/clang/clang -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -IModules/_io -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Mac/Include -I. -IInclude -I./Include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/bzip2-1.0.6-v2mr5fian2hsq2fucberwsqp4isjgx57/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/ncurses-6.0-yz5pwlpnmngucsbfj2aswcowcf2gnav6/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/zlib-1.2.11-ahv5tlvsgqpenkehyj7s6oagr5hbksnv/include -I/usr/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/sqlite-3.8.5-qhml3gk5d6cg2ljox7xeftlo2li2zvnq/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/readline-7.0-fuphoesrzfpywojpreftevqszupck3io/include -I/usr/local/include -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Include -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13 -c /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/fileio.c -o build/temp.macosx-10.6-x86_64-2.7/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/fileio.o
/Users/Adam/spack/lib/spack/env/clang/clang -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -IModules/_io -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Mac/Include -I. -IInclude -I./Include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/bzip2-1.0.6-v2mr5fian2hsq2fucberwsqp4isjgx57/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/ncurses-6.0-yz5pwlpnmngucsbfj2aswcowcf2gnav6/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/zlib-1.2.11-ahv5tlvsgqpenkehyj7s6oagr5hbksnv/include -I/usr/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/sqlite-3.8.5-qhml3gk5d6cg2ljox7xeftlo2li2zvnq/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/readline-7.0-fuphoesrzfpywojpreftevqszupck3io/include -I/usr/local/include -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Include -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13 -c /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/iobase.c -o build/temp.macosx-10.6-x86_64-2.7/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/iobase.o
/Users/Adam/spack/lib/spack/env/clang/clang -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -IModules/_io -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Mac/Include -I. -IInclude -I./Include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/bzip2-1.0.6-v2mr5fian2hsq2fucberwsqp4isjgx57/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/ncurses-6.0-yz5pwlpnmngucsbfj2aswcowcf2gnav6/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/zlib-1.2.11-ahv5tlvsgqpenkehyj7s6oagr5hbksnv/include -I/usr/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/sqlite-3.8.5-qhml3gk5d6cg2ljox7xeftlo2li2zvnq/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/readline-7.0-fuphoesrzfpywojpreftevqszupck3io/include -I/usr/local/include -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Include -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13 -c /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/_iomodule.c -o build/temp.macosx-10.6-x86_64-2.7/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/_iomodule.o
/Users/Adam/spack/lib/spack/env/clang/clang -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -IModules/_io -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Mac/Include -I. -IInclude -I./Include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/bzip2-1.0.6-v2mr5fian2hsq2fucberwsqp4isjgx57/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/ncurses-6.0-yz5pwlpnmngucsbfj2aswcowcf2gnav6/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/zlib-1.2.11-ahv5tlvsgqpenkehyj7s6oagr5hbksnv/include -I/usr/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/sqlite-3.8.5-qhml3gk5d6cg2ljox7xeftlo2li2zvnq/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/readline-7.0-fuphoesrzfpywojpreftevqszupck3io/include -I/usr/local/include -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Include -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13 -c /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/stringio.c -o build/temp.macosx-10.6-x86_64-2.7/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/stringio.o
/Users/Adam/spack/lib/spack/env/clang/clang -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -IModules/_io -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Mac/Include -I. -IInclude -I./Include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/bzip2-1.0.6-v2mr5fian2hsq2fucberwsqp4isjgx57/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/ncurses-6.0-yz5pwlpnmngucsbfj2aswcowcf2gnav6/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/zlib-1.2.11-ahv5tlvsgqpenkehyj7s6oagr5hbksnv/include -I/usr/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/sqlite-3.8.5-qhml3gk5d6cg2ljox7xeftlo2li2zvnq/include -I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/readline-7.0-fuphoesrzfpywojpreftevqszupck3io/include -I/usr/local/include -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Include -I/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13 -c /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/textio.c -o build/temp.macosx-10.6-x86_64-2.7/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/textio.o
/Users/Adam/spack/lib/spack/env/clang/clang -bundle -undefined dynamic_lookup -L/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/bzip2-1.0.6-v2mr5fian2hsq2fucberwsqp4isjgx57/lib -L/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/ncurses-6.0-yz5pwlpnmngucsbfj2aswcowcf2gnav6/lib -L/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/zlib-1.2.11-ahv5tlvsgqpenkehyj7s6oagr5hbksnv/lib -L/usr/lib -L/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/sqlite-3.8.5-qhml3gk5d6cg2ljox7xeftlo2li2zvnq/lib -L/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/readline-7.0-fuphoesrzfpywojpreftevqszupck3io/lib build/temp.macosx-10.6-x86_64-2.7/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/bufferedio.o build/temp.macosx-10.6-x86_64-2.7/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/bytesio.o build/temp.macosx-10.6-x86_64-2.7/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/fileio.o build/temp.macosx-10.6-x86_64-2.7/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/iobase.o build/temp.macosx-10.6-x86_64-2.7/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/_iomodule.o build/temp.macosx-10.6-x86_64-2.7/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/stringio.o build/temp.macosx-10.6-x86_64-2.7/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-nkMTAE/Python-2.7.13/Modules/_io/textio.o -L/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/bzip2-1.0.6-v2mr5fian2hsq2fucberwsqp4isjgx57/lib -L/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/ncurses-6.0-yz5pwlpnmngucsbfj2aswcowcf2gnav6/lib -L/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/zlib-1.2.11-ahv5tlvsgqpenkehyj7s6oagr5hbksnv/lib -L/usr/lib -L/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/sqlite-3.8.5-qhml3gk5d6cg2ljox7xeftlo2li2zvnq/lib -L/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/readline-7.0-fuphoesrzfpywojpreftevqszupck3io/lib -L/usr/local/lib -L. -o build/lib.macosx-10.6-x86_64-2.7/_io.so
*** WARNING: renaming "_io" since importing it failed: dlopen(build/lib.macosx-10.6-x86_64-2.7/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: build/lib.macosx-10.6-x86_64-2.7/_io.so
  Expected in: flat namespace
 in build/lib.macosx-10.6-x86_64-2.7/_io.so
...
Failed to build these modules:
_io
```
Now I just need to figure out why `__PyCodecInfo_GetIncrementalDecoder` wasn't found.

**Comment by adamjstewart** [comment] 2017-03-18 14:35
Submitted a bug report with Python: http://bugs.python.org/issue29846

**Comment by adamjstewart** [comment] 2017-03-18 20:14
According to the Python developers:

> My guess is that you will find that the problem goes away if you avoid the use of `--enable-shared` on the Python configure; most Python distributions on macOS use `--enable-framework` rather than `--enable-shared` and we seldom test it.  Or use neither.

Removing `--enable-shared` from the build solves the problem. I think this is the best way to go, at least on macOS.

**Closed** 2017-04-30 00:24 UTC
Labels: build-error, macOS, python
