### ISSUE TITLE
Cannot access Mercurial repository

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1645] opened 2016-08-26 22:17 UTC
I am trying to access a Mercurial repository via Spack. This fails with this error message:

```
==> Trying to clone Mercurial repository:
  https://bitbucket.org/yt_analysis/yt
abort: couldn't find mercurial libraries in [/usr/bin /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-matplotlib-1.4.3-3idasdgdwnj6on34vkrxnjtd3mwe5nje/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-nose-1.3.7-edc7y5lzpn4wp4c2vtq5cmdcoixmiacz/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-dateutil-2.5.2-o6xvkdkmvdovdvy6w6vaunblrtcmis6u/lib/python2.7/site-packages/python_dateutil-2.5.2-py2.7.egg /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-six-1.10.0-zaejwqbge4q4oflupmoddflzeu5zdmqe/lib/python2.7/site-packages/six-1.10.0-py2.7.egg /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-numpy-1.11.0-tiaxzbybgr73vaka2gvdmpdwkfvu5k3v/lib/python2.7/site-packages/numpy-1.11.0-py2.7-linux-x86_64.egg /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-funcsigs-0.4-j43xifssmk2qn6kjrhso5nmm7bao4dxp/lib/python2.7/site-packages/funcsigs-0.4-py2.7.egg /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-dateutil-2.5.2-o6xvkdkmvdovdvy6w6vaunblrtcmis6u/lib/python2.7/site-packages/python_dateutil-2.5.2-py2.7.egg /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-setuptools-20.7.0-ibfn5ooc7h7ocaqhlvfk2y4hfgepbm6u/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-yt-3.3-6bl2vyo7eyera3u4znvrjc64czzjyti7/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-cython-0.23.5-qplq4k6ystfqjnre7mpm4pemvapatin4/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-matplotlib-1.4.3-3idasdgdwnj6on34vkrxnjtd3mwe5nje/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-dateutil-2.5.2-o6xvkdkmvdovdvy6w6vaunblrtcmis6u/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-setuptools-20.7.0-ibfn5ooc7h7ocaqhlvfk2y4hfgepbm6u/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-six-1.10.0-zaejwqbge4q4oflupmoddflzeu5zdmqe/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-funcsigs-0.4-j43xifssmk2qn6kjrhso5nmm7bao4dxp/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-mock-1.3.0-2te7rkanyqmrtav5ocsrhc4lltt5p4za/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-pbr-1.8.1-65rd5zk5qay2guqslgbs2bejps2kl7fl/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-nose-1.3.7-edc7y5lzpn4wp4c2vtq5cmdcoixmiacz/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-numpy-1.11.0-tiaxzbybgr73vaka2gvdmpdwkfvu5k3v/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-pyparsing-2.0.3-xxelplxz3oahojyyoauvufpxarazoz7x/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-pytz-2016.3-gjjm245yri6hb65q34v2ckydl7c6vtjc/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-sympy-1.0-47mnu5lzvg3xctdqxl4afu6cdu7oyjlr/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/py-mpmath-0.19-rwhbgdlp2kh43ohdgagnr6hirnadnpex/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/python-2.7.12-ce4wlum3tkujeyknvql7ibxfi5dskqpy/lib/python2.7 /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/python-2.7.12-ce4wlum3tkujeyknvql7ibxfi5dskqpy/lib/python2.7/plat-x86_64-linux-gnu /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/python-2.7.12-ce4wlum3tkujeyknvql7ibxfi5dskqpy/lib/python2.7/lib-tk /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/python-2.7.12-ce4wlum3tkujeyknvql7ibxfi5dskqpy/lib/python2.7/lib-old /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/python-2.7.12-ce4wlum3tkujeyknvql7ibxfi5dskqpy/lib/python2.7/lib-dynload /nfs/galaxy/unixhome/eschnetter/.local/lib/python2.7/site-packages /xfs1/eschnetter/src/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-6.1.1/python-2.7.12-ce4wlum3tkujeyknvql7ibxfi5dskqpy/lib/python2.7/site-packages]
(check your install and PYTHONPATH)
==> Fetching from [hg] https://bitbucket.org/yt_analysis/yt failed.
==> Error: All fetchers failed for py-yt-3.3-6bl2vyo7eyera3u4znvrjc64czzjyti7
==> Error: Installation process had nonzero exit code : 256
```

Mercurial is implemented in Python. Can it be that Spack sanitizes `PYTHONPATH`, thus disabling Mercurial?

**Comment by citibeth** [comment] 2016-08-28 12:06
Try `spack install --dirty`, see if that helps for now.

I'm coming to believe the santization may be a mistake.  In many real-life situations, the only way to get Spack working is to use `--dirty`, and then be intentional about what we put in the paths.

**Comment by eschnett** [comment] 2016-08-28 13:50
`--dirty` makes no difference.

Cloning the repository outside Spack (with a straightforward `hg clone ...`) works fine.

**Comment by citibeth** [comment] 2016-08-28 13:53
Hmmm, that's sadly surprising to me.  What happens if you put a fake "hg" in your path that prints out the environment when run.  Try running it directly, and then within Spack.  Would that help debug what's going on?

**Comment by adamjstewart** [comment] 2016-08-28 13:58
You'll probably just have to use a Spack-installed Mercurial so that the libraries are RPATHed.

**Comment by tgamblin** [comment] 2016-08-29 00:41
@eschnett: do you have the build log?  It's hard to tell what error 256 is here.

One thing we could probably do would be to move the fetch stage out of the forked process.  It used to live outside, but it was oddly inconsistent for module-scoped things to be accessible from `install()` and not from `patch()` within the same package file.  Now patch is called from `do_install`, which recursively calls `do_stage()` and `do_fetch()`.

**Comment by eschnett** [comment] 2016-08-29 01:52
Things are working find with a Spack-installed Mercurial.

**Comment by citibeth** [comment] 2016-08-29 02:44
One more mysterious bootstrapping issue to document...

**Comment by eschnett** [comment] 2016-08-29 03:15
This is Ubuntu 14.04,
```
$ hg --version
Mercurial Distributed SCM (version 2.8.2)
```

**Comment by BarrySmith** [comment] 2017-01-07 23:53
I am getting a similar problem on 

```
$ uname -a
Linux es 3.13.0-101-generic #148-Ubuntu SMP Thu Oct 20 22:08:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ ./bin/spack install mercurial
==> Installing mercurial
==> Installing py-docutils
==> python is already installed in /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/python-2.7.13-ufzufqm3j4m5p2fjcr4c4doqplnlxkh2
==> Fetching https://pypi.python.org/packages/source/d/docutils/docutils-0.12.tar.gz
######################################################################## 100.0%
==> Staging archive: /sandbox/bsmith/spack/var/spack/stage/py-docutils-0.12-fnn3nq5wsw2wgs5nhdkkzbj7xgxq4wgx/docutils-0.12.tar.gz
==> Created stage in /sandbox/bsmith/spack/var/spack/stage/py-docutils-0.12-fnn3nq5wsw2wgs5nhdkkzbj7xgxq4wgx
==> No patches needed for py-docutils
==> Building py-docutils [Package]
==> Executing phase : 'install'
==> Successfully installed py-docutils
  Fetch: 0.16s.  Build: 0.78s.  Total: 0.94s.
[+] /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/py-docutils-0.12-fnn3nq5wsw2wgs5nhdkkzbj7xgxq4wgx
==> python is already installed in /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/python-2.7.13-ufzufqm3j4m5p2fjcr4c4doqplnlxkh2
==> Fetching https://www.mercurial-scm.org/release/mercurial-3.9.1.tar.gz
######################################################################## 100.0%
==> Staging archive: /sandbox/bsmith/spack/var/spack/stage/mercurial-3.9.1-5do2dioodwu5qoetblupr4isnqleaxdt/mercurial-3.9.1.tar.gz
==> Created stage in /sandbox/bsmith/spack/var/spack/stage/mercurial-3.9.1-5do2dioodwu5qoetblupr4isnqleaxdt
==> No patches needed for mercurial
==> Building mercurial [Package]
==> Executing phase : 'install'
==> Successfully installed mercurial
  Fetch: 0.86s.  Build: 6.70s.  Total: 7.56s.
[+] /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/mercurial-3.9.1-5do2dioodwu5qoetblupr4isnqleaxdt
/sandbox/bsmith/spack (develop=) 
$ ./bin/spack install pflotran
==> Installing pflotran
==> petsc is already installed in /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/petsc-for-pflotran-0.1.0-oo33wmj64hhpqtjgen3lr4wfwurjjltb
==> openmpi is already installed in /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/openmpi-2.0.1-nkvqjyew6hdofrjdrzvpdz3b5tycdz3b
==> hdf5 is already installed in /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/hdf5-1.8.12-b3p6zincukehxcimtvlwlrzztj65sxgz
==> Trying to clone Mercurial repository:
  https://bitbucket.org/pflotran/pflotran-xsdk
abort: couldn't find mercurial libraries in [/usr/bin /tmp/bsmith/spack-stage/spack-stage-Ot1Usq /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/python-2.7.13-ufzufqm3j4m5p2fjcr4c4doqplnlxkh2/lib/python2.7 /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/python-2.7.13-ufzufqm3j4m5p2fjcr4c4doqplnlxkh2/lib/python2.7/plat-x86_64-linux-gnu /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/python-2.7.13-ufzufqm3j4m5p2fjcr4c4doqplnlxkh2/lib/python2.7/lib-tk /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/python-2.7.13-ufzufqm3j4m5p2fjcr4c4doqplnlxkh2/lib/python2.7/lib-old /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/python-2.7.13-ufzufqm3j4m5p2fjcr4c4doqplnlxkh2/lib/python2.7/lib-dynload /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/python-2.7.13-ufzufqm3j4m5p2fjcr4c4doqplnlxkh2/lib/python2.7/site-packages]
(check your install and PYTHONPATH)
==> Fetching from [hg] https://bitbucket.org/pflotran/pflotran-xsdk failed.
==> Error: FetchError: All fetchers failed for pflotran-0.1.0-g7oo3qwsjekg5anjfuzvikqhobx72osh
```

```
$ hg clone https://bitbucket.org/pflotran/pflotran-xsdk
destination directory: pflotran-xsdk
requesting all changes
adding changesets
adding manifests
adding file changes                                                                                                                        
added 10446 changesets with 31294 changes to 3802 files                                                                                    
updating to branch default
2007 files updated, 0 files merged, 0 files removed, 0 files unresolved
/sandbox/bsmith/spack (develop=) 
```

`rm -rf pflotran-xsdk`


```
$ /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/mercurial-3.9.1-5do2dioodwu5qoetblupr4isnqleaxdt/bin/hg clone https://bitbucket.org/pflotran/pflotran-xsdk
*** failed to import extension hgext.qct: No module named qct
destination directory: pflotran-xsdk
requesting all changes
adding changesets
adding manifests
adding file changes                                                                                                                        
added 10446 changesets with 31294 changes to 3802 files                                                                                    
updating to branch default
2007 files updated, 0 files merged, 0 files removed, 0 files unresolved
/sandbox/bsmith/spack (develop=) 
```

so both the system installed hg and the spack installed hg seem to work if called directly to clone pflotran but spack cannot do the download.
```
$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
```

```
$ git log | head 
commit f379697985f0b09a3856e12fff3cf69972a31cc1
Author: Todd Gamblin <tgamblin@llnl.gov>
Date:   Sat Jan 7 09:03:50 2017 -0800

    Fix issues linking hDF5 1.8.14 and below on Ubuntu. (#2772)

commit e39ba88e9c2f4c9409771982e0b12e25d97c359a
Author: Cyrus Harrison <cyrush@llnl.gov>
Date:   Fri Jan 6 12:33:51 2017 -0800
```

I do not have a problem on my Mac.

**Comment by tgamblin** [comment] 2017-01-08 00:08
Did you add the spack-installed Mercurial to your path?  The fetchers aren't currently smart enough to realize that Mercurial is installed by Spack but not in the PATH.  We could probably make them realize that relatively easily.

**Comment by BarrySmith** [comment] 2017-01-08 01:45
That did work, but note I already had a working hg in the path (perhaps it did not work with spack because it used the system python instead of the spack installed python).

   I still consider this a problem with spack because presumably 1) spack should be able to use the working hg in my path or 2) spack should be able to use the hg that it installed without me needing to add it to my path.


```
$ export PATH=/sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/mercurial-3.9.1-5do2dioodwu5qoetblupr4isnqleaxdt/bin:$PATH
/sandbox/bsmith/spack (develop=) 
$ which hg
/sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/mercurial-3.9.1-5do2dioodwu5qoetblupr4isnqleaxdt/bin/hg
/sandbox/bsmith/spack (develop=) 
$ ./bin/spack install pflotran
==> Installing pflotran
==> petsc is already installed in /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/petsc-for-pflotran-0.1.0-oo33wmj64hhpqtjgen3lr4wfwurjjltb
==> openmpi is already installed in /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/openmpi-2.0.1-nkvqjyew6hdofrjdrzvpdz3b5tycdz3b
==> hdf5 is already installed in /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/hdf5-1.8.12-b3p6zincukehxcimtvlwlrzztj65sxgz
==> Trying to clone Mercurial repository:
  https://bitbucket.org/pflotran/pflotran-xsdk
*** failed to import extension hgext.qct: No module named qct
destination directory: pflotran-xsdk
requesting all changes
adding changesets
adding manifests
adding file changes                                                                                                                        
added 10446 changesets with 31294 changes to 3802 files                                                                                    
updating to branch default
2007 files updated, 0 files merged, 0 files removed, 0 files unresolved
```

**Comment by tgamblin** [comment] 2017-01-08 01:57
@BarrySmith: Can you execute this and see what it prints out?

```console
spack-python -c 'import os; print os.environ.["PYTHONPATH"]'
```

**Comment by tgamblin** [comment] 2017-01-08 01:57
Also, does the `hg` fetch test work for you?

```python
$ spack test hg_fetch
```

**Comment by BarrySmith** [comment] 2017-01-08 03:33
```
./bin/spack python -c 'import os; print os.environ["PYTHONPATH"]'

/sandbox/bsmith/spack (develop=) 

```

```
$ ./bin/spack test hg_fetch
=========================================================== test session starts ===========================================================
platform linux2 -- Python 2.7.6, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /sandbox/bsmith/spack, inifile: pytest.ini
collected 487 items 

lib/spack/spack/test/hg_fetch.py ..

======================================================== slowest 20 test durations ========================================================
0.64s call     lib/spack/spack/test/hg_fetch.py::test_fetch[default]
0.61s setup    lib/spack/spack/test/hg_fetch.py::test_fetch[default]
0.47s call     lib/spack/spack/test/hg_fetch.py::test_fetch[rev0]
0.00s teardown lib/spack/spack/test/hg_fetch.py::test_fetch[rev0]
0.00s setup    lib/spack/spack/test/hg_fetch.py::test_fetch[rev0]
0.00s teardown lib/spack/spack/test/hg_fetch.py::test_fetch[default]
========================================================== 485 tests deselected ===========================================================
================================================ 2 passed, 485 deselected in 2.79 seconds =================================================
/sandbox/bsmith/spack (develop=) 

```

**Comment by becker33** [comment] 2017-01-13 00:24
Since #2811 was closed as a duplicate of this, I'll post here. I was able to fetch pflotran on Cori (after loading the mercurial module) as of current develop this afternoon. I have not tested with other mercurial-based packages from this conversation.

**Comment by BarrySmith** [comment] 2017-01-17 23:14
@tgamblin I poked around a little more on this and found the fundamental problem, unfortunately fixing it is more instrusive on spack than I can handle.

Recall we are using a system hg in this case.

When spack calls the executable hg it does this in the spack environment which contains a PYTHONPATH for the Spack installed python. This causes the the system python to not load into its standard sys.path all the directories it normally would and hence the mecurial libraries are not found by the system path. Note the system python has in this case only items from the spack installed Python, which is totally wrong.

`abort: couldn't find mercurial libraries in [/usr/bin /tmp/bsmith/spack-stage/spack-stage-Ot1Usq /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/python-2.7.13-ufzufqm3j4m5p2fjcr4c4doqplnlxkh2/lib/python2.7 /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/python-2.7.13-ufzufqm3j4m5p2fjcr4c4doqplnlxkh2/lib/python2.7/plat-x86_64-linux-gnu /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/python-2.7.13-ufzufqm3j4m5p2fjcr4c4doqplnlxkh2/lib/python2.7/lib-tk /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/python-2.7.13-ufzufqm3j4m5p2fjcr4c4doqplnlxkh2/lib/python2.7/lib-old /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/python-2.7.13-ufzufqm3j4m5p2fjcr4c4doqplnlxkh2/lib/python2.7/lib-dynload /sandbox/bsmith/spack/opt/spack/linux-ubuntu14-x86_64/gcc-6.2.0/python-2.7.13-ufzufqm3j4m5p2fjcr4c4doqplnlxkh2/lib/python2.7/site-packages]
`

One fix is to make sure that the hg is called in the original user environment and not in an environment where spack has set PYTHONPATH, unfortunately due to the clever way you guys run exectuables from python I can't see an easy way to not have the PYTHONPATH set incorrectly. But presumably you can.

**Comment by becker33** [comment] 2017-01-18 18:23
@BarrySmith On what machine are you seeing this error? I am unable to reproduce on Cori and an LLNL Linux machine.

**Comment by tgamblin** [comment] 2017-01-18 18:31
@becker33: I've got this one -- thanks for checking on it

**Comment by adamjstewart** [comment] 2017-04-14 22:01
@eschnett I'm trying to improve Spack's mercurial support in #3834. Can you try my PR and see if the latest version of Mercurial works any better for you?

**Closed** 2017-04-20 01:59 UTC
Labels: fetching, mercurial
