### ISSUE TITLE
py-transformers unable to be found

### ISSUE THREAD

**Issue by cameronrutherford** [LLNL/spack#32444] opened 2022-08-30 15:25 UTC
### Steps to reproduce

This is quite a simple error to reproduce, and has consistently been an issue for me for a while now with various versions of spack.
```console
$ spack spec py-transformers
```
or, to see this error in an environment:
```console
$ spack env create -d ./test-env
$ spacktivate -p ./test-env
$ spack add py-transformers
$ spack concretize -f
```

### Error message

```console
$ spack --debug --stacktrace spec py-transformers
```
<details> <summary>Full error output</summary>

```console
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:24.766764] Reading config file /Users/ruth521/Projects/spack/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:24.794562] Reading config file /Users/ruth521/Projects/spack/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:24.802347] Reading config file /Users/ruth521/Projects/spack/test-env/spack.yaml
lib/spack/spack/environment/environment.py:173 ==> [2022-08-30-11:22:24.804814] Using environment '/Users/ruth521/Projects/spack/test-env'
lib/spack/spack/cmd/__init__.py:124 ==> [2022-08-30-11:22:24.813121] Imported spec from built-in commands
lib/spack/spack/cmd/__init__.py:124 ==> [2022-08-30-11:22:24.814080] Imported spec from built-in commands
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:24.848930] Reading config file /Users/ruth521/Projects/spack/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/environment/environment.py:197 ==> [2022-08-30-11:22:24.857615] Deactivated environment '/Users/ruth521/Projects/spack/test-env'
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:24.900861] Reading config file /Users/ruth521/Projects/spack/spack/etc/spack/defaults/config.yaml
lib/spack/spack/database.py:389 ==> [2022-08-30-11:22:24.919398] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:395 ==> [2022-08-30-11:22:24.919670] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:24.920386] Reading config file /Users/ruth521/Projects/spack/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/database.py:389 ==> [2022-08-30-11:22:24.926917] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:395 ==> [2022-08-30-11:22:24.927213] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/bootstrap.py:626 ==> [2022-08-30-11:22:24.927477] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/bootstrap.py:637 ==> [2022-08-30-11:22:24.928027] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/Users/ruth521/Projects/spack/spack/etc/spack/defaults
lib/spack/spack/bootstrap.py:638 ==> [2022-08-30-11:22:24.928253] [BOOTSTRAP CONFIG SCOPE] name=defaults/darwin, path=/Users/ruth521/Projects/spack/spack/etc/spack/defaults/darwin
lib/spack/spack/bootstrap.py:637 ==> [2022-08-30-11:22:24.928475] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/Users/ruth521/.spack/bootstrap/config
lib/spack/spack/bootstrap.py:638 ==> [2022-08-30-11:22:24.928687] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/darwin, path=/Users/ruth521/.spack/bootstrap/config/darwin
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:24.933957] Reading config file /Users/ruth521/.spack/bootstrap/config/darwin/compilers.yaml
lib/spack/spack/bootstrap.py:763 ==> [2022-08-30-11:22:25.002845] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %apple-clang target=x86_64
lib/spack/spack/bootstrap.py:522 ==> [2022-08-30-11:22:25.003185] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:25.003926] Reading config file /Users/ruth521/Projects/spack/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:25.342635] Reading config file /Users/ruth521/Projects/spack/spack/etc/spack/defaults/config.yaml
lib/spack/spack/bootstrap.py:107 ==> [2022-08-30-11:22:25.500305] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %apple-clang target=x86_64 ^python@3.8 /p5on7i4hejl775ezndzfdkhvwra3hatn" provides the "clingo" Python module
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:25.501973] Reading config file /Users/ruth521/Projects/spack/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:25.520729] Reading config file /Users/ruth521/Projects/spack/test-env/spack.yaml
lib/spack/spack/environment/environment.py:173 ==> [2022-08-30-11:22:25.523291] Using environment '/Users/ruth521/Projects/spack/test-env'
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:25.523640] Reading config file /Users/ruth521/Projects/spack/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:25.528254] Reading config file /Users/ruth521/Projects/spack/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:25.553097] Reading config file /Users/ruth521/Projects/spack/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:29.111862] Reading config file /Users/ruth521/.spack/darwin/compilers.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:29.132916] Reading config file /Users/ruth521/Projects/spack/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:29.163155] Reading config file /Users/ruth521/Projects/spack/spack/etc/spack/defaults/darwin/packages.yaml
lib/spack/spack/config.py:1008 ==> [2022-08-30-11:22:29.173765] Reading config file /Users/ruth521/.spack/packages.yaml
lib/spack/spack/main.py:964 ==> [2022-08-30-11:22:44.591636] SpackError: No versions available for package 'py-transformers'
lib/spack/spack/error.py:54 ==> [2022-08-30-11:22:44.596360] Error: No versions available for package 'py-transformers'
Traceback (most recent call last):
  File "/Users/ruth521/Projects/spack/spack/lib/spack/spack/cmd/__init__.py", line 227, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/Users/ruth521/Projects/spack/spack/lib/spack/spack/spec.py", line 2924, in concretize
    self._new_concretize(tests)
  File "/Users/ruth521/Projects/spack/spack/lib/spack/spack/spec.py", line 2899, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/Users/ruth521/Projects/spack/spack/lib/spack/spack/solver/asp.py", line 2380, in solve
    result, _, _ = self.driver.solve(setup, specs, reuse=reusable_specs, output=output)
  File "/Users/ruth521/Projects/spack/spack/lib/spack/spack/solver/asp.py", line 706, in solve
    answers = builder.build_specs(tuples)
  File "/Users/ruth521/Projects/spack/spack/lib/spack/spack/solver/asp.py", line 2232, in build_specs
    action(*args)
  File "/Users/ruth521/Projects/spack/spack/lib/spack/spack/solver/asp.py", line 2066, in error
    raise UnsatisfiableSpecError(msg)
spack.solver.asp.UnsatisfiableSpecError: No versions available for package 'py-transformers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ruth521/Projects/spack/spack/lib/spack/spack/main.py", line 961, in main
    return _main(argv)
  File "/Users/ruth521/Projects/spack/spack/lib/spack/spack/main.py", line 916, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/Users/ruth521/Projects/spack/spack/lib/spack/spack/main.py", line 944, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/Users/ruth521/Projects/spack/spack/lib/spack/spack/main.py", line 608, in _invoke_command
    return_val = command(parser, args)
  File "/Users/ruth521/Projects/spack/spack/lib/spack/spack/cmd/spec.py", line 104, in spec
    concretized_specs = spack.cmd.parse_specs(args.specs, concretize=True)
  File "/Users/ruth521/Projects/spack/spack/lib/spack/spack/cmd/__init__.py", line 241, in parse_specs
    raise spack.error.SpackError(msg)
spack.error.SpackError: No versions available for package 'py-transformers'
```
</details>

### Information on your system

I have seen this error on multiple systems:

On my local mac:
```console
$ spack debug report
* **Spack:** 0.19.0.dev0 (08c67302fc61e18c32be3ff5a0cf20c96db5e26e)
* **Python:** 3.8.5
* **Platform:** darwin-catalina-skylake
* **Concretizer:** clingo
```

On HPC clusters:

```console
$ spack debug report
* **Spack:** 0.19.0.dev0
* **Python:** 3.9.5
* **Platform:** linux-centos7-zen2
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by cameronrutherford** [comment] 2022-08-30 15:26
@adamjstewart is the maintainer of the relevant package, and replied in the slack when I asked about this issue in #general.

I get this behaviour with a fresh clone of spack, and it is painfully easy to re-produce for me.

I am able to run `spack edit py-transformers` just fine and see that the `package.py` exists, but for some reason spack cannot concretize the package itself.

**Comment by cameronrutherford** [comment] 2022-08-30 15:28
A workaround that I have imagined would be to install the relevant stack without `py-transformers` using spack, and then to install the transformers library using `pip`.

This might work, but it would be 1000% easier to have this working within spack.

**Comment by adamjstewart** [comment] 2022-08-30 17:06
... aaaand all of a sudden I'm magically able to reproduce this. I don't think anything changed on my end, but I'm glad that you're not the only one experiencing this anymore.

@becker33 @alalazo is it possible that this error message is a red herring? The package clearly has versions, so I'm guessing it's more something like "no version can be concretized successfully".

**Comment by cameronrutherford** [comment] 2022-11-04 19:46
Any progress on this? I would love to manage transformers through spack.

**Comment by adamjstewart** [comment] 2022-11-04 20:20
Concretizer error message is still useless...

Going to try to add a newer version and see if it's easier to concretize. What is almost certainly going on here is that two of the dependencies require versions that conflict with each other. The tricky part is figuring out which versions conflict.

**Comment by adamjstewart** [comment] 2022-11-04 21:34
Fixed in #33716.

The concretization bug was due to rust and how Spack sorts versions. Basically:

1. `py-transformers` depends on `py-tokenizers`
2. `py-tokenizers` depends on `rust@nightly` (in older versions)
3. `rust@:1.43` depends on `python@2.7:2.8`
4. Spack sorts `nightly` as older than all stable release versions
5. `py-transformers` (and many other packages in the DAG) depends on Python 3+

I've talked to @AndrewGaspar about this before but it's really hard to solve this issue. "nightly" in rust-land doesn't mean newest, it means an unstable release. You could have a version of nightly from years ago that works, while a stable release from last week wouldn't work. So we can't just sort "nightly" as newer than all stable releases either. 

Luckily, the latest version of tokenizers works with stable rust, so this version requirement is no longer necessary. I removed the `@nightly` requirement from the package, which means older versions may break but all versions now concretize. If anyone wants to build older tokenizers, they just need to manually install rust@nightly beforehand.

I also added py-transformers to CI so we can ensure that it continues to build correctly.

**Comment by cameronrutherford** [comment] 2022-11-04 23:50
Amazing news! Thanks, @adamjstewart. I know concretizer is an NP hard problem, and so I wish I could have been more useful in tracking this down.

I am much more adept ad debugging packages I maintain like ExaGO and HiOp

**Comment by adamjstewart** [comment] 2022-11-04 23:59
I basically just started commenting out dependencies (in a binary search) until things magically concretized, that usually gives away what the problem is.

**Closed as completed** 2022-11-05 17:38 UTC
Labels: bug, concretization, triage
