### ISSUE TITLE
Build issue: py-pip can't find spec `python`

### ISSUE THREAD

**Issue by kwryankrattiger** [LLNL/spack#28578] opened 2022-01-25 02:03 UTC
### Steps to reproduce the issue

The command.

```console
spack install -j 4 ascent+shared+mpi~openmp+python~vtkh~dray~fortran %gcc@11.2.0
```

The error with --verbose --stacktrace on:
```console
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/ncurses-6.2-34rtfejtbumggcwiinlhmhohvlsh5xer
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/berkeley-db-18.1.40-bibpdt762rgu2lpume4kfeg5bsxelypm
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/libiconv-1.16-dvmasuijosalk4slnymrt3dw37o537in
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/zlib-1.2.11-sudngp7k3vr7lknscbfii2n2rcrubghg
lib/spack/spack/installer.py:323 ==> mpich@8.1.10-spock : has external module in ['craype-network-ofi', 'libfabric/1.11.0.4.75', 'cray-mpich/8.1.10']
[+] /opt/cray/pe/mpich/8.1.10/gtl (external mpich-8.1.10-spock-mlqdr2ygrffdrrki5cj2jhglqbykm4tk)
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/pkgconf-1.8.0-56u5dumncfbiit2usbym4tgcxhltcnv4
lib/spack/spack/installer.py:323 ==> py-mpi4py@3.0.3-spock : has external module in ['cray-python/3.8.5.1']
[+] /opt/cray/pe/python/3.8.5.1 (external py-mpi4py-3.0.3-spock-2dfvre2mtkhpvd4to7x6nscciq4ymjem)
lib/spack/spack/installer.py:323 ==> py-numpy@1.18.2-spock : has external module in ['cray-python/3.8.5.1']
[+] /opt/cray/pe/python/3.8.5.1 (external py-numpy-1.18.2-spock-t7rn4ut5gxfqawyxrweu6upkboonzod3)
lib/spack/spack/installer.py:323 ==> python@3.8.5.1-spock : has external module in ['cray-python/3.8.5.1']
[+] /opt/cray/pe/python/3.9.4.1 (external python-3.8.5.1-spock-xh5zbpneaenl76ontqaglulu5thifzgp)
lib/spack/spack/installer.py:323 ==> py-pip@20.1.1-spock : has external module in ['cray-python/3.8.5.1']
[+] /opt/cray/pe/python/3.8.5.1 (external py-pip-20.1.1-spock-r3lqii2opu2brxzlncvz57ebfl44enus)
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/readline-8.1-e5rezb2rtanzq3tt3nslenepbdjfznnf
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/diffutils-3.8-l75huvldatvdf3kbcxju7n2p76l4ndaq
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/gdbm-1.19-u4663v5sjkczci4mjwidnyjwjamtbgco
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/bzip2-1.0.8-okqitxvyrdezbkbdkdfeifyrjjf5qrdo
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/perl-5.34.0-scze5mv6tig5zqtufb423yxxd2pmbjgw
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/openssl-1.1.1m-rrr5ke5oqfoqwyvtijwka7b5or4eu5lq
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/cmake-3.22.1-sxug24tr2ejimmgj4hl7qhbuogebpy6y
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/hdf5-1.8.22-6k56s3ksovqz7jefeswclzhcqvpe4nc4
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/metis-5.1.0-nmtzjo4st4pqsnzuqctlt6ymcxtntxxk
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/parmetis-4.0.3-og7hwxmk6xewona563umboohitoe74rq
[+] /gpfs/alpine/csc444/scratch/rkratt/opt/spack/cray-sles15-zen2/gcc-11.2.0/conduit-0.7.2-kq52cevkkp6a6uptlxetlco74cuenfid
lib/spack/spack/installer.py:1160 ==> Installing ascent-0.7.1-trxhsymh5qi7e5wskcuxokggmgdie3bz
lib/spack/spack/installer.py:286 ==> No binary for ascent-0.7.1-trxhsymh5qi7e5wskcuxokggmgdie3bz found: installing from source
lib/spack/spack/error.py:54 ==> Error: KeyError: 'No spec with name python in py-pip@20.1.1-spock%gcc@11.2.0 arch=cray-sles15-zen2'

/autofs/nccs-svm1_home1/rkratt/repos/spack/var/spack/repos/builtin/packages/py-pip/package.py:53, in setup_dependent_package:
         52    def setup_dependent_package(self, module, dependent_spec):
  >>     53        pip = self.spec['python'].command
         54        pip.add_default_arg('-m')
         55        pip.add_default_arg('pip')
         56        setattr(module, 'pip', pip)

```

### Information on your system

On Spock@ORNL

packages.yaml (abridged)
```yaml
packages:
  py-pip:
    externals:
    - spec: py-pip@20.1.1-spock
      modules:
        - cray-python/3.8.5.1
    buildable: false
  python:
    externals:
    - spec: python@3.8.5.1-spock
      modules:
      - cray-python/3.8.5.1
      prefix: /opt/cray/pe/python/3.9.4.1
    buildable: false
```

I am on a custom branch for testing a few different changes on spock. The relevant changes for building conduit at a minimum are [here](https://github.com/kwryankrattiger/spack/tree/conduit_no_check_fc) and all of the changes on this are [here](https://github.com/kwryankrattiger/spack/tree/spock_test).

```console
* **Spack:** 0.17.1-922-8752c39b47
* **Python:** 3.6.13
* **Platform:** cray-sles15-zen2
* **Concretizer:** clingo
```

### Additional information

[ascent-build-out.txt](https://github.com/spack/spack/files/7930049/ascent-build-out.txt)
[ascent-build-env.txt](https://github.com/spack/spack/files/7930050/ascent-build-env.txt)

@adamjstewart 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment] 2022-01-25 02:13
It looks like this is a duplicate of #9149. For now, you can't have `py-pip` registered as an external package. If you remove that, then everything should build fine.

**Closed as completed by adamjstewart** 2022-01-25 02:13 UTC
Labels: build-error
