### ISSUE TITLE
Cannot use installed package if the recipe was later deleted

### ISSUE THREAD

**Issue by myan-rarcellino-nnl** [LLNL/spack#29859] opened 2022-04-03 03:01 UTC
### Steps to reproduce

#18322  deleted the `uuid` package from the package repo. This seems like an interesting change if a requirement exists that a recipe must exist in the package repo in order to use an installed package. In my test example the general flow is to checkout `v0.16.0`, install `uuid`, checkout `v0.17.0`, and try to use `uuid`.

```bash
git clone https://github.com/spack/spack
cd spack
git checkout tags/v0.16.0
. share/spack/setup-env.sh
spack install uuid
git checkout tags/v0.17.0
spack --debug --stacktrace load uuid
```

Is the expectation that a software stack installed with Spack v0.16.0 cannot be upgraded to v0.17.0? Is uninstalling `uuid` and all dependent packages the only solution?

### Error message

```console
lib/spack/spack/cmd/__init__.py:123 ==> [2022-04-03-01:57:06.594695] Imported load from built-in commands
lib/spack/spack/cmd/__init__.py:123 ==> [2022-04-03-01:57:06.595643] Imported load from built-in commands
lib/spack/spack/config.py:1007 ==> [2022-04-03-01:57:06.597481] Reading config file /opt/test/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1007 ==> [2022-04-03-01:57:06.623106] Reading config file /opt/test/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/database.py:374 ==> [2022-04-03-01:57:06.633618] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:378 ==> [2022-04-03-01:57:06.633787] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1007 ==> [2022-04-03-01:57:06.635767] Reading config file /opt/test/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:1007 ==> [2022-04-03-01:57:06.648610] Reading config file /opt/test/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/config.py:1007 ==> [2022-04-03-01:57:06.672406] Reading config file /opt/test/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/main.py:884 ==> [2022-04-03-01:57:06.675568] UnknownPackageError: Package 'uuid' not found in repository '/opt/test/spack/var/spack/repos/builtin'
lib/spack/spack/error.py:54 ==> [2022-04-03-01:57:06.675751] Error: Package 'uuid' not found in repository '/opt/test/spack/var/spack/repos/builtin'
Traceback (most recent call last):
  File "/opt/test/spack/lib/spack/spack/main.py", line 881, in main
    return _main(argv)
  File "/opt/test/spack/lib/spack/spack/main.py", line 864, in _main
    return _invoke_command(command, parser, args, unknown)
  File "/opt/test/spack/lib/spack/spack/main.py", line 534, in _invoke_command
    return_val = command(parser, args)
  File "/opt/test/spack/lib/spack/spack/cmd/load.py", line 94, in load
    env_mod.extend(uenv.environment_modifications_for_spec(spec))
  File "/opt/test/spack/lib/spack/spack/user_environment.py", line 94, in environment_modifications_for_spec
    spack.build_environment.set_module_variables_for_package(spec.package)
  File "/opt/test/spack/lib/spack/spack/spec.py", line 1297, in package
    self._package = spack.repo.get(self)
  File "/opt/test/spack/lib/spack/spack/repo.py", line 1215, in get
    return path.get(spec)
  File "/opt/test/spack/lib/spack/spack/repo.py", line 91, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/opt/test/spack/lib/spack/spack/repo.py", line 643, in get
    return self.repo_for_pkg(spec).get(spec)
  File "/opt/test/spack/lib/spack/spack/repo.py", line 91, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/opt/test/spack/lib/spack/spack/repo.py", line 895, in get
    package_class = self.get_pkg_class(spec.name)
  File "/opt/test/spack/lib/spack/spack/repo.py", line 1107, in get_pkg_class
    module = self._get_pkg_module(pkg_name)
  File "/opt/test/spack/lib/spack/spack/repo.py", line 1067, in _get_pkg_module
    raise UnknownPackageError(pkg_name, self)
spack.repo.UnknownPackageError: Package 'uuid' not found in repository '/opt/test/spack/var/spack/repos/builtin'
```

### Information on your system

* **Spack:** 0.17.0
* **Python:** 3.6.8
* **Platform:** linux-centos7-x86_64_v3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment] 2022-04-03 16:51
I also often encounter this problem when creating and installing a package on a new branch, then switching back to develop. Luckily my issue is only encountered by developers who know what they're doing, but the issue reported here is much more serious and easily encountered if you follow best practice and update Spack often.

@alalazo @tgamblin

**Comment by alalazo** [comment] 2023-05-02 22:10
Duplicate of #13597

**Comment by alalazo** [comment] 2023-07-10 12:09
Closing as duplicate. Let's continue the discussion in #13597

**Closed as not planned by alalazo** 2023-07-10 12:09 UTC
Labels: bug, duplicate
