### ISSUE TITLE
Slack channel sign-up app error

### ISSUE THREAD

**Issue by vdikan** [LLNL/spack#17527] opened 2020-07-14 13:53 UTC
Reintroduction of  [#6799](https://github.com/spack/spack/issues/6799) : heroku app error renders instead of sign-up for slack.

**Comment by vdikan** [comment] 2020-07-14 14:48
Sorry, I overlooked https://github.com/spack/spack/issues/17513
which is about same issue

**Comment by adamjstewart** [comment] 2020-07-15 02:15
Closing as a duplicate of #17513, let's continue the discussion there

**Closed as completed by adamjstewart** 2020-07-15 02:15 UTC
Labels: bug, duplicate, triage
