### ISSUE TITLE
Hashes of nodes change with a variant of the root node for exactly the same DAG

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#1457] opened 2016-08-05 13:41 UTC
If one diffs the concretized specs of `spack spec dealii@develop` and `spack spec dealii@develop~python+mpi ^boost+python` there is a zero difference apart from the `python` variant of the root node (`dealii`) -- this is expected and a desired behaviour. In other words dags should be identical and so their hashes.

However after successfully installing 

```
$ spack install dealii@develop
==> dealii is already installed in /Users/davydden/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/dealii-develop-if6ztag7fopoe7vcppk2sidqe44j7u7b
```

 the second build actually starts with re-installing `hwloc` and then, supposedly, `openmpi` and the rest:

```
$ spack install dealii@develop~python+mpi ^boost+python
==> Installing dealii
==> metis is already installed in /Users/davydden/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/metis-5.1.0-sawhq7id7lig7enw7qhexuj423xk6eq7
==> Installing trilinos
==> Installing superlu-dist
==> Installing openmpi
==> Installing hwloc
==> libpciaccess is already installed in /Users/davydden/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/libpciaccess-0.13.4-plgdrjeje7tk63kv65wuhptmi5rhbugr
==> Can not find version 1.11.3 in url_list
==> Already downloaded /Users/davydden/spack/var/spack/stage/hwloc-1.11.3-jtkwa4li2oxkedg6j4fc2p2in2tlf3hb/hwloc-1.11.3.tar.gz
==> Already staged hwloc-1.11.3-jtkwa4li2oxkedg6j4fc2p2in2tlf3hb in /Users/davydden/spack/var/spack/stage/hwloc-1.11.3-jtkwa4li2oxkedg6j4fc2p2in2tlf3hb
==> No patches needed for hwloc
==> Building hwloc
```

Something is certainly wrong here. 

Could it be that hashes are dependent on **normalized** specs, which are different here:

```
Input spec
------------------------------
  dealii@develop+mpi~python
      ^boost+python

Normalized
------------------------------
  dealii@develop+mpi~python
      ^astyle@2.04
      ^blas
      ^boost@1.59.0:+iostreams+mpi+python+serialization+system+thread
          ^bzip2
          ^mpi
          ^python
              ^ncurses
              ^openssl
                  ^zlib
              ^readline
              ^sqlite
      ^cmake
      ^lapack
      ^muparser
      ^numdiff
          ^gettext
      ^suite-sparse
      ^tbb
```

vs

```
Input spec
------------------------------
  dealii@develop

Normalized
------------------------------
  dealii@develop
      ^astyle@2.04
      ^blas
      ^bzip2
      ^cmake
      ^lapack
      ^muparser
      ^numdiff
          ^gettext
      ^suite-sparse
      ^tbb
      ^zlib
```

Below is the Conretized specs (again, the only difference between the two is `~python` vs `+python` of the root node):

```
Concretized
------------------------------
  dealii@develop%clang@7.3.0-apple+arpack~doc+gsl+hdf5+metis+mpi+netcdf+oce+p4est+petsc~python+slepc+trilinos arch=darwin-elcapitan-x86_64
      ^arpack-ng@3.4.0%clang@7.3.0-apple+mpi+shared arch=darwin-elcapitan-x86_64
          ^cmake@3.6.0%clang@7.3.0-apple~doc+ncurses+openssl~qt arch=darwin-elcapitan-x86_64
              ^ncurses@6.0%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
              ^openssl@1.0.2h%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
                  ^zlib@1.2.8%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
          ^openblas@0.2.18%clang@7.3.0-apple+fpic~openmp+shared arch=darwin-elcapitan-x86_64
          ^openmpi@2.0.0%clang@7.3.0-apple~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=darwin-elcapitan-x86_64
              ^hwloc@1.11.3%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
                  ^libpciaccess@0.13.4%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
                      ^libtool@2.4.6%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
                          ^m4@1.4.17%clang@7.3.0-apple+sigsegv arch=darwin-elcapitan-x86_64
                              ^libsigsegv@2.10%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
      ^astyle@2.04%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
      ^boost@1.61.0%clang@7.3.0-apple+atomic+chrono+date_time~debug+filesystem~graph~icu_support+iostreams+locale+log+math+mpi+multithreaded+program_options+python+random+regex+serialization+shared+signals+singlethreaded+system+test+thread+timer+wave arch=darwin-elcapitan-x86_64
          ^bzip2@1.0.6%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
          ^python@2.7.12%clang@7.3.0-apple~tk~ucs4 arch=darwin-elcapitan-x86_64
              ^readline@6.3%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
              ^sqlite@3.8.5%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
      ^gsl@2.1%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
      ^hdf5@1.10.0-patch1%clang@7.3.0-apple+cxx~debug+fortran+mpi+shared~szip~threadsafe arch=darwin-elcapitan-x86_64
      ^metis@5.1.0%clang@7.3.0-apple~debug~gdb~idx64~real64+shared arch=darwin-elcapitan-x86_64
      ^muparser@2.2.5%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
      ^netcdf@4.4.1%clang@7.3.0-apple~hdf4+mpi arch=darwin-elcapitan-x86_64
          ^curl@7.49.1%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
      ^netcdf-cxx@4.2%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
      ^numdiff@5.8.1%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
          ^gettext@0.19.8.1%clang@7.3.0-apple+bzip2+curses+git~libunistring+libxml2+tar+xz arch=darwin-elcapitan-x86_64
              ^libxml2@2.9.2%clang@7.3.0-apple~python arch=darwin-elcapitan-x86_64
                  ^xz@5.2.2%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
              ^tar@1.28%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
      ^oce@0.17.2%clang@7.3.0-apple+tbb arch=darwin-elcapitan-x86_64
          ^tbb@4.4.4%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
      ^p4est@1.1%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
          ^autoconf@2.69%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
          ^automake@1.15%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
          ^lua@5.3.2%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
      ^petsc@3.7.2%clang@7.3.0-apple+boost~complex~debug+double+hdf5+hypre+metis+mpi+mumps+shared+superlu-dist arch=darwin-elcapitan-x86_64
          ^hypre@2.10.1%clang@7.3.0-apple~internal-superlu~shared arch=darwin-elcapitan-x86_64
          ^mumps@5.0.1%clang@7.3.0-apple+complex+double+float~idx64~metis+mpi~parmetis~ptscotch~scotch+shared arch=darwin-elcapitan-x86_64
              ^netlib-scalapack@2.0.2%clang@7.3.0-apple~fpic+shared arch=darwin-elcapitan-x86_64
          ^parmetis@4.0.3%clang@7.3.0-apple~debug~gdb+shared arch=darwin-elcapitan-x86_64
          ^superlu-dist@5.0.0%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
      ^slepc@3.7.1%clang@7.3.0-apple+arpack arch=darwin-elcapitan-x86_64
      ^suite-sparse@4.5.3%clang@7.3.0-apple+tbb arch=darwin-elcapitan-x86_64
      ^trilinos@12.6.4%clang@7.3.0-apple+boost~debug+hdf5+hypre+metis+mumps~python+shared+suite-sparse+superlu-dist arch=darwin-elcapitan-x86_64
          ^glm@0.9.7.1%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
          ^matio@1.5.2%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
          ^swig@3.0.10%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
              ^pcre@8.38%clang@7.3.0-apple+utf arch=darwin-elcapitan-x86_64
```

**Comment by davydden** [comment] 2016-08-05 13:42
could be similar to https://github.com/LLNL/spack/issues/1055

**Comment by davydden** [comment] 2016-08-10 06:36
double checked that the issue is still there on a095fd517f34c9570fd930a7b4819d607593785f with a clean installation of spack.

**Comment by becker33** [comment] 2016-08-10 17:03
Can you check whether #1409 resolves this issue?

**Comment by adamjstewart** [comment] 2016-08-10 17:08
I'm seeing a very similar problem to this. If I install qt and then install py-pyside, it uses the already installed qt. However, if I add additional dependencies on libxml2 and libxslt to py-pyside (with no version constraints), Spack tries to reinstall qt. Normally I wouldn't care, but qt takes well over an hour to build.

@becker33 I'll try #1409 right now.

**Comment by davydden** [comment] 2016-08-10 19:22
@becker33 i tested by `s.tree(format='$_$@$%@+$+$=$#')` and the hashes are still different. I would give it another try when #1409 is merged, but so far it seems that it does not solve the problem.

**Comment by mdavezac** [comment] 2016-08-11 10:29
When I try it on my machine, I get that the first spec depends on `mvapich2`, whereas the second depends on `openmpi`. I have not set defaults for which mpi version to go for. Could it be that when defaults are not specified, the concretize methods chooses virtual packages from an unordered container?

**Comment by davydden** [comment] 2016-08-11 10:39
@mdavezac maybe... I did not notice this as i do have default virtual packages set:
```
packages:
  all:
    compiler: [clang, gcc]
    providers:
      mpi: [openmpi]
      blas: [openblas]
      lapack: [openblas]
```

**Comment by adamjstewart** [comment] 2016-08-11 14:34
> When I try it on my machine, I get that the first spec depends on mvapich2, whereas the second depends on openmpi. I have not set defaults for which mpi version to go for. Could it be that when defaults are not specified, the concretize methods chooses virtual packages from an unordered container?

@mdavezac I don't think that's the case. See `etc/spack/defaults/packages.yaml`. That's where all of the defaults are set for Spack. It should be taking the first MPI found there.

**Comment by becker33** [comment] 2016-08-11 15:34
The difference between the two specs is in the hash of the libpciaccess dependency of openmpi. I have not been able to track it down any further so far, but I'm working on it.

@mdavezac was your testing with #1409 or without?

**Comment by davydden** [comment] 2016-08-11 15:37
@becker33 thanks for looking at it. I tried to create a smaller unit test with some mockup packages, but was not able to reproduce the problem.

**Comment by becker33** [comment] 2016-08-11 18:29
Update: Something is clobbering the deptypes for libpciaccess when concretizing dealii@develop, but not when concretizing dealii@develop~python+mpi^boost+python. The deptypes for libpciaccess' dependency on libtool should be 'build', 'link', but it's getting set to just 'build'.

@mathstuf do you have any idea why the deptype would be set to just build even thought the depends_on statement has the default ('build, link')?

I'll keep looking.

**Comment by mathstuf** [comment] 2016-08-11 19:29
Hook into `Spec._add_dependency` and raise an exception based on the inputs; it's where I got lots of information out.

**Comment by becker33** [comment] 2016-08-11 23:00
It looks like the current _constrain_dependencies method doesn't properly union the sets of deptypes for dependencies, so we're getting different behavior depending on which dependant of libtool is evaluated first. p4est has a build dependency on libtool, and hwloc has a build and link dependency on libtool.

In this case, hwloc's dependency should probably be a build type, but that won't be the case in every situation so this is worth continuing to work on. I'm currently trying to figure out what needs to change to make it work.

This could apply to run and link vs run only dependencies too, so the separate concretization of build dependencies work that @mathstuf has been working on won't solve this entirely, only make us less likely to encounter it.

If anyone else was thinking about working on this: I have not been able to create a simpler reproducer so far.

**Comment by davydden** [comment] 2016-08-12 07:00
@becker33
wow, that's quite a hidden bug! 

I assume you mean 
```
openmpi [build,link] ->hwloc [build,link] ->libpciaccess [build,link] -> libtool
```
vs 
```
p4est [build] -> libtool
  \
    [build, link] -> openmpi
```

I was not aware that hashes change with dependency type of edges in DAG. 

If I understand you correct, in this particular case the expected behaviour is that `hwloc` should always (wrongly) have `build`+`link` dependency on `libtool` through `libpciaccess`. This however got screwed up somewhere due to the presence of `build`-only dependency on `libtool` in `p4est`.

**Comment by mdavezac** [comment] 2016-08-12 14:31
@becker33, I've tried both, I think, with similar results

**Comment by becker33** [comment] 2016-08-15 17:24
@davydden Yes, that is precisely what I was saying. The "somewhere" is the part of the bug that I haven't been able to track down yet.

**Comment by tgamblin** [comment] 2016-09-02 14:35
Fixed by #1409, #1692

**Comment by davydden** [comment] 2016-09-02 14:57
@tgamblin are you sure it's fixed? The issue was with different types of dependencies for the same package within a graph, see my comment https://github.com/LLNL/spack/issues/1457#issuecomment-239375286

**Comment by adamhough** [comment] 2016-09-21 22:57
I have multi versions on ncurses 6.0 being installed currently as it is not detecting the old versions.  could this be caused by a spack DB issue?

**Comment by tgamblin** [comment] 2016-09-21 23:00
This wouldn't be caused by a DB issue, especially if you see the old versions in the DB.  This is caused because Spack (still) does not do very aggressive spec matching on installed packages.  This is being worked on.  For now you *should* be able to do this if you want to face spack to reuse soemthing:

```python
    spack install foo ^/abc123
```

where `abc123` is the hash prefix (from, e.g., `spack find -l`) of something installed.

**Comment by tgamblin** [comment] 2016-12-05 18:25
@davydden: do you still see this?  Do you have a reproducer?

**Comment by davydden** [comment] 2016-12-06 14:15
@tgamblin 

This should still be the case, to trigger you need to patch `hwloc` to have different dependency type on libtool and then check hashes of `dealii@develop~python+mpi ^boost+python` and `dealii@develop`:
```
diff --git a/var/spack/repos/builtin/packages/libpciaccess/package.py b/var/spack/repos/builtin/packages/libpciaccess/package.py
index f4a3cf7..84036c7 100644
--- a/var/spack/repos/builtin/packages/libpciaccess/package.py
+++ b/var/spack/repos/builtin/packages/libpciaccess/package.py
@@ -33,7 +33,7 @@ class Libpciaccess(Package):

     version('0.13.4', 'cc1fad87da60682af1d5fa43a5da45a4')

-    depends_on('libtool', type='build')
+    depends_on('libtool')
     depends_on('pkg-config@0.9.0:', type='build')
     depends_on('util-macros', type='build')
```
The hashes of `hwloc` should be different. The latest clues are https://github.com/LLNL/spack/issues/1457#issuecomment-239318984

**Comment by alalazo** [comment] 2016-12-06 17:34
@tgamblin @adamjstewart I may have one originating from a patological case in #2495 where the graph is no more acyclic:
```console
$ spack spec -L tk+X ^python+tk
Input spec
--------------------------------
igqtbijwwjckc2obcbkbqewoix6gcqum  tk+X
mkgomsqch2uzthfr7vrzrbfrdcd3nap4      ^python+tk

Normalized
--------------------------------
nqcqdbwravnmdjicgovy6a6r7b27oxmq  tk+X
of4t2uvqpzfsog4yttm2rsxjxsmq5zy7      ^libx11
cwrmue2zsxrbdvkqnuzdxjwdmrollkjh          ^inputproto
4s3wwngh7tx5mluortkkabzojnmilefa              ^pkg-config@0.9.0:
v5snlvcf7q2hrh3ru4plrzmlqgjzddoy              ^util-macros
skzsdadwmw5gnatyewqxdavofta66lwh          ^kbproto
xs7d2kfjac6mfljuie2somthp3dsb2gz          ^libxcb@1.1.92:
mxmbsld4kfgks3a7ri5xnvm6lgjid7zd              ^libpthread-stubs
uxhnmsdxh7y4hcnpzzwt2wbkhmvhn2bw              ^libxau@0.99.2:
yxi4d3tdrdwnh7jjyzied77j4tegqot4                  ^xproto@7.0.17:
wmindbtilhg46q2ivscumprzhow7uqjr              ^libxdmcp
mhouflo5wuubbd4zjv5dd3mdmn7vywdp              ^python@2:2.8+tk
5gd5s7mcugw54n62esdlsbhxyzqoq3ar                  ^bzip2
fvevxql3m6x5m2eogk4opppf7kmavxbz                  ^ncurses
hl37cq753uzoyapg4t7lvj5fxse4fbwi                  ^openssl
ctlbt62cqefrv3cepz3khie5echpjnf3                      ^zlib
xry7gicfijcitxjzspnt74woeo5e44xl                  ^readline
6o2mntstpo5ix7ilhtvyv5m6jz33zfon                  ^sqlite
4dvsiefi7zqdgl2b6kh6x6x77v3fpu75                  ^tcl
uhgtmsbglnd4yihholdkfuyi2xcvicad                  ^tk
uixklfwoxolgbga7htc2ij7mhra5ypbs              ^xcb-proto
r3uo7nav3u6dgi6mkjh6cs26c4r2wzib          ^xextproto
3raclz5wrc6jpdgqoljigy6naftlsm7t          ^xtrans

Concretized
--------------------------------
bznkl47xfdajnxey6egc2wi7erazlx77  tk@8.6.5%gcc@4.8+X arch=linux-ubuntu14-x86_64
4wjnfqxlbfanhq27lj5mo74imhm2p6gy      ^libx11@1.6.3%gcc@4.8 arch=linux-ubuntu14-x86_64
v4rriv4sntqbf4lzp7yxnvhceyxmqgcb          ^inputproto@2.3.2%gcc@4.8 arch=linux-ubuntu14-x86_64
6eyt3nwho47i7zm734xeyvllnp5wukrf              ^pkg-config@0.29.1%gcc@4.8+internal_glib arch=linux-ubuntu14-x86_64
c4heqyf7lcml66i3utgc3boun5upeu3v              ^util-macros@1.19.0%gcc@4.8 arch=linux-ubuntu14-x86_64
s2m64n234igrkjmhh4bbqdvjvquud7b2          ^kbproto@1.0.7%gcc@4.8 arch=linux-ubuntu14-x86_64
hxvaymexq5k4oyzehtgdmiqdqfakg25d          ^libxcb@1.12%gcc@4.8 arch=linux-ubuntu14-x86_64
46bdihu7b7m67sh4oukafolcayf4p2np              ^libpthread-stubs@0.3%gcc@4.8 arch=linux-ubuntu14-x86_64
lxz6mpvldlux7tqa43nzez5woxrsvzk6              ^libxau@1.0.8%gcc@4.8 arch=linux-ubuntu14-x86_64
yrm4rvz5s7pyxs5tdph5cnpyrtknv2st                  ^xproto@7.0.29%gcc@4.8 arch=linux-ubuntu14-x86_64
wkqotnmnpjqmvvce6fgpqj2vjeqi72bi              ^libxdmcp@1.1.2%gcc@4.8 arch=linux-ubuntu14-x86_64
fpyfuo2df5j4iwkedav6wvlhmgoxbu6c              ^python@2.7.12%gcc@4.8+tk~ucs4 arch=linux-ubuntu14-x86_64
t34nstuoxy7cn6njir2o4isrgaaflrqy                  ^bzip2@1.0.6%gcc@4.8 arch=linux-ubuntu14-x86_64
o4lmbzigzkr65qhlulxfcmjojnh2ghzh                  ^ncurses@6.0%gcc@4.8 arch=linux-ubuntu14-x86_64
5yabvumye5h4z6ebcy2bthc6w5aeq54h                  ^openssl@1.0.2j%gcc@4.8 arch=linux-ubuntu14-x86_64
td4mhtsaaopiu76mxuxdy3d72smgn2gk                      ^zlib@1.2.8%gcc@4.8+pic arch=linux-ubuntu14-x86_64
pihnz5pmtypzffsenfizop2rhlbtdxvo                  ^readline@6.3%gcc@4.8 arch=linux-ubuntu14-x86_64
slxpiaz4tdbolnjvms73r6s4vth35ldp                  ^sqlite@3.8.5%gcc@4.8 arch=linux-ubuntu14-x86_64
yj64lflmhw7pvbua5iaufdc27aw6isz4                  ^tcl@8.6.5%gcc@4.8 arch=linux-ubuntu14-x86_64
qapjzpjdxko3v43kczshvnnolrrknfbs                  ^tk@8.6.5%gcc@4.8+X arch=linux-ubuntu14-x86_64
f2t5id33pukkawtfoib33z7tnjeierx3              ^xcb-proto@1.12%gcc@4.8 arch=linux-ubuntu14-x86_64
maixfrbl7djpa2whe2af4td62yhgwllc          ^xextproto@7.3.0%gcc@4.8 arch=linux-ubuntu14-x86_64
feuuqlxpvrertu7zf4givrkaugpafryx          ^xtrans@1.3.5%gcc@4.8 arch=linux-ubuntu14-x86_64
```
Check the concretized `tk`: there are two version of it in the DAG which look like they are identical to one other, just the hashes change.

Another funny thing is that this command completes because the dependency on python is of `type=build` and is treated differently (and incorrectly I think). 

If you start the traversing the non acyclic graph from python it blows up as shown in #2495 because in that case `python` is not of `type=build` and thus it does not break the infinite traversal.

**Comment by davydden** [comment] 2016-12-23 10:31
@tgamblin i just double checked that the issue is still there, I created a separate branch which triggers is, see https://github.com/davydden/spack/commit/f4ca2e74520e4ff7ee0907050f5fd69d0111f0d3

**Comment by tgamblin** [comment] 2016-12-23 16:30
I have a fix for this --- finishing up getting all the tests working with the PR.  

This is caused because of some bugs introduced when deptypes were implemented.  Specifcally there's a routine that "flattens" the dependencies in the DAG and gives you a dict of single node specs keyed by name.  That was adapted to give you a dict of DependencySpecs, which are basically edges in the DAG, but it assumes each package is depended on only one way.  This stuff has been rewritten to use `traverse(cover='edges')` instead of flattening.

**Comment by davydden** [comment] 2016-12-23 16:34
Sounds great!

**Comment by tgamblin** [comment] 2016-12-25 21:20
Ok here are specs for @davydden's reproducer, without and with the fix.

## Without fix
```console
$ spack spec -lt dealii@develop+python+mpi
...
rzcljax  [   ]  dealii@develop%clang@7.0.2-apple+arpack~doc+gsl+hdf5+metis+mpi+netcdf+oce+p4est+petsc+python+slepc+trilinos arch=darwin-elcapitan-x86_64
...
jtzpkon  [bl ] << hash diff     ^libpciaccess@0.13.4%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
kzmnsf4  [bl ] << deptype diff      ^libtool@2.4.6%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
unwqvpp  [b  ]                          ^m4@1.4.17%clang@7.0.2-apple+sigsegv arch=darwin-elcapitan-x86_64
zilbzv7  [bl ]                              ^libsigsegv@2.10%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
ts5ta54  [b  ]                      ^pkg-config@0.29.1%clang@7.0.2-apple+internal_glib arch=darwin-elcapitan-x86_64
podueew  [b  ]                      ^util-macros@1.19.0%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
...

$ spack spec -lt dealii@develop
...
64g7366  [   ]  dealii@develop%clang@7.0.2-apple+arpack~doc+gsl+hdf5+metis+mpi+netcdf+oce+p4est+petsc+python+slepc+trilinos arch=darwin-elcapitan-x86_64
...
osgk2ir  [bl ] << hash diff     ^libpciaccess@0.13.4%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
kzmnsf4  [b  ] << deptype diff      ^libtool@2.4.6%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
unwqvpp  [b  ]                          ^m4@1.4.17%clang@7.0.2-apple+sigsegv arch=darwin-elcapitan-x86_64
zilbzv7  [bl ]                              ^libsigsegv@2.10%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
ts5ta54  [b  ]                      ^pkg-config@0.29.1%clang@7.0.2-apple+internal_glib arch=darwin-elcapitan-x86_64
podueew  [b  ]                      ^util-macros@1.19.0%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
```

Notice that the two different command lines should result in the exact same DAG, but in one, `libpciaccess` has a build dependency on `libtool` and in the other it has `build` and `link` dependencies on `libtool`.  This is because `libool` is actually needed by several packages, and deptypes from one end up overwriting the deptypes from another.  So, `libpciaccess` ends up with a different hash, and so does `dealii`.

## With fix
```console
$ spack spec -lt dealii@develop+python+mpi
...
nhehtwy  [   ]  dealii@develop%clang@7.0.2-apple+arpack~doc+gsl+hdf5+metis+mpi+netcdf+oce+p4est+petsc+python+slepc+trilinos arch=darwin-elcapitan-x86_64
...
jtzpkon  [bl ]                  ^libpciaccess@0.13.4%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
kzmnsf4  [bl ]                      ^libtool@2.4.6%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
unwqvpp  [b  ]                          ^m4@1.4.17%clang@7.0.2-apple+sigsegv arch=darwin-elcapitan-x86_64
zilbzv7  [bl ]                              ^libsigsegv@2.10%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
ts5ta54  [b  ]                      ^pkg-config@0.29.1%clang@7.0.2-apple+internal_glib arch=darwin-elcapitan-x86_64
podueew  [b  ]                      ^util-macros@1.19.0%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
...

$ spack spec -lt dealii@develop
...
nhehtwy  [   ]  dealii@develop%clang@7.0.2-apple+arpack~doc+gsl+hdf5+metis+mpi+netcdf+oce+p4est+petsc+python+slepc+trilinos arch=darwin-elcapitan-x86_64
...
jtzpkon  [bl ]                  ^libpciaccess@0.13.4%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
kzmnsf4  [bl ]                      ^libtool@2.4.6%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
unwqvpp  [b  ]                          ^m4@1.4.17%clang@7.0.2-apple+sigsegv arch=darwin-elcapitan-x86_64
zilbzv7  [bl ]                              ^libsigsegv@2.10%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
ts5ta54  [b  ]                      ^pkg-config@0.29.1%clang@7.0.2-apple+internal_glib arch=darwin-elcapitan-x86_64
podueew  [b  ]                      ^util-macros@1.19.0%clang@7.0.2-apple arch=darwin-elcapitan-x86_64
...
```

Now the `libpciaccess hash is the same in both scenarios because the dependency types on `libtool` in the final DAG are the same.  If you run `spack spec -lt --cover=edges`  on these DAGs (I won't show it here) you'll see that all the libtools have the same hash but other packages only have a build dependency on it while `libpciaccess` has `build` and `link` dependencies on it.

**Closed** 2016-12-29 22:44 UTC
Labels: bug, hashes, needs-response, specs
