### ISSUE TITLE
Installation issue: How to install local source code package?

### ISSUE THREAD

**Issue by Bitllion** [LLNL/spack#22191] opened 2021-03-09 08:56 UTC
I optimized some programs of BLAS and used makefile to build them。If the source code is in the official warehouse, I can create an installation definition script through `spack create http://www.netlib.org/blas/blas-3.8.0.tgz` command, which is ok。But when I run `spack create /home/bit/blas-optimized-3.8.0.tgz`, it not work,the output like this:
```
spack create /home/bit/BLAS-3.8.0.tgz
==> This looks like a URL for BLAS
==> Found 1 version of blas:

  3.8.0  BLAS-3.8.0.tgz

==> Something failed on BLAS-3.8.0.tgz, skipping.  (All fetchers failed)
==> Error: Could not fetch any versions for blas
```

**Comment by adamjstewart** [comment] 2021-03-10 17:55
Duplicate of #2545

**Closed as completed by adamjstewart** 2021-03-10 17:55 UTC
Labels: duplicate, build-error
