### ISSUE TITLE
`spack unit-test`: recent test fails randomly

### ISSUE THREAD

**Issue by scheibelp** [LLNL/spack#32470] opened 2022-09-01 01:45 UTC
### Steps to reproduce

Rerun `SPACK_PYTHON=python2 SPACK_TEST_SOLVER=clingo spack unit-test -k "installed_externals_are_reused"`

It will fail sometimes and succeed other times. This means that all PRs have a random chance of failing CI.

* The test only actually runs when the concretizer is clingo, and otherwise skips
* I'm not yet sure if this also applies to Python 3 but will check that shortly and update here
  * Update: I get this failure about 20% of the time with Python 2 but got no failures in ~30 attempts with Python 3, so I think it is specific to Python 2

### Error message

When the test fails:

```
>       assert external2.dag_hash() != external1.dag_hash()
E       AssertionError: assert 'g2vslm4o3q5wru32m7akp4523tgsyhlt' != 'g2vslm4o3q5wru32m7akp4523tgsyhlt'
E        +  where 'g2vslm4o3q5wru32m7akp4523tgsyhlt' = <bound method Spec.dag_hash of changing@1.0%gcc@4.5.0+fee+foo arch=test-debian6-core2>()
E        +    where <bound method Spec.dag_hash of changing@1.0%gcc@4.5.0+fee+foo arch=test-debian6-core2> = changing@1.0%gcc@4.5.0+fee+foo arch=test-debian6-core2.dag_hash
E        +  and   'g2vslm4o3q5wru32m7akp4523tgsyhlt' = <bound method Spec.dag_hash of changing@1.0%gcc@4.5.0+fee+foo arch=test-debian6-core2>()
E        +    where <bound method Spec.dag_hash of changing@1.0%gcc@4.5.0+fee+foo arch=test-debian6-core2> = changing@1.0%gcc@4.5.0+fee+foo arch=test-debian6-core2.dag_hash
```

### Information on your system

https://github.com/spack/spack/commit/0c6e3188ac7ca780783bb36c0763c069cc0c1043 adds a test called `test_installed_externals_are_reused`

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by scheibelp** [comment] 2022-09-01 01:46
@alalazo @becker33 FYI as the writer/merger of the PR

**Comment by alalazo** [comment] 2022-09-01 06:32
Will investigate this, the only weird thing I notice is that:
```console
assert external2.dag_hash() != external1.dag_hash()
E       AssertionError: assert 'g2vslm4o3q5wru32m7akp4523tgsyhlt' != 'g2vslm4o3q5wru32m7akp4523tgsyhlt'
```
and copying the two strings:
```python
Python 2.7.18 (default, Jul  1 2022, 12:27:04) 
[GCC 9.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> s1 = 'g2vslm4o3q5wru32m7akp4523tgsyhlt' 
>>> s2 = 'g2vslm4o3q5wru32m7akp4523tgsyhlt'
>>> s1 == s2
True
```
I'll check later what type does `dag_hash()` return.

**Comment by alalazo** [comment] 2022-09-01 08:08
Might have to do with these lines:

https://github.com/spack/spack/blob/0df0b9a505d3731088a462c7fafadf6e162b1cc6/lib/spack/spack/util/hash.py#L13-L21

**Comment by alalazo** [comment] 2022-09-01 11:20
I was able to reproduce with:
```console
 % for ii in $(seq 10); do SPACK_PYTHON=python2 SPACK_TEST_SOLVER=clingo spack unit-test -k "installed_externals_are_reused" ; done
```
I can give it a try to remove the `sys.modules` hacking the fixture and see if it has anything to do with that.

**Comment by alalazo** [comment] 2022-09-02 08:21
As a quick mitigation we can mark the test at xfailing when Python 2.X is used

**Comment by alalazo** [comment] 2022-09-02 15:41
I added a print to the assert, and:
```
AssertionError: ext1: changing@1.0%gcc@4.5.0+fee+foo arch=test-debian6-core2, ext2: changing@1.0%gcc@4.5.0+fee+foo arch=test-debian6-core2
```
so it seems to be an error in the fixture, i.e. both have the `fee` variant that was supposed to be deleted a few lines above the assert.

**Comment by scheibelp** [comment] 2022-09-06 23:51
Interesting, I get a similar error for `installed_version_is_selected_only_for_reuse`:

(EDIT: this is also intermittent and also only for Python 2)

```
>       assert not new_root["changing"].satisfies("@1.0")
```

I assume an analog to https://github.com/spack/spack/pull/32526 would be suitable?

**Comment by scheibelp** [comment] 2022-09-21 17:47
See https://github.com/spack/spack/pull/32569

That should likely be replicated for all tests using the `repo_with_changing_recipe` fixture.

**Comment by alalazo** [comment] 2023-04-07 12:57
Closing since we don't support running under Python 2 anymore

**Closed as not planned by alalazo** 2023-04-07 12:57 UTC
Labels: bug, impact-low
