### ISSUE TITLE
Error after ctrl-c or fail in build

### ISSUE THREAD

**Issue by Exteris** [LLNL/spack#1410] opened 2016-08-01 12:58 UTC
Hi!

I'm just trying spack for the first time, to package a few things that I will need in my code.
One of the package.py files I'm making contained an error, and now when I try to install it again I'm getting this message:

 python2 spack install pfunit
==> Installing pfunit
==> Error: Specs openmpi@2.0.0%gcc@6.1.1~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=linux--x86_64^hwloc@1.11.3%gcc@6.1.1 arch=linux--x86_64^libpciaccess@0.13.4%gcc@6.1.1 arch=linux--x86_64^libtool@2.4.6%gcc@6.1.1 arch=linux--x86_64 and openmpi@2.0.0%gcc@6.1.1~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=linux-None-x86_64^hwloc@1.11.3%gcc@6.1.1 arch=linux-None-x86_64^libpciaccess@0.13.4%gcc@6.1.1 arch=linux-None-x86_64^libtool@2.4.6%gcc@6.1.1 arch=linux-None-x86_64 have the same SHA-1 prefix!

All of the dependencies seem to have installed OK, so I definitely did not expect this.
Do you have any ideas?

Thanks,
Daan

**Comment by adamjstewart** [comment] 2016-08-01 13:09
Do you already have OpenMPI installed or is it not installing for you?

**Comment by Exteris** [comment] 2016-08-01 13:11
openmpi is both installed on my system through pacman and installed successfully through spack.
Here are some more logs:

==> Successfully installed openmpi
  Fetch: 3.58s.  Build: 6m 6.86s.  Total: 6m 10.44s.
[+] /home/daan/source/spack/opt/spack/linux--x86_64/gcc-6.1.1/openmpi-2.0.0-ullrkmirvaoont7w34bz2rk75au5ynaq
==> Trying to fetch from file:///home/daan/source/spack/var/spack/cache/pfunit/pfunit-3.2.7.tar.gz
curl: (37) Couldn't open file /home/daan/source/spack/var/spack/cache/pfunit/pfunit-3.2.7.tar.gz
==> Fetching from file:///home/daan/source/spack/var/spack/cache/pfunit/pfunit-3.2.7.tar.gz failed.
==> Trying to fetch from http://downloads.sourceforge.net/project/pfunit/Source/pFUnit-3.2.7.tar.gz
######################################################################## 100.0%
==> Staging archive: /home/daan/source/spack/var/spack/stage/pfunit-3.2.7-376tgkbp2p7rct7wc6k4jknntvwzl7nc/pFUnit-3.2.7.tar.gz
==> Created stage in /home/daan/source/spack/var/spack/stage/pfunit-3.2.7-376tgkbp2p7rct7wc6k4jknntvwzl7nc
==> No patches needed for pfunit
==> Building pfunit
Traceback (most recent call last):
  File "/home/daan/source/spack/lib/spack/spack/build_environment.py", line 512, in fork
    function()
  File "/home/daan/source/spack/lib/spack/spack/package.py", line 997, in build_process
    self.install(self.spec, self.prefix)
  File "/home/daan/source/spack/var/spack/repos/builtin/packages/pfunit/package.py", line 52, in install
    os.environ['MPIF90'] = os.environ['FC']
NameError: global name 'os' is not defined
==> Error: Installation process had nonzero exit code : 256

ps. Is this the correct way of modifying the environment the build is taking place in?

**Comment by davydden** [comment] 2016-08-01 13:14
I think it's better if you create a PR with new packages you want to add and then people can comment on things which could be wrong. In any case,

```
os.environ['MPIF90'] = os.environ['FC']
```
does not look right to me.

You certainly miss include 

> NameError: global name 'os' is not defined

**Comment by adamjstewart** [comment] 2016-08-01 13:16
Yes, that's the proper way of modifying the environment. You just need to add `import os` to the top of the file. Can you do that and try running again? This seems unrelated to the originally posted error message.

**Comment by Exteris** [comment] 2016-08-01 13:19
@davydden @adamjstewart yes, that was quite a simple and stupid mistake. I am rerunning now.

rm -Rf opt/spack/linux--x86_64/ allowed me to build again, but now I have to rebuild openmpi also. 

Reproducing is simply a matter of running spack install openmpi (on a clean spack), pressing ctrl-c and then spack install openmpi again.

**Comment by adamjstewart** [comment] 2016-08-01 13:30
When are you pressing <kbd>Ctrl</kbd>-<kbd>C</kbd>? During the download or during the build? By the way, you may want to run `spack reindex`. Otherwise Spack can get confused when you delete stuff manually. It might think that some packages are installed even though they aren't.

**Comment by Exteris** [comment] 2016-08-01 13:39
During the build (but right now it's mostly my package script failing)
`spack reindex` does not help.

I think it might be related to arch=linux--x86_64 versus arch=linux-None-x86_64

**Comment by adamjstewart** [comment] 2016-08-01 13:43
Hmm, what linux distribution are you on? Are you on the latest Spack development branch? Did you happen to check out Spack before #561 was merged (June 16th)?

**Comment by Exteris** [comment] 2016-08-01 13:44
I'm on arch linux, checked out spack from git this morning.

**Comment by adamjstewart** [comment] 2016-08-01 13:45
Development branch or master branch?

**Comment by Exteris** [comment] 2016-08-01 13:45
As in http://software.llnl.gov/spack/getting_started.html#installation (so I'm on develop)

**Comment by adamjstewart** [comment] 2016-08-01 13:48
Maybe we are using two different means of determining the Linux distribution and one returns the empty string whereas the other returns None? I'm not familiar with how Spack determines distributions, but @becker33 or @tgamblin may be able to help. It sounds like Arch Linux isn't being detected properly.

**Comment by alalazo** [comment] 2016-10-25 07:06
@adamjstewart @tgamblin I can't reproduce this behavior anymore. If somebody else could confirm, I think the issue can be closed.

**Comment by tgamblin** [comment] 2016-10-27 18:57
This works for me.

**Closed by tgamblin** 2016-10-27 18:57 UTC
Labels: bug
