### ISSUE TITLE
When clause in version directive

### ISSUE THREAD

**Issue by birnbera** [LLNL/spack#24566] opened 2021-06-28 16:33 UTC
I’m working on updating the package definition for [Nextflow](https://github.com/nextflow-io/nextflow) (currently in house, but hopefully can share out soon). Nextflow uses Github releases for new versions, but it provides a “slim” version that performs a bunch of additional downloads the first time it is run and a “fat” version with everything already included. I’d like to be able to provide both as an option for downstream use, however they have different checksums. I found a couple of Spack issues addressing this question (e.g. #9910 and #11206). The most straightforward solution seems to be to use a `when` clause along with a `variant` in the `version` directive, that way whenever a variant is present (e.g. `+all`) Spack uses the fat version checksum and when it is absent it uses the slim one. Combined with version-specific URL’s or a `url_for_version` function, this seems to work ok. The problem is that if you try to install both it tries to use the cached version of the other. However, if you delete the cache the checksum fails.

An example of the two `version` directives:

```nextflow
version('21.04.1', sha256='840ca394237e0f4d9f34642ff77c0ac92361319bcc9d9441f3d99f7b6d48ae7d', expand=False, when='~all')
version('21.04.1', sha256='566deaf7533a2484d09f6520c677b31eff983d59b82c0816f9fe36b2886c768d', expand=False, when='+all')

variant('all', default=True, description='Use all-inclusive tarball requiring no additional downloads')

def url_for_version(self, version):
    if "+all" in self.spec:
        return f"https://github.com/nextflow-io/nextflow/releases/download/v{version}/nextflow-{version}-all"
    else:
        return f"https://github.com/nextflow-io/nextflow/releases/download/v{version}/nextflow"
```

### Steps to reproduce the issue

```console
$ spack install nextflow@21.04.1+all
$ spack clean -ds nextflow
$ spack install nextflow@21.04.1~all
```

### Error Message

```console
spack.fetch_strategy.ChecksumError: sha256 checksum failed for /tmp/andrew.birnberg/spack-stage/spack-stage-nextflow-21.04.1-65uot5cmhrin7zsbhwa3h7l5klbki3qj/nextflow
    Expected 566deaf7533a2484d09f6520c677b31eff983d59b82c0816f9fe36b2886c768d but got 840ca394237e0f4d9f34642ff77c0ac92361319bcc9d9441f3d99f7b6d48ae7d
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
```
* **Spack:** 0.16.2-3306-69d69cbc79
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** original
```
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment] 2021-06-29 10:28
I think this is more a request for a feature that we have been wanting since a long time, since currently we don't support a `when=` with the `version` and `variant` directives. I agree that this would be welcome, and it will indeed simplify a lot of packages, like for instance `cuda`.

**Comment by birnbera** [comment] 2021-06-30 05:52
@alalazo, my mistake. I thought I had seen examples of this scattered throughout Spack issues and comments indicating that this was the preferred way to handle version specific downloads. Do you have any suggestions about the best way to accomplish this before `when` clauses are implemented for versions?

**Comment by alalazo** [comment] 2023-06-07 10:42
Duplicate of #11206

**Closed as not planned** 2023-06-07 10:43 UTC
Labels: feature
