### ISSUE TITLE
Spack-in-container: Stripped libraries cannot be used for linking

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#18030] opened 2020-08-12 20:23 UTC
I am using Spack in a container. I follow the instructions in the manual, except that I am using Ubuntu 20.04 instead of 18.04 as base image. The standard generated Dockerfile contains the lines

```Dockerfile
# Strip all the binaries
RUN find -L /opt/view/* -type f -exec readlink -f '{}' \; | \
    xargs file -i | \
    grep 'charset=binary' | \
    grep 'x-executable\|x-archive\|x-sharedlib' | \
    awk -F: '{print $1}' | xargs strip -s
```

in the builder.

When I later use the resulting image, I cannot link against Spack-generated `*.a` libraries. The linker complains that they have no symbol table (and suggests to run `ranlib`). When I look at the object files in such a library, `nm` says they contain no symbols.

I find that archives need to be stripped with `strip` (without the `-s` option) for things to work:

```Dockerfile
RUN find -L /opt/view/* -type f -exec readlink -f '{}' \; | \
    xargs file -i | \
    grep 'charset=binary' | \
    tee >(grep 'x-executable\|x-sharedlib' | \
          awk -F: '{print $1}' | xargs strip --strip-all) \
        >(grep 'x-archive' | \
          awk -F: '{print $1}' | xargs strip) \
        > /dev/null
```

**Comment by haampie** [comment] 2020-08-12 22:19
I think the point of the multistage build is to have one part where you build, and one part where you generate a final set of binaries meant for just running the binaries, with the complete build environment gone.

In case you need to link to your libs in the second part, maybe don't even consider a multistage build at all? Or at least drop stripping of binaries?

**Comment by eschnett** [comment] 2020-08-12 23:20
For me, the end product is an image where people can modify, build, and run my application. Thus the Spack-generated libraries are part of the end product.

If you only want binaries, then you might as well not copy the `*.a` files; binaries won't need them.

A multi-stage build still makes sense because it gets rid of intermediate packages.

**Comment by alalazo** [comment] 2020-08-13 04:58
@eschnett Marking this as a question and not a bug and closing. You can opt-out of stripping libraries by adding a:
```yaml
strip: false
```
attribute to your environment. See [here](https://spack.readthedocs.io/en/latest/containers.html#environment-configuration) for a list of options you can use to fine tune container generation. Feel free to reopen if you think there are additional issues to be revised.

**Comment by eschnett** [comment] 2020-08-13 15:15
Stripping `*.a` libraries is fine, but Spack is too aggressive in stripping them. The result are `*.a` libraries that are useless – they cannot be used for linking. I was reporting a bug, not asking a question.

I see three options:
- Strip `*.a` libraries less aggressively, so that they remain useful for linking (my suggestion above)
- Delete `*.a` libraries instead of stripping them if you only want to retain binaries (which saves even more space)
- Don't strip `*.a` libraries at all (since the description says "strip binaries")

**Comment by eschnett** [comment] 2020-08-15 22:17
@alalazo Can you re-open this ticket?

**Comment by alalazo** [comment] 2020-08-17 06:33
> Can you re-open this ticket?

Sure. I mean you can also reopen it as the original poster, can't you? Let me know if the UI prevents you to do that and I'll reopen it for you.

Can you clarify:
> Stripping *.a libraries is fine, but Spack is too aggressive in stripping them. The result are *.a libraries that are useless – they cannot be used for linking. I was reporting a bug, not asking a question.

I still don't see where the bug is. If you use `strip: false` do you still have issues? If not I'd see this either as a question or as a feature request - but definitely not a bug. I also don't get this comment:

> Don't strip *.a libraries at all (since the description says "strip binaries")

I think there's a mismatch on terminology here: a shared or a static library is a "binary" file whereas an application is a "binary executable" (or just an "executable"). If there are parts of the docs that are not clear, can you link them here? For what is worth in the long term we already plan to go with option two and deal with it using `spack gc`, but that requires Spack to have a finer understanding of the linking model.

**Comment by eschnett** [comment] 2020-08-17 19:25
I cannot reopen. It seems I can still edit the title (how strange), but otherwise I can only open a new issue, unsubscribe from this issue, and leave a comment.

The thing I call a "bug" is the following: When I run `strip` on a `*.a` archive, then I expect to still be able use the library for linking afterwards. This is probably what people commonly mean by "stripping" in the Unix sense: Remove debug information, but keep things in a working state otherwise. I assume many Linux distributions routinely strip their libraries and executables to save space.

However, Spack uses the `-s` option when stripping, which is very aggressive, and leaves the `*.a` library in a broken state. It cannot be used for linking any more. The linker reports errors. It's not a "library" in the Unix sense any more since the linker cannot resolve any names any more. It does not make sense to ship a `*.a` libraries after using `strip -s`. The file is useless.

What is fine is running plain `strip` on a `*.a` library. This works, and that's the remedy I suggest.

For the record: I assume that `strip: false` works (I haven't tested), but that's not what I want. I want to save disk space, and I want my executables and libraries stripped. But you can't do that with the `-s` option, because it does something weird to libraries that breaks them. I am asking Spack to not use the `-s` option for `*.a` libraries.

I agree that using `strip: false` is a work-around, but that doesn't mean the current behaviour is not a bug.

**Comment by eschnett** [comment] 2020-08-25 20:09
Can you remove the `question` tag? I don't have a question; I reported a bug.

**Closed as completed** 2023-04-13 15:09 UTC
Labels: bug, containers
