### ISSUE TITLE
Clingo choosing an old version for a root spec

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#28829] opened 2022-02-08 13:24 UTC
### Steps to reproduce

Note really a bug per-se, but in certain situations I have found that clingo was choosing a very old version of a package even though the preferred version could be concretized fine if I specify the version manually.

Here is a list of commands to reproduce the problem, using the `spack.yaml` attached (renammed `spack.yaml.txt` because github doesn't support yaml files, apparently), which provides external packages for the platform I'm on.

```
git clone https://github.com/spack/spack.git
git clone https://github.com/mochi-hpc/mochi-spack-packages.git
. spack/share/spack/setup-env.sh
spack env create myenv spack.yaml
spack env activate myenv
spack repo add mochi-spack-packages
spack add hepnos
spack concretize -f
```

This leads to spack concretizing `hepnos@0.4.6`, even though it has newer vesions (0.5 and 0.6).

Doing the same thing _without_ the spack.yaml file leads to spack correctly concretizing `hepnos@0.6`, even though I don't see anything in that file that could affect this. Also using `spack add hepnos@0.6` with the spack.yaml file works perfectly fine.

Something to note is that the hepnos package in question has pretty different dependencies after version 0.4.6. So I suspect that clingo finds is "easier" (whatever that means for clingo) to build an older version given what's available on the system, but (1) I can't figure out what could have made clingo make that choice, given the external packages listed, and (2) I think that's not a behavior we want (if it can concretize the preferred version of any root or dependency, I think it should do that).

[spack.yaml.txt](https://github.com/spack/spack/files/8024097/spack.yaml.txt)

### Error message

N/A

### Information on your system

* **Spack:** 0.17.1-1106-c1b51d6
* **Python:** 2.7.5
* **Platform:** linux-centos7-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by mdorier** [comment] 2022-02-08 13:34
I should add that this is not the only situation in which clingo decided to build old versions of roots or dependencies. I have a CI process building a set of other packages daily on another platform, using another spack.yaml specific to that platform, and I realized recently that spack had been building old versions of many packages for weeks. I had to work around that by searching for the preferred version in my bash script using `echo $(spack info $1 | grep -A1 Preferred | tail -n1 | awk '{ print $1 }')` and forcing that version to be used.

**Comment by mwkrentel** [comment] 2022-02-08 16:26
@mdorier In #28820, I requested that spack should at least warn of these sorts of choices.
I think warning is not hard, so maybe that could be added relatively quickly.

**Comment by mdorier** [comment] 2022-02-08 16:30
> @mdorier In #28820, I requested that spack should at least warn of these sorts of choices. I think warning is not hard, so maybe that could be added relatively quickly.

I would say that warning is not enough. As I mentioned, I had CI pipelines building old versions for weeks, and I would have missed the warnings since I check the logs only if builds fail.

**Comment by white238** [comment] 2022-02-18 05:45
I am having this problem as well. I am requesting `scr@3.0rc2~shared` in the `packages` section of an environment file.  If I remove `~shared` it will concretize the correct version otherwise I end up with `scr@2.0.0` which is very undesirable. Especially since I am trying to see if Axom works with the new release of SCR.

`spack -e some_env solve axom+scr` produces:

```
==> Best of 4 considered solutions.
==> Optimization Criteria:
  Priority  Criterion                                            Installed  ToBuild
  1         number of packages to build (vs. reuse)                      -        0
  2         deprecated versions used                                     0        0
  3         version weight                                               0        0
  4         number of non-default variants (roots)                       0        0
  5         preferred providers for roots                                0        0
  6         default values of variants not being used (roots)            0        1
  7         number of non-default variants (non-roots)                   0        0
  8         preferred providers (non-roots)                              0        0
  9         compiler mismatches                                          0        0
  10        OS mismatches                                                0        0
  11        non-preferred OS's                                           0        0
  12        version badness                                              0       23
  13        default values of variants not being used (non-roots)        0       16
  14        non-preferred compilers                                      0        0
  15        target mismatches                                            0        0
  16        non-preferred targets                                        0     -780

axom@0.6.1%clang@10.0.0+cpp14~cuda~debug~devtools+examples+fortran+hdf5~ipo+lua~mfem+mpi+openmp~python+raja+scr+shared+tools+umpire build_type=RelWithDebInfo patches=68a3ae8 arch=linux-rhel7-ivybridge
    ^cmake@3.14.5%clang@10.0.0~doc+ncurses+openssl+ownlibs~qt build_type=Release patches=1c54004 arch=linux-rhel7-ivybridge
    ^conduit@0.7.2%clang@10.0.0~adios+blt_find_mpi~doc~doxygen+fortran+hdf5+hdf5_compat~ipo+mpi+parmetis~python~shared~silo~test~zfp build_type=RelWithDebInfo patches=89d1829 arch=linux-rhel7-ivybridge
        ^hdf5@1.8.22%clang@10.0.0~cxx~fortran~hl~ipo~java~mpi~shared~szip~threadsafe+tools api=default build_type=RelWithDebInfo arch=linux-rhel7-ivybridge
            ^pkgconf@1.8.0%clang@10.0.0 arch=linux-rhel7-ivybridge
            ^zlib@1.2.7%clang@10.0.0+optimize+pic+shared arch=linux-rhel7-ivybridge
        ^metis@5.1.0%clang@10.0.0~gdb~int64~real64+shared build_type=Release patches=4991da9 arch=linux-rhel7-ivybridge
        ^mvapich2@2.3%clang@10.0.0~alloca~cuda~debug+regcache+wrapperrpath ch3_rank_bits=32 fabrics=mrail file_systems=auto process_managers=slurm threads=multiple arch=linux-rhel7-ivybridge
        ^parmetis@4.0.3%clang@10.0.0~gdb~int64~ipo+shared build_type=RelWithDebInfo patches=4f89253,50ed208,704b84f arch=linux-rhel7-ivybridge
    ^dtcmp@1.1.4%clang@10.0.0+shared arch=linux-rhel7-ivybridge
        ^lwgrp@1.0.5%clang@10.0.0+shared arch=linux-rhel7-ivybridge
    ^kvtree@main%clang@10.0.0~ipo+mpi+shared build_type=RelWithDebInfo file_lock=FLOCK arch=linux-rhel7-ivybridge
    ^lua@5.3.5%clang@10.0.0~pcfile+shared fetcher=curl arch=linux-rhel7-ivybridge
        ^curl@7.80.0%clang@10.0.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2~nghttp2 tls=openssl arch=linux-rhel7-ivybridge
            ^openssl@1.1.1m%clang@10.0.0~docs certs=system arch=linux-rhel7-ivybridge
                ^perl@5.16.3%clang@10.0.0+cpanm+shared+threads patches=0eac10e,3bbd7d6 arch=linux-rhel7-ivybridge
        ^ncurses@6.2%clang@10.0.0~symlinks+termlib abi=none arch=linux-rhel7-ivybridge
        ^readline@6.2%clang@10.0.0 arch=linux-rhel7-ivybridge
        ^unzip@6.0%clang@10.0.0 arch=linux-rhel7-ivybridge
    ^raja@0.14.0%clang@10.0.0~cuda~examples~exercises~ipo+openmp~rocm~shared~tests build_type=RelWithDebInfo arch=linux-rhel7-ivybridge
        ^blt@0.4.1%clang@10.0.0 arch=linux-rhel7-ivybridge
        ^camp@0.2.2%clang@10.0.0~cuda~ipo~rocm~tests build_type=RelWithDebInfo arch=linux-rhel7-ivybridge
    ^scr@2.0.0%clang@10.0.0+dtcmp+fortran~ipo+libyogrt async_api=NONE build_type=RelWithDebInfo cache_base=/dev/shm cntl_base=/dev/shm copy_config=none file_lock=FLOCK resource_manager=SLURM scr_config=scr.conf arch=linux-rhel7-ivybridge
        ^libyogrt@1.24%clang@10.0.0~static scheduler=slurm arch=linux-rhel7-ivybridge
        ^pdsh@2.33%clang@10.0.0+ssh+static_modules arch=linux-rhel7-ivybridge
    ^umpire@6.0.0%clang@10.0.0+c~cuda~deviceconst~examples~fortran~ipo~numa+openmp~rocm~shared build_type=RelWithDebInfo tests=none arch=linux-rhel7-ivybridge
```

**Comment by tgamblin** [comment] 2022-02-18 06:34
FWIW, @white238's case can be reproduced by comparing these:

```

```

**Comment by tgamblin** [comment] 2022-02-18 06:36
Oops accidentally closed -- sorry!

These two concretizations are worth comparing the scores on:

```console
spack solve axom+scr
spack solve axom ^scr~shared
```

@alalazo can you take a look at this?

**Comment by alalazo** [comment] 2022-02-22 14:16
@tgamblin Just saw your comment above. I'll take a look at this asap.

**Comment by alalazo** [comment] 2022-03-01 16:43
@white238 I started having a look at this. Concretizing both `axom+scr` and `axom ^scr` gives the following consistent result for me:

<details>

<summary>`axom+scr` and `axom ^scr`</summary>

```
oszc45b  axom@0.6.1%gcc@9.3.0+cpp14~cuda~debug~devtools+examples+fortran+hdf5~ipo+lua~mfem+mpi+openmp~python+raja+scr+shared+tools+umpire build_type=RelWithDebInfo patches=68a3ae8 arch=linux-ubuntu20.04-icelake
e32qi6r      ^cmake@3.22.2%gcc@9.3.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-ubuntu20.04-icelake
wevrxpl          ^ncurses@6.2%gcc@9.3.0~symlinks+termlib abi=none arch=linux-ubuntu20.04-icelake
5u2zrji              ^pkgconf@1.8.0%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
spy577h          ^openssl@1.1.1m%gcc@9.3.0~docs certs=system arch=linux-ubuntu20.04-icelake
5fknwft              ^perl@5.34.0%gcc@9.3.0+cpanm+shared+threads arch=linux-ubuntu20.04-icelake
bca2ndl                  ^berkeley-db@18.1.40%gcc@9.3.0+cxx~docs+stl patches=b231fcc arch=linux-ubuntu20.04-icelake
m6msmwh                  ^bzip2@1.0.8%gcc@9.3.0~debug~pic+shared arch=linux-ubuntu20.04-icelake
t3p6jzn                      ^diffutils@3.8%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
ueh6r5u                          ^libiconv@1.16%gcc@9.3.0 libs=shared,static arch=linux-ubuntu20.04-icelake
q5oia5x                  ^gdbm@1.19%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
23mubk3                      ^readline@8.1%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
ech7q6s                  ^zlib@1.2.11%gcc@9.3.0+optimize+pic+shared arch=linux-ubuntu20.04-icelake
caw3aoy      ^conduit@0.8.2%gcc@9.3.0~adios+blt_find_mpi~doc~doxygen+fortran+hdf5+hdf5_compat~ipo+mpi+parmetis~python+shared~silo+test~zfp build_type=RelWithDebInfo arch=linux-ubuntu20.04-icelake
pdmgobx          ^hdf5@1.8.22%gcc@9.3.0~cxx~fortran~hl~ipo~java+mpi+shared~szip~threadsafe+tools api=default build_type=RelWithDebInfo arch=linux-ubuntu20.04-icelake
msml4e7              ^openmpi@4.1.2%gcc@9.3.0~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker~pmi~pmix+romio~singularity~sqlite3+static~thread_multiple+vt+wrapper-rpath fabrics=none schedulers=none arch=linux-ubuntu20.04-icelake
cjbql7h                  ^hwloc@2.7.0%gcc@9.3.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~opencl+pci~rocm+shared arch=linux-ubuntu20.04-icelake
f3ujejk                      ^libpciaccess@0.16%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
w2merzt                          ^libtool@2.4.6%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
qal57j2                              ^m4@1.4.19%gcc@9.3.0+sigsegv patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-icelake
basfgy2                                  ^libsigsegv@2.13%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
rh46vik                          ^util-macros@1.19.3%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
umfo2pm                      ^libxml2@2.9.12%gcc@9.3.0~python arch=linux-ubuntu20.04-icelake
essg37l                          ^xz@5.2.5%gcc@9.3.0~pic libs=shared,static arch=linux-ubuntu20.04-icelake
slmazbc                  ^libevent@2.1.12%gcc@9.3.0+openssl arch=linux-ubuntu20.04-icelake
2semoyz                  ^numactl@2.0.14%gcc@9.3.0 patches=4e1d78c,62fc8a8,ff37630 arch=linux-ubuntu20.04-icelake
6ago2g2                      ^autoconf@2.69%gcc@9.3.0 patches=35c4492,7793209,a49dd5b arch=linux-ubuntu20.04-icelake
7cfs7rx                      ^automake@1.16.5%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
l2d3u54                  ^openssh@8.8p1%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
7elophq                      ^libedit@3.1-20210216%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
hemcf6d          ^metis@5.1.0%gcc@9.3.0~gdb~int64~real64+shared build_type=Release patches=4991da9,b1225da arch=linux-ubuntu20.04-icelake
5iqxvcl          ^parmetis@4.0.3%gcc@9.3.0~gdb~int64~ipo+shared build_type=RelWithDebInfo patches=4f89253,50ed208,704b84f arch=linux-ubuntu20.04-icelake
o73eghd      ^dtcmp@1.1.4%gcc@9.3.0+shared arch=linux-ubuntu20.04-icelake
ujs6how          ^lwgrp@1.0.5%gcc@9.3.0+shared arch=linux-ubuntu20.04-icelake
grsjhlr      ^kvtree@main%gcc@9.3.0~ipo+mpi+shared build_type=RelWithDebInfo file_lock=FLOCK arch=linux-ubuntu20.04-icelake
hpv3o26      ^lua@5.3.5%gcc@9.3.0~pcfile+shared fetcher=curl arch=linux-ubuntu20.04-icelake
lngbe46          ^curl@7.81.0%gcc@9.3.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2~nghttp2 tls=openssl arch=linux-ubuntu20.04-icelake
cyjmsey          ^unzip@6.0%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
mvire2a      ^raja@0.14.0%gcc@9.3.0~cuda+examples+exercises~ipo+openmp~rocm+shared~tests build_type=RelWithDebInfo arch=linux-ubuntu20.04-icelake
x5mv67s          ^blt@0.4.1%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
ttnwzbe          ^camp@0.2.2%gcc@9.3.0~cuda~ipo~rocm~tests build_type=RelWithDebInfo arch=linux-ubuntu20.04-icelake
a7u4em7      ^scr@3.0rc2%gcc@9.3.0+bbapi~bbapi_fallback~dw+examples+fortran~ipo+libyogrt+pdsh+shared+tests build_type=RelWithDebInfo cache_base=/dev/shm cntl_base=/dev/shm copy_config=none file_lock=FLOCK resource_manager=SLURM scr_config=scr.conf arch=linux-ubuntu20.04-icelake
4eo2oez          ^axl@0.5.0%gcc@9.3.0+bbapi~bbapi_fallback~dw~ipo+shared async_api=daemon build_type=RelWithDebInfo arch=linux-ubuntu20.04-icelake
koznun5          ^er@0.1.0%gcc@9.3.0~ipo+shared build_type=RelWithDebInfo arch=linux-ubuntu20.04-icelake
rpshkie              ^rankstr@0.1.0%gcc@9.3.0~ipo+shared build_type=RelWithDebInfo arch=linux-ubuntu20.04-icelake
mmg5uj6              ^redset@0.1.0%gcc@9.3.0~ipo+shared build_type=RelWithDebInfo arch=linux-ubuntu20.04-icelake
yq6liug              ^shuffile@0.1.0%gcc@9.3.0~ipo+shared build_type=RelWithDebInfo arch=linux-ubuntu20.04-icelake
at32k6f          ^libyogrt@1.27%gcc@9.3.0~static scheduler=slurm arch=linux-ubuntu20.04-icelake
w2sxjlq              ^slurm@21-08-1-1%gcc@9.3.0~gtk~hdf5~hwloc~mariadb~pmix+readline~restd sysconfdir=PREFIX/etc arch=linux-ubuntu20.04-icelake
dgvsjji                  ^glib@2.70.4%gcc@9.3.0~libmount patches=8547954 tracing=none arch=linux-ubuntu20.04-icelake
l6ucc3w                      ^gettext@0.21%gcc@9.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu20.04-icelake
qi2zebt                          ^tar@1.34%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
w2grorr                      ^libffi@3.4.2%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
o6q522c                      ^meson@0.61.2%gcc@9.3.0 patches=aa6c50d arch=linux-ubuntu20.04-icelake
mtxlgbn                          ^ninja@1.10.2%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
a36rd2l                              ^python@3.9.10%gcc@9.3.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-ubuntu20.04-icelake
eqsolym                                  ^expat@2.4.6%gcc@9.3.0+libbsd arch=linux-ubuntu20.04-icelake
oz6j2gg                                      ^libbsd@0.11.5%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
awhhr3w                                          ^libmd@1.0.4%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
cjxgaz5                                  ^sqlite@3.37.2%gcc@9.3.0+column_metadata+dynamic_extensions+fts~functions+rtree arch=linux-ubuntu20.04-icelake
7hj2n5k                                  ^util-linux-uuid@2.37.4%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
vghdyum                          ^py-pip@21.3.1%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
udwix74                          ^py-setuptools@59.4.0%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
3evel63                              ^py-wheel@0.37.0%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
lo3pihi                      ^pcre@8.45%gcc@9.3.0~jit+multibyte+utf arch=linux-ubuntu20.04-icelake
4ba22j6                  ^json-c@0.15%gcc@9.3.0~ipo build_type=RelWithDebInfo arch=linux-ubuntu20.04-icelake
umklwmi                  ^lz4@1.9.3%gcc@9.3.0 libs=shared,static arch=linux-ubuntu20.04-icelake
hhariwe                  ^munge@0.5.14%gcc@9.3.0 localstatedir=PREFIX/var arch=linux-ubuntu20.04-icelake
eshuxyi                      ^libgcrypt@1.9.4%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
rjboppt                          ^libgpg-error@1.43%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
mqcxk3y                              ^gawk@5.1.1%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
2wwjypa                                  ^gmp@6.2.1%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
emcreaw                                  ^mpfr@4.1.0%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
4lovbhf                                      ^autoconf-archive@2019.01.06%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
odnf7rk                                      ^texinfo@6.5%gcc@9.3.0 patches=12f6edb,1732115 arch=linux-ubuntu20.04-icelake
ne3spup          ^pdsh@2.31%gcc@9.3.0+ssh+static_modules arch=linux-ubuntu20.04-icelake
mlzof73          ^spath@0.1.0%gcc@9.3.0~ipo+mpi+shared build_type=RelWithDebInfo arch=linux-ubuntu20.04-icelake
maazopz      ^umpire@6.0.0%gcc@9.3.0+c~cuda~deviceconst+examples~fortran~ipo~numa+openmp~rocm+shared build_type=RelWithDebInfo tests=none arch=linux-ubuntu20.04-icelake
```

</details>

Using `scr~shared` changes the hash since `~shared` is not the default value for that variant, but `scr` is still at version `3.0rc2`. I'll try to concretize with `clang` next to see if that matters.

**Comment by alalazo** [comment] 2022-03-01 16:57
Tried with `%clang` too and cannot find a combination that on my platform:

* **Spack:** 0.17.1-1378-8cefe38b0e
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

results in a version of `scr` that is not `3.0rc2`. @white238 Can you share your `spack.yaml` or another reproducer?

**Comment by alalazo** [comment] 2022-03-01 17:08
@mdorier I just tried to reproduce your issue on the same platform as in https://github.com/spack/spack/issues/28829#issuecomment-1055650704 and couldn't reproduce it too. What I get is `hepnos@0.6`. I'll attach [spack.yaml.txt](https://github.com/spack/spack/files/8163448/spack.yaml.txt) and [spack.lock.txt](https://github.com/spack/spack/files/8163449/spack.lock.txt) for reference.

**Comment by mdorier** [comment] 2022-03-01 17:42
@alalazo did you try with the spack.yaml file that I attached? I also get `hepnos@0.6` with an empty environment. The problem seems to come specifically from the spack.yaml file that I attached.

**Comment by alalazo** [comment] 2022-03-01 17:50
@mdorier 

> Doing the same thing without the spack.yaml file leads to spack correctly concretizing hepnos@0.6, even though I don't see anything in that file that could affect this. Also using spack add hepnos@0.6 with the spack.yaml file works perfectly fine.

Ahem, I took a look at the `spack.yaml` and I see that there are 26 external specs registered as `buildable: false`. *That means Spack is forced to use those externals*. On my platform I cannot even concretize because of conflicts with those externals set, until I removed most of them. 

There's another thing that is worth pointing out. Looking into your repository I see this pattern used in a few places:
```python
from spack.pkg.builtin.mercury import Mercury

class Mercury(Mercury):
    ...
```
which seems *at least* very bad practice to me (not sure when name binding happens and if the base class is correct). It would be safer to:
```python
from spack.pkg.builtin.mercury import Mercury as BuiltinMercury

class Mercury(BuiltinMercury):
    ...
```

**Comment by alalazo** [comment] 2022-03-01 17:57
~For some reason the spec creating issues is, for me, `cmake@3.20.3`. I am still trying to understand what triggers the issue.~ Some architectural details (like the OS) are pinned. I need to try remove those.

EDIT: Removing `arch=...` everywhere I can reproduce concretizing to v0.4.6 The issue are external specs, I'll try to pin down which are "problematic"

**Comment by mdorier** [comment] 2022-03-01 18:22
Thanks for the tips on inheriting from builtin packages. I'm not the author of those packages so I never noticed they were setup like that.

**Comment by alalazo** [comment] 2022-03-01 18:26
@mdorier The issue with your environment is that you have:
```yaml
   openssl:
      buildable: false
      version: []
      target: []
      compiler: []
      providers: {}
      externals:
      - spec: openssl@1.0.2k arch=linux-centos7-x86_64
        prefix: /usr
```
registered, which is deprecated. Given the current policy in `clingo` to avoid deprecated versions unless strictly necessary to satisfy the constraint imposed by the user, then you'll get the first version which doesn't need `openssl` (v0.4.6). Note that `clingo` cannot build a newer one because it is forbid to by `buildable: false`.

**Comment by mdorier** [comment] 2022-03-01 18:34
I see, that's not a cause I would I found by myself. Maybe spack could warn when this kind of thing happens?

**Comment by alalazo** [comment] 2022-03-01 21:00
> Maybe spack could warn when this kind of thing happens?

In this case it's not that easy. We warn the user if we *actually* use a deprecated version, but how can we warn the user about anything we *might* have used but we don't?

More to the point of this environment: the request is `hepnos` and clingo gave back a concretized version of `hepnos` so everything is good with Spack. With a more specific request, like `hepnos@0.6:` Spack would warn the user that it had to bring in a deprecated version of `openssl` to satisfy it.

**Comment by mdorier** [comment] 2022-03-01 21:03
I see. Since this weird concretization happened within a CI script that captures the logs and only displays them in case of failure, when I forced it to use hepnos@0.6 the warning must have gotten lost in logs.

**Comment by alalazo** [comment] 2022-03-02 08:07
What we might do more easily is add a new audit so that:
```console
$ spack audit configs
```
Is able to report if any external with `buildable: false` is at a deprecated version. This would still require user intervention to be diagnosed, but can be helpful to point out potential issues.

**Comment by mdorier** [comment] 2022-03-02 09:56
It could be useful to have a field in the YAML file that would say "allow deprecated versions of this package as if they were not deprecated". I saw the weird concretization problem on multiple platforms and I now realize that on each of them, an external openssl was specified, so that could have been the cause every time. For external packages, it would make sense to disable deprecation.

**Comment by alalazo** [comment] 2022-03-02 10:08
> For external packages, it would make sense to disable deprecation.

That opens to the opposite issue: why was a deprecated version being used without a warning to the user? I don't think we should try to special case externals even more than they are now. It's software that is outside of the control of Spack, so it's difficult to ask Spack for consistency/optimality in the DAG and at the same time introduce manual constraints that work against it.[^1] I see for instance why a user would need externals to interface with proprietary libraries etc. but what was the purpose here to pin `zlib@1.2.7` and have it `buildable:false`?

[^1]: Honestly, I'd really like if in the long term we could detect externals *with their dependencies* and put records in a DB, rather than specifying them in `packages.yaml`.

**Comment by alalazo** [comment] 2023-07-10 12:54
Marking this one as not a bug, since it has been checked extensively and the trigger for using old versions of some packages was to avoid external specs with deprecated versions. See https://github.com/spack/spack/issues/28829#issuecomment-1055731350

**Comment by white238** [comment] 2023-07-10 18:01
I just hit this again today where clingo is choosing a version 7 back. I can reproduce this pretty easily but was forced to lock the desired version in the `spack.yaml` with `require`.

**Comment by alalazo** [comment] 2023-07-10 18:08
@white238 Is that also a case with a deprecated versions in `packages.yaml`? Or is the trigger different?

**Comment by white238** [comment] 2023-07-10 19:21
Honestly not sure how to figure that out.

**Comment by alalazo** [comment] 2023-07-10 19:42
If you have a minimal reproducer, I can try to make sense of the weights from clingo using `spack solve`

**Comment by white238** [comment] 2023-07-10 23:37
I tracked this down to a change in raja/umpire where they are now requiring a newer CMake.

Just in general, this quietly turning off or downgrading versions of important libraries scares me. I guess the answer is to lock down versions in the environment file by the `require` functionality.

**Comment by alalazo** [comment] 2023-07-12 11:45
> I guess the answer is to lock down versions in the environment file by the require functionality.

:+1: 

Closing this issue, since `clingo` is optimizing as designed (so there's no actionable point here, or bug to fix).

**Closed as not planned by alalazo** 2023-07-12 11:45 UTC
Labels: bug, concretization, user-experience, not-a-bug

**Comment by tgamblin** [comment] 2023-07-13 07:00
@alalazo: I do think the actionable thing is to inform the user *why* we made a decision.  I think that'll be much easier actually with @becker33's #34363.  I think the same technique he is using there could be used to explain choices as well as errors.  The other fix would be highlighting anything that deviates from latest/default/required in `spack spec` output.  e.g. we could make the "weird" decisions red.

I'm inclined to leave this to #34363, but I do think we should do a better job of explaining surprises.

**Comment by alalazo** [comment] 2023-07-13 08:35
> The other fix would be highlighting anything that deviates from latest/default/required in spack spec output. e.g. we could make the "weird" decisions red.

I agree with this. I'll open a feature request later.

**Comment by white238** [comment] 2023-07-13 16:40
> @alalazo: I do think the actionable thing is to inform the user _why_ we made a decision. I think that'll be much easier actually with @becker33's #34363. I think the same technique he is using there could be used to explain choices as well as errors. The other fix would be highlighting anything that deviates from latest/default/required in `spack spec` output. e.g. we could make the "weird" decisions red.
> 
> I'm inclined to leave this to #34363, but I do think we should do a better job of explaining surprises.

Can i plus this up like a 1000?
