### ISSUE TITLE
Installation issue: cp2k

### ISSUE THREAD

**Issue by sjpb** [LLNL/spack#17791] opened 2020-07-30 14:17 UTC
### Steps to reproduce the issue

```console
$ spack spec -I cp2k+openmp%gcc@7.3.0 ^openmpi/ziwdzwh ^fftw/jryxrru ^openblas/wr2gbc4

Input spec
--------------------------------
 -   cp2k%gcc@7.3.0+openmp
[+]      ^fftw@3.3.8%gcc@7.3.0+mpi~openmp~pfft_patches precision=double,float arch=linux-centos7-broadwell
[+]          ^openmpi@4.0.3%gcc@7.3.0~atomics~cuda~cxx~cxx_exceptions+gpfs~java~legacylaunchers~memchecker~pmi+runpath~sqlite3+static~thread_multiple+vt fabrics=ucx schedulers=auto arch=linux-centos7-broadwell
[+]              ^hwloc@1.11.11%gcc@7.3.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml+pci+shared arch=linux-centos7-broadwell
[+]                  ^libpciaccess@0.13.5%gcc@7.3.0 arch=linux-centos7-broadwell
[+]                  ^libxml2@2.9.10%gcc@7.3.0~python arch=linux-centos7-broadwell
[+]                      ^libiconv@1.16%gcc@7.3.0 arch=linux-centos7-broadwell
[+]                      ^xz@5.2.5%gcc@7.3.0 arch=linux-centos7-broadwell
[+]                      ^zlib@1.2.11%gcc@7.3.0+optimize+pic+shared arch=linux-centos7-broadwell
[+]                  ^numactl@2.0.12%gcc@7.3.0 arch=linux-centos7-broadwell
[+]              ^ucx@1.8.0%gcc@7.3.0~assertions~cuda~debug~gdrcopy~java~logging~optimizations~parameter_checking+pic+thread_multiple cuda_arch=none arch=linux-centos7-broadwell
[+]                  ^rdma-core@20%gcc@7.3.0 build_type=RelWithDebInfo arch=linux-centos7-broadwell
[+]                      ^libnl@3.3.0%gcc@7.3.0 arch=linux-centos7-broadwell
[+]      ^openblas@0.3.9%gcc@7.3.0~consistent_fpcsr~ilp64+pic+shared threads=none arch=linux-centos7-broadwell
[+]      ^openmpi@4.0.3%gcc@7.3.0~atomics~cuda~cxx~cxx_exceptions+gpfs~java~legacylaunchers~memchecker~pmi+runpath~sqlite3+static~thread_multiple+vt fabrics=ucx schedulers=auto arch=linux-centos7-broadwell
[+]          ^hwloc@1.11.11%gcc@7.3.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml+pci+shared arch=linux-centos7-broadwell
[+]              ^libpciaccess@0.13.5%gcc@7.3.0 arch=linux-centos7-broadwell
[+]              ^libxml2@2.9.10%gcc@7.3.0~python arch=linux-centos7-broadwell
[+]                  ^libiconv@1.16%gcc@7.3.0 arch=linux-centos7-broadwell
[+]                  ^xz@5.2.5%gcc@7.3.0 arch=linux-centos7-broadwell
[+]                  ^zlib@1.2.11%gcc@7.3.0+optimize+pic+shared arch=linux-centos7-broadwell
[+]              ^numactl@2.0.12%gcc@7.3.0 arch=linux-centos7-broadwell
[+]          ^ucx@1.8.0%gcc@7.3.0~assertions~cuda~debug~gdrcopy~java~logging~optimizations~parameter_checking+pic+thread_multiple cuda_arch=none arch=linux-centos7-broadwell
[+]              ^rdma-core@20%gcc@7.3.0 build_type=RelWithDebInfo arch=linux-centos7-broadwell
[+]                  ^libnl@3.3.0%gcc@7.3.0 arch=linux-centos7-broadwell

Concretized
--------------------------------
==> Error: Multiple providers found for 'blas': ['intel-mkl@2020.1.217%gcc@7.3.0~ilp64+shared threads=none arch=linux-centos7-broadwell', 'openblas@0.3.9%gcc@7.3.0~consistent_fpcsr~ilp64+pic+shared threads=none arch=linux-centos7-broadwell']

...
```

### Information on your system

* **Spack:** 0.14.2-1247-6ddc077
* **Python:** 3.7.6
* **Platform:** linux-centos7-broadwell

`packages.yaml`:

```yaml
packages:
  # slurm:
  #   paths:
  #     slurm@18.08.8: /opt/ohpc/admin/pmix/
  #   buildable: False
  openmpi:
    modules:
      openmpi@3.1.0: openmpi3/3.1.0
```

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

@dev-zero

**Comment by dev-zero** [comment] 2020-07-30 15:40
I'd say this is a duplicate of #4107 (and others) and not really specific to CP2K. Can you please try with one of the workarounds over there?

**Closed as completed** 2020-08-23 17:13 UTC
Labels: duplicate, build-error, virtual-dependencies
