### ISSUE TITLE
Specifying a site-scope compiler does not add the compiler to the more highly prioritized /linux/compilers.yaml file that is initially created

### ISSUE THREAD

**Issue by dmentock** [LLNL/spack#30922] opened 2022-05-30 11:23 UTC
### Steps to reproduce

```
% spack install py-seaborn
[+] /opt/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-10.3.0/py-seaborn-0.11.2-tsnevnnxuoyqliywmfjbtwmmvjizlbjj
% spack compiler find
==> Found no new compilers
==> Compilers are defined in the following files:
    /opt/spack/etc/spack/linux/compilers.yaml  /opt/spack/etc/spack/linux/compilers.yaml
% spack install gcc@12.1.0
% spack load gcc@12.1.0
% spack compiler find --scope=site
==> Added 1 new compiler to /opt/spack/etc/spack/compilers.yaml
    gcc@12.1.0
==> Compilers are defined in the following files:
    /opt/spack/etc/spack/compilers.yaml  /opt/spack/etc/spack/linux/compilers.yaml  /opt/spack/etc/spack/linux/compilers.yaml
% spack install py-seaborn
[+] /opt/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-10.3.0/py-seaborn-0.11.2-tsnevnnxuoyqliywmfjbtwmmvjizlbjj

```

### Error message

`gcc@12.1.0` is currently set as the preferred version for the `gcc` compiler, so I would like to be able to use it as the default compiler for every package without having to explicitly specify the version every time. Adding the newly installed `gcc@12.1.0` to the list of compilers with `spack compiler find --scope=site` creates a new file in `/opt/spack/etc/spack/compilers.yaml` with only one compiler entry for `gcc@12.1.0`:

```
% cat /opt/spack/etc/spack/compilers.yaml  
compilers:
- compiler:
    spec: gcc@12.1.0
    paths:
      cc: /opt/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-10.3.0/gcc-12.1.0-hxmogndjq46ymejnei2c546qkhwqt7mw/bin/gcc
      cxx: /opt/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-10.3.0/gcc-12.1.0-hxmogndjq46ymejnei2c546qkhwqt7mw/bin/g++
      f77: /opt/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-10.3.0/gcc-12.1.0-hxmogndjq46ymejnei2c546qkhwqt7mw/bin/gfortran
      fc: /opt/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-10.3.0/gcc-12.1.0-hxmogndjq46ymejnei2c546qkhwqt7mw/bin/gfortran
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

However, the initially created `/opt/spack/etc/spack/linux/compilers.yaml` file, which does not contain the new compiler, is prioritized over the abovementioned `/opt/spack/etc/spack/compilers.yaml` file:

```
% cat /opt/spack/etc/spack/linux/compilers.yaml
compilers:
- compiler:
    spec: gcc@10.3.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@8.4.0
    paths:
      cc: /usr/bin/gcc-8
      cxx: null
      f77: /usr/bin/gfortran-8
      fc: /usr/bin/gfortran-8
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@9.4.0
    paths:
      cc: /usr/bin/gcc-9
      cxx: /usr/bin/g++-9
      f77: /usr/bin/gfortran-9
      fc: /usr/bin/gfortran-9
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```
This causes spack to still use `gcc@10.3.0` as the default compiler in the example specified in the **Steps to reproduce** section. Removing the `/opt/spack/etc/spack/linux/compilers.yaml` file finally causes spack to use the desired `gcc@12.1.0` compiler instead, but ideally I would like to add the `gcc@12.1.0` compiler to the `/opt/spack/etc/spack/linux/compilers.yaml` file as the highest priority compiler in the first place.

On top of that, the bootstrap compiler in `~/.spack/bootstrap/config/linux/compilers.yaml` file is also not being updated and continues using `gcc@10.3.0` by default.

EDIT: I have also tried using the `spack compiler find` command without specifying the scope, which adds the `12.1.0` compiler to the `/opt/spack/etc/spack/linux/compilers.yaml` file. However, this causes spack to prioritize `gcc@10.3.0` instead of `12.1.0`, in spite of `12.1.0` being listed as the preferred version in the gcc package.

### Information on your system

* **Spack:** 0.18.0.dev0 (6170c270a5f859b6112ead7039dec2d3458556f4)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by dmentock** [comment] 2022-05-31 21:37
I found a solution many other packages use where they assign the variables by using `os.environ['HDF5_LIB_DIR'] = spec['hdf5'].prefix.lib`

**Comment by scheibelp** [comment] 2022-05-31 22:44
A few questions:

* Does `gcc@12.1.0` appear when you run `spack config blame compilers` from the command line?
* Can you explicitly specify `spack spec libelf %gcc@12.1.0`?

> However, this causes spack to prioritize gcc@10.3.0 instead of 12.1.0, in spite of 12.1.0 being listed as the preferred version in the gcc package.

I think you mean here that if you `spack edit gcc`, that you set `12.1.0` as `preferred` (or it already was that). Note this doesn't have much effect on what compiler version Spack uses to install other packages. For that, you generally have to set it as a preference in `packages.yaml`. That being said, if `spack config blame compilers` shows 12.1.0, then Spack should prefer that over 10.3.0 (it prefers newer compiler versions automatically).

**Comment by dmentock** [comment] 2022-06-01 10:47
- `gcc@12.1.0` is the first entry I get when I run `spack config blame compilers` on my current setup, where all of my compilers are stored in the `/opt/spack/etc/spack/compilers.yaml` file:

```
% spack config blame compilers
---                                     compilers:
/opt/spack/etc/spack/compilers.yaml:2   - compiler:
/opt/spack/etc/spack/compilers.yaml:3       spec: gcc@12.1.0
/opt/spack/etc/spack/compilers.yaml:4       paths:
/opt/spack/etc/spack/compilers.yaml:5         cc: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-10.3.0/gcc-12.1.0-woaaa3llrd4t64weowfbyfycgnzfbuvc/bin/gcc
/opt/spack/etc/spack/compilers.yaml:6         cxx: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-10.3.0/gcc-12.1.0-woaaa3llrd4t64weowfbyfycgnzfbuvc/bin/g++
/opt/spack/etc/spack/compilers.yaml:7         f77: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-10.3.0/gcc-12.1.0-woaaa3llrd4t64weowfbyfycgnzfbuvc/bin/gfortran
/opt/spack/etc/spack/compilers.yaml:8         fc: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-10.3.0/gcc-12.1.0-woaaa3llrd4t64weowfbyfycgnzfbuvc/bin/gfortran
/opt/spack/etc/spack/compilers.yaml:9       flags: {}
/opt/spack/etc/spack/compilers.yaml:10      operating_system: ubuntu20.04
/opt/spack/etc/spack/compilers.yaml:11      target: x86_64
/opt/spack/etc/spack/compilers.yaml:12      modules: []
/opt/spack/etc/spack/compilers.yaml:13      environment: {}
/opt/spack/etc/spack/compilers.yaml:14      extra_rpaths: []
/opt/spack/etc/spack/compilers.yaml:15  - compiler:
/opt/spack/etc/spack/compilers.yaml:16      spec: dpcpp@2022.1.0
/opt/spack/etc/spack/compilers.yaml:17      paths:
/opt/spack/etc/spack/compilers.yaml:18        cc: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-12.1.0/intel-oneapi-compilers-2022.1.0-c26o5grrfkmnwx5iydjvmpbgbl33cpte/compiler/2022.1.0/linux/bin/icx
/opt/spack/etc/spack/compilers.yaml:19        cxx: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-12.1.0/intel-oneapi-compilers-2022.1.0-c26o5grrfkmnwx5iydjvmpbgbl33cpte/compiler/2022.1.0/linux/bin/dpcpp
/opt/spack/etc/spack/compilers.yaml:20        f77: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-12.1.0/intel-oneapi-compilers-2022.1.0-c26o5grrfkmnwx5iydjvmpbgbl33cpte/compiler/2022.1.0/linux/bin/ifx
/opt/spack/etc/spack/compilers.yaml:21        fc: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-12.1.0/intel-oneapi-compilers-2022.1.0-c26o5grrfkmnwx5iydjvmpbgbl33cpte/compiler/2022.1.0/linux/bin/ifx
/opt/spack/etc/spack/compilers.yaml:22      flags: {}
/opt/spack/etc/spack/compilers.yaml:23      operating_system: ubuntu20.04
/opt/spack/etc/spack/compilers.yaml:24      target: x86_64
/opt/spack/etc/spack/compilers.yaml:25      modules: []
/opt/spack/etc/spack/compilers.yaml:26      environment: {}
/opt/spack/etc/spack/compilers.yaml:27      extra_rpaths: []
/opt/spack/etc/spack/compilers.yaml:28  - compiler:
/opt/spack/etc/spack/compilers.yaml:29      spec: intel@2021.6.0
/opt/spack/etc/spack/compilers.yaml:30      paths:
/opt/spack/etc/spack/compilers.yaml:31        cc: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-12.1.0/intel-oneapi-compilers-2022.1.0-c26o5grrfkmnwx5iydjvmpbgbl33cpte/compiler/2022.1.0/linux/bin/intel64/icc
/opt/spack/etc/spack/compilers.yaml:32        cxx: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-12.1.0/intel-oneapi-compilers-2022.1.0-c26o5grrfkmnwx5iydjvmpbgbl33cpte/compiler/2022.1.0/linux/bin/intel64/icpc
/opt/spack/etc/spack/compilers.yaml:33        f77: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-12.1.0/intel-oneapi-compilers-2022.1.0-c26o5grrfkmnwx5iydjvmpbgbl33cpte/compiler/2022.1.0/linux/bin/intel64/ifort
/opt/spack/etc/spack/compilers.yaml:34        fc: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-12.1.0/intel-oneapi-compilers-2022.1.0-c26o5grrfkmnwx5iydjvmpbgbl33cpte/compiler/2022.1.0/linux/bin/intel64/ifort
/opt/spack/etc/spack/compilers.yaml:35      flags: {}
/opt/spack/etc/spack/compilers.yaml:36      operating_system: ubuntu20.04
/opt/spack/etc/spack/compilers.yaml:37      target: x86_64
/opt/spack/etc/spack/compilers.yaml:38      modules: []
/opt/spack/etc/spack/compilers.yaml:39      environment: {}
/opt/spack/etc/spack/compilers.yaml:40      extra_rpaths: []
/opt/spack/etc/spack/compilers.yaml:41  - compiler:
/opt/spack/etc/spack/compilers.yaml:42      spec: oneapi@2022.1.0
/opt/spack/etc/spack/compilers.yaml:43      paths:
/opt/spack/etc/spack/compilers.yaml:44        cc: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-12.1.0/intel-oneapi-compilers-2022.1.0-c26o5grrfkmnwx5iydjvmpbgbl33cpte/compiler/2022.1.0/linux/bin/icx
/opt/spack/etc/spack/compilers.yaml:45        cxx: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-12.1.0/intel-oneapi-compilers-2022.1.0-c26o5grrfkmnwx5iydjvmpbgbl33cpte/compiler/2022.1.0/linux/bin/icpx
/opt/spack/etc/spack/compilers.yaml:46        f77: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-12.1.0/intel-oneapi-compilers-2022.1.0-c26o5grrfkmnwx5iydjvmpbgbl33cpte/compiler/2022.1.0/linux/bin/ifx
/opt/spack/etc/spack/compilers.yaml:47        fc: /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-12.1.0/intel-oneapi-compilers-2022.1.0-c26o5grrfkmnwx5iydjvmpbgbl33cpte/compiler/2022.1.0/linux/bin/ifx
/opt/spack/etc/spack/compilers.yaml:48      flags: {}
/opt/spack/etc/spack/compilers.yaml:49      operating_system: ubuntu20.04
/opt/spack/etc/spack/compilers.yaml:50      target: x86_64
/opt/spack/etc/spack/compilers.yaml:51      modules: []
/opt/spack/etc/spack/compilers.yaml:52      environment: {}
/opt/spack/etc/spack/compilers.yaml:53      extra_rpaths: []
/opt/spack/etc/spack/compilers.yaml:54  - compiler:
/opt/spack/etc/spack/compilers.yaml:55      spec: gcc@10.3.0
/opt/spack/etc/spack/compilers.yaml:56      paths:
/opt/spack/etc/spack/compilers.yaml:57        cc: /usr/bin/gcc
/opt/spack/etc/spack/compilers.yaml:58        cxx: /usr/bin/g++
/opt/spack/etc/spack/compilers.yaml:59        f77: /usr/bin/gfortran
/opt/spack/etc/spack/compilers.yaml:60        fc: /usr/bin/gfortran
/opt/spack/etc/spack/compilers.yaml:61      flags: {}
/opt/spack/etc/spack/compilers.yaml:62      operating_system: ubuntu20.04
/opt/spack/etc/spack/compilers.yaml:63      target: x86_64
/opt/spack/etc/spack/compilers.yaml:64      modules: []
/opt/spack/etc/spack/compilers.yaml:65      environment: {}
/opt/spack/etc/spack/compilers.yaml:66      extra_rpaths: []
/opt/spack/etc/spack/compilers.yaml:67  - compiler:
/opt/spack/etc/spack/compilers.yaml:68      spec: gcc@8.4.0
/opt/spack/etc/spack/compilers.yaml:69      paths:
/opt/spack/etc/spack/compilers.yaml:70        cc: /usr/bin/gcc-8
/opt/spack/etc/spack/compilers.yaml:71        cxx: null
/opt/spack/etc/spack/compilers.yaml:72        f77: /usr/bin/gfortran-8
/opt/spack/etc/spack/compilers.yaml:73        fc: /usr/bin/gfortran-8
/opt/spack/etc/spack/compilers.yaml:74      flags: {}
/opt/spack/etc/spack/compilers.yaml:75      operating_system: ubuntu20.04
/opt/spack/etc/spack/compilers.yaml:76      target: x86_64
/opt/spack/etc/spack/compilers.yaml:77      modules: []
/opt/spack/etc/spack/compilers.yaml:78      environment: {}
/opt/spack/etc/spack/compilers.yaml:79      extra_rpaths: []
/opt/spack/etc/spack/compilers.yaml:80  - compiler:
/opt/spack/etc/spack/compilers.yaml:81      spec: gcc@9.4.0
/opt/spack/etc/spack/compilers.yaml:82      paths:
/opt/spack/etc/spack/compilers.yaml:83        cc: /usr/bin/gcc-9
/opt/spack/etc/spack/compilers.yaml:84        cxx: /usr/bin/g++-9
/opt/spack/etc/spack/compilers.yaml:85        f77: /usr/bin/gfortran-9
/opt/spack/etc/spack/compilers.yaml:86        fc: /usr/bin/gfortran-9
/opt/spack/etc/spack/compilers.yaml:87      flags: {}
/opt/spack/etc/spack/compilers.yaml:88      operating_system: ubuntu20.04
/opt/spack/etc/spack/compilers.yaml:89      target: x86_64
/opt/spack/etc/spack/compilers.yaml:90      modules: []
/opt/spack/etc/spack/compilers.yaml:91      environment: {}
/opt/spack/etc/spack/compilers.yaml:92      extra_rpaths: []
```

- `spack spec libelf%gcc@12.1.0` returns `libelf@0.8.13%gcc@12.1.0 arch=linux-ubuntu20.04-zen2`, and `spack install libelf%gcc@12.1.0` installs `libelf` with the desired gcc version.

With this setup, issuing `spack spec libelf` and `spack install libelf` also show the correct `gcc@12.1.0` spec and install libelf with the correct `gcc@12.1.0` version. However, testing it on the `py-seaborn` package, which has no compiler preference entry in the `packages.yaml` file, `spack install py-seaborn` still uses `gcc@10.3.0` by default if `%gcc@12.1.0` is not explicitly specified. `spack spec py-seaborn` also return all packages with the `gcc@10.3.0` compiler, whereas `spack spec py-seaborn%gcc@12.1.0` returns the spec with `gcc@12.1.0`

**Comment by scheibelp** [comment] 2022-06-01 18:08
Additional questions/notes:

* Can you also post the output of `spack config blame packages`?
  * In particular it looks like you are now getting different results for libelf in https://github.com/spack/spack/issues/30922#issuecomment-1143441602 vs. in the beginning of the thread (so I'm curious if you changed the preferences for just libelf)
* Can you post the output of `spack spec py-seaborn`?
  * At least one of the dependencies (`py-numpy`) has constraints on which `gcc` is used to compile (although I don't think that particular case is the issue here)
* Note that preferences are not *guaranteed* to apply: this is true for implicit preferences - e.g. I mentioned that Spack generally prefers newer compilers - as well as for explicit preferences (i.e. those manually written in `packages.yaml`
  * So ultimately, specifying the compiler explicitly like `spack speec foo%gcc@12.1.0` may be the way to proceed with this (it may be of interest though to dig into why the concretizer chooses an older gcc version without coaxing)
  * If you are concretizing a set of packages together and want to force the use of a particular compiler, you can place that constraint on one of the user specs
  * The environment compilers section can override other sections (so concretizations ignore the existence of all compilers except for those defined in the environment)

**Comment by dmentock** [comment] 2022-06-01 21:08
- here is my `spack config blame packages` output:
```
% spack config blame packages
---                                             packages:
/opt/spack/etc/spack/defaults/packages.yaml:17    all:
/opt/spack/etc/spack/defaults/packages.yaml:18      compiler: [gcc, intel, pgi, clang, xl, nag, fj, aocc]
/opt/spack/etc/spack/defaults/packages.yaml:19      providers:
/opt/spack/etc/spack/defaults/packages.yaml:20        awk: [gawk]
/opt/spack/etc/spack/defaults/packages.yaml:21        blas: [openblas, amdblis]
/opt/spack/etc/spack/defaults/packages.yaml:22        D: [ldc]
/opt/spack/etc/spack/defaults/packages.yaml:23        daal: [intel-daal]
/opt/spack/etc/spack/defaults/packages.yaml:24        elf: [elfutils]
/opt/spack/etc/spack/defaults/packages.yaml:25        fftw-api: [fftw, amdfftw]
/opt/spack/etc/spack/defaults/packages.yaml:26        flame: [libflame, amdlibflame]
/opt/spack/etc/spack/defaults/packages.yaml:27        fuse: [libfuse]
/opt/spack/etc/spack/defaults/packages.yaml:28        gl: [mesa+opengl, mesa18, opengl]
/opt/spack/etc/spack/defaults/packages.yaml:29        glu: [mesa-glu, openglu]
/opt/spack/etc/spack/defaults/packages.yaml:30        glx: [mesa+glx, mesa18+glx, opengl]
/opt/spack/etc/spack/defaults/packages.yaml:31        golang: [gcc]
/opt/spack/etc/spack/defaults/packages.yaml:32        iconv: [libiconv]
/opt/spack/etc/spack/defaults/packages.yaml:33        ipp: [intel-ipp]
/opt/spack/etc/spack/defaults/packages.yaml:34        java: [openjdk, jdk, ibm-java]
/opt/spack/etc/spack/defaults/packages.yaml:35        jpeg: [libjpeg-turbo, libjpeg]
/opt/spack/etc/spack/defaults/packages.yaml:36        lapack: [openblas, amdlibflame]
/opt/spack/etc/spack/defaults/packages.yaml:37        libllvm: [llvm, llvm-amdgpu]
/opt/spack/etc/spack/defaults/packages.yaml:38        lua-lang: [lua, lua-luajit-openresty, lua-luajit]
/opt/spack/etc/spack/defaults/packages.yaml:39        luajit: [lua-luajit-openresty, lua-luajit]
/opt/spack/etc/spack/defaults/packages.yaml:40        mariadb-client: [mariadb-c-client, mariadb]
/opt/spack/etc/spack/defaults/packages.yaml:41        mkl: [intel-mkl]
/opt/spack/etc/spack/defaults/packages.yaml:42        mpe: [mpe2]
/opt/spack/etc/spack/defaults/packages.yaml:43        mpi: [openmpi, mpich]
/opt/spack/etc/spack/defaults/packages.yaml:44        mysql-client: [mysql, mariadb-c-client]
/opt/spack/etc/spack/defaults/packages.yaml:45        opencl: [pocl]
/opt/spack/etc/spack/defaults/packages.yaml:46        onedal: [intel-oneapi-dal]
/opt/spack/etc/spack/defaults/packages.yaml:47        osmesa: [mesa+osmesa, mesa18+osmesa]
/opt/spack/etc/spack/defaults/packages.yaml:48        pbs: [openpbs, torque]
/opt/spack/etc/spack/defaults/packages.yaml:49        pil: [py-pillow]
/opt/spack/etc/spack/defaults/packages.yaml:50        pkgconfig: [pkgconf, pkg-config]
/opt/spack/etc/spack/defaults/packages.yaml:51        rpc: [libtirpc]
/opt/spack/etc/spack/defaults/packages.yaml:52        scalapack: [netlib-scalapack, amdscalapack]
/opt/spack/etc/spack/defaults/packages.yaml:53        sycl: [hipsycl]
/opt/spack/etc/spack/defaults/packages.yaml:54        szip: [libaec, libszip]
/opt/spack/etc/spack/defaults/packages.yaml:55        tbb: [intel-tbb]
/opt/spack/etc/spack/defaults/packages.yaml:56        unwind: [libunwind]
/opt/spack/etc/spack/defaults/packages.yaml:57        uuid: [util-linux-uuid, libuuid]
/opt/spack/etc/spack/defaults/packages.yaml:58        xxd: [xxd-standalone, vim]
/opt/spack/etc/spack/defaults/packages.yaml:59        yacc: [bison, byacc]
/opt/spack/etc/spack/defaults/packages.yaml:60        ziglang: [zig]
/opt/spack/etc/spack/defaults/packages.yaml:61      permissions:
/opt/spack/etc/spack/defaults/packages.yaml:62        read: world
/opt/spack/etc/spack/defaults/packages.yaml:63        write: user
```
I did not change any preferences, the only difference is that as opposed to having two seperate `compiler.yaml` files in `/opt/spack/etc/spack/linux/compilers.yaml` and `/opt/spack/etc/spack/compilers.yaml` I now have all my compilers listed in `/opt/spack/etc/spack/compilers.yaml`.

- Here is my spack `spec py-seaborn` output
```
% spack spec py-seaborn
                Input spec
--------------------------------
py-seaborn

Concretized
--------------------------------
py-seaborn@0.11.2%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
    ^py-matplotlib@3.5.2%gcc@10.3.0~animation~fonts+image~latex~movies backend=agg arch=linux-ubuntu20.04-zen2
        ^freetype@2.11.1%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
            ^bzip2@1.0.8%gcc@10.3.0~debug~pic+shared arch=linux-ubuntu20.04-zen2
                ^diffutils@3.8%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
                    ^libiconv@1.16%gcc@10.3.0 libs=shared,static arch=linux-ubuntu20.04-zen2
            ^libpng@1.6.37%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
                ^zlib@1.2.12%gcc@10.3.0+optimize+pic+shared patches=0d38234 arch=linux-ubuntu20.04-zen2
            ^pkgconf@1.8.0%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
        ^py-certifi@2021.10.8%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
            ^py-pip@21.3.1%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
                ^python@3.9.12%gcc@10.3.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-ubuntu20.04-zen2
                    ^expat@2.4.8%gcc@10.3.0+libbsd arch=linux-ubuntu20.04-zen2
                        ^libbsd@0.11.5%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
                            ^libmd@1.0.4%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
                    ^gdbm@1.19%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
                        ^readline@8.1%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
                            ^ncurses@6.2%gcc@10.3.0~symlinks+termlib abi=none arch=linux-ubuntu20.04-zen2
                    ^gettext@0.21%gcc@10.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu20.04-zen2
                        ^libxml2@2.9.13%gcc@10.3.0~python arch=linux-ubuntu20.04-zen2
                            ^xz@5.2.5%gcc@10.3.0~pic libs=shared,static arch=linux-ubuntu20.04-zen2
                        ^tar@1.34%gcc@10.3.0 zip=pigz arch=linux-ubuntu20.04-zen2
                            ^pigz@2.7%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
                            ^zstd@1.5.2%gcc@10.3.0+programs compression=none libs=shared,static arch=linux-ubuntu20.04-zen2
                    ^libffi@3.4.2%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
                    ^openssl@1.1.1o%gcc@10.3.0~docs~shared certs=system arch=linux-ubuntu20.04-zen2
                        ^perl@5.34.1%gcc@10.3.0+cpanm+shared+threads arch=linux-ubuntu20.04-zen2
                            ^berkeley-db@18.1.40%gcc@10.3.0+cxx~docs+stl patches=b231fcc arch=linux-ubuntu20.04-zen2
                    ^sqlite@3.38.5%gcc@10.3.0+column_metadata+dynamic_extensions+fts~functions+rtree arch=linux-ubuntu20.04-zen2
                    ^util-linux-uuid@2.37.4%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
            ^py-setuptools@59.4.0%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
                ^py-wheel@0.37.0%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
        ^py-cycler@0.11.0%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
        ^py-fonttools@4.31.2%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
        ^py-kiwisolver@1.3.2%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
            ^py-cppy@1.1.0%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
        ^py-numpy@1.22.4%gcc@10.3.0+blas+lapack patches=873745d arch=linux-ubuntu20.04-zen2
            ^openblas@0.3.20%gcc@10.3.0~bignuma~consistent_fpcsr~ilp64+locking+pic+shared symbol_suffix=none threads=none arch=linux-ubuntu20.04-zen2
            ^py-cython@0.29.30%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
        ^py-packaging@21.3%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
            ^py-pyparsing@3.0.6%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
        ^py-pillow@9.0.0%gcc@10.3.0~freetype~imagequant+jpeg~jpeg2000~lcms~tiff~webp~webpmux~xcb+zlib arch=linux-ubuntu20.04-zen2
            ^libjpeg-turbo@2.1.3%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
                ^cmake@3.23.1%gcc@10.3.0~doc+ncurses+ownlibs~qt build_type=Release arch=linux-ubuntu20.04-zen2
                ^nasm@2.15.05%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
        ^py-python-dateutil@2.8.2%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
            ^py-setuptools-scm@6.3.2%gcc@10.3.0+toml arch=linux-ubuntu20.04-zen2
                ^py-tomli@1.2.2%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
            ^py-six@1.16.0%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
        ^py-setuptools-scm-git-archive@1.1%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
        ^qhull@2020.2%gcc@10.3.0~ipo build_type=RelWithDebInfo arch=linux-ubuntu20.04-zen2
    ^py-pandas@1.4.2%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
        ^py-bottleneck@1.3.2%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
        ^py-numexpr@2.7.3%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
        ^py-pytz@2021.3%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
    ^py-scipy@1.8.1%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
        ^py-pybind11@2.8.1%gcc@10.3.0~ipo build_type=RelWithDebInfo arch=linux-ubuntu20.04-zen2
            ^ninja@1.10.2%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
        ^py-pythran@0.11.0%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
            ^py-beniget@0.4.1%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
                ^py-gast@0.5.3%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
            ^py-ply@3.11%gcc@10.3.0 arch=linux-ubuntu20.04-zen2
```

I think for now we will just specify the compiler priority in our packages.yaml as
```
packages:
  all:
    compiler: [gcc@12.1.0, gcc, intel, pgi, clang, xl, nag, fj, aocc]
```

since there does not seem to be a better solution.

**Comment by scheibelp** [comment] 2022-06-01 21:51
This is strange: if I check out the tip of Spack (5faa927fe6b6708e54e8a05dfca5189a64910af7 as of now) inside of the `ubuntu:latest` docker image (`Image ID: d13c942271d6`) and do

```
spack -C fake-compiler/ spec py-seaborn
```

such that

```
cat fake-compiler/compilers.yaml 
compilers:
- compiler:
    spec: gcc@12.1.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: null
      fc: null
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment:
      unset: [SPACK_TARGET_ARGS]
    extra_rpaths: []
```

then the concretization chooses `%gcc@12.1.0` (in my case there's a choice between this and `gcc@9.3.0`); I don't have to set a preference (i.e. default package preferences). Do you get the same problem if you follow that (you'd have to undo the `packages.yaml` changes to test that out)?

Thanks for posting the spec: there is at least one package (`py-numpy`) in that DAG which may constrain `%gcc` to versions before 11, but not for the version selected in your output (I wanted to confirm that though).

**Comment by dmentock** [comment] 2022-06-02 15:00
I checked out the commit you posted, installed `gcc@12.1.0` and created the `fake_compiler/compilers.yaml` file you posted, but `spack -C fake-compiler/ spec py-seaborn` still returns `gcc@10.3.0` as the preferred compiler. Changing the `packages.yaml` file as following did not have an effect either:

```
packages:
  all:
    compiler: [gcc@12.1.0, gcc, intel, pgi, clang, xl, nag, fj, aocc]
    providers:
        ...
```
the `py-seaborn` package does not seem to have a problem with using the gcc@12.1.0 compiler since specifying `spack spec py-seaborn%gcc@12.1.0` returns the according spec with no problems.

**Comment by alalazo** [comment] 2023-04-07 10:19
I can't reproduce this one:
![Screenshot from 2023-04-07 12-18-56](https://user-images.githubusercontent.com/4199709/230592142-8b64810d-ebdc-4402-b511-858bf44b83fd.png)

Closing, but feel free to reopen if you want to continue investigating the issue.

**Closed as not planned by alalazo** 2023-04-07 10:19 UTC
Labels: bug, compilers, unreproducible
